#+TITLE:  Grymoire SED Guide   
#+AUTHOR: PilJin Kwon
#+EMAIL:  piljin.kwon@gmail.com

#+DESCRIPTION: 이 문서는 Grymoire sed Guide 의 한국어 버전입니다.
#+KEYWORDS:    grymoire, sed, regex, regular expression, regex, gnu sed
#+LANGUAGE:    ko
#+OPTIONS:     H:4
#+OPTIONS:     toc:2
#+TOC:         tables

* Grymoire SED Guide
자동으로 파일을 수정하는 특수한 편집기 혹은 파일 내용을 변경하려면 ~sed~ 를 사용합니다.

유닉스 도구 상자에는 진정한 ‘일꾼’ 역할을 처리하는 프로그램이 몇 가지 있습니다. 이들 프로그램은 간단한 용도로 사용하기 쉬우면서 복잡한 작업까지 수행할 수 있는 풍부한 명령어 세트를 갖추고 있습니다. 프로그램이 가진 복잡한 잠재력 때문에 간단한 기능을 활용하는 것을 주저하지 마시기 바랍니다. 우선 간단한 개념을 다루고 나중엔 고급 주제를 소개하겠습니다.

이 글을 처음 작성할 당시(1994년) 대부분의 sed 버전은 스크립트에 주석을 넣을 수 없었습니다. 참고로 ‘#’ 문자로 시작하는 줄은 주석문입니다. 최신 버전의 sed는 줄 끝 주석도 잘 지원합니다.

이를 이해할 수 있는 방법은 구식 “클래식” 버전이 GNU, FreeBSD 및 Solaris 버전의 sed 기반이란 점입니다. 제가 어떠한 환경에서 작업했는지 이해하는 데 도움되도록 [[https://docs.oracle.com/cd/E26502_01/html/E29030/sed-1b.html#scrolltoc][Sun/Oracle의 sed(1) 매뉴얼 페이지]]를 소개합니다.


* The Awful Truth about sed
~sed~ 는 최고의 스트림 편집기입니다. 이말이 이상하게 들린다면 파이프를 통해 흐르는 개울물을 상상하시기 바랍니다. 아, 파이프에 있으면 개울물을 볼 순 없겠죠. 흐르는 물에 비유하려니 이런 결과가 나왔습니다. 문학 작품을 원하시면 제임스 조이스를 읽으시기 바랍니다.

어쨌든 sed는 매우 놀라운 유틸리티입니다. 안타깝게도 사람들 대부분은 sed의 진정한 위력을 제대로 알지 못합니다. 언어는 아주 간단하지만 설명서는 형편없습니다. Solaris의 sed 온라인 매뉴얼 페이지는 전체 5페이지인데 그 중 2페이지는 운영 중에 발생할 수 있는 34가지 오류에 대한 설명으로 채워져 있습니다. 기능 설명에 할애한 공간만큼 오류 설명에 많은 공간을 할애한 프로그램의 학습 곡선은 가파를 수밖에 없습니다.

하지만, 걱정하지 않아도 됩니다! sed를 이해하지 못하는 건 여러분의 잘못이 아닙니다. 제가 sed에 대해 철저히 다룰 겁니다. 다만 제가 배운 순서대로 기능을 설명합니다. 저도 한 번에 모든 것을 배운 건 아니니까요. 여러분도 그럴 필요 없습니다.


* The essential command: s for substitution
sed엔 여러 명령어가 있지만 대부분의 사람들은 주로 대체 명령어 ~s~ (/substitute/)만 배웁니다. 대체 명령어는 정규 표현식과 일치한 부분을 새로운 값으로 바꿉니다. 간단한 예로 “old” 파일의 “day” 를 “new” 파일의 “night” 로 바꾸는 경우입니다:

#+begin_src 
sed s/day/night/ <old >new
#+end_src

또는 다른 방법(유닉스 초보자를 위한):

#+begin_src bash
sed s/day/night/ old >new
#+end_src

그리고 이를 테스트해 볼 분들은:

#+begin_src bash
echo day | sed s/day/night/
#+end_src

위의 명령 모두 “night” 를 출력합니다.

참고로 이 예제는 따옴표가 필요하지 않기 때문에 인수를 따옴표로 묶지 않았습니다. 따옴표에 관한 저의 이전 [[https://www.grymoire.com/Unix/Quote.html][튜토리얼]]을 읽으셨다면 왜 따옴표가 필요없는지 이해하실 겁니다. 하지만 따옴표를 사용할 것을 권장합니다. 만약 명령어에 메타 문자가 포함되면 *따옴표 사용은 필수* 입니다. 확실치 않더라도 따옴표를 사용하는 것은 좋은 습관이며 저는 앞으로 “모범 사례” 를 강조하기 위해 예제에 따옴표를 사용할 것입니다.

강한 따옴표(단일 따옴표)를 사용하면 다음과 같습니다.

#+begin_src bash
sed ‘s/day/night/’ <old >new
#+end_src

sed 편집기는 "사용자가 지시한대로 변경한다!" 는 점을 강조합니다. 따라서 다음 명령을 실행하면

#+begin_src bash
echo Sunday | sed ‘s/day/night/’
#+end_src

sed는 입력에서 “day” 문자열을 찾았으므로 “Sunnight” 를 출력합니다.

또 다른 중요한 개념은 sed는 "행 단위로 작동한다!" 는 점입니다. 다음과 같은 입력 파일을 가정합니다.

#+begin_example
one two three, one two three
four three two one
one hundred
#+end_example

그리고 다음 명령어를 사용했다고 가정합니다.

#+begin_src bash
sed ‘s/one/ONE/’ <file
#+end_src

출력은 다음과 같습니다.

#+begin_example
ONE two three, one two three
four three two ONE
ONE hundred
#+end_example

이 명령은 각 줄의 “one” 을 *한 번씩* “ONE” 으로 변경했다는 점에 유의합니다. 첫 번째 줄은 “one” 이 두 번 등장했지만 첫 번째 나타난 것만 변경했습니다!! 이것이 바로 sed의 기본 동작 방식입니다. 이와 다른 결과를 원하시면 사용 가능한 옵션 중 일부를 사용해야 합니다. 나중에 자세히 설명하겠습니다.

계속 진행하겠습니다.

/substitute/ 명령어는 네 부분으로 구성됩니다:

- s :: 대체 명령어
- /../../ :: 구분 기호 또는 구분자
- one :: 정규 표현식 검색 패턴
- ONE :: 대체 문자열

(정규 표현식) 검색 패턴은 구분 기호 왼쪽에 대체 문자열은 오른쪽에 위치합니다.

지금까지 [[https://www.grymoire.com/Unix/Quote.html][따옴표 사용법]]과 [[https://www.grymoire.com/Unix/Regular.html][정규 표현식]]을 다루었습니다. 이것이 /substitute/ 명령어를 배우는 데 필요한 노력의 90%를 차지합니다. 다른 말로 여러분은 sed의 가장 빈번한 사용법의 90%를 이미 알고 있는 셈입니다. 앞으로 sed 전문가가 되려면 알아야 할 몇 가지 세부 사항이 좀 더 있습니다. (이제 겨우 1절을 마쳤습니다. 앞으로 다룰 섹션은 63개밖에 남지 않습니다. :-) 


* The slash as a delimiter
's' 뒤의 문자는 구분자(구분 기호)입니다. 관례적으로 슬래시 문자를 사용하는데 이는 ed, more, vi에서 사용하는 기본 구분자입니다. 하지만 원하는 어떤 문자든 설정할 수 있습니다.

슬래시 문자가 많이 포함된 경로명 예를 들어,  ~/usr/local/bin~ 을 ~/common/bin~ 으로 변경하려면 다음과 같이 백슬래시 문자로 모든 슬래시 문자를 이스케이프 처리해야 합니다.

#+begin_src bash
sed ‘s/\/usr\/local\/bin/\/common\/bin/’ <old >new
#+end_src

헉. 어떤 사람은 이것을 ‘피켓 펜스(/Picket Fence/)’ 라 부르는데 보기에 흉합니다. 구분자로 슬래시 문자 대신 밑줄 문자를 사용하면 읽기 훨씬 더 쉽습니다:

#+begin_src bash
sed ‘s_/usr/local/bin_/common/bin_’ <old >new
#+end_src

콜론을 사용하는 사람도 있습니다:

#+begin_src bash
sed ‘s:/usr/local/bin:/common/bin:’ <old >new
#+end_src

또 다른 사람은 “|” 문자를 사용합니다.

#+begin_src bash
sed ‘s|/usr/local/bin|/common/bin|’ <old >new
#+end_src

자신 마음에 드는 것으로 고릅니다. 검색할 문자열에 포함되지 않는 한 무엇이든 상관없습니다. 그리고 "구분자는 반드시 세 개가 필요하다" 는 점을 기억합니다. “/Unterminated `s' command/” 오류가 발생한다면 구분자 중 하나가 빠졌기 때문입니다.


* Using & as the matched string
때로는 패턴을 검색한 후 찾은 패턴 주변이나 근처에 괄호 같은 문자를 추가할 때가 있습니다. (고정) 문자열을 찾는 경우는 쉽게 수행할 수 있습니다:

#+begin_src bash
sed ‘s/abc/(abc)/’ <old >new
#+end_src

하지만, 무엇을 찾을지 모를 경우는 이 방법이 통하지 않습니다. 찾을 문자열이 무엇인지 모르는데 어떻게 치환 문자열에 넣을 수 있을까요? 해결책은 바로 특수 문자 “&” (/ampersand/)를 사용하는 것입니다. 이 문자는 "검색 일치한 패턴 자체" 를 의미합니다.

#+begin_src bash
sed ‘s/[a-z]*/(&)/’ <old >new
#+end_src

“&” 문자는 원하는만큼 사용할 수 있습니다. 따라서 패턴을 두 번 반복할 수 있습니다. 예를 들어, 첫 번째 숫자를 반복할 경우:

#+begin_src csh
% echo “123 abc” | sed ‘s/[0-9]*/& &/’
123 123 abc
#+end_src

예제를 약간 수정하겠습니다. sed는 첫 번째 문자와 일치시킬 때 가능한 한 탐욕적(/greedy/)으로 일치시킵니다. 이에 대해선 나중에 다루겠습니다. 탐욕적이지 않게(즉, 일치 범위를 제한) 처리하려면 일치 조건에 제한(/restrict/)을 부여합니다.

'[0-9]*' 패턴의 첫 번째 일치는 첫 번째 문자입니다. 0개 이상의 숫자와 일치하기 때문입니다. 따라서 입력이 “abc 123” 이면 출력은 변경되지 않습니다(글자 앞의 공백을 제외하면 말입니다). 숫자를 복제하는 좀 더 좋은 방법은 정확히 숫자만 일치하도록 만드는 것입니다:

#+begin_src bash
% echo “123 abc” | sed ‘s/[0-9][0-9]*/& &/’
123 123 abc
#+end_src

문자열 “abc” 는 정규 표현식과 일치하지 않으므로 변경되지 않습니다. 출력 결과에서 “abc” 를 제거하려면 정규 표현식을 확장해서 줄 나머지 부분을 일치시키고 “\(”, “\)” 및 “\1” 을 사용해서 표현식의 일부를 명시적으로 제외해야 합니다. 이에 대해선 다음에 다룰 예정입니다.


* Extended Regular Expressions
위의 스크립트의 또 다른 버전이 있습니다. “[0-9]*” 패턴은 0개 이상의 숫자와 일치합니다. “[0-9][0-9]*” 패턴은 (최소) 1개 이상의 숫자와 일치합니다. 또 다른 방법은 “+” 메타 문자로 “[0-9]+” 패턴을 사용합니다. 이렇게 확장 정규 표현식을 사용할 때 “+” 는 특수 문자로 작동합니다. 확장 정규 표현식은 좀 더 강력한 기능을 제공하지만 “+” 를 일반 문자로 취급하는 sed 스크립트는 오류가 발생합니다. 따라서 명령줄 옵션으로 이런 확장을 명시적으로 활성화해야 합니다.

GNU 버전의 sed는 “-r” (명령줄) 옵션으로 이 기능을 활성화합니다. 따라서 위의 내용은 다음과 같이 작성합니다.

#+begin_src bash
% echo “123 abc” | sed -r 's/[0-9]+/& &/'
123 123 abc
#+end_src

Mac OS X와 FreeBSD는 “-r” 옵션 대신 “-E” 를 사용합니다. 확장 정규 표현식에 대한 자세한 내용은 [[https://www.grymoire.com/Unix/Regular.html][정규 표현식]] 및 “-r” 명령줄 옵션 설명을 참조합니다.


* Using \1 to keep part of the pattern
[[https://www.grymoire.com/Unix/Regular.html][정규 표현식 튜토리얼]]에서 이미 “\("”, “\)” (부분 문자열) 및 “\1” (역참조) 사용법을 설명했습니다. 다시 정리하면 이스케이프 처리된 괄호(즉, 앞에 백슬래시가 붙은 괄호)는 정규 표현식으로 일치시킨 문자열의 일부를 기억합니다. 이를 활용해서 정규 표현식으로 일치시킨 문자열의 일부를 제외할 수 있습니다. “\1” 은 첫 번째 저장한 패턴이고 “\2” 는 두 번째 저장한 패턴입니다. Sed는 최대 9개 패턴을 저장할 수 있습니다.

줄의 첫 단어만 남기고 나머지를 삭제하려면 중요한 부분을 괄호로 묶어 부분 문자열로 기억합니다:

#+begin_src bash
sed 's/\([a-z]*\).*/\1/'
#+end_src

자세히 설명하겠습니다. 정규 표현식은 탐욕적(/greedy/)이라서 가능한 한 많이 일치시키려고 시도합니다. “[a-z]*” 패턴은 소문자 0개 이상을 일치시키며 가능한 한 많은 문자를 일치시키려 시도합니다. “.*” 패턴은 첫 번째로 일치한 문자를 0개 이상 일치시킵니다. 따라서 첫 번째 부분에서 연속된 소문자를 모두 가져가므로 두 번째 부분은 그 외의 모든 것을 일치시킵니다. 따라서 다음과 같이 입력하면

#+begin_src bash
echo abcd123 | sed ‘s/\([a-z]*\).*/\1/’
#+end_src

“abcd” 는 출력하고 숫자는 삭제합니다.

두 단어의 순서를 바꾸려면 두 개의 패턴으로 기억하고 출력 순서를 바꿉니다:

#+begin_src bash
sed 's/\([a-z]*\) \([a-z]*\)/\2 \1/'
#+end_src

여기서 기억된 두 패턴 사이의 공백에 유의합니다!! 이는 두 단어로 발견된 것을 확인하기 위함입니다. 하지만, 단어 하나만 발견되거나 문자가 없는 줄일 경우엔 아무런 효과가 없습니다. 다음 명령어로 단어에 최소한 하나의 문자가 포함되도록 제한할 수 있습니다.

#+begin_src bash
sed 's/\([a-z][a-z]*\) \([a-z][a-z]*\)/\2 \1/'
#+end_src

위와 같이 사용하거나 또는 확장 정규 표현식으로 최소 한 글자만 포함하도록 요구할 수 있습니다(확장 정규식에선 ‘(‘ 와 ’)' 앞에 백슬래시를 더이상 붙일 필요 없단 점에 유의합니다):

#+begin_src bash
sed -r ‘s/([a-z]+) ([a-z]+)/\2 \1/’       # GNU sed 사용 시
sed -E ‘s/([a-z]+) ([a-z]+)/\2 \1/’       # Apple Mac OS X 사용 시
#+end_src

또한 “\1” (역참조)은 반드시 치환 문자열(오른쪽)에 있을 필요는 없습니다. 검색 패턴(왼쪽)에 사용할 수 있습니다. 중복 단어를 제거하려면 다음을 시도합니다:

#+begin_src bash
sed 's/\([a-z]*\) \1/\1/'
#+end_src

중복 단어를 제거하지 않고 탐지하려면 다음을 시도합니다.

#+begin_src bash
sed -n ‘/\([a-z][a-z]*\) \1/ p’
#+end_src

또는 확장 정규식으로 다음을 시도합니다.

#+begin_src bash
sed -rn ‘/([a-z]+) \1/ p’      # GNU sed
sed -En ‘/([a-z]+) \1/ p’      # Mac OS X
#+end_src

이 명령을 필터(/filter/)로 사용하면 중복된 단어가 포함된 줄을 출력합니다.

역참조에 사용하는 숫자는 “\1” 에서 “\9” 까지 최대 9개 지정할 수 있습니다. 줄의 처음 세 문자를 뒤집으려면 다음을 시도합니다.

#+begin_src bash
sed 's/^\(.\)\(.\)\(.\)/\3\2\1/'
#+end_src


* Sed Pattern Flags
마지막 구분자 뒤에 플래그(/flags/)를 추가할 수 있습니다. 앞서 소개한 /substitute/ 명령어의 끝에 ‘p' 플래그가 붙어 있던 것을 눈치챘을지 모릅니다. 또한 ’-n' 옵션도 함께 추가했습니다. 먼저 'p' 와 다른 플래그에 대해 설명 드리겠습니다. 이 플래그들은 일치 부분을 발견했을 때 어떤 동작을 수행할지 지정합니다. 하나씩 설명 드리겠습니다.


** /g - Global replacement 
대부분 유닉스 유틸리티는 파일을 처리할 때 한 줄씩 읽어가면서 작동합니다. Sed도 기본적으로 이와 동일한 방식으로 작동합니다. 특정 단어를 변경하도록 지시하면 해당 줄에서 그 단어가 처음 나타난 부분만 변경합니다. 줄 첫 번째 단어 대신 모든 단어를 변경할 수도 있습니다.

예를 들어, 한 줄에 검색 일치한 단어를 괄호로 묶겠습니다. “won't” 같은 단어와 일치하지 않는 “[A-Za-z]*” 패턴 대신 공백을 제외한 모든 것을 일치시키는 “[^ ]*” 패턴을 사용합니다. 사실 “*” 는 0개 이상을 의미하므로 이 패턴은 모든 것을 일치시킵니다. (이 글을 작성하는 시점에서...)

#+begin_quote
[!TIP]
Solaris의 sed는 이와 같은 패턴을 제대로 처리하지 못해서 “/Output line too long/” 오류를 발생시키거나 심지어 무한 루프에 빠집니다. 저는 이를 버그로 간주해서 Sun에 보고했습니다.
#+end_quote

sed에 “g” 플래그를 사용할 때는 빈 문자열은 일치하지 않도록 처리해야 합니다. 해결 방법은 다음과 같습니다:

#+begin_src 
“[^ ][^ ]*.”
#+end_src

다음 명령어는 첫 번째 단어에 괄호를 씌웁니다:

#+begin_src bash
sed ‘s/[^ ]*/(&)/’ <old >new
#+end_src

모든 단어를 변경하려면 마지막 구분자 뒤에 “g” 플래그를 추가합니다:

#+begin_src bash
sed ‘s/[^ ][^ ]*/(&)/g’ <old >new
#+end_src


** Is sed recursive?
Sed는 입력 데이터에서 발견된 패턴에만 작업을 수행합니다. 즉, 입력 행을 읽은 후 패턴과 일치하면 수정된 출력을 생성하고 나머지 입력 행을 스캔합니다. “s” 명령어는 새로 생성한 출력을 스캔하지 않습니다. 따라서 다음과 같은 표현을 걱정할 필요는 없습니다.

#+begin_src bash
sed ‘s/loop/loop the loop/g’ <old >new
#+end_src

이 명령어는 무한 루프를 일으키지 않습니다!! 두 번째 “s” 명령어가 실행되면 이전 명령어의 처리 결과를 수정합니다. 여러 명령어를 실행하는 방법은 나중에 설명하겠습니다.


** /1, /2, etc. Specifying which occurrence
플래그를 지정하지 않으면 가장 먼저 일치한 부분만 대체합니다. “g” 플래그를 사용하면 모든 일치 항목을 대체합니다. 줄에서 첫 번째가 아닌 특정 위치의 패턴을 수정하려면 “\(” 와 “\)” 로 패턴을 부분 문자열로 기억하고 “\1” 역참조로 첫 번째 패턴을 변경하지 않은 채로 복원할 수 있습니다.

다음 예제는 줄의 첫 번째 단어는 유지하고 두 번째 단어는 삭제합니다.

#+begin_src bash
sed ‘s/\([a-zA-Z]*\) \([a-zA-Z]*\) /\1 /’ <old >new
#+end_src

으윽. 이보다 좀 더 쉽게 처리할 수 있는 방법이 있습니다. 대체 명령어 뒤에 숫자 플래그를 추가해서 특정 위치의 패턴만 일치시킬 수 있습니다. 

#+begin_src bash
sed ‘s/[a-zA-Z]* //2’ <old >new
#+end_src

숫자 플래그와 “g” (전역) 플래그는 함께 사용할 수 있습니다. 예를 들어, 첫 번째 단어는 그대로 두고 두 번째 세 번째 단어 등을 DELETED 로 변경하려면 “/2g” 플래그를 사용합니다:

#+begin_src bash
sed ‘s/[a-zA-Z]* /DELETED /2g’ <old >new
#+end_src

MacOS는 숫자 플래그와 “g” 플래그를 함께 사용하는 것이 작동하지 않는다고 들었으며 아마 FreeBSD 버전의 sed도 이와 마찬가지일 겁니다.

“/2” 플래그와 “\2” 역참조를 혼동하지 마시기 바랍니다. “/2” 플래그는 대체 명령어 끝에 사용됩니다. “\2” 역참조는 치환(대체 문자열) 필드에서 주로 사용합니다.

“*” 문자 뒤의 공백에 유의합니다. 만약 이 공백이 없으면 sed는 아주 오랫동안 실행됩니다. (참고: 이 버그는 지금쯤 수정했을 겁니다.) 이는 숫자 플래그와 “g” 플래그에 버그가 있기 때문입니다. 또는 다음과 같은 패턴을 사용할 수 있습니다.

#+begin_src bash
sed ‘s/[^ ]*//2’ <old >new
#+end_src

이 방법도 CPU 자원을 많이 소모합니다. 만약 이 방법이 여러분 컴퓨터에서 작동한다면(일부 UNIX 시스템은 작동합니다) 암호 파일의 암호화된 비밀번호를 제거할 수 있습니다:

#+begin_src bash
sed ‘s/[^:]*//2’ </etc/passwd >/etc/password.new
#+end_src

하지만 이 글을 작성할 당시엔 이 방법이 제 컴퓨터에선 작동하지 않았습니다. “[^:][^:]*” 패턴으로 우회해도 소용 없습니다. 존재하지 않는 비밀번호는 일치하지 않을 뿐만 아니라 세 번째 필드인 사용자 ID를 삭제합니다! 대신 다음과 같이 보기 흉한 괄호를 사용합니다:

#+begin_src bash
sed ‘s/^\([^:]*\):[^:]:/\1::/’ </etc/passwd >/etc/password.new
#+end_src

또한 첫 번째 패턴에 문자를 하나 추가해서 더이상 빈 패턴과 일치하지 않도록 처리할 수 있습니다:

#+begin_src bash
sed ‘s/[^:]*:/:/2’  </etc/passwd >/etc/password.new
#+end_src

숫자 플래그는 한 자릿수로 제한되지 않습니다. 1부터 512까지 임의의 숫자를 사용할 수 있습니다. 줄의 80번째 문자에 콜론을 추가하려면 다음과 같이 입력합니다:

#+begin_src bash
sed ‘s/./&:/80’ <file >new
#+end_src

또는 직접 80개 점을 입력해서 복잡하고 무식하게 처리할 수 있습니다:

#+begin_src bash
sed 's/^................................................................................/&:/' <file >new
#+end_src


** /p - print
sed는 기본적으로 모든 줄을 출력합니다! 치환이 이루어지면 기존 텍스트 대신 새로운 텍스트를 출력합니다. sed에 선택적 인수 “sed -n” 을 사용하면 줄을 출력하지 않습니다. 이 옵션과 다른 옵션은 나중에 다루겠습니다. “-n” 옵션을 사용할 때 “p” 플래그를 함께 사용하면 수정한 줄만 출력합니다.

다음은 sed로 grep 기능을 구현한 방법 중 하나입니다.

#+begin_src bash
sed -n ‘s/pattern/&/p’ <file
#+end_src

좀 더 간단한 방법은 나중에 다시 설명합니다.


** Write to a file with /w filename 
세 번째 구분자 뒤에 사용하는 플래그가 하나 더 있습니다. 이 플래그를 사용하면 수정된 데이터를 받을(저장할) 파일을 지정할 수 있습니다. 다음은 짝수 숫자로 시작하고 그 뒤에 공백이 오는 모든 줄을 ‘even’ 파일에 기록하는 예제입니다.

#+begin_src bash
sed -n ‘s/^[0-9]*[02468] /&/w even’ <file
#+end_src

이 예제는 입력을 수정하지 않으므로 사실 출력 파일은 필요하지 않습니다. “w” 명령어와 파일 이름 사이엔 정확히 하나의 공백이 있어야 합니다. 또한 하나의 sed 인스턴스로 최대 10개의 파일을 열 수 있습니다. 이를 통해 데이터 스트림을 별도의 파일로 분할할 수 있습니다. 앞서 본 예제를 나중에 설명할 다중 치환 명령과 결합하면 첫 번째 숫자의 마지막 숫자에 따라 파일을 10개로 분할할 수 있습니다. 또한 이 방법으로 오류나 디버깅 정보를 별도의 파일에 기록할 수도 있습니다.


** /I - Ignore Case
GNU 버전의 sed는 또 다른 패턴 플래그인 “/I” 가 추가되었습니다.

이 플래그는 패턴 일치 시 대소문자를 구분하지 않습니다. 이 플래그를 사용하면 abc, aBc, ABC, AbC 등과 일치합니다:

#+begin_src bash
sed -n ‘/abc/I p’ <old >new
#+end_src

‘/I’ 뒤와 ‘p’(출력) 명령어 사이의 공백은 'p' 가 패턴 수식어(플래그)가 아니라 패턴 일치 후 실행할 명령어임을 강조하기 위함입니다.


** Combining substitution flags
상황에 따라선 플래그를 조합할 수 있습니다. 단, “w” 플래그는 *반드시* 마지막에 위치한다는 점에 유의합니다. 예를 들어, 다음 명령어는 정상 작동합니다.

#+begin_src bash
sed -n ‘s/a/A/2pw /tmp/file’ <old >new
#+end_src

다음에는 sed 옵션과 sed를 호출할 수 있는 다양한 방법에 대해 설명하겠습니다.


** Arguments and invocation of sed
지금까지 대체 명령어를 하나만 사용했습니다. 두 가지 변경을 처리하는데 설명서를 읽지 않으려면 여러 개의 명령어를 파이프(/pipe/)로 연결할 수 있습니다:

#+begin_src bash
sed ‘s/BEGIN/begin/’ <old | sed ‘s/END/end/’ >new
#+end_src

이 방법은 하나의 프로세스 대신 두 개의 프로세스를 사용합니다. sed 고수는 하나의 프로세스로 해결할 수 있는 일을 두 개의 프로세스로 처리하지 않습니다!!


** Multiple commands with -e command
여러 개의 명령을 결합하는 한 가지 방법은 각 명령 앞에 “-e” 옵션을 사용하는 것입니다:

#+begin_src bash
sed -e ‘s/a/A/’ -e ‘s/b/B/’ <old >new
#+end_src

앞선 예제들은 “-e” 옵션이 필요하지 않습니다. sed는 항상 "하나의 명령이 있다!" 는 것을 잘 알기 때문입니다. sed에 하나의 인수만 전달하면 그 인수는 명령이며 sed는 표준 입력에서 읽은 데이터를 편집합니다.

긴 인자 형식은 다음과 같습니다.

#+begin_src bash
sed --expression=‘s/a/A/’ --expression=‘s/b/B/’ <old >new
#+end_src

또한 Bourne 셸에서 여러 개의 명령을 따옴표로 묶는 방법도 참조합니다.


** Filenames on the command line
원한다면 명령줄에 파일을 지정할 수 있습니다. sed에 옵션으로 시작하지 않는 인수가 두 개 이상일 경우 그 인수는 반드시 파일 이름이라야 합니다.

다음 예제는 “#” 으로 시작하지 않는 세 파일의 줄 수를 계산합니다.

#+begin_src bash
sed ‘s/^#.*//’  f1 f2 f3 | grep -v ‘^$’ | wc -l
#+end_src

단계별로 살펴보겠습니다.

- sed의 /substitute/ 명령어는 “#” 으로 시작하는 모든 줄을 빈 줄로 바꿉니다.
- ~grep~ 은 빈 줄을 걸러내는(삭제하기) 용도로 사용했습니다.
- ~wc~ 는 남은 줄의 수를 셉니다.

~sed~ 는 ~grep~ 을 사용하지 않아도 처리할 수 있는 명령어가 있습니다. 또한 ~grep -c~ 로 ~wc -l~ 을 대체할 수 있습니다. 나중에 ~grep~ 의 일부 기능을 어떻게 재현할 수 있는지 설명하겠습니다.

마지막 예제는 “-e” 옵션으로 다음과 같이 작성할 수 있습니다:

#+begin_src bash
sed -e ‘s/^#.*//’  f1 f2 f3 | grep -v ‘^$’ | wc -l
#+end_src

sed는 이 외에도 두 가지 옵션이 더 있습니다.


** sed -n: no printing
“-n” 옵션은 명시적인 출력 요청이 발견되지 않는 한 아무것도 출력하지 않습니다!! 앞서 /substitute/ 명령어의 “/p” 플래그로 출력을 켜는 방법을 언급한 바 있습니다. 이에 대해 좀 더 명확히 설명드리겠습니다. 다음 명령어

#+begin_src bash
sed  ‘s/PATTERN/&/p’ file
#+end_src

은 파일에 PATTERN 이 없으면 ~cat~ 프로그램처럼 작동합니다. 즉, 아무것도 변경하지 않습니다. PATTERN 이 있으면 패턴이 포함된 줄을 두 번 중복 출력합니다. “-n” 옵션을 추가하면 ~grep~ 처럼 동작합니다:

#+begin_src bash
sed -n ‘s/PATTERN/&/p’ file
#+end_src

PATTERN 이 포함된 줄을 제외하곤 아무것도 출력하지 않습니다.

“-n” 명령어의 긴 인수는 다음 둘 중 하나입니다.

#+begin_src bash
sed --quiet ‘s/PATTERN/&/p’ file
#+end_src

또는

#+begin_src bash
sed --silent ‘s/PATTERN/&/p’ file
#+end_src


** Using 'sed /pattern/'
Sed는 명령어 앞에 주소를 지정해서 어떤 줄을 검사하거나 수정할지 지정할 수 있는 기능을 가집니다. 가장 간단한 버전인 ~/PATTERN/~ (패턴) 주소를 설명하겠습니다. 패턴 주소를 사용하면 패턴과 일치한 줄에만 명령어가 적용됩니다. “/p” 플래그를 사용하면 일치한 줄은 두 번 중복 출력됩니다:

#+begin_src bash
sed ‘/PATTERN/p’ file
#+end_src

물론 PATTERN 은 어떤 정규 표현식이든 모두 사용 가능합니다.

출력을 위한 “p” 같은 "명령어를 포함하지 않으면 오류가 발생한다!" 는 점에 유의합니다!! 즉 다음과 같이 입력하면

#+begin_src bash
echo abc | sed '/a/'
#+end_src

다음과 같은 오류가 발생합니다.

#+begin_example
sed: -e expression #1, char 3: missing command
#+end_example

필수 사항은 아니지만 "패턴과 명령어 사이에 공백을 넣는 것을 권장" 합니다. 패턴 일치를 수정하는 플래그와 패턴 일치 후 실행할 명령어를 구분하는 데 도움됩니다. 따라서 다음과 같은 형식으로 사용하길 권장합니다:

#+begin_src bash
sed ‘/PATTERN/ p’ file
#+end_src


** Using 'sed -n /pattern/p' to duplicate the function of grep
~grep~ 기능을 재현하려면 “-n” (/nocopy/) 옵션과 “/p” (/print/)플래그를 함께 사용합니다:

#+begin_src bash
sed -n ‘/PATTERN/p’ file
#+end_src


** sed -f scriptname
사용할 명령어가 많으면 파일로 저장해서 호출할 수 있습니다.

#+begin_src bash  
sed -f sedscript <old >new
#+end_src

여기서 /sedscript/ 는 다음과 같이 작성합니다.

#+begin_src bash
# sed 주석 - 이 스크립트는 소문자 모음을 대문자로 변경합니다.
s/a/A/g
s/e/E/g
s/i/I/g
s/o/O/g
s/u/U/g
#+end_src

파일에 여러 명령어를 사용할 경우 각 명령어를 별도의 줄에 작성합니다.

긴 인자 형식은 다음과 같습니다.

#+begin_src bash
sed --file=sedscript <old >new
#+end_src

또한 sed를 직접 실행하는 스크립트 작성 방법은 다음을 참조합니다.

** sed in shell scripts
명령어가 많아 한 줄에 들어가지 않을 경우 백슬래시로 줄을 나눕니다:

#+begin_src bash
sed -e ‘s/a/A/g’ \
    -e ‘s/e/E/g’ \
    -e ‘s/i/I/g’ \
    -e ‘s/o/O/g’ \
    -e ‘s/u/U/g’  <old >new
#+end_src


** Quoting multiple sed lines in the C shell
C 셸은 여러 줄로 구성된 sed 스크립트를 사용할 수 있지만 따옴표로 여러 줄에 걸쳐진다는 사실을 알려야 합니다. 이를 위해 각 줄 끝에 백슬래시를 붙입니다:

#+begin_src bash
#!/bin/csh -f
sed 's/a/A/g  \
s/e/E/g \
s/i/I/g \
s/o/O/g \
s/u/U/g'  <old >new
#+end_src

** Quoting multiple sed lines in the Bourne shell
Bourne 셸은 따옴표로 여러 줄을 감쌀 수 있으므로 작업이 좀 더 쉽습니다:

#+begin_src bash
#!/bin/sh
sed '
s/a/A/g
s/e/E/g
s/i/I/g
s/o/O/g
s/u/U/g'  <old >new
#+end_src


** sed -V
“-V” 옵션은 현재 사용 중인 sed 버전을 표시합니다. 긴 형식은 다음과 같습니다.

#+begin_src bash
sed --version
#+end_src


** sed -h
“-h” 옵션은 sed 명령어의 요약 정보를 표시합니다. 긴 형식은 다음과 같습니다.

#+begin_src bash
sed --help
#+end_src


** A sed interpreter script
sed를 실행할 수 있는 또 다른 방법은 인터프리터 스크립트로 사용하는 것입니다.

다음 내용을 포함하는 파일을 만듭니다.

#+begin_src bash
#!/bin/sed -f
s/a/A/g
s/e/E/g
s/i/I/g
s/o/O/g
s/u/U/g
#+end_src

이 스크립트를 “CapVowel” 파일로 저장하고 실행 권한을 부여하면 다음과 같이 간단한 명령어로 사용할 수 있습니다:

#+begin_src bash
CapVowel <old >new
#+end_src


** Comments
sed 주석은 첫 번째 비공백 문자가 “#” 인 줄입니다!! 많은 시스템의 sed는 한 가지 주석만 가질 수 있으며 스크립트의 첫 번째 줄에 위치해야 합니다. Sun 시스템(이 글을 작성한 1988년 당시)은 스크립트 어디서나 여러 개의 주석을 넣을 수 있습니다. 최신 버전의 sed는 이를 잘 지원합니다.

스크립트 첫 번째 줄에 정확히 “#n” 이 포함되면 “-n” 옵션과 동일한 기능을 수행합니다!! 즉, 기본 출력 기능을 비활성화합니다. 하지만, sed 인터프리터 스크립트는 수행할 수 없습니다. 왜냐하면 첫 번째 줄은 반드시 “#!/bin/sed -f” 로 시작하기 때문인데 제 기억에 “#!/bin/sed -nf” 는 오류를 발생시킨 것으로 기억합니다. 이 글을 작성했을 때(2008년)는 정상 작동했습니다. “#!/bin/sed -fn” 은 sed가 스크립트 파일 이름을 “n” 으로 인식하므로 작동하지 않는다는 점에 유의합니다. 그러나, “#!/bin/sed -nf” 는 정상 작동합니다.


** Passing arguments into a sed script
UNIX 따옴표 튜토리얼을 기억하신다면 sed를 호출하는 스크립트에 단어(인수)를 전달하는 것은 쉽습니다. 정리하면 작은 따옴표로 따옴표 처리를 켜거나 끌 수 있습니다. sed로 ~grep~ 을 모방하는 간단한 셸 스크립트는 다음과 같습니다.

#+begin_src bash
#!/bin/sh
sed -n ‘s/’$1'/&/p'
#+end_src

하지만 이 스크립트는 미묘한 문제가 있습니다. 만약 인자에 공백이 포함되면 다음과 같은 구문 오류를 발생시킵니다.

#+begin_example
sed: -e expression #1, char 4: unterminated `s' command
#+end_example

개선한 버전은 이 문제를 방지합니다:

#+begin_src bash
#!/bin/sh
sed -n ‘s/’“$1”‘/&/p’
#+end_src

이 코드를 /sedgrep/ 파일에 저장했다면 다음과 같이 실행할 수 있습니다.

#+begin_src bash
sedgrep ‘[A-Z][A-Z]’ <파일
#+end_src

/sedgrep/ 프로그램은 ~grep~ 처럼 작동합니다.


** Using sed in a shell here-is document
sed로 사용자에게 몇 가지 매개변수를 입력받은 다음 해당 매개변수로 채워진 파일을 생성할 수 있습니다. 가짜 값이 들어 있는 파일을 만들고 sed로 가짜 값을 변경할 수 있습니다. 간단한 방법은 쉘 스크립트 일부를 표준 입력처럼 사용할 수 있는 “here is” 문서를 활용하는 것입니다:

#+begin_src bash
#!/bin/sh
echo -n ‘값은 무엇입니까? ’
read value
sed  ‘s/XYZ/’$value'/' <<EOF
값은 XYZ 입니다
EOF
#+end_src

이 스크립트를 실행하면 다음과 같이 표시됩니다:

#+begin_example
값은 무엇입니까?
#+end_example

“123” 을 입력하면 다음과 같이 표시됩니다:

#+begin_example
값은 123 입니다
#+end_example

네, 예제가 인위적이란 점을 인정합니다. “here is” 문서는 sed를 사용하지 않고 값을 평가할 수 있습니다. 다음 예제도 동일한 기능을 수행합니다:

#+begin_src bash
#!/bin/sh
echo -n ‘값은 무엇입니까? ’
read value
cat <<EOF
값은 $value 입니다
EOF
#+end_src

하지만 “here is” 문서를 sed와 결합하면 일부 복잡한 경우는 유용합니다.

다음과 같은 경우에 유의합니다.

#+begin_src bash
sed ‘s/XYZ/’$value'/' <<EOF
#+end_src

사용자가 “a b c” 처럼 공백이 포함된 답변을 입력하면 구문 오류가 발생합니다. 좀 더 나은 방법은 값을 평가할 때 큰따옴표로 묶는 것입니다:

#+begin_src bash
#!/bin/sh
echo -n ‘값은 무엇입니까? ’
read value
sed  ‘s/XYZ/’“$value”‘/’ <<EOF
값은 XYZ 입니다
EOF
#+end_src

이 내용은 따옴표 튜토리얼에서 다룬 바 있습니다.


** Multiple commands and order of execution
sed 명령어를 많이 알아갈수록 명령어는 복잡해지고 실제 실행 순서가 헷갈릴 수 있습니다. 사실 아주 간단합니다!!

각 줄이 차례로 읽혀져 들어옵니다. 사용자가 지정한대로 명령어는 입력된 줄에 작업을 수행할 기회를 갖습니다. 치환이 완료된 이후 이전 명령어들에 의해 수정된 줄에 다음 명령어가 처리할 기회를 얻습니다.

어떤 결과가 나올지 알아보는 가장 좋은 방법은 간단한 예제로 만드는 것입니다. 복잡한 명령어가 제대로 작동하지 않으면 좀 더 단순하게 만듭니다. 복잡한 스크립트를 작동시킬 때 문제있다면 두 개의 작은 스크립트로 나눈 후 두 스크립트를 파이프로 연결합니다.


** Addresses and Ranges of Text
지금까지 명령어 하나만 배웠음에도 sed가 얼마나 강력한지 잘 알 수 있습니다. 하지만 명령어로 처리한 일은 그저 ~grep~ 과 /substitute/ 를 수행한 것에 불과합니다. 즉, /substitute/ 명령어는 인접한 줄은 고려하지 않고 각 줄을 모두 처리합니다. 특정 줄로 작업을 제한할 수 있다면 아주 유용할 것입니다.

제한 조건은 다음과 같습니다:

- 행 번호를 지정해서 특정 행을 선택합니다.
- 행 번호 범위를 지정해서 특정 행 범위를 선택합니다.
- 특정 패턴이 포함된 모든 행을 선택합니다.
- 파일 시작에서 정규 표현식까지 모든 행을 선택합니다.
- 정규 표현식에서 파일 끝까지 모든 행을 선택합니다.
- 두 정규 표현식 사이의 모든 행을 선택합니다.

sed는 이 모든 기능과 그 이상의 작업까지 수행할 수 있습니다. sed의 모든 명령어 앞에는 주소, 범위 또는 제한 조건이 올 수 있습니다. 제한 조건이나 주소는 명령어 바로 앞에 위치합니다:

#+begin_example
restriction command
#+end_example


** Restricting to a line number
가장 간단한 제한 조건은 줄 번호입니다. 3번째 줄의 첫 번째 숫자를 삭제하려면 명령어 앞에 “3” 을 추가합니다.

#+begin_src bash
sed ‘3 s/[0-9][0-9]*//’ <file >new
#+end_src


** Patterns
~vi~ 나 ~more~ 같은 UNIX 유틸리티는 슬래시 문자로 정규식을 검색합니다. Sed도 표현식을 슬래시로 끝맺으면 동일한 규칙을 따릅니다. 예를 들어, “#” 으로 시작하는 모든 줄에서 첫 번째 숫자를 삭제하려면 다음을 사용합니다.

#+begin_src bash
sed ‘/^#/ s/[0-9][0-9]*//’
#+end_src

가독성을 높이기 위해 ~/표현식/~ 뒤에 공백을 넣었습니다. 꼭 필요한 건 아니지만 이 공백이 없으면 명령어를 이해하기 어렵습니다. Sed는 정규 표현식을 지정할 때 몇 가지 추가 옵션을 제공합니다. 하지만 나중에 다시 설명하겠습니다.

표현식이 백슬래시 문자로 시작하면 그 다음 문자는 구분자 역할을 처리합니다!! 예를 들어, 슬래시 대신 쉼표를 구분자로 사용하려면 다음을 입력합니다:

#+begin_src bash
sed '\,^#, s/[0-9][0-9]*//'
#+end_src

이 기능의 가장 큰 장점은 "슬래시 문자를 검색할 수 있다!" 는 점입니다. ~/usr/local/bin~ 문자열을 검색해서 ~/common/all/bin~ 으로 바꾼다고 가정합니다. 다음과 같이 백슬래시로 모든 슬래시 문자를 이스케이프 처리해야 합니다:

#+begin_src bash
sed '/\/usr\/local\/bin/ s/\/usr\/local/\/common\/all/'
#+end_src

검색 시 슬래시 대신 밑줄 문자를 사용하면 이해하기 쉽습니다. 다음 예제는 검색 명령과 대체 명령 모두에 밑줄 문자를 사용합니다:

#+begin_src bash
sed '\_/usr/local/bin_ s_/usr/local_/common/all_'
#+end_src

이런 이유로 "sed 스크립트는 난해하다!" 는 평판을 자주 받습니다. 좀 더 모질게 “g” 로 시작하는 모든 줄을 찾아낸 후 해당 줄의 모든 “g” 를 “s” 로 바꾸는 예제를 보여드리지만:

#+begin_src bash
sed ‘/^g/s/g/s/g’
#+end_src

이제 공백을 추가하고 대체 명령어에 밑줄(_)을 구분자로 사용하면 훨씬 읽기 쉬워집니다:

#+begin_src bash
sed ‘/^g/ s_g_s_g’
#+end_src

아, 이 말은 취소하겠습니다. 이건 도저히 안 되겠네요.

여기서 얻을 수 있는 교훈은 "sed 스크립트는 주석을 아낌없이 사용해야 한다!" 는 것입니다. (구형) 운영 체제에서 이 스크립트를 실행하려면 주석을 제거해야 할 수도 있지만 이제 이를 매우 쉽게 처리할 수 있는 sed 스크립트 작성 방법을 알게 되었습니다! 여하튼 주석은 좋은 것입니다!!

스크립트 작성 당시엔 완벽히 이해했을지도 모릅니다. 하지만 6개월 후에는 마치 모뎀 잡음처럼 보일 수 있습니다. 이 비유가 이해되지 않으면 8개월 된 아이가 키보드를 두드리는 모습을 상상하시기 바랍니다.


** Ranges by line number
줄 번호 사이에 쉼표를 삽입해서 (주소) 범위를 지정할 수 있습니다. 첫 100줄로 치환을 제한하려면 다음과 같이 사용합니다.

#+begin_src bash
sed '1,100 s/A/a/'
#+end_src

파일의 줄 수를 정확히 안다면 숫자를 명시해서 나머지 부분도 치환할 수 있습니다. 이 경우 ~wc~ 명령어로 파일에 532줄이 있단 것을 확인했다고 가정합니다:

#+begin_src bash
sed ‘101,532 s/A/a/’
#+end_src

좀 더 쉬운 방법은 파일 마지막 줄을 의미하는 특수 문자 “$” 를 사용하는 것입니다.

#+begin_src bash
sed ‘101,$ s/A/a/’
#+end_src

“$” 문자는 ~cat -e~, ~vi~, ~ed~ 같은 유틸리티에서 “마지막” 을 의미하는 관례 중 하나입니다. “cat -e” 에서 여러 파일을 편집할 경우 줄 번호는 누적됩니다. 즉,

#+begin_src bash
sed ‘200,300 s/A/a/’ f1 f2 f3 >new
#+end_src

는 다음과 동일합니다.

#+begin_src bash
cat f1 f2 f3 | sed ‘200,300 s/A/a/’ >new
#+end_src


** Ranges by patterns
(주소) 범위로 두 개의 정규식을 지정할 수 있습니다. “#” 으로 시작하는 주석을 가정할 때 첫 번째 키워드를 검색한 후, 두 번째 키워드가 나타날 때까지 모든 주석을 제거할 수 있습니다. 이 경우 사용할 두 키워드는 “start” 와 “stop” 입니다.

#+begin_src bash
sed '/start/,/stop/ s/#.*//'
#+end_src

첫 번째 패턴은 sed가 모든 줄에서 대체 명령을 수행하는 플래그를 켭니다. 두 번째 패턴은 이 플래그를 끕니다. 따라서 “start” 와 ‘stop’ 패턴이 두 번 나타나면 두 번 모두 대체합니다. “stop” 패턴이 누락된 경우 플래그는 꺼지지 않으므로 파일 끝까지 모든 줄에 대체가 수행됩니다.

“start” 패턴이 발견되면 “start” 가 포함된 줄부터 작업이 수행된다는 점을 알아야 합니다. 이는 줄 단위로 작동되는 스위치를 켜는 것입니다. 즉, 다음 줄을 읽어와 대체 명령을 확인합니다. 만약 “stop” 이 포함되면 이 스위치는 꺼집니다. 즉, 이 스위치는 단어 단위가 아닌 줄 단위로 작동합니다!!

줄 번호와 정규식을 결합할 수 있습니다. 다음 예제는 파일 시작부터 “start” 키워드가 발견될 때까지 주석을 제거합니다.

#+begin_src bash
sed -e '1,/start/ s/#.*//'
#+end_src

이 예제는 두 키워드 사이의 줄을 *제외한* 모든 곳의 주석을 제거합니다:

#+begin_src bash
sed -e ‘1,/start/ s/#.*//’ -e ‘/stop/,$ s/#.*//’
#+end_src

마지막 예제는 두 범위 모두 키워드가 포함된 줄이 대상이므로 ~/start/,/stop/~ 범위와 중복되는 부분이 있습니다. 나중에 지정한 패턴이 포함된 줄로(해당 줄은 제외) 명령을 제한하는 방법을 보여 드리겠습니다. 이는 “패턴을 제외한 패턴 범위에서 작업하기” 섹션에 나와 있습니다. 하지만 그 전에 몇 가지 기본 원리를 다뤄야 합니다.

다양한 명령를 설명하기 전에 일부 명령은 "줄 범위로 적용할 수 없다!" 는 점을 미리 말합니다. 해당 명령을 설명할 때 알려 드리겠습니다. 다음 섹션에서 세 가지 명령을 설명할 예정이며 그 중 하나는 범위에 적용할 수 없습니다.


** Delete with d
범위는 것은 다소 헷갈릴 수 있으므로 새로운 스크립트를 시험할 때는 몇 번의 시행착오를 겪을 각오를 해야 합니다.  제한 조건에 맞는 모든 줄을 삭제하는 유용한 “d” (/delete/)명령어가 있습니다. 예를 들어, 파일 처음 10줄만 보려면 다음과 같이 사용합니다.

#+begin_src bash
sed ‘11,$ d’ <file
#+end_src

이는 ~head~ 명령어와 기능이 비슷합니다. 메일 메시지의 헤더 즉, 첫 번째 빈 줄까지 모든 내용을 잘라내려면 다음을 사용합니다.

#+begin_src bash
sed ‘1,/^$/ d’ <file
#+end_src

파일 길이를 안다면 ~tail~ 기능을 재현할 수 있습니다. ~wc~ 로 줄 수를 세고 ~expr~ 로 줄 수에서 10을 뺍니다. 파일 마지막 10줄을 확인하는 Bourne 셸 스크립트는 다음과 같습니다:

#+begin_src bash
#!/bin/sh
#print last 10 lines of file
# First argument is the filename
lines=$(wc -l "$1" | awk '{print $1}' )
start=$(( lines - 10))
sed "1,$start d" "$1"
#+end_src

삭제 범위는 작업 시작과 끝을 표시하는 정규 표현식 쌍일 수도 있고 단일 정규 표현식일 수도 있습니다. “#” 으로 시작하는 모든 줄을 삭제하는 것은 간단합니다:

#+begin_src bash
sed '/^#/ d'
#+end_src

주석과 빈 줄까지 모두 제거하려면 두 개의 명령어가 필요합니다. 첫 번째 명령어는 “#” 부터 줄 끝까지 모든 문자를 제거하고 두 번째 명령어는 모든 빈 줄을 삭제합니다:

#+begin_src bash
sed -e ‘s/#.*//’ -e ‘/^$/ d’
#+end_src

줄 끝 앞의 공백과 탭까지 제거하려면 세 번째 명령어를 추가합니다:

#+begin_src bash
sed -e 's/#.*//' -e ‘s/[ ^I]*$//’ -e ‘/^$/ d’
#+end_src

여기서 “^I” 는 ~CTRL-I~ 또는 탭 문자를 의미합니다. 탭 문자는 직접 입력합니다. 또한 위의 명령어 실행 순서에 유의합니다. 이 순서는 타당한 이유가 있어 정했습니다. 주석은 줄 중간에서 시작할 수 있으며 그 앞에 공백 문자가 있을 수 있습니다. 따라서 먼저 주석을 제거하며 이 과정에서 주석 앞에 공백 문자가 남을 수 있습니다. 두 번째 명령어는 줄 끝의 모든 공백을 제거해서 이제 공백으로 남은 줄을 빈 줄로 변환합니다. 마지막 명령어는 빈 줄을 삭제합니다. 이 세 명령어를 사용하면 주석, 탭 또는 공백만 포함된 모든 줄을 제거할 수 있습니다.

다음은 sed가 줄을 처리할 때 사용하는 패턴 공간(/pattern space/)을 보여줍니다. 

- 입력 행을 패턴 공간에 복사합니다.
- 주소 제한 조건이 참일 경우 패턴 공간에 첫 번째 sed 명령을 적용합니다.
- 다음 sed 표현식으로 이 과정을 반복하며 다시 패턴 공간에 명령을 적용합니다.
- 마지막 명령까지 적용하면 패턴 공간을 출력하고 입력 파일의 다음 행을 읽습니다.


** Printing with p
또 다른 유용한 명령어는 출력 명령어인 “p” (/print/)입니다. sed를 “-n” 옵션없이 실행한 경우 “p” 명령어는 입력 내용을 복제합니다. 다음 명령어

#+begin_src bash
sed ‘p’
#+end_src

는 모든 줄을 복제합니다. 빈 줄만 두 번 출력하려면 다음과 같이 사용합니다:

#+begin_src bash
sed ‘/^$/ p’
#+end_src

“-n” 옵션을 추가하면 명시적으로 요청하지 않는 한 출력은 비활성화 됩니다. ~head~ 기능을 재현하는 또 다른 방법은 원하는 행만 출력하는 것입니다. 다음 예제는 처음 10행을 출력합니다:

#+begin_src bash
sed -n ‘1,10 p’ <file
#+end_src

sed는 /print/ 명령어(연산자)로 정규 표현식과 일치한 모든 행에 작업을 수행함으로 ~grep~ 과 동일한 역할을 수행합니다:

#+begin_src bash
sed -n ‘/match/ p’
#+end_src

이는 다음 명령어와 동일합니다:

#+begin_src bash
grep match
#+end_src


** Reversing the restriction with !
때로는 정규 표현식과 일치한 줄이나 주소 범위의 줄을 *제외한* 모든 줄에 작업할 때가 있습니다. UNIX 유틸리티에서 흔히 ‘아님’ 을 의미하는 “!” 문자는 주소 제한 조건을 *반전* 시킵니다. 기억하시겠지만,

#+begin_src bash
sed -n ‘/match/ p’
#+end_src

는 ~grep~ 과 같은 역할을 처리합니다. ~grep~ 의 “-v” 옵션은 해당 패턴이 포함되지 않은 모든 줄을 출력합니다. sed는 다음 명령으로 동일하게 수행합니다.

#+begin_src bash
sed -n ‘/match/ !p’ </tmp/b
#+end_src

** Relationships between d, p, and !
아시다시피, sed를 사용하면 문제를 해결할 수 있는 여러 방법이 존재합니다. 이는 /print/ 와 /delete/ 가 서로 반대되는 기능을 처리하기 때문인데 “!p” 는 “d” 와 비슷하고 “!d” 는 “p” 와 비슷합니다.

이를 확인하기 위해 20줄짜리 테스트 파일을 만들고 가능한 모든 조합을 시도했습니다. 다음 표는 테스트 결과로 그 차이점을 잘 보여줍니다:

*Relations between d, p, and !*

| Sed    | Range | Command | Results                                             |
|--------+-------+---------+-----------------------------------------------------|
| sed -n | 1,10  | p       | Print first 10 lines                                |
| sed -n | 11,$  | !p      | Print first 10 lines                                |
| sed    | 1,10  | !d      | Print first 10 lines                                |
| sed    | 11,$  | d       | Print first 10 lines                                |
| sed -n | 1,10  | !p      | Print last 10 lines of my 20-line file              |
| sed -n | 11,$  | p       | Print last 10 lines of my 20-line filme             |
| sed    | 1,10  | d       | Print last 10 lines of my 20-line file              |
| sed    | 11,$  | !d      | Print last 10 lines of my 20-line file              |
| sed -n | 1,10  | d       | Nothing printed                                     |
| sed -n | 1,10  | !d      | Nothing printed                                     |
| sed -n | 11,$  | d       | Nothing printed                                     |
| sed -n | 11,$  | !d      | Nothing printed                                     |
| sed    | 1,10  | p       | Print first 10 lines twice, then next 10 lines once |
| sed    | 11,$  | !p      | Print first 10 lines twice, then last 10 lines once |
| sed    | 1,10  | !p      | Print first 10 lines once, then last 10 lines twice |
| sed    | 11,$  | p       | Print first 10 lines once, then last 10 lines twice |

이 표는 제가 준비한 20줄짜리 테스트 파일에 사용했을 때 다음과 같은 명령어가 동일한 결과를 보인다는 것을 잘 보여줍니다:

#+begin_src bash
sed -n ‘1,10 p’
sed -n ‘11,$ !p’
sed ‘1,10 !d’
sed ‘11,$ d’
#+end_src

또한 “!” (반전)명령어가 주소 범위를 “반전” 시켜 다른 줄을 처리한다는 사실도 잘 보여줍니다. 물론 20줄보다 긴 파일의 경우 마지막 두 예제는 10줄 이상이 처리합니다.


** The q or quit command
특정 줄 범위로 제한할 수 있는 간단한 명령어가 있습니다. “q” 명령어 즉, 종료(/quit/) 명령어입니다. ~head~ 를 모방하는 세 번째 방법은 다음과 같습니다.

#+begin_src bash
sed ‘11 q’
#+end_src

이 명령어는 11번째 줄에 도달하는 즉시 종료합니다. 이 명령어는 특정 조건에 도달했을 때 작업을 중단할 때 유용합니다.

“q” 명령어는 주소 범위를 지정할 수 없는 *유일한* 명령어입니다. 당연히 다음과 같은 명령어

#+begin_src bash
sed ‘1,10 q’
#+end_src

는 10번 줄에서 종료하지 않습니다! 대신

#+begin_src bash
sed ‘1 q’
#+end_src

또는

#+begin_src bash
sed ‘10 q’
#+end_src

가 올바른 명령어입니다.


** Grouping with { and }
중괄호 “{” 와 “}” 는 명령어를 그룹으로 묶는데 사용합니다.

장황하게 설명할만한 가치가 있을진 의문입니다. 길게 설명하고 정작 중괄호 두 개를 맞추는 것 뿐입니다. 하지만 복잡한 점도 있습니다. 각 sed 명령어는 *반드시* 별도의 단독 줄에서 시작해야 하므로 중괄호와 중첩된 sed 명령어는 서로 다른 줄에 위치해야 합니다.

앞서 “#” 으로 시작하는 주석을 제거하는 방법을 보여 드렸습니다. 만약 “begin” 과 “end” 키워드 사이의 줄만 제거하도록 제한하려면 다음과 같이 사용합니다:

#+begin_src bash
#!/bin/sh
# 이 Bourne 셸 스크립트는 ‘begin' 과 'end’ 사이의 #-형식 주석을 제거합니다.
sed -n '
	/begin/,/end/ {
	     s/#.*//
	     s/[ ^I]*$//
	     /^$/ d
	     p
	}
'
#+end_src

중괄호는 중첩할 수 있으므로 주소 범위를 결합할 수 있습니다. 동일한 작업을 수행하되 변경 범위를 처음 100줄로 제한합니다:

#+begin_src bash
#!/bin/sh
# 이 Bourne 셸 스크립트는 #-형식 주석을 ‘begin' 과 'end’ 사이의 단어에서 제거합니다.
sed -n '
	1,100 {
		/begin/,/end/ {
		     s/#.*//
		     s/[ ^I]*$//
		     /^$/ d
		     p
		}
	}
'
#+end_src

중괄호 앞에 “!” (반전)를 붙일 수 있습니다. 주소가 반전되어 두 예약어 사이의 줄을 *제외한* 모든 줄의 주석이 제거됩니다:

#+begin_src bash
#!/bin/sh
sed '
	/begin/,/end/ !{
	     s/#.*//
	     s/[ ^I]*$//
	     /^$/ d
	     p
	}
'
#+end_src



** Operating in a pattern range except for the patterns
제가 "패턴 범위로 대체 작업을 처리할 수 있다!" 고 언급한 것을 기억하실지 모르겠습니다. 예를 들어, begin/end 패턴 사이의 “old” 를 “new” 로 바꾸는 것처럼 말입니다:

#+begin_src bash
#!/bin/sh
sed '
	/begin/,/end/ s/old/new/
'
#+end_src

또 다른 방법은 중괄호로 그룹으로 묶습니다:

#+begin_src bash
#!/bin/sh
sed '
	/begin/,/end/ {
	    s/old/new/
	}
'
#+end_src

코드를 좀 더 명확히 이해할 수 있고 수정하기도 쉽다고 생각합니다.

“begin” 부분은 수정하지 않으려면 해당 줄을 건너뛰도록 새로운 조건을 추가합니다:

#+begin_src bash
#!/bin/sh
sed '
	/begin/,/end/ {
	    /begin/n        # “begin” 줄은 건너뜁니다
	    s/old/new/
	}
'
#+end_src

하지만 “end” 가 포함된 줄을 건너뛰는 것은 까다롭습니다. “begin” 에 적용한 방법을 사용하면 sed 엔진에서 범위를 중단할 “end” 를 인식하지 못하고 그 줄까지 건너뜁니다. 해결책은 “end” 가 포함되지 않은 모든 줄에 대체 작업을 수행하는 것입니다.

#+begin_src bash
#!/bin/sh
sed '
    /begin/,/end/ {
      /begin/n              # “begin” 줄은 건너뜁니다
      /end/ !{
        s/old/new/
      }  
    }
'
#+end_src


** Writing a file with the 'w' command
/substitute/ 명령어로 파일에 쓸 수 있다는 점을 기억하실 겁니다. 다음은 짝수(그 뒤에 공백이 오는)로 시작하는 줄만 ‘even’ 파일에 기록하는 예제입니다.

#+begin_src bash
sed -n ‘s/^[0-9]*[02468] /&/w even’ <file
#+end_src

대체 명령어의 대체 문자열에 “&” 를 사용한 이유는 해당 줄을 변경하지 않기 위해서입니다. 좀 더 간단한 예로는 ‘w’ 명령어를 사용하는 것인데 이는 /substitute/ 명령어의 “w” 플래그와 구문이 동일합니다:

#+begin_src bash
sed -n ‘/^[0-9]*[02468]/ w even’ <file
#+end_src

명심합니다!! 명령어 뒤엔 공백 하나만 위치해야 합니다!! 그 외의 모든 것은 파일 이름 일부로 간주합니다. “w” 명령어 역시 “w” 플래그와 동일한 제한 사항이 적용됩니다. 즉, sed는 최대 10개 파일만 열 수 있습니다.


** Reading in a file with the 'r' command
파일을 읽는 명령어도 있습니다. 다음 명령어

#+begin_src bash
sed ‘$r end’ <in >out
#+end_src

는 파일의 끝(주소 “$”)에 ‘end’ 파일을 읽고 내용을 추가합니다. 다음 명령어는 “INCLUDE” 단어가 포함된 줄 뒤에 파일을 삽입합니다.

#+begin_src bash
sed ‘/INCLUDE/ r file’ <in>out
#+end_src

중괄호로 “INCLUDE” 명령어가 포함된 줄을 삭제합니다:

#+begin_src bash
#!/bin/sh
sed '/INCLUDE/ {
    r file
    d
}'
#+end_src

삭제 명령어 “d” (/delete/)와 파일 읽기 명령어 “r” (/read/)의 배치 순서는 중요합니다. 이 순서를 바꾸면 제대로 작동하지 않습니다. 이 명령어가 작동하지 않는 두 가지 미묘한 동작이 있습니다. 첫 번째는 “r” 명령어는 (파일을) "출력 스트림에만 기록한다!" 는 점입니다. 파일은 패턴 공간에 삽입되지 않으므로 어떤 명령어로도 수정할 수 없습니다. 따라서 삭제 명령어는 파일에서 읽은 데이터엔 영향을 미치지 않습니다.

또 다른 미묘한 점은 “d” 명령어는 "패턴 공간의 현재 데이터를 삭제한다!" 는 것입니다. 데이터가 삭제되면 더이상 작업을 시도하지 않는 것이 당연합니다. 따라서 중괄호(~{...}~) 안에서 실행된 “d” 명령어는 이후의 모든 작업을 중단시킵니다!!

예를 들어, 다음 /substitute/ 명령어는 절대 실행되지 않습니다:

#+begin_src bash
#!/bin/sh
# 이 예제는 잘못된 것입니다.
sed -e '1 {
    d
    s/.*//
}'
#+end_src

앞서 소개한 예제는 C 전처리기 프로그램의 조잡한 버전입니다. 포함시킬 파일 이름이 미리 정해져 있습니다. sed로 고정된 파일 이름 대신 변수(예: “\1”)를 사용할 수 있으면 좋겠지만 아쉽게도 sed는 이런 기능이 없습니다.

이를 우회하려면 sed 명령을 즉석에서 생성하거나 셸 따옴표로 쉘 변수를 sed 스크립트에 전달합니다. cpp와 동일한 방식으로 파일을 포함하는 명령을 만들고 파일 이름이 스크립트 인자라고 가정합니다. 이 스크립트는 다음과 같이 사용합니다:

#+begin_src bash
% include ‘sys/param.h’ <file.c >file.c.new
#+end_src

이를 수행하는 셸 스크립트는 다음과 같습니다:

#+begin_src bash
#!/bin/sh
# 매개변수 내의 '/' 에 주의하세요
# 대체 검색 구분자를 사용하세요
sed -e ‘\_#INCLUDE <’“$1”'>_ {
    r ‘“$1”’
    d
}'
#+end_src

자세히 설명하겠습니다. 다음과 같은 파일을 가정합니다.

#+begin_example
첫 번째 테스트 파일
#INCLUDE <file1>
두 번째 파일 테스트
#INCLUDE <file2>
#+end_example

위와 같은 파일이 있다면,

#+begin_src bash
sed_include1.sh file1 <input | sed_include1.sh file2
#+end_src

명령어로 지정한 파일을 포함할 수 있습니다.


** The # Comment Command
sed를 깊이 파고들수록 주석을 많이 사용할수록 명령어를 이해하기가 더 쉬워집니다. 구버전의 sed는 한 줄 주석만 허용하며 반드시 첫 번째 줄에 위치해야 합니다. SunOS(및 GNU의 sed)는 여러 줄 주석을 허용하며 주석이 반드시 첫 번째 줄에 있을 필요도 없습니다. 마지막 예제는 다음과 같이 주석을 추가합니다:

#+begin_src bash
#!/bin/sh
# 매개변수 내의 '/' 에 주의하세요
# 다른 검색 구분 기호를 사용하세요
sed -e '\_#INCLUDE <'"$1"'>_{

	# 파일을 읽습니다
	r '"$1"'

	# 패턴 영역에 있는 모든 문자를 삭제하고
        # 다음 줄을 읽어옵니다
	d
}'
#+end_src


** Adding, Changing, Inserting new lines
Sed는 출력 스트림에 줄을 추가할 수 있는 세 가지 명령이 있습니다. 줄 단위로 처리되므로 새로운 줄은 별도의 줄에 위치해야 합니다. 별도의 옵션은 없으며 전체 줄을 사용하며 반드시 별도의 줄에 위치해야 합니다.

많은 UNIX 유틸리티에 익숙한 사용자는 sed도 비슷한 규칙을 따를 것을 예상할 수 있습니다. 즉, 이전 줄 끝에 “\” 를 붙여 계속 이어가는 방식입니다. 이 명령어의 구문은 ‘r’ 및 “w” 명령어와 마찬가지로 좀 까다롭습니다.

*** Append a line with 'a'
“a” (/append/)명령어는 지정한 주소나 패턴 *뒤에* 한 줄을 추가합니다. 예제는 “WORD” 가 포함된 모든 줄 뒤에 한 줄을 추가합니다.

#+begin_src bash
#!/bin/sh
sed '
/WORD/ a\
WORD가 포함된 모든 줄 뒤에 이 줄을 추가합니다
'
#+end_src

원한다면 스크립트의 두 줄을 제거할 수 있습니다:

#+begin_src bash
#!/bin/sh
sed '/WORD/ a\WORD가 포함된 모든 줄 뒤에 이 줄을 추가합니다'
#+end_src

저는 첫 번째 구문 형식을 더 선호합니다. 새 줄을 추가하므로 명령을 넣기도 쉽고 사용 의도도 명확하기 때문입니다. “\” 뒤에는 공백이 없어야 합니다!!


*** Insert a line with 'i'
“i” (/insert/)명령어는 지정한 주소나 패턴 *앞에* 새 줄을 삽입합니다:

#+begin_src bash
#!/bin/sh
sed '
/WORD/ i\
WORD가 포함된 모든 줄 앞에 이 줄을 삽입합니다
'
#+end_src


*** Change a line with 'c'
“c” (/change/)명령어는 지정한 (범위) 주소나 패턴 또는 현재 줄을 새로운 줄로 변경합니다.

#+begin_src bash
#!/bin/sh
sed '
/WORD/ c\
현재 줄을 다음 줄로 대체
'
#+end_src

앞서 설명했듯이 “d” 명령어 뒤에 “a” 명령어를 이어서 사용하면 작동하지 않습니다. “d” 명령어는 현재 수행 중인 작업을 종료하기 때문입니다. 중괄호로 세 가지 작업을 결합합니다:

#+begin_src bash
#!/bin/sh
sed '
/WORD/ {
i\
이 줄은 앞에 삽입
a\
이 줄은 뒤에 추가
c\
이 줄로 변경
}'
#+end_src


** Leading tabs and spaces in a sed script
sed는 모든 명령 앞의 탭과 공백을 무시합니다. 하지만 공백 문자가 “a”, “c” 또는 “i” 명령 뒤에 오는 텍스트 시작 부분에 위치할 경우는 무시할 수도 있고 무시하지 않을 수도 있습니다.

SunOS는 이 두 가지 “기능” 모두를 사용할 수 있습니다. 버클리(및 리눅스) 스타일의 sed는 ~/usr/bin~ 에 있으며 AT&T 버전(System V)은 ~/usr/5bin/~ 에 있습니다. 자세히 설명하면 ~/usr/bin/sed~ 명령어는 공백을 유지하는 반면, ~/usr/5bin/sed~ 는 앞쪽 공백을 제거합니다.

앞쪽 공백을 유지하며 사용 중인 sed 버전에 상관 안할려면 다음과 같이 줄 첫 번째 문자에 “\” 를 추가합니다:

#+begin_src bash
#!/bin/sh
sed '
    a\
\    이 줄은 탭으로 시작합니다
'
#+end_src


** Adding more than one line
세 가지 명령어 모두 한 줄 이상 추가할 수 있습니다. 이 경우 각 줄 끝을 “\” 로 마무리합니다. (마지막 줄은 제외)

#+begin_src bash
#!/bin/sh
sed '
/WORD/ a\
이 줄을 추가\
이 줄\
그리고 이 줄
'
#+end_src


** Adding lines and the pattern space
앞서 패턴 공간을 언급했습니다. 대부분의 명령어는 패턴 공간에 작동하며 뒤따르는 명령어는 마지막 명령으로 수정한 결과에 적용됩니다. 앞서 살펴본 세 가지 명령어는 파일 읽기 명령어와 마찬가지로 패턴 공간을 거치지 않고 출력 스트림에 줄을 추가합니다.


** Address ranges and the above commands
일부 명령어는 줄 범위를 지정할 수 있지만 다른 명령어는 그렇지 않다고 말씀드린 것을 기억하실 겁니다. 정확히 말하면 “a”, “i”, “r”, “q” 명령어는 ~1,100~ 이나 ~/begin/,/end/~ 같은 범위를 지정할 수 없습니다!! 설명서에는 /read/ 명령어는 범위를 지정할 수 있다고 나오지만 직접 시도하면 오류가 발생합니다.

“c” /change/ 명령어는 범위를 지정할 수 있으므로 여러 줄을 하나의 줄로 변경할 수 있습니다:

#+begin_src bash
#!/bin/sh
sed '
/begin/,/end/ c\
,***DELETED***
'
#+end_src

범위 작업이 필요할 경우 중괄호로 모든 줄에 작업할 수 있습니다:

#+begin_src bash
#!/bin/sh
# 모든 줄 뒤에 빈 줄 추가
sed '1,$ {
    a\

}'
#+end_src



** Multi-Line Patterns
대부분의 유닉스 유틸리티는 (단일) 줄 단위로 작동합니다. 정규 표현식도 줄 단위로 작동합니다. 따라서 한 줄 이상을 아우르는 패턴을 찾는 것은 쉬운 일이 아닙니다. (힌트: 곧 아주 쉬워질 겁니다.)

Sed는 텍스트를 한 줄 읽어들이고 해당 줄을 수정할 수 있는 명령을 실행하며 필요한 경우 수정된 결과를 출력합니다.

sed 스크립트의 주요 실행 루프(흐름)는 다음과 같습니다:

- 입력 파일에서 줄을 읽어 패턴 공간에 저장합니다.

- 파일 끝이 발견되고 읽을 추가 파일이 있을 경우, 현재 파일을 닫고 다음 파일을 연 다음 새 파일의 첫 번째 줄을 패턴 공간에 저장합니다. 이때 줄 수는 1씩 증가합니다. 새 파일을 연다해서 이 숫자가 재설정되진 않습니다.

- sed 명령을 검사합니다. 명령에 제한 조건이 설정되고 패턴 공간의 현재 줄이 해당 제한 조건을 충족하면 명령이 실행됩니다. “n” 이나 “d” 같은 일부 명령은 실행 루프 맨 위로 돌아가게 합니다. “q” 명령은 sed를 즉시 중지시킵니다. 그렇지 않은 경우 다음 명령을 검사합니다.

- 모든 명령을 검사한 후, sed에 선택적 “-n” 인수가 지정되지 않은 한 패턴 공간을 출력합니다.

명령어 앞의 제한 조건에 따라 해당 명령어가 실행될지 여부가 결정됩니다. 제한 조건이 패턴이고 작업이 삭제 명령어일 경우 다음 명령어는 해당 패턴을 포함한 모든 줄을 삭제합니다:

#+begin_src bash
/PATTERN/ d
#+end_src

제한 조건이 두 개의 숫자 쌍일 경우 줄 번호가 첫 번째 숫자와 같거나 첫 번째 숫자보다 크고 마지막 숫자 이하일 때 삭제가 이루어집니다:

#+begin_src bash
10,20 d
#+end_src

제한 조건이 두 개의 패턴 쌍일 경우, 각 쌍에 변수 하나씩 유지됩니다. 변수가 /false/ 인 상태에서 첫 번째 패턴이 발견되면 변수는 /true/ 로 설정됩니다. 변수가 /true/ 인 경우 명령어가 실행됩니다. 변수가 /true/ 이고 해당 줄에 마지막 패턴이 있다면 명령어를 실행한 후 변수는 비활성화됩니다:

#+begin_src bash
/begin/,/end/ d
#+end_src

휴! 꽤 긴 설명입니다. 여기까지 주의 깊게 읽으셨다면 이 내용을 쉽게 이해할 겁니다. 몇 가지 미묘한 점도 다뤘으니 다시 한번 되짚어 보겠습니다. 제가 선택한 표현은 다분히 의도적입니다. 다음과 같은 특이한 경우도 다룹니다:

#+begin_src bash
# 두 번째 숫자가 첫 번째 숫자보다 작으면 어떻게 될까요?
sed -n ‘20,1 p’ file
#+end_src

그리고

#+begin_src bash
# 줄 번호가 포함된 10줄짜리 파일을 생성하고
# 두 패턴이 겹칠 때 어떤 일이 일어나는지 확인합니다
yes | head -10 | cat -n | \
sed -n -e ‘/1/,/7/ p’ -e '/5/,/9/ p'
#+end_src

이제 정신 고문은 그만!! 표 형식으로 다른 예제를 살펴보겠습니다. 입력 파일에 다음과 같은 줄들이 포함된다고 가정합니다.

#+begin_example
AB
CD
EF
GH
IJ
#+end_example

sed가 시작되면 첫 번째 줄은 패턴 공간에 저장됩니다. 다음 줄은 “CD” 입니다. “n”, ‘d’, “p” 명령어의 작동 방식은 다음과 같이 요약할 수 있습니다.

| 패턴 공간 | 다음 입력 | 명령어 | 출력     | 새로운 패턴 공간 | 새로운 텍스트 입력 |
|-----------+-----------+--------+----------+------------------+--------------------|
| AB        | CD        | n      | <기본값> | CD               | EF                 |
| AB        | CD        | d      | -        | CD               | EF                 |
| AB        | CD        | p      | AB       | CD               | EF                 |

“n” 명령어는 “-n” 플래그 유무에 따라 출력을 생성할 수도 있고 생성하지 않을 수도 있습니다.

이렇게 정리하니 좀 더 이해하기 쉬워졌죠? 여러 줄로 구성된 패턴을 다루기 전에 세 가지 명령어를 설명합니다:


** Print line number with =
“=” (/equal, print line number/)명령어는 현재 줄 번호를 표준 출력으로 표시합니다. 일반적으로 특정 패턴이 포함된 줄 번호를 확인하는 방법은 다음과 같습니다.

#+begin_src bash
# 먼저 줄 번호를 추가하고,
# 그 다음 grep 을 사용하고,
# 마지막으로 번호만 출력합니다.
cat -n file | grep ‘PATTERN’ | awk ‘{print $1}’
#+end_src

sed는 다음과 같이 처리합니다.

#+begin_src bash
sed -n ‘/PATTERN/ =’ file
#+end_src

앞서 파일의 줄 수를 확인하기 위해 다음과 같은 코드를 사용했습니다.

#+begin_src bash
#!/bin/sh
lines=$(wc -l file | awk ‘{print $1}’ )
#+end_src

“=” 명령어를 사용하면 좀 더 간단히 만들 수 있습니다:

#+begin_src bash
#!/bin/sh
lines=$(sed -n ‘$=’ file )
#+end_src

“=” 명령어는 하나의 주소만 허용하므로 특정 범위의 줄 번호를 출력하려면 중괄호를 사용합니다:

#+begin_src bash
#!/bin/sh
# 단순히 줄 번호만 출력
sed -n '/begin/,/end/ {
=
d
}' file
#+end_src

“=” 명령어는 표준 출력으로 출력하므로 패턴과 같은 줄에 줄 번호를 출력할 순 없습니다. 이를 위해선 여러 줄로 구성된 패턴으로 처리해야 합니다.


** Transform with y
단어를 소문자에서 대문자로 바꾸려면, 즉 “a” 를 “A” 로 변환하는 등 26가지 알파벳 문자에 대한 치환 규칙을 작성할 수도 있습니다. Sed는 ~tr~ 프로그램과 유사하게 작동하는 명령어가 있습니다. 바로 “y” (/transform/)명령어입니다.

예를 들어, “a” 부터 “f” 까지의 문자를 대문자로 바꾸려면 다음을 사용합니다.

#+begin_src bash
sed ‘y/abcdef/ABCDEF/’ file
#+end_src

다음은 ~tr~ 명령어와 마찬가지로 모든 대문자를 소문자로 변환하는 sed 예제입니다:

#+begin_src bash
sed ‘y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/’ <uppercase >lowercase
#+end_src

16진수(예: 0x1aff)가 포함된 줄을 대문자(0x1AFF)로 변환하려면 다음을 사용합니다:

#+begin_src bash
sed ‘/0x[0-9a-zA-Z]*/ y/abcdef/ABCDEF’ file
#+end_src

파일에 숫자만 있다면 이 방법도 잘 작동합니다. 하지만 한 줄의 두 번째 단어를 대문자로 바꾸고 싶은데 클래식 sed를 사용한다면 다중 줄 편집 기능을 사용하지 않는 한 처리할 방법은 없습니다. (어라, 뭔가 공통된 주제가 반복되네요!)

하지만 GNU sed는 대문자 및 소문자 변환을 위한 확장 기능이 있습니다.


** Displaying control characters with a l
“l” (/list/)명령어는 현재 패턴 공간을 출력합니다. 따라서 sed 스크립트를 디버깅할 때 유용합니다. 또한 출력할 수 없는 문자를 “\” 문자를 앞에 붙인 8진수 값으로 변환해서 출력합니다. 저는 sed의 미묘한 차이점을 파악하는 과정에서 현재 패턴 공간을 출력하는 기능이 매우 유용하다는 것을 잘 알게 되었습니다.


** Working with Multiple Lines
여러 줄로 구성된 패턴에 사용하는 세 가지 새로운 명령어인 “N”, “D”, “P” 가 있습니다. 이 명령어들이 단일 줄 패턴 명령어인 “n”, “d”, “p” 와 어떤 관련이 있는지 설명하겠습니다.

“n” (/next/)명령어는 (“-n” 플래그가 사용되지 않는 한) 현재 패턴 공간을 출력하고 현재 패턴 공간을 비운 후 다음 입력 줄을 읽어옵니다. “N” 명령어는 현재 패턴 공간을 출력하지 않으며 패턴 공간을 비우지 않습니다. 다음 줄을 읽어들이되 입력 줄 자체와 줄 바꿈 문자를 패턴 공간에 추가합니다.

“d” (/delete/)명령어는 현재 패턴 공간을 삭제하고 다음 줄을 읽어들이고 새로운 줄을 패턴 공간에 넣은 후 현재 명령어는 중단하고 첫 번째 sed 명령어부터 실행을 시작합니다. 이를 새로운 “사이클” 을 시작한다고 표현합니다. “D” 명령어는 새 줄 문자(줄바꿈)에 이르는 패턴 공간의 첫 부분을 삭제하고 나머지 패턴은 그대로 둡니다. “d” 명령과 마찬가지로 현재 명령어를 중지하고 명령어 사이클을 다시 시작합니다. 그러나 현재 패턴 공간을 출력하지 않습니다!! 패턴 공간을 출력하려면 직접 출력해야 합니다. “D” 명령어가 중괄호 안에서 다른 명령어 그룹과 함께 실행되면 “D” 명령어 뒤의 명령어들은 무시됩니다!! 패턴 공간이 비워지지 않는 한 다음 sed 명령어 그룹이 실행됩니다. 패턴 공간이 비워지면 사이클은 처음부터 다시 시작되고 새 줄이 읽힙니다.

“p” (/print/)명령어는 패턴 공간 전체를 출력합니다. “P” 명령어는 패턴 공간의 첫 부분 즉, NEWLINE (개행 또는 줄바꿈)문자까지만 출력합니다. ‘p’ 명령어와 “P” 명령어 모두 패턴 공간을 변경하지 않습니다.

다음 예제처럼 “N” 명령어를 단독 사용하는 것은 그다지 유용하지 않다는 것을 알 수 있습니다. 다음과 같은 필터

#+begin_src bash
sed -e ‘N’
#+end_src

은 입력 스트림을 수정하지 않습니다. 대신, 첫 번째 줄과 두 번째 줄을 합쳐서 출력하고 세 번째 줄과 네 번째 줄을 합쳐서 출력하는 식으로 처리합니다. 이 명령어를 사용하면 새로 추가된 “앵커” 문자인 “\n” 을 사용할 수 있습니다. 이 문자는 패턴 공간에서 여러 줄을 구분하는 줄바꿈 문자와 일치합니다.

예를 들어, “#” 문자로 끝나는 줄을 찾아 그 뒤에 다음 줄을 덧붙이려면 다음과 같이 사용합니다.

#+begin_src bash
#!/bin/sh
sed '
# 줄 끝에서 “#” 을 찾습니다.
/#$/ {
# “#” 을 찾으면 다음 줄을 읽습니다.
    N
# “#” 과 줄 바꿈 문자를 삭제합니다.
    s/#\n//
}' file
#+end_src

“ONE” 과 “TWO” 가 포함된 두 줄을 검색해서 이 두 줄만 연속 출력합니다:

#+begin_src bash
#!/bin/sh
sed -n '
/ONE/ {
# “ONE” 을 찾음 - 다음 줄을 읽어들임
    N
# 두 번째 줄에서 “TWO” 를 찾음
# 있다면 출력함
    /\n.*TWO/ p
}' file
#+end_src

다음 예제는 “ONE” 과 “TWO” 사이의 모든 내용을 삭제합니다:

#+begin_src bash
#!/bin/sh
sed '
/ONE/ {
# 패턴 공간에 한 줄 추가
    N
# 두 번째 줄에서 “TWO” 를 검색
    /\n.*TWO/ {
# 발견됨 - 이제 한 줄로 편집
        s/ONE.*\n.*TWO/ONE TWO/
    }
}' file
#+end_src


** Matching three lines with sed
검색 시 여러 줄을 일괄적으로 일치시킬 수 있습니다.

다음은 “skip3” 문자열을 찾아 해당 문자열이 발견되면 해당 줄과 그 다음 두 줄까지 삭제합니다.

#+begin_src bash
#!/bin/sh
sed '/skip3/ {
           N
           N
           s/skip3\n.*\n.*/# 3 lines deleted/
}'
#+end_src

다음 두 줄의 내용이 무엇이든 상관없다는 점에 유의합니다. 특정 3줄을 일치시키려면 작업이 좀 더 복잡해집니다.

이 스크립트는 첫 번째 줄에 “one”, 두 번째 줄에 ‘two’, 세 번째 줄에 “three” 가 포함된 세 줄을 찾고 해당 줄이 발견되면 “1+2+3” 문자열로 대체합니다:

#+begin_src bash
#!/bin/sh
sed '
/one/ {
      N
      /two/ {
            N
            /three/ {
                    N
                    s/one\ntwo\nthree/1+2+3/
                    }
             }
       }
'
#+end_src


** Matching patterns that span multiple lines
연속된 두 줄에서 특정 패턴을 검색하거나 줄 경계에서 나뉠 수 있는 연속된 두 단어를 검색할 수 있습니다. 다음 예제는 같은 줄에 있거나 하나는 줄 끝, 다른 하나는 다음 줄의 시작 부분에 있는 두 단어를 찾습니다. 해당 단어가 발견되면 첫 번째 단어를 삭제합니다:

#+begin_src bash
#!/bin/sh
sed '
/ONE/ {
# 줄 하나 추가
    N
# 같은 줄에 있는 “ONE TWO”
    s/ONE TWO/TWO/
# 두 연속된 줄에 있는 "ONE
# TWO"
    s/ONE\nTWO/TWO/
}' file
#+end_src

이제 “D” 명령어를 사용합니다. “ONE” 이 포함된 줄 바로 뒤에 “TWO” 가 포함된 줄이 발견되면 첫 번째 줄을 삭제합니다:

#+begin_src bash
#!/bin/sh
sed '
/ONE/ {
# 줄 추가
    N
# “TWO” 가 발견되면 첫 번째 줄 삭제
    /\n.*TWO/ D
}' file
#+end_src

첫 번째 줄을 삭제하는 대신 출력하고 격행(매 두 번째 줄)을 출력하지 않으려면 “D” 를 “P” 로 바꾸고 sed에 “-n” 을 인수를 추가합니다:

#+begin_src bash
#!/bin/sh
sed -n '
# 기본적으로 아무것도 출력하지 않음
/ONE/ {
# 줄 하나 추가
    N
# TWO가 발견되면, 첫 번째 줄
	/\n.*TWO/ P
}' file
#+end_src

이 세 가지 다중 행 명령 모두를 결합하는 것은 흔한 일입니다. 일반적인 순서는 “N”, ‘P’, 그리고 마지막으로 “D” 순서입니다. 다음 코드는 “ONE” 과 “TWO” 가 한 줄 또는 두 줄 연속으로 있을 경우 그 사이의 모든 내용을 삭제합니다:

#+begin_src bash
#!/bin/sh
sed '
/ONE/ {
# 다음 줄 추가
    N
# “ONE” 뒤에 “TWO” 가 오는 부분 찾기
    /ONE.*TWO/ {
#    그 사이의 모든 내용 삭제
        s/ONE.*TWO/ONE TWO/
#    출력
        P
#    그런 다음 첫 번째 줄 삭제
        D
    }
}' file
#+end_src

앞서 “=” 명령어로 파일에 줄 번호를 출력하는 방법을 설명했습니다. 이를 처리하려면 sed를 두 번 호출합니다(한 번으로 처리하는 방법도 있지만 그 내용은 다음 섹션에 다룹니다). 첫 번째 sed 명령어는 한 줄에 줄 번호를 출력하고 다음 줄에 해당 줄의 내용을 출력합니다. 두 번째 sed 명령어는 이 두 줄을 하나로 병합합니다:

#+begin_src bash
#!/bin/sh
sed ‘=’ file | \
sed '{
    N
    s/\n/ /
}'
#+end_src

필요하면 한 줄을 두 줄로 나누고 각각 편집한 후 다시 병합할 수도 있습니다. 예를 들어, 16진수 뒤에 단어가 오는 파일에서 첫 번째 단어를 대문자로 모두 변환하려면 “y” 명령을 사용할 수 있지만, 먼저 해당 줄을 두 줄로 분할한 다음 그 중 하나를 변경하고 다시 병합해야 합니다. 즉,

#+begin_example
0x1fff table2
#+end_example

라는 줄은 다음과 같이 두 줄로 변경됩니다:

#+begin_example
0x1fff
table2
#+end_example

그리고 첫 번째 줄은 대문자로 변환됩니다. ~tr~ 로 공백을 새 줄로 변환한 다음, sed로 나머지 작업을 수행합니다. 명령어는 다음과 같습니다.

#+begin_src bash
./sed_split <file
#+end_src

그리고 /sed_split/ 은 다음과 같습니다.

#+begin_src bash
#!/bin/sh
tr ‘ ’ '\012' |
sed ' {
    y/abcdef/ABCDEF/
    N
    s/\n/ /
}'
#+end_src

이상하게 보이겠지만 ~tr~ 대신 sed를 사용할 수도 있습니다. /substitute/ 명령어에 줄 바꿈을 삽입할 수 있지만 백슬래시로 이스케이프 처리해야 합니다. /substitute/ 명령어 왼쪽에는 “\n” 을, 오른쪽에는 삽입된 줄바꿈을 사용한다는 점이 아쉽습니다. 한숨만 나옵니다. 다음은 예시입니다:

#+begin_src bash
#!/bin/sh
sed '
s/ /\
/' | \
sed ' {
    y/abcdef/ABCDEF/
    N
    s/\n/ /
}'
#+end_src

때로는 마커로 특수 문자를 추가하고 입력 스트림에서 해당 문자를 찾기도 합니다. 이 문자가 발견되면 그곳에 공백이 있었음을 의미합니다. 백슬래시도 좋은 문자지만 백슬래시로 이스케이프 처리해야 하고 sed 스크립트를 난해하게 만든다는 단점이 있습니다. 바보같은 질문만 하는 사람한테나 써줍니다.

공백을 “\” 와 그 뒤의 새 줄로 바꾸는 sed 스크립트는 다음과 같습니다:

#+begin_src bash
#!/bin/sh
sed 's/ /\\\
/' file
#+end_src

네. 바로 이겁니다. 아니면 C셸로 그를 완전히 헷갈리게 만듭니다!

#+begin_src bash
#!/bin/csh -f
sed '\
s/ /\\\\
/' file
#+end_src

이런 예제를 몇 개 더 보여주면 그 사람은 두 번 다신 당신에게 질문하지 않을 겁니다! 제가 좀 과장한 것 같네요...

지금까지 다룬 기능을 정리한 표로 마무리합니다:

| Pattern Space | Next Input | Command | Output    | New Pattern Space | New Text Input |
|---------------+------------+---------+-----------+-------------------+----------------|
| AB            | CD         | n       | <default> | CD                | EF             |
| AB            | CD         | N       | -         | AB\nCD            | EF             |
| AB            | CD         | d       | -         | -                 | EF             |
| AB            | CD         | D       | -         | -                 | EF             |
| AB            | CD         | p       | AB        | AB                | CD             |
| AB            | CD         | P       | AB        | AB                | CD             |
| AB\nCD        | EF         | n       | <default> | EF                | GH             |
| AB\nCD        | EF         | N       | -         | AB\nCD\nEF        | GH             |
| AB\nCD        | EF         | d       | -         | EF                | GH             |
| AB\nCD        | EF         | D       | -         | CD                | EF             |
| AB\nCD        | EF         | p       | AB\nCD    | AB\nCD            | EF             |
| AB\nCD        | EF         | P       | AB        | AB\nCD            | EF             |



** Using newlines in sed scripts
때때로 sed 스크립트에서 줄바꿈 문자를 사용할 때가 있습니다. 그런데 미묘한 문제가 있습니다. 줄바꿈을 검색하려면 “\n” 을 사용합니다. 다음은 특정 구문을 검색한 후 그 구문 뒤의 줄바꿈 문자를 삭제해서 두 줄을 하나로 합치는 예시입니다.

#+begin_src bash
(echo a;echo x;echo y) | sed '/x$/ {
N
s:x\n:x:
}'
#+end_src

이 명령어는 다음과 같은 결과를 생성합니다.

#+begin_example
a
xy
#+end_example

하지만 새 줄을 삽입할 때는 “\n” 을 사용하지 말고 대신 리터럴 새 줄 문자를 삽입합니다!!

#+begin_src bash
(echo a;echo x;echo y) | sed 's:x:X\
:'
#+end_src

이 명령어는 다음과 같은 결과를 생성합니다.

#+begin_example
a
X

y
#+end_example


** The Hold Buffer
지금까지 sed의 세 가지 개념을 살펴봤습니다:

(1) 수정되기 전의 입력 스트림 또는 데이터,
(2) 수정된 이후의 출력 스트림 또는 데이터, 그리고
(3) 패턴 공간 즉, 수정되고 출력 스트림으로 전송하는 문자들을 포함한 버퍼입니다.

다뤄야할 ‘위치’ (저장소)가 하나 더 있습니다. 홀드 버퍼(/hold buffer/) 또는 홀드 공간(/hold space/)입니다. 이를 "여분의 패턴 버퍼" 라 생각합니다. 이 버퍼는 패턴 공간의 데이터를 나중에 사용할 수 있도록 ‘복사’ 하거나 ‘기억’ 하는 용도로 사용합니다.

홀드 버퍼를 사용하는 명령어는 다섯 가지입니다.

** Exchange with x
“x” (/exchange/)명령어는 패턴 영역과 홀드 버퍼의 내용을 서로 교환합니다. 이 명령어 자체는 별다른 용도가 없습니다. 다음 sed 명령어

#+begin_src bash
sed ‘x’
#+end_src

를 필터로 실행하면 맨 앞에 빈 줄이 추가되고 마지막 줄은 삭제됩니다. 입력 스트림에 큰 변화가 없는 것처럼 보이지만 sed는 모든 줄을 수정합니다.

홀드 버퍼는 처음에 빈 줄을 포함합니다. “x” 명령어로 첫 번째 줄을 수정하면 첫 번째 줄은 홀드 버퍼에 저장되고 빈 줄은 첫 번째 줄의 자리를 차지합니다. 두 번째 “x” 명령어는 두 번째 줄을 첫 번째 줄이 들어 있는 홀드 버퍼와 교환합니다. 이후의 각 줄은 바로 앞의 줄과 교환됩니다. 마지막 줄은 홀드 버퍼에 저장되지만 교환되지 않으므로 프로그램을 종료할 때 홀드 버퍼에 그대로 남고 출력되지 않습니다. 이는 홀드 버퍼에 데이터를 저장할 때 주의해야 함을 의미합니다. 명시적으로 요청하지 않는 한 해당 데이터를 출력하지 않기 때문입니다.


** Example of Context Grep
홀드 버퍼의 주된 용도는 이전 줄을 기억하는 것입니다. 예를 들어, 패턴과 일치한 줄을 표시하는 ~grep~ 과 유사한 기능을 처리하는 유틸리티가 있습니다. 또한 이 유틸리티는 패턴 앞뒤의 줄도 함께 표시합니다. 즉, 8번째 줄에 패턴이 포함되면 이 유틸리티는 7, 8, 9번 줄을 출력합니다.

이를 구현하는 방법은 해당 줄에 패턴이 있는지 확인하는 것입니다. 패턴이 없으면 현재 줄을 홀드 버퍼에 저장합니다. 패턴이 있으면 홀드 버퍼에 저장된 줄을 출력한 다음 현재 줄과 다음 줄을 차례로 출력합니다. 각 명령어 세트가 끝날 때마다 대시 세 개를 출력합니다. 또한, 이 스크립트는 인수(매개 변수)를 확인하며 인수가 없으면 오류 메시지를 출력합니다. 이처럼 sed 스크립트에 인수를 전달하려면 작은따옴표 처리 메커니즘을 비활성화하고 스크립트에 “$1” 을 삽입한 다음 다시 작은따옴표 처리를 활성화합니다:

#+begin_src bash
#!/bin/sh
# grep3 - 패턴 중심으로 세 줄을 출력합니다
# 인수가 하나뿐이면 종료합니다

case $# in
    1);;
	,*) echo “사용법: $0 패턴”;exit;;
esac;
# 인자에 / 가 포함되지 않기를 바랍니다
# 포함되면 sed에서 오류가 발생합니다

# sed -n 을 사용해서 출력 비활성화
# 명시적으로 요청하지 않는 한
sed -n '
‘/“$1”/’ !{
    # 일치 항목 없음 - 현재 줄을 홀드 버퍼에 저장
    x
    # 이전 줄을 삭제합니다. 이 줄은 현재 패턴 버퍼에 있습니다
    d
}
‘/“$1”/’ {
    # 일치 항목 있음 - 마지막 줄 가져오기
    x
    # 출력
    p
    # 원래 줄을 다시 가져오기
    x
    # 출력
    p
    # 다음 줄 가져오기
    n
    # 출력
    p
    # 이제 마커로 대시 세 개 추가
    a\
---
    # 이 줄을 홀드 버퍼에 저장
    x
}'
#+end_src

이 스크립트로 키워드 중심의 세 줄을 표시할 수 있습니다. 예를 들어:

#+begin_src bash
grep3 vt100 </etc/termcap
#+end_src


** Hold with h or H
“x” 명령어는 홀드 버퍼와 패턴 버퍼의 위치를 바꿉니다. 이는 두 버퍼 모두 변경됩니다. “h” 명령어는 패턴 버퍼의 내용을 홀드 버퍼로 복사합니다. 패턴 버퍼는 변경되지 않습니다. 위와 동일한 스크립트에서 /hold/ 명령어를 사용한 예는 다음과 같습니다.

#+begin_src bash
#!/bin/sh
# grep3 버전 b - hold 명령어를 사용하는 또 다른 버전
# 인수가 하나뿐이면 종료

case $# in
    1);;
	,*) echo “사용법: $0 패턴”;exit;;
esac;
    # 다시 한 번 - 인자에 / 가 포함되지 않기를 바랍니다
    # sed -n 을 사용해서 출력 비활성화

sed -n '
‘/“$1”/’ !{
    # 일치하지 않는 줄을 홀드 버퍼에 넣습니다
    h
}
'/“$1”/' {
    # 일치하는 줄을 찾음
    # 홀드 버퍼에 추가
    H
    # 홀드 버퍼에 2줄이 있음
    # 다음 줄 가져오기
    n
    # 홀드 버퍼에 추가
    H
    # 이제 패턴 공간으로 다시 출력
    x
    # 출력.
    p
    # 마커로 하이픈 3개를 추가
    a\
---
}'
#+end_src


** Keeping more than one line in the hold buffer
“H” 명령을 사용하면 홀드 버퍼에 여러 줄을 결합할 수 있습니다. 이 명령은 줄을 버퍼에 추가할 때 줄 사이에 “\n” 을 삽입한다는 점은 “N” 명령과 유사합니다. 홀드 버퍼에 여러 줄을 저장했다가 나중에 특정 패턴이 발견될 때만 이를 출력합니다.

예를 들어, 줄의 첫 번째 문자를 줄 이어쓰기 문자로 사용하는 파일을 가정합니다. ~/etc/termcap~, ~/etc/printcap~, ~makefile~ 및 메일 메시지 파일은 공백이나 탭을 사용해서 항목의 이어쓰기를 나타냅니다. 특정 단어 앞의 항목을 출력하려면 다음 스크립트를 사용합니다. 실제 탭 문자를 나타내기 위해 “^I” 를 사용합니다:

#+begin_src bash
#!/bin/sh
# 이전 항목 출력
sed -n '
/^[ ^I]/!{
    # 줄이 공백이나 탭으로 시작하지 않는 경우,
    # 관심있는 패턴이 포함되어 있는가?
    ‘/“$1”/’ {
        # 그렇다면 대시 세 개 출력
        i\
---
        # 홀드 버퍼를 가져와 현재 줄 저장
        x
	# 이제 홀드 버퍼에 있던 내용을 출력
        p
        # 원래 줄을 다시 가져옴
        x
    }
    # 홀드 버퍼에 저장
    h
}
# 공백이나 탭으로 시작하는 줄은 어떻게 처리할까?
/^[ ^I]/ {
    # 홀드 버퍼에 추가
    H
}'
#+end_src

“H” 명령어로 ~grep~ 의 검색 범위를 확장할 수 있습니다. 이 예제에서 프로그램은 패턴 앞의 한 줄 대신 두 줄을 출력합니다. 이를 두 줄로 제한하는 방법은 “s” 명령어로 줄바꿈 하나만 남기고 나머지 줄은 삭제합니다. 저는 이것을 /grep4/ 라 부릅니다:

#+begin_src bash
#!/bin/sh

# grep4: 패턴 중심으로 4줄을 출력합니다
# 인수가 하나뿐이면 종료합니다

case $# in
    1);;
    ,*) echo “사용법: $0 패턴”;exit;;
esac;

sed -n '
‘/“$1”/’ !{
    # 일치하지 않음 - 이 줄을 홀드 공간에 추가합니다
    H
    # 이를 패턴 공간으로 다시 가져옴
    x
    # 두 줄의 경우 .*\n.* 과 같음
    # 세 줄의 경우 .*\n.*\n.* 과 같음
    # 여분의 줄 삭제 - 두 줄만 남김
    s/^.*\n\(.*\n.*\)$/\1/
    # 이제 (최대) 두 줄을 홀드 버퍼에 다시 넣음
	x
}
‘/“$1”/’ {
    # 일치하면 - 현재 줄을 추가
    H
    # 다음 줄 가져오기
    n
    # 그 줄도 추가
    H
    # 다시 패턴 공간으로 되돌리되, 현재 줄은
    # 홀드 버퍼에 남겨둡니다. 이 줄은 패턴 다음의 줄이며,
    # 다음 줄에 원하는 패턴이 있을 경우를 대비해
    # 홀드 버퍼에 저장합니다
    x
    # 4줄을 출력
    p
    # 마크 추가
    a\
---
}'
#+end_src

이 스크립트를 조금 수정하면 패턴 중심으로 원하는 줄 수만큼 출력할 수 있습니다. 보다시피, 홀드 버퍼에 무엇이 들어있는지 패턴 버퍼에 무엇이 들어있는지를 기억해야 합니다. 동일한 루틴을 작성하는 다른 방법도 있습니다.


** Get with g or G
홀드 공간과 패턴 공간을 바꾸는 대신 “g” 명령어로 홀드 공간을 패턴 공간으로 복사합니다. 이 명령어는 패턴 공간을 삭제합니다!! 패턴 공간에 내용을 추가하려면 “G” 명령어를 사용합니다. 이 명령어는 패턴 공간에 새 줄을 추가하고 새 줄 뒤에 홀드 공간의 내용을 복사합니다.

다음은 “grep3” 명령어의 또 다른 버전입니다. 이전 버전과 똑같이 작동하지만 구현 방식이 다릅니다. sed는 문제를 해결하는 데 여러 가지 방법을 가지고 있음을 잘 보여줍니다. 여기서 중요한 것은 문제를 정확히 이해하고 해결책을 문서화하는 것입니다:

#+begin_src bash
#!/bin/sh
# grep3 버전: H 대신 ‘G’ 사용
# 인수가 하나뿐이면 종료

case $# in
    1);;
    ,*) echo “사용법: $0 패턴”;exit;;
esac;

# 다시 말하지만, 인수에 '/' 가 포함되지 않기를 바랍니다

sed -n '
‘/“$1”/’ !{
    # 일치하지 않는 줄을 홀드 버퍼에 넣음
    h
}
‘/“$1”/’ {
    # 일치하는 줄을 찾음
    # 다음 줄을 패턴 공간에 추가
    N
    # 이전 줄과 패턴 공간의 2번째 줄을 교환
    x
    # 이제 두 줄을 다시 합침
    G
    # 그리고 출력
    p
    # 마커로 하이픈 3개를 추가
    a\
---
    # 처음 2줄 제거
    s/.*\n.*\n\(.*\)$/\1/
    # 다음 번을 위해 홀드 버퍼에 저장
    h
}'
#+end_src

“G” 명령어를 사용하면 한 줄을 두 개로 복제합니다. 첫 번째 16진수 숫자를 대문자로 변환하고 싶지만 앞서 설명한 /sed_split.sh/ 스크립트는 사용하지 않는다고 가정합니다. 해당 스크립트는 한 줄에 정확히 두 개의 단어가 있을 때만 작동합니다. 한 줄에 두 개 이상의 단어가 포함될 수 있도록 허용하면서 첫 번째 16진수 단어만 대문자로 변환하려면 다음 방법이 좀 더 적합합니다:

#+begin_src bash
#!/bin/sh
# 첫 번째 16진수 숫자를 대문자 형식으로 변환하고, 나머지 줄 내용은 그대로 둠
# sed를 두 번 사용
# 필터로 사용
# convert2uc <in>out
sed '
s/ /\
/' | \
sed ' {
    y/abcdef/ABCDEF/
    N
    s/\n/ /
}'
#+end_src

다음은 “h” 및 “G” 명령으로 sed를 두 번 호출할 필요가 없는 해결 방법입니다:

#+begin_src bash
#!/bin/sh
# convert2uc 버전 b
# 첫 번째 16진수 숫자를 대문자 형식으로 변경하고 나머지 줄은 그대로 둡니다
# sed를 한 번만 호출합니다
# 필터로 사용합니다
# convert2uc <in >out
sed '
{
    # 줄을 기억합니다
    h
    # 현재 줄을 대문자로 변경
    y/abcdef/ABCDEF/
    # 원래 줄을 다시 추가
    G
    # 첫 번째 줄의 첫 번째 단어와
    # 두 번째 줄의 두 번째 단어를
    # 하나의 거대한 정규 표현식을 사용해서 추출
    s/^\([^ ]*\) .*\n[^ ]* \(.*\)/\1 \2/
}'
#+end_src

/Carl Henrik Lunde/ 는 이 과정을 간단히 만들 수 있는 방법을 제안했지만 범용성이 다소 떨어집니다. 이전 두 버전은 여러 단어가 포함된 줄을 변환할 수 있습니다. 이 버전은 첫 번째 단어와 마지막 단어, 즉 두 단어만 변환합니다. 대신 그 사이의 단어는 모두 삭제합니다.

#+begin_src bash
  #!/bin/sh
  # convert2uc 버전 b
  # 첫 번째 16진수 숫자를 대문자 형식으로 변환하고 마지막 단어는 유지합니다.
  # 중간의 단어들이 삭제된다는 점에 유의합니다.
  # sed를 한 번만 호출합니다.
  # 필터로 사용합니다.
  # convert2uc <in>out
  sed '
  {
      # 줄을 기억합니다.
      h
      # 현재 줄을 대문자로 변경합니다.
      y/abcdef/ABCDEF/
      # 원래 줄을 다시 추가
      G
      # 첫 번째 줄의 첫 번째 단어와
      # 두 번째 줄의 마지막 단어를 유지
      # 하나의 거대한 정규 표현식을 사용해서
      # 첫 번째와 마지막 단어 외에는 모두 삭제
      s/ .* / / 
  }'
#+end_src

이 예제는 “a” 부터 “f” 까지 글자만 대문자로 변환합니다. 이는 좁은 범위를 출력하기 쉽게 만들기 위해 선택한 방식입니다. 모든 글자를 대문자로 변환하거나 첫 글자 또는 두 번째 단어 등으로 변경하도록 스크립트를 수정할 수 있습니다.


** Branch (Flow Control)
sed를 배우다 보면 sed에 "프로그래밍 언어가 있다" 는 것을 알게 됩니다. 물론 이 언어는 아주 특화되어 있고 아주 단순합니다. 흐름 제어 방식을 변경할 수 있는 방법이 없다면 어떤 언어가 완전하다고 말할 수 있을까요?

sed는 이를 위한 세 가지 명령어가 있습니다. 콜론(:) 앞에 문자열을 붙여 레이블(/label/)을 지정합니다. “b” (/branch/)명령어는 레이블로 분기합니다. 레이블은 명령어 뒤에 위치합니다. 레이블이 없으면 스크립트 끝으로 분기합니다. “t” (/test/)명령어는 조건을 테스트할 용도로 사용합니다.

‘t’ 명령어를 설명하기 전에 먼저 “b” 명령어를 사용한 예제를 보여드리겠습니다. 예제는 단락을 기억했다가 (인수로 지정된) 패턴이 포함된 경우 해당 단락 전체를 출력합니다.

#+begin_src bash
#!/bin/sh
sed -n '
# 빈 줄이면 단락 확인
/^$/ b para
# 그렇지 않으면 홀드 버퍼에 추가
H
# 파일 끝에서 단락 확인
$ b para
# 이제 스크립트 끝으로 분기
b
# 여기서 단락에 패턴이 있는지 확인
:para
# 전체 단락을 패턴 공간으로 반환
x
# 패턴을 찾고 있다면 출력
/‘“$1”’/ p
'
#+end_src


** Testing with t
패턴이 발견되면 분기를 실행합니다. 치환이 이루어진 경우만 분기할 수 있습니다. “t label” 명령은 마지막 치환 명령이 패턴 공간을 수정한 경우만 해당 레이블로 분기합니다.

이 기능의 주된 용도는 재귀 패턴입니다. 괄호 내부의 공백을 제거한다고 가정합니다. 괄호는 중첩될 수 있습니다. 즉, “( ( ( ())) )” 같은 문자열을 삭제합니다. 다음 sed 표현식

#+begin_src bash
sed ‘s/([ ^I]*)/g’
#+end_src

은 가장 안쪽의 괄호 세트만 제거합니다. 각 괄호 쌍 모두 제거하려면 데이터를 스크립트로 네 번 파이프합니다. 정규 표현식

#+begin_src bash
sed ‘s/([ ^I()]*)/g’
#+end_src

를 사용할 수 있지만 이 경우 일치하지 않는 괄호 쌍도 삭제합니다. “t” 명령어로 이 문제를 해결할 수 있습니다:

#+begin_src bash
#!/bin/sh
sed '
:again
    s/([ ^I]*)//
    t again
'
#+end_src

이전 버전은 ‘s’ 표현식 뒤에 'g' 가 있었지만 이젠 필요하지 않습니다.


** Debugging with l
'l' (/list/)명령어는 패턴 영역을 보다 명확한 형태로 출력합니다. 비출력 문자는 C 스타일의 이스케이프 형식으로 출력됩니다.

이는 복잡한 여러 줄로 구성된 sed 스크립트를 디버깅할 때 유용합니다.


** An alternate way of adding comments
주석을 지원하지 않는 sed 스크립트에 주석을 추가할 방법이 있습니다. 줄 번호를 0 으로 지정해서 “a” 명령어를 사용합니다:

#+begin_src bash
#!/bin/sh
sed '
/begin/ {
0i\
    이것은 주석입니다\
    여러 줄로 작성할 수 있습니다\
    모든 버전의 sed에서 작동합니다
}'
#+end_src


** The poorly documented ;
문서에 제대로 설명되지 않은 sed 명령어가 있습니다. 바로 “;” 명령어입니다. 이 명령어로 여러 개의 sed 명령어를 한 줄로 결합합니다. 다음은 앞서 설명한 /grep4/ 스크립트인데 주석과 오류 확인 루틴을 제거하고 명령어 사이에 세미콜론을 넣은 간소화된 버전입니다:

#+begin_src bash
#!/bin/sh
sed -n '
‘/“$1”/’ !{;H;x;s/^.*\n\(.*\n.*\)$/\1/;x;}
‘/“$1”/’ {;H;n;H;x;p;a\
---
}'
#+end_src

네, 맞습니다! 확실히 인내심을 기르는 과정입니다. 하지만 요점은 충분히 전달된 것 같습니다. 제 생각에 세미콜론이 유용한 유일한 경우는 명령줄에서 sed 스크립트를 입력할 때 뿐입니다. 스크립트에 넣을거면 가독성 좋게 형식을 정리합니다.

앞서 언급했듯이 많은 버전의 sed는 첫 번째 줄을 제외하고 주석을 지원하지 않습니다. 스크립트를 작성할 때는 주석을 넣고 배포할 때는 주석을 제거한 ‘바이너리’ 형태로 설치하는 방법을 고려합니다. 그리 어렵진 않을 겁니다. 어쨌든 여러분은 이제 sed의 달인이니까요. 따라서 주석을 제거하는 스크립트를 작성하는 방법은 굳이 설명하지 않겠습니다. 그건 여러분의 지능을 무시하는 것이니까요.

또한, 일부 운영 체제에선 세미콜론을 사용할 수 없습니다. 따라서 세미콜론이 포함된 스크립트인데 리눅스가 아닌 시스템에서 작동하지 않는다면 세미콜론을 줄바꿈 문자로 대체합니다. (csh/tcsh를 사용하지 않는 한 말입니다. 하지만 그건 전혀 다른 주제입니다.)


** Passing regular expressions as arguments
이전 스크립트에서 슬래시가 포함된 인수를 스크립트에 전달하면 문제가 발생한다고 수차례 언급했습니다. 사실, 정규 표현식도 문제를 일으킬 수 있습니다. 다음과 같은 스크립트는 언젠가 오류가 발생할 수밖에 없습니다:

#+begin_src bash
#!/bin/sh
sed ‘s/’“$1”‘//g’
#+end_src

인수에 ~/\.*[]^$~ 문자 중 하나라도 포함되면 스크립트는 제대로 작동하지 않습니다.  예를 들어, 누군가 “/” 를 입력하면 /substitute/ 명령어는 세 개가 아닌 네 개의 구분 기호로 인식합니다. 또한 “]” 없이 “]” 를 제공하면 구문 오류가 발생합니다.

해결책은 사용자가 인수를 전달할 때 이런 문자 앞에 백슬래시 문자를 붙이는 방법입니다. 하지만 사용자는 어떤 문자가 특수 문자인지 알아야 합니다. 다른 해결책은 스크립트 내에서 특수 문자 앞에 백슬래시를 자동으로 추가하는 방법입니다.

#+begin_src bash
#!/bin/sh
# 다음 문자 앞에 백슬래시 두 개를 추가합니다: ][^$.*/
# 첫 번째 ']' 에는 백슬래시가 필요하지 않다는 점에 유의합니다
arg=$(echo “$1” | sed ‘s:[]\[\^\$\.\*\/]:\\\\&:g’)
# 쉘이 따옴표 안의 이중 백슬래시를 단일 백슬래시로 변환하므로 두 개의 백슬래시가 필요합니다.
sed ‘s/’“$arg”‘//g’
#+end_src

예를 들어, ~^../,~ 패턴의 경우 이 스크립트는 sed로 전달하기 전에 ~\^\.\.\/~ 로 변환합니다.


** Inserting binary characters
이진 문자를 다루는 것은 매우 까다롭고 특히 사람이 읽는 스크립트 작성시엔 더욱 그렇습니다. EMACS 같은 편집기를 사용하면 이진 문자를 삽입할 수 있지만 이진 문자를 표시하면 터미널에서 사용자에게 잘 보이도록 문자를 변경할 수도 있습니다.

스크립트를 이식성 높게 만들기 위한 쉬운 방법은 ~tr~ (1) 명령어를 사용하는 방법입니다. 이 명령어는 8진수 표기법을 인식하며 결과를 변수에 저장할 수 있습니다.

다음은 “ding” 문자열을 ASCII 벨 문자로 대체하는 스크립트입니다.

#+begin_src bash
#!/bin/sh
BELL=$(echo x | tr ‘x’ '\007')
sed “s/ding/$BELL/”
#+end_src

여기서 큰따옴표를 사용했다는 점에 유의합니다. 특수 문자로 해석되므로 이 기법을 사용할 때는 주의합니다.


** GNU sed Command Line arguments
유닉스 시스템 관례 중 하나는 명령줄 인수에 단일 문자를 사용하는 것입니다. 입력 속도가 빨라지고 길이도 짧아지므로 대회에 참가할 때는 유리합니다. 일반 사용자는 종종 sed의 간결한 표현 방식을 이해하기 어렵게 느낍니다. 긴 단어 형태의 옵션을 사용하면 sed 스크립트의 가독성을 높일 수 있습니다. 즉, 다음과 같이 입력하는 대신

#+begin_src bash
sed -n 20p
#+end_src

-n 인수의 긴 버전을 입력합니다.

#+begin_src bash
sed --quiet 20p
#+end_src

또는

#+begin_src bash
sed --silent 20p
#+end_src

sed의 긴 형식 명령줄 인수는 이름 앞에 항상 하이픈 2개가 붙습니다. GNU sed는 다음과 같은 긴 형식 명령줄 인수가 있습니다:

*GNU Command Line Arguments*

| Short Form    | Long Form           |
|---------------+---------------------|
| -n            | --quiet             |
|               | --silent            |
| -e script     | --expression=SCRIPT |
| -f SCRIPTFILE | --file=SCRIPTFILE   |
| -i[SUFFIX]    | --in-place[=SUFFIX] |
| -l N          | --line-length=N     |
|               | --posix             |
| -b            | --binary            |
|               | --follow-symlinks   |
| -r            | --regular-extended  |
| -s            | --separate          |
| -u            | --unbuffered        |
|               | --help              |
|               | --version           |

하나씩 설명합니다.

*** The -posix argument
GNU 버전의 sed는 다른 버전에서 사용할 수 없는 수많은 기능이 포함되어 있습니다. 이식성이 중요할 경우 ~-posix~ 옵션으로 스크립트를 테스트합니다. 버전 번호를 확인하기 위해 ‘v’ 명령 같이 GNU sed의 기능을 사용한 예제가 있다면 예를 들어 다음과 같은 경우입니다.

#+begin_src bash
#이것은 sed 명령 파일입니다
v 4.0.1
# 줄 수 출력
$=
#+end_src

그리고 다음 명령으로 실행했다면

#+begin_src bash
sed -nf sedfile --posix <file
#+end_src

GNU 버전의 sed 프로그램은 해당 sed 스크립트가 호환되지 않는다는 경고를 표시합니다. 즉 다음과 같은 메시지를 출력합니다:

#+begin_example
sed: -e expression #1, char 2: unknown command: `v'
#+end_example


*** The --version argument
GNU ~sed --version~ 명령어는 현재 사용 중인 sed 버전을 확인합니다. 제 컴퓨터는 다음과 같은 결과를 출력합니다.

#+begin_example
# sed --version
GNU sed version 4.2.1
Copyright (C) 2009 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE,
to the extent permitted by law.

GNU sed home page: <https://www.gnu.org/software/sed/>.
General help using GNU software: <https://www.gnu.org/gethelp/>.
E-mail bug reports to: <bug-gnu-utils@gnu.org>.
Be sure to include the word ``sed'' somewhere in the ``Subject:'' field.
#+end_example

*** The -h Help argument
-h 옵션은 sed 명령어의 요약 정보를 표시합니다. 긴 형식은 다음과 같습니다.

#+begin_src bash
sed --help
#+end_src

이 명령어는 명령줄 인자에 대한 알기 쉬운 요약 정보를 제공합니다.

*** The -l Line Length Argument
'l' 명령은 이미 설명했습니다. ‘l’ 명령의 기본 줄 표시 너비는 70자입니다. 이 값은 ‘-l N’ 옵션을 추가하고 ‘-l’ 뒤에 숫자를 지정해서 최대 줄 길이를 설정해서 변경할 수 있습니다.

#+begin_src bash
sed -n -l 80 ‘l’ <file
#+end_src

긴 형식은 다음과 같습니다.

#+begin_src bash
sed -n --line-length=80 ‘l’ <파일
#+end_src

*** The -s Separate argument
일반적으로 명령줄에서 여러 파일을 지정하면 sed는 해당 파일들을 하나의 스트림으로 결합한 다음 그 단일 스트림에 작업을 수행합니다. 각각 100줄로 구성된 세 개의 파일이 있다면 다음 명령어

#+begin_src bash
sed -n ‘1,10 p’ file1 file2 file3
#+end_src

는 file1 파일의 첫 10줄만 출력합니다. '-s' 옵션은 GNU sed에게 각 파일을 독립적인 파일로 취급하도록 지시하며 각 파일의 처음 10줄을 출력합니다. 이는 ~head~ 명령어와 유사합니다.

다른 예를 들겠습니다. 각 파일의 줄 수를 출력하려면 ~wc -l~ 을 사용합니다. 각 파일의 줄 수와 파일 이름을 출력하고 마지막에 전체 줄 수를 출력합니다. 다음은 sed로 이와 유사한 작업을 수행하는 간단한 셸 스크립트입니다:

#+begin_src bash
#!/bin/sh
FILES=$*
sed -s -n ‘$=’ $FILES    # 각 파일의 줄 수 출력
sed -n ‘$=’ $FILES       # 전체 줄 수 출력.
#+end_src

~wc -l~ 명령어는 위의 스크립트와 달리 파일 이름도 출력합니다. ~wc -l~ 명령어를 모방하려면 루프로 명령어를 실행하고 파일 이름을 출력합니다. 다음은 이를 수행하는 좀 더 고급 스크립트지만 ‘-s’ 옵션을 사용하지 않습니다:

#+begin_src bash
#!/bin/sh
for F in “$@”
do
 NL=$(sed -n ‘$=’ < “$F” ) &&  printf “  %d %s\n” $NL “$F”
done
TOTAL=$(sed -n ‘$=’ “$@”)
printf “  %d total\n” $TOTAL
#+end_src


*** The -i in-place argument
‘여러 파일 편집하기’ 섹션에서 제가 선호하는 방법을 이미 설명했습니다. 좀 더 간단한 방법을 원하시는 분을 위해 GNU Sed는 “-i” 라는 명령줄 옵션으로 이 작업을 수행합니다. 각 줄 앞에 탭을 추가하는 것 같은 간단한 변경을 수행한다고 가정합니다.

다음은 현재 디렉토리에서 확장자가 ‘.txt’ 인 모든 파일에 작업을 수행합니다.

#+begin_src bash
sed -i ‘s/^/\t/’ *.txt
#+end_src

긴 인자 형식은 다음과 같습니다.

#+begin_src bash
sed --in-place ‘s/^/\t/’ *.txt
#+end_src

이 옵션은 원본 파일을 삭제합니다!! 저처럼 신중한 분이라면 원본 파일의 사본을 보관하기 위해 확장자를 지정하는 방법을 선호할 수 있습니다:

#+begin_src bash
sed -i.tmp ‘s/^/\t/’ *.txt
#+end_src

그리고 긴 인자 이름 형식은 다음과 같습니다.

#+begin_src bash
sed --in-place=.tmp ‘s/^/\t/’  *.txt
#+end_src

마지막 두 버전의 경우 “a.txt” 파일의 원본은 “a.txt.tmp” 라는 이름이 됩니다. 모든 작업이 예상대로 진행된지 확인한 후 원본 파일을 삭제합니다. 항상 백업 옵션을 고려하시고 저의 경고를 유념하시기 바랍니다. 확장자가 고유한 한 백업된 원본 파일은 쉽게 삭제할 수 있습니다.

GNU 버전의 sed는 인수를 지정하지 않고 “-i” 옵션을 사용할 수 있습니다. 하지만 FreeBSD/Mac OS X 버전은 그렇지 않습니다. FreeBSD/Mac OS X 버전은 *반드시* 확장자를 지정해야 합니다. 백업 파일을 생성하지 않고 인플레이스 편집을 수행하려면 다음 명령을 사용합니다.

#+begin_src bash
sed -i ‘’  ‘s/^/\t/’  *.txt
#+end_src


*** The --follow-symlinks argument
인플레이스 편집은 유용합니다. 하지만 편집 중인 파일이 다른 파일을 가리키는 심볼릭 링크면 어떻게 될까요? “tmp” 디렉터리에 “b” 라는 이름의 파일이 있고 이 파일을 가리키는 심볼릭 링크도 있다고 가정합니다.

#+begin_example
$ ls -l b
lrwxrwxrwx 1 barnett adm 6 3월 16일 16:03 b.txt -> tmp/b.txt
#+end_example

위의 명령어를 실행해서 인플레이스 편집을 수행하면 현재 디렉터리에 “b.txt” 라는 새 파일이 생성되고 “tmp/b.txt” 는 변경되지 않은 상태로 남습니다. 이제 파일의 두 가지 버전이 존재하는데 하나는 변경된 버전(현재 디렉터리 내)이고 다른 하나는 변경되지 않은 버전(“tmp” 디렉터리 내)입니다.

또한 심볼릭 링크의 위치는 원본 파일의 수정된 버전으로 대체됩니다. 실제 파일을 편집하면서 심볼릭 링크를 그대로 유지하려면 “--follow-symlinks” 명령줄 옵션을 사용합니다:

#+begin_src bash
sed -i --follow-symlinks ‘s/^/\t/’ *.txt
#+end_src

이 명령은 심볼릭 링크의 원본 위치로 이동해서 “tmp” 디렉터리의 파일을 수정합니다. 확장자를 지정하면 실제 소스 파일과 동일한 디렉터리에 해당 확장자를 가진 원본 파일을 찾을 수 있습니다. --follow-symlinks 명령줄 옵션을 사용하지 않으면 “백업” 파일인 “b.tmp” 는 심볼릭 링크가 있던 디렉터리에 위치하며 여전히 심볼릭 링크로 남습니다. 단지 새로운 확장자를 부여하기 위해 이름만 변경한 것 뿐입니다.


*** The -b Binary argument
유닉스 및 리눅스 시스템은 줄바꿈 문자 “\n” 을 줄 끝으로 간주합니다. 반면, MS-DOS, Windows 및 Cygwin 시스템은 각 줄의 끝을 “\r\n” (캐리지 리턴 및 줄 바꿈)으로 처리합니다. 이런 운영 체제를 사용할 경우 “-b” 또는 “--binary” 명령줄 옵션으로 캐리지 리턴/줄바꿈 조합을 줄 끝으로 처리합니다. 그렇지 않은 경우 캐리지 리턴은 줄 끝 앞의 인쇄 불가능한 문자로 처리합니다. 제 생각에는 말입니다... (참고: 이 부분은 정확히 확인해야 합니다).


*** The -r Extended Regular Expression argument
~s/pattern/~ 같은 패턴을 언급할 때 이 패턴은 정규 표현식입니다. 정규 표현식은 두 가지 유형이 있는데 바로 원래의 “기본” (BRE)표현식과 “확장” (ERE)정규 표현식입니다. 두 유형의 차이점에 대한 자세한 내용은 제 [[https://www.grymoire.com/Unix/Regular.html][정규 표현식 튜토리얼]]과 [[https://www.grymoire.com/Unix/Regular.html#uh-12][확장 정규 표현식 관련 섹션]]을 참고합니다.

기본 정규 표현식과 확장 정규 표현식에서 특정 문자의 의미가 다르므로 sed가 확장 기능을 사용하려면 명령줄 인수를 지정합니다. 이런 확장 기능을 활성화하려면 한 줄에서 중복된 단어를 찾는 예제에서 언급한대로 “-r” 옵션을 사용합니다.

#+begin_src bash
sed -r -n ‘/\([a-z]+\) \1/p’
#+end_src

또는 긴 형식으로

#+begin_src bash
sed --regular-extended -quiet '/\([a-z]+\) \1/p'
#+end_src

앞서 언급했듯이 Mac OS X와 FreeBSD는 -r 대신 -E 옵션을 사용합니다.


*** The -u Unbuffered argument
일반적으로 유닉스 및 리눅스 시스템은 표준 출력을 처리할 때 지능적인 방식을 적용해서 처리합니다. 터미널로 결과를 전송할 경우 사용자가 결과가 나오자마자 곧바로 출력받기를 원한다고 가정합니다. 반면, 출력을 파일로 전송할 경우 좀 더 나은 성능을 원한다고 가정하므로 버퍼가 가득찰 때까지 출력을 버퍼링(/buffering/)한 다음 파일에 기록합니다.

자세히 설명하겠습니다. 이 예제는 매우 큰 파일이 있고 sed를 사용해서 특정 문자열을 검색한 뒤 발견되면 출력한다고 가정합니다.

#+begin_src bash
sed -n ‘/MATCH/p’ <file
#+end_src

이 경우 출력 대상은 터미널로 일치 항목이 발견되는 즉시 출력합니다. 하지만 출력을 다른 프로그램으로 파이프(/pipe/)로 전달하면 결과를 버퍼링합니다. 하지만 즉각적인 결과를 원할 때도 있습니다. 특히 대용량 파일을 다루거나 간헐적으로 데이터를 생성하는 파일을 다룰 때는 더욱 그렇습니다. 요약하면, 많은 양의 입력 데이터가 있고 sed로 이를 처리한 후 결과를 처리할 다른 프로그램으로 보내되 처리 결과를 지연하지 않고 발생 즉시 결과를 얻고자 할 경우입니다.

간단한 예를 들겠습니다. 다소 인위적이지만 작동 원리를 설명하는 데 도움됩니다. 1초에 한 번씩 1부터 60까지 숫자를 출력하는 /SlowText/ 프로그램입니다:

#+begin_src bash
#!/bin/sh
for i in $(seq 1 60)
do
  echo $i
  sleep 1
done
#+end_src

sed로 '1' 이란 문자가 포함된 줄을 검색하고 결과를 ~awk~ 로 보내 숫자의 제곱을 계산합니다. 다음은 다소 인위적으로 만들어진 스크립트입니다:

#+begin_src bash
SlowText | sed -n ‘/1/p’ | awk '{print $1*$1}'
#+end_src

이 코드는 작동하지만 sed가 결과를 버퍼링하므로 버퍼가 가득차거나 /SlowText/ 프로그램이 종료될 때까지 결과를 볼 수 없습니다. 이때 “-u” 옵션을 사용하면 이런 버퍼링을 제거하고 /SlowText/ 가 결과를 출력하는 즉시 확인할 수 있습니다. 이 옵션을 사용하면 제곱 값은 가능한 한 빨리 출력합니다:

#+begin_src bash
SlowText | sed -un ‘/1/p’ | awk ‘{print $1*$1}’
#+end_src

긴 형식은 “--unbuffered” 입니다.

Mac OS X와 FreeBSD는 “-l” 인수를 사용합니다.

GNU Sed 4.2.2 이상 버전은 파일에 쓰는 경우뿐만 아니라 읽는 경우도 버퍼링이 적용되지 않습니다.


*** The -z Null Data argument
일반적으로 sed는 줄 끝 문자(줄바꿈 또는 캐리지 리턴)까지 문자열을 읽고 한 줄로 처리합니다. (-b Binary 명령줄 인수를 참조합니다.) GNU 버전의 sed는 버전 4.2.2부터 “NULL” 문자를 사용하는 기능을 추가했습니다. 이 기능은 /NULL/ 을 레코드 구분자로 사용할 때 유용합니다. 일부 GNU 유틸리티는 “find . -print0” 이나 “grep -lZ” 같이 줄바꿈 문자 대신 /NULL/ 문자를 사용하는 출력을 생성합니다. 이 기능은 공백이나 이진 문자가 포함된 파일을 처리할 때 유용합니다.

예를 들어, “find” 로 파일을 검색하고 “-print0” 옵션으로 파일 이름 끝에 /NULL/ 을 출력할 경우 sed로 디렉터리 경로를 제거합니다.

#+begin_src bash
find . -type f -print0  | sed -z ‘s:^.*/::’ | xargs -0 echo
#+end_src

예제는 “xargs” 에서 ~echo~ 를 사용할 때 파일 이름의 공백을 그대로 유지할 수 없으므로 유용하지 않습니다. 하지만 sed의 “-z” 옵션을 사용하는 방법을 잘 보여줍니다.

GNU ~grep~ 도 파일에서 문자열을 검색할 때 파일 이름 끝에 줄바꿈 문자 대신 “NULL” 을 추가하는 -Z 옵션이 있습니다. 또한 -l 옵션을 사용하면 ~grep~ 은 해당 문자열이 포함된 파일 이름을 출력하면서 비표시 문자 및 바이너리 문자를 그대로 유지합니다:

#+begin_src bash
grep -lZ STRING */*/* | sed -z ‘s:^.*/::’ | xargs -0 echo
#+end_src

이 기능은 사용자가 직접 파일 이름을 생성할 경우 유용합니다.


** FreeBSD Extensions
애플은 Mac OS X 운영 체제에 GNU sed 대신 FreeBSD 버전의 sed를 사용합니다. 하지만 FreeBSD 버전은 몇 가지 추가 기능이 있습니다.

*** The -a or delayed open Argument
일반적으로 sed가 시작되면 “w” 명령어가 참조하는 모든 파일을 즉시 엽니다. FreeBSD 버전의 sed는 “w” 명령어가 실행될 때까지 이 작업을 지연시키는 옵션입니다.

*** The -I in-place argument
FreeBSD는 -i 옵션과 유사한 “-I” 옵션을 추가했습니다. “-i” 옵션은 각 파일을 별도의 sed 인스턴스로 취급합니다. “-I” 옵션을 사용하면 줄 시작 부분에서 줄 번호를 재설정하지 않으며 주소 범위가 한 파일에서 다음 파일로 이어집니다. 즉, ~/BEGIN/,/END/~ 범위를 사용하고 “-I” 옵션을 적용할 경우 첫 번째 파일에 “BEGIN” 이 있고 두 번째 파일에 “END” 가 있더라도 해당 범위로 실행되는 명령은 두 파일을 모두를 아우릅니다. 반면 “-i” 를 사용한 경우는 그렇지 않습니다.

또한 -i 옵션과 마찬가지로 백업 파일을 저장하는 확장자를 *반드시* 지정해야 합니다.

*** -E or Extended Regular Expressions
앞서 확장 정규 표현식을 언급했습니다. FreeBSD(및 Mac OS X)는 “-E” 옵션으로 이 기능을 활성화합니다. 하지만 FreeBSD는 이후 GNU sed의 호환성을 위해 -r 옵션을 추가했습니다.


** Using word boundaries
한때 누군가가 단어 경계를 다루는 sed 문제 해결에 도움을 요청한 적이 있습니다. 다음과 같은 입력 데이터를 가정합니다.

#+begin_example
/usr/bin /usr/local/bin /usr/local /usr/local/project/bin
#+end_example

여기서 ~/usr/local~ 만 삭제하고 나머지 3개 경로는 그대로 남긴다고 가정합니다. 다음과 같은 간단하지만 잘못된 명령어를 사용할 수 있습니다.

#+begin_src bash
sed ‘s@/usr/local@@’
#+end_src

이 명령어를 실행하면 다음과 같은 결과가 나옵니다.

#+begin_src bash
/usr/bin /bin /usr/local /usr/local/project/bin
#+end_src

즉, ~/usr/local/bin~ 을 ~/bin~ 으로 변경하고 프로그래머가 의도한 ~/usr/local~ 을 삭제하지 않습니다. 좀 더 나은 방법은 검색어 주위에 공백을 포함시키는 것입니다.

#+begin_src bash
sed ‘s@ /usr/local @ @’
#+end_src

하지만 ~/usr/local~ 문자열이 줄 맨 앞이나 맨 뒤에 있을 경우 이 방법은 작동하지 않습니다. 또한 ~/usr/local~ 이 해당 줄의 유일한 문자열인 경우도 작동하지 않습니다. 이런 예외적인 경우를 처리하려면 조건별로 구분해서 처리합니다:

#+begin_src bash
#!/bin/sh
sed '
s@ /usr/local @ @g
s@^/usr/local @@
s@ /usr/local$@@
s@^/usr/local$@@
'
#+end_src

검색할 문자열이 공백으로 둘러싸여 있다면 이 방법도 작동합니다. 하지만 문자열이 공백 이외의 다른 문자로 둘러싸여 있다면 어떻게 될까요?

‘단어의 끝' 을 정의하는 문자 클래스를 만듭니다. 예를 들어, 문자열이 영숫자와 슬래시로 구성된다면 문자 클래스는 ’[a-zA-Z0-9/]‘ 또는 좀 더 유연한 ’[[:alnum:]/]' 로 정의합니다. 캐럿(^)으로 이 문자를 *제외한* 모든 문자로 문자 집합을 정의합니다. 즉, ‘[^[:alnum:]/]' 패턴입니다.

앞서 언급한 공백과 다른 문자 집합을 사용할 경우 해당 문자들이 무엇인지를 기억하고 삭제하지 않도록 주의해야 합니다. 따라서 공백을 ’[^[:alnum:]/]' 로 대체하고 명령어를 다음과 같이 변경합니다.

#+begin_src bash
#!/bin/sh
sed '
s@\([^[:alnum:]/]\)/usr/local\([^[:alnum:]/]\)@\1\2@g
s@^/usr/local\([^[:alnum:]/]\)@\1@
s@\([^[:alnum:]/]\)/usr/local$@\1@
s@^/usr/local$@@
'
#+end_src

첫 번째 버전은 ‘ /usr/local ' 을 단일 공백으로 대체합니다. 이 방법을 사용하면 ’:/usr/local:‘ 은 ’::' 으로 대체됩니다. 이는 중복된 구분자를 삭제하지 않기 때문입니다. 필요한 경우 이 부분을 반드시 수정해야 합니다.

이 방법은 항상 작동하지만 우아하지 않고 오류가 발생하기 쉽습니다. 다른 방법도 있지만 이식성이 떨어집니다. Solaris의 sed는 ‘\<’ 와 ‘\>’ 특수 문자로 단어 경계를 처리하는 앵커로 사용합니다. 따라서 다음과 같이 사용할 수 있습니다.

#+begin_src bash
s@\</usr/local\>@@
#+end_src

그러나 GNU 버전의 sed는 이런 특수 문자의 사용이 정의되지 않았다고 명시합니다. 매뉴얼 페이지에 따르면:

#+begin_example
정규 표현식 구문 충돌 (백슬래시 관련 문제)
     sed는 POSIX 기본 정규 표현식 구문을 사용합니다.  표준에 따르면
     구문에서 일부 이스케이프 시퀀스 의미를 정의하지 않았습니다.

     sed의 경우 특히 `\|‘, `\+’, `\?',
     `\`‘, `\’', `\<‘, `\>’, `\b', `\B', `\w', `\W' 가 이에 해당합니다.

     POSIX 기본 정규 표현식을 사용하는 모든 GNU 프로그램과 마찬가지로
     sed는 이런 이스케이프 시퀀스를 특수 문자로 해석합니다.

     따라서, `x\+' 는 `x' 가 최소 한 번 이상 나타날 경우 일치합니다.
     `abc\|def' 는 `abc' 또는 `def' 둘 중 하나와 일치합니다.
#+end_example

확실치 않으면 항상 실험해 보시기 바랍니다.


** Command Summary
약속대로 다양한 명령어를 요약한 표를 소개합니다. 두 번째 열은 명령어가 주소나 주소 쌍, 단일 패턴 또는 범위 패턴을 지정할 수 있는지를 의미합니다. 다음 네 개 열은 명령어가 네 가지 버퍼 또는 스트림 중 어느 것에 영향을 미치는지 의미합니다. 일부 명령어는 출력 스트림만 영향을 미치고 다른 명령어는 홀드 버퍼만 영향을 미칩니다. 패턴 공간은 출력된다는 점(sed에 “-n” 옵션이 지정되지 않은 경우)을 기억하시면 이 표로 다양한 명령어를 파악할 때 도움됩니다.

#+caption: Command Summary
| 명령 | 주소 또는 범위 | 입력 스트림에 대한 변경 | 출력 스트림에 대한 변경 | 패턴 공간에 대한 변경 | 홀드 버퍼에 대한 변경 |
|------+----------------+-------------------------+-------------------------+-----------------------+-----------------------|
|  =   |       -        |            -            |            Y            |           -           |           -           |
|  a   |      주소      |            -            |            Y            |           -           |           -           |
|  b   |      범위      |            -            |            -            |           -           |           -           |
|  c   |      범위      |            -            |            Y            |           -           |           -           |
|  d   |      범위      |            Y            |            -            |           Y           |           -           |
|  D   |      범위      |            Y            |            -            |           Y           |           -           |
|  g   |      범위      |            -            |            -            |           Y           |           -           |
|  G   |      범위      |            -            |            -            |           Y           |           -           |
|  h   |      범위      |            -            |            -            |           -           |           Y           |
|  H   |      범위      |            -            |            -            |           -           |           Y           |
|  i   |      주소      |            -            |            Y            |           -           |           -           |
|  l   |      주소      |            -            |            Y            |           -           |           -           |
|  n   |      범위      |            Y            |            *            |           -           |           -           |
|  N   |      범위      |            Y            |            -            |           Y           |           -           |
|  p   |      범위      |            -            |            Y            |           -           |           -           |
|  P   |      범위      |            -            |            Y            |           -           |           -           |
|  q   |      주소      |            -            |            -            |           -           |           -           |
|  r   |      주소      |            -            |            Y            |           -           |           -           |
|  s   |      범위      |            -            |            -            |           Y           |           -           |
|  t   |      범위      |            -            |            -            |           -           |           -           |
|  w   |      범위      |            -            |            Y            |           -           |           -           |
|  x   |      범위      |            -            |            -            |           Y           |           Y           |
|  y   |      범위      |            -            |            -            |           Y           |           -           |


** In Conclusion
이것으로 ~sed~ 튜토리얼을 모두 마치겠습니다. 제가 소개한 스크립트 중 일부는 좀 더 간결한 형태로 작성할 수 있습니다. 하지만 저는 몇 가지 기본 구문을 명확히 설명하기 위해 예제를 사용했습니다. 난해함보단 명확함을 추구했습니다. 재미있게 보셨길 바랍니다.


감사합니다!!

