* Sed Syntax and Basic

** Commands
이 문서의 sed 예제는 다음과 같은 /employee.txt/ 파일을 사용한다. 따라서, 이 문서에서 제공하는 명령을 실행하려면 이 파일부터 생성한다.  

#+begin_src
$ sed -n 'w employee.txt'
101,John Doe,CEO
102,Jason Smith,IT Manager
103,Raj Reddy,Sysadmin
104,Anand Ram,Developer
105,Jane Miller,Sales Manager
^d
#+end_src

#+begin_quote
[!IMPORTANT]
마지막 줄의 ~^d~ 는 ~Control~ 키와 ~d~ 키를 눌러 입력을 종료한다!!
#+end_quote

위의 직원 데이터베이스 파일의 레코드는 다음과 같은 필드를 포함한다:  

- 직원 ID  
- 직원 이름  
- 직책  

~sed~ 는 스트림 편집기(/stream editor/)를 의미한다. 텍스트를 조작하고, 필터링하며, 변환할 수 있는 강력한 도구이다. 

sed는 파일이나 파이프에서 입력받을 수 있다. 아마 시스템 시작 파일에 sed 한 줄 명령을 넣어두고 다양한 상황에 사용했는지도 모른다. 혹은 sed 스크립트를 이해하지 못한 채 사용했을 수도 있다. 초보자에게 sed 스크립트는 난해하게 보일 수 있다. 하지만, sed 명령을 이해하면 간단한 sed 스크립트를 작성해서 복잡한 텍스트 문제를 해결할 수 있다.  

이 문서는 모든 sed 명령을 설명하고 이해하기 쉬운 예제를 제공한다.


** Sed Command Syntax
이번 섹션의 목적은 sed 문법과 명령 구조에 익숙해지는 것이다. 따라서, sed 명령을 설명하기 위한 것이 아니며 명령은 이후에 자세히 다룬다.

#+begin_quote
[!TIP]
원문에선 명령(/command/) 대신 함수(/function/)라는 표현을 사용한다.
#+end_quote

*기본 sed 문법:* 

#+begin_src
sed [옵션] {sed-명령} {입력파일}  
#+end_src

sed는 ~{입력파일}~ 에서 한 줄 읽고 해당 줄에 ~{sed-명령}~ 을 실행한다. 즉, ~{입력파일}~ 첫 번째 줄을 읽고 첫 번째 줄에 ~{sed-명령}~ 을 실행한다. 그 다음 두 번째 줄을 읽고 두 번째 줄에 ~{sed-명령}~ 을 실행한다. sed는 ~{입력파일}~ 끝에 도달할 때까지 이 과정을 계속 반복한다.  

~[옵션]~ 으로 출력 결과에 선택적인 명령줄 옵션을 sed에 전달할 수 있다. 다음 예제는 기본적인 sed 문법을 보여준다. ~/etc/passwd~ 파일의 모든 줄을 출력한다.

#+begin_src 
sed -n 'p' /etc/passwd  
#+end_src

여기서 핵심은 ~{sed-명령}~ (='p'=) 은 단일 명령일 수도 있고 여러 개일 수도 있다. 여러 개의 sed 명령을 (명령) 파일에 저장하고 ~-f~ 옵션으로 sed 스크립트를 호출할 수 있다.

*sed 스크립트 파일 문법:*

#+begin_src
sed [옵션] -f {sed-명령 파일} {입력파일}  
#+end_src

다음 예제는 기본 문법을 보여준다. ~/etc/passwd~ 파일에서 root 와 nobody 로 시작하는 줄을 출력한다.  

#+begin_src
$ sed -n 'w test-script.sed'  
/^root/ p  
/^nobody/ p
^d
$ sed -n -f test-script.sed /etc/passwd
#+end_src

명령줄(/command line/)에서 여러 sed 명령을 실행할 때는 다음과 같이 ~-e~ 옵션을 사용할 수 있다.  

*-e 옵션 문법:*

#+begin_src
sed [옵션] -e {sed-명령-1} -e {sed-명령-2} {입력파일}~  
#+end_src

다음 예제는 기본 문법을 보여준다. ~/etc/passwd~ 파일에서 root 와 nobody 로 시작하는 줄을 출력한다.  

#+begin_src
sed -n -e '/^root/ p' -e '/^nobody/ p' /etc/passwd~  
#+end_src

명령줄에서 여러 개의 ~-e~ 옵션을 사용할 때, 한 줄에 많은 명령을 입력할 경우 다음과 같이 백슬래시 문자로 여러 줄로 나눌 수 있다.  

#+begin_src
sed -n \  
-e '/^root/ p' \  
-e '/^nobody/ p' \  
/etc/passwd
#+end_src

명령줄에서 여러 개의 sed 명령을 ~{...}~ 로 묶어 그룹 명령을 실행할 수 있다. 

*{...} 명령 그룹 문법:*  

#+begin_src
sed [옵션] '{  
sed-명령-1  
sed-명령-2  
}' 입력파일
#+end_src

다음 예제는 기본 문법을 보여준다. 이 예제 역시 ~/etc/passwd~ 파일에서 root 와 nobody 로 시작하는 줄을 출력한다.  

#+begin_src
sed -n '{  
/^root/ p  
/^nobody/ p  
}' /etc/passwd
#+end_src

#+begin_quote
[!NOTE]
Sed는 원본 파일을 절대 수정하지 않는다!! 항상 출력 결과를 표준 출력(/stdout/)으로 출력한다. 따라서, 변경 사항을 파일로 저장하려면 ~> filename.txt~ 같이 명시적으로 출력을 파일로 리디렉션한다.
#+end_quote



** Sed Scripting Flow
Sed 스크립트의 실행 흐름은 기억하기 쉬운 "읽기(/Read/), 실행(/Execute/), 출력(/Print/), 반복(/Repeat/)" 을 따른다. sed의 실행 흐름을 기억하려면 약어인 "~REPR~" 을 사용한다. 

실행 순서(흐름)는 다음과 같다. 즉, Sed는 다음과 과정으로 수행한다:

+ 입력(파일이나 파이프)에서 한 줄을 읽어 패턴 공간(sed 내부의 임시 버퍼)에 저장한다. 

+ 패턴 공간에 읽은 줄에 sed 명령을 실행한다. sed 명령이 여러 개일 경우 sed 스크립트 파일이나 ~-e~ 옵션 또는 ~{...}~ 로 명령을 패턴 공간에 순차적으로 실행한다.  

+ 패턴 공간의 줄을 출력한다. 출력한 이후 패턴 공간은 비워진다.  

+ 입력 파일 끝에 도달할 때까지 이 과정을 계속 반복한다.  


** Print Pattern Space (p command)
sed의 ~p~ (/print/)명령을 사용하면 패턴 공간의 내용을 출력할 수 있다. sed는 기본적으로 명령을 실행한 후 패턴 버퍼를 출력하는데 왜 ~p~ 명령이 필요한지 궁금할 수 있다. ~p~ 명령으로 출력 내용을 명확히 제어할 수 있다. 

일반적으로 ~p~ 명령을 사용할 때는 ~-n~ 옵션을 함께 사용해서 sed의 기본 출력 동작을 억제한다. 그렇지 않고 ~p~ 명령만 실행하면 줄을 두 번 중복 출력한다.  

다음 예제는 ~employee.txt~ 파일의 줄을 두 번씩 중복 출력한다: (기본 출력 + ~p~ 출력 명령)

#+begin_src
$ sed 'p' employee.txt  
101,John Doe,CEO  
101,John Doe,CEO  
102,Jason Smith,IT Manager  
102,Jason Smith,IT Manager  
103,Raj Reddy,Sysadmin  
103,Raj Reddy,Sysadmin  
104,Anand Ram,Developer  
104,Anand Ram,Developer  
105,Jane Miller,Sales Manager  
105,Jane Miller,Sales Manager
#+end_src

다음은 각 줄을 한 번만 출력한다. (기능적으론 ~cat employee.txt~ 과 동일):  

#+begin_src
$ sed -n 'p' employee.txt  
101,John Doe,CEO  
102,Jason Smith,IT Manager  
103,Raj Reddy,Sysadmin  
104,Anand Ram,Developer  
105,Jane Miller,Sales Manager
#+end_src

*** 주소 지정  
sed 명령 앞에 주소나 주소 범위를 지정하지 않으면 기본적으로 모든 줄에 명령을 적용한다!!  

다음은 주소를 지정한 몇 가지 예제이다.  

*2번 줄만 출력:*  

#+begin_src
$ sed -n '2 p' employee.txt  
102,Jason Smith,IT Manager
#+end_src

*1번 줄부터 4번 줄까지 출력:*  

#+begin_src
$ sed -n '1,4 p' employee.txt  
101,John Doe,CEO  
102,Jason Smith,IT Manager  
103,Raj Reddy,Sysadmin  
104,Anand Ram,Developer
#+end_src

*2번 줄부터 마지막 줄까지 출력($ 는 마지막 줄을 의미):*  

#+begin_src
$ sed -n '2,$ p' employee.txt  
102,Jason Smith,IT Manager  
103,Raj Reddy,Sysadmin  
104,Anand Ram,Developer  
105,Jane Miller,Sales Manager
#+end_src

*** 주소 수정자  
주소는 쉼표(~,~), 플러스(~+~), 틸드(=~=) 문자로 수정할 수 있다.

위에서 쉼표(~,~)를 사용한 주소 지정은 이미 사용했다. 따라서,
- ~n,m~ 은 ~n~ 부터 ~m~ 까지를 의미한다.
- 플러스(~+~)는 쉼표와 함께 사용하며 줄 번호 대신 줄 수를 지정한다. ~n,+m~ 은 ~n~ 부터 시작해서 ~m~ 개 줄을 의미한다.
- 틸드(=~=)는 줄을 건너뛸 때 사용한다. ~n~m~ 은 ~n~ 번 줄부터 시작해서 ~m~ 번마다 줄을 선택한다.  

예를 들면 다음과 같다.

- ~1~2~ :: 1,3,5,7,... 과 일치  
- ~2~2~ :: 2,4,6,8,... 과 일치  
- ~1~3~ :: 1,4,7,10,... 과 일치  
- ~2~3~ :: 2,5,8,11,... 과 일치  

*홀수 줄만 출력:*  

#+begin_src
$ sed -n '1~2 p' employee.txt  
101,John Doe,CEO  
103,Raj Reddy,Sysadmin  
105,Jane Miller,Sales Manager
#+end_src

*** 패턴 매칭  
줄 번호로 구성된 주소(또는 주소 범위)를 지정할 수 있는 것처럼 패턴(또는 패턴 범위) 주소를 지정해서 매칭할 수 있다. (이를 ~필터링~ 이라 함)  

*"Jane" 패턴과 일치한 줄 출력:*  

#+begin_src
$ sed -n '/Jane/ p' employee.txt  
105,Jane Miller,Sales Manager
#+end_src

*"Jason" 패턴과 처음 일치한 줄부터 4번 줄까지 출력:*  

#+begin_src
$ sed -n '/Jason/,4 p' employee.txt  
102,Jason Smith,IT Manager  
103,Raj Reddy,Sysadmin  
104,Anand Ram,Developer
#+end_src

#+begin_quote
[!NOTE]
만약 처음 4줄에 "Jason" 이 없으면 4번 줄 이후 "Jason" 과 일치한 줄을 출력한다.
#+end_quote

*"Raj" 패턴과 처음 일치한 줄부터 마지막 줄까지 출력:*  

#+begin_src
$ sed -n '/Raj/,$ p' employee.txt  
103,Raj Reddy,Sysadmin  
104,Anand Ram,Developer  
105,Jane Miller,Sales Manager
#+end_src

*"Raj" 패턴과 일치한 줄부터 "Jane" 패턴과 일치한 줄까지 출력:*  

#+begin_src
$ sed -n '/Raj/,/Jane/ p' employee.txt  
103,Raj Reddy,Sysadmin  
104,Anand Ram,Developer  
105,Jane Miller,Sales Manager
#+end_src

*"Jason" 패턴과 일치한 줄부터 그 다음 두 줄 출력:*  

#+begin_src
$ sed -n '/Jason/,+2 p' employee.txt  
102,Jason Smith,IT Manager  
103,Raj Reddy,Sysadmin  
104,Anand Ram,Developer
#+end_src

** Delete Lines (d command)
sed의 ~d~ (/delete/)명령을 사용하면 줄을 삭제할 수 있다. 하지만, 삭제 명령은 출력 스트림에만 적용되며 다른 sed 명령과 마찬가지로 원본 파일의 내용을 수정하지 않는다!!  

기본적으로 sed 명령 앞에 주소를 지정하지 않으면 모든 줄에 적용한다. 따라서, 다음 예제는 ~employee.txt~ 파일의 모든 줄을 삭제하므로 아무것도 출력하지 않는다:  

#+begin_src
sed 'd' employee.txt
#+end_src

삭제 명령은 주소를 지정해야만 유용하게 사용할 수 있다. 다음은 몇 가지 예제이다:  

*2번 줄만 삭제:*  

#+begin_src
$ sed '2 d' employee.txt  
101,John Doe,CEO  
103,Raj Reddy,Sysadmin  
104,Anand Ram,Developer  
105,Jane Miller,Sales Manager
#+end_src

*1번 줄부터 4번 줄까지 삭제:*  

#+begin_src
$ sed '1,4 d' employee.txt  
105,Jane Miller,Sales Manager
#+end_src

*2번 줄부터 마지막 줄까지 삭제:*  

#+begin_src
$ sed '2,$ d' employee.txt  
101,John Doe,CEO
#+end_src

*홀수 줄만 삭제:*  

#+begin_src
$ sed '1~2 d' employee.txt  
102,Jason Smith,IT Manager  
104,Anand Ram,Developer
#+end_src

*"Manager" 패턴과 일치한 줄 삭제:*  

#+begin_src
$ sed '/Manager/ d' employee.txt  
101,John Doe,CEO  
103,Raj Reddy,Sysadmin  
104,Anand Ram,Developer
#+end_src

*"Jason" 패턴과 처음 일치한 줄부터 4번 줄까지 삭제:*  

#+begin_src
$ sed '/Jason/,4 d' employee.txt  
101,John Doe,CEO  
105,Jane Miller,Sales Manager
#+end_src

#+begin_quote
[!NOTE]
만약, 처음 4줄에 "Jason" 이 없으면 4번 줄 이후에 "Jason" 과 일치한 줄만 삭제한다.
#+end_quote

*"Raj" 패턴과 처음 일치한 줄부터 마지막 줄까지 삭제:*  

#+begin_src
$ sed '/Raj/,$ d' employee.txt  
101,John Doe,CEO  
102,Jason Smith,IT Manager
#+end_src

*"Raj" 패턴과 일치한 줄부터 "Jane" 패턴과 일치한 줄까지 삭제:*  

#+begin_src
$ sed '/Raj/,/Jane/ d' employee.txt  
101,John Doe,CEO  
102,Jason Smith,IT Manager
#+end_src

*"Jason" 패턴과 일치한 줄과 그 다음 두 줄 삭제:*  

#+begin_src
$ sed '/Jason/,+2 d' employee.txt  
101,John Doe,CEO  
105,Jane Miller,Sales Manager
#+end_src

*** 유용한 삭제 명령 예제  
다음은 실제 작업을 처리할 때 유용하다:  

*파일 내의 모든 빈 줄 삭제:*  

#+begin_src
sed '/^$/ d' employee.txt
#+end_src

*주석 삭제 (주석은 # 문자로 시작한다고 가정):*  

#+begin_src
sed '/^#/ d' employee.txt
#+end_src

#+begin_quote
[!NOTE]
여러 개의 sed 명령일 경우, ~d~ 명령을 만나면 해당 줄을 삭제하며 이미 삭제한 줄에 명령을 적용하지 않는다.
#+end_quote


** Write Pattern Space to File (w command)
sed의 ~w~ (/write/)명령을 사용하면 패턴 공간의 내용을 파일에 쓸(저장) 수 있다. 기본적으로 sed의 표준 실행 흐름에 따라 패턴 공간은 표준 출력(/stdout/)으로 출력하므로 화면에 출력하지 않고 파일로 저장하려면 ~-n~ 옵션을 함께 사용한다.  

다음은 몇 가지 사용 예제이다:  

*employee.txt 파일의 내용을 output.txt 파일에 쓰고 화면에 출력:*  

#+begin_src
$ sed 'w output.txt' employee.txt  
101,John Doe,CEO  
102,Jason Smith,IT Manager  
103,Raj Reddy,Sysadmin  
104,Anand Ram,Developer  
105,Jane Miller,Sales Manager  

$ cat output.txt  
101,John Doe,CEO  
102,Jason Smith,IT Manager  
103,Raj Reddy,Sysadmin  
104,Anand Ram,Developer  
105,Jane Miller,Sales Manager
#+end_src

*employee.txt 파일의 내용을 output.txt 파일에 쓰고 화면에 출력하지 않음:*  

#+begin_src
$ sed -n 'w output.txt' employee.txt  

$ cat output.txt  
101,John Doe,CEO  
102,Jason Smith,IT Manager  
103,Raj Reddy,Sysadmin  
104,Anand Ram,Developer  
105,Jane Miller,Sales Manager
#+end_src

*2번 줄만 파일에 쓰기:*  

#+begin_src
$ sed -n '2 w output.txt' employee.txt  

$ cat output.txt  
102,Jason Smith,IT Manager
#+end_src

*1번 줄부터 4번 줄까지 쓰기:*  

#+begin_src
$ sed -n '1,4 w output.txt' employee.txt  

$ cat output.txt  
101,John Doe,CEO  
102,Jason Smith,IT Manager  
103,Raj Reddy,Sysadmin  
104,Anand Ram,Developer
#+end_src

*2번 줄부터 마지막 줄까지 쓰기:*  

#+begin_src
$ sed -n '2,$ w output.txt' employee.txt  

$ cat output.txt  
102,Jason Smith,IT Manager  
103,Raj Reddy,Sysadmin  
104,Anand Ram,Developer  
105,Jane Miller,Sales Manager
#+end_src

*홀수 줄만 쓰기:*  

#+begin_src
$ sed -n '1~2 w output.txt' employee.txt  

$ cat output.txt  
101,John Doe,CEO  
103,Raj Reddy,Sysadmin  
105,Jane Miller,Sales Manager
#+end_src

*"Jane" 패턴과 일치한 줄 쓰기:*  

#+begin_src
$ sed -n '/Jane/ w output.txt' employee.txt  

$ cat output.txt  
105,Jane Miller,Sales Manager
#+end_src

*"Jason" 패턴과 처음 일치한 줄부터 4번 줄까지 쓰기:*  

#+begin_src
$ sed -n '/Jason/,4 w output.txt' employee.txt  

$ cat output.txt  
102,Jason Smith,IT Manager  
103,Raj Reddy,Sysadmin  
104,Anand Ram,Developer
#+end_src

#+begin_quote
[!NOTE]
만약, 처음 4줄에 "Jason" 이 없으면 4번 줄 이후에 "Jason" 과 일치한 줄만 쓴다.
#+end_quote

*"Raj" 패턴과 처음 일치한 줄부터 마지막 줄까지 쓰기:*  

#+begin_src
$ sed -n '/Raj/,$ w output.txt' employee.txt  

$ cat output.txt  
103,Raj Reddy,Sysadmin  
104,Anand Ram,Developer  
105,Jane Miller,Sales Manager
#+end_src

*"Raj" 패턴과 일치한 줄부터 "Jane" 패턴과 일치한 줄까지 쓰기:*  

#+begin_src
$ sed -n '/Raj/,/Jane/ w output.txt' employee.txt  

$ cat output.txt  
103,Raj Reddy,Sysadmin  
104,Anand Ram,Developer  
105,Jane Miller,Sales Manager
#+end_src

*"Jason" 패턴과 일치한 줄과 그 다음 두 줄 쓰기:*  

#+begin_src
$ sed -n '/Jason/,+2 w output.txt' employee.txt  

$ cat output.txt  
102,Jason Smith,IT Manager  
103,Raj Reddy,Sysadmin  
104,Anand Ram,Developer
#+end_src

#+begin_quote
[!NOTE]
~w~ 명령은 자주 사용하지 않을 수 있다. 사용자 대부분은 sed의 출력을 파일로 저장할 때 UNIX 출력 리디렉션 기능을 사용한다. 예, ~sed 'p' employee.txt >output.txt~
#+end_quote



* Sed Substitute

** command
스트림 편집기에서 가장 강력한 명령은 /substitute/ (치환 또는 대체) 명령이다. 이 명령은 강력하고 다양한 옵션을 제공하므로 별도의 장으로 자세히 다룬다.


*대체 명령 기본 문법*:

#+begin_src
sed '[주소-범위|패턴-범위] s/검색-문자열/대체-문자열/[대체-플래그]' 입력파일  
#+end_src

위의 sed 대체 명령에서:

- 주소-범위 또는 패턴-범위 :: "선택 사항" 으로 지정하지 않으면 모든 줄에 대체 명령을 실행한다.  
- ~s~ :: 대체 명령을 실행하라고 지시한다.  
- 검색-문자열 :: 입력 파일에서 검색할 문자열이다. 정규 표현식도 사용할 수 있다.  
- 대체-문자열 :: 검색 문자열을 이 문자열로 바꾼다.  
- 대체-플래그 :: "선택 사항" 으로 다음 섹션에 자세히 설명한다.  

sed는 원본 파일을 *절대* 변경하지 않으며 대체 작업는 패턴 공간 버퍼에서 이루어지고 처리 결과는 /stdout/ 으로 출력한다.  

다음은 간단한 대체 예제이다.  

*모든 줄의 "Manager" 를 "Director" 로 대체:*  

#+begin_src
$ sed 's/Manager/Director/' employee.txt  
101,John Doe,CEO  
102,Jason Smith,IT Director  
103,Raj Reddy,Sysadmin  
104,Anand Ram,Developer  
105,Jane Miller,Sales Director
#+end_src

*"Sales" 를 포함한 줄만 "Manager" 를 "Director" 로 대체:*  

#+begin_src
$ sed '/Sales/ s/Manager/Director/' employee.txt  
101,John Doe,CEO  
102,Jason Smith,IT Manager  
103,Raj Reddy,Sysadmin  
104,Anand Ram,Developer  
105,Jane Miller,Sales Director
#+end_src

이전 예제에서 두 줄을 변경한 것과 달리 한 줄만 변경한 것을 알 수 있다.


** Global Flag (g flag)
대체 플래그 중 ~g~ 는 /global/ (전체)을 의미한다. 기본적으로 대체 명령은 각 줄에서 ~{검색-문자열}~ 의 *첫 번째 항목* 만 ~{대체-문자열}~ 로 바꾼다. 줄 내의 모든 ~{검색-문자열}~ 을 ~{대체-문자열}~ 로 바꾸려면 ~g~ 플래그를 사용한다.  

*소문자 "a" 를 대문자 "A" 로 첫 번째 항목만 대체:*  

#+begin_src
$ sed 's/a/A/' employee.txt  
101,John Doe,CEO  
102,JAson Smith,IT Manager  
103,RAj Reddy,Sysadmin  
104,AnAnd Ram,Developer  
105,JAne Miller,Sales Manager
#+end_src

*소문자 "a" 를 대문자 "A" 로 모든 항목 대체:*  

#+begin_src
$ sed 's/a/A/g' employee.txt  
101,John Doe,CEO  
102,JAson Smith,IT MAnAger  
103,RAj Reddy,SysAdmin  
104,AnAnd RAm,Developer  
105,JAne Miller,SAles MAnAger
#+end_src

#+begin_quote
[!NOTE]
위의 예제는 주소 범위를 지정하지 않았으므로 파일 전체에 적용된다.
#+end_quote


** Number Flag (1,2,3.. flag)
숫자 플래그를 사용하면 검색 문자열의 특정 항목을 대체할 수 있다. 각 줄의 n번째 항목을 대체하고 줄마다 카운트는 새로 시작된다. 숫자 플래그 n 은 1 부터 512 까지 지정할 수 있다. 예를 들어, ~/11~ 은 한 줄 내에서 11번째로 일치한 검색 문자열을 대체한다.  

다음은 몇 가지 예제이다.  

*소문자 "a" 의 두 번째 항목만 대문자 "A" 로 대체:*  

#+begin_src
$ sed 's/a/A/2' employee.txt  
101,John Doe,CEO  
102,Jason Smith,IT MAnager  
103,Raj Reddy,SysAdmin  
104,Anand RAm,Developer  
105,Jane Miller,SAles Manager
#+end_src

다음과 같은 파일을 생성한 후:  

#+begin_src
$ sed -n 'w substitute-locate.txt'  
locate command is used to locate files  
locate command uses database to locate files  
locate command can also use regex for searching
^d
#+end_src

*각 줄의 "locate" 두 번째 항목만 "find" 로 대체:*  

#+begin_src
$ sed 's/locate/find/2' substitute-locate.txt  
locate command is used to find files  
locate command uses database to find files  
locate command can also use regex for searching
#+end_src

#+begin_quote
[!NOTE]
위의 예제에서 3번 줄은 "locate" 가 한 번만 등장하므로 변경하지 않는다.
#+end_quote


** Print Flag (p flag)
대체 플래그 ~p~ 는 /print/ (출력)를 의미한다. 성공적으로 대체한 경우만 출력한다. 다른 명령과 마찬가지로 기본 출력 동작을 억제하기 위해 ~-n~ 옵션과 함께 사용하는 것이 효과적이다.  

*대체한 줄만 출력:*  

#+begin_src
$ sed -n 's/John/Johnny/p' employee.txt  
101,Johnny Doe,CEO
#+end_src

이전 숫자 플래그 예제는 ~/2~ 로 "locate" 의 두 번째 항목을 "find" 로 변경했다. /locate.txt/ 파일 3번째 줄은 "locate" 가 한 번 등장하므로 대체는 발생하지 않는다. ~p~ 플래그를 사용하면 변경한 두 줄만 출력한다.  

*"locate" 의 두 번째 항목을 "find" 로 변경하고 변경된 줄만 출력:*  

#+begin_src
$ sed -n 's/locate/find/2p' substitute-locate.txt  
locate command is used to find files  
locate command uses database to find files
#+end_src

** Write Flag (w flag)
대체 플래그 ~w~ 는 /write/ (쓰기)를 의미한다. 대체 작업이 성공한 경우 변경된 줄을 지정한 파일에 기록한다. 

사용자 대부분은 ~p~ 플래그로 출력을 파일로 리디렉션하는 방식을 선호하지만 ~w~ 플래그도 완전한 설명을 위해 포함한다.  

*대체한 줄만 output.txt 파일에 기록:*  

#+begin_src
$ sed -n 's/John/Johnny/w output.txt' employee.txt  

$ cat output.txt  
101,Johnny Doe,CEO
#+end_src

~p~ 플래그처럼 ~w~ 플래그를 /substitute-locate.txt/ 예제에 적용하면 변경된 두 줄만 /output.txt/ 파일에 기록한다.  

*"locate" 의 두 번째 항목을 "find" 로 변경하고 결과를 파일에 기록하며 모든 줄 출력:*  

#+begin_src
$ sed 's/locate/find/2w output.txt' substitute-locate.txt  
locate command is used to find files  
locate command uses database to find files  
locate command can also use regex for searching  

$ cat output.txt  
locate command is used to find files  
locate command uses database to find files
#+end_src

** Ignore Case Flag (i flag)
치환 플래그 ~i~ 는 /ignore case/ (대소문자 무시)를 의미한다. 이 플래그를 사용하면 검색 문자열을 대소문자 구분없이 매칭할 수 있다. 단, 이 기능은 *GNU Sed만 지원* 된다.  

다음 예제는 검색 문자열을 소문자 "john" 으로 지정했으므로 "John" 은 대체하지 않는다:  

#+begin_src
$ sed 's/john/Johnny/' employee.txt  
101,John Doe,CEO  
102,Jason Smith,IT Manager  
103,Raj Reddy,Sysadmin  
104,Anand Ram,Developer  
105,Jane Miller,Sales Manager
#+end_src

*"john" 또는 "John" 모두 "Johnny" 로 대체:*  

#+begin_src
$ sed 's/john/Johnny/i' employee.txt  
101,Johnny Doe,CEO  
102,Jason Smith,IT Manager  
103,Raj Reddy,Sysadmin  
104,Anand Ram,Developer  
105,Jane Miller,Sales Manager
#+end_src

** Execute Flag (e flag)
치환 플래그 또는 명령  ~e~ 는 /execute/ (실행)를 의미한다. 패턴 공간의 내용을 시스템 쉘 명령으로 실행하며 결과를 패턴 공간으로 반환한다. 이 기능은 *GNU Sed만 지원* 된다.  

다음은 몇 가지 예제이다.  

다음과 같은 파일을 새로 생성한다:  

#+begin_src
$ cat files.txt  
/etc/passwd  
/etc/group
#+end_src

*각 줄 앞에 ls -l 을 추가한 후 출력:*  

#+begin_src
$ sed 's/^/ls -l /' files.txt  
ls -l /etc/passwd  
ls -l /etc/group
#+end_src

*각 줄 앞에 ls -l 을 추가한 후 쉘 명령으로 실행:*  

#+begin_src
$ sed 's/^/ls -l /e' files.txt  
-rw-r--r-- 1 root root 1547 Oct 27 08:11 /etc/passwd  
-rw-r--r-- 1 root root 651 Oct 27 08:11 /etc/group
#+end_src


** Combine Sed Substitution Flags
필요에 따라 하나 이상의 대체 플래그를 조합할 수 있다. 다음 예제는 "Manager" 또는 "manager" 의 모든 항목을 "Director" 로 대체한다. 또한, 대체한 줄만 화면에 출력하며 동일한 내용으로 /output.txt/ 파일에 기록한다.  

*g, i, p, w 플래그 조합 예제:*  

#+begin_src
$ sed -n 's/Manager/Director/gipw output.txt' employee.txt  
102,Jason Smith,IT Director  
105,Jane Miller,Sales Director  

$ cat output.txt  
102,Jason Smith,IT Director  
105,Jane Miller,Sales Director
#+end_src


** Sed Substitution Delimiter
지금까지 대체 예제는 기본 구분자인 슬래시 ~/~ 문자를 사용했다. 즉, ~s/검색-문자열/대체-문자열/~ 형식이다. 하지만, 검색 문자열에 슬래시 ~/~ 문자가 포함될 경우, 백슬래시 ~\~ 문자로 슬래시 문자를 모두 이스케이프 처리해야 한다.  

예를 들어, 다음과 같은 /path.txt/ 파일을 새로 생성한다:  

#+begin_src
$ sed 'w path.txt'  
reading /usr/local/bin directory
^d
#+end_src

~/usr/local/bin~ 을 ~/usr/bin~ 으로 대체하려면 다음과 같이 모든 슬래시 문자를 모두 이스케이프해야 한다:  

#+begin_src
$ sed 's/\/usr\/local\/bin/\/usr\/bin/' path.txt  
reading /usr/bin directory
#+end_src

이것은 보기에 복잡하고 긴 경로를 대체할 때는 이스케이프 문자 ~\~ 가 많아지므로 혼란스러울 수 있다. 다행히 sed는 대체 명령 구분자에 어떤 문자든 사용할 수 있도록 허용한다. (예: ~|~, ~^~, ~@~, ~!~ ... 등)  

다음은 모두 동일한 결과를 출력하며 가독성은 훨씬 더 좋다:  

#+begin_src
sed 's|/usr/local/bin|/usr/bin|' path.txt  
sed 's^/usr/local/bin^/usr/bin^' path.txt  
sed 's@/usr/local/bin@/usr/bin@' path.txt  
sed 's!/usr/local/bin!/usr/bin!' path.txt
#+end_src

개인적으로 디렉터리 경로를 대체할 때는 ~@~ 또는 ~!~ 기호를 사용할 것을 권장하지만 선택은 사용자에게 달려 있다.



** Multiple Substitute Commands
앞서 설명대로 sed의 실행 흐름은 "읽기(/Read/), 실행(/Execute/), 출력(/Print/), 반복(/Repeat/)" 이다. 실행 단계는 여러 개의 sed 명령으로 구성할 수 있으며 sed는 이를 하나씩 실행한다. 

예를 들어, 두 개의 sed 명령이 있을 경우 첫 번째 명령을 패턴 공간에 실행한 후, 두 번째 명령을 패턴 공간에 실행한다. 첫 번째 명령으로 패턴 공간을 변경했다면 두 번째 명령은 원래 줄이 아닌 변경된 패턴 공간에 실행한다.  

다음 예제는 패턴 공간에 두 개의 sed 대체 명령을 실행하는 과정을 보여준다.  

*"Developer" 를 "IT Manager" 로 변경한 후, "Manager" 를 "Director" 로 변경한다:*  

#+begin_src 
$ sed '{  
s/Developer/IT Manager/  
s/Manager/Director/  
}' employee.txt
101,John Doe,CEO  
102,Jason Smith,IT Director  
103,Raj Reddy,Sysadmin  
104,Anand Ram,IT Director  
105,Jane Miller,Sales Director  
#+end_src

예제 4번 줄의 실행 흐름을 분석해보자.  

- 읽기(/Read/) :: 이 단계는 줄을 읽은 후 패턴 공간에 넣는다. 따라서, 패턴 공간의 내용은 다음과 같다. ~104,Anand Ram,Developer~  

- 실행(/Execute/) :: 첫 번째 sed 명령 ~s/Developer/IT Manager/~ 를 패턴 공간에 실행한다. 이 명령 이후 패턴 공간의 내용은 다음과 같다. ~104,Anand Ram,IT Manager~ 그 후 두 번째 명령 ~s/Manager/Director/~ 를 패턴 공간에 실행한다. 이 명령 이후 패턴 공간의 내용은 다음과 같다. ~104,Anand Ram,IT Director~ *기억하자:* Sed는 첫 번째 명령을 실행한 후, 동일한 패턴 공간에 두 번째 명령을 실행한다.  

- 출력(/Print/) :: 패턴 공간의 내용을 출력한다. 출력은 다음과 같다. ~104,Anand Ram,IT Director~  

- 반복(/Repeat/) :: 다음 줄로 이동한 후 1단계부터 다시 반복한다.


** Power of & - Get Matched Pattern
~&~ 문자를 대체 문자열에 사용하면 검색 문자열 또는 정규 표현식과 일치한 텍스트로 대체된다.

#+begin_quote
[!TIP]
~&~ 를 반드시 대체 문자열에만 사용할 수 있는 것은 아니다! 검색 문자열에 사용할 수도 있다.
#+end_quote

다음은 몇 가지 예제이다.  

*사번(처음 세 자리 숫자)을 [...] 로 감싸기:*  

#+begin_src
$ sed 's/^[0-9][0-9][0-9]/[&]/g' employee.txt  
[101],John Doe,CEO  
[102],Jason Smith,IT Manager  
[103],Raj Reddy,Sysadmin  
[104],Anand Ram,Developer  
[105],Jane Miller,Sales Manager
#+end_src

*줄 전체를 <...> 로 감싸기:*  

#+begin_src
$ sed 's/^.*/<&>/' employee.txt  
<101,John Doe,CEO>  
<102,Jason Smith,IT Manager>  
<103,Raj Reddy,Sysadmin>  
<104,Anand Ram,Developer>  
<105,Jane Miller,Sales Manager>
#+end_src


** Substitution Grouping (Single Group)
대체 그룹(/Grouping/ 또는 /sub string/)은 정규 표현식과 동일하게 사용한다. 대체 그룹은 ~\(~ 로 시작하고 ~\)~ 로 종료한다. (하위 문자열 또는 부분 문자열이라 부름) 

그룹은 역참조(/back-referencing/)로 사용할 수 있다. 역참조는 그룹으로 선택한 정규 표현식의 일부를 재사용한다.

#+begin_quote
[!NOTE]
sed의 역참조는 검색 문자열과 대체 문자열 모두 사용할 수 있다.
#+end_quote
  
*단일 그룹핑:*  

#+begin_src
$ sed 's/\([^,]*\).*/\1/g' employee.txt  
101  
102  
103  
104  
105
#+end_src

위의 예제에서:  

- ~\([^,]*\)~ :: 첫 번째 쉼표까지의 문자열을 매칭한다.  

- ~\1~ :: 역참조는 첫 번째 그룹으로 매칭된 문자열로 대체한다.  

- ~g~ :: 글로벌 대체 플래그이다.  

*다음 sed 예제는 /etc/passwd 파일의 첫 번 필드(사용자 이름)만 출력한다:*  

#+begin_src
sed 's/\([^:]*\).*/\1/' /etc/passwd
#+end_src

*다음 예제는 각 단어의 첫 글자가 대문자일 경우만 괄호로 감싼다:*  

#+begin_src
$ echo "The Geek Stuff" | sed 's/\(\b[A-Z]\)/(\1)/g'  
(T)he (G)eek (S)tuff
#+end_src

예제를 위해 /numbers.txt/ 파일을 생성한다:  

#+begin_src
$ vi numbers.txt  
1  
12  
123   
1234  
12345  
123456
#+end_src

*세자리 숫자에 쉼표를 삽입해서 가독성 높이기:*  

#+begin_src
$ sed 's/\(^\|[^0-9.]\)\([0-9]\+\)\([0-9]\{3\}\)/\1\2,\3/g' numbers.txt  
1  
12  
123  
1,234  
12,345  
123,456
#+end_src

*위의 명령은 한 줄로 실행한다:*  

#+begin_src
sed 's/\(^\|[^0-9.]\)\([0-9]\+\)\([0-9]\{3\}\)/\1\2,\3/g' numbers.txt
#+end_src


** Substitution Grouping (Multiple Group)
다중 그룹은 여러 개의 그룹을 ~\(~ 와 ~\)~ 로 각각 감싸서 사용한다. 대체 명령의 검색 문자열에 여러 그룹이 존재할 경우, 대체 문자열에서 ~\n~ (n 은 숫자)형식으로 n번째 그룹을 역참조한다.  

*1번 필드(사번)와 3번 필드(직책)만 추출:*  

#+begin_src
$ sed 's/\([^,]*\),\([^,]*\),\([^,]*\).*/\1,\3/g' employee.txt  
101,CEO  
102,IT Manager  
103,Sysadmin  
104,Developer  
105,Sales Manager
#+end_src

*위의 명령은 한 줄로 실행한다:*  

#+begin_src
sed 's/\([^,]*\),\([^,]*\),\([^,]*\).*/\1,\3/g' employee.txt
#+end_src

위의 예제에서 검색 문자열에 세 개의 (하위 문자열) 그룹이 있다:  

- ~\([^,]*\)~ → 그룹 1: 사번  
- ~\([^,]*\)~ → 그룹 2: 이름  
- ~\([^,]*\)~ → 그룹 3: 직책  

대체 문자열에서:  

- ~\1~ → 그룹 1 출력 (사번)  
- ~,~ → 구분자 출력  
- ~\3~ → 그룹 3 출력 (직책)  

#+begin_quote
[!NOTE]
sed는 최대 9개의 그룹을 지원하며 ~\1~ 부터 ~\9~ 까지 역참조할 수 있다
#+end_quote
  
*1번 필드(사번)와 2번 필드(이름) 바꾸기:*  

#+begin_src
$ sed 's/\([^,]*\),\([^,]*\),\(.*\).*/\2,\1,\3/g' employee.txt  
John Doe,101,CEO  
Jason Smith,102,IT Manager  
Raj Reddy,103,Sysadmin  
Anand Ram,104,Developer  
Jane Miller,105,Sales Manager
#+end_src

*위의 명령은 한 줄로 실행한다:*  

#+begin_src
sed 's/\([^,]*\),\([^,]*\),\(.*\).*/\2,\1,\3/g' employee.txt
#+end_src


** Gnu Sed Only Replacement String Flags
다음 플래그는 GNU 버전의 sed만 사용 가능하고 대체 문자열에 사용한다.

*** ~\l~ 대체 문자열 플래그 
대체 문자열에 ~\l~ 플래그를 지정하면 ~\l~ 바로 다음 문자를 소문자로 변경한다. 

다음 예제는 "John" 을 "JOHNNY" 로 변경한다.  

#+begin_src
sed 's/John/JOHNNY/' employee.txt
#+end_src

다음 예제는 대체 문자열의 H 앞에 ~\l~ 플래그를 사용한다. (즉, ~JO\lHNNY~) "JOHNNY" 에서 h 문자만 소문자로 변경한다.  

*"John" 을 "JOhNNY" 로 변경:*  

#+begin_src
$ sed -n 's/John/JO\lHNNY/p' employee.txt
101,JOhNNY Doe,CEO
#+end_src

*** ~\L~ 대체 문자열 플래그  
대체 문자열에 ~\L~ 플래그를 지정하면 이후 모든 문자를 소문자로 변경한다. 

다음 예제는 대체 문자열 H 앞에 ~\L~ 을 사용한다. (즉, ~JO\LHNNY~) h 부터 나머지 문자를 모두 소문자로 변경한다.  

*"Johnny" 를 "JOhnny" 로 변경:*  

#+begin_src
$ sed -n 's/John/JO\LHNNY/p' employee.txt
101,JOhnny Doe,CEO
#+end_src

*** ~\u~ 대체 문자열 플래그  
~\l~ 플래그와 유사하지만 대문자 처리용이다. 대체 문자열에 ~\u~ 를 사용하면 ~\u~ 바로 다음 문자를 대문자로 변경한다. 

다음 예제는 대체 문자열의 h 앞에 ~\u~ 를 사용한다. (즉, ~jo\uhnny~) *johnny* 에서 h 문자만 대문자로 변경한다.  

*"John" 을 "joHnny" 로 변경:*  

#+begin_src
$ sed -n 's/John/jo\uhnny/p' employee.txt
101,joHnny Doe,CEO
#+end_src

*** ~\U~ 대체 문자열 플래그  
대체 문자열에 ~\U~ 를 사용하면 이후 모든 문자를 대문자로 변경한다. 

다음 예제는 대체 문자열의 h 앞에 ~\U~ 를 사용한다. (즉, ~jo\Uhnny~) "johnny" 에서 h 부터 나머지 문자 모두를 대문자로 변경한다.  

*"John" 을 "joHNNY" 로 변경:*  

#+begin_src
$ sed -n 's/John/jo\Uhnny/p' employee.txt
101,joHNNY Doe,CEO
#+end_src

*** ~\E~ 대체 문자열 플래그  
이 플래그는 ~\L~ 또는 ~\U~ 플래그와 함께 사용한다. ~\L~ 또는 ~\U~ 플래그로 시작한 변환 작업을 중단한다. 

다음 예제는 대체 문자열 시작에 ~\U~ 플래그가 있으므로 전체 문자열 "Johnny Boy" 를 대문자로 변경한다.  

*"John" 을 "JOHNNY BOY" 로 변경:*  

#+begin_src
$ sed -n 's/John/\UJohnny Boy/p' employee.txt
101,JOHNNY BOY Doe,CEO
#+end_src

*"John" 을 "JOHNNY Boy" 로 변경:*  

#+begin_src
$ sed -n 's/John/\UJohnny\E Boy/p' employee.txt
101,JOHNNY Boy Doe,CEO
#+end_src
위의 예제는 대체 문자열에서 "Johnny" 바로 뒤에 ~\E~ 플래그가 있으므로 "Johnny" 만 대문자로 변경한다.

*** 대체 문자열 플래그 사용법  
위의 정적인 예제는 대체 문자열 플래그를 어떻게 사용하는지 이해를 돕기 위해 사용한 것이다. 하지만, 대체 문자열 플래그는 정적인 값에 사용할 때는 별 가치가 없다. 왜냐하면, 정확한 대소문자를 정적인 문자열에 직접 입력할 수 있기 때문이다. 대체 문자열 플래그는 그룹에 사용할 때 유용하다.  

이전 예제에서 그룹(부분 문자열)을 사용해서 필드 1과 필드 3을 교환하는 방법을 배웠다. 이제 대체 문자열 플래그로 전체 그룹을 대문자 또는 소문자로 변환할 수 있다.

*직원 이름은 모두 대문자로, 직책은 모두 소문자로:*  

#+begin_src
$ sed 's/\([^,]*\),\([^,]*\),\(.*\).*/\U\2\E,\1,\L\3/g' employee.txt
JOHN DOE,101,ceo  
JASON SMITH,102,it manager  
RAJ REDDY,103,sysadmin  
ANAND RAM,104,developer  
JANE MILLER,105,sales manager
#+end_src

*위의 명령은 다음과 같이 한 줄로 실행한다:*  

#+begin_src
sed 's/\([^,]*\),\([^,]*\),\(.*\).*/\U\2\E,\1,\L\3/g' employee.txt
#+end_src

위의 예제는 대체 문자열에 다음과 같은 플래그를 사용한다: 

- ~\U\2\E~ :: 필드(두 번째 그룹 즉, 직원 이름)를 대문자로 변환한다. ~\U~ 플래그로 대문자 변환을 시작하고 ~\E~ 플래그로 변환을 중단한다.  

- ~\L\3~ :: 필드(세 번쨰 그룹 즉, 직책)를 소문자로 변환한다. ~\L~ 플래그로 나머지 문자의 소문자 변환을 시작한다.




* Regular Expressions

** Regular Expression Fundamentals
정규 표현식(또는 /regex/)은 sed를 포함한 수많은 Unix 명령에서 광범위하게 사용한다.

*** 줄의 시작 ( ^ )  
캐럿 ~^~ 문자는 줄의 시작 부분과 일치한다.  

*103으로 시작하는 줄 출력:*  

#+begin_src
$ sed -n '/^103/ p' employee.txt
103,Raj Reddy,Sysadmin
#+end_src

~^~ 문자는 정규 표현식의 첫 번째 문자일 때만 줄의 시작과 일치한다. ~^N~ 은 N 으로 시작하는 모든 줄과 일치한다.

*** 줄의 끝 ( $ )  
달러 ~$~ 문자는 줄의 끝과 일치한다.

*r 로 끝나는 줄 출력:*  

#+begin_src
$ sed -n '/r$/ p' employee.txt
102,Jason Smith,IT Manager  
104,Anand Ram,Developer  
105,Jane Miller,Sales Manager
#+end_src

#+begin_quote
[!NOTE]
~^,$~ 문자를 앵커(/Anchor/)라 부른다.
#+end_quote

*** 단일 문자 ( . )  
마침표 ~.~ 문자는 줄 바꿈 문자를 제외한 모든 문자와 일치한다. 

- ~.~ :: 한 문자와 일치  
- ~..~ :: 두 문자와 일치  
- ~...~ :: 세 문자와 일치  

다음 예제에서 J 다음 세 문자 그리고 공백 패턴을 "Jason" 다음에 공백으로 대체한다. 즉, ~J...~ 는 /employee.txt/ 파일의 "John " 과 "Jane " 모두 일치하며 이 두 줄을 다음과 같이 대체한다.  

#+begin_src
$ sed -n 's/J... /Jason /p' employee.txt
101,Jason Doe,CEO  
105,Jason Miller,Sales Manager
#+end_src

*** 0개 이상 반복 ( * )  
별표 ~*~ 문자는 바로 앞 문자의 0개 이상의 반복과 일치한다. 예를 들어, 패턴 ~1*~ 는 0개 이상의 1 과 일치한다.

설명을 위해 다음과 같은 /log.txt/ 파일을 생성한다:  

#+begin_src
$ vi log.txt
log: Input Validated  
log:  
log: testing resumed  
log:  
log:output created
#+end_src

"log:" 다음 메시지가 포함된 줄만 출력한다고 가정한다. 메시지는 "log:" 바로 뒤에 오거나 공백이 있을 수 있다. "log:" 만 있는 줄은 출력하지 않는다.  

*"하나 이상 공백이나 하나 이상 문자" 가 있는 "log:" 줄 출력:*  

#+begin_src
$ sed -n '/log: *./ p' log.txt
log: Input Validated  
log: testing resumed  
log:output created
#+end_src

#+begin_quote
[!NOTE]
위의 예제에서 마지막 점(~.~) 문자는 *필수* 이다. 이를 포함하지 않으면 "log:~ 만 있는 줄도 출력한다.
#+end_quote

*** 1개 이상의 반복 ( \+ )  
플러스 ~\+~ 문자는 바로 앞 문자의 1개 이상의 반복과 일치한다. 예를 들어, ~\+~ 는 하나 이상의 공백 문자와 일치한다.

이전과 동일한 /log.txt/ 파일 사용:  

*"하나 이상 공백" 이 있는 "log:" 줄 출력:*  

#+begin_src
$ sed -n '/log: \+/ p' log.txt
log: Input Validated  
log: testing resumed
#+end_src

#+begin_quote
[!NOTE]
위의 예제는 "log:" 만 있는 줄 뿐만아니라 "log:output created" 줄도 일치하지 않는다. 왜냐하면, 해당 줄은 "log:" 뒤에 공백이 없기 때문이다.
#+end_quote

*** 0개 또는 1개의 반복 ( \? )  
물음표 ~\?~ 문자는 바로 앞 문자의 0개 또는 1개의 반복과 일치한다.  

#+begin_src
$ sed -n '/log: \?/ p' log.txt
log: Input Validated  
log:  
log: testing resumed  
log:  
log:output created
#+end_src

*** 특수 문자 이스케이프 ( \\ )  
정규 표현식에 특수 문자(예: ~*~, ~.~) 자체를 사용하려면 해당 문자를 이스케이프 처리해야 한다.  

#+begin_src
$ sed -n '/127\.0\.0\.1/ p' /etc/hosts
127.0.0.1 localhost.localdomain localhost
#+end_src

*** 문자 클래스 ( [0-9] )  
문자 클래스는 대괄호 안에 나열한 문자들의 집합이며 나열한 문자 중 하나와 일치한다.  

*2 또는 3 또는 4를 포함한 줄 출력:*  

#+begin_src
$ sed -n '/[234]/ p' employee.txt
102,Jason Smith,IT Manager  
103,Raj Reddy,Sysadmin  
104,Anand Ram,Developer
#+end_src

대괄호에 하이픈 문자를 사용하면 문자 범위를 지정할 수 있다. 예를 들어, ~[0123456789]~ 는 ~[0-9]~ 로 표현할 수 있고 알파벳 범위는 ~[a-z]~, ~[A-Z]~ 로 지정할 수 있다.

*2 또는 3 또는 4를 포함한 줄 출력(대체 형식):*  

#+begin_src
$ sed -n '/[2-4]/ p' employee.txt
102,Jason Smith,IT Manager  
103,Raj Reddy,Sysadmin  
104,Anand Ram,Developer
#+end_src


** Additional Regular Expressions

*** OR 연산 ( \| )  
파이프 ~\|~ 문자는 두 개의 표현식 중 하나만 해당 위치에 나타날 수 있음을 의미한다. 즉, ~subexpression1|subexpression2~ 는 subexpression1 또는 subexpression2 둘 중 하나와 일치한다.  

*101 또는 102 를 포함한 줄 출력:*  

#+begin_src
$ sed -n '/101\|102/ p' employee.txt
101,John Doe,CEO  
102,Jason Smith,IT Manager
#+end_src

#+begin_quote
[!NOTE]
~|~ 기호는 ~\~ 로 이스케이프 처리해야 한다.
#+end_quote

*2~3 사이의 숫자를 포함하거나 문자열 105 를 포함한 줄 출력:*  

#+begin_src
$ sed -n '/[2-3]\|105/ p' employee.txt
102,Jason Smith,IT Manager  
103,Raj Reddy,Sysadmin  
105,Jane Miller,Sales Manager
#+end_src

*** 정확히 M 번 반복 ( \{m\} )  
정규 표현식 뒤에 ~\{m\}~ 을 붙이면 앞의 표현식은 정확히 ~m~ 번 반복될 경우만 일치한다.  

다음과 같은 /numbers.txt/ 파일을 생성한다:  

#+begin_src
$ sed -n 'w numbers.txt'
1  
12  
123  
1234  
12345  
123456
^d
#+end_src

*숫자를 포함한 모든 줄 출력 (모든 줄 출력됨):*  

#+begin_src
$ sed -n '/[0-9]/ p' numbers.txt
1  
12  
123  
1234  
12345  
123456
#+end_src

*정확히 5자리 숫자로 구성된 줄만 출력:*  

#+begin_src
$ sed -n '/^[0-9]\{5\}$/ p' numbers.txt
12345
#+end_src

*** M\~N번 반복 ( \{m,n\} )  
정규 표현식 뒤에 ~\{m,n\}~ 을 붙이면 앞 항목이 최소 ~m~ 번, 최대 ~n~ 번 반복될 경우 일치한다. ~m~ 과 ~n~ 은 0 이상 255 미만이라야 한다.  

*최소 3자리, 최대 5자리 숫자로 구성된 줄만 출력:*  

#+begin_src
$ sed -n '/^[0-9]\{3,5\}$/ p' numbers.txt
123  
1234  
12345
#+end_src

~\{m,\}~ 형식은 ~m~ 번 이상 반복될 경우만 일치하는 특수 형식이다.

*** 단어 경계 ( \b )  
~\b~ 는 단어 경계를 일치시킬 때 사용한다. ~\b~ 는 단어 시작(~\bxx~) 이나 끝(~xx\b~) 문자와 일치한다. 따라서, ~\bthe\b~ 는 "the" 와 정확히 일치하지만 "they" 와 일치하지 않는다. ~\bthe~ 는 "the" 또는 "they" 와 일치한다.

다음과 같은 /words.txt/ 파일을 생성한다:  

#+begin_src
$ cat words.txt
word matching using: the  
word matching using: thethe  
word matching using: they
#+end_src

*전체 단어 "the" 를 포함한 줄 출력:*  

#+begin_src
$ sed -n '/\bthe\b/ p' words.txt
word matching using: the
#+end_src

#+begin_quote
[!NOTE]
끝에 ~\b~ 를 지정하지 않으면 모든 줄과 일치한다.
#+end_quote

*"the" 로 시작하는 단어를 포함한 줄 출력:*  

#+begin_src
$ sed -n '/\bthe/ p' words.txt
word matching using: the  
word matching using: thethe  
word matching using: they
#+end_src

*** 역참조 ( \n )  
역참조는 표현식을 그룹화하고 재사용할 수 있다. 

*"the" 단어가 두 번 반복된 줄 출력:*  

#+begin_src
$ sed -n '/\(the\)\1/ p' words.txt
#+end_src

정규 표현식 ~\([0-9]\)\1~ 패턴은 두 자리 숫자 중 두 숫자가 동일할 경우(예: 11, 22, 33 등) 일치한다.


** Sed Substitution Using Regular Expression
다음은 정규 표현식 특수 문자를 사용하는 몇 가지 예제이다.

*employee.txt 파일 각 줄에서 마지막 두 문자를 ",Not Defined" 로 대체:*  

#+begin_src
$ sed 's/..$/,Not Defined/' employee.txt
101,John Doe,C,Not Defined  
102,Jason Smith,IT Manag,Not Defined  
103,Raj Reddy,Sysadm,Not Defined  
104,Anand Ram,Develop,Not Defined  
105,Jane Miller,Sales Manag,Not Defined
#+end_src

*"Manager" 로 시작하는 줄 삭제:*  

#+begin_src
$ sed 's/Manager.*//' employee.txt
101,John Doe,CEO  
102,Jason Smith,IT  
103,Raj Reddy,Sysadmin  
104,Anand Ram,Developer  
105,Jane Miller,Sales
#+end_src

*# 문자로 시작하는 모든 줄과 빈 줄 삭제:*  

#+begin_src
sed -e 's/#.*//; /^$/ d' employee.txt
#+end_src

다음 예제를 위해 /test.html/ 파일을 생성한다:  

#+begin_src
$ vi test.html
<html><body><h1>Hello World!</h1></body></html>
#+end_src

*test.html 파일의 모든 HTML 태그 제거:*  

#+begin_src
$ sed -e 's/<[^>]*>//g' test.html
Hello World!
#+end_src

*모든 주석과 빈 줄 제거:*  

#+begin_src
sed -e 's/#.*//' -e '/^$/ d' /etc/profile
#+end_src

*주석만 제거하고 빈 줄은 유지:*  

#+begin_src
sed -e '/^#.*/ d' /etc/profile
#+end_src

*DOS 개행(CR/LF) 문자를 Unix 형식으로 변환:*  

DOS 파일을 Unix로 복사하면 줄 끝에 ~\r\n~ 이 포함될 수 있다.  

*sed로 DOS 파일 형식을 Unix 형식으로 변환:*  

#+begin_src
sed 's/.$//' filename
#+end_src



* Sed Execution

** Multiple Sed Commands in Command Line
1장에서 설명한 것처럼 명령줄에 여러 개의 sed 명령을 실행하는 방법은 여러 가지이다.

*** ~-e~ 옵션을 여러 번 사용하는 방법
다음과 같이 ~-e~ 옵션을 여러 번 사용해서 여러 개의 sed 명령을 실행한다:  

#+begin_src
sed -e 'command1' -e 'command2' -e 'command3'
#+end_src

*~/etc/passwd~ 파일에서 "root", "nobody", "mail" 출력:*  

#+begin_src
sed -n -e '/^root/ p' -e '/^nobody/ p' -e '/^mail/ p' /etc/passwd
#+end_src

위의 명령은 한 줄로 실행한다.

*** ~\~ 로 긴 명령 줄 바꿈
명령줄에서 ~-e~ 옵션을 여러 번 사용할 때 명령이 너무 길면 ~\~ 문자로 여러 줄로 나눈다:  

#+begin_src
sed -n -e '/^root/ p' \
-e '/^nobody/ p' \
-e '/^mail/ p' \
/etc/passwd
#+end_src

*** ~{...}~ 로 여러 개의 명령 그룹화
여러 개의 sed 명령을 실행할 경우 ~{...}~ 로 명령을 그룹화한다:  

#+begin_src
sed -n '{
/^root/ p
/^nobody/ p
/^mail/ p
}' /etc/passwd
#+end_src


** Sed Script Files
sed 명령을 재사용하려면 sed 명령을 sed 스크립트 파일에 저장한 후 ~-f~ 옵션으로 실행한다.

다음과 같이 sed 명령을 포함한 파일을 생성한다. 개별 sed 명령이 무엇을 처리할지는 이전 섹션에서 모두 설명했다.  

#+begin_src
$ sed -n 'w mycommands.sed'
s/\([^,]*\),\([^,]*\),\(.*\).*/\2,\1,\3/g  
s/^.*/<&>/  
s/Developer/IT Manager/  
s/Manager/Director/
^d
#+end_src

다음과 같이 sed 명령 파일을 입력 파일에 적용한다.  

#+begin_src
$ sed -f mycommands.sed employee.txt
<John Doe,101,CEO>  
<Jason Smith,102,IT Director>  
<Raj Reddy,103,Sysadmin>  
<Anand Ram,104,IT Director>  
<Jane Miller,105,Sales Director>
#+end_src


** Sed Comments
sed의 주석은 ~#~ 문자로 시작한다!! 

우리 모두는 sed가 "난해한 언어를 사용한다!" 는 것을 잘 알고 있다. 방금 작성한 sed 명령을 시간이 지난 후에 다시 보면 낯설게 느껴질 수 있다. 따라서, 다음과 같이 sed 스크립트 파일에 주석으로 사용 의미를 문서화할 것을 강력히 권장한다.  

#+begin_src
$ sed -n 'w mycommands.sed'
# Swap field 1 (employee id) with field 2 (employee name)  
s/\([^,]*\),\([^,]*\),\(.*\).*/\2,\1,\3/g  
# Enclose the whole line within < and >  
s/^.*/<&>/  
# Replace Developer with IT Manager  
s/Developer/IT Manager/  
# Replace Manager with Director  
s/Manager/Director/
^d
#+end_src

#+begin_quote
[!NOTE]
~*.sed~ 스크립트 파일의 첫 번째 줄의 처음 두 문자가 ~#n~ 이면 sed는 ~-n~ (패턴 버퍼를 출력하지 않음)옵션을 적용한다.
#+end_quote


** Sed as an Interpreter
쉘 스크립트로 작성한 후 명령줄에서 실행하는 것처럼 sed 스크립트도 명령줄에서 실행할 수 있다. 즉, sed를 인터프리터로 사용한다. 

이를 위해 /sed-script.sh/ 파일 첫 번째 줄에 ~#!/bin/sed -f~ 를 추가한다.  

#+begin_src
$ sed -n 'w myscript.sed'
#!/bin/sed -f  
# Swap field 1 (employee id) with field 2 (employee name)  
s/\([^,]*\),\([^,]*\),\(.*\).*/\2,\1,\3/g  
# Enclose the whole line within < and >  
s/^.*/<&>/  
# Replace Developer with IT Manager  
s/Developer/IT Manager/  
# Replace Manager with Director  
s/Manager/Director/
^d
#+end_src

*이제 명령줄에서 다음과 같이  sed 스크립트를 실행한다*:  

#+begin_src
chmod u+x myscript.sed  
./myscript.sed employee.txt
#+end_src

*기본 출력을 억제하려면 sed 스크립트 첫 번 줄에 -n 옵션을 지정한다.*:

#+begin_src
$ sed -n 'w testscript.sed'
#!/bin/sed -nf  
/root/ p  
/nobody/ p
#+end_src

*위의 스크립트는 다음과 같이 실행한다.*

#+begin_src
chmod u+x testscript.sed  
./testscript.sed /etc/passwd
#+end_src

테스트 목적으로 /testscript.sed/ 파일 첫 번째 줄의 ~-n~ 옵션을 제거해서 작동 방식을 확인한다.

#+begin_quote
[!NOTE]
반드시 ~-nf~ 형태로 사용하며 ~-fn~ 형태로 사용해선 안된다. ~-fn~ 을 지정하면 sed 스크립트를 실행할 때 다음과 같은 오류 메시지가 나타난다. "couldn't open file n: No such file or directory"
#+end_quote


** Modifying the Input File Directly
이미 잘 알듯이 sed는 기본적으로 "입력 파일을 수정하지 않는다!!" sed는 출력을 표준 출력으로만 보낼 뿐이다. 파일에 저장하려면 파일로 리디렉션하거나 ~w~ 명령이나 플래그를 사용한다.

*예제를 계속하기 전에 employee.txt 백업 파일을 만든다:*  

#+begin_src
cp employee.txt employee.txt.orig
#+end_src

*입력 파일을 수정하려면 출력 결과를 임시 파일로 리디렉션한 다음 생성한 임시 파일을 새로운 파일로 이름을 바꾼다:*  

#+begin_src
sed 's/John/Johnny/' employee.txt > new-employee.txt  
mv new-employee.txt employee.txt
#+end_src

하지만, sed 명령줄 옵션 ~-i~ (/in-place/)로 입력 파일을 직접 수정할 수 있다.

*employee.txt 파일에서 "John" 을 "Johnny" 로 바꾼다:*  

#+begin_src
$ sed -i 's/John/Johnny/' employee.txt  
$ cat employee.txt
101,Johnny Doe,CEO  
102,Jason Smith,IT Manager  
103,Raj Reddy,Sysadmin  
104,Anand Ram,Developer  
105,Jane Miller,Sales Manager
#+end_src

다시 말하지만, ~-i~ 옵션은 입력 파일을 수정한다!! 가끔 이렇게 처리할 수도 있지만 주의해서 사용해야 한다!! 

원본 파일을 보호하려면 ~-i~ 옵션에 백업 파일 확장자를 추가한다. sed는 내용을 쓰기 전에 원래 파일의 백업 파일을 만든다.

*employee.txt 파일에서 "John" 을 "Johnny" 로 바꾸고 복사본을 생성한다:*  

#+begin_src
$ sed -ibak 's/John/Johnny/' employee.txt
#+end_src

*다음과 같이 원본 파일의 백업 파일을 만든다:*

#+begin_src
$ sed '' employee.txtbak
101,John Doe,CEO  
102,Jason Smith,IT Manager  
103,Raj Reddy,Sysadmin  
104,Anand Ram,Developer  
105,Jane Miller,Sales Manager
#+end_src

*위의 sed 명령으로 원본 파일은 다음과 같이 수정된다:*

#+begin_src
$ sed -n 'p' employee.txt
101,Johnny Doe,CEO  
102,Jason Smith,IT Manager  
103,Raj Reddy,Sysadmin  
104,Anand Ram,Developer  
105,Jane Miller,Sales Manager
#+end_src

*i 옵션 대신 긴 형식의 --in-place 옵션을 사용할 수 있다. 따라서, 다음 두 명령은 동일하다:*

#+begin_src
sed -ibak 's/John/Johnny/' employee.txt  
sed --in-place=bak 's/John/Johnny/' employee.txt
#+end_src

*마지막으로 다음 예제를 위해 employee.txt 파일을 복원한다:*

#+begin_src
cp employee.txt.orig employee.txt
#+end_src



* Additional Sed Command

** Append Line After (a command)
특정 위치 뒤에 새로운 줄을 추가하려면 ~a~ (/append/)명령을 사용한다.
  
#+begin_src
$ sed '[address] a the-line-to-append' input-file
#+end_src

*줄 뒤에 새로운 줄을 employee.txt 파일에 추가:*  

#+begin_src
$ sed '2 a 203,Jack Johnson,Engineer' employee.txt
101,John Doe,CEO  
102,Jason Smith,IT Manager  
203,Jack Johnson,Engineer  
103,Raj Reddy,Sysadmin  
104,Anand Ram,Developer  
105,Jane Miller,Sales Manager
#+end_src

*employee.txt 파일 끝에 새로운 줄 추가:*  

#+begin_src
$ sed '$ a 106,Jack Johnson,Engineer' employee.txt
101,John Doe,CEO  
102,Jason Smith,IT Manager  
103,Raj Reddy,Sysadmin  
104,Anand Ram,Developer  
105,Jane Miller,Sales Manager  
106,Jack Johnson,Engineer
#+end_src

~a~ 명령은 여러 줄을 추가할 수 있다.

#+begin_quote
[!IMPORTANT]
이 경우 ~a\~ 형식으로 여러 줄을 입력하고 마지막 줄은 ~\~ 문자를 붙이지 않는다.
#+end_quote

*"Jason" 과 일치한 줄 뒤에 두 줄 추가:*  

#+begin_src
$ sed '/Jason/a\
203,Jack Johnson,Engineer\
204,Mark Smith,Sales Engineer' employee.txt
101,John Doe,CEO  
102,Jason Smith,IT Manager  
203,Jack Johnson,Engineer  
204,Mark Smith,Sales Engineer  
103,Raj Reddy,Sysadmin  
104,Anand Ram,Developer  
105,Jane Miller,Sales Manager
#+end_src


** Insert Line Before (i command)
~i~ (/insert/)명령은 /append/ 명령과 동일하지만 특정 위치의 뒤가 아니라 앞에 줄을 삽입한다.

#+begin_src
$ sed '[address] i the-line-to-insert' input-file
#+end_src

*employee.txt 파일 2번 줄 앞에 새로운 줄 삽입:*  

#+begin_src
$ sed '2 i 203,Jack Johnson,Engineer' employee.txt
101,John Doe,CEO  
203,Jack Johnson,Engineer  
102,Jason Smith,IT Manager  
103,Raj Reddy,Sysadmin  
104,Anand Ram,Developer  
105,Jane Miller,Sales Manager
#+end_src

*employee.txt 파일의 마지막 줄 앞에 새로운 줄 삽입:*  

#+begin_src
$ sed '$ i 108,Jack Johnson,Engineer' employee.txt
101,John Doe,CEO  
102,Jason Smith,IT Manager  
103,Raj Reddy,Sysadmin  
104,Anand Ram,Developer  
108,Jack Johnson,Engineer  
105,Jane Miller,Sales Manager
#+end_src

~i~ 명령은 여러 줄을 삽입할 수 있다.

*"Jason" 과 일치한 줄 앞에 두 줄 삽입:*  

#+begin_src
$ sed '/Jason/i\
203,Jack Johnson,Engineer\
204,Mark Smith,Sales Engineer' employee.txt
101,John Doe,CEO  
203,Jack Johnson,Engineer  
204,Mark Smith,Sales Engineer  
102,Jason Smith,IT Manager  
103,Raj Reddy,Sysadmin  
104,Anand Ram,Developer  
105,Jane Miller,Sales Manager
#+end_src


** Change Line (c command)
~c~ (/change/)명령은 기존 줄을 새로운 줄로 교체한다.

#+begin_src
$ sed '[address] c the-line-to-insert' input-file
#+end_src

*employee.txt 파일 2번 줄을 삭제하고 새로운 줄로 교체:*  

#+begin_src
$ sed '2 c 202,Jack Johnson,Engineer' employee.txt
101,John Doe,CEO  
202,Jack Johnson,Engineer  
103,Raj Reddy,Sysadmin  
104,Anand Ram,Developer  
105,Jane Miller,Sales Manager
#+end_src

한 줄을 여러 줄로 교체할 수 있다.

*"Raj" 와 일치한 줄을 삭제하고 두 개의 새로운 줄로 교체:*  

#+begin_src
$ sed '/Raj/c\
203,Jack Johnson,Engineer\
204,Mark Smith,Sales Engineer' employee.txt
101,John Doe,CEO  
102,Jason Smith,IT Manager  
203,Jack Johnson,Engineer  
204,Mark Smith,Sales Engineer  
104,Anand Ram,Developer  
105,Jane Miller,Sales Manager
#+end_src


** Combine a, i, and c Commands
~a~, ~i~, ~c~ 명령은 함께 사용할 수 있다. 다음 예제는 세 가지 작업을 동시에 실행한다: 

- ~a~ :: "Jason" 다음에 "Jack Johnson" 추가  
- ~i~ :: "Jason" 앞에 "Mark Smith" 삽입  
- ~c~ :: "Jason" 을 "Joe Mason" 으로 변경  

#+begin_src
$ sed '/Jason/ {
a\
204,Jack Johnson,Engineer
i\
202,Mark Smith,Sales Engineer
c\
203,Joe Mason,Sysadmin
}' employee.txt
101,John Doe,CEO  
202,Mark Smith,Sales Engineer  
203,Joe Mason,Sysadmin  
204,Jack Johnson,Engineer  
103,Raj Reddy,Sysadmin  
104,Anand Ram,Developer  
105,Jane Miller,Sales Manager
#+end_src


** Print Hidden Characters (l command)
~l~ (/list/)명령은 출력에서 숨겨진 문자를 출력한다. 예를 들어, 탭 문자는 ~\t~, 줄 바꿈 문자는 ~$~ 로 출력한다.

테스트를 위한 파일을 생성한다. 필드에 탭 키를 사용한다.  

#+begin_src
$ sed '' tabfile.txt
fname    First Name  
lname    Last Name  
mname    Middle Name
#+end_src

~l~ 명령은 탭 문자를 ~\t~, 줄 끝(줄바꿈)은 ~$~ 로 출력한다:  

#+begin_src
$ sed -n l tabfile.txt
fname\tFirst Name$  
lname\tLast Name$  
mname\tMiddle Name$
#+end_src

숫자와 함께 ~l~ 명령을 실행하면 지정한 숫자에 줄바꿈하고 비출력 문자를 출력한다. 이 기능은 *GNU sed만 작동* 한다.  

#+begin_src
$ sed -n 'l 20' employee.txt
101,John Doe,CEO$  
102,Jason Smith,IT \  
Manager$  
103,Raj Reddy,Sysad\  
min$  
104,Anand Ram,Devel\  
oper$  
105,Jane Miller,Sal\  
es Manager$
#+end_src


** Print Line Numbers (= command)
~=~ (/equal, print line number/)명령은 줄 번호를 출력하며 다음 줄에 줄 내용을 출력한다.

*모든 줄 번호 출력:* 

#+begin_src
$ sed = employee.txt
1  
101,John Doe,CEO  
2  
102,Jason Smith,IT Manager  
3  
103,Raj Reddy,Sysadmin  
4  
104,Anand Ram,Developer  
5  
105,Jane Miller,Sales Manager
#+end_src

#+begin_quote
[!NOTE]
~=~ 명령을 ~N~ 명령과 결합하면 줄 번호와 줄 내용을 같은 줄에 출력할 수 있다. (자세한 내용은 나중에 설명)
#+end_quote

*1, 2, 3번 줄만 줄 번호 출력:*  

#+begin_src
$ sed '1,3 =' employee.txt
1  
101,John Doe,CEO  
2  
102,Jason Smith,IT Manager  
3  
103,Raj Reddy,Sysadmin  
104,Anand Ram,Developer  
105,Jane Miller,Sales Manager
#+end_src

*"Jane" 키워드를 포함한 줄만 줄 번호 출력. 입력 파일의 원래 줄도 출력한다:*  

#+begin_src
$ sed '/Jane/ =' employee.txt
101,John Doe,CEO  
102,Jason Smith,IT Manager  
103,Raj Reddy,Sysadmin  
104,Anand Ram,Developer  
5  
105,Jane Miller,Sales Manager
#+end_src

*키워드를 포함한 줄 번호만 표시하고 원래 줄은 출력하지 않으려면 -n 옵션과 함께 = 명령을 사용한다:*  

#+begin_src
$ sed -n '/Raj/ =' employee.txt
3
#+end_src

*파일의 전체 줄 수 출력:*  

#+begin_src
$ sed -n '$ =' employee.txt
5
#+end_src


** Change Case (using the y 'transform' command)
~y~ (/transform/)명령은 문자를 변환한다. 이를 편하게 사용할 방법 중 하나는 대문자를 소문자로 또는 그 반대로 변환하는 것이다.

*예제는 "a" 는 "A" 로, "b" 는 "B" 로, "c" 는 "C" ... 로 변환한다:*  

#+begin_src
$ sed 'y/abcde/ABCDE/' employee.txt
101,John DoE,CEO  
102,JAson Smith,IT MAnAgEr  
103,RAj REDDy,SysADmin  
104,AnAnD RAm,DEvElopEr  
105,JAnE MillEr,SAlEs MAnAgEr
#+end_src

*모든 소문자를 대문자로 변환:*  

#+begin_src
$ sed 'y/abcdefghijklmnopqrstuvwxyz/ABCDEFGHIJKLMNOPQRSTUVWXYZ/' employee.txt
101,JOHN DOE,CEO  
102,JASON SMITH,IT MANAGER  
103,RAJ REDDY,SYSADMIN  
104,ANAND RAM,DEVELOPER  
105,JANE MILLER,SALES MANAGER
#+end_src

*위의 명령은 다음과 같이 한 줄로 실행한다:*  

#+begin_src
sed 'y/abcdefghijklmnopqrstuvwxyz/ABCDEFGHIJKLMNOPQRSTUVWXYZ/' employee.txt
#+end_src


** Multiple Files in Command Line
이전 모든 sed 예제는 하나의 입력 파일만 사용했다. sed는 여러 개의 입력 파일을 전달해서 실행할 수 있다.

*다음 예제는 /etc/passwd 파일에서 "root" 를 검색하고 출력한다:*  

#+begin_src
$ sed -n '/root/ p' /etc/passwd
root:x:0:0:root:/root:/bin/
#+end_src

*다음 예제는 /etc/group 파일에서 "root" 를 검색하고 출력한다:*  

#+begin_src
$ sed -n '/root/ p' /etc/group
root:x:0:
#+end_src

*/etc/passwd 와 /etc/group 두 파일에서 "root" 를 검색하고 출력한다:*  

#+begin_src
$ sed -n '/root/ p' /etc/passwd /etc/group
root:x:0:0:root:/root:/bin/  
root:x:0:
#+end_src


** Quit Sed (q command)
~q~ (/quit/)명령은 실행을 중단한다. 앞서 설명한대로 일반적인 sed 실행 흐름은 "읽기(/Read/), 실행(/Execute/), 출력(/Print/), 반복(/Repeat/)" 이다. 

~q~ 명령을 실행하면 나머지 sed 명령을 실행하지 않고 입력 파일의 나머지 줄을 반복하지 않고 즉시 종료한다.

*첫 번째 줄 출력 후 종료:*  

#+begin_src
$ sed 'q' employee.txt
101,John Doe,CEO
#+end_src

*다섯 번째 줄에서 종료. 즉, 처음 5줄 출력:*  

#+begin_src
$ sed '5 q' employee.txt
101,John Doe,CEO  
102,Jason Smith,IT Manager  
103,Raj Reddy,Sysadmin  
104,Anand Ram,Developer  
105,Jane Miller,Sales Manager
#+end_src

*"Manager" 키워드를 포함한 첫 번째 줄까지 출력:*  

#+begin_src
$ sed '/Manager/q' employee.txt
101,John Doe,CEO  
102,Jason Smith,IT Manager
#+end_src

#+begin_quote
[!NOTE]
~q~ 명령은 주소 범위를 허용하지 않는다. 즉, 단일 주소(또는 단일 패턴)만 작동한다.
#+end_quote


** Read from File (r command)
~r~ (/read/)명령은 입력 파일을 처리할 때 다른 파일의 내용을 읽어와서 지정한 위치에 출력한다.

*다음 예제는 log.txt 파일의 내용을 읽어 employee.txt 마지막 줄 뒤에 출력한다. 따라서, employee.txt 와 log.txt 를 결합해서 출력한다:*  

#+begin_src
$ sed '$ r log.txt' employee.txt
#+end_src

패턴 주소에 ~r~ 명령을 실행할 수 있다. 다음 예제는 /employee.txt/ 파일에서 "Raj" 와 일치한 줄 뒤에 /log.txt/ 파일 내용을 출력한다.

*employee.txt 파일에서 "Raj" 키워드 뒤에 log.txt 파일 삽입:*  

#+begin_src
$ sed '/Raj/ r log.txt' employee.txt
#+end_src


** Simulating Unix commands in sed (cat, grep, head)
지금까지 표준 UNIX 프로그램처럼 작동하는 sed 예제를 살펴봤다. sed로 여러 가지 프로그램을 시뮬레이션할 수 있다. 

sed의 작동 방식을 이해하기 위해 분석하길 바란다.

*** Cat in sed  
#+begin_src
cat employee.txt
#+end_src

*다음 sed 명령들은 위의 cat 명령과 동일한 출력을 생성한다:* 

#+begin_src
sed 's/JUNK/&/p' employee.txt  
sed -n 'p' employee.txt  
sed 'n' employee.txt  
sed 'N' employee.txt
#+end_src

*** Grep in sed
*단순 grep:*  

#+begin_src
grep Jane employee.txt
#+end_src

*다음 sed 명령들은 위의 grep 명령과 동일한 출력을 생성한다:*  

#+begin_src
sed -n 's/Jane/&/p' employee.txt  
sed -n '/Jane/ p' employee.txt
#+end_src

*grep -v (일치하지 않는 줄 출력):*  

#+begin_src
grep -v Jane employee.txt
#+end_src

*다음 sed 명령은 위의 grep -v 명령과 동일하다:*  

#+begin_src
sed -n '/Jane/! p' employee.txt
#+end_src

*** Head in sed
#+begin_src
head -10 /etc/passwd
#+end_src

*다음 sed 명령들은 위의 head 명령과 동일한 출력을 생성한다:*  

#+begin_src
sed '11,$ d' /etc/passwd  
sed -n '1,10 p' /etc/passwd  
sed '10 q' /etc/passwd
#+end_src


** Sed Command Line Options

*** -n 옵션  
이 옵션은 이미 많이 설명했고 많은 예제에서 사용했다. 

~-n~ 옵션은 표준 sed 실행 흐름의 일부로 발생하는 기본 출력을 억제한다. ~--quiet~ 또는 ~--silent~ 옵션을 ~-n~ 옵션 대신 사용할 수 있다. 기능은 동일하다.

*다음 명령들은 모두 동일하다:*  

#+begin_src
sed -n 'p' employee.txt  
sed --quiet 'p' employee.txt  
sed --silent 'p' employee.txt
#+end_src

*** -f 옵션  
여러 개의 sed 명령을 파일에 저장하고 ~-f~ 옵션으로 sed 스크립트 파일을 호출할 수 있다. 앞에서 이미 시연했다. ~--file~ 옵션도 동일하다.

*다음 명령들은 모두 동일하다:*  

#+begin_src
sed -n -f test-script.sed /etc/passwd  
sed -n --file=test-script.sed /etc/passwd
#+end_src

*** -e 옵션  
~-e~ 옵션으로 명령줄에서 sed 명령를 실행한다. 명령줄에 여러 개의 ~-e~ 옵션을 사용할 수도 있다. ~--expression~ 도 동일다.

*다음 명령들은 모두 동일하다:*  

#+begin_src
sed -n -e '/root/ p' /etc/passwd  
sed -n --expression '/root/ p' /etc/passwd
#+end_src

*** -i 옵션  
이미 설명했듯이 sed는 절대 입력 파일을 수정하지 않는다!! 항상 표준 출력으로 출력하거나 ~w~ 명령이나 플래그로 다른 파일에 출력한다. ~-i~ 옵션으로 입력 파일을 수정하는 방법도 이미 보여줬다.

*employee.txt 파일에서 "John" 을 "Johnny" 로 변경:* 

#+begin_src
sed -i 's/John/Johnny/' employee.txt
#+end_src

*동일한 명령을 실행하지만 -i 옵션에 확장자를 추가해서 백업 파일 생성:*  

#+begin_src
sed -ibak 's/John/Johnny/' employee.txt
#+end_src

~-i~ 대신 ~--in-place~ 옵션을 사용할 수 있다.

*다음 명령들은 모두 동일하다:*  

#+begin_src
sed -ibak 's/John/Johnny/' employee.txt  
sed --in-place=bak 's/John/Johnny/' employee.txt
#+end_src

*** -c 옵션  
이 옵션은 sed ~-i~ 옵션과 함께 사용한다. sed의 ~-i~ 옵션은 변경 사항을 처리할 때 임시 파일을 사용하고 작업이 완료되면 이를 원본 파일로 이름을 바꾼다. 이로 인해, 파일 소유권이 변경된다. ~-i~ 옵션과 ~-c~ 옵션을 사용하면 파일 소유권을 변경하지 않는다. ~--copy~ 옵션도 사용할 수 있다.

*다음 명령들은 모두 동일하다:*  

#+begin_src
sed -ibak -c 's/John/Johnny/' employee.txt  
sed --in-place=bak --copy 's/John/Johnny/' employee.txt
#+end_src

*** -l 옵션  
출력할 줄 길이를 지정한다. ~l~ 명령과 함께 사용한다. ~-l~ 옵션에 지정한 값은 줄의 넓이로 사용된다. ~--line-length~ 도 사용할 수 있다.

*다음 명령들은 모두 동일하다:*  

#+begin_src
sed -n -l 20 'l' employee.txt  
sed -n --line-length=20 employee.txt
#+end_src

*-n 옵션으로 동일한 출력을 얻을 수 있다:*  

#+begin_src
sed -n 'l 20' employee.txt
#+end_src


** Print Pattern Space (n command)
~n~ (/next/)명령은 패턴 공간을 출력하고 입력 파일에서 다음 줄을 가져온다. 이 동작은 명령 실행 중에도 발생하며 다른 명령 사이에 사용할 경우 일반적인 실행 흐름을 변경한다.

*각 줄의 패턴 공간 출력:*  

#+begin_src
$ sed n employee.txt
101,John Doe,CEO  
102,Jason Smith,IT Manager  
103,Raj Reddy,Sysadmin  
104,Anand Ram,Developer  
105,Jane Miller,Sales Manager
#+end_src

*n 명령을 사용할 때 -n 옵션을 사용하면 아무것도 출력하지 않는다:*  

#+begin_src
$ sed -n n employee.txt
#+end_src

앞서 설명한대로 일반적인 sed의 실행 흐름은 "읽기(/Read/), 실행(/Execute/ — 모든 sed 명령), 출력(/Print/), 반복(/Repeat/)" 이다. ~n~ 명령은 이런 실행 흐름을 변경한다. ~n~ 명령은 패턴 공간을 출력한 후, 패턴 공간을 지우고 입력 파일에서 다음 줄을 읽어 명령 흐름을 계속한다.

*다음과 같이 n 명령 앞뒤에 2개의 명령이 있다고 가정한다:* 

#+begin_src
sed-command-1  
sed-command-2  
n  
sed-command-3  
sed-command-4
#+end_src

이 경우, sed-command-1 과 sed-command-2 는 패턴 공간의 현재 줄에 적용된다. ~n~ 명령을 만나면 현재 줄을 패턴 공간에서 지우고 입력 파일에서 다음 줄을 읽고 sed-command-3 과 sed-command-4 를 새로 읽은 줄에 적용한다.

#+begin_quote
[!NOTE]
~n~ 명령 자체는 상대적으로 쓸모가 없다. 하지만, 다음에 설명할 홀드 공간과 멀티 라인 명령과 결합하면 강력해진다.
#+end_quote



* Sed Hold and Pattern

** 작업 공간 명령  
sed는 두 가지 유형의 내부 저장 공간이 있다: 

- 패턴 공간(/Pattern space/) :: 패턴 공간은 일반적인 sed 실행 흐름의 일부로 사용한다. 패턴 공간은 sed가 입력 파일에서 읽은 줄을 배치하고 수정하는 sed 내부의 버퍼이다.  

- 홀드 공간(/Hold space/) :: 임시 데이터를 저장할 수 있는 추가 버퍼이다. 패턴 공간과 홀드 공간 사이에 데이터를 이동하도록 허용하지만 일반적인 sed 명령은 홀드 공간에 실행할 수 없다.

이미 설명한대로 일반적인 sed 실행 흐름은 매 사이클이 끝날 때마다 패턴 공간은 삭제된다. 그러나, 홀드 공간의 내용은 다음 사이클까지 유지되며 사이클 사이에 삭제되지 않는다.

*홀드 공간 예제에 사용할 텍스트 파일을 생성한다:*

#+begin_src
$ sed -n 'w empnametitle.txt'
John Doe  
CEO  
Jason Smith  
IT Manager  
Raj Reddy  
Sysadmin  
Anand Ram  
Developer  
Jane Miller  
Sales Manager
^d
#+end_src

보다시피 이 파일은 직원 이름과 직책이 두 개의 연속된 줄에 포함한다.


** Swap Pattern Space with Hold Space (x command)
~x~ (/exchange/)명령은 패턴 공간과 홀드 공간을 서로 교환한다. 이 명령만으론 별 도움이 안되지만 다른 sed 명령과 결합하면 강력하다. 예를 들어, 패턴 공간에 "line 1" 이 있고 홀드 공간에 "line 2" 가 있다면 ~x~ 명령이 실행된 후에는 패턴 공간에는 "line 2", 홀드 공간에는 "line 1" 이 있다.

다음 예제는 관리자 이름을 출력한다. "Manager" 키워드를 찾고 이전 줄을 출력한다.

*empnametitle.txt 파일에서 관리자 이름 출력:*  

#+begin_src
$ sed -n -e 'x;n' -e '/Manager/{x;p}' empnametitle.txt
Jason Smith  
Jane Miller
#+end_src

위의 예제에서:

- ~x;n~ :: ~x~ 명령은 패턴 공간을 홀드 공간으로 교환하고 ~n~ 명령은 다음 줄을 패턴 공간으로 읽는다. 현재 줄을 홀드 공간에 저장하고 다음 줄을 패턴 공간으로 가져온다. 예제 파일은 직원 이름을 홀드 공간에 저장하고 직책을 패턴 공간으로 가져온다.

- ~/Manager/{x;p}~ :: 패턴 공간에 "Manager" 키워드가 있으면 패턴 공간과 홀드 공간을 교환한 후 패턴 공간을 출력한다. 즉, 직책에 "Manager" 가 포함되면 직원 이름을 출력한다.

*이 명령을 sed 스크립트에 저장하고 다음과 같이 실행한다:*  

#+begin_src
$ sed -n 'w x.sed'
#!/bin/sed -nf  
x;n  
/Manager/{x;p}
^d
$ chmod u+x empnametitle.txt  
$ ./x.sed empnametitle.txt
Jason Smith  
Jane Miller
#+end_src


** Copy Pattern Space to Hold Space (h command)
~h~ (/hold/)명령은 패턴 공간의 내용을 홀드 공간으로 복사한다. ~x~ 명령과 달리 ~h~ 명령은 패턴 공간의 내용을 변경하지 않는다. 홀드 공간의 이전 내용은 패턴 공간의 내용으로 덮어쓴다. 예를 들어, 패턴 공간에 "line 1", 홀드 공간에 "line 2" 가 있다면 ~h~ 명령이 실행된 후에는 패턴 공간은 그대로 "line 1" 이고, 홀드 공간도 "line 1" 이 된다.

*관리자 이름 출력:*  

#+begin_src
$ sed -n -e '/Manager/!h' -e '/Manager/{x;p}' empnametitle.txt
Jason Smith  
Jane Miller
#+end_src

위의 예제에서:

- ~/Manager/!h~ :: 패턴 공간의 내용이 "Manager" 를 포함하지 않으면(패턴 앞의 ~!~ 는 "패턴과 같지 않음" 을 의미) 패턴 공간의 내용을 홀드 공간으로 복사한다. (이 경우 직원 이름 또는 "Manager" 가 아닌 직책일 수 있다.) 이전 예제와 달리 다음 줄을 가져오기 위해 ~n~ 명령을 사용하지 않고 일반적인 실행 흐름으로 다음 줄을 가져온다.  

- ~/Manager/{x;p}~ :: 패턴 공간의 내용이 "Manager" 포함하면 패턴 공간과 홀드 공간을 교환하고 출력한다. ~x~ 명령 예제에 사용한 출력과 동일하다.

*이 명령을 sed 스크립트에 저장하고 다음과 같이 실행한다:*  

#+begin_src
$ sed -n 'w h.sed'
#!/bin/sed -nf  
/Manager/!h  
/Manager/{x;p}
^d
$ chmod u+x empnametitle.txt  
$ ./h.sed empnametitle.txt
Jason Smith  
Jane Miller
#+end_src


** Append Pattern Space to Hold Space (H command)
~H~ (/Hold/)명령은 패턴 공간을 홀드 공간에 새로운 줄로 추가한다. 홀드 공간의 기존 내용을 덮어쓰지 않고 패턴 공간의 내용이 홀드 공간의 끝에 새로운 줄로 추가된다. 예를 들어, 패턴 공간에 "line 1", 홀드 공간에 "line 2" 가 있다면 ~H~ 명령을 실행한 후에 패턴 공간은 그대로 "line 1" 이고, 홀드 공간은 "line 2\nline 1" 이 된다.

*관리자 이름과 직책을 (각각 별도의 줄로) 출력:*  

#+begin_src
$ sed -n -e '/Manager/!h' -e '/Manager/{H;x;p}' empnametitle.txt
Jason Smith  
IT Manager  
Jane Miller  
Sales Manager
#+end_src

위의 예제에서:  

- ~/Manager/!h~ :: 패턴 공간에 "Manager" 가 포함되지 않으면 패턴 공간의 내용을 홀드 공간에 복사한다. (직원 이름 또는 "Manager" 가 아닌 직책일 수 있음)  

- ~/Manager/{H;x;p}~ :: 패턴 공간에 "Manager" 가 포함되면 ~H~ 명령은 패턴 공간(직책)을 홀드 공간에 새로운 줄로 추가한다. 이 시점에 홀드 공간은 "직원 이름\n직책" 이 된다. ~x~ 명령은 홀드 공간과 패턴 공간을 교환하고 ~p~ 명령은 패턴 공간을 출력한다.

*이 명령을 sed 스크립트에 저장하고 실행한다:*  

#+begin_src
$ sed -n 'w H-upper.sed'
#!/bin/sed -nf  
/Manager/!h  
/Manager/{H;x;p}
^d
$ chmod u+x H-upper.sed  
$ ./H-upper.sed empnametitle.txt
Jason Smith  
IT Manager  
Jane Miller  
Sales Manager
#+end_src

*직원 이름과 직책을 콜론(:)으로 구분해서 같은 줄에 출력하려면 다음과 같이 수정한다:*  

#+begin_src
$ sed -n -e '/Manager/!h' -e '/Manager/{H;x;s/\n/:/;p}' empnametitle.txt
Jason Smith:IT Manager  
Jane Miller:Sales Manager
#+end_src

*이 명령을 sed 스크립트에 저장하고 실행한다:* 

#+begin_src
$ sed -n 'w H1-upper.sed'
#!/bin/sed -nf  
/Manager/!h  
/Manager/{H;x;s/\n/:/;p}
^d
$ chmod u+x H1-upper.sed  
$ ./H1-upper.sed empnametitle.txt
Jason Smith:IT Manager  
Jane Miller:Sales Manager
#+end_src


** Copy Hold Space to Pattern Space (g command)
~g~ (/get/)명령은 홀드 공간의 내용을 패턴 공간으로 복사한다. 이렇게 생각하면 편하다! 

~h~ 명령은 홀드 공간에 보관하고 ~g~ 명령은 홀드 공간에서 가져온다!! 예를 들어, 패턴 공간에 "line 1", 홀드 공간에 "line 2" 가 있다면 ~g~ 명령을 실행한 후에 패턴 공간은 "line 2" 로 변경되고, 홀드 공간은 그대로 "line 2" 를 유지한다.

*관리자 이름 출력:*  

#+begin_src
$ sed -n -e '/Manager/!h' -e '/Manager/{g;p}' empnametitle.txt
Jason Smith  
Jane Miller
#+end_src

위의 예제에서:  

- ~/Manager/!h~ :: 이전 예제처럼 패턴 공간에 "Manager" 가 포함되지 않으면 패턴 공간의 내용을 홀드 공간에 복사한다.  

- ~/Manager/{g;p}~ :: ~g~ 명령은 홀드 공간의 줄을 가져와서 패턴 공간에 넣고 ~p~ 명령은 이를 출력한다.

*이 명령을 sed 스크립트에 저장하고 실행한다:*  

#+begin_src
$ sed -n 'w g.sed'
#!/bin/sed -nf  
/Manager/!h  
/Manager/{g;p}
^d
$ chmod u+x g.sed  
$ ./g.sed empnametitle.txt
Jason Smith  
Jane Miller
#+end_src


** Append Hold Space to Pattern Space (G command)
~G~ (/Get/)명령은 홀드 공간의 내용을 패턴 공간에 새로운 줄로 추가한다. 패턴 공간의 기존 내용은 덮어쓰지 않고 홀드 공간의 내용이 패턴 공간 끝에 새로운 줄로 추가된다.

~G~ 와 ~g~ 명령의 관계는 ~H~ 와 ~h~ 명령과 같다. 즉, 소문자 명령은 내용을 교체하고 대문자 명령은 내용을 추가한다. 예를 들어, 패턴 공간에 "line 1", 홀드 공간에 "line 2" 가 있다면 ~G~ 명령을 실행한 후에 패턴 공간은 "line 1\nline 2" 가 되고, 홀드 공간은 그대로 "line 2" 를 유지한다.

*관리자 이름과 직책을 콜론으로 구분해서 출력:*  

#+begin_src
$ sed -n -e '/Manager/!h' -e '/Manager/{x;G;s/\n/:/;p}' empnametitle.txt
Jason Smith:IT Manager  
Jane Miller:Sales Manager
#+end_src

위의 예제에서:

- ~/Manager/!h~ :: 이전 예제처럼 패턴 공간에 "Manager" 가 포함되지 않으면 패턴 공간의 내용을 홀드 공간에 복사한다.  

- ~/Manager/{x;G;s/\n/:/;p}~ :: 패턴 공간에 "Manager" 가 포함되면 다음을 실행한다:  

  - ~x~ :: 패턴 공간과 홀드 공간을 교환한다. 즉, 홀드 공간에 저장된 직원 이름을 패턴 공간으로 가져오고 직책은 홀드 공간으로 이동한다.  
  - ~G~ :: 홀드 공간의 내용을 패턴 공간에 새로운 줄로 추가한다. 이 시점에 패턴 공간은 "직원 이름\n직책" 이 된다.  
  - ~s/\n/:/~ :: 직원 이름과 직책 사이의 줄 바꿈을 콜론으로 바꾼다.  
  - ~p~ :: 결과를 출력한다.

#+begin_quote
[!NOTE]
만약 ~x~ 명령을 생략하고 ~/Manager/{G;s/\n/:/;p}~ 만 사용하면 출력은 "이름:직책" 이 아니라 "직책:이름" 이 된다.
#+end_quote

*이 명령을 sed 스크립트에 저장하고 실행한다:*  

#+begin_src
$ sed -n 'w G-upper.sed'
#!/bin/sed -nf  
/Manager/!h  
/Manager/{x;G;s/\n/:/;p}
^d
$ chmod u+x G-upper.sed  
$ ./G-upper.sed empnametitle.txt
Jason Smith:IT Manager  
Jane Miller:Sales Manager
#+end_src



* Sed Multi-Line Command

** 명령과 루프  
sed는 기본적으로 한 줄씩 처리한다. 단, ~H~, ~G~ 또는 ~N~ 명령으로 줄바꿈으로 구분된 여러 줄을 생성할 경우는 예외이다. 

이 장은 다중 줄(멀티 라인) 버퍼에 적용되는 sed 명령을 설명한다.

#+begin_quote
[!NOTE]
여러 줄이 있을 경우 ~^~ 는 버퍼 전체에서 첫 번째 문자만 일치하며 ~$~ 는 버퍼 전체에서 마지막 문자 즉, 마지막 줄의 줄바꿈 문자만 일치한다.
#+end_quote


** Append Next Line to Pattern Space (N command)
~N~ (/Next/)명령은 현재 줄을 지운 후, 대체하지 않고 입력 파일에서 다음 줄을 읽어 패턴 공간에 추가한다. 앞서 살펴본 소문자 ~n~ 명령은 패턴 공간을 출력하고 패턴 공간을 지운 뒤, 다음 줄을 읽어 패턴 공간에 넣고 명령을 계속 실행한다.

반면, 대문자 ~N~ 명령은 패턴 공간을 출력하지 않고 지우지 않는다. 대신 패턴 공간 끝에 줄바꿈(~\n~)을 추가하고 입력 파일에서 다음 줄을 읽어 패턴 공간에 덧붙인 후 나머지 sed 명령을 실행한다.

*직원 이름과 직책을 콜론으로 구분해서 출력:*  

#+begin_src
$ sed -e '{N;s/\n/:/}' empnametitle.txt
John Doe:CEO  
Jason Smith:IT Manager  
Raj Reddy:Sysadmin  
Anand Ram:Developer  
Jane Miller:Sales Manager
#+end_src

*설명:*  

- ~N~ :: 패턴 공간(직원 이름)에 줄바꿈을 추가하고 다음 줄(직책)을 읽어 패턴 공간에 덧붙인다. 결과적으로 패턴 공간은 "직원 이름\n직책" 형태가 된다.  

- ~s/\n/:/~ :: 줄 바꿈을 콜론으로 바꾼다.

*줄 번호와 내용을 같은 줄에 출력:*  

#+begin_src
$ sed -e '=' employee.txt | sed -e '{N;s/\n/ /}'
1 101,John Doe,CEO  
2 102,Jason Smith,IT Manager  
3 103,Raj Reddy,Sysadmin  
4 104,Anand Ram,Developer  
5 105,Jane Miller,Sales Manager
#+end_src

*설명:*  

- ~sed -e '='~ :: 줄 번호를 출력한다. 줄 번호 다음 줄에 원래 줄을 출력한다.  

- ~N~ :: 줄 번호 다음에 원래 줄을 덧붙여 "줄번호\n내용" 형태의 패턴 공간을 만든다.  

- ~s/\n/ /~ :: 줄바꿈을 공백으로 바꿔 "줄 번호 내용" 형태로 출력한다.


** Print 1st Line in MultiLine (P command)
지금까지 세 가지 대문자 명령을 살펴봤는데 모두 버퍼 내용을 대체하지 않고 추가하는 방식으로 작동했다. 대문자 ~P~ 와 ~D~ 명령은 소문자 명령과 유사하지만 멀티라인 버퍼와 관련된 특별한 동작을 수행한다는 것도 잘 알 것이다.

앞서 설명한대로 소문자 ~p~ 명령은 패턴 공간을 출력한다. 대문자 ~P~ 명령도 패턴 공간을 출력하지만 줄바꿈(~\n~)을 만날 때까지 출력한다. 

*다음 예제는 empnametitle.txt 파일의 모든 관리자 이름을 출력한다.*

#+begin_src
$ sed -n -e 'N' -e '/Manager/P' empnametitle.txt
Jason Smith
Jane Miller
#+end_src


** Delete 1st Line in MultiLine (D command)
앞서 설명한대로 소문자 ~d~ 명령은 패턴 공간을 삭제하고 입력 파일에서 다음 줄을 읽어 패턴 공간에 넣은 후 나머지 sed 명령을 중단하고 루프를 다시 시작한다. 대문자 ~D~ 명령은 패턴 공간을 삭제한 후 다음 줄을 읽지 않으며 패턴 버퍼를 완전히 지우지 않는다. (단, 한 줄만 있는 경우는 제외) 대신 다음과 같이 작업을 수행한다: 

- 줄바꿈(~\n~)을 만날 때까지 패턴 공간의 일부를 삭제한다.  

- 나머지 sed 명령을 중단하고 패턴 버퍼에 남아있는 내용으로 명령을 처음부터 다시 시작한다.

다음은 각 직책에 ~@~ 문자로 둘러싸인 주석이 포함된 파일이다. 이 주석은 경우에 따라 여러 줄에 걸쳐질 수 있다. 예를 들어, ~@Information Technology officer@~ 는 두 줄에 걸쳐 있다.

*다음과 같이 샘플 파일을 생성한다.*

#+begin_src
$ sed -n 'w empnametitle-with-comment.txt'
John Doe
CEO @Chief Executive Officer@
Jason Smith
IT Manager @Information Technology
Officer@
Raj Reddy
Sysadmin @System Administrator@
Anand Ram
Developer @Senior
Programmer@
Jane Miller
Sales Manager @Sales
Manager@
^d
#+end_src

*이 파일에서 주석만 제거하는 것이 목표이다. 다음과 같이 수행한다.*

#+begin_src
$ sed -e '/@/{N;/@.*@/{s/@.*@//;P;D}}' empnametitle-with-comment.txt
#+end_src

*출력 결과:*

#+begin_src
John Doe
CEO
Jason Smith
IT Manager
Raj Reddy
Sysadmin
Anand Ram
Developer
Jane Miller
Sales Manager
#+end_src

위의 명령은 한 줄로 실행한다:

#+begin_src
sed -e '/@/{N;/@.*@/{s/@.*@//;P;D}}' empnametitle-with-comment.txt
#+end_src

*또한, sed 스크립트 파일에 저장해서 다음과 같이 실행한다:*

#+begin_src
$ sed -n 'w D-upper.sed'
#!/bin/sed -f
/@/ {
N
/@.*@/ {s/@.*@//;P;D }
}
^d
$ chmod u+x D-upper.sed
$ ./D-upper.sed empnametitle-with-comment.txt
#+end_src

위의 예제에서:  

- ~/@/ {~ :: 외부 루프이다. sed는 ~@~ 기호가 포함된 줄을 찾는다. 찾으면 나머지 로직을 실행하고 그렇지 않으면 다음 줄을 읽는다. 예를 들어, 4번 줄 ~@Information Technology~ 는 여러 줄에 걸쳐지며 5번 줄까지 이어진다. 4번 줄에 ~@~ 기호가 있으므로 나머지 명령들이 실행된다.  

- ~N~ :: 입력 파일에서 다음 줄을 가져와서 패턴 공간에 추가한다. 예를 들어, 5번 줄 ~Officer@~ 를 읽어 패턴 공간에 추가한다. 따라서, 패턴 공간은 ~@Information Technology\nOfficer@~ 를 포함한다.  

- ~/@.*@/~ :: 패턴 공간에 ~"@.*@"~ 패턴이 있는지 검색한다. 즉, ~@~ 와 ~@~ 사이의 모든 내용을 찾는다. 패턴 공간에서 이 표현식은 참(/true/)이므로 다음 단계로 진행한다.

- ~s/@.*@//;P;D~ :: ~@Information Technology\nOfficer@~ 전체 텍스트를 아무것도 없는 것으로 대체한다. (즉, 삭제한다.) ~P~ 명령은 줄의 첫 번째 부분을 출력하고 ~D~ 명령은 패턴 공간의 첫 번째 내용을 삭제한다. 그리고 실행 로직은 다시 처음부터 계속된다.


** Loop and Branch (b command and :label)
sed 명령의 실행 흐름은 레이블(/label/)과 분기~b~ (/branch/)명령으로 변경할 수 있다. 

- ~:label~ :: 레이블을 정의한다.  

- ~b label~ :: 실행 흐름을 해당 레이블로 분기시킨다. 

sed는 레이블이 포함된 줄로 이동한 후 명령을 계속 실행한다.  

#+begin_quote
[!NOTE]
~b~ 명령을 레이블 없이 단독 실행할 수 있다. 이 경우 sed는 스크립트 파일 끝으로 이동한다.
#+end_quote

다음 예제는 empnametitle.txt 파일에서 직원 이름과 직책을 하나의 줄로 결합하고 직책에 "Manager" 키워드가 포함된 경우 직원 이름 앞에 * 문자를 추가한다.

#+begin_src
$ sed -n 'w label.sed'
#!/bin/sed -nf
h;n;H;x
s/\n/:/
/Manager/!b end
s/^/*/
:end
p
^d
#+end_src

위의 예제에서 ~h;n;H;x~ 와 ~s/\n/:/~ 가 무엇을 처리하는지 앞서 살펴본 예제로 이미 알고 있다. 

다음은 분기와 관련된 라인에 대한 설명이다: 

- ~/Manager/!b end~ :: 줄에 "Manager" 키워드가 없으면 ~end~ 레이블로 분기한다. 레이블 이름은 자유롭게 지정할 수 있다. (8글자까지) ~s/^/*/~ (앞에 ~*~ 추가)를 "Manager" 를 포함한 줄에 실행한다.  

- ~:end~ :: 레이블을 정의한다.

*다음과 같이 스크립트를 실행한다:*

#+begin_src
$ chmod u+x label.sed
$ ./label.sed empnametitle.txt
#+end_src

*출력 결과:*

#+begin_src
John Doe:CEO
*Jason Smith:IT Manager
Raj Reddy:Sysadmin
Anand Ram:Developer
*Jane Miller:Sales Manager
#+end_src


** Loop Using t command
~t label~ (/test/)명령은 이전 대체(/substitute/) 명령이 성공한 경우만 실행 흐름을 해당 레이블로 분기시킨다. 즉, 이전 대체 명령이 성공하면 지정한 레이블로 이동한 후 나머지 명령을 계속 실행하고 그렇지 않으면 일반적인 실행 흐름을 따른다.

다음 예제는 empnametitle.txt 파일에서 직원 이름과 직책을 : 문자로 구분해서 한 줄로 결합하고 직책에 "Manager" 키워드가 포함된 경우 직원 이름 앞에 ** 를 추가한다.

#+begin_quote
[!NOTE]
이전 예제에서 대체 명령을 ~s/^/**/~ 로 바꾸는 것으로 동일한 결과를 얻을 수 있지만 이 예제는 ~t~ 명령의 동작 방식을 설명하기 위한 것이다.
#+end_quote

#+begin_src
$ sed -n 'w label-t.sed'
#!/bin/sed -nf
h;n;H;x
s/\n/:/
:repeat
/Manager/s/^/*/
/\*\*\*/!t repeat
p
^d
#+end_src

*다음과 같이 스크립트를 실행한다:*

#+begin_src
$ chmod u+x label-t.sed
$ ./label-t.sed empnametitle.txt
#+end_src

*출력 결과:*

#+begin_src
John Doe:CEO
**Jason Smith:IT Manager
Raj Reddy:Sysadmin
Anand Ram:Developer
**Jane Miller:Sales Manager
#+end_src

위의 예제에서:

- 다음 코드가 루프를 수행한다:

#+begin_src 
:repeat
/Manager/s/^/*/
/\*\*\*/!t repeat
#+end_src
  
- ~/Manager/s/^/*/~ :: 직책이 "Manager" 일 경우 줄 앞에 ~*~ 문자를 추가한다.

- ~/\*\*\*/!t repeat~ :: 줄에 ~**~ 가 없고 이전 대체 명령이 성공하면 ~repeat~ 레이블로 분기한다.

- ~:repeat~ :: 레이블을 정의한다.

감사합니다!!
