* Chapter 6. The Practicals of Emacs

#+BEGIN_QUOTE
“[…] Emacs outshines all other editing software in approximately the same way
that the noonday sun does the stars. It is not just bigger and brighter;
it simply makes everything else vanish.”

– Neal Stephenson, In the Beginning… was the CommandLine.
#+END_QUOTE

이전 챕터들은 전적으로 Emacs의 이론적인 측면에 대해서만 다루었습니다. 하지만, 두뇌를 활발하게 움직여 실용적이거나 참신한 활용법을 찾아내는 것은 또 다른 문제입니다. 무엇보다 이론만으로는 부족합니다. 이 마지막 챕터는 제가 ‘워크플로’ 라고 부르는 것, 즉 특정 영역이나 문제를 상당히 깊이 있게 다루는 실습 가이드를 보여드리겠습니다.

지난 두 장과 달리, 이 장에서 소개하는 명령어와 기능에 대해서는 자세히 다루지 않을 것입니다. 그 부분은 여러분이 직접 시간을 내서 알아가시기 바랍니다. 만약 새로운 기능을 찾는 방법을 아직까지 잘 모르겠다면, 계속 읽어보시기 바랍니다—이 장의 첫 부분은 ‘Emacs 탐구’ 입니다.


** Exploring Emacs
Emacs를 진정으로 마스터하려면, 무엇을 어떻게 찾아야 하는지부터 배워야 합니다. 이것이 바로 Emacs의 핵심입니다. 매뉴얼, 서적, 블로그 글들은 사용자의 편집 환경, 즉 Emacs에 대해 일정한 가정을 전제로 하고 있습니다. 변수를 변경하거나 키 바인딩을 재설정하거나, 자신의 필요에 맞게 Emacs를 수정하면, 다른 사람이라면 거의, 아니면 아예 아무도 가지고 있지 않은 고유한 변경 사항의 조합이 만들어집니다. 그러므로 문제를 진단하거나, 마음에 들지 않는 부분을 수정하고 변경하려면, 우선 그 요소들을 어떻게 찾아내는지 알아야 합니다.

이제 Emacs의 버전 관리 인터페이스인 VC 시스템을 살펴보겠습니다. VC 시스템은 Emacs에 내장된 강력하지만 제대로 활용되지 않는 기능으로, 버전 이력, 원인 분석, 커밋, 푸시 및 풀 같은 작업에 대한 일반적인 인터페이스를 제공하며, 이를 통해 사용자가 선택한 버전 관리 시스템과 연동됩니다. VC 는 두 개 이상의 버전 관리 시스템을 정기적으로 사용하는 경우 유용합니다.

만약 이전에 VC 에 대해 전혀 알지 못했고, 지금 이 글을 읽는 것이 VC 에 대한 첫 접점이라면, 어떻게 배워야 할까요?


*** Reading the Manual
당연히 Emacs 매뉴얼은 잘 쓰여져 있고 내용도 방대합니다. 먼저 Emacs의 버전 관리(Version Control) 관련 매뉴얼을 열어보겠습니다.

1. ~C-h i~ 를 입력해서 ~M-x info~ 매뉴얼을 엽니다.
2. Emacs 하이퍼링크로 이동해서 엽니다.
3. ~C-s~ 를 사용해서 ~version~ 또는 ~version control~ 을 검색합니다.

보시다시피, ~C-s~ 를 충분히 많이 누르면 결국 그렇게 해서 버전 관리 매뉴얼을 찾게 될 것입니다.

따라서, 매뉴얼을 읽는 것은 효과적이지만, 모든 기능이 매뉴얼에 포함된 것은 아닙니다. 게다가 챕터들이 손이 닿기 어려운 하위-하위-하위 챕터에 묻혀 있을 수도 있습니다. 또한 타사 패키지는 거의 항상 info 매뉴얼이 포함되어 있지 않습니다.

*Apropos for info manuals* : 검색 패턴을 지정해서 ~M-x info-apropos~ 명령을 사용하면, Emacs가 알려진 모든 info 매뉴얼 페이지를 샅샅이 뒤져 해당 패턴과 일치하는 내용을 찾아줍니다. 어떤 내용이 어디에 있는지 잘 모르겠다면, 이 명령은 아주 유용한 도구입니다.


*** Using Apropos
‘Apropos’ 글에서 저는 apropos 를 사용해서 Emacs의 문서 시스템을 조회하는 다양한 방법을 모두 소개했습니다. 그 중 하나의 apropos 명령은 doc string(Emacs의 대부분의 변수와 함수에 동반되는 문서 문자열)을 검색해서 일치하는 함수나 변수를 나열해 줍니다. Emacs의 문서 문자열을 검색하는 것은 정보를 찾는 데 있어 가장 산발적인 접근 방식입니다. 말 그대로 일반 텍스트 문서를 검색하는 것이기 때문입니다. 이를 수행하려면 문서를 검색하는 apropos 명령어인 ~C-h d~ 를 사용해야 합니다.

#+BEGIN_QUOTE
*Namespacing in Emacs Lisp* :
Emacs Lisp은 다른 Lisp 언어들과 달리 네임스페이스 구분이 없습니다.
Emacs는 모듈이나 네임스페이스를 이용해서 관심사를 분리하지 않습니다.
실제로는 그다지 큰 문제는 아니지만(좀 더 중요한 문제들이 많기 때문이죠),
이는 비공식적으로 Emacs 패키지들이 심볼(함수, 변수 등)에 접두사를 붙여
충돌을 방지한다는 것을 의미합니다.

예를 들면, Python 메이저 모드는 `python-`,
apropos 관련 명령어에는 `apropos-` 등이 사용됩니다.
#+END_QUOTE

그럼에도 불구하고, ~C-h d~ 를 사용해서 버전 관리를 검색하면, 첫 번째 결과는 다음과 같습니다:

#+BEGIN_SRC
vc-mode

Function: Version Control minor mode. This
minor mode is automatically activated whenever
you visit a file under control of one of the
revision control systems in
`vc-handled-backends'.

VC commands are globally reachable under the
prefix `C-x v':
#+END_SRC

이제 약간의 단서가 생겼습니다. VC 모드는 ~vc-mode~ 입니다. 하지만, 우리가 원하는 것은 이 모드가 사용하는 접두사이며, 그것은 ~vc-~ 입니다.

VC의 접두사가 ~vc-~ 임을 알았으므로, ~C-h a~ 에 바인딩된 ~M-x apropos-command~ 를 사용해서 모든 VC 명령어를 찾을 수 있습니다:

~M-x apropos-command~

그런 다음 프롬프트에 다음을 입력합니다:

~Search for a command (word list or regexp): ^vc-~

Emacs는 Apropos 검색 결과를 반환합니다:

#+BEGIN_SRC
vc-annotate C-x v g
  Display the edit history of the current
  FILE using colors.
vc-check-headers M-x ... RET
  Check if the current file has any headers in it.
vc-clear-context M-x ... RET
  Clear all cached file properties.
[...]
#+END_SRC

명령어 목록과 간단한 설명, 그리고 해당 키 바인딩(있는 경우)을 확인할 수 있습니다.

대략 훑어보면 몇 가지 흥미로운 명령어들이 나타납니다.

| 키 및 명령어                   | 설명                      |
| ~C-x v vc-~                    | 명령어 접두사 키          |
| ~M-x vc-dir , C-x v d~         | VC 상태 표시              |
| ~M-x vc-diff , C-x v d~        | 버퍼와 마지막 개정판 비교 |
| ~M-x vc-annotate , C-x v g~    | 블레임 표시               |
| ~M-x vc-next-action , C-x v v~ | 다음 논리적 작업 실행     |
| ~M-x vc-print-log , C-x v l~   | 커밋 로그 출력            |

이것들을 살펴보면 분명한 경향을 알 수 있습니다. 많은 명령어가 접두사 키 ~C-x v~ 에 할당되어 있습니다. 다음 단계는 ~C-h~ 를 추가해서 접두사 키 자체에 어떤 명령어가 할당되어 있는지 확인하는 것입니다. 


*** C-h : Exploring Prefix keys
『키 찾기 및 기억하기』 에서, 부분(접두사) 키를 입력할 때 ~C-h~ 를 덧붙이면 해당 접두사 키에 바인딩된 모든 키를 나열한다는 점을 보여드렸습니다. ~C-x v~ 도 예외는 아닙니다. ~C-x v C-h~ 를 입력하면 이 접두사 키에 바인딩된 모든 키가 나열됩니다. ~C-x v C-h~ 를 입력하면 다음과 같은 결과가 나옵니다:

#+BEGIN_SRC
Global Bindings Starting With C-x v:

key binding
C-x v +    vc-update
C-x v =    vc-diff
C-x v D    vc-root-diff
C-x v G    vc-ignore
C-x v I    vc-log-incoming
C-x v L    vc-print-root-log
C-x v O    vc-log-outgoing
C-x v a    vc-update-change-log
C-x v b    vc-switch-backend
[...]
#+END_SRC

이 명령어의 가장 큰 장점은 입력하기 정말 쉽다는 점입니다. ~C-x v~ 가 현재 파일을 마지막 파일 버전과 비교한다는 사실을 잊어버리셨나요? 문제없습니다. ~C-x v C-h~ 를 입력하면 ~C-x v~ 에 할당된 명령어가 ~M-x vc-diff~ 임을 확인할 수 있습니다. 또 다른 분명한 이점은 평소에는 사용하려고 생각조차 하지 않았거나, 심지어 존재조차 몰랐던 명령어들을 접할 수 있게 해준다는 것입니다. 예를 들어, 새로운 태그(~C-x v s~)를 생성할 필요가 생겼는데, 그 명령의 이름이 무엇인지, 어떤 키에 바인딩되어 있는지, 심지어 Emacs에 그런 기능이 존재하는지조차 확실치 않다면, ~C-h~ 를 통해 그 답을 찾을 수 있을 것입니다.


*** C-h k : Describe what a key does
반대로, 키는 알지만 그 기능이 무엇인지 모르는 경우도 있습니다. ~C-h k~ 명령어는 키 바인딩을 입력받아 현재 활성화된 버퍼에서 해당 키에 어떤 명령이 할당되어 있는지 보여줍니다. 예를 들어, ~C-h k~ 를 입력한 뒤 ~C-x v v~ 를 입력하면 명령의 이름뿐만 아니라 해당 명령에 대한 설명문도 확인할 수 있습니다. 보통 이 설명문은 해당 명령이 무엇을 하는지 명확하게 설명해 줍니다:

#+BEGIN_SRC
C-x v v runs the command vc-next-action (found
in global-map), which is an interactive
autoloaded compiled Lisp function in `vc.el'.

It is bound to C-x v v, <menu-bar> <tools> <vc>
<vc-next-action>.

(vc-next-action VERBOSE)

Do the next logical version control operation on
the current fileset. This requires that all
files in the current VC fileset be in the same
state. If not, signal an error.
...
#+END_SRC

위에는 키 바인딩과 해당 키가 실행하는 명령이 표시되어 있습니다. 또한 명령이 발견된 위치(이 경우 전역 키이므로 전역 맵)와 명령이 포함된 라이브러리 파일도 함께 표시됩니다. 다음으로, 해당 명령이 차지하는 모든 키(여러 개의 바인딩이 있을 수 있음)가 나열되며, Lisp에서 직접 명령을 호출할 경우 함수 인수가 그 뒤에 이어집니다. 그리고 마지막으로, 명령을 설명하는 문서 문자열이 표시됩니다.

이 모든 정보는 ~C-h k~ 를 호출할 때 동적으로 생성됩니다.

~C-h k~ 의 약간의 단점은 이 명령이 일반 사용자가 아닌 엘리스프(Elisp) 개발자를 대상으로 한다는 점입니다. 문서 문자열은 기술적인 관점에서 명령이 어떻게 작동하는지 설명하며, 이는 대개 각 인수가 어떻게 작동하는지, 그리고 일반 사용자는 별 관련없는 기타 기술적인 세부 사항을 설명하는 것을 의미합니다. 하지만, 기술에 익숙한 사람이라면, 비록 리스프 개발자가 아니더라도, 이는 대개 문제가 되지 않습니다.

*명령 설명하기* : ~vc-dir~ 같은 명령 이름이 있다면, ~C-h f~ 를 사용하면 Emacs가 해당 명령의 기능을 설명해 줍니다.


*** C-h m : Finding mode commands 
~C-x v d~ 명령을 실행하면 현재 버퍼의 리포지토리 버전 상태를 보여주는 새로운 버퍼가 나타납니다. 여기에는 추적되지 않은 파일이나 수정된 파일 등의 정보가 표시됩니다. 하지만, 이 버퍼를 어떻게 활용할까요? VC 의 상태 버퍼 사용법을 어떻게 알 수 있을까요?

정답은 ~C-h m~ 입니다. 이 도움말 명령어는 활성화된 메이저 모드 및 마이너 모드에 존재하는 문서 문자열을 설명해 줍니다. 즉, 이 명령어를 사용해서 각 메이저 및 마이너 모드가 무엇을 하는지(그리고 해당 모드에서 사용할 수 있는 키가 있다면 어떤 키인지) 알아볼 수 있습니다.

따라서, VC 상태 버퍼 내에서 ~C-h m~ 을 호출하면 수많은 키와 관련 문서를 확인할 수 있습니다:

#+BEGIN_SRC
key    binding
C-c    Prefix Command
TAB    vc-dir-next-directory
C-k    vc-dir-kill-line
RET    vc-dir-find-file
...
#+END_SRC

그 후에는 관심 있는 각 하이퍼링크를 (~RET~ 키나 마우스로) 클릭하면 됩니다.


*** M-S-x : Execute Extended Command for Buffer
또 다른 방법은 Emacs 28에 도입된 ~M-S-x~ 를 사용하는 것입니다. 하지만, 이 방법이 모든 상황에서 훌륭한 결과를 보장하는 것은 아닙니다. 이 기능은 현재 버퍼의 활성 모드에 두 키가 모두 할당되어 있어야 하며, 해당 모드 개발자가 중요한 명령을 표시하기 위해 ~M-S-x~ 에 대한 힌트를 코드에 추가해야 하기 때문입니다.

VC 의 경우, ~C-x v d~ 같은 전용 모드에서 가장 잘 작동하며, ~C-h m~ 을 보완하는 역할을 처리할 수 있습니다.



** Project Management
역사적으로 Emacs는 파일을 항상 개별적으로만 다루었고, 관련된 파일들의 집합으로 간주한 적은 없었습니다. 2002년부터 Emacs에 포함되어 있었음에도 불구하고 유지보수자들조차 잊어버릴 정도로 제대로 알려지지 않았던 ‘파일셋(filesets)’ 기능이 있었음에도 불구하고, Emacs는 그 역할 대부분을 디렉터리 로컬 변수와 Makefile 및 관련 도구 같은 외부 도구들에 맡겨두었습니다. 이로 인해 Emacs 개발자들과 커뮤니티는 검색 및 교체, 컴파일 같은 다중 파일 작업에 대한 일관된 접근 방식을 구축하기 어려웠습니다. 이는 Emacs 23에서 EDE 가 도입되면서 바뀌었는데, EDE 는 Emacs에 IDE와 유사한 기능을 제공하는 매우 복잡한 도구 모음인 CEDET 의 하위 집합입니다.

#+BEGIN_QUOTE
*What is CEDET?* :
CEDET 는 의미 분석 및 코드 완성 기능을 갖춘
언어 구문 분석, 프로젝트 관리, 코드 생성, 도식화 등의
기능을 제공하는 도구 모음입니다.

C 및 C++ 환경에서 잘 작동하며 해당 커뮤니티에서 많은 사랑을 받았지만,
다른 분야는 크게 보편화되지는 못했습니다.
축약된 버전이 Emacs 23에 포함되었습니다.
#+END_QUOTE

CEDET 와 마찬가지로 EDE 도 제대로 자리를 잡지 못했고, 그동안 다중 언어 프로젝트가 보편화되면서 Projectile 같은 수많은 타사 라이브러리가 번성했습니다. 또한 이들은 파일을 선택적으로 추가하거나 제거하는 정적인 프로젝트 파일 대신 소스 제어 저장소를 기반으로 함으로써 프로젝트 관리의 개념을 변화시켰습니다.

그 후, Emacs는 project.el 을 도입했으며, 그 이후로 꾸준히 개발이 진행되어 왔습니다. 이 “새로운” 프로젝트 관리자는 다양한 기능을 갖추고 있으며, 제 생각에는 대부분의 사용자에게 훌륭한 기본적인 경험을 제공하는 무언가를 만들기 위해 타사 도구들의 집합적인 작업에서 영감을 얻었습니다.

주요 기능 중 일부는 다음과 같습니다:

*버전 관리 시스템에 등록된 파일을 기반으로 파일 추론* : Emacs는 현재 사용 중인 버전 관리 시스템에 파일이 등록되어 있다면, 해당 파일이 프로젝트 사용자와 관련이 있을 가능성이 높다는 가정 하에 프로젝트와 관련된 파일을 자동으로 추론합니다.

*버전 관리 시스템의 홈 디렉터리를 기반으로 루트 디렉터리 추론* : 파일 검색, 린팅 도구, 컴파일 명령어 등이 종종 루트 디렉터리를 기준으로 실행되기 때문에 이는 중요합니다.

*프로젝트 파일 열거에 대한 내장 지원* : 프로젝트 내의 여러 파일이나 프로젝트 파일의 일부 집합을 대상으로 검색 및 치환을 수행하기 위함입니다.

*프로젝트와 연동되는 명령어 선택* : ~M-x shell~ 또는 ~M-x dired~ 버퍼 열기; 파일 찾기; 프로젝트 관련 버퍼 종료; 또는 이름으로 다른 프로젝트로 전환하는 것 등이 있습니다.

여기서 나열한 세부 사항들은 저수준으로 보일 수 있지만, 중요합니다: 이는 Emacs에서 오랫동안 간절히 기다려온 기능인 것이며, 탄탄한 기반을 마련하는 것—개발팀이 이미 해낸 일—은 이 기능이 출시된 지금, 좀 더 넓은 커뮤니티의 채택이 필수적이므로 매우 중요합니다.

사용할 도구에 대해 확고한 선호도가 없다면, 이것을 사용해야 합니다. 이를 위해 필요한 것은 Git 이나 Mercurial 저장소 뿐입니다.

~C-x p~ (Emacs 28에 도입됨)에 바인딩된 프로젝트 전용 접두사 키맵이 있습니다:

| 프로젝트 키 | 설명                            |
| ~C-x p p~   | 다른 알려진 프로젝트로 전환     |
| ~C-x p b~   | 버퍼로 전환                     |
| ~C-x p f~   | 프로젝트 내 파일 찾기           |
| ~C-x p k~   | 프로젝트 버퍼 삭제              |
| ~C-x p g~   | 정규 표현식 검색                |
| ~C-x p r~   | 정규 표현식 검색 및 바꾸기 쿼리 |
| ~C-x p c~   | 프로젝트 컴파일                 |
| ~C-x p v~   | VC 대화 상자 열기               |
| ~C-x p s~   | 셸 열기                         |
| ~C-x p d~   | Dired 버퍼 열기                 |

보다 일반적인 단축키와 달리, ~C-x p f~ 및 ~C-x p b~ 같은 키 바인딩은 동일한 방식으로 작동하지만, 당연히 프로젝트에서 인식하는 파일로 제한됩니다. 모든 명령어 역시 이와 마찬가지입니다. 이 명령어들은 백엔드에 정의된 프로젝트 범위 내에서만 작동하며, 기본적으로 이는 VC 루트 디렉터리와 해당 디렉터리가 인식하는 모든 파일을 의미합니다.


** Xref: Cross-References in Emacs
Xref 는 기호(예: 아래 점)를 해당 정의와 매칭한 후, 사용자가 이를 편집하거나 해당 위치로 이동할 수 있도록 표시해 주는 통합 플랫폼입니다. 이 플랫폼은 실행 중인 버퍼의 메이저 모드에 따라 달라질 수도 있는 구성 가능한 백엔드를 통해 이런 기능을 수행합니다. 이 도구는 타사 패키지와 연동되도록 설계되었으나, 아직까지 널리 채택되지는 않았으며, 자체적인 심볼 정의 목록을 생성하는 도구들과 호환됩니다.

알아두어야 할 가장 일반적인 명령어 네 가지는 다음과 같습니다:

| 키      | 설명                        |
| ~M-.~   | 포인트 지점에서 정의 찾기   |
| ~M-,~   | 팝 마커를 표시하고 돌아가기 |
| ~M-?~   | 패턴과 일치하는 참조 찾기   |
| ~C-M-.~ | 패턴과 일치하는 기호 찾기   |

xref 의 ‘정의 찾기’ 기능을 ~M-.~ 키로 호출할 때, 사용 중인 메이저 모드에 xref 가 아직까지 설정되지 않았다면 먼저 TAGS 테이블 파일을 찾으라는 메시지가 표시될 가능성이 높습니다. TAGS 파일은 오래된 ~M-.~ 같은 명령을 사용하면 현재 위치에서 이동하는데, 이때 나중에 다시 돌아올 수 있도록 마커를 남겨둡니다. 식별자와 그 위치를 생성한 다음, 성능 향상을 위해 파일 시스템의 거대한 정적 조회 테이블에 저장하는 방식입니다. TAGS 파일은 엄청나게 큰 프로젝트를 작업할 때 유용합니다. 하지만, 대부분의 사용자는 파일 시스템을 실시간으로 검색하거나 Language Server에 쿼리를 보내는 도구만으로도 충분합니다.

시작하기 위해, 저는 타사 패키지인 dumb-jump 를 사용해 보기를 권장합니다. 이름과는 달리, 이 패키지는 grep, ack, ag 또는 ripgrep 같은 파일 검색 도구의 실행 속도를 활용해서 현재 사용 중인 메이저 모드와 관련된 일치 항목을 찾아줍니다. 대부분의 경우 이 정도면 충분합니다. 특히 ripgrep 은 최신 하드웨어에서 믿기 힘들 정도로 빠르며 Emacs와 잘 어울립니다.

설정이 완료되면 ~M-.~ 을 눌러 식별자로 이동할 수 있으며, 다시 되돌아가려면 ~M-, .~ 을 눌러 스택에서 마커를 제거할 수 있습니다. 정의가 여러 개 있거나 Emacs가 어떤 것이 가장 적합한지 확신할 수 없는 경우, 일치하는 정의들이 나열된 버퍼가 표시됩니다. ~C-M-.~ 을 사용해서 정규 표현식과 일치시키는 것도 가능합니다. 

#+BEGIN_QUOTE
*Popping the Stack* :
Emacs에서 흔히 쓰이는 용어 중 하나는 ‘스택에서 무언가를 팝(pop)한다’ 는 표현으로,
이는 컴퓨터 과학에서 리스트에 가장 최근에 추가된 항목을 제거한다는 개념을 가리킵니다.
이 용어는 Emacs 사용자 명령어 여기저기서 볼 수 있습니다.
#+END_QUOTE

~M-?~ 키 바인딩은 다른 백엔드가 없는 경우 grep 같은 일반적인 파일 검색 도구를 사용해서 프로젝트 디렉터리를 검색하도록 설정될 수 있습니다. 패키지 관리자를 확인해 보시기 바랍니다. 패키지 목록에서 ~M-s~ 또는 ripgrep 을 입력해서 해당 도구가 언급된 패키지를 찾아보시기 바랍니다. 보통 이 방법이 시작점으로 적합합니다.

검색 결과는 xref 정의 버퍼에 표시됩니다.

| Xref 버퍼 키 | 설명                            |
| ~RET~        | 정의로 이동                     |
| ~TAB~        | 정의로 이동 및 상호 참조 숨기기 |
| ~C-o~        | 정의 표시                       |
| ~.~ 및 ~,~   | 위/아래로 이동                  |
| ~r~          | 정규식 검색 및 바꾸기           |

~.~ 와 ~,~ 키를 사용해서 일치 항목 목록을 빠르게 훑어보면서 필요한 정의를 찾아보시기 바랍니다. 목록을 이동하면 Emacs가 해당 일치 항목으로 곧바로 이동합니다. 원하는 항목을 찾았다면 TAB 키를 눌러 커서 위치의 정의로 이동하고 xref 버퍼를 닫을 수 있습니다.

~r~ 을 입력하면 검색 및 치환에 사용할 정규식을 입력하라는 메시지가 표시됩니다. 이 기능은 '검색 및 치환' 에서 설명한 ~C-M-%~ 와 동일하게 작동합니다.

#+BEGIN_QUOTE
*Xref and Dired* :
Dired 에서도 Xref 기능을 사용할 수 있습니다.
~A~ 를 입력하면 검색을, ~Q~ 를 입력하면
표시된 파일 내에서 검색 및 바꾸기를 수행할 수 있습니다.
#+END_QUOTE


** Working with Log Files
로그 파일을 꼼꼼히 살펴보는 것은 흔한 작업이며, Emacs는 이를 손쉽게 관리할 수 있는 도구들이 있습니다.

| 키        | 설명                               |
| ~C-x C-f~ | 파일을 검색합니다                  |
| ~C-x C-r~ | 읽기 전용 모드로 파일을 검색합니다 |
| ~C-x C-q~ | 읽기 전용 모드로 전환합니다        |

로그 파일을 여는 것이 첫 번째 단계입니다. 파일을 읽기 전용으로 열 수도 있습니다. 파일에 쓰기 권한이 없다면, Emacs는 자동으로 ~M-x read-only-mode~ 로 파일을 엽니다. ~C-x C-q~ 를 눌러 이 모드를 켜거나 끌 수 있습니다. 읽기 전용 모드를 해제해야 하는 이유는 버퍼에 플러싱이나 줄 유지 같은 파괴적인 변경을 적용할 수 있도록 처리하기 위해서입니다:

| 키                | 설명                                        |
| ~M-x flush-lines~ | 지정된 패턴과 일치하는 줄을 모두 삭제합니다 |
| ~M-x keep-lines~  | 지정된 패턴과 일치하는 줄만 남깁니다        |
| ~M-s o~           | 지정된 패턴과 일치하는 줄을 나열합니다      |

~M-s o~ 는 패턴에 일치하는 Occur 모드 버퍼를 생성합니다. 많은 사람들이 간과하는 점은, Occur 모드 버퍼에서 ~M-s o~ 를 다시 실행해서 내용을 좀 더 세밀하게 필터링할 수 있다는 사실입니다.

거의 똑같은 로그 항목들이 줄줄이 이어지는 화면을 스크롤하다 보면 패턴에만 눈이 멀어 정작 중요한 내용을 놓치기 쉽습니다. 이럴 때 Emacs의 하이라이터 기능이 유용합니다. 버퍼 내의 패턴을 서로 다른 색상으로 강조 표시해서 구분할 수 있기 때문입니다:

| 키        | 설명                                    |
| ~M-s h p~ | 특정 구문을 강조 표시합니다             |
| ~M-s h r~ | 정규식을 강조 표시합니다                |
| ~M-s h .~ | 커서 위치의 기호를 강조 표시합니다      |
| ~M-s h u~ | 커서 위치의 밑줄 강조 표시를 해제합니다 |

하이라이터 기능은 유용하며, Emacs 모든 곳에서 사용할 수 있습니다. 키 바인딩을 외우지 못하더라도, 모든 명령 이름이 ~highlight-~ 로 시작하므로 필요할 때 ~M-x .~ 을 사용해서 쉽게 실행할 수 있다는 점만 기억하시기 바랍니다.

로그 파일은 정적 파일이 아닌 경우가 많습니다. 로그 파일은 끊임없이 변경되거나 추가됩니다. 파일 시스템에서 파일이 변경되면 Emacs가 파일을 새로 고치는 마이너 모드를 활성화할 수 있습니다. 최신 버전의 Emacs는 (대부분의 최신 플랫폼에서) 파일 변경 이벤트를 사용하고, 알림을 지원하지 않는 구형 시스템은 폴링 기술을 사용합니다.

| 키                          | 설명                                        |
| ~M-x auto-revert-mode~      | 파일이 변경되면 버퍼를 복원합니다           |
| ~M-x auto-revert-tail-mode~ | 파일이 변경되면 변경 내용을 끝에 추가합니다 |

두 모드 모두 비슷합니다. 파일 내용이 자주 변경되는 경우 ~M-x auto-revert-mode~ 는 필수적입니다. Emacs는 변경 사항을 감지해서 파일 전체를 다시 불러옵니다. 반면 ~M-x auto-revert-tail-mode~ 는 ~tail -f~ 와 동일한 방식으로 작동합니다. 파일이 변경되면 변경된 내용은 버퍼 끝에 추가되고, Emacs는 이에 따라 화면을 스크롤합니다.


*** Browsing Other Files
물론 이런 개념을 다른 파일 형식에 적용하는 것을 막을 이유는 전혀 없습니다. 예를 들어, Emacs는 기본적으로 활성화된 수동 모드인 자동 압축 모드가 내장되어 있으므로, 파일을 열거나 저장할 때 자동으로 압축을 풀고 다시 압축합니다. 이 기능을 ~M-x dired~ 와 함께 사용하면 압축된 아카이브를 마치 디렉터리인 것처럼 탐색할 수 있습니다.


**** Dired: Thumbnail Image Browser
~M-x image-dired~ 를 입력하면 Emacs의 이미지 썸네일 브라우저로 들어갈 수 있습니다. 썸네일이 표시된 창과 파일이 담긴 dired 창이 나타납니다.

썸네일 버퍼는 다양한 키 바인딩이 구비되어 있습니다. 그 중 일부는 다음과 같습니다:

| Thumbnail 키 | 설명                                 |
| ~C-f, C-b~   | 다음 또는 이전 썸네일로 이동         |
| ~C-p, C-n~   | 썸네일 행을 위나 아래로 이동         |
| ~d, m, u~    | 삭제, 선택, 선택 해제 (Dired와 동일) |
| ~t t, t u~   | 이미지에 태그 지정 또는 태그 해제    |
| ~RET~        | 이미지 열기                          |
| ~l, r~       | 썸네일을 왼쪽 또는 오른쪽으로 회전   |

전체 크기 이미지 버퍼는 세 가지 단축키로 제공됩니다:

| Image 키 | 설명                         |
| ~q~      | 종료                         |
| ~s~      | 이미지를 창 크기에 맞게 조정 |
| ~f~      | 전체 화면으로 보기           |

다만, dired 에서 파일을 열면 Dired Image Display Mode가 아닌 일반 이미지 뷰어인 Image Mode(훨씬 더 강력한 기능을 갖추고 있음)로 전환된다는 점에 유의하시기 바랍니다.


**** DocView: Viewing Rich Documents
사용 중인 시스템이 비교적 최신 버전이고, 필요한 프로그램이 설치되어 있다면, Emacs의 이미지 렌더링 기능을 활용해서 PDF 및 Open/MS Office 문서를 열 때 즉시 변환할 수 있습니다.

#+BEGIN_QUOTE
*DocView Support* :
Emacs가 변환을 시도하는 항목의 전체 목록을 보려면
~C-h v auto-mode-alist~ 를 입력하고 ~doc-view~ 를 검색합니다.
이 변수는 책 초반부에 메이저 모드 로드 순서에 대해 다룰 때
언급했던 것을 기억하실 겁니다.
#+END_QUOTE

DocView 를 사용하면 PDF 또는 기타 지원되는 바이너리 파일을 열면 Emacs가 해당 파일을 렌더링하려고 시도합니다. 파일이 열리면 사용할 수 있는 주요 단축키 조합은 다음과 같습니다:

| 키                | 설명                                     |
| ~n, p~            | 위/아래 페이지 이동                      |
| ~<next>, <prior>~ | 위/아래 페이지 이동                      |
| ~SPC~             | 아래로 스크롤                            |
| ~S-SPC~           | 위로 스크롤                              |
| ~M-<, M->~        | 첫 페이지/마지막 페이지로 이동           |
| ~+ , - , 0~       | 확대, 축소 또는 초기화                   |
| ~W, H, P, F~      | 너비, 높이, 페이지 또는 창 크기에 맞추기 |

이는 사용 가능한 키 바인딩 중 일부에 불과합니다. 특히 주목할 점은 문서를 천천히 넘겨가면서 읽을 때 사용하는 ~SPC~ 와 ~S-SPC~ 로, 이 기능들은 주로 읽는 문서에 맞춰 설계되었습니다. ~+~ 와 ~-~ 를 사용해서 확대하거나 축소할 수 있습니다. 또한 ~W~ 나 ~H~ 를 사용해서 Emacs가 자동으로 문서 크기를 조정해서 창의 너비나 높이에 맞출 수 있습니다. 반면 ~F~ 를 누르면 창의 크기를 문서에 맞게 조정합니다.

만약 이미지가 깨져 보인다면, ~doc-view-resolution~ 을 사용자 정의해서 DPI를 높일 수 있습니다.

#+BEGIN_QUOTE
*Slide Show Viewer*:
~M-x doc-view-presentation~ 명령어는 Doc View 버퍼를
전체 화면 슬라이드 쇼로 전환합니다.

~n~ 과 ~p~ 키를 사용해서 “슬라이드” 사이를 이동할 수 있으며,
~q~ 키를 눌러 종료할 수 있습니다.
#+END_QUOTE



** TRAMP: Remote File Editing
원격 파일 편집은 대개 번거롭습니다. 보통 터미널 에뮬레이터를 통해 원격 환경과 상호작용하며, 거의 항상 그래픽 인터페이스의 편리함이나 평소 사용하던 설정 없이 작업해야 하기 때문입니다. /.emacs.d/ 디렉터리를 휴대하는 것은 식은 죽 먹기지만, 불편한 점은 여전합니다. 기술이 아무리 발전해도 원격 파일 편집에는 대개 타협안이 따르기 마련입니다.

Emacs의 ~TRAMP~ 시스템은 사용자가 마주칠 가능성 높은 대부분의 원격 파일 상호작용 문제를 해결하는 투명한 프록시입니다. TRAMP 는 의심할 여지 없이 Emacs에서 가장 멋진 기능 중 하나입니다.

TRAMP 는 ~C-x C-f~ (및 기타 명령어)를 모니터링해서 작동하며, scp 같은 명령줄 도구가 사용하는 것과 비슷한 특수 구문을 통해 원격 파일에 접근하려는 시도를 감지합니다. TRAMP 의 가장 큰 장점은 완전한 투명성입니다. Emacs에 원격 편집 기능이 있다는 사실을 모른다면, 전혀 눈치채지 못했을 것입니다. 원격 파일에 접근해서 편집하는 과정은 빠르고 매끄럽습니다.

모든 TRAMP 연결은 다음과 같은 구문을 따릅니다:

~/protocol:[user@]hostname[#port]:~

TRAMP 는 구형 및 신형 프로토콜을 다수 지원하지만, 요즘에는 주로 ssh 나 scp 를 사용할 가능성이 높습니다. TRAMP 프로토콜의 전체 목록과 작동 방식은 ~tramp-methods~ 변수나 info 매뉴얼 페이지(tramp)의 ‘Internal methods’ 항목을 참조하시기 바랍니다.

#+BEGIN_QUOTE
*Microsoft Window* :
Windows는 프로토콜 선택 옵션이 다릅니다.
Cygwin이나 크로스 컴파일된 OpenSSH 버전을 사용하지 않는다면,
PuTTY의 plink.exe 도구를 설치하고 프로토콜로 plink 를 사용해야 합니다.
#+END_QUOTE

오늘날의 서버 환경은 25년 전보다 훨씬 더 균일해졌지만, TRAMP 는 원격 셸이 일관되고 신뢰할 수 있는 환경을 제공하도록 배경에서 많은 작업을 수행합니다. 앞서 언급한 변수인 ~tramp-methods~ 는 TRAMP 가 각 프로토콜 유형을 어떻게 처리할지를 제어합니다. 잘 알려지지 않은 시스템을 사용하는 경우, 이 변수를 사용자 정의해야 할 수도 있습니다.

TRAMP 의 또 다른 유용한 기능은 =~/.ssh/config= 파일을 파싱해서 프로토콜로 ssh 를 입력했을 때 알려진 호스트를 자동으로 완성해 준다는 점입니다. 물론 호스트 이름, 사용자 이름, 포트 모두를 수동으로 지정할 수 있으며, 후자 두 가지는 선택 사항입니다.

#+BEGIN_QUOTE
*SSH config*:
ssh 를 사용한다면, 모든 연결 및 인증 정보를 기억하기 쉬운 이름으로
저장할 수 있는 설정 파일을 사용하시기를 강력히 권장합니다.

자세한 내용은 Emacs에서 ~M-x man ssh_config~ 를 입력해서
관련 매뉴얼 페이지를 참조하시기 바랍니다.
#+END_QUOTE

마지막으로, TRAMP 를 실제로 실행하려면 루트에서 호출해야 합니다. FIDO 또는 IDO 모드에서 ~//~ 를 입력하면 루트로 이동하며, 위와 같은 형식을 따라야 합니다.

#+BEGIN_QUOTE
*Helm* :
Helm 을 사용 중이면, ~helm-tramp~ 라는 타사 패키지를 설치해서
필요한 모든 TRAMP 구성을 자동으로 생성할 수 있습니다.

또한 Docker 같은 도구에 대한 지원을 추가하는 TRAMP 확장 기능도 찾아볼 수 있습니다.
#+END_QUOTE

Emacs는 다음과 같이 두 번째 콜론(:)을 입력할 때까지 원격 연결을 시작하지 않는다는 점에 유의하시기 바랍니다:

~/ssh:homer@powerplant:/var/log/reactor.log~

위의 명령은 ssh 프로토콜과 homer 사용자를 사용해서 powerplant 서버에 연결합니다. 그런 다음 ~/var/log/reactor.log~ 파일을 엽니다. 


*** The Default Directory and Remote Editing
모든 버퍼는 ~default-directory~ 변수가 있습니다. 이 변수는 엘리스프(Elisp) 용어로 말하면 버퍼 로컬 변수입니다. 각 버퍼는 해당 버퍼에 국한되고 전역 변수가 아니기 때문에(Emacs에서 기본적으로 변수가 전역인 것과 달리) 고유한 ~default-directory~ 변수를 가지고 있습니다.

버퍼에서 ~C-x C-f~ 를 입력하면, Emacs는 ~default-directory~ 를 확인하고 해당 디렉터리를 새 파일을 열 때의 기본 디렉터리로 선택합니다. 이는 현재 버퍼와 디렉터리를 공유하는 다른 파일을 열기를 원할 수 있으므로 합리적인 방식입니다. ~/etc~ 에서 파일을 편집하는 중에 ~C-x C-f~ 를 입력하면 ~/etc~ 에 있는 다른 파일을 열기를 원할 수 있으므로, Emacs는 그곳을 기본 디렉터리로 선택합니다.

이 기능은 TRAMP 및 원격 파일도 동일하게 작동합니다. 원격으로 편집 중인 파일에서 ~C-x C-f~ 를 호출하면, Emacs는 로컬 시스템이 아닌 원격 시스템을 자동으로 조회해서, 다른 원격 파일을 쉽게 열 수 있게 해줍니다.

파일을 열면 TRAMP 가 뒤에서 마법 같은 작업을 수행해서, Emacs에서 로컬 파일과 거의 똑같이 보이고 느껴지는 파일을 사용할 수 있게 됩니다. 해당 파일이 원격 파일임을 알 수 있는 유일한 시각적인 단서는 모드라인입니다. 파일 이름 앞에 ~@~ 기호가 나타나며, ~default-directory~ 변수는 TRAMP 가 주석 처리한 파일 경로를 반영합니다. 직접 시도해 보고 ~C-h v~ 를 눌러 해당 변수를 확인하시기 바랍니다.

따라서, 파일을 원격으로 편집할 수 있을 뿐만 아니라, TRAMP 와 Emacs 간의 긴밀한 통합 덕분에 훨씬 더 많은 작업을 수행할 수 있습니다. ~M-x rgrep~ 같은 명령을 호출하면 Emacs와 TRAMP 가 매끄럽게 연동됩니다. 명령은 원격 머신에서 실행되며, 마치 로컬에서 명령을 호출한 것처럼 결과는 Emacs로 다시 전송됩니다.

원격으로 실행할 수 있는 작업에는 끝이 없습니다. 다음은 제가 원격으로 사용하는 몇 가지 명령어입니다:

*~C-x d~ : Dired* : 모든 명령어는 원격 세션을 통해 터널링되므로, 마치 로컬에 있는 것처럼 Dired 를 사용해서 파일과 디렉터리를 관리할 수 있습니다. 원격 및 로컬 Dired 세션 간에 파일을 복사할 수도 있으며, TRAMP 가 파일을 투명하게 복사해 줍니다.

*~M-x compile~ : Compile* : make 나 python manage.py runserver 같은 컴파일 명령어, 또는 원하는 어떤 명령어든 입력할 수 있습니다. Emacs는 명령을 원격으로 실행하며, 그 결과는 ~*compilation*~ 버퍼에 표시됩니다. 실시간 피드백을 통해 원격으로 대화형 서버를 실행할 수도 있습니다.

*~M-x rgrep~ : Grep* : find 와 grep 모두 원격으로 호출되며, 다른 명령과 마찬가지로 결과는 Emacs에 표시됩니다. grep 출력에 포함된 하이퍼링크된 파일은 원격 파일을 올바르게 엽니다.

*~M-x shell~ : Emacs의 셸 래퍼* : 원격 로그인 셸을 시작하고 사용자에게 제어권을 넘겨줍니다. 이는 로컬 머신에서 ~M-x shell~ 을 실행하는 것과 똑같이 작동하지만, 이 경우 셸은 당연히 원격 머신에 있습니다. TAB 자동 완성 – ~M-x shell~ 은 실제 셸이 아닌 Emacs에서 수행됨– 역시 작동합니다.

*~M-x eshell~ : Emacs의 Elisp 셸* : Eshell 은 Emacs Lisp으로 작성된 셸입니다. 또한 원격 TRAMP 연결도 투명하게 작동합니다. 실제로 로컬 셸에서 곧바로 원격 디렉터리로 cd 명령을 실행할 수 있습니다.


*** Multi-Hops and User Switching
TRAMP 의 또 다른 멋진 기능은 su 또는 sudo 를 통한 권한 상승입니다. 다른 사용자나 루트 권한으로 파일을 편집할 경우, 로컬 파일도 이 기능이 작동합니다. 이 기능은 중간 호스트를 통해 원격 호스트에 연결하는 ‘멀티 홉(multi-hop)’ 개념과 자연스럽게 연결됩니다. 예를 들어, 내부 서버에 접속해야지만 보안을 강화하기 위해 먼저 공용 서버를 통해 연결하는 경우나, 특정 사용자로 로그인한 후 sudo 를 호출해서 원격 서버에서 루트 권한으로 파일을 편집할 경우가 있습니다.

~/etc/fstab~ 파일에 대한 sudo 접근 권한을 요청하는 좀 더 간단한 경우부터 시작해 보겠습니다:

~/sudo:root@localhost:/etc/fstab~

보시다시피, 구문은 일반적인 원격 TRAMP 연결 방식과 동일합니다. 단지 sudo 를 사용하고 로컬로 연결한다는 점만 다를 뿐입니다. TRAMP 는 root 사용자임을 알아차릴 만큼 똑똑하므로 보통 ~root@~ 는 생략해도 됩니다. 이 파일은 (TRAMP의 관점에서) 기술적으로 원격 파일이므로 기본 디렉터리에 대한 일반적인 규칙이 그대로 적용된다는 점을 명심하시기 바랍니다. 원격 버퍼에서 ~C-x C-f~ 로 파일을 열면 다른 파일들도 sudo 권한으로 열립니다

TRAMP 에서 멀티 홉(multi-hopping)은 보통 ~tramp-default-proxies-alist~ 를 수정해서 수행하지만, 저는 이 방법이 다소 번거롭다고 생각합니다.

adhoc 구문을 사용하는 것이 훨씬 더 간편합니다:

~/ssh:homer@powerplant|sudo:powerplant:/root/salary.txt~

위의 예제는 homer 계정으로 powerplant 서버에 연결합니다. 그런 다음, 또 다른 ‘연결’ 이 sudo 를 호출해서 sudo 권한을 가진 사용자로 ~/root/salary.txt~ 파일을 엽니다. sudo 문자열에 호스트명을 반복해서 지정하는 것이 중요합니다. 그렇지 않으면 작동하지 않습니다. 앞서 설명한 것과 마찬가지로, 원격 파일도 이와 동일한 규칙을 따릅니다. salary 파일 내에서 ~M-x shell~ 같은 명령을 호출하면 powerplant 서버에서 루트 셸을 얻을 수 있습니다.

#+BEGIN_QUOTE
*Bookmarks* :
~C-x r m~ 을 사용해서 원격 파일을 북마크로 저장할 수 있으며(북마크 및 레지스터 참조),
나중에 ~C-x r b~ 또는 ~C-x r l~ 로 북마크를 다시 열면 TRAMP가 자동으로 다시 연결됩니다.

북마크는 Emacs의 다양한 기능과 폭넓게 연동됩니다.
특히 복잡한 다단계 연결의 경우, 북마크를 사용하면 시간을 크게 절약할 수 있습니다.
#+END_QUOTE

마지막으로, init 파일에 다음 코드 조각을 추가하시기를 권장합니다. 이것은 ~M-x sudo~ 로 호출하면 TRAMP 를 사용해서 현재 파일을 루트 권한으로 편집하는 사용자 정의 명령어입니다:

#+BEGIN_SRC
(defun sudo ()
  "Use TRAMP to `sudo' the current buffer."
  (interactive)
  (when buffer-file-name
    (find-alternate-file
      (concat "/sudo:root@localhost:"
              buffer-file-name))))
#+END_SRC

위에서 살펴본 것 같이, 문자열을 약간 수정하면 다단계 명령을 쉽게 만들 수 있습니다. 엘리스프(Elisp)를 처음 접하고 다단계 명령이 필요하다면, 이를 재미있는 입문 과정으로 삼아서 배워보는 것도 좋습니다.

*Conclusion* : TRAMP 는 Emacs의 내장 셸 지원 기능 및 창과 버퍼와 결합되어, tmux 및 GNU screen 기반의 워크플로우를 대체할 훌륭한 대안이 됩니다. 원격 파일 편집을 Emacs 내에서 수행함으로써, 사용 환경이 통합되고 서로 다른 TRAMP 는 Emacs의 정말 강력한 기능이며, 다른 대안들보다 사용해 볼 가치가 있습니다. 기존의 원격 편집 방식을 완전히 대체할 수는 없겠지만, 시작하기에 좋은 선택지입니다.



** EWW: Emacs Web Wowser
오래전부터 Emacs는 자윈스키(Zawinski)의 ‘소프트웨어 포괄화 법칙’ 에 굴복해 왔습니다. 이 법칙은 “모든 프로그램은 이메일을 읽을 수 있을 때까지 확장하려 한다. 그렇게 확장할 수 없는 프로그램은 확장할 수 있는 프로그램으로 대체된다!” 고 규정하는데 Emacs는 하나가 아닌 여러 개의 메일 클라이언트를 내장함으로써 이를 실천해 왔습니다.

분명 21세기엔 기준을 한 단계 더 높여야 합니다. 따라서, 이맥스에 내장 웹 브라우저인 EWW(Emacs Web Wowser)가 있다는 사실은 그리 놀라운 일도 아닙니다.

EWW는 작고 멋진 웹 브라우저 엔진입니다. 렌더러는 기본적인 HTML과 이미지 지원으로 제한되지만 기존 텍스트 기반 브라우저들과 크게 다르지 않습니다. 하지만, 제한된 렌더러에도 불구하고 기술 문서를 훑어보거나, 빠르게 웹 검색을 하거나, 상사에게 들키고 싶지 않은 웹사이트를 둘러보는 데는 아주 훌륭합니다.

EWW를 사용하려면 ~M-x eww~ 를 입력한 후 URL 이나 검색어(keyword)를 입력하라는 메시지가 나타납니다. 기본 검색 엔진은 DuckDuckGo 지만 ~eww-search-prefix~ 를 사용자 정의해서 변경할 수 있습니다. Emacs 27부터 이미 EWW 버퍼가 존재해도 ~C-u M-x eww~ 를 입력하면 새로운 EWW 버퍼를 생성합니다.

#+BEGIN_QUOTE
*External and internal browsing* :
~M-x browse-url~ 명령어로 시스템 웹 브라우저로 열 수 있습니다.

Emacs는 ~browse-url-default-browser~ 변수를 사용하는데 이 변수는 운영체제에 설치된 브라우저에 따라
적절한 브라우저를 자동으로 추정하는 함수입니다.

~M-x customize-option browse-url-default-browser~ 로 기본 브라우저를 사용자 정의할 수 있습니다. 
#+END_QUOTE

EWW는 주로 키보드로 탐색하지만(Emacs에서 예상할 수 있듯이) 하이퍼링크는 마우스로 클릭할 수 있습니다.

| 키           | 설명                            |
|--------------+---------------------------------|
| ~TAB, S-TAB~ | 다음/이전 하이퍼링크로 이동     |
| ~q~          | EWW 종료                        |
| ~&~          | ~M-x browse-url~ 로 페이지 열기 |
| ~B~          | 북마크 표시                     |
| ~b~          | 북마크 추가                     |
| ~H~          | 브라우저 기록 표시              |
| ~l, r~       | 기록에서 뒤로/앞으로 이동       |
| ~p, n, u, t~ | 시맨틱 웹 탐색 보조 기능        |
| ~R~          | 리더 모드 활성화                |
| ~RET~        | 링크 탐색                       |
| ~C-u RET~    | 외부 브라우저에서 링크 열기     |
| ~M-s M-w~    | EWW에서 현재 위치 검색          |
| ~M-RET~      | 새 버퍼에서 링크 열기           |
| ~s~          | 다른 EWW 버퍼로 전환            |
| ~w~          | 현재 위치의 링크 복사           |

#+BEGIN_QUOTE
*Emacs 28* :
Emacs 28에서 EWW는 Emacs의 다른 구성 요소들과 북마크 시스템을 공유합니다.
#+END_QUOTE

가장 많이 사용하는 명령어는 하이퍼링크를 여는 ~TAB~ 과 ~S-TAB~ 그리고 브라우저 기록 내에서 앞뒤로 이동하는 ~l~ 과 ~r~ 입니다. ~p, n, u, t~ 명령어는 웹 페이지에서 어떤 하이퍼링크가 다음 링크고 이전 링크인지 의미론적으로 명시되어 있을 때만 작동합니다.

~R~ 키를 누르면 리더 모드로 전환합니다. 정말 훌륭합니다. 이 모드는–시도만 하지만 EWW는 대부분 정확하게 처리합니다–모든 방해 요소를 제거하고 본문 텍스트만 남깁니다. 읽기에 최적입니다.

~M-s M-w~ 명령어도 유용합니다. 이 명령어는 선택된 영역을 기본 검색 엔진(보통 DuckDuckGo)으로 보내고 결과를 EWW에 표시합니다.

** Dired: Files and Directories
파일 시스템에서 파일과 디렉터리를 탐색하고 조작하는 작업은 Emacs에 특히 잘 맞는 분야입니다. 일반적인 방식으로 로컬 파일을 편집하거나 TRAMP 를 사용해서 원격 파일을 편집하는 것 외에도, Emacs의 디렉터리 편집기인 dired 를 사용해서 디렉터리와 파일을 조작할 수 있습니다.

dired 에 접근하는 방법은 여러 가지가 있습니다:

*IDO 또는 FIDO 모드에서* : ~C-x C-f~ 로 파일을 검색할 때 ~C-d~ 를 입력하면 해당 파일의 현재 디렉터리에서 dired 버퍼를 열 수 있습니다.

*명령어로* : ~M-x dired~ 명령어를 실행하면 열 디렉터리를 입력하라는 프롬프트가 나타납니다. 기본값은 ~current-buffer~ 가 위치한 디렉터리인 ~default-directory~ 입니다. TRAMP 와 마찬가지로, 파일이 원격에 있는 경우 Emacs는 원격 dired 세션을 열 것인지 묻습니다.

*키 바인딩으로* : 키 바인딩 ~C-x d~ 는 위의 명령과 동일하게 작동합니다. 명령 ~C-x 4 d~ 는 동일한 작업을 수행하지만 다른 창에서 실행합니다.

Emacs에서 dired 버퍼를 열면, 다음과 비슷한 화면이 나타납니다:

#+BEGIN_SRC
/usr/share/dict:
total used in directory 2328 available 187646744
drwxr-xr-x 2 root root 4096 Feb 16 09:57 .
drwxr-xr-x 326 root root 12288 Mar 27 11:43 ..
-rw-r--r-- 1 root root 938848 Oct 23 2011 american-english
-rw-r--r-- 1 root root 938969 Oct 23 2011 british-english
-rw-r--r-- 1 root root 199 Jan 14 2014 select-wordlist
#+END_SRC

리눅스 명령줄을 사용해 본 적이 있다면, 출력 결과가 매우 익숙하게 느껴질 것입니다. 이는 Emacs가 ~M-x grep~ 같은 다른 명령어들의 정신을 이어받아, 기존 명령줄 유틸리티의 출력 결과를 단순히 확장하기 때문입니다. 이 경우 대개 ~ls -al~ 명령을 사용하지만, ~dired-listing-switches~ 를 사용자 정의해서 적용되는 옵션을 변경할 수 있습니다.

#+BEGIN_QUOTE
*Microsoft Windows* :
Microsoft Windows를 사용한다면 걱정하지 않아도 됩니다.
Emacs는 엘리스프(Elisp)로 작성된 ls 에뮬레이션 레이어가 내장되어 있습니다.

Emacs는 ls 를 호출하는 대신 운영체제에 직접 쿼리를 보냅니다.
그 결과 플랫폼을 가리지 않고 원활하게 작동하는 인터페이스를 제공합니다.
#+END_QUOTE

앞서 언급했듯이, 버퍼(The Buffer) 개념과 Emacs의 “확장(augmentation)” 시스템은 외부 프로그램과 연동하는 강력하고 실용적인 방식입니다. Emacs가 ls 를 호출하면, 그 출력은 버퍼로 삽입되고, dired 모드가 활성화되며, Emacs가 텍스트를 자동으로 탐색할 수 있도록 돕기 위해 텍스트에 하이라이트, 하이퍼링크 및 기타 숨겨진 속성이 추가됩니다. 메이저 모드 자체가 키 바인딩을 제공하므로, 파일에서 ~RET~ 키를 누르면 해당 파일이 열립니다. 실제 다른 버퍼와 마찬가지로, dired 의 출력은 기본적으로 일반 텍스트로 그대로 복사할 수 있습니다.

대부분의 Emacs 초보자, 심지어 중급 사용자들조차 dired 를 제대로 다루지 못합니다. 대부분은 디렉터리를 탐색하는 정도를 넘어서지 못하는데, 이는 매우 안타까운 일입니다. 왜냐하면, 단순해 보이는 겉모습 뒤에는 파일 및 디렉터리 작업을 위한 매우 복잡하고 효율적인 시스템이 숨어 있기 때문입니다. 실제로, 수백 가지의 dired 명령어와 수십 가지의 다른 명령어와의 연동 기능이 dired 인터페이스와 매끄럽게 연동되어 작동합니다.


*** Navigation
dired 의 탐색 기능은 꽤 직관적이며, 버퍼이기 때문에 Isearch, 화살표 키, 마우스 등 평소 사용하던 모든 탐색 도구를 그대로 사용할 수 있습니다.

| 키               | 설명                           |
| ~RET~            | 파일 또는 디렉터리를 열기      |
| ~^~              | 한 단계 위 디렉터리로 이동     |
| ~q~              | dired 종료                     |
| ~n, p, C-n, C-p~ | 커서를 목록에서 위/아래로 이동 |

하지만, 현재 디렉터리의 상위 디렉터리로 한 단계 이동하려면 ~^~ 키를 사용해야 합니다. ~C-n~ 및 ~n, C-p~ 및 ~p~ 명령은 한 줄씩 위나 아래로 이동할 뿐만 아니라, 포인터를 파일 이름 바로 앞에 위치하도록 재조정합니다.

~RET~ 키를 누르면 Emacs는 해당 파일이나 디렉터리를 열며, 디렉터리인 경우 새로운 dired 버퍼가 열립니다. 따라서, 하위 디렉터리를 열고 난 후 ~q~ 를 누르면 마지막으로 열었던 dired 버퍼로 돌아갈 수 있습니다.


*** Marking and Unmarking
여러 파일이나 디렉터리에 어떠한 작업을 수행하려면 항목에 체크 표시를 하거나 해제하는 작업을 자주할 것입니다.

| 키  | 설명           |
| ~m~ | 선택 상태 표시 |
| ~u~ | 선택 상태 해제 |
| ~U~ | 모두 선택 해제 |
| ~d~ | 삭제 표시      |

표시(marking)와 삭제 표시(flagging for deletion)는 반드시 구분해서 사용해야 합니다. ~d~ 는 삭제 표시를 의미하며(표시된 항목 옆에 =D= 가 표시됨), ~m~ 은 표시를 의미합니다. 표시된 파일은 삭제 명령의 영향을 받지 않으며, 그 반대의 경우도 마찬가지입니다. 단, 표시된 파일을 삭제하는 특정 명령 하나는 예외입니다. 표시된 파일은 ~*~ 로 강조 표시됩니다.

표시 및 삭제 표시 모두 커서를 다음 항목으로 이동시킵니다(마치 ~C-n~ 을 입력한 것처럼), 하지만, 음수 인수를 사용하면 이동 방향을 반대로 바꿀 수 있습니다.

#+BEGIN_QUOTE
*Discover more* :
dired 는 명령어가 너무 많아 모두 나열하는 것은 불가능합니다.
나머지 명령어들은 평소처럼 탐색적인 접근 방식
(즉, 모드 설명, 접두사에 바인딩된 키 목록 확인 등)을 이용해서
직접 찾아보시길 권장합니다.

또는, Emacs에 설명이 포함된 팝업 메뉴를 추가해 주는
저의 패키지인 Discover 를 사용할 수도 있습니다.

또한 저의 웹사이트를 방문하시면 다양한 dired 기능을
매우 상세하게 다루는 글들을 찾아보실 수 있습니다.
#+END_QUOTE

특정 항목을 표시하는 마크 명령어도 있습니다:

| 키       | 설명                             |
| ~* m~    | 영역 표시                        |
| ~* u~    | 영역 표시 해제                   |
| ~* %~    | 정규 표현식을 사용해서 파일 표시 |
| ~* .~    | 확장자를 기준으로 파일 표시      |
| ~t, * t~ | 표시 상태 전환                   |
| ~* c~    | 표시 변경                        |

접두사 키 ~*~ 는 다양한 마크 명령이 포함되어 있습니다. 위에 나열된 것은 일상적으로 사용하기에 가장 실용적인 네 가지 명령입니다. 영역 키들은 활성 영역이 닿는 모든 dired 항목을 표시하거나 표시를 해제합니다. 정규식 및 확장자 표시 명령도 마찬가지로 유용하며, ~* t~ 를 사용해서 표시 상태를 토글(반전)할 수 있습니다.

~* c~ 는 매우 특별한 기능입니다. 이 명령은 마크 기호를 기존 기호에서 새로운 기호로 변경합니다. 따라서, ~*~ (기본 마크 기호)를 ~D~ 로 변경해서 마크된 파일을 삭제 표시된 파일로 바꿀 수 있습니다. 하지만, 삭제 표시된 파일로 처리할 수 있는 작업은 사실상 삭제 뿐이므로, 삭제 표시된 파일을 삭제하는 전용 명령과 마크된 파일도 삭제하는 또 다른 명령이 따로 있습니다.


*** Operations
작업(또는 연산)은 현재 선택된 항목(디렉터리에 선택된 파일이 없는 경우)이나, 선택된 파일이 있는 경우 해당 파일들에 대해 수행할 수 있습니다.

선택된 파일에 작업을 수행할 때, Emacs는 대개 작업 확인을 요청하고 영향받는 파일 목록을 표시합니다. 선택 명령어와 마찬가지로 수행할 수 있는 작업은 다양합니다. 먼저 기본적인 작업들을 살펴보겠습니다:

| 키(마크 표시됨) | 설명                             |
| ~C~             | 파일 복사                        |
| ~R~             | 파일 이름 변경 또는 이동         |
| ~O~             | 소유자 변경                      |
| ~G~             | 그룹 변경                        |
| ~M~             | 권한 변경                        |
| ~D~             | 표시된 파일 삭제 (*로 표시됨)    |
| ~x~             | 표시된 파일 삭제 (D로 표시됨)    |
| ~F~             | 파일 열기 (dired-x 필요)         |
| ~c~             | 표시된 파일을 하나의 파일로 압축 |

위의 키들은 대부분 설명이 필요없을 정도로 매우 직관적입니다. 파일을 삭제하려면 ~x~ 와 ~D~ 의 차이점만 기억하면 됩니다.

#+BEGIN_QUOTE
*Copying or renaming between dired buffers* :
~dired-dwim-target~ 옵션을 사용자 정의하면 두 개의 dired 버퍼 간에
파일을 복사하거나 이름을 변경(이동)할 수 있습니다.

실수로 열어둔 채 잊고 있던 다른 dired 버퍼로 파일을 옮기지 않도록
주의하시기 바랍니다. 저도 그런 실수를 꽤 여러 번 저질렀거든요!
#+END_QUOTE

또한 표시된 파일에 적용되지 않는 키들도 있습니다:

| 키     | 설명                      |
| ~g~    | 디렉터리 버퍼 새로 고침   |
| ~+~    | 하위 디렉터리 생성        |
| ~s~    | 이름/날짜 정렬 전환       |
| ~<, >~ | 이전/다음 디렉터리로 이동 |
| ~j~    | 파일로 이동               |

#+BEGIN_QUOTE
*Dired-X* :
일부 명령어는 ~dired-x~ 가 필요합니다.
이 패키지는 어떤 타당한 이유없이 기본적으로 활성화되지 않아서
안타깝게도 수동으로 활성화해야 합니다.

이 설정이 적용되도록 초기화 파일(init 파일)에 다음을 추가합니다:

~(require 'dired-x)~
#+END_QUOTE

~dired-x~ 가 설치되면, 마크된 모든 파일을 순차적으로 확인하는 ~F~ 명령을 사용할 수 있습니다. 중요한 점은, 이 명령은 파일을 열려고 시도하며 각 파일에 별도의 창을 할당한다는 것입니다. 이는 원치 않는 상황일 수 있습니다. 이를 피하고 파일을 백그라운드에서 열려면 ~C-u F~ 를 입력합니다.

| 키(마크 표시됨) | 설명                     |
| ~M-s~ 및 ~C-s~  | iSearch 시작             |
| ~Q~             | Xref Query로 regexp 대체 |
| ~A~             | Xref 검색 regexp 검색    |
| ~!~             | 동기식 셸 명령           |
| ~&~             | 비동기식 셸 명령         |

때때로 파일 내의 텍스트를 검색하거나 바꿔치울 때가 있는데, 다소 다루기 까다로운 키 바인딩인 ~M-s a C-s~ 를 사용해서 여러 파일을 한 번에 검색할 수 있습니다. ~Q~ 명령어는 마크된 모든 파일에 ~C-M-%~ –정규식 검색 및 교체–를 실행합니다. 하지만, 변경 사항을 저장하는 것을 잊지 마시기 바랍니다(~C-x s~ 를 누르면 저장되지 않은 모든 버퍼에 대해 저장 여부를 묻는 메시지가 표시됩니다).

~!~ 를 마크없이 호출하면, ~dired-xis~ 가 활성화된 경우 해당 파일에 대한 다음 작업을 추측하려고 시도합니다. 예를 들어 ~.zip~ 파일인 경우, 압축을 풀 것인지를 묻습니다. ~.patch~ 파일인 경우, Emacs는 해당 파일에 patch 명령을 실행합니다. ~dired-guess-shell-alist-default~ 변수는 많은 패턴이 지정되어 있습니다. 이는 시간을 많이 절약해 줍니다.

마크가 활성화된 상태에서 ~!~ 와 ~&~ 를 누르면 사용자가 선택한 외부 명령을 호출합니다. 또한 Emacs에 마크된 항목을 명령에 어떻게 전달할지 알려주어야 합니다:

*표시된 항목당 하나의 명령* : 이 모드는 Emacs가 마크된 각 항목에 대해 사용자가 선택한 명령을 한 번씩 호출합니다.

*표시된 모든 항목에 대한 하나의 명령* : 이 경우 Emacs는 마크된 각 항목을 공백으로 구분해서 단일 명령에 전달합니다.

일부 명령은 실행하는 데 시간이 오래 걸릴 수도 있으므로, Emacs가 명령을 동기식으로 호출해서 완료될 때까지 Emacs를 대기 상태로 만들지(~!~ 사용), 아니면 명령을 비동기식으로 실행하도록 지정할지(~&~ 사용) 결정해야 합니다.

다음은 실제 예입니다. /american-english/ 와 /british-english/ 라는 두 파일을 가정합니다. 셸 명령을 어떻게 작성하느냐에 따라 동작은 달라집니다. 선택적으로 ~*~ 또는 ~?~ 를 지정해서, 각 선택 항목마다 하나의 명령을 실행할지, 아니면 모든 선택 항목에 대해 하나의 명령을 실행할지 지정할 수 있습니다.

~*~ 는 셸의 파일 글로브(glob) 패턴처럼 작동하며, Emacs는 선택된 모든 파일을 하나의 긴 인수로 단일 명령에 삽입합니다:

~echo *~

출력 결과:

~american-english british-english~

이것은 Emacs가 선택된 두 항목 모두를 포함해서 명령을 한 번만 실행했기 때문입니다.

반면 ~?~ 를 사용하면 마크된 각 항목에 대해 명령이 실행됩니다:

~echo ?~

이때 출력은 다음과 같습니다:

#+BEGIN_SRC
american-english
british-english
#+END_SRC

출력이 있는 경우, 몇 줄에 불과하다면 echo 영역에 표시됩니다. 그렇지 않은 경우, ~*Shell Command Output*~ 또는 ~*Async Shell Command*~ 라는 전용 버퍼로 리디렉션됩니다. 


*** Working Across Directories
디렉터리를 새로운 dired 버퍼로 여는 대신, 기존 dired 버퍼에 해당 내용을 삽입하도록 설정할 수 있습니다. 디렉터리에 커서를 두고 ~i~ 를 입력하면, dired 는 이를 하위 디렉터리로 동일한 dired 버퍼에 삽입합니다. 즉, 동일한 dired 버퍼에 있는 한, 여러 dired 디렉터리에 걸쳐 동일한 마크 및 플래그 명령을 사용할 수 있습니다. ~$~ 명령어를 사용하면 하위 디렉터리를 접을 수 있으며, 접혀있는 동안엔 해당 디렉터리에 명령어가 적용되지 않습니다.

여러 디렉터리를 하나의 공유 dired 버퍼에 삽입하면, 여러 디렉터리를 동시에 한 눈에 볼 수 있을 뿐만 아니라, 마치 하나의 커다란 디렉터리인 것처럼 작업할 수도 있습니다. 이는 Emacs의 강력하지만 제대로 활용되지 않는 또 다른 기능입니다. 하지만, ~i~ 를 입력하는 것은 번거로울 뿐만 아니라, dired 또는 셸 명령을 재귀적으로 적용할 경우는 제대로 작동하지 않으므로 다른 접근 방식이 필요합니다.

이 문제를 해결하려면 Emacs의 find 래퍼 명령을 사용할 수 있습니다. 저는 이런 명령들이 dired 의 강력한 기능과 결합되면 find 와 xargs 를 직접 사용하는 것을 거의 완전하게 대체할 수 있다고 생각합니다. dired 의 셸 명령어 지원과 광범위한 파일 조작 기능을 활용하면, 대부분의 사용자가 find 를 사용해서 제대로 수행하기 어려워하는 작업도 Emacs에서 처리할 수 있습니다.

모든 명령어는 find 의 출력을 받아서 시작 디렉터리를 기준으로 dired 버퍼를 생성합니다. Emacs는 버퍼의 파일 이름 부분에 포함된 상대 경로를 자동으로 인식할만큼 똑똑합니다. dired 내의 모든 명령어는 평소와 같이 작동합니다.

| 키                     | 설명                                         |
| ~find-dired~           | 패턴을 지정해서 find 명령을 실행합니다       |
| ~find-name-dired~      | -name 옵션을 사용해서 find 명령을 실행합니다 |
| ~find-grep-dired~      | find 와 grep 을 함께 실행합니다              |
| ~find-lisp-find-dired~ | Emacs와 정규식을 사용해서 파일을 찾습니다    |

처음 세 개 명령어는 명령줄 유틸리티인 find 를 호출합니다. ~find-dired~ 는 grep 명령어와 마찬가지로 가장 기본적인 명령어입니다. 이 명령어는 find 패턴과 시작 디렉터리를 지정해야 합니다. ~find-name-dired~ 는 사용자가 지정한 특정 디렉터리에서 시작해서 파일 이름에 대해서만 셸 글로브 패턴을 사용해서 검색합니다. ~find-grep-dired~ 는 모든 파일을 검색하지만, grep 에 전달된 패턴과 일치하는 파일만 표시합니다.

#+BEGIN_QUOTE
*Microsoft Windows* :
Microsoft Windows는 GNUWin32나 Cygwin 같은 크로스 컴파일된 바이너리를
설치하거나 ~find-lisp-find-dired~ 를 사용할 수 있습니다.
#+END_QUOTE

~find-lisp-find-dired~ 명령어는 Emacs의 elisp로 구현된 ~find-dired~ 입니다. 이 명령어는 모든 플랫폼에서 작동하며 별도의 외부 도구가 필요하지 않습니다. 대신, 기능 면에서는 그다지 강력하지 않습니다. 또한, 셸 글로빙(globbing)이 아닌 Emacs의 정규 표현식 엔진을 사용합니다.



** Shell Commands
dired 에 관한 장에서 살펴본 것 같이, Emacs는 셸과 연동되는 강력한 명령어들이 있습니다. 그 외의 모든 버퍼의 경우, 일반적인 버퍼에서 작동하는 훨씬 더 포괄적이면서도 강력한 셸 명령어들이 있습니다.

| 키            | 설명                                          |
| ~M-!~         | 셸 명령을 호출하고 출력을 표시합니다          |
| ~C-u M-!~     | 위와 같으나, 버퍼에 내용을 삽입합니다         |
| ~M-&~         | ~M-!~ 와 같으나 비동기적으로 실행됩니다       |
| ~C-u M-&~     | ~C-u M-!~ 와 같으나 비동기적으로 실행됩니다   |
| ~M-\vert~     | 선택한 영역을 셸 명령으로 파이프합니다        |
| ~C-u M-\vert~ | ~M-\vert~ 와 같으나, 선택한 영역을 대체합니다 |

~M-!~ 를 사용해서 어떤 셸 명령이든 호출할 수 있으며, 텍스트가 몇 줄에 불과한 경우 Emacs는 출력 결과를 에코 영역에 표시합니다. ~M-!~ 를 사용한 경우는 ~*Shell Command Output*~ 이라는 전용 버퍼에, ~M-&~ 를 사용한 경우는 ~*Async Shell Command*~ 버퍼에 출력됩니다. 두 명령 중 하나를 범용 인자와 함께 호출하면, 현재 버퍼의 커서 위치에 출력 결과를 삽입합니다.

~M-|~ 명령은 훨씬 더 실용적입니다. 이 명령은 선택된 영역을 입력으로 받아 사용자가 지정한 셸 명령의 표준 입력으로 보내며, ~M-!~ 와 거의 동일한 방식으로 출력을 반환합니다: 즉, 에코 영역이나 전용 버퍼에 출력합니다. 범용 인수를 사용해서 명령을 호출하면, 활성 영역이 대체됩니다. 이는 uniq 나 입력을 수정하는 다른 명령줄 도구 같은 명령을 즉석에서 호출할 때 ~C-u M-|~ 을 훌륭하게 만들어 줍니다.

~M-&~ 는 비동기적이라서(즉, 명령이 종료될 때까지 Emacs를 블록하지 않음) 장시간 실행되는 작업에 적합하지 않습니다. ~M-x compile~ 을 사용하는 것이 훨씬 더 낫습니다.


*** Compiling in Emacs
셸 명령어를 호출하는 것은 빠르고 일회성인 명령에 적합하며, 일반적으로 반복적으로 자주 수행하는 작업은 아닙니다. 그런 목적으로는 이름과는 달리 단순한 컴파일 이상의 기능을 뛰어나게 수행하는 Emacs의 ~M-x compile~ 명령어를 고려하시기 바랍니다.

| 명령어             | 설명                                    |
| ~M-x compile~      | 명령을 실행하고 오류를 추적합니다       |
| ~M-x recompile~    | 마지막 명령을 다시 실행합니다           |
| ~M-g M-n, M-g M-p~ | 다음/이전 오류 위치로 이동합니다 (전역) |
| ~g~                | 마지막 명령을 다시 실행합니다           |
| ~C-x p c~          | 현재 프로젝트에서 컴파일합니다          |

~M-x compile~ 을 호출하면 명령어를 입력하라는 메시지가 나타나며, Emacs는 사용자가 make 를 사용한다고 가정합니다. 하지만, 출력을 추적하고 싶은 명령어라면 무엇이든 자유롭게 대입할 수 있습니다: 단위 테스트, 컴파일, 스크립트 실행 등 무엇이든 가능합니다.

~M-x compile~ 의 가장 큰 장점은 보조 명령어인 ~M-x recompile~ 로, 이 명령어는 마지막으로 실행한 명령을 다시 실행합니다. 또한 Compile 은 패턴 매칭 엔진 덕분에 오류도 추적합니다. ~M-x grep~ 및 ~M-x occur~ 와 마찬가지로, ~M-g M-n~ 및 ~M-g M-p~ 명령어는 호출 스택이나 컴파일러 오류 로그를 탐색할 수 있으며, 해당 형식이 Emacs가 인식하는 형식과 일치하는 경우에 한합니다. 파이썬부터 대부분의 컴파일러에 이르기까지 모든 것이 Emacs에 알려져 있으므로, 여러분이 사용하는 컴파일러도 아마 작동할 것입니다.



** Shells in Emacs
외부 터미널 에뮬레이터를 사용하거나, tmux 나 screen 과 함께 쓰기 위해 터미널에서 Emacs를 실행하는 대신, Emacs를 “멀티플렉서” 로 활용해서 Emacs 내에서 셸을 실행하는 건 어떨까요? TRAMP 와 Emacs의 타일형 창 관리 및 버퍼 기능을 결합하면, 전용 터미널 에뮬레이터의 거의 모든 일반적인 사용 사례를 대체할 수 있습니다.

Emacs에서 bash 같은 셸을 사용하는 방법에는 세 가지가 있습니다. 하나는 ~M-x shell~ 이라 불리는, 외부에 존재하는 기존 셸(예: bash)을 단순히 감싸는 래퍼 방식입니다. 또 다른 방법은 ~M-x eshell~ 이라 불리는, Lisp으로 작성된 완전한 셸 구현체입니다. 그리고 세 번째는 ~M-x ansi-term~ 이라 불리는 터미널 에뮬레이터입니다.

세 가지 모두 매우 강력하며, 각각 고유한 방식으로 문제를 해결하려 시도합니다. 어떤 것을 사용하든 (결국 하나 이상을 사용할 수도 있습니다) 여러 가지 장단점이 따릅니다.

그러나, 이 세 가지 모두 elisp를 사용해서 외부 프로그램과 통신하거나, Emacs 내에서 셸을 구현하거나, top 같은 복잡하고 대화형인 프로그램을 렌더링하는 데 필요한 터미널 제어 코드를 해석합니다. 또한 세 가지 모두 지금쯤이면 여러분이 꽤 익숙해졌을 Emacs의 강력한 버퍼 패러다임을 사용해서 세 가지 구현체 모두에 대한 통합된 인터페이스를 제공합니다.

버퍼 패러다임은 특히 여기서 강력한데, 외부 프로그램이나 운영체제와 직접 통신할 수 있는 기능이 바로 Emacs를 그토록 강력한 편집기로 만드는 요소 중 하나이기 때문입니다. 텍스트 편집 같은 전통적인 용도로도 사용되지만, 이제 bash와의 상호작용 같은 훨씬 더 고급스럽고 특화된 작업까지 활용되는 버퍼에서 모든 편집 및 이동 명령과 elisp의 강력한 기능을 활용할 수 있습니다. 그리고 이 두 극단적인 용도가 버퍼라는 공통 기반을 공유하기 때문에, 완전히 새로운 시스템을 다시 배울 필요가 없습니다. 텍스트 편집기나 웹 브라우저로 복사하기 위해 터미널 에뮬레이터에서 마우스로 텍스트를 일일이 선택하는 번거로움도 더 이상 없습니다. Emacs는 모든 것이 텍스트이며, 여러분이 익숙한 모든 이동 및 편집 명령이 여기서도 정확히 동일하게 작동합니다.


*** M-x shell : Shell Mode
Emacs의 셸 모드는 외부 프로그램(예: Linux의 bash 나 Windows의 cmd.exe)을 호출하며, Windows는 stdin, stdout, stderr 를 재지정하거나(리디렉션), Linux는 의사 터미널을 통해 Emacs를 통해 기본 셸과 상호작용할 수 있도록 해줍니다.

하지만, Emacs가 I/O를 리디렉션하기 때문에, 이에 따르는 장점과 단점을 감수해야 합니다. 예를 들어, 셸 고유의 TAB 자동 완성 기능을 사용할 수 없습니다. 대신 Emacs 자체의 자동 완성 기능을 사용해야 하는데, 이는 어떤 면에서는 좀 더 강력합니다. 반대로 셸 모드 버퍼는 완전히 텍스트로 구성되므로, 명령어의 출력을 편집하고 삭제할 수 있으며, 버퍼 안팎으로 텍스트를 복사하고 붙여넣는 것도 손쉽게 처리할 수 있습니다. 이로 인해 셸 모드는 유연하지만 호불호가 갈립니다. top 이나 man 같은 프로그램은 작동하지 않거나, 작동하더라도 제대로 동작하지 않습니다.

저는 개인적으로 거의 모든 명령줄 작업에 셸 모드를 사용합니다. 대화형 터미널 프로그램은 거의 사용하지 않으며, 정말 필요할 때는 Emacs의 ~M-x ansi-term~ 을 사용해서 제대로 된 터미널 에뮬레이션을 이용할 수 있습니다.

*장점* : 셸 모드는 단순한 버퍼에 불과하기 때문에 자유로운 텍스트 편집과 이동이 가능하다는 점이 단점보다 더 큽니다.

#+BEGIN_QUOTE
*GNU readline and defaults* :
대부분의 리눅스 배포판은 GNU readline 라이브러리를 사용해서
명령어 기록, 검색 및 교체, 고급 이동 및 편집 같은
기본적인 명령 프롬프트 기능을 제공합니다.

기본적으로 이런 기능은 Emacs 키 바인딩을 통해 사용할 수 있습니다.
#+END_QUOTE

다음은 가장 흔히 사용되는 명령어 몇 가지입니다. 아쉽게도 키 바인딩은 제각각입니다.

| 키                 | 설명                                             |
| ~M-p, M-n~         | 명령어 이력을 순환합니다                         |
| ~C-<위>, C-<아래>~ | 명령어 이력을 순환합니다                         |
| ~M-r~              | 이력을 역방향으로 검색합니다                     |
| ~C-c C-p, C-c C-n~ | 이전/다음 프롬프트로 이동합니다                  |
| ~C-c C-s~          | 명령어 출력을 파일에 저장합니다                  |
| ~C-c C-o~          | 명령어 출력을 킬 링(kill ring)으로 보냅니다      |
| ~C-c C-l~          | 명령어 이력을 나열합니다                         |
| ~C-d~              | 현재 위치의 문자를 삭제하거나 ~^D~ 를 전송합니다 |
| ~C-c C-z~          | 서브 작업 중지 신호를 전송합니다                 |
| ~TAB~              | 현재 위치에서 자동 완성합니다                    |

~M-p, M-n, C-<up>, C-<down>~ 은 모두 일반 터미널 에뮬레이터에서 위/아래 화살표 키를 사용할 때와 거의 동일한 방식으로 명령어 이력을 순환합니다. Emacs는 이 키들이 버퍼 내에서 커서를 실제로 이동시키지만, 셸 모드에 익숙하지 않은 사용자들은 이를 보고 항상 헷갈려 합니다.

~M-r~ 은 이력 역방향 Isearch 를 실행합니다. 이 명령은 매우 강력해서 배워둘 가치가 충분히 있습니다. ~C-d~ 는 다른 곳과 마찬가지로 커서 앞의 문자를 삭제합니다. 하지만, 입력 내용이 없는 경우(즉, 프롬프트에 아무것도 입력하지 않은 경우), Emacs는 EOF 제어 코드를 전송해서 현재 실행 중인 프로그램을 종료합니다. 마찬가지로, ~C-c C-z~ 는 bash에서 작업 제어를 위해 사용하는 ~C-z~ 와 동일한 기능을 수행합니다.

셸 모드의 멋진 기능 중 하나는 ~C-c C-s~ 를 사용해서 마지막 명령의 출력을 파일에 저장하거나, ~C-c C-o~ 를 사용해서 그 내용을 킬 링(kill ring)으로 보낼 수 있다는 점입니다.

~TAB~ 키는 별도로 언급할 가치가 있습니다. bash 같은 셸은 파일 경로뿐만 아니라 자체적인 복잡한 자동 완성 메커니즘을 갖추고 있습니다. Emacs도 마찬가지입니다. ssh 같은 명령어의 호스트명이나 chown 명령어의 그룹 및 소유자 등을 자동 완성할 수 있습니다.


*** M-x ansi-term : Terminal Emulator
Emacs는 ANSI를 지원하는 터미널 에뮬레이터입니다. ~M-x ansi-term~ 을 실행하고 셸을 선택하면, top 이나 심지어 vim, emacs 같은 대화형 프로그램을 실행할 수 있습니다.

이 에뮬레이터의 가장 큰 단점은 속도가 느리다는 점이며, 일부 잘 알려지지 않은 터미널 에뮬레이션 기능은 지원되지 않습니다.

| 키        | 설명             |
| ~C-c C-j~ | 라인 모드로 전환 |
| ~C-c C-k~ | 문자 모드로 전환 |

기본적으로 ~ansi-term~ 은 셸 모드나 일반적인 Emacs 버퍼가 아닌 일반 터미널 에뮬레이터처럼 작동합니다. 하지만, 두 가지 모드, 즉 일반적인 Emacs 버퍼와 유사한 ‘라인 모드’ 와 일반 터미널 에뮬레이터와 유사한 ‘캐릭터 모드’ 사이를 전환할 수 있습니다.

기본 모드는 문자 모드이며, 이는 키보드 문자를 포함해서(단순히 Emacs 키 바인딩뿐만 아니라) 대부분의 키 입력이 Emacs를 완전히 우회해서 기본 셸 프로그램으로 직접 전송된다는 것을 의미합니다. ~C-c~ 라는 이스케이프 문자가 있는데, Emacs가 이를 가로채기 때문에 ~C-c C-j~ 나 ~C-c C-k~ 같은 명령은 하위 프로그램으로 전송되지 않습니다. 따라서, ~C-c~ 를 하위 프로그램으로 보내려면 ~C-c C-c~ 를 입력해야 합니다.

Emacs에서 가장 실제 터미널과 유사한 환경을 원한다면, ANSI term이 최선의 선택입니다. 저는 라인 모드와 문자 모드 사이를 전환하는 번거로움이 꽤 귀찮게 느껴져서, 대신 셸 모드를 사용하는 것을 선호합니다.


*** M-x eshell : Emacs’s Shell
누군가가 Lisp으로 셸 전체를 구현했다는 사실은 그다지 놀라운 일도 아닙니다. ~M-x eshell~ 을 실행하면, Elisp로 작성된 셸을 사용하는데, 이 셸은 Emacs를 통해 기본 호스트 운영체제와 통신하며, ls, cp, cd 등 Elisp로 에뮬레이트된 GNU coreutils 명령어를 포함한 전형적인 리눅스 스타일의 bash 셸을 훌륭하게 재현해 줍니다.

실질적으로 이는 Emacs가 실행되는 모든 플랫폼에서 일관된 셸 환경을 제공한다는 것을 의미합니다. 네이티브 TRAMP 지원 및 명령어 출력을 Emacs 버퍼로 직접 리디렉션하는 기능과 결합되어, 다재다능하고 강력하며 Emacs의 정신을 충실히 반영한 도구를 갖게 됩니다.

Eshell 은 ANSI-term 보다는 쉘 모드에 좀 더 가깝습니다. top 같은 대화형 프로그램을 지원하지 않으며, 대신 Eshell에서 해당 프로그램을 호출할 때 전용 ~M-x ansi-term~ 인스턴스를 열어 실행하는 방식을 선호합니다. 이는 문제에 대한 영리하고 실용적인 해결책입니다.

또 다른 중요한 차이점은, Eshell이 bash 같은 셸에서 영감을 받았지만, 사실은 그 자체만의 셸 구현체로서 그에 따르는 모든 특이점, 기능 및 한계를 고유하게 지니고 있다는 점입니다. Eshell은 무엇보다 elisp 셸이라는 점을 명심해야 합니다. Eshell에 입력하는 모든 명령은 먼저 Eshell 고유의 에뮬레이션 레이어를 거쳐, 그 다음 Emacs 고유의 대화형 명령을 통과한 뒤, 마지막으로 ~$PATH~ 에 있거나 현재 디렉터리에 있는 프로그램을 통해 처리되기 때문입니다. 예를 들어, ~dired .~ 을 입력하면 현재 디렉터리에서 ~M-x dired~ 세션을 열 수 있고, ~find-file todo.org~ 를 입력하면 현재 실행 중인 Emacs에서 todo.org 파일을 열 수 있습니다.


