* Chapter 1. Introduction

#+BEGIN_QUOTE
“I’m using Linux. A library that emacs uses to communicate with Intel hardware.”  
 
 – Erwin, #emacs,Freenode.
#+END_QUOTE


**  Thank You
『Mastering Emacs』 를 구매해 주셔서 감사합니다. 이 책은 오랜 시간 준비한 결과물입니다. 2010년 제 블로그에 『Mastering Emacs』 를 시작한 것은 친한 친구인 리(lee)가 제게 Emacs와 Emacs 작업 흐름에 대한 생각을 공유해보라고 권유했기 때문입니다. 그당시 저는 'blogideas.org' org 파일에 제가 배웠던 내용과 누군가에게 가르쳐 주면 좋겠다고 생각했던 아이디어와 개념을 방대하지만 무작위로 모아 뒀습니다. 그 파일의 최종 결과물이 바로 그 블로그였고 이제는 이 책이 되었습니다.


*** Special Thanks
다음 분들께 격려와 조언, 제안, 그리고 비판을 보내주신 데 대해 감사의 말씀을 전합니다:

#+BEGIN_EXAMPLE
Akira Kitada, Alvaro Ramirez, Arialdo Martini,
Bob Koss, Catherine Mongrain, Chandan
Rajendra, Christopher Lee, Daniel Hannaske,
Edwin Ong, Evan Misshula, Friedrich Paetzke,
Gabriela Hajduk, Gabriele Lana, Greg Sieranski,
Holger Pirk, John Mastro, John Kitchin, Jonas
Enlund, Konstantin Nazarenko, Lee Cullip,
Luis Gerhorst, Lukas Pukenis, Manuel Uberti,
Marcin Borkowski, Mark Kocera, Matt Wilbur,
Matthew Daly, Michael Reid, Nanci Bonfim,
Oliver Martell, Patrick Mosby, Patrick Martin,
Sebastian Garcia Anderman, Stephen Nelson Smith,
Steve Mayer, Tariq Master, Travis
Jefferson, Travis Hartwell.
#+END_EXAMPLE

다른 사람과 마찬가지로 저 또한 Emacs에 대해 아무것도 모르는 상태에서 그 세계로 내몰렸습니다. 저의 경우 대학 1학년 때였는데 그당시 학교 컴퓨터 동아리 대부분은 Vim 사용자들로 구성되어 있었습니다. 저에게 “Vim을 써야 해, 그게 다야!” 라고 단호하게 말했습니다. 누군가에게 지시받는 것을 원치 않았던 저는 Vim과 정반대인 ~Emacs~ 를 선택했습니다.

Emacs는 오랫 동안 안정적이고 믿을만한 편집기임을 증명했지만 익히기엔 꽤 까다로운 도구였습니다. 방대한 사용자 설명서에도 불구하고 Emacs를 배우거나 이해하는 데는 별 도움이 되지 않았습니다.


** 2022 Edition Update
~Emacs 28~ 은 최신 버전으로 오랫동안 기다려온 네이티브 컴파일 기능을 도입해서 Emacs 27에 비해 상당한 업그레이드를 이루었습니다. 타사 패키지의 규모와 야망이 해마다 커짐에 따라 Emacs의 성능도 향상되야 합니다. 네이티브 컴파일 기능은 Elisp를 사용자의 플랫폼과 시스템 아키텍처에 적합한 네이티브 코드로 컴파일함으로 전반적으로 Emacs의 성능을 크게 향상시킵니다. 이는 주로 /Andrea Corallo/ 한 사람의 거대한 노력으로 이루어졌으며 Emacs 28에 포함되기까지 수 년의 고된 작업을 필요로 했습니다.

이 기능을 제외하면 Emacs 28의 변경 사항 대부분은 점진적인 것으로 새로운 명령어나 사용자 정의 기능이 사용자가 알아둘 가치가 있다고 판단될 때 이에 맞춰 책을 업데이트 했습니다.

다음과 같이 강조하고 싶은 몇 가지 기능이 있습니다:

- *프로젝트 관리 기능 개선 사항:* 

이 중 일부는 Emacs 27에도 포함됐지만 Emacs 28에서 크게 강화됐습니다. 프로젝트 관리용 키맵으로 접근성과 사용 편의성이 향상됐으며 Emacs에 이미 존재하던 수많은 기능도 개선됐습니다.

- *좀 더 친숙한 도움말 및 설명 명령어:* 

Emacs는 자체 문서화 기능을 갖추고 있지만 이번 릴리스에서 해결될 것으로 보이던 몇 가지 사각지대가 있습니다. 도움말 시스템은 새로 추가된 키 바인딩과 보다 명확한 설명으로 약간의 업데이트가 이루어 졌습니다. ~describe~ 시스템은 Emacs에서 심볼을 조회할 수 있는 주요 방법이며 Emacs 28은 이를 돕는 몇 가지 새로운 명령어를 추가했습니다.

- *좀 더 나은 기능 탐색성:*

마이너 모드나 메이저 모드와 관련된 유용한 명령을 찾는 것이 항상 쉬운 일은 아닙니다. 특정 모드에서 수많은 명령을 도입할 수 있지만 그 중에서 일반 사용자에게 유용한 것은 소수에 불과할 수 있습니다. 이제 Emacs는 현재 버퍼의 활성 모드와 관련된 명령만 선별적으로 요청할 수 있습니다. 이는 기능 탐색성을 크게 향상시킵니다.

책 내용은 독자에게 실질적인 차이를 주지않을 것으로 판단된 대부분의 버전 표기(일부는 Emacs 24 시절까지 거슬러 올라가는 것들)를 제거했습니다. 그 과정에서 제가 원한만큼 명확하거나 자명하지 않다고 생각되던 부분의 문장을 다듬고 내용을 명확히 했습니다.


** Emacs in the Future
앞으로 몇 년 동안 Emacs에 어떤 변화가 기다리고 있을까요? 한 가지 흥미로운 가능성은 대부분의 편집기에서 구문 강조와 의미론적 정보를 추출할 때 사용하는 도구인 정규 표현식은 이미 수십 년 전에 정점을 찍었다는 사실을 인식하는 것입니다. 이보다 지능적인 도구를 원한다면 소스 코드의 파싱 방식을 좀 더 스마트하게 개선해야 합니다. 이것은 새롭거나 독창적인 아이디어는 아니지만 구현하기 어려운 대규모의 과제입니다. 이로 인해 지능형 코드 완성 기능의 언어 서버(Language Servers)로 누구나 접근하거나 확장할 수 있는 표준화된 프로토콜로 대중화하기 전까진 발전이 더뎠습니다.

Emacs는 ~js2-mode~ 나 ~nxml-mode~ 처럼 구문이나 의미론적 보강 작업을 위해 언어 파서를 사용하는 몇 가지 메이저 모드가 있습니다. 자체 언어 파서와 의미론적 툴링을 갖춘 방대한 다국어 IDE인 ~CEDET~ 는 대략 10년 전 Emacs 코어에 병합됐지만 그다지 인기를 얻진 못했습니다. 다른 편집기에서 널리 채택된 범용 언어 파싱 라이브러리인 ~tree-sitter~ 가 이 작업에 가장 적합한 도구입니다. 이 라이브러리는 정규 표현식을 완전히 대체하진 않으며 그럴 필요도 없습니다. 정규 표현식도 그 나름대로 용도가 있으니까요...

하지만, ~tree sitter~ 는 수십 가지 언어를 지원하며 S-표현식 기반의 쿼리 언어를 사용합니다. 이로 인해 Emacs와 elisp에 완벽히 어울립니다. 또한, 처리 속도가 빠르고 소스 코드를 처리할 수 있으므로 코딩 중에도 제대로 작동합니다. 지금 바로 Emacs의 tree-sitter로 훨씬 개선된 구문 강조 기능을 경험할 수 있습니다.


** 2020 Edition Update
제가 사람들이 관심가질 만하다고 생각되는 Emacs 글을 공유하기 위해 블로그를 시작한 지도 벌써 10년입니다. 그리고 이 책의 초판을 출간한 지도 5년입니다. 5년 동안 어느날 갑자기 등장해서 폭발적으로 인기를 끌었던 텍스트 편집기들이 나타났다가 새로운 도전자 앞에서 그 기세가 꺾이기도 했습니다. 한편 Emacs 사용자들은 여전히 Emacs를 사용하며 다른 편집기들의 발전(그리고 퇴보…)에서 배우고 있습니다. 하지만, 지난 5년 동안 Emacs 사용자들이 혜택볼 수 있는 발전도 많이 있습니다.

Microsoft VSCode는 소프트웨어 커뮤니티에서 수십 년 전에 합의되고 구현했어야 할 것을 표준화 했단 점에서 언급할 가치가 있습니다. 즉, 컴파일러, 인터프리터 및 기타 프로그래밍 가능한 엔진의 내부 구조를 노출하거나(불가능한 경우 재구현) 비공개 소스의 IDE를 사용한 사람은 누구나 익숙한 고급 기능을 지원할 수 있는 프로토콜입니다: 자동 리팩토링; 구문 및 오류 강조 표시; 코드 완성; 문서 조회 등. 

일부는 놀랍게도 마이크로소프트가 개방형 JSON-RPC 표준인 /Language Server Protocol/ 을 통해 논쟁에서 승리했습니다!! 이 프로토콜이 등장하기 전에는 대부분의 IDE와 에디터는 범위, 깊이, 품질 면에서 제각각인 폐쇄적인 자체적인 구현 방식을 사용했습니다. 이는 특히 Emacs와 사용자들에겐 커다란 승리입니다. 그들은 이제 Language Server를 구축한 사람들의 공동 작업 기능을 누릴 수 있습니다.

#+BEGIN_QUOTE
[!NOTE]
*Language Servers in Emacs* : 주목할만한 두 가지 구현체가 있습니다. ~LSP mode~ 와 ~EGlot~ 입니다.
LSP mode는 설치 즉시 완벽한 IDE 환경을 제공하는 반면 EGlot은 간결하고 Emacs 중심의 접근 방식을 선호합니다.

두 가지 모두를 사용한 후 마음에 드는 것으로 선택하시기 바랍니다.

두 제품 모두 현재 활발히 개발 중이며 그에따라 빠르게 변화하고 있습니다.
또한, 다양한 도구와 언어를 폭넓게 지원합니다.
#+END_QUOTE

IDE 스타일의 기능은 이맥스의 위상을 높여주지만 이맥스를 배울 때 피할 수 없는 한 가지 사실은 일단 익숙해지면 배우던 시절의 고생이 얼마나 힘들었는지 금새 잊어버린다는 점입니다. 이것이 바로 비-사용자들이 비판하기 쉬운 표면적인 문제점 중 하나였습니다. 용어는 난해하고 UI는 투박하며 키 바인딩이 복잡하다는 것입니다. 하지만, 사실입니다. 그것이 바로 Emacs입니다. 또한, 모든 것을 바꿀 수 있습니다. 저는 이런 불만에 일말의 진실이 있다고 믿습니다. 좀 더 예쁜 UI는 즉각적인 성과며 몇몇 목소리 크고 까다로운 원로 사용자를 화나게 만들 위험이 있더라도 Emacs의 다소 난해한 기본 설정 중 일부를 변경한 것은 또 다른 성과입니다.

하지만, 첫인상은 매우 중요합니다. 사람들은 적합성과 형태로 순식간에 판단을 내립니다. 만약 이 편집기로는 코드를 처리하진 못하지만 다른 편집기가 해낸다면 그들은 Emacs를 시도조차 하지 않을 수 있다는 뜻입니다. =Spacemacs= 와 =Doom Emacs= 같은 올인원 패키지의 매력이나 첫인상은 이러한 첫인상의 중요성과 합리적인 기본 설정의 가치를 증명합니다. 많은 이들이 스타터 키트 중 하나를 사용하면서 Emacs로 뛰어들고 그런 신기함이 사라지면 그만큼 많은 이들이 자신만의 Emacs 설정 단계로 넘어갑니다. 하지만, 그 시점에 그들은 이미 평생 Emacs 사용자가 된 것입니다.

이 책은 Emacs를 배우는 상세한 방법을 다루며 여러분은 분명 Emacs를 익히게 됩니다. Emacs의 용어들은 현대 컴퓨팅보다 훨씬 더 오래됐지만 다른 곳에서 주로 사용하는 UI 용어와 구별되는 용어는 소수에 불과하므로 배우기 쉽습니다. 키 바인딩과 명령어는 익히기 좀 더 어렵지만 그야말로 Emacs의 핵심입니다.

Emacs는 복잡한 소프트웨어로 이를 익힐려면 시간과 노력이 필요합니다. 하지만, 일단 익힌다면 평생 사용할 수 있는 편집기를 갖게 됩니다. Emacs는 활발하고 친근한 커뮤니티가 있으므로 다른 편집기에서 이루어낸 어떠한 발전이라도 빠르게 받아들여 Emacs에 통합합니다. 그리고 이는-이 책 나머지 부분에서 보겠지만–다른 편집기는 따라올 수 없는 수많은 장점을 제외하는 것입니다.

Emacs 유지보수자는 이런 사실을 잘 알고 있으며 이전 버전과 호환성을 유지하면서 모든 사용자를 위해 Emacs를 점진적으로 개선하기 위해 뒤에서 끊임없이 노력하고 있습니다. 그들은 훌륭한 관리자로 GNU 프로젝트 철학과 Emacs의 유산 그리고 안정성에 대한 헌신을 존중할 필요성과 기술 발전 및 사용자 피드백 사이에서 신중하게 균형을 맞추고 있습니다.

Emacs를 인내심을 가지고 익히신 노력은 분명 크게 보상받을 것입니다. 제가 장담합니다!!


** Intended Audience
이미 책을 구입한 상태에서 대상 독자층에 대해 이야기하는 것이 이상할 수 있습니다. 어쨌든 언급할 필요는 있습니다. 여러분의 Emacs 실력이나 수준과 관계없이 이 책에서 무언가는 얻어갈 수 있으니까요...

첫 번째(이자 가장 명백한) 대상 독자층은 Emacs를 처음 접하는 분입니다. 평생 Emacs를 한 번도 사용한 적 없다면 이 책이 도움되길 바랍니다. 하지만, Emacs도 처음이고 기술적인 배경도 없다면 다소 어려움을 겪을 수 있습니다. Emacs는 단순한 프로그래밍 이상의 용도로 적합하지만 본질적으로 컴퓨터에 익숙한 사람이 주대상입니다. 물론 Emacs를 사용하는 데는 아무런 문제도 없지만 이 책은 독자가 어느 정도의 기술적인 소양이 있다고 가정하되 반드시 프로그래머일 필요는 없습니다.

다음은 Emacs를 사용했지만 포기했다면 이 책으로 계속 사용하길 바랍니다. 하지만, 괜찮습니다. (많은 Emacs 사용자들이 주장하는 것과 달리) 일부 언어나 개발 환경은 Emacs와 맞지 않기 때문입니다. Visual Studio를 사용하는 Microsoft Windows 개발자가 Emacs를 사용한다는 것은 두 걸음 전진하고 한 걸음 후퇴하는 상황입니다. 즉, 전례없는 텍스트 편집 기능과 도구 통합은 얻지만 통합 IDE가 제공하던 이점의 일부를 잃을 겁니다.

만약 Vim에서 넘어오신 분이라면 어둠의 세계에 오신 것을 환영합니다!! 여러분의 주된 목표가 Emacs의 Vim 에뮬레이션 레이어(evil)를 사용하는 것이라면 이 책의 일부 내용은 중복될 수 있습니다. 이 책은 기본 Emacs 키 바인딩에 초점을 맞추며 Emacs의 방식을 가르칩니다. 하지만, 걱정하지 않아도 됩니다. 이 책에 담긴 수많은 팁과 조언은 여전히 유용하며 언젠가 Evil 모드에서 벗어날지 모릅니다.

마지막으로 Emacs를 사용하고 있지만 한 단계 더 발전하는 데 어려움을 겪고 있거나 또는 처음부터 배우고 싶은 분이면 이 책은 바로 여러분을 위한 책입니다!!


** What You'll Learn
한 권의 책에서 Emacs의 모든 기능을 다룬다는 것은 시지프스 노동과 같은 일입니다. 대신 저는 여러분이 Emacs로 생산적으로 작업할 때 필요한 내용 즉, Emacs 기능의 일부만 가르쳐 드립니다. 이 책을 다 읽고 실습하면 Emacs를 충분히 이해하고 이 편집기에 대한 궁금증을 스스로 찾아내거나 해결할 수 있기를 바랍니다.

좀 더 구체적으로 저는 여섯 가지 주제를 다룹니다:

- *What Emacs is about* : Emacs에서 사용하는 용어와 관례에 대한 상세한 설명으로 이는 다른 편집기와 많은 경우 크게 다릅니다. 또한, Emacs의 철학이 무엇인지 그리고 텍스트 편집기에 왜 철학이 필요한지 배웁니다. 또한, Vim을 간략히 다루고 에디터 전쟁과 다양한 수정키의 의미도 설명합니다.

- *Getting started with Emacs*: Emacs 설치 방법과 실행 방법 그리고 최신 버전의 Emacs를 사용하는지 확인하는 방법을 다룹니다. Emacs를 수정하는 방법과 변경 사항을 영구 적용하기 위해 필요한 절차도 설명합니다. =Customize= 인터페이스와 사용자 정의 색상 테마를 로드하는 방법도 소개합니다. 마지막으로 Emacs의 사용자 인터페이스와 무언가 막힐 때 사용할 유용한 팁에 대해 이야기합니다.

- *Discovering Emacs*: Emacs는 자체 문서화 기능을 갖추고 있습니다. 하지만, 이것이 무엇을 의미하며 이런 특성을 활용해서 Emacs에 대해 좀 더 많이 알아가거나 특정 기능에 대한 의문점을 해결하려면 어떻게 할까요? 저는 Emacs에서 새로운 메이저 모드나 사용법을 배울 때 제가 어떻게 했는지를 보여드리고 여러분이 특정 정보를 찾기위해 Emacs의 자체 문서화 특성을 어떻게 활용할지를 설명합니다.

- *Movement*: Emacs에서 이동 방법은 언뜻 보기엔 간단하지만 Emacs는 현재 위치에서 가야할 곳까지 가능한 한 적은 키 입력으로 이동할 수 있는 댜양한 방법이 있습니다. 이동 작업은 개발자에겐 작업의 절반을 차지한다고 할 수 있으며 이를 빠르게 수행할 방법을 안다면 작업 효율은 크게 높아집니다. 배울 내용 중 일부는 구문 단위별 이동과 구문 단위가 정확히 무엇인지; 창과 버퍼의 사용법; 텍스트 검색 및 색인 생성 방법; 텍스트 선택과 마크 사용법 등이 포함됩니다.

- *Editing*: 이전 Movements 장과 마찬가지로 Emacs가 제공하는 다양한 도구로 텍스트를 편집하는 방법을 보여드립니다. 여기엔 균형잡힌 표현식, 단어, 줄, 단락 단위로 텍스트 편집하기; 반복 작업을 자동화하기 위한 키보드 매크로 생성 방법; 검색 및 바꾸기; 레지스터; 다중 파일 편집; 약어; 원격 파일 편집 등이 포함됩니다.

- *Productivity* : Emacs는 단순히 텍스트 편집기 이상의 기능을 제공하며 이 장은 수많은 사람들이 Emacs에 매료되는 이유 즉, 외부 도구와의 긴밀한 통합을 맛보게 해줍니다. 저는 여러분의 호기심을 자극하고 Emacs의 이동 및 편집 기능을 조화롭게 활용했을 때 처리할 수 있는 흥미로운 기능 몇 가지를 보여 드리겠습니다.



* Chapter 2. The Way of Emacs

#+BEGIN_QUOTE
“The purpose of a windowing system is to put
some amusing fluff around your one almighty emacs window.”

– Mark, gnu.emacs.help.
#+END_QUOTE

1960년대부터 시작된 현대 컴퓨팅 시대의 역사를 떠올려 보면 Emacs는 그 어떤 것보다 오랫동안 존재했습니다. Emacs는 1976년 리처드 스톨먼이 =TECO= 편집기에 매크로 세트로 처음 작성했습니다. =TECO= 편집기는 극히 난해한 것으로 기억됩니다. 이후 Emacs의 수많은 경쟁 구현체가 등장했지만 오늘날엔 =XEmacs= 와 =GNU Emacs= 정도만 만날 가능성이 높습니다.

하지만, 이 책은 =GNU Emacs= 에만 초점을 맞춥니다. 한때는 =XEmacs= 가 좀 더 발전됐고 기능도 풍부한 편집기였지만 이젠 그렇지 않습니다. Emacs 22 버전부터 =GNU Emacs= 가 가장 뛰어난 Emacs입니다. =XEmacs= 와 =GNU Emacs= 의 역사는 흥미롭습니다. 이는 자유 소프트웨어 프로젝트에서 일어난 최초의 중요 포크 중 하나였습니다. 오늘날 =XEmacs= 는 더이상 유지보수조차 되지 않고 있습니다.

#+BEGIN_QUOTE
[!NOTE]
*참고*:
대부분의 사람들에게 ‘Emacs’ 는 구체적으로 =GNU Emacs= 를 의미합니다.
저는 서로 다른 구현체로 구분할 때만 전체 이름을 명시합니다.

따라서, 제가 =Emacs= 라고 언급할 때는 항상 =GNU Emacs= 를 의미합니다.
#+END_QUOTE

Emacs가 오랜 역사를 지닌 탓에 여러 가지 특이한 점이 존재합니다. 이상한 용어의 선택이나 시대착오적인 표현이 여전히 남아있는 이유는 대부분의 경우 Emacs가 수십 년 동안 에디터-IDE 분야의 흐름을 선도했기 때문에 각종 기능에 독자적인 용어를 만들어야만 했기 때문입니다. Emacs의 용어를 누구나 익숙한 단어로 바꾸자는 논의도 있었지만 설령 그런 일이 일어나더라도 아직 갈 길이 멉니다.

마케팅은 부족하고 Emacs 개발자 인력은 아주 적으며 현대적인 개인용 컴퓨팅 시대보다 앞서 있던 시대착오적인 요소와 용어에도 불구하고 세상엔 Emacs를 사랑하는 사람들이 많습니다. Emacs의 강점은 그런 적응 능력에 있습니다. 여기서 말하는 '그런 적응 능력' 은 소프트웨어뿐만 아니라 Emacs의 방향을 결정하는 수많은 자원봉사 유지보수자와 기여자를 의미합니다. 그들은 대부분의 사용자들보다 더 오래된 제품의 한계 속에서도 세상의 변화에 뒤처지지 않도록 지칠 줄도 모르고 일을 합니다. 굳어버린 Emacs 커뮤니티와 플랫폼은 그저 신화에 불과합니다.

이번 장엔 ‘Way of Emacs’ 에 대해 이야기합니다. 여기엔 용어와 Emacs가 사람들에게 어떤 의미인지 그리고 Emacs의 기원을 이해하는 것이 왜 Emacs를 받아들이는 데 도움되는지 다룹니다.


** Guiding Philosophy
Emacs는 무언가 만지작거리기 좋아하는 사람을 위한 편집기입니다. 그 이상도 이하도 아닙니다. 사람들이 Emacs를 개조하는 이유는 이 편집기의 거의 모든 측면이 확장 가능하기 때문입니다. Emacs는 확장 가능하고 사용자 정의 가능하며 자동 문서화 기능을 갖춘 최초의 편집기입니다. 다른 편집기를 사용한 사람이라면 뭐든지 바꿀 수 있다는 생각이 불필요한 방해 요소로 보일 수 있습니다. 실제로 많은 Emacs 개조 작업은 본업에 지장주면서 이루어지기도 합니다. 하지만, 편집기를 자신이 원하는대로 만들 수 있다는 사실을 깨닫게 되면 무한한 가능성의 세계가 열립니다.

즉, Emacs의 모든 키 바인딩을 원하는대로 자유롭게 재설정할 수 있다는 뜻입니다. 여러분은 IDE의 문서화되지 않은 버그 투성이 API나 설정을 변경시 따를 수 있는 여러 제한 사항들—예를 들어, 사용자 정의 탐색 키가 검색 및 바꾸기 창이나 내부 도움말에서 제대로 작동하지 않는 것 같은 문제들—에 얽매이지 않습니다. Emacs는 모든 것을 바꿀 수 있으며 실제로 사람들은 그렇게 합니다.

Vim 사용자들이 Emacs로 이동하는 이유는?? 글쎄요, 종종 Emacs가 Vim보다 더 나은 Vim이기 때문입니다.

Emacs는 당신을 매료시킵니다. 일단 편집에 Emacs를 사용하면 IrC, 이메일, 데이터베이스 접속, 생각 정리, 명령줄 셸, 코드 컴파일, 인터넷 서핑까지 모두 텍스트 편집 작업만큼 쉽다는 것을 깨닫습니다. 게다가 키 바인딩과 테마 그리고 모든 동작을 재구성하거나 변경할 수 있는 Emacs와 elisp의 기능을 사용할 수 있습니다.

그리고 그 모든 것이 매끄럽게 통합되면 애플리케이션을 오가면서 겪을 수 있는 컨텍스트 전환을 피할 수 있습니다: 하지만, 대부분의 Emacs 사용자는 편집기, 웹브라우저 그리고 터미널 애플리케이션 정도만 사용합니다.

#+BEGIN_QUOTE
[!NOTE]
*Emacs's history* :
Emacs 소스 코드 저장소(현재 Git 기반)는 30년 이상의 역사를 자랑하며 13만 건이 넘는 커밋과 600명 가까운 커미터가 참여하고 있습니다.
#+END_QUOTE

Emacs나 수많은 패키지 중 하나를 수정하려면 ~Emacs Lisp~ (비공식적으로 =elisp= 라고 함)을 사용해야 합니다. elisp과 Emacs에 다른 언어를 접목하려는 시도도 몇 차례 있었지만 지속적인 성과를 거두진 못했습니다. 결과적으로 LISP는 Emacs 같은 고급 도구를 위한 완벽한 추상화 언어임이 밝혀졌습니다. 그리고 대부분의 현대 언어가 시간의 시험을 견딜 수 있었던 것은 아닙니다. 예를 들어, TCL 언어는 90년대 인기가 많았기에 잠시 고려됐지만 오늘날엔 LISP 언어보다 생소하단 특징을 가집니다.

유일한 단점은 Emacs 설정을 만지는 일을 받아들여야 한다는 점입니다(LISP도 마찬가지지만 사실 장점입니다). 그래서 제가 Emacs를 무언가 만지작거리는 사람을 위한 에디터라고 강조한 것입니다. 만약, 설정 건드리는 걸 싫어하고 설치 즉시 완벽하게 작동하길 원한다면 이제 남은 선택지는 두 가지 뿐입니다:

*Use a starter kit*: 추가 패키지와 작성자가 적절하다고 판단한 설정이 포함된 무료 스타터 키트가 있습니다. 이는 시작하기엔 좋은 방법일 수 있지만 Emacs 본연의 기능이 어디서 끝나고 스타터 키트의 기능이 어디서 시작되는지 구분하기 어렵다는 점을 유념합니다.

다음 스타터 키트 중 하나를 살펴보시길 권장합니다:

• [[Steve Purcell의 .emacs.d] - https://github.com/purcell/emacs.d
• Bozhidar Batzov의 Prelude - https://github.com/bbatsov/prelude

Vim에 강한 애착을 가진 독창적인 키트를 원하신다면:

• Spacemacs: Vim의 모달 편집과 Emacs의 확장성을 결합한 인기있는 스타터 키트 - https://spacemacs.org/
• Doom Emacs: Spacemacs과 마찬가지로 완성도 높고 가벼운 스타터 키트 - https://github.com/hlissner/doom-emacs

*Use the defaults*: 하나의 선택지지만 Emacs는 중립적이고 구식인 기본 설정으로 제공됩니다. 사용자는 자신의 취향에 맞게 Emacs를 설정하거나 다른 사람에게 그 작업을 맡겨야 합니다. 주류 편집기들과 극명하게 다른 이 편집기의 유지보수자들은 기존 사용자층(그들야말로 Emacs 설정 방법을 가장 잘 알고 있을 사람입니다)을 불편하게 만들까봐 기본 설정을 변경할 때는 매우 신중을 기합니다.

개인적으로 저는 스타터 키트를 사용한 적이 없습니다. 제가 20년 전쯤 시작했을 무렵엔 지금처럼 스타터 키트가 존재하지 않았기 때문입니다. 대신 그당시 우리가 '.emacs 파일' 이라 부르던 다른 사람의 설정 파일을 대거 차용했습니다.

이 접근 방식은 편집기를 처음부터 끝까지 이해하려는 사람에게 적합합니다. 스타터 키트를 살펴보시고(앞서 언급한 키트들에서 좋은 아이디어를 얻으세요!) 거기서 마음껏 차용하시길 권합니다.


*** LISP?
Emacs는 ‘Emacs Lisp’ 또는 줄여서 ‘elisp’ 이라 불리는 자체 LISP 구현체 기반으로 작동합니다. 많은 사람들이 이런 난해한 언어때문에 주저하거나 겁을 먹는데 이는 정말 아쉬운 일입니다. 왜냐하면, LISP를 하나의 독립된 기계로 간주하는 개념을 바탕으로 구축된 이 편집기로 LISP 언어를 배운다는 것은 실용적이면서 재미있는 방법이기 때문입니다. Emacs의 모든 부분은 검토, 평가 또는 수정할 수 있습니다. 왜냐하면, 이 편집기는 대략 95%가 elisp 코드이며 5% 정도가 C 코드이기 때문입니다. 또한, 이는 급진적인 패러다임을 배울 수 있는 실용적인 방법입니다. 즉, 코드와 데이터는 상호 교환 가능하고 유연하며 언어의 간단한 구문과 매크로를 통해 쉽게 확장할 수 있습니다.

안타깝지만 언젠가 Elisp를 배워야 합니다!! 하지만, 이 책은 Emacs의 사용자 정의 옵션을 동적으로 설정할 수 있는 인터페이스인 'Customize 인터페이스' 에 대해 이야기합니다. 하지만, 키 재할당처럼 단순한 작업조차 Elisp와 상호작용해야 합니다. 하지만, 나쁜 것만은 아닙니다. 여러분이 마주칠 가능성 높은 문제 대부분은 오래 전에 누군가에 의해 해결됐으니 단지 인터넷에서 해결책만 검색하면 되는 간단한 문제일 뿐입니다.

파이썬, 루비, 자바스크립트 같은 보다 현대적인 언어에 비해 엘리스프(Elisp)는 상대적으로 인기는 적지만 좀 더 전통적인 명령형/객체 지향 언어를 사용했다면 이맥스(Emacs)가 지금처럼 강력한 확장성을 갖출 수 있었을지 의문입니다. LISP를 그토록 훌륭한 언어로 만드는 것은 소스 코드와 데이터 구조는 본질적으로 하나이기 때문입니다. 사람이 읽는 LISP 소스 코드는 LISP가 데이터를 코드로 조작하는 방식과 거의 동일합니다. “데이터란 무엇인가?” 와 “코드란 무엇인가?” 란 질문 사이의 구분은 사실상 존재하지 않습니다.

'데이터는 코드', 매크로 시스템 그리고 임의의 함수에 조언(advise)할 수 있는 기능—즉, 원본 소스를 복사하거나 수정하지 않고 기존 코드의 동작을 변경할 수 있다는 점—은 사용자의 필요에 맞게 Emacs를 변경할 수 있는 전례없는 능력을 제공합니다. 대부분의 소프트웨어 프로젝트에선 코드 스멜이나 부실한 아키텍처로 간주될만한 것이 Emacs에선 장점입니다. 다른 사람이 작성한 소스 코드의 방대한 부분을 다시 작성하지 않고 사용자의 필요에 맞게 Emacs의 기존 루틴을 후크하거나 교체할 수 있기 때문입니다.

하지만, 이 책은 엘리스프(Elisp)에 대해 자세히 다루지 않습니다!! 이맥스(Emacs)는 기본 제공되는 엘리스프 입문 자료가 포함되므로 관심있다면 꼭 한 번 읽어보시길 추천합니다. 솔직히 말해서 여러분은 관심을 가져야 마땅합니다. LISP 언어는 아주 재미있는 언어이며 실용 환경에서 이런 강력한 언어를 배우고 활용하는데 더할나위 없이 좋은 방법입니다. 단지 괄호 때문에 겁먹진 마시기 바랍니다; 괄호는 사실 이 언어의 가장 큰 장점입니다.


*** Emacs as an Operating System

그림

Emacs는 반짝거리는 물건들로 가득찬 까치 둥지 같습니다. 만약 여러분이 Emacs를 처음 접하는 분이라면 제가 비유를 지나치게 확장했다고 생각할 수 있지만 Emacs는 ~M-x zone~ 으로 실행하는 스크린세이버, ~M-x dunnet~ 으로 실행하는 텍스트 어드벤처 게임, ~M-x tetris~ 로 실행하는 테트리스 클론, 본격적인 클라이언트-서버 모델이자 달 위상 계산기, ~M-x doctor~ 로 실행하는 심리 치료사, 여러 이메일 클라이언트, ASCII 아트를 그릴 수 있는 ~Artist Mode~; ~EXWM~ Emacs 기반 X 윈도우 매니저; 그리고 이 책을 읽을 수 있는 EPUB 리더인 ~nov~ 등이 포함된다는 점을 생각하시기 바랍니다.

Emacs를 실행하면 사실상 운영체제의 ABI와 저수준의 상호작용을 담당하는 작은 C 코어를 시작하는 것입니다. 여기엔 파일 시스템과 네트워크 접근, 화면에 무언가 그리거나 터미널에 제어 코드를 출력하는 것 같은 일상적인 작업도 포함됩니다.

하지만, Emacs의 초석은 elisp 인터프리터입니다!! 이것이 없다면 Emacs도 존재할 수 없습니다!! 이 인터프리터는 낡고 구식이라 점점 늘어나는 사용자의 요구를 감당하기에 힘겨워 합니다. 현대의 Emacs 사용자들은 이런 소박한 인터프리터에 너무나 많은 것을 기대합니다. 속도와 비동기 처리가 대표적인 쟁점 사항입니다. 인터프리터는 단일 스레드로 실행되므로 부하가 큰 작업은 UI 스레드를 잠급니다. 하지만, 해결책은 항상 있습니다. 문제는 다양하지만 사람들이 좀 더 정교한 패키지를 작성하는 것을 막진 못합니다. Emacs 28의 출시와 함께(그리고 사용 중인 Emacs 인스턴스가 이를 지원하도록 컴파일된 경우) 사용하는 모든 Elisp 코드는 네이티브 코드로 컴파일되므로 상당한 속도 향상을 가져옵니다.

엘리스프(Elisp)를 작성할 때 여러분은 단순히 모든 것에서 격리된 샌드박스에서 실행되는 코드 조각을 작성하는 것이 아닙니다. 여러분은 살아있는 시스템 즉, 운영체제에서 실행되는 운영체제를 변경하는 것입니다. 여러분이 변경하는 모든 변수와 호출하는 모든 함수는 텍스트를 편집할 때 사용하는 바로 그 인터프리터에 의해 실행됩니다.

Emacs는 거대하고 가변적인 상태 그 자체로 해커들에겐 꿈같은 존재입니다. 그런 단순함은 축복이자 저주입니다. 실행 중인 함수를 재정의할 수 있고 변수를 마음대로 변경할 수 있으며 언제든지 시스템 상태를 조회할 수 있습니다. 이런 상태는 Emacs가 키보드부터 네트워크 스택에 이르는 이벤트에 반응함에 따라 혹은 키를 누를 때마다 변화합니다. 또한, Emacs는 문서 그 자체로 자체 설명적입니다. 이렇게 처리할 수 있는 편집기는 없습니다. 그에 근접한 편집기조차 없습니다.

그런데도 Emacs는 충돌하지 않습니다. 엄밀히 말해서 Emacs는 충돌하지 않는다는 사실을 증명하는 가동 시간 카운터가 있습니다(~M-x emacs-uptime~)—몇 달 동안 가동되는 경우도 드물지 않습니다.

따라서, Emacs에 어떤 질문을 던질 때—나중에 그 방법을 보여드리지만—여러분은 Emacs의 현재 상태가 어떤지 묻는 셈입니다. 이 때문에 Emacs는 훌륭한 Elisp 디버거를 갖추고 있으며 Emacs 인터프리터와 상태의 모든 측면에 제한없이 접근할 수 있습니다. 또한, 뛰어난 코드 완성 기능도 갖추고 있습니다. LISP 표현식을 만날 때마다 Emacs에게 이를 평가할 수 있으며 Emacs는 숫자 더하기부터 변수 설정, 패키지 다운로드까지 모든 작업을 수행합니다.


*** Extensiblility
확장성도 중요하지만 Emacs가 제공하는 가능성의 범위를 모른다면 중요성을 강조하기 어렵습니다. 여기선 Emacs가 무엇을 처리할 수 있는지 좀 더 중요하게는 Emacs가 사람들에게 무엇을 가능하게 해주는지에 대한 몇 가지 예시만 담았습니다.

- *A speech interface for the blind*: 지난 25년 동안 =Emacspeak= 는 시각 장애가 있는 Emacs 사용자들에게 화면에 표시된 내용을 이해하는 음성 인터페이스를 통해 Emacs 및 주변 환경과 상호작용할 수 있는 방법을 제공했습니다. Emacspeak는 소스 코드의 다양한 구문 요소를 반영하거나 레이아웃, 글꼴, 그래픽 아이콘을 강조하기 위해 음성 엔진의 음성 특성으로 변경합니다.

시각 장애가 있는 Emacs 사용자에게 Emacspeak은 이메일이나 웹 브라우징 같은 Emacs의 다양한 도구를 사용해서 작업할 수 있게 해준 생명의 끈과 같은 존재입니다. 이런 기능이 25년 동안 지속됐다는 사실도 인상적이지만 이런 소프트웨어를 지원할 수 있는 Emacs의 능력이야말로 감동 그 자체입니다.

- *Remote file editing*: Emacs의 =TRAMP= 를 사용하면 SSH, FTP, Docker, rclone, rsync 등 다양한 네트워크 프로토콜을 통해 원격 파일을 마치 로컬 파일처럼 매끄럽게 편집할 수 있습니다.

- *Shell access*: Emacs는 ANSI를 지원하는 내장 터미널 에뮬레이터가 있으며 bash 같은 셸을 감싸는 Emacs 래퍼 그리고 전적으로 Elisp로 작성된 셸인 =Eshell= 이 포함됩니다.

- *ORG mode*: 할 일 관리, 일정 관리, 프로젝트 계획, 리터러시 프로그래밍, 메모 작성(그 외 다양한 기능!)을 지원하는 통합 애플리케이션입니다. 이 앱은 역대 최고의 텍스트 기반 일정 관리 도구로 널리 인정받고 있으며 이보다 더 놀라운 점은 사람들이 이 앱을 사용하기 위해 Emacs로 전환한다는 사실입니다.

- *Symbolic Calculator*: 역-폴란드 표기법(RPN) 계산기로 기호 대수, 임의 정밀도 연산, 사용자 정의 함수, 행렬 및 단위 기반의 수학 연산 등 다양한 기능을 지원합니다.

- *Music Player*: Emacs 멀티미디어 시스템(EMMS)은 대화형 미디어 브라우저이자 음악 플레이어입니다.

- *And much more*: 거의 모든 프로그래밍 환경에 대한 공식 또는 비공식 지원; 내장 매뉴얼 페이지 및 인포 리더; 정교한 디렉터리 및 파일 관리자; 대부분의 버전 관리 시스템에 대한 원활한 지원; 그리고 크고 작은 수백 가지 기타 기능이 포함됩니다.



** Important Conventions
진행하기 전에 몇 가지 중요한 Emacs 관례를 설명하겠습니다. 이런 관례는 반드시 외우거나 의문이 생길 때마다 이 페이지를 다시 찾아보는 것이 중요합니다. 이런 관례는 이 책과 다른 곳에서 반복 등장하며 방대한 Emacs의 내부 문서를 제대로 활용하려면 이를 숙지하는 것이 무엇보다 중요합니다.

이 목록은 Emacs 혹은 이 책에서 사용하는 관례의 모든 것을 망라한 것이 아닙니다. 책 전체에 구체적인 용어와 개념을 소개하지만 일부 용어는 특정 주제를 초월하므로 알아두는 것이 중요합니다.


*** The Buffer
대부분의 텍스트 편집기와 IDE는 파일 기반입니다. 즉, 파일의 텍스트를 표시하거나 파일에 저장할 뿐입니다. 그게 전부입니다!! Emacs에서 모든 파일은 버퍼지만 모든 버퍼가 파일은 아닙니다!! 로그 파일에서 가져온 텍스트 조각을 임시로 저장하거나 텍스트를 조작하거나 그 밖의 어떤 이유로든 일회성 작업 공간이 필요하면 그냥 새로운 버퍼를 생성하고 사용하면 됩니다. Emacs는 파일 이름을 묻는 번거로움을 주지 않습니다. 하지만, 이런 버퍼는 Emacs 내에서만 존재합니다!! 따라서, 이를 영구적으로 유지하려면 디스크 파일로 명시적으로 저장해야 합니다.

Emacs는 버퍼를 단순히 텍스트 편집에 사용하는 것이 아닙니다. 버퍼는 마치 I/O 장치처럼 작동해서 bash 같은 셸이나 심지어 Python 같은 다른 프로세스와 통신할 수 있습니다.

Emacs 명령 대부분은 버퍼를 대상으로 작동합니다. 예를 들어, Emacs에게 검색 및 바꾸기를 지시하면 실제로는 버퍼에서 검색 및 바꾸기를 수행합니다. 현재 작성 중인 활성 버퍼일 수도 있고 임시 복제본일 수도 있습니다. 여러분이 생각할 수 있는 불투명한 폐쇄된 데이터 구조가 아닙니다. Emacs에선 버퍼가 데이터 구조입니다. 이는 매우 강력한 개념입니다. 왜냐하면, Emacs에서 이동하거나 편집할 때 사용하는 명령어들은 항상 elisp 내부에서 사용하는 명령어와 동일하기 때문입니다. 따라서, 일단 Emacs의 명령어를 익히면 간단한 함수 호출을 통해 직접 손으로 처리하는 작업을 모방할 수 있습니다.


*** The Window and the Frame
버퍼는 화면에 창으로 표시됩니다. 하지만, Emacs에서 창이란 단순히 프레임의 일부를 타일 형태로 나눈 것에 불과하며 이는 대부분의 윈도우 매니저에서 창이라 부르는 것과 같습니다. Emacs는 그 반대인데 네, 정말 혼란스럽습니다.

그림

위의 스크린샷을 보면 두 개의 창과 하나의 프레임이 보입니다. 프레임은 하나 이상의 창을 가질 수 있으며 창은 정확히 하나의 버퍼를 가집니다. 따라서, 버퍼가 사용자에게 표시되려면 창으로 보여야 하며 창을 사용자에게 표시하려면 프레임에 있어야 합니다.

#+BEGIN_QUOTE
[!NOTE]
*참고*:
이것은 마치 프레임이 달린 물리적인 창문이라 생각해야 합니다. 프레임은 창유리로 이루어져 있습니다.
#+END_QUOTE

Emacs는 원하는만큼 프레임을 자유롭게 생성할 수 있으며 각 프레임을 여러 개의 창으로 분할하거나 배열할 수 있습니다. 대형 모니터를 사용한다면(요즘 누가 그렇지 않겠습니까?), Emacs의 타일링 시스템을 활용해서 화면에 여러 개의 버퍼를 표시하는 것은 유용합니다.


*** Modeline, Echo Area, and Minibuffer

그림

위의 그림은 터미널 모드 Emacs 세션입니다. Emacs는 모드라인으로 Emacs 자체와 현재 열려있는 버퍼에 대한 정보를 표시합니다. 모드라인은 다음과 같습니다:

#+BEGIN_SAMPLE
-UUU:**--F3 *scratch* All L4 (Lisp Interaction) --
#+END_SAMPLE

좁은 공간에 많은 정보가 담겨져 있습니다. 주목할 부분은 버퍼 이름과 메이저 모드입니다. 이 경우 버퍼 이름은 =*scratch*= 이며 메이저 모드는 =Lisp Interaction= 입니다. 대부분의 편집기는 상태표시줄(status bar)이란 이와 유사한 개념이 있습니다.

모드라인(modeline)은 문서의 비율, 현재 실행 중인 함수나 클래스, 사용 중인 소스 제어 리비전이나 브랜치 등 다양한 정보를 표시할 수 있습니다.

미니버퍼(minibuffer)는 모드라인 하단에 위치하며 오류 및 일반 정보를 표시합니다:

#+BEGIN_SAMPLE
-UUU:**--F3 *scratch* All L4 (Lisp Interaction) --
M-x insert-hello-world
#+END_SAMPLE

이 경우 저는 Emacs 확장 명령을 호출했습니다. 이 기능은 ~M-x~ 로 표시하며 이에 대해서는 키에 관한 장에서 자세히 다루겠습니다. 그리고 ~M-x~ 프롬프트에 ~insert-hello-world~ 명령을 입력했습니다.

에코 영역(echo area)과 미니버퍼는 화면상 동일한 위치를 공유합니다. 미니버퍼는 일반 버퍼와 거의 동일합니다. 대부분의 편집 명령을 사용할 수 있으며 한 줄로 구성된 미니버퍼는 필요에 따라 여러 줄로 자동 확장됩니다. 이것이 바로 Emacs와 소통하는 주요 수단입니다. 문자열을 검색하려면 미니버퍼에 검색할 문자열을 입력합니다. 미니버퍼는 필요한 내용을 찾도록 도와주는 자동 완성 메커니즘도 지원하며 이는 아마 여러분이 가장 자주 사용할 필수 도구입니다.


*** The Point and Mark
‘포인트(point)’ 는 캐럿(caret)이나 커서(cursor)를 의미하는 또 다른 표현입니다. Emacs 문서에서 ‘포인트’ 와 ‘커서’ 를 다소 일관성없이 사용하므로 두 용어 모두 등장합니다. 그럼에도 불구하고 포인트 자체는 버퍼의 현재 위치를 의미합니다. 이 책은 =█= 문자로 표시합니다. 각 버퍼는 포인트의 위치를 개별 추적하므로 버퍼를 전환해도 포인트 위치는 기억됩니다.

#+BEGIN_QUOTE
[!NOTE]
*참고*:
Emacs에서 “현재 버퍼” 를 자주 이야기하는데 이 용어는 두 가지 의미를 가집니다.
현재는 그 중 하나만 관심가질 만한데 커서가 위치한 버퍼를 의미합니다.
(다른 경우는 기본적으로 동일하지만 elisp 프로그래밍으로 버퍼를 변경한 경우입니다.)

포인터가 있는 버퍼가 현재 버퍼인 이유는 바로 그 버퍼에 글을 쓰거나 커서를 움직이기 때문입니다.
한 번에 하나의 버퍼만 현재 버퍼가 될 수 있으며 바로 이 버퍼가 포인터를 가집니다.
#+END_QUOTE

Emacs에서 포인트는 단순히 사용자가 입력한 문자가 화면 어느 위치에 표시되는지 시각적으로 표시하는 역할을 넘어 좀 더 많은 용도로 사용됩니다. 포인트는 또한 ‘포인트’ 와 ‘마크’ 로 불리는 한 쌍의 요소 중 하나입니다. 포인트와 마크는 영역의 경계를 의미하며 여기서 영역이란 현재 버퍼의 연속된 텍스트 블록을 의미합니다. 다른 편집기에선 이를 선택 영역이나 하이라이트라고 부릅니다. 대부분의 편집기는 영역의 시작점과 끝점을 가리키는 구체적인 명칭이 없지만 이맥스는 있으며 ‘선택 영역과 영역’ 섹션에서 그 이유에 대해 자세히 설명합니다.

#+BEGIN_QUOTE
[!NOTE]
*팁*:
역사적으로 Emacs는 화면에 가시적인 영역을 표시하지 않으므로 사용자는 마음속으로 이를 시각화해야 했습니다.
Emacs는 오랫동안 '일시적 마크 모드(TMM)' 라 불리는 시각적 영역 기능을 지원했습니다. 이 기능은 기본으로 활성화됩니다.
놀랍게도 TMM을 사용하지 않는 것도 가치가 있겠지만 이에 대해서는 나중에 자세히 다루겠습니다.
#+END_QUOTE

하지만, 포인트와 마찬가지로 마크도 겉으로 보이는 것 이상의 의미를 지닙니다. 마크는 해당 지역의 경계를 표시하는 역할도 처리하지만 버퍼의 다른 곳에서 다시 돌아올 수 있는 이정표 역할도 처리합니다. 마크도 눈으로 보이지 않습니다.


***  Killing, Yanking and CUA
표준 사용자 인터페이스에서 가장 많이 벗어난 첫 번째 요소이자 초보자에게 가장 거부감을 주는 것은 Emacs의 클립보드 시스템입니다. 잘라내기, 복사, 붙여넣기는 보편적으로 ~Ctrl+x~ 또는 ~Shift+Delete~, ~Ctrl+c~ 또는 ~Ctrl+Insert~ 그리고 ~Ctrl+v~ 또는 ~Shift+Insert~ 로 알려져 있습니다.

Emacs는 이런 키와 용어가 크게 다릅니다!!: 'killing' 은 잘라내기, 'yanking' 은 붙여넣기, 복사는 어색하지만 'kill ring에 저장하기' 라고 불립니다(비공식적으로는 그냥 'copy' 라고 합니다).

이는 앞서 언급했듯이 역사적인 이유입니다. 대부분의 키와 용어는 IBM의 =Common User Access= (CUA) 및 Apple에서 유래했습니다. 하지만, CUA는 1987년 도입됐는데 이 시기는 Emacs가 자신만의 용어와 표준을 확립한 지 수 년이나 지난 이후입니다.

'선택 호환 모드' 섹션에서 저는 몇 가지 주의 사항과 현대적인 클립보드 키로 전환하는 방법과 또한 그렇게 해선 안되는 이유를 설명합니다. 대신, 텍스트 편집에 Emacs 시스템이 좀 더 나은 이유도 보여드리겠습니다.


*** emacs.d, init.el, and emacs
Emacs 사용자들이 가장 즐겨하는 취미 중 하나는 자신의 작업을 좀 더 편리하게 만드는 작은 코드 조각이나 사용자 설정을 다른 Emacs 사용자들과 공유하는 것입니다.

예전에는 이런 설정들은 =.emacs= 라는 단일 파일에 저장했지만 리눅스는 =~/.emacs.d/init.el=, 윈도우는 =%HOME%\init.el= 파일에 사용자 설정을 보관합니다. 현재 Emacs는 파일 시스템에 보다 많은 파일을 생성하므로 홈 디렉터리가 복잡해지는 것을 방지하기 위해 이 파일들은 =.emacs.d= 라는 전용 디렉터리에 보관됩니다.

#+BEGIN_QUOTE
[!NOTE]
*XDG Support in Emacs 27*:
Emacs 27 이상은 이를 지원하는 리눅스 플랫폼에서 사용자 설정을 =~/.config/emacs/init.el= 에 저장하는 XDG 표준을 지원합니다.
#+END_QUOTE

따라서, 사람들이 자신의 init 파일이나 “.emacs 파일” 을 이야기하거나 해당 파일에 무언가 추가하라고 말할 때는 바로 그 파일을 의미합니다. Emacs를 처음 사용하면 =~/.emacs.d/init.el= 파일을 사용합니다. 이 파일에 내용을 추가한 후에는 Emacs가 이를 적용하도록 지시해야 합니다. 이를 적용하는 방법도 여러 가지로 ‘Elisp 코드 평가하기’ 섹션에서 보다 자세히 설명하지만 초보자는 단지 Emacs를 종료했다가 다시 시작하는 방법을 권장합니다.

#+BEGIN_QUOTE
[!NOTE]
*참고*:
요즘엔 Emacs 스타터 키트가 흔해졌습니다.
이것은 Emacs에 커뮤니티 차원에서 추가한 것으로 다양한 수정이나 심지어 타사 패키지를 한데 묶어 제공합니다.
만약, 스타터 키트를 사용한다면 수정 사항을 어디 저장하는지 확인하려면 해당 문서를 읽어봐야 합니다.
#+END_QUOTE

Emacs는 변경 사항을 자동으로 저장하지 않습니다!! Emacs에서 변경 사항을 유지하려면 ‘Customize’ 인터페이스로 저장해야 합니다. 즉, 유지하려는 변경 사항은 사용자가 init.el 파일에 직접 저장해야 합니다. 마찬가지로, 실수로 Emacs에 오류가 발생했거나 원치않는 변경을 가한 경우 단순히 Emacs를 종료한 후 다시 시작합니다.


*** Major Modes and Minor Modes
Emacs의 메이저 모드는 버퍼의 동작 방식을 제어합니다. 예를 들어, 파이썬 코드를 편집하려고 Emacs에서 /helloworld.py/ 파일을 열면 Emacs는 파일 확장자를 메이저 모드와 매핑하는 중앙 집중식 레지스터를 통해 파이썬 파일임을 인식하고 파이썬 메이저 모드를 사용한다는 것을 알게 됩니다. 모든 버퍼는 항상 메이저 모드가 지정됩니다. 메이저 모드는 글꼴 잠금(구문 강조) 기능만 제공하고 특별한 기능이 없는 기본적인 형태일 수도 있고 그와 반대로 글꼴 잠금, 고급 들여쓰기 엔진, 특수 명령어 등을 제공하는 완전히 다른 형태일 수도 있습니다.

#+BEGIN_QUOTE
[!NOTE]
*참고*:
‘폰트 락킹(Font Locking)’ 은 Emacs의 구문 강조(syntax highlighting)를 지칭하는 용어이며
이는 폰트 락킹 엔진이 텍스트를 보기좋게 표시하기 위해 사용하는 속성(색상, 폰트, 텍스트 크기 등)의 집합인 ‘페이스(face)’ 로 구성됩니다.
Emacs의 용어인 ‘페이스’ 와 ‘폰트 락킹’ 은 다른 곳에서 흔히 볼 수 있는 용어보다 훨씬 먼저 등장했습니다.
#+END_QUOTE

다른 모드 명령어를 입력해서 언제든지 버퍼의 메이저 모드를 변경할 수 있습니다. Emacs의 파일 확장자 및 메이저 모드 레지스터 외에도 파일 확장자가 모호하거나 아예 없는 파일을 위한 또 다른 감지 시스템이 있습니다. Emacs는 파일 앞부분을 스캔해서 메이저 모드를 추측합니다. 드물게 Emacs가 잘못 판단할 경우도 있으므로 사용자가 직접 변경할 수도 있습니다.

버퍼는 오직 하나의 메이저 모드만 가질 수 있다는 점을 기억합니다. 반면, 마이너 모드는 일반적으로 일부(또는 모든) 버퍼에서 활성화할 수 있는 선택적인 추가 기능입니다. 한 가지 예로는 글을 작성할 동안 문법 검사를 수행하는 마이너 모드인 ~flyspellmode~ 가 있습니다.

메이저 모드는 항상 모드라인에 표시됩니다. 일부 마이너 모드도 모드라인에 표시하지만 대개 버퍼 자체나 사용자와의 상호작용 방식을 어떤 식으로든 변경하는 모드만 표시됩니다.
