* Chapter 5. The Theory of Editing

#+BEGIN_QUOTE
“An infinite number of monkeys typing into  
GNU Emacs would never make a good program.”  
– Linus Torvalds, Linux Kernel Coding Style Documentation
#+END_QUOTE

Emacs로 편집한다는 것은 Emacs에서 효율적으로 이동하는 방법을 배우는 것보다 어쩌면 좀 더 쉬울지 모릅니다. 대부분의 일상적인 편집 작업은 전문적인 명령어들을 간간이 사용하면서 텍스트를 작성하거나 삭제하는 것으로 이루어집니다. 그럼에도 불구하고 Emacs는 텍스트를 삭제하거나 킬 링(클립보드)을 사용하는 것 같은 평범한 작업조차 최적화되어 있습니다.

버퍼를 전환하거나 Emacs의 윈도우 시스템을 효과적으로 사용하는 방법을 배우게 된다는 점에서 먼저 이동 기능을 숙달하는 것이 좀 더 중요하다고 생각합니다. 그래서 이 책의 3분의 2가 지나기 전까지 텍스트 편집에 대해 전혀 다루지 않았습니다. 파일을 열고 저장하는 것 그리고 하던 작업을 놓치지 않고 Emacs로 이동하는 데 익숙해지면 그때서야 좀 더 고급 편집 개념을 다룰 준비가 된 것입니다.

이 장을 읽으면서 여전히 탐색 키(화살표 키, 페이지 업/다운 등)를 사용하더라도 괜찮습니다. 다만, Emacs의 이동 키가 그토록 효과적인 이유는 텍스트 편집 기능과 조화를 이루는 관계에 있기 때문에 그런 경험을 다소 단절된 느낌으로 받아들일 수도 있을 것입니다.

이 장에선 텍스트 편집 방법에 대해 다룹니다. 검색 및 바꾸기 같은 기본적인 기능, 킬 링(kill ring) 또는 클립보드 사용법, 매크로 사용법 그리고 텍스트 변환 도구 사용법이 포함됩니다.


** Killing and Yanking Text
다른 텍스트 편집기들은 단순히 텍스트를 잘라내는 것에 그치지만, Emacs는 텍스트를 ‘죽인다’ 고 표현합니다. ‘Killing, Yanking and CUA’ 섹션에서 언급했듯이 이런 용어는 기이할뿐만 아니라 대부분의 그래픽 사용자 인터페이스가 등장하기 훨씬 이전부터 사용되어 왔습니다.

#+BEGIN_QUOTE
*Discovering the Kill Commands* :  
여기에 나열되지 않은 다른 킬 명령을 찾으려면 Emacs의 ~apropos~ 기능을 사용하시기 바랍니다.
#+END_QUOTE

Emacs의 삭제 명령어는 이동 명령어와 동일한 구문 단위의 개념을 사용합니다. 이 중 일부는 키 대칭성도 공유하므로 삭제 명령어로 쉽게 전환할 수 있습니다.

| 키 바인딩             | 용도                |
|-----------------------+---------------------|
| ~C-d~                 | 문자 삭제           |
| ~<backspace>~         | 이전 문자 삭제      |
| ~M-d , C-<backspace>~ | 단어 삭제           |
| ~C-k~                 | 줄 나머지 부분 삭제 |
| ~M-k~                 | 문장 삭제           |
| ~C-M-k~               | S-표현식 삭제       |
| ~C-S-<backspace>~     | 현재 줄 삭제        |

위에서 눈에 띄는 것은 다음 문자를 삭제하는 ~C-d~ 와 같은 기능을 처리하지만 역방향으로 삭제하는 ~<backspace>~ 입니다. 그 외의 모든 명령어는 텍스트를 삭제하지 않고 제거합니다. 이런 차이는 중요합니다. 삭제된 텍스트는 킬 링에 저장되지 않는 반면 제거된 텍스트는 킬 링에 저장되기 때문입니다.

*숫자 인수와 음수 인수* :  이동 명령어와 마찬가지로 숫자 인수를 사용해서 한 번에 여러 유닛을 제거할 수 있습니다. 작업 속도를 유지하려면 호출하려는 제거 명령어의 수식자와 동일한 숫자 수식자를 사용합니다. ~C-M-k~ 로 3개의 s-표현식을 제거하려면 ~C-M-3 C-M-k~ 를 입력합니다.

부정 인수는 이동 명령어와 마찬가지로 방향을 반대로 바꿉니다. 오해하진 마시기 바랍니다. 이 기능은 생각보다 훨씬 더 실용적입니다!! 저는 종종 무언가 작성하고 나서야 그것을 다른 곳으로 옮기거나 어쩌면 완전히 삭제한다는 것을 깨닫곤 합니다.

다음 예제를 살펴보겠습니다:

#+begin_src 
s = make_upper_case(“hello, world!”█)
#+end_src

~C-M-- C-M-k~ 입력 후:

#+begin_src 
s = make_upper_case(█)
#+end_src

Emacs는 일반화된 삭제 및 복사 명령도 있습니다. 자주 사용하므로 기억하면 좋습니다:

| 키 바인딩 | 킬링 용도                                                                      | 클립보드 |
|-----------+--------------------------------------------------------------------------------+----------|
| ~C-w~     | 영역 삭제                                                                      | 잘라내기 |
| ~M-w~     | 삭제 링에 복사                                                                 | 복사     |
| ~C-M-w~   | 삭제 링에 추가                                                                 |          |
| ~C-y~     | 마지막 삭제 내용 붙여넣기                                                      | 붙여넣기 |
| ~M-y~     | 삭제 링을 순환하며 붙여넣은 텍스트를 대체합니다. 삭제 링 기록 표시 (Emacs 28)  |          |


*** Killing versus Deleting
‘킬(kill)’ 과 ‘삭제(delete)’ 의 차이점은 많은 Emacs 초보자를 혼란스럽게 만듭니다. 대부분의 편집기는 선택된 텍스트에 독점적으로 적용되는 클립보드 명령과 텍스트를 삭제하는 명령 사이에 명확한 구분이 있습니다. Emacs는 ~C-d~ 나 ~<backspace>~ 같은 몇 가지 예외를 제외하고 모든 명령은 텍스트를 킬 링(kill ring)으로 이동시킵니다. 만약 Emacs를 처음 접한다면 이런 점이 매우 혼란스럽고 심지어 분노를 일으킬 수 있습니다. 다른 편집기들은 사용자가 명시적으로 지시하지 않는 한 클립보드 내용을 건드리지 않지만 Emacs는 그렇게 합니다. 하지만, 일단 익숙해지면 이는 훌륭한 기능입니다.

Emacs의 킬 명령은 다음의 다섯 가지 간단한 규칙으로 요약할 수 있습니다:

*연속 삭제 시 킬 링에 추가* : 모든 삭제 명령은 마지막 명령이 삭제 명령일 때만 킬 링에 추가됩니다. 즉, 킬 링의 텍스트에 추가된다는 뜻입니다. 이동하거나 텍스트를 입력하거나 명령을 실행하는 등의 방식으로 이런 순환을 끊으면 다음 삭제 명령은 킬 링에 새로운 항목을 생성합니다.

예를 들어, ~M-d M-d M-d~ 를 입력해서 단어 세 개를 연속 삭제하면 다음에 텍스트를 복사할 때 킬 링에는 삭제한 세 단어가 저장됩니다. 만약 ~M-d M-d M-d~ 를 입력한 후 ~C-n~ 으로 다음 줄로 이동해서 또 다른 세 단어를 삭제하면 킬 링에서 불러오는 것은 마지막 세 단어 뿐이며 여섯 개가 아닙니다!! 이동 명령으로 이런 순환을 끊었기 때문입니다. 이런 방식에 익숙해지려면 시간이 조금 걸릴 수 있습니다. 하지만, 텍스트 먼저 선택할 필요가 없으므로 좀 더 스마트한 작업 방식입니다.

*킬 링은 많은 항목을 저장할 수 있습니다* : 실행 취소 언두 링과 마찬가지로 킬 링에 저장된 정보를 쉽게 잃어버릴 염려가 없습니다. 무언가 삭제했다가 나중에 첫 번째 삭제 항목을 다른 삭제 항목으로 대체해도 첫 번째로 삭제한 항목을 잃은 것이 아닙니다. 따라서, 쉽게 복구할 수 있으며 사실 텍스트를 다시 작성할 때 킬 링은 종종 스니펫을 임시 저장하는 보조 “저장소” 로 사용됩니다.

하지만, 킬 링은 최대 용량이 있습니다. 즉, 가장 오래된 항목들이 자동 삭제되기 전까지 저장할 수 있는 텍스트 셀의 수를 의미하며 ~kill-ring-max~ 변수를 변경해서 이를 사용자 정의할 수 있습니다. 하지만, 기본값이 비교적 넉넉하므로 개인적으로 이 설정을 별도로 변경할 필요는 없었습니다.

*킬 링은 전역적입니다* : Emacs의 모든 버퍼에 공유됩니다. 즉, 킬 링의 모든 항목을 어디서나 사용할 수 있습니다.

*킬 링은 삭제 기능입니다* : 제가 Emacs를 처음 접했을 때 삭제 명령어가 없다는 점이 이상했습니다. 하지만, 이는 킬 링이 텍스트를 위한 클립보드인 동시에 원치않는 텍스트를 버리는 저장소 역할도 처리하기 때문입니다. 텍스트를 직접 삭제하는 명령은 거의 없습니다. Emacs는 실수로 데이터를 잃을 가능성 높은 상황에 사용자를 놓아둘 일이 거의 없으므로 모든 범위 지정 명령은 텍스트를 킬 링으로 보냅니다. 하지만, 그것도 괜찮습니다. 킬 링은 유한하지만 여러분이 신경쓸만한 용량보다 훨씬 더 큽니다.

킬 링이 소중하다는 생각은 버리세요! 그렇지 않습니다.

*마킹은 불필요합니다* : 텍스트든 산문이든 여러분이 처리하는 작업 대부분은 구문 단위를 다루는 작업이란 것을 알게 됩니다. 먼저 ~M-@~ 로 세 단어를 마킹한 다음 ~C-w~ 로 삭제하는 것보다 ~M-d~ 를 세 번 연속 눌러 세 단어를 삭제하는 것이 훨씬 더 빠릅니다. 

하지만, 두 가지 예외가 있습니다:

- 영역을 복사(~M-w~)할 경우 먼저 영역으로 지정한 다음 복사하는 것이 좀 더 빠릅니다.
- 구문 단위의 배수가 아닌 불규칙한 모양의 영역을 삭제하거나 복사할 경우

#+BEGIN_QUOTE
*Appending to the kill ring* :  
때때로 킬 링의 기존 내용 뒤에 새로운 내용을 추가할 때가 있습니다.  
이는 버퍼의 서로 다른 부분들을 킬할 때 그 부분들이 하나의 연속된 영역이나 일련의 킬 명령어가 아닐 때 자주 발생합니다.

이를 수행하려면, ~C-M-w~ 를 입력하면 Emacs가 에코 영역에 다음 명령어가 킬 명령어일 경우 킬 링에 내용을 추가할 것이라고 알려줍니다.
#+END_QUOTE


**** Killing Lines
전체 줄을 삭제하려면 ~C-S-<backspace>~ 를 사용합니다. 하지만, 이 명령은 터미널 에뮬레이터의 기술적인 한계로 터미널 모드 Emacs는 작동하지 않습니다!!

다른 방법이자 제가 사용하는 방법은 활성 영역을 삭제하는 명령어인 ~C-w~ 의 동작을 수정해서 영역이 활성화되지 않았을 때 커서가 위치한 현재 줄을 삭제하는 방법입니다. Emacs에 이 기능을 사용하려면 ~whole-line-or-region~ 패키지를 설치할 것을 권장합니다:

#+begin_src 
~M-x package-install whole-line-or-region~
#+end_src

마찬가지로 줄 끝까지 삭제하는 ~C-k~ 도 있습니다. 이 동작은 대부분의 사람들이 예상하는 것과 다릅니다: ~C-k~ 는 줄 끝의 개행 문자는 삭제하지 않습니다! 이는 버그가 아닌 기능입니다. 텍스트를 다른 곳으로 옮길 때 개행 문자가 필요한 경우는 거의 없습니다. 만약 개행 문자를 삭제하지 않으면 킬 링에 여분의 줄바꿈 한 개가 생기고 버퍼는 줄바꿈 하나가 부족하게 됩니다. 이와 반대로 커서가 줄 끝에 있을 때는 줄바꿈 기호만 삭제됩니다. 따라서, ~C-k~ 를 두 번 누르면 텍스트와 줄바꿈 모두 삭제되어 줄바꿈을 포함할 때 두 가지를 같은 텍스트 셀에 넣기 쉽습니다.

원한다면 ~kill-whole-line~ 옵션을 사용자 정의해서 ~C-k~ 가 줄바꿈을 영구적으로 삭제하도록 강제할 수 있습니다. 하지만, 이를 변경하기 전에 기본 설정부터 사용하시길 권장합니다.


*** Yanking Text
Emacs의 킬 링에 저장된 텍스트를 붙여 넣으려면 킬 링에서 텍스트를 불러와야 합니다.

#+BEGIN_QUOTE
*Terminology* :  
'Paste' 는 Emacs에서 널리 쓰이는 용어가 아닙니다.  
하지만, 다른 곳에선 이 단어를 매우 흔하게 사용하므로  
–다른 몇 가지 단어와 마찬가지로–apropos 를 사용할 때  
Emacs는 이를 yank 의 동의어로 취급합니다.
#+END_QUOTE

알아두면 좋은 두 가지 yank 명령어는 다음과 같습니다:

| 키 바인딩 | 용도                                                                                    | 클립보드 |
|-----------+-----------------------------------------------------------------------------------------+----------|
| ~C-y~     | 마지막으로 복사한 내용을 붙여넣기                                                       | 붙여넣기 |
| ~M-y~     | 킬 링을 순환하며 복사한 텍스트를 대체합니다. 킬 링 기록을 표시할 수 있습니다 (Emacs 28) |          |

*yank 명령은 예상대로 작동합니다* : 활성 버퍼의 지정한 위치에 킬 링에 저장된 현재 항목을 삽입합니다. yank 명령을 반복 호출하면 동일한 텍스트를 삽입합니다.

앞서 언급했듯이 킬 링은 언두 링과 마찬가지로 링 형태를 띄며 이전에 삭제한 내용을 기억하므로 이를 순차적으로 탐색할 수 있습니다.

킬 링을 순차적으로 탐색하는 방법은 간단합니다:

1. 얹저넣을 텍스트가 나타날 위치에서 ~C-y~ 를 누릅니다.
2. 다른 명령을 실행하지 않은 상태에서(이동이나 텍스트 편집 포함) ~M-y~ 를 입력해서 Emacs의 킬 링을 거꾸로 탐색합니다.

Emacs 28부터 ~M-y~ 를 사용해서 킬 링을 탐색하거나 얹저넣을 항목을 선택할 수 있습니다. 이 기능은 방금 ~C-y~ 로 얹기(yank)를 호출하지 않은 경우만 사용할 수 있습니다. 즉, ~M-y~ 의 기본 동작은 킬 링의 기록을 표시하는 것입니다.

** Transposing Text
텍스트 전치란 두 개의 구문 단위를 서로 위치를 바꾸는 행위입니다. 언뜻 보기엔 유용성이 제한적이라 생각할 수 있지만 사실 이는 실질적인 문제를 해결하며 이를 숙달하면 결코 후회하지 않습니다. 산문에서 단어의 순서를 바꾸거나 함수의 인수를 바꾸는 일은 흔히 발생하는 일입니다.

텍스트를 전치할 때는 텍스트를 이동하거나 삭제할 때와 동일한 방식으로 구문 단위를 사용해서 수행합니다:

| 키 바인딩                  | 용도                 |
|----------------------------+----------------------|
| ~C-t~                      | 문자 순서 바꾸기     |
| ~M-t~                      | 단어 순서 바꾸기     |
| ~C-M-t~                    | S-표현식 순서 바꾸기 |
| ~C-x C-t~                  | 줄 순서 바꾸기       |
| ~M-x transpose-paragraphs~ | 단락 순서 바꾸기     |
| ~M-x transpose-sentences~  | 문장 순서 바꾸기     |

전치(transpose) 명령을 호출하면 Emacs는 먼저 포인터의 위치를 확인한 후 사용자가 입력한 전치 명령에 따라 포인터를 둘러싼 두 개의 구문 단위를 서로 교환합니다. 이 경우 Emacs가 구문 단위를 정의하는 방식은 다소 복잡한데 이는 구문 단위의 정의가 현재 사용 중인 메이저 모드에 따라 결정되기 때문입니다.

음수 인자도 작동하며 숫자 인자도 작동하지만 예상하는 방식과 다릅니다. 전치 명령에 숫자 인자를 지정하면 포인트 앞쪽의 N번째 단위를 가져와(음수 인자도 함께 지정하지 않는 한 반대 순서가 됩니다) 해당 단위를 포인트 바로 앞의 구문 단위와 서로 교환합니다.


*** C-t : Transpose Characters
문자를 전치하면 커서 위치의 좌우 문자를 서로 바꿉니다:

~A█BC~

~C-t~ 를 누른 후:

~BA█C~

포인터가 한 칸 앞으로 이동하므로 ~C-t~ 를 반복해서 문자를 오른쪽으로 “끌어올” 수 있습니다:

~BCA█~

이 규칙의 중요한 예외 중 하나는 줄 끝에서 작업할 때입니다. 이때 ~C-t~ 는 포인터 왼쪽의 두 문자를 서로 바꿉니다:

~BCA█~

~C-t~ 입력 후:

~BAC█~

이런 비대칭성은 오타가 발생했을 때 이를 수정하기 유용한 방법입니다. ~C-t~ 를 사용해서 잘못 입력된 문자를 수정하면 두 문자 모두 삭제한 후 다시 입력하는 수고를 덜어주므로 시간을 절약할 수 있습니다.


*** M-t : Transpose Words
~M-t~ 키를 사용해서 두 단어를 뒤바꾸는 기능은 다음과 같이 단순한 텍스트일 경우는 예상대로 작동합니다:

~Hello █World~

~M-t~ 실행 후:

~World Hello█~

~C-t~ 로 문자를 뒤바꾸는 것과 마찬가지로 커서는 ~M-f~ (~M-x forward-word~)를 입력한 것처럼 앞으로 이동하며 이는 단어를 오른쪽으로 “끌어당길” 수 있음을 의미합니다. ~M-t~ 가 진가를 발휘하는 곳은 소스 코드에서 사용할 때입니다. “단어의 정의란 무엇인가?” 섹션에서 설명했듯이 ~M-f~ 와 ~M-b~ 이동 명령은 이동 방향의 기호를 무시하며 ~M-t~ 도 이와 동일한 방식으로 동작합니다.

다음과 같은 Python 코드 예제로 살펴보겠습니다. 다음과 같은 딕셔너리(키-값 해시 맵)가 있습니다:

#+BEGIN_SRC 
names = {
  ‘Jerry’:█ ‘Seinfeld’,
  ‘Cosmo’: ‘Kramer’,
}
#+END_SRC

커서가 키와 값 사이에 있을 때 ~M-t~ 를 호출하면 마법같은 일이 일어납니다:

#+BEGIN_SRC
names = {
  ‘Seinfeld’: ‘Jerry’,
  ‘Cosmo’: ‘Kramer’,
}
#+END_SRC

보시다시피 키와 값의 위치가 바뀌지만 심볼은 제자리에 남습니다. 이 작업을 다시 반복하면 Emacs는 계속해서 Jerry 와 Cosmo 의 위치를 바꿉니다; 한 번 더 반복하면 Jerry 와 Kramer 의 위치를 바꿀 수 있습니다.

#+BEGIN_QUOTE
*How Transposing Actually Works* :  
~M-t~ 명령어는 본질적으로 ~M-x forward-word (M-f)~ 명령어와 밀접하게 연관되어 있습니다.

간단히 말해 Emacs는 ~M-f~ 를 두 번 호출합니다.  
한 번은 음수 인수를 사용해서 왼쪽 단어를 바꾸고 또 한 번은 음수 인수없이 호출해서 오른쪽 단어를 바꿉니다.

실제로는 좀 더 복잡하지만 큰 차이는 없습니다. 이 이론은 테스트하기 쉽습니다.

원래 위치에서 ~M-- M-f~ 와 ~M-f~ 를 호출합니다. 호출에 커서를 원래 위치로 되돌리는 것을 잊지마시기 바랍니다.  
그러면 ~M-t~ 가 전치할 단어의 좌우 끝을 확인할 수 있습니다.
#+END_QUOTE

이전에 Emacs의 단어 이동 동작이 이해되지 않았다면 이젠 좀 더 이해됐기를 바랍니다. 모든 사람의 취향에 맞는 것은 아니지만 이동, 삭제, 위치 바꾸기 기능 전반에 걸쳐 일관성이 있습니다.

이 기능은 산문에도 그대로 작동합니다:

~Hello,█ World!~

~M-t~ 를 누른 후:

~World, Hello█!~


*** C-M-t : Transpose S-expressions
~C-M-t~ 를 사용해서 균형잡힌 표현식인 S-표현식도 전치할 수 있으며 ~M-t~ 를 이용한 단어 전치와 마찬가지로 작동 원리는 동일합니다. 전치 함수가 좌우 끝을 찾을 때 앞뒤 방향에 동일한 원리가 적용됩니다.

다음과 같은 LISP 코드 조각을 살펴보겠습니다:

#+begin_src 
~(/ (+ 2 n)█ (* 4 n))~
#+end_src

이 코드에 ~C-M-t~ 를 호출하면 두 표현식의 위치가 바뀝니다:

#+begin_src 
~(/ (* 4 n) (+ 2 n)█)~
#+end_src

앞서 설명한 ~M-t~ 와 마찬가지로 개념은 동일하지만 적용 방식이 다릅니다. 하지만, ~C-M-t~ 는 ~M-x forward-sexp~ (~C-M-f~)와 유사하게 균형잡힌 표현식이 없을 경우 ~M-x transpose-word~ 의 역할을 수행합니다:

#+begin_src 
~Hello,█ World!~
#+end_src

그리고 ~C-M-t~ 적용 후에는 다음과 같이 됩니다:

#+begin_src 
~World, Hello█!~
#+end_src

하지만, 균형잡힌 표현식과 단어를 혼합하면 어떻게 되는지 살펴보겠습니다:

#+begin_src 
~Hello,█ (이름을 여기에 입력하세요)!~
#+end_src

~C-M-t~ 적용 후:

#+begin_src 
~(이름을 여기에 입력하세요), Hello█!~
#+end_src

따라서, ~C-M-t~ 는 예상대로 작동합니다. 이런 가능성은 코드에서 분명합니다:

#+BEGIN_SRC
ages = {
  ‘Seinfeld’:█ 34,
}
#+END_SRC

예상대로 Emacs는 해당 요소를 올바르게 전치합니다:

#+BEGIN_SRC
ages = {
  34: ‘Seinfeld’█,
}
#+END_SRC

이 동작은 ~M-t~ 와 다릅니다. 앞선 시나리오에 ~M-t~ 로 적용하겠습니다:

#+BEGIN_SRC
ages = {
  ‘34’: Seinfeld█,
}
#+END_SRC


결과는 확실히 다릅니다. Emacs는 단어를 바꾸지만 심볼은 그대로 남겨둡니다. 이는 Emacs가 단어와 단어 경계를 처리하는 방식과 일치합니다.


*** Other Transpose Commands
줄, 단락, 문장 같은 다른 구문 단위들도 순서를 바꿀 수 있지만 줄 순서를 바꾸는 것 외에는 나머지 기능들은 당장 배울 필요성을 느끼기엔 어렵다고 생각합니다. 단락과 문장 명령어는 단축키가 지정되어 않아서 사용하기 더 어렵습니다. 이 명령어들을 사용하려면 ~M-x~ 로 호출하는 방법 밖에 없습니다!!

하지만, ~C-x C-t~ 를 사용해서 줄을 재배열하는 것은 분명한 용도가 있습니다. 저는 줄바꿈에 기반으로 한 목록의 순서를 바꾸기 위해 이 명령을 자주 사용하며 프로그래밍에도 제 역할을 다한다고 생각합니다.


** Filling and Commenting
*** Filling
텍스트를 많이 작성하면 줄 길이가 일정 길이를 넘지않도록 수동으로 단락을 나눠야할 때가 있습니다. Emacs의 ~fill~ 기능을 사용하면 직접 수동으로 처리하거나 작성 도중에 자동으로 이 작업을 처리할 수 있습니다. fill 명령은 단순히 텍스트에 국한되지 않습니다. 예를 들어, 주석이나 doc string도 80자 이내로 맞추도록 fill 기능을 사용할 수 있습니다.

| 키 바인딩            | 용도                  |
|----------------------+-----------------------|
| ~M-q~                | 단락 채우기           |
| ~C-x f~              | 채우기 열 너비 설정   |
| ~C-x .~              | 채우기 접두사 설정    |
| ~M-x auto-fill-mode~ | 자동 채우기 모드 전환 |

저는 코드에 주석을 달 때 ~M-q~ 를 사용해서 단락 채우기를 자주 활용합니다. 메이저 모드(major modes)는 프로그래밍 언어나 파일 유형에 적합한 모범 사례에 따라 채우기 너비(~C-x f~)를 설정하는 것이 일반적입니다.

한 페이지를 넘쳐흐르는 셜록 홈즈의 다음과 같은 인용문을 살펴보겠습니다:

#+begin_src 
'It is an old maxim of mine that when you have excluded […]
#+end_src

문단 내에 커서를 위치시킨 후 ~M-q~ 를 입력하면:

#+BEGIN_QUOTE
'It is an old maxim of mine that when you  
have excluded the impossible, whatever  
remains, however improbable, must be the  
truth.'
#+END_QUOTE

접두사 ~C-u~ 와 함께 ~M-q~ 를 입력하면 Emacs는 텍스트를 양쪽 정렬(justify)합니다:

#+BEGIN_QUOTE
'It is an old maxim of mine that when you  
have excluded the impossible, whatever  
remains, however improbable, must be the  
truth.'
#+END_QUOTE

~C-x f~ 를 입력하면 채움 너비를 입력하라는 메시지가 나타납니다. 예를 들어, 위의 인용문에서 단락으로 나눌 열에 커서를 두고 ~C-x f~ 를 눌렀습니다. 대략 42글자 정도입니다. 채움 너비는 줄당 문자 수를 의미하지만 Emacs는 단어를 하이픈으로 나누지 않으므로 채움 너비를 너무 작게 설정하면 제대로 채워지지 않습니다.

fill prefix 는 흥미로운 기능입니다. ~C-x .~ 을 입력하면 Emacs는 커서 위치까지의 현재 줄의 모든 문자를 채우기 접두사로 지정합니다. 이름으로 알 수 있듯이 fill prefix 는 ~M-q~ 를 사용해서 단락을 채울 때 줄 앞에 삽입됩니다. fill prefix 를 제거하려면 커서를 빈 줄에 놓고 ~C-x . .~ 를 입력합니다.

~M-x auto-fill-mode~ 를 활성화하면 글을 작성할 동안 텍스트가 자동으로 채워지도록 Emacs에게 지시할 수 있습니다. 저는 프로그래밍 모드에선 이 기능을 사용하지 않으며(제대로 작동하지 않기 때문에) 텍스트 모드에서만 사용하도록 제한합니다.


*** Commenting
코드에 주석을 삽입하는 것은 Emacs가 충분히 잘 할 수 있는 작업입니다. Emacs는 몇 가지 서로 다른 키 바인딩과 명령어가 내장되어 있으며 각각 다른 용도로 사용합니다.

| 키 바인딩         | 용도                                        |
|-------------------+---------------------------------------------|
| ~M-;~             | DWIM 주석 처리 또는 주석 해제               |
| ~C-x C-;~         | 줄 주석 처리 또는 주석 해제                 |
| ~M-x comment-box~ | 해당 영역을 상자 형태로 주석 처리           |
| ~M-j , C-M-j~     | 새 줄을 삽입하고 새 줄에 주석을 이어서 작성 |

주석 달기에서 자주 사용하는 두 가지 명령은 ~M-;~ 와 ~C-x C-;~ 입니다. ~M-;~ 를 입력하면 Emacs는 커서가 위치한 줄 끝에 주석을 삽입하며 커서가 빈 줄에 있을 경우 메이저 모드의 들여쓰기 규칙에 따라 주석을 들여쓰기합니다. 영역이 활성화된 상태에서 ~M-;~ 를 누르면 해당 영역의 주석 표시/해제를 전환합니다. ~C-x C-;~ 명령은 커서가 위치한 줄 전체의 주석 표시를 전환합니다. ~C-x C-;~ 는 음수 및 숫자 인수를 사용해도 정상 작동합니다.

포인트가 주석에 있을 때 ~M-j~ 또는 ~C-M-j~ 를 입력하면 Emacs는 줄을 끊고 새로운 주석을 삽입합니다. 그런 의미에서 이는 fill prefix 와 동일합니다. 이 명령은 문서 문자열을 작성할 때 유용합니다. Emacs는 일반적으로 일부 문서 문자열 형식이 요구하는 주석 접두사를 똑똑하게 인식하기 때문입니다.

앞서 언급한 Emacs fill 명령어들은 주석 구문을 이해하고 준수하므로 주석에서 ~M-q~ 를 자유롭게 사용해도 됩니다.

필요한 주석 변수가 설정되지 않은 메이저 모드에서 주석 명령어를 사용할 경우(아래 표 참조) Emacs는 명령어를 처음 실행할 때 사용할 주석 문자를 묻습니다.

| 변수 이름         | 용도                                   |
|-------------------+----------------------------------------|
| ~comment-style~   | 사용할 주석 스타일                     |
| ~comment-styles~  | 사용 가능한 주석 스타일의 연관 목록    |
| ~comment-start~   | 주석 시작을 표시할 문자                |
| ~comment-end~     | 주석 끝을 표시할 문자                  |
| ~comment-padding~ | 주석 문자(들)와 본문의 여백(보통 공백) |
|                   |                                        |

위의 모든 변수는 ~M-x customize-option~ 을 사용해서 사용자 정의할 수 있습니다. ~comment-start~ 나 ~comment-end~ 는 항상 메이저 모드 작성자가 설정하므로 직접 변경할 일은 거의 없습니다. ~comment-style~ 은 팀 내의 규정이나 개인적인 선호에 따라 특정 주석 스타일을 사용할 경우엔 반드시 설정해야 합니다. 사용 가능한 주석 스타일 목록을 확인하려면 Customize 인터페이스에서 ~comment-styles~ 변수의 설명을 읽거나 ~M-x describe-variable~ (~C-h v~ 키에도 할당됨)을 사용해서 해당 변수를 조회해야 합니다.


** Search and Replace
텍스트를 검색할 때는 정규식(다음 섹션 ‘정규식’ 참조)을 사용하거나 사용하지 않고 검색할 수 있습니다. Emacs에서 텍스트를 바꾸는 작업도 이와 마찬가지지만 검색 및 바꾸기의 ‘바꾸기’ 단계에서 Elisp의 강력한 기능을 활용할 수 있다는 장점이 있습니다.

그런 의미에서 Emacs는 다른 편집기와 다릅니다. Elisp과 정규표현식의 캡처 그룹을 사용할 수 있는데 Elisp을 잘 안다면 이는 강력한 기능입니다. Emacs의 정규표현식 구현은 나중에 설명하겠지만 PCRE 와 다릅니다. 이 구현은 정규표현식에 대한 GNU 표준을 따르되 패키지 개발자와 Emacs 사용자 모두에게 적합하도록 많은 기능이 추가(그리고 꽤 많은 기능이 생략)됐습니다.

Emacs의 검색 및 바꾸기 명령어는 다음과 같습니다:

| 키 바인딩            | 용도                  |
|----------------------+-----------------------|
| ~C-M-%~              | 정규식 검색 및 바꾸기 |
| ~M-%~                | 검색 및 바꾸기        |
| ~M-x replace-string~ | 검색 및 바꾸기        |
| ~M-x replace-regexp~ | 정규식 검색 및 바꾸기 |

Isearch에서 Emacs의 검색 및 바꾸기 기능을 사용할 수 있습니다:

| Isearch 키 바인딩 | 용도                       |
|-------------------+----------------------------|
| ~C-M-%~           | 쿼리 정규식 검색 및 바꾸기 |
| ~M-%~             | 쿼리 검색 및 바꾸기        |

쿼리(query) 명령어는 대화형으로 일치 항목이 나올 때마다 사용자에게 다음 단계를 안내합니다. Isearch와 마찬가지로 인터페이스는 간결하지만 매우 실용적입니다. 또한, 이 인터페이스는 두 부분으로 나뉩니다. 하나는 검색 및 바꾸기 프롬프트, 다른 프롬프트와 동일한 방식으로 작동하며 다른 하나는 각 일치 항목을 선택하는 대화형 부분입니다.

일치 항목이 표시되면 다음 옵션 중 하나를 선택할 수 있습니다:

| Qeury 키 바인딩 | 용도                                          |
|-----------------+-----------------------------------------------|
| ~SPC , y~       | 일치 부분을 하나 교체한 후 계속 진행          |
| ~.~             | 일치 부분을 하나 교체한 후 종료               |
| ~,~             | 교체하되 현재 일치 위치에 그대로 머무름       |
| ~RET,q~         | 일치 부분을 교체하지 않고 종료                |
| ~!~             | 버퍼의 모든 일치 항목을 교체                  |
| ~^~             | 커서를 이전 일치 위치로 이동                  |
| ~u,U~           | 마지막 교체ㅡ 작업 취소 / 모든 교체 작업 취소 |


*** Case Folding
“Isearch: 증분 검색” 섹션에서 저는 대소문자 변환(case folding)를 이미 다룬 바 있습니다. 이는 Emacs의 유용한 기능으로 대소문자가 섞인 문자열이나 대문자로 구성된 문자열을 검색할 때를 제외하고 대소문자를 구분하지 않고 문자열을 지능적으로 일치시킵니다. 이 기능이 활성화되면 대소문자를 구분하는 검색이 수행됩니다. 이는 매우 훌륭한 기능이며 Emacs의 문자열 교체 메커니즘도 이를 활용합니다.

다음과 같은 의사 코드가 포함된 버퍼를 가정합니다:

#+begin_src 
HELLO_WORLD = “Hello, World!”

function hello() {
  print(HELLO_WORLD)
}
#+END_SRC

~C-M-%~ 단축키를 사용해서 hello 를 goodbye 로 쿼리 교체(query replace)하면 위 버퍼의 결과는 다음과 같습니다:

#+begin_src 
GOODBYE_WORLD = “Goodbye, World!”

function goodbye() {
  print(GOODBYE_WORLD)
}
#+end_src

보다시피 Emacs는 Hello 나 HELLO 가 아닌 hello 를 검색하므로 치환 대상의 대소문자를 그대로 유지합니다. 만약 Hello 나 HELLO 를 검색했다면 Emacs는 대문자가 포함된 문자열만 치환했을 겁니다.


*** Regular Expressions
앞서 저는 PCRE와 Emacs의 차이점에 대해 언급한 바 있습니다. 요컨대 Emacs의 정규식 엔진은 도저히 사용자 친화적이라곤 말할 수 없을 정도입니다. 이 엔진은 아주 오래되고 낡았으며 Emacs의 특수한 요구 사항에 맞추기 위해 대대적으로 수정된 탓에 쉽게 대체하기도 어려운 상태입니다.

예를 들어, PCRE 스타일의 엔진에서 ~(~ 와 ~)~ 문자는 메타 문자로 즉, 엔진이 이를 문자그대로의 문자가 아닌 캡처 그룹으로 처리합니다. 반면 Emacs는 이와 정반대입니다. 이 문자들은 백슬래시(~\~)로 이스케이프 처리할 때까지는 문자그대로의 문자로 취급되다가 그 시점에서야 비로소 메타 문자 역할을 수행합니다.

실질적으로 이는 Emacs의 독특한 정규표현식 엔진에 익숙하지 않은 사용자들에게 정규표현식 작성 시 혼란을 야기합니다. Elisp을 작성할 때는 상황이 좀 더 심각합니다. Emacs의 C 스타일 문자열 리더가 백슬래시를 감지해서 오류를 발생시키므로 이탈 문자를 다시 한 번 이스케이프 처리해야 하기 때문입니다.

정규표현식은 그 자체로 한 권의 책이 될만큼 아주 방대하므로 여기선 자세히 다루지 않겠습니다. 대신, Emacs의 정규표현식 엔진이 현대적인 엔진들과 어떻게 다른지를 설명하겠습니다.


**** Backslashed Constructs
다음 구문는 백슬래시가 필요하며 그렇지 않으면 Emacs가 이를 리터럴 문자로 처리합니다:

| 구문      | 설명      |
|-----------+-----------|
| ~\~       | 대안      |
| ~\( , \)~ | 캡처 그룹 |
| ~\{ , \}~ | 반복      |


**** Missing Features
Emacs는 하드코딩된 구문을 제외하곤 어떤 종류의 음수 또는 양수 선행/후행 검사도 지원하지 않습니다!! 분기 재설정 그룹 같은 다소 생소한 정규식 기능도 빠져 있습니다. 대부분의 텍스트 편집 작업에선 이것이 큰 문제가 되진 않습니다.

한 가지 불편한 점은 숫자 클래스를 나타내는 약어인 ~\d~ 가 없다는 것입니다. ~\d~ 대신 ~[0-9]~ 를 사용하거나 명시적인 ~[:digit:]~ 클래스를 사용해야 합니다.


**** Emacs-only features
Emacs의 정규식 엔진이 특히 뛰어난 점은 매치 구문 지원과 유니코드 지원입니다:

| 구문        | 설명                                                    |
|-------------+---------------------------------------------------------|
| ~\< , \>~   | 단어의 시작과 끝을 일치시킵니다                         |
| ~\_< , \_>~ | 기호의 시작과 끝을 일치시킵니다                         |
| ~\scode~    | 구문 테이블 코드가 code인 모든 문자를 일치시킵니다      |
| ~\Scode~    | 구문 테이블 코드가 code가 아닌 모든 문자를 일치시킵니다 |

~\<, \>, \_<, \_>~ 를 사용해서 기호와 단어를 일치시키는 것은 임시적인 리팩토링을 위한 프로그래밍에서 흔히 볼 수 있는 처리 방식입니다. 단어와 기호의 정의는 Emacs의 구문 테이블에 달려 있으므로 메이저 모드에 따라 달라집니다.

~\s~ 와 ~\S~  모두 특정 구문 클래스에 속하는 문자를 일치시킬 수 있다는 점에서 각각의 용도가 있습니다. 각 클래스의 명명은 사실 단순한 지침일 뿐입니다. 메이저 모드 작성자가 숫자 9 를 공백 클래스에 속한다고 선언하는 것을 막을 수 있는 것은 아무것도 없기 때문입니다.

다음은 흥미로운 구문 클래스의 요약 목록입니다:

*공백 문자 (-)* : 예상대로 일반적인 공백뿐만 아니라 줄바꿈 및 일반적으로 비-분리 공백같은 유니코드 등가 문자도 포함합니다.

*단어 구성 요소 (w)* : 이는 일반적으로 모든 소문자 및 대문자, 숫자 그리고 비-라틴 문자 집합의 유니코드 등가 문자를 포함합니다.

*기호 구성 요소 (_)* : 모든 단어 구성 요소와 프로그래밍 언어에서 가장 자주 사용되는 ~!~ 나 ~_~ 같은 기호를 포함합니다. 이 클래스는 다른 어떤 클래스보다 현재 사용 중인 메이저 모드에 따라 변화할 가능성이 높습니다.

*구두점 문자 (.)* : ~.~ 이나 ~;~ 같은 일반적인 문자를 포함합니다. 텍스트 모드와 프로그래밍 모드는 상당히 다를 가능성이 높습니다.

*열림/닫힘 괄호 (( 및 ))* : 쌍을 이루는 모든 문자 집합을 포함합니다. 대부분의 텍스트 및 프로그래밍 모드는 ~() , []~ 및 ~{}~ 가 포함됩니다.

*문자열 문자 (")* : 연속된 블록을 문자열로 표시하는 모든 기호를 포함합니다. 큰따옴표와 작은따옴표, ~'~ 및 ~"~ 가 일반적으로 여기에 포함됩니다. 좌/우 괄호, 기요모트(guillemots) 같은 유니코드 문자도 이 범주에 포함됩니다.

*주석 시작/종료 문자 (< 및 >)* : 주석 경계를 정의하는 모든 문자 또는 문자 쌍입니다. 일부 언어는 줄 단위 주석만 지원하며 이 경우 ~<~ 만 사용됩니다.

예를 들어, 모든 공백 문자를 일치시키려면 ~\s-~ 를 검색합니다. 모든 문자열 따옴표 문자를 일치시키려면 예를 들어, 'strings' 와 “strings” 모두 가능한 Python처럼– ~\s"~ 를 사용해서 모든 따옴표 기호를 일치시킵니다. 이를 통해 Emacs가 사용자의 메이저 모드 구문을 이해하는 기능을 활용해서 텍스트를 변환합니다 (또는 단순히 찾을 수 있습니다. 이 명령은 regexpIsearch 나 Occur 에도 작동합니다).

#+BEGIN_QUOTE
*Determining a character’s syntax class* :  
Emacs의 유니코드 지원 기능은 훌륭하며 광범위한 유니코드 지원의 일환으로  
~C-u M-x what-cursor-position~ 명령을 사용해서 원하는 문자를 자세히 살펴볼 수 있습니다.

이를 사용하려면 확인할 문자에 커서를 위치시킨 후 해당 명령을 실행하거나 ~C-u C-x =~ 를 입력합니다.  
그러면 구문 클래스, 폰트 락, 유니코드 이름 등을 포함한 다양한 정보가 표시됩니다.
#+END_QUOTE

Emacs는 다음과 같은 여러 종류의 캡처 그룹이 있습니다:

| 구문        | 설명                                                        |
|-------------+-------------------------------------------------------------|
| ~\1 ~ \9~   | 그룹 \N 의 텍스트를 삽입합니다                              |
| ~\#1 ~ \#9~ | 그룹 \N 의 텍스트를 삽입하되 정수로 변환합니다 (Elisp 전용) |
| ~\?~        | 사용자에게 텍스트 입력을 요청합니다                         |
| ~\#~        | 0 부터 증가하는 숫자를 삽입합니다                           |
| ~\&~        | 일치한 문자열 전체를 삽입합니다                             |

~\#N~ 캡처 그룹은 elisp 형식 외에는 거의 쓸모가 없습니다. ~\?~ 를 사용하면 일치 부분을 직접 입력한 문자열로 바꿀 수 있습니다. ~\#~ 그룹은 0 부터 시작하는 번호를 삽입하며 일치할 때마다 1 씩 증가합니다. 마지막으로 ~\&~ 는 단순히 일치한 문자열 전체를 삽입합니다.


**** Invoking Elisp
검색 및 바꾸기 인터페이스의 ‘바꾸기’ 부분에서 elisp 함수를 호출할 수 있습니다. 이 기능을 사용할지 여부는 전적으로 elisp에 대한 이해도(또는 실험해 볼 의지)와 복잡한 검색 및 바꾸기 작업을 얼마나 자주 수행하느냐에 달려 있습니다.

Elisp을 호출하려면 다음과 같은 형식을 사용합니다:

#+begin_src 
\,(form ...)
#+end_src

여기서 form 은 호출할 함수의 이름입니다. Elisp을 호출하려면 반드시 따라야 할 몇 가지 규칙이 있습니다:

- 캡처 그룹은 기본적으로 문자열 유형입니다. 정수같은 다른 유형을 기대하는 엘리스프(Elisp) 함수에 문자열을 전달하면 오류가 발생합니다.

- 함수에서 캡처 그룹이 필요하지 않으면 캡처 그룹을 사용할 필요가 전혀 없습니다. 함수의 유일한 출력값으로 일치 결과를 대체하는 것도 충분히 가능합니다.

- 한 번에 하나의 형식만 호출할 수 있습니다. 따라서, 두 개 이상을 호출하려면 progn 이나 prog1 같은 함수로 감싸거나 concat 같은 함수를 사용해서 여러 함수의 결과를 하나로 연결해야 합니다.

- 캡처 그룹을 따옴표로 묶지마시기 바랍니다. 이는 Emacs 인터프리터에게 리터럴 문자열(~\N~ 사용 시) 또는 숫자(~\#N~ 사용 시)로 전달되기 때문입니다.

다음은 시도할 수 있는 몇 가지 대체 문자열의 예입니다:

| 대체 문자열             | 설명                                                           |
|-------------------------+----------------------------------------------------------------|
| ~\,(upcase \N)~         | 대문자로 변환하는 캡처 그룹 \N                                 |
| ~\,(format “%.2f” \#N)~ | ~\#N~ 을 숫자로 변환하고 소수점 두 자리 십진수 형식으로 포맷팅 |

강력한 기능이지만 상황에 따라 다릅니다. ‘버퍼(The Buffer)’ 섹션에서 언급했듯이 Emacs 내부 함수 대부분—흥미로운 작업을 수행하는 거의 모든 함수—은 문자열이 아닌 버퍼를 대상으로 작동합니다. 이로인해 이 기능의 유용성이 크게 떨어지는데 원하는 작업을 수행할 함수를 찾아야할 뿐만 아니라 문자열을 대상으로 작동하는 함수도 찾아야 하기 때문입니다.

이 기능이 필요할 때마다 저는 어쩔 수 없이 원하는 방식으로 텍스트를 변환하는 나만의 특수 함수를 직접 작성했습니다. 하지만, 이는 elisp에 대한 어느 정도의 숙련도를 전제로 합니다. 제 조언은 Emacs의 키보드 매크로를 활용하는 방법입니다. 이 주제는 곧 다룰 예정인데 복잡한 편집 작업에는 키보드 매크로가 훨씬 더 적합하기 때문입니다.


** Changing Case
대소문자 변경—텍스트의 대소문자를 변경하거나 소문자 또는 대문자로 바꾸는 것—은 코드와 텍스트 모두에서 흔히 발생하는 현상입니다.

| 영역 명령                    | 설명                                |
|------------------------------+-------------------------------------|
| ~C-x C-u~                    | 선택 영역의 문자를 대문자로 변환    |
| ~C-x C-l~                    | 선택 영역의 문자를 소문자로 변환    |
| ~M-x upcase-initials-region~ | 선택 영역의 첫 글자를 대문자로 변환 |

처음 두 가지는 딱히 설명할 것이 별로 없습니다. 영역이 활성화된 상태는 해당 영역의 글자를 대문자나 소문자로 변경할 수 있습니다. 영역의 글자를 대문자로 변경하는 것은 실제로는 문장, 줄 또는 단락의 첫 단어뿐만 아니라 영역 내의 모든 단어를 대문자로 만드는 것을 의미합니다.

단어에 적용되는 대소문자 명령어들이 훨씬 더 흥미롭습니다:

| 키 바인딩 | 용도                      |
|-----------+---------------------------|
| ~M-c~     | 다음 단어를 대문자로 변경 |
| ~M-u~     | 다음 단어를 대문자로 변경 |
| ~M-l~     | 다음 단어를 소문자로 변경 |

우선 이 명령어들은 기억하기도 쉽고 소위 ‘주요 키 영역’ (손이 닿기 쉽고 입력하기 편한 키들)에 할당되어 있습니다. 이 명령어들은 Emacs의 다른 단어 기반 명령어들과 정확히 동일한 방식으로 작동하며 ~forward-word, mark-word, kill-word, transpose-words~ 명령어와 동일한 구문 테이블 처리 규칙을 따릅니다.

숫자 인자와 음수 인자 모두 예상대로 작동합니다. 다른 단어 기반 명령어들과 마찬가지로 이 명령어들도 외워둘 것을 권장합니다. 영역 명령어들은 별도로 외울 필요가 없습니다. 영역 단위로 대소문자를 변경하는 작업을 많이 하지않는 한 단어 단위로 대소문자를 변경할 가능성이 훨씬 더 높기 때문입니다.

이 명령어들을 사용할 때 커서를 유지하는 것은 매우 중요합니다. 일반적으로 글을 쓰면서 이 명령어들을 사용하기 때문입니다. ~M-- M-u~ 는 예를 들어, 방금 입력한 단어를 대문자로 바꾸고 ~M-b M-- M-u~ 는 한 단어 뒤로 이동해서 그 앞의 단어를 대문자로 바꿉니다. 물론 키를 누르는 사이에 메타 키를 놓아선 안 됩니다. 따라서, 엄지손가락을 왼쪽 메타 키에 둔 채로 다른 손가락들은 자유롭게 ~b - u~ 를 입력할 수 있습니다.

다음 문장을 살펴보겠습니다. 마침표를 삽입하고 다음 단어를 대문자로 변환합니다:

#+begin_src 
Hey how are you?
#+end_src

~M-f~ 를 눌러 한 단어 앞으로 이동한 후 ~.~ 을 눌러 마침표를 삽입하고 ~M-c~ 를 눌러 다음 단어를 대문자로 변경하면:

#+begin_src 
Hey. How█ are you?
#+end_src

마찬가지로 여기서 식별자 입력은 마쳤지만 이 식별자는 문자열 상수로 대문자로 표기되야 합니다:

#+begin_src 
print(greeting_string)█
#+end_src

대부분의 메이저 모드에서 ~_~ 는 구두점이나 기호로 인식되므로 단어를 끊어버립니다. 따라서, ~M-b~ 를 두 번 눌러 뒤로 이동해서 커서를 greeting_string 의 시작 부분에 위치시켜야 합니다.

아니라면 숫자와 부정 연산자를 결합한 ~M-- M-2 M-u~ 를 사용할 수 있습니다:

#+begin_src 
print(GREETING_STRING)█
#+end_src

조금만 연습하면 생각할 필요없이 빠르고 직관적으로 이 작업을 수행할 수 있습니다. 또 다른 장점은 커서를 이동하지 않으므로 계속 글을 쓸 수 있다는 점입니다. 커다란 시간 절약처럼 보이진 않겠지만 이런 것이 쌓인다면 큰 차이가 납니다.

대소문자 명령어는 비-라틴 문자도 잘 작동합니다. Emacs는 대부분의 유니코드 문자를 올바른 유니코드 범주로 매핑하기 때문입니다. 실질적으로 이는 Emacs가 소문자나 대문자를 만났을 때 이를 인식한다는 것을 의미합니다:

#+BEGIN_QUOTE
그리스어: αβψδεφγ -> ΑΒΨΔΕΦΓ  
덴마크어: abcdæøå -> ABCDÆØÅ
#+END_QUOTE


#+BEGIN_QUOTE
*Unicode categories* :  
~M-x describe-categories~ 를 실행해서 모든 유니코드 범주의 전체 목록을 확인하시기 바랍니다.
#+END_QUOTE



** Counting Things
무언가 세기 위해 굳이 wc 프로그램을 호출할 필요는 없습니다. Emacs도 그 작업을 완벽히 수행할 수 있습니다.

| 명령어                         | 설명                                        |
|--------------------------------+---------------------------------------------|
| ~M-x count-lines-region~       | 지정된 영역의 줄 수를 셉니다                |
| ~M-x count-matches~            | 지정된 영역에서 일치한 패턴의 개수를 셉니다 |
| ~M-x count-words~              | 버퍼의 단어, 줄, 문자 수를 셉니다           |
| ~M-x count-words-region , M-=~ | 지정된 영역의 단어, 줄, 문자 수를 셉니다    |

세는 방법은 여러 가지지만 기억할만한 두 가지는 다음과 같습니다:

*~M-x count-words~* : 이 명령은 이름과 달리 줄과 문자까지 셉니다. 때로는 특정 영역의 항목을 셀 수도 있는데 이 경우 ~M-=~ 를 사용합니다.

*~M-x count-matches~* : 지정한 정규표현식 패턴의 일치 횟수를 셉니다. 활성 영역이 없을 경우 커서 위치부터 버퍼 끝까지, 활성 영역이 있을 경우 해당 영역만 셉니다.


** Text Manipulation
텍스트 조작 작업은 Emacs가 특히 뛰어난 분야 중 하나로 이를 돕기위한 다양한 도구를 갖추고 있습니다. 텍스트 파일을 가공하거나 로그 파일에서 관련 정보를 추출하는 작업은 Emacs에서 흔히 수행되는 작업입니다. 비록 Emacs가 awk 나 sed 같은 전용 도구나 Python 같은 프로그래밍 언어를 완전히 대체할 수 없겠지만 중소 규모의 작업에선 훌륭한 선택지입니다.


*** Editable Occur
앞서 특정 패턴과 일치하는 모든 줄을 정렬하는 방법으로 ~M-x occur~ 를 소개한 바 있습니다. occur 모드에서 아직 언급하지 않은 기능 중 하나는 일치 부분을 편집하고 작업이 끝나면 변경 사항을 해당 줄에 반영할 수 있다는 점입니다.

이를 위해선 우선 ~e~ 를 입력해서 편집 가능한 occur 모드로 진입합니다. 그런 다음 ~C-c C-c~ 를 입력해서 변경 사항을 적용합니다. 활용 가능성은 무궁무진합니다. 이 기능은 특히 키보드 매크로와 검색 및 바꾸기 작업에서 유용합니다.


*** Deleting Duplicates
Emacs는 중복된 줄을 삭제할 수 있으며 가장 큰 장점은 명령줄 유틸리티인 uniq 와 달리 Emacs가 중복을 감지할 때 줄들이 서로 인접할 필요가 없다는 점입니다. 즉, 텍스트를 정렬하지 않고도 중복 부분을 삭제할 수 있습니다.

| 범용 인자     | 설명                         |
|---------------+------------------------------|
| 삭제 없이     | 첫 번째 중복 행 삭제         |
| ~C-u~         | 마지막 중복 행 삭제          |
| ~C-u C-u~     | 인접한 중복 행만 삭제        |
| ~C-u C-u C-u~ | 인접한 빈 행은 삭제하지 않음 |

기본적으로 ~M-x delete-duplicate-lines~ 은 맨 위부터 시작해서 처음 발견된 중복 줄을 삭제합니다. 단일 범용 인수를 지정하면 맨 아래부터 시작하므로 마지막 줄을 삭제합니다.


*** Flushing and Keeping Lines
때로는 영역의 줄을 특정 패턴에 따라 필터링할 때도 있습니다. 패턴과 일치한 줄 혹은 일치하지 않는 줄만 남겨두는 방식입니다.

두 명령어 모두 활성 영역에 적용되므로 버퍼 전체에 이 작업을 수행하려면 먼저 ~C-x h~ 를 눌러 버퍼 전체를 선택하는 것이 일반적입니다.

| 명령어            | 설명                                                                              |
|-------------------+-----------------------------------------------------------------------------------|
| ~M-x flush-lines~ | 지정된 패턴과 일치한 영역의 모든 줄을 지웁니다                                    |
| ~M-x keep-lines~  | 지정된 패턴과 일치한 영역의 모든 줄을 유지하고 일치하지 않는 줄 모두를 제거합니다 |

두 명령어 모두 정규식 패턴을 지원합니다. 패턴이 줄과 일치하면 해당 줄은 유지되거나 삭제됩니다. 패턴 자체는 변경되지 않습니다(패턴 자체를 변경하려면 검색 및 바꾸기 기능을 사용합니다).

저는 텍스트를 처리할 때 이 명령들을 자주 사용합니다. 패턴과 일치한 줄을 유지해서 '가난한 사람의 grep' 처럼 사용할 수 있으며 flush 는 반대 역할을 처리합니다. 로그 파일 필터링이나 데이터 정제 작업은 이 명령들이 가장 효과적으로 활용되는 두 가지 예입니다.


*** Copying and Killing Matching Lines
줄을 지우거나 유지하는 명령과 마찬가지로 Emacs에서 줄을 복사하거나 삭제하도록 지시할 수 있습니다. 하지만, 이 기능들은 Emacs 28에 새로 추가된 기능으로 이전 버전에선 사용할 수 없습니다.

| 명령어                    | 설명                                                           |
|---------------------------+----------------------------------------------------------------|
| ~M-x copy-matching-lines~ | 지정된 영역에서 패턴과 일치한 모든 줄을 복사합니다 (Emacs 28+) |
| ~M-x kill-matching-lines~ | 지정된 영역에서 패턴과 일치한 모든 줄을 삭제합니다 (Emacs 28+) |


*** Joining and Splitting Lines
줄을 삭제하는 명령어(~C-M-<backspace>~ 및 ~C-k~)와 달리 이 명령어들은 킬 링을 변경하지 않습니다. 또한, 커서 위치를 이동하지 않고 줄을 삽입하거나 삭제하므로 좀 더 특수한 용도로 사용합니다.

| 키 바인딩 | 설명                                               |
|-----------+----------------------------------------------------|
| ~C-o~     | 커서 위치 뒤에 빈 줄을 삽입합니다                  |
| ~C-x C-o~ | 커서 위치 뒤의 모든 빈 줄을 삭제합니다             |
| ~C-M-o~   | 커서 위치 뒤에서 줄을 나누되 들여쓰기를 유지합니다 |
| ~M-^~     | 커서가 위치한 줄과 그 위 줄을 합칩니다             |

커서 위치 바로 뒤에 새로운 줄을 삽입하려면 ~C-o~ 를 사용합니다. ~RET~ 과 달리 커서는 다음 줄로 이동하지 않고 원래 위치에 그대로 남습니다. 저는 ~RET~ 을 사용할 때 커서 위치까지 함께 이동하는 것을 원치 않을 때 이 명령으로 단락을 두 개로 나누곤 합니다.

빈 줄을 삭제하는 것은 매우 흔한 작업입니다. ~C-x C-o~ 는 바로 이 작업을 수행하지만 다음과 같은 세 가지 규칙을 따릅니다:

*현재 줄은 무시합니다* : 비어있는 줄도 커서가 위치한 줄은 제거하지 않습니다. 즉, 빈 줄 블록에서 이 명령을 실행하면 정확히 한 줄의 빈 줄만 남습니다. 이 규칙을 반드시 기억하시기 바랍니다. 텍스트의 단락 사이나 코드의 클래스 및 함수 정의 사이 등 일정한 간격을 유지하는 데 유용한 방법입니다.

*커서 앞쪽을 처리합니다* : 따라서, 비어있지 않은 줄에서 이 명령을 호출하면 커서 앞쪽의 빈 줄을 제거합니다. 앞서 설명한 규칙과 달리 ~C-x C-o~ 는 모든 빈 줄을 제거합니다.

*공백과 탭만 포함된 줄도 제거합니다* : 빈 줄에 탭이나 공백 문자를 그대로 남겨두는 많은 언어에 유용합니다.

~C-M-o~ 는 일상적으로 사용하지 않는 매우 특수한 명령어입니다. 마침표 뒤에 새로운 줄을 삽입하는(‘줄 시작’ 이라고도 함) ~C-o~ 와 달리 ~C-M-o~ 는 동일한 기능을 수행하지만 텍스트의 열 오프셋을 그대로 유지합니다.

~C-o~ 와 ~C-M-o~ 의 차이점을 살펴보겠습니다:

#+begin_src 
All the world's a stage, █and all the …
#+end_src

~C-o~ 사용 후:

#+BEGIN_QUOTE
All the world's a stage, █
and all the …
#+END_QUOTE

이제 원래 예제를 ~C-M-o~ 를 사용해서 다시 살펴보겠습니다:

#+BEGIN_QUOTE
All the world's a stage, █
                                         and all the …
#+END_QUOTE

커서가 원래 위치에 그대로 남아있음을 확인하시기 바랍니다.

마지막으로 ~M-^~ 명령어는 ~C-o~ 및 ~C-M-o~ 와 정반대 기능을 수행합니다: 커서가 위치한 현재 줄을 바로 위의 줄과 합칩니다. 문장을 하나의 긴 단락으로 합치거나 여러 줄에 걸친 함수 인수를 한 줄로 합칠 경우 유용합니다.

~M-^~ 는 두 줄을 연결할 때 공백을 적절히 잘라내는 기능을 갖추고 있습니다. 즉, Emacs는 병합하려는 줄에 텍스트가 있는지 여부에 따라 공백을 잘라내어 최소 0개 또는 1개의 공백만 남게 만듭니다. 빈 줄의 경우 모든 공백은 제거되며 텍스트가 있는 줄의 경우 한 칸을 제외한 모든 공백이 제거됩니다.

#+BEGIN_QUOTE
*Fill prefix*:
채우기 접두사가 활성화된 상태에서 ~C-M-o~ 를 입력하 현재 줄은 분할되고 새로운 줄에 채우기 접두사가 삽입됩니다.
반대로 ~M-^~ 를 누르면 병합할 줄의 채우기 접두사는 제거됩니다.
#+END_QUOTE


*** Whitespace Commands
다른 곳에서 텍스트를 가져오거나 공백이 중요한 의미를 갖는 언어나 텍스트를 다룰 때는 공백 관리가 종종 문제가 됩니다.

| 명령어                           | 설명                                                                    |
|----------------------------------+-------------------------------------------------------------------------|
| ~M-x delete-trailing-whitespace~ | 뒤쪽의 모든 공백을 삭제합니다.                                          |
| ~M-SPC~                          | 커서 위치 좌우의 공백이나 탭 중 하나를 제외한 나머지를 모두 삭제합니다. |
| ~M-x cycle-spacing~              | 위와 같으나 ‘하나만 남기기’, ‘모두’, ‘취소’ 모드를 순환합니다.          |
| ~M-\~                            | 커서 위치 주변의 공백을 삭제합니다.                                     |

~M-SPC~ 는 커서 위치 좌우의 모든 공백을 하나의 공백 문자로 줄여줍니다. ~M-\~ 도 마찬가지로 작동하지만 모든 공백 문자를 제거해서 아무것도 남기지 않습니다. ~M-x cycle-spacing~ 은 공백을 하나 남기기, 공백을 전혀 남기지 않기 그리고 원래의 공백 간격을 복원하기를 순차적으로 전환합니다.

#+BEGIN_QUOTE
*Cycle Spacing as the default* :
기본적으로 공백 하나만 입력하는 대신 ~M-SPC~ 키를 누를 때 공백 간격 옵션을 순환하면서 선택할 수 있습니다.

이를 구현하려면 다음 내용을 init 파일에 추가합니다:

~(global-set-key [remap just-one-space] 'cycle-spacing)~
#+END_QUOTE

Emacs의 공백 모드를 사용하면 공백 문자와 줄 끝의 여분 공백이나 지나치게 긴 줄 같은 타자 오류를 화면에 표시할 수 있습니다.


**** Whitespace Minor Mode

| 명령어                          | 설명                                                        |
|---------------------------------+-------------------------------------------------------------|
| ~M-x whitespace-mode~           | 모든 공백 문자를 강조 표시하는 마이너 모드                  |
| ~M-x whitespace-newline-mode~   | 줄바꿈 문자를 ~$~ 기호로 표시하는 줄바꿈 모드               |
| ~M-x whitespace-toggle-options~ | ~whitespace-mode~ 의 모든 옵션을 토글할 수 있는 메뉴를 표시 |

Emacs의 공백 마이너 모드는 평소엔 보이지 않는 공백 문자에 글리프와 색상을 입혀서 사용자가 이를 구분할 수 있도록 해줍니다. 문장 끝의 공백, 잘못된 탭 문자 또는 공백이 포함된 “빈” 줄을 찾을 때 유용합니다.

공백 모드는 다음과 같은 항목을 추적합니다: 줄 끝 공백, 탭, 공백, ~whitespace-line-column~ (일반적으로 80자)보다 긴 줄, 줄바꿈 문자, 유니코드 간격, 빈 줄, 들여쓰기(탭과 공백 모두), 탭 뒤의 공백 및 탭 앞의 공백. 기본적으로 이 모드는 구문이나 서식 오류를 유발할 수 있는 모든 가능한 조합을 추적합니다.

~M-x customize-group~ 명령을 사용해서 whitespace 그룹을 사용자 정의함으로써 특히 색상이 다소 강렬하므로 ~whitespace-mode~ 를 사용자 정의할 것을 권장합니다.

또한, ~M-x whitespace-toggle-options~ 을 사용해서 ~whitespace-mode~ 가 강조 표시할 스타일을 전환할 수 있습니다.


**** Whitespace Reporting and Cleanup

| M-x 명령어                  | 설명                                     |
|-----------------------------+------------------------------------------|
| ~whitespace-report~         | 공백과 관련된 문제를 표시합니다          |
| ~whitespace-report-region~  | 위와 동일하지만 지정한 영역에 적용됩니다 |
| ~whitespace-cleanup~        | 자동 정리를 시도합니다                   |
| ~whitespace-cleanup-region~ | 위와 동일하지만 지정된 영역에 적용됩니다 |

~M-x whitespace-report~ 명령을 실행하면 (리전(region)의 경우도 마찬가지) 버퍼나 리전에 존재하는 “문제점” 을 간결히 정리한 목록을 확인할 수 있습니다. 또한, 해당 정리 명령을 사용해서 Emacs에 버퍼나 리전의 정리를 시도하도록 요청할 수 있습니다.



** Keyboard Macros
Emacs는 키 입력과 명령을 기록해서 나중에 재생할 수 있도록 키보드 매크로로 저장할 수 있습니다. Emacs의 키보드 매크로는 LISP 매크로와 많이 다르므로 두 가지를 혼동해서는 안 됩니다.

매크로 기록 기능은 새로운 발명품이 아닙니다. 대부분의 IDE와 텍스트 편집기에 이 기능이 있지만, Emacs만큼 진보된 기능을 갖춘 것은 거의 없습니다. Emacs의 키보드 매크로는 거의 모든 것이 기록될 수 있으므로 특히 강력합니다. 사각지대는 거의 없으며 –실제로 마주칠 가능성도 거의 없습니다– 바로 이런 점이 Emacs를 IDE와 그 대부분이 빈약한 매크로 기록 기능을 가진 다른 편집기들과 차별화합니다.

Emacs의 매크로 레코더는 LISP 언어로 작성되었습니다. 이 사실만으로도 Emacs가 제공하는 확장성의 힘을 잘 알 수 있지만, 이는 또한 Emacs 내에서 미시적 및 거시적 수준에서 이루어지는 변경 사항을 얼마나 세밀하게 관찰하고 기록할 수 있는지를 다시 한번 증명해 줍니다.


*** Basic Commands

| 키 바인딩        | 설명                                                |
| ~F3~             | 매크로 녹화를 시작하거나, 카운터 값을 삽입합니다    |
| ~F4~             | 매크로 녹화를 중지하거나 마지막 매크로를 실행합니다 |
| ~C-x~ (및 ~C-x~) | 매크로 녹화를 시작하고 중지합니다                   |
| ~C-x e~          | 마지막 매크로를 실행합니다                          |

~F3~ 키로 녹화를 시작하고 ~F4~ 키로 중지할 수 있습니다. 나머지 두 키는 사용하기 다소 불편하지만, Emacs의 노련한 베테랑 사용자들과의 하위 호환성을 위해 마련된 것입니다. 매크로 레코더는 범용 종료 명령인 ~C-g~ 를 호출하면 중지됩니다. 

#+BEGIN_QUOTE
*Signaling Errors* :
때때로 Emacs에서 오류가 발생하면 녹화나 재생이 중단되기도 합니다.
흔히 발생하는 “오류” 중 하나는 오류 목록의 시작이나 끝 부분에 도달했을 때
~M-g M-n~ 또는 ~M-g M-p~ (다음 오류 또는 이전 오류로 이동)를 입력하는 경우입니다.

이때 Emacs는 내부적으로 오류를 발생시키는데, 시스템의 사양에 따라 경고음이 울리거나
화면이 깜빡일 수 있습니다.
조심하지 않으면 이 때문에 당황할 수 있습니다. 저조차도 여전히 그런 일이 생기곤 합니다!

하지만, 결국에는 좋은 일입니다. 다음 또는 이전 오류 기능을 호출하는 매크로를 녹화한 다음,
해당 매크로를 반복해서 재생할 수 있기 때문입니다.
오류 목록의 끝(또는 시작)에 도달하면 매크로가 중지 신호를 보낼 것입니다
#+END_QUOTE

매크로 녹화가 진행 중일 때는 모드라인에 ‘Def’ 라는 단어가 표시됩니다. 녹화를 마치면 ~C-x e~ 또는 ~F4~ 를 입력해서 즉시 재생할 수 있습니다.

기록된 매크로는 킬 링, 실행 취소 링, 히스토리 링과 마찬가지로 자체적인 매크로 링을 가지고 있습니다. 즉, 새로운 매크로를 시작하더라도 실수로 기존 매크로를 덮어쓰는 걱정을 할 필요가 없습니다. 매크로는 (Emacs를 종료하지 않는 한) 절대 완전히 사라지지 않지만, 원한다면 디스크에 명시적으로 저장할 수도 있습니다.

또한 매크로 명령어에 범용 인자와 숫자 인자를 전달할 수 있습니다:

| 키 바인딩 | 설명                                                |
| ~C-u F3~  | 녹화를 시작하지만 마지막 매크로에 내용을 추가합니다 |
| ~C-u F4~  | 매크로 링에 있는 두 번째 매크로를 재생합니다        |
| ~숫자 F3~ | 녹화를 시작하지만 카운터를 숫자로 설정합니다        |
| ~숫자 F4~ | 마지막 매크로를 숫자 번 재생합니다                  |

따라서, ~C-u~ 와 숫자 인수는 서로 다른 기능을 수행합니다. 여기서 ‘숫자’ 란 ~C-u 10~ 이나 ~M-10~ 같은 숫자를 의미합니다.

마지막 매크로(~C-u F3~) 뒤에 매크로를 추가하는 방법도 유용하지만, ~F4~ 에 숫자 인수를 전달하는 방법도 알아두면 좋습니다. 매크로를 정해진 횟수만큼 반복해서 실행하는 경우가 좀 더 흔하기 때문입니다. 숫자 0 (예를 들어 ~C-0 F4~ 또는 ~C-u 0 F4~)을 전달하면, Emacs는 버퍼의 끝에 도달하거나 기록된 매크로가 오류 신호를 보낼 때 같이 Emacs가 오류를 알릴 때까지 매크로를 반복해서 실행합니다.


*** Advanced Commands
~C-x C-k~ 라는 접두사 키 조합은 전적으로 Emacs의 매크로 기능을 위해 마련된 것입니다. 여기에는 수많은 명령어가 포함되어 있으며, 대부분은 상당히 특수한 용도로 쓰입니다.

#+BEGIN_QUOTE
*Learn more* :
항상 그렇듯이, 접두사 키 앞에 ~C-h~ 를 입력하면
Emacs가 해당 접두사에 바인딩된 모든 키를 나열해 줍니다.

또 다른 방법은 apropos (~C-h a~)를 사용해서
모든 명령어를 나열하는 것입니다.

명명 체계는 다소 일관성이 없습니다. 많은 매크로 명령은 kmacro 로 시작합니다.
그러나, 일부는 Emacs의 해당 부분이 도입되기 이전에 만들어진 것으로,
단순히 ~kbd-macro~ 라는 단어를 포함하고 있을 뿐입니다.
#+END_QUOTE


**** Interactive Macro Playback
먼저 카운터부터 살펴보겠습니다. 녹화를 시작하면 Emacs는 내부 카운터를 자동으로 0 으로 초기화하며, 녹화 중에 ~F3~ 키를 누를 때마다 Emacs는 해당 카운터를 삽입한 뒤 내부 카운터를 1씩 증가시킵니다. 물론 이 카운터를 창의적으로 활용할 수 있는 방법은 많지만, 번호가 매겨진 목록을 만드는 것이 가장 대표적인 예입니다.

| 키 바인딩           | 설명                     |
| ~C-x C-k C-a~       | 카운터에 값 추가         |
| ~C-x C-k TAB, F3~   | 카운터 삽입              |
| ~C-x C-k C-c~       | 카운터 설정              |
| ~C-x C-k C-f~       | 포맷 카운터 설정         |
| ~C-x C-k q , C-x q~ | 녹화 중 사용자 입력 요청 |

위의 카운터 명령어들은 이뿐만 아니라 좀 더 많은 기능을 수행합니다. ~C-x C-k C-a~ 는 카운터에 숫자를 더하고, 반대로 음수를 입력하면 카운터에서 숫자를 뺍니다. ~F3~ 과 ~C-x C-k TAB~ 은 모두 카운터 값을 삽입하고 1 을 더하지만, 범용 인자 ~C-u~ 를 지정하면 마지막 숫자를 삽입하고 카운터를 증가시키지 않습니다. 이는 같은 숫자를 연속해서 여러 번 사용할 때 유용합니다.

#+BEGIN_QUOTE
*Counter Resets & Registers* :
카운터는 사용자가 명시적으로 초기화하거나
새로운 매크로를 기록할 때만 초기화됩니다.

카운터 값은 매크로 재생 사이에도 유지됩니다.

마찬가지로, 원한다면 Emacs의 레지스터를 사용해서
값을 추적하거나 더하거나 뺄 수도 있습니다.

레지스터는 매크로 메커니즘과 독립적으로 작동하며,
매크로가 초기화될 때 함께 초기화되지 않습니다.
#+END_QUOTE

~C-x C-k C-c~ 명령은 ~C-x C-k C-a~ 같이 단순히 카운터를 증가시키는 것과 달리, 카운터를 명시적으로 설정합니다. 마지막으로, ~C-x C-k C-f~ 는 아마 카운터 명령 중 가장 고급 기능일 것입니다. 이 명령은 포맷 문자열을 받아 이 문자열에 따라 카운터를 포맷팅합니다(포맷 문자열에 대한 자세한 내용은 ~C-h f format~ 을 입력합니다). 예를 들어, 숫자를 10진수로 변환하거나 앞뒤에 0을 채워 출력할 수 있으며, 단순한 숫자와 텍스트를 삽입하는 등 이와 유사한 작업도 가능합니다. ~C-x C-k C-c~ 에 전달하는 텍스트를 따옴표로 묶지 않도록 주의하시기 바랍니다. 따옴표는 자동으로 이스케이프 처리됩니다.

가장 눈에 띄는 명령은 ~C-x C-k q~ (또는 간단히 ~C-x q~)입니다. 이 명령을 호출하면, Emacs는 매크로 기록에서 해당 단계를 표시하고 계속 진행하기 전에 사용자에게 조언을 요청합니다. 즉, 매크로를 일시적으로 중지하고 사용자에게 프롬프트를 표시하는 것입니다.

| Query 키 바인딩 | 설명                              |
| ~y~             | 평소대로 계속 진행                |
| ~n, DEL~        | 매크로의 나머지 부분을 건너뜁니다 |
| ~RET~           | 매크로를 완전히 중지합니다        |
| ~C-l~           | 화면을 중앙에 맞춥니다            |
| ~C-r~           | 재귀 편집 모드로 들어갑니다       |
| ~C-M-c~         | 재귀 편집 모드를 종료합니다       |

~y~ 와 ~n~ 은 현재 매크로의 반복을 계속하거나 중지합니다. 따라서, 연속해서 여러 매크로를 실행 중인 경우, ~N~ 을 누르면 나머지 매크로를 건너뛰고 해당 매크로의 시작 부분에서 다시 시작합니다. ~Y~ 는 그저 평소처럼 실행을 계속합니다. ~RET~ 는 매크로를 완전히 중지하고 이후의 매크로 재생을 멈춥니다.

화면을 다시 중앙에 맞출 수 있습니다. 이는 일반적인 ~C-l~ 명령과 다르며, Emacs는 커서를 버퍼 중앙에 위치시킵니다.

*재귀 편집* : 재귀 편집은 고급 주제입니다. 재귀 편집(~C-r~) 모드로 진입하면, Emacs는 Isearch, 검색 및 바꾸기 또는 매크로 같은 현재 진행 중인 명령을 일시 중지하고 제어권을 사용자에게 돌려줍니다. 그러면 사용자는 평소와 같이 편집을 계속하거나 Emacs를 사용할 수 있지만, 언제든지 ~C-M-c~ 를 입력하면 Emacs는 사용자가 진입했던 이전 재귀 단계로 즉시 돌아가서 그 지점부터 작업을 재개합니다. 재귀 편집은 합리적인 범위 내에서 원하는 만큼 중첩할 수 있으며, 재귀 편집 상태일 때는 모드라인에 대괄호([])가 표시되어 이를 확인할 수 있습니다. ~ESC ESC ESC~ 를 입력하면 Emacs가 모든 재귀 편집 레벨을 강제로 종료하게 할 수 있습니다. 다른 대부분의 경우와 달리, ~C-g~ 는 재귀 편집에서 빠져나오지 않는다는 점에 유의하시기 바랍니다.

그렇다면 실제로는 어떻게 사용할까요? 한 가지 예로, 검색이나 매크로 재생 중에 텍스트를 편집하거나, 이메일을 보내거나, 현재 작업을 일시적으로 중단할 필요가 있다는 것을 깨달았을 때를 들 수 있습니다. ~C-r~ 을 사용하면 이를 수행할 수 있습니다. 작업이 모두 끝나면 ~C-M-c~ 를 입력해서 중단 지점부터 다시 이어갈 수 있습니다. 이것은 매우 강력한 기능으로, 이 책의 다른 모든 내용을 마스터한 후에 알아두면 유용합니다.


**** Saving and Recalling
매크로는 Emacs의 다른 부분(킬링 링이나 되돌리기 링 등)에서 익숙하게 접했을 법한 개념인 매크로 링에 저장됩니다. 새 매크로를 생성하면 별도의 조치 없이도 기존 매크로가 자동으로 매크로 링에 저장됩니다. 아래 명령어를 사용하면 매크로 링에 매크로를 저장하고 불러올 수 있으며, 매크로를 편집하고 키에 바인딩하는 등의 작업을 수행할 수 있습니다.

| 키 바인딩              | 설명                           |
| ~C-x C-k C-n~          | 매크로 링을 다음 항목으로 순환 |
| ~C-x C-k C-p~          | 매크로 링을 이전 항목으로 순환 |
| ~C-x C-k n~            | 마지막 매크로에 이름 지정      |
| ~C-x C-k b~            | 마지막 매크로를 키에 바인딩    |
| ~C-x C-k e~            | 마지막 매크로 편집             |
| ~C-x C-k l~            | 최근 300개의 키 입력 편집      |
| ~M-x insert-kbd-macro~ | 매크로를 elisp 코드로 삽입     |

~C-x C-k C-n~ 과 ~C-x C-k C-p~ 모두 매크로 링을 순환합니다. 이 작업을 수행하면 Emacs가 현재 활성화된 매크로가 어느 것인지 알 수 있도록 매크로의 일부를 표시해 줍니다.

~C-x C-k n~ 을 사용해서 매크로에 이름을 지정할 수 있습니다. 매크로를 파일에 저장하려면 먼저 이 작업을 수행해야 합니다. 사용자 init 파일을 열고 ~M-x insert-kbd-macro~ 를 호출하면 Emacs가 코드 생성된 버전의 매크로를 삽입해 줍니다. 이름이 지정되고 삽입된 매크로는 ~M-x~ 를 사용해서 호출할 수 있는 명령으로 변환됩니다. 또한 ~C-x C-k b~ 를 사용해서 현재 세션 동안만 일시적으로 키에 매핑할 수도 있습니다.

#+BEGIN_QUOTE
*Naming Things* :
일관된 명명 규칙을 정하는 것을 추천합니다.
LISP는 공백을 사용할 수 없지만 그 외의 거의 모든 문자를 사용할 수 있습니다.
하지만, 저는 항상 제 이니셜인 ‘mp-’ 로 시작하는데, 이렇게 하면
~C-h a~ 및 관련 단축키들과 결합할 수 있기 때문입니다.

이제 Emacs의 자체 문서화 기능을 통해
제가 직접 만든 모든 명령어를 쉽게 찾을 수 있습니다.
#+END_QUOTE

실수를 했다면 기존 매크로를 편집할 수 있습니다. ~C-x C-k e~ 명령을 실행하면 매크로 명령어 목록이 표시되며, 이 목록을 일반 텍스트처럼 편집할 수 있습니다. ~C-c C-c~ 를 눌러 변경 사항을 적용할 수 있습니다.

#+BEGIN_QUOTE
*Lossage* :
Emacs는 사용자가 입력한 마지막 300개의 문자와 명령을
‘lossage’ 라고 하며 기억합니다.
~C-h l~ 을 입력하면 이 문자 목록을 확인할 수 있습니다.

~M-x open-dribble-file~ 을 입력하면 Emacs에서 입력한
모든 키 입력을 저장할 수도 있습니다.
단, 비밀번호 같은 민감한 정보도 포함되므로 주의해야 합니다.

lossage 는 키 입력이 속한 명령도 함께 표시합니다.
버퍼의 활성 모드 같은 요소에 따라 키가 속한 명령은 달라질 수 있습니다.
따라서, 해당 키가 실행된 버퍼나 모드 외부에서 키를 조회할 때는
이런 점에 유의하시기 바랍니다.

키보드 매크로를 소급해서 생성하고 싶을 때는 lossage 기능을 활용합니다.
~M-x kmacro-edit-lossage~ 명령을 사용하면 입력 내용을 기반으로
매크로를 생성할 수 있습니다.
#+END_QUOTE


**** Practical Uses for Keyboard Macros
키보드 매크로라 하면 가장 먼저 떠오르는 것은 단순한 텍스트 자동화지만, Emacs의 매크로 시스템은 그보다 훨씬 더 많은 기능을 갖추고 있습니다.

간과되기 쉬운 한 가지 측면은 여러 복잡한 작업을 결합한 뒤, 나중에 재사용할 수 있도록 매크로에 이름을 지정하고 저장할 수 있다는 점입니다. 이 기능 자체만으로는 그리 놀랍거나 주목할 만한 특징으로 보이지 않을 수 있습니다. 하지만, 매크로 없이는 (아직 갖추지 못했을 수도 있는!) 심도 있는 Emacs나 elisp 지식이 필요한 수많은 지루한 작업을 매크로를 통해 원활하게 처리할 수 있다는 사실을 깨닫게 되면 이야기가 달라집니다.

*원하는 대로 창 환경을 설정하는 방법* : 특정 파일을 열어 특정 방향으로 표시하려면, 키보드 매크로를 사용하면 됩니다. 먼저 ~C-x 1~ 을 눌러 창을 모두 비운 다음, 매크로를 사용해서 원하는 파일을 엽니다. 원하는 대로 창을 분할하고 관심 있는 버퍼로 전환한 후, 매크로를 종료하면 됩니다. 이제 원할 때마다 이 설정을 자유롭게 불러올 수 있습니다.

*자주 사용하는 텍스트 편집 작업을 위한 매크로 작성* : 일괄 변경하고 싶은 텍스트 패턴이 있거나, 그날의 작업량에 따라 반동적으로 처리하고 싶을 수도 있습니다. 예를 들어, ~M-x rgrep~ 을 사용해서 변경할 파일들을 찾아내고, 키보드 매크로를 사용해서 ~*grep*~ 버퍼의 각 항목을 순차적으로 처리하면서 검색 및 교체 패턴을 적용할 수 있습니다.

단순히 녹화를 시작하고 ~M-g M-n~ 을 입력해서 Emacs가 결과를 가져오는 소스에서 다음 일치 항목을 선택하고, 텍스트 편집을 수행한 후 녹화를 종료하면 됩니다. 이제 ~C-x e~ 를 사용해서 매크로를 호출할 때마다 항목이 하나씩 처리되며, 이 방식은 매우 일반적이라서 grep 대신 ~occur, M-x compile~ 및 ~M-g M-n / M-g M-p~ 를 사용하는 다른 소스를 대체할 수 있습니다.

*복잡한 결정은 사람이 내리도록 미룹니다* : ~C-x C-k q~ 를 사용해서 쿼리 단계를 삽입할 수 있으므로, 매크로가 진행되기 전에 모호하거나 복잡한 선택 사항이 있다는 것을 알고 있다면, 매크로의 주요 지점에서 이를 자유롭게 삽입해서 매크로를 중단할지, 변경 사항을 건너뛸지, 아니면 재귀적 편집 레이어로 들어가서 버퍼를 수동으로 편집한 후 매크로를 계속할지 결정할 수 있습니다. 심지어 포인트를 이동하거나, 재개하기 전에 버퍼 텍스트를 변경할 수도 있습니다.

*매크로 내에서 매크로 호출* : 매크로 내에서 매크로를 호출할 수 있습니다. 그러니 작고 재사용 가능한 매크로 로직 조각들을 만들어 두고, 이를 호출하는 매크로를 하나 만들어 보는 건 어떨까요? 이름을 지어두면–이름이 없더라도 매크로 링을 사용하면– 원할 때 언제든지 호출할 수 있습니다.

*프롬프트에 적절한 기본값 채우기* : 같은 명령을 반복 입력할 경우, 이를 간단한 키보드 매크로로 만들 수 있습니다. 프롬프트에 쿼리 마커를 삽입하고, ~C-r~ 을 눌러 재귀 편집 모드로 진입해서 녹화 시 입력한 기본값을 덮어쓸 수 있습니다. 프롬프트에 입력한 내용을 수정한 후, ~C-M-c~ 를 눌러 매크로로 돌아갈 수 있습니다. Emacs는 프롬프트에 있더라도 실행 중인 매크로를 매끄럽게 수정할 수 있게 해줍니다. 프롬프트는 미니버퍼에 표시되는데, 미니버퍼 역시 버퍼입니다. 이는 Emacs 전반에 걸쳐 개념의 대칭성과 재사용성을 다시 한번 강조해 줍니다.

매크로는 배울 가치가 충분하며, 보시다시피 엘리스프(Elisp)나 사용자 정의 설정만으로는 문제를 해결하는 방법을 모를 때 유연한 대안이 될 수 있습니다. 다만, Emacs와 직접 상호작용해서 사람이 직접 수행할 수 있는 작업이라면, 매크로를 기록해 두면 Emacs가 이를 반복해 줄 수 있다는 점을 기억해 두시기 바랍니다.



** Text Expansion 
Emacs는 텍스트를 확장해 주는 여러 가지 내장 도구와 그만큼 많은 타사 도구가 있습니다. 이들 모두의 용도는 약간씩 다르지만, 목표는 타이핑을 최소화하고 자동화를 극대화하는 것입니다.

다음은 Emacs에서 사용할 수 있는 도구들 중 일부입니다:

*Abbrev*: 모드별 또는 전역 수준에서 func 를 function 같이 약어 확장합니다. 매우 단순한 확장 메커니즘으로, 주요 장점은 사용자가 입력하는 동안 눈에 띄지 않게 작동하며 오타를 수정하거나 약어를 확장해 준다는 점입니다. Emacs의 다른 많은 기능과 마찬가지로, 이 기능도 화려한 그래픽 효과는 거의 없습니다. 키보드 단축키를 확장할 때 사용자의 주의를 산만하게 하는 회전하는 그래픽이나 기타 시각적 잡음은 없습니다. 사실, 일부러 찾지 않는 한 전혀 눈치채지 못할 가능성이 높습니다.

일반적으로 오타 수정 같이 의미상 모호함이 없는 교정을 위해 이 기능을 사용합니다.

*DAbbrev, 또는 동적 약어* : Abbrev 와 유사하지만, 커서 위치의 단어가 무엇으로 확장될 수 있는지 동적으로 검색해서 이전 단어를 확장합니다. 예를 들어, 함수 정의가 많이 있는 버퍼에서 func 를 입력하면, 확장 메커니즘을 수동으로 실행했을 때 DAbbrev 가 이를 자동으로 function 으로 확장해 줍니다.

*Hippie expand* : 단어뿐만 아니라 전체 줄, Lisp 심볼, Abbrev 약어, 파일 이름 및 파일 경로까지 확장하는, DAbbrev 를 대체하는 강력한 기능입니다. 이 기능은 매우 강력하며, Emacs에 기본으로 포함된 DAbbrev 를 곧바로 대체할 수 있습니다.

*Skeletons* : 프롬프트, 영역 감싸기, 들여쓰기, 포인트 위치 지정 같은 간단한 elisp 기본 기능들을 Abbrev 와 유사한 확장 기능과 결합한 복잡한 템플릿 도구입니다. 20년 넘게 Emacs의 핵심 기능으로 자리 잡아 왔음에도 거의 사용되지 않습니다. 정말 안타까운 일입니다. 매우 강력한 도구지만, 사용하려면 인내심이나 Elisp 지식이 필요하기 때문에 거의 아무도 사용하지 않았습니다.

*Tempo* : Emacs에 기본으로 포함된 또 다른 템플릿 도구입니다. Skeletons 과 유사합니다.

*YASnippet* : 텍스트 에디터 TextMate 의 템플릿 도구에서 영감받은 타사 패키지 템플릿 도구입니다. (물론 TextMate 자체도 그 이전의 다른 도구로부터 많은 부분을 차용했습니다.) 간단한 템플릿 언어를 사용해서 탭이나 공백 키로 호출할 수 있는 스니펫을 생성하고, 이를 편집 가능한 템플릿으로 확장할 수 있습니다. Skeletons 과 유사하지만 사용하기 훨씬 더 쉽다고 할 수 있습니다.

*Autoinsert* :  특정 파일 형식과 일치하는 새 파일을 생성할 때 Skeletons 과 유사하게 템플릿을 삽입합니다. html, head 같은 HTML 파일의 기본 내용을 자동으로 생성할 때 유용합니다.

위의 모든 선택지 중에서, 저는 템플릿 작업에는 ~YAsnippet~ 에 주목할 것입니다. 이 도구는 메이저 모드들을 위한 다양한 스니펫을 제공하며, 생산성을 크게 높여주는 ~Hippie Expand~ 도 주목할 만합니다.

특별한 이유가 없다면, 현재로는 Tempo 나 Skeletons 을 배울 가치는 없습니다. Abbrev 는 앞서 언급한 고급 텍스트 확장 도구들의 기능을 갖추지 못했기 때문에 단어 대체 용도로만 적합합니다. YASnippet 과 Hippie Expand 를 작업 흐름에 통합한 후에는, 필요하다고 느껴진다면 Abbrev 와 Autoinsert 를 추가할 수 있습니다.


*** Abbrev
Abbrev 는 워드 프로세서의 자동 수정 기능에 안성맞춤인 도구입니다. 저는 이 도구를 사용해서 흔히 틀리는 철자를 수정하거나, ‘resume’ 같은 단어를 ‘résumé’ 로 바꾸곤 합니다. 하지만, 소프트웨어 개발에서 사용하는 복잡한 텍스트 확장 같은 고급 기능을 원한다면, 이 도구는 분명 적합하지 않습니다.

abbrev 가 효과적인 이유 중 하나는 단순함에 있습니다. 이 도구는 시각적인 방해 요소 없이 단어를 확장해 주며, 사실 저는 단어가 수정되는 것을 거의 눈치채지 못합니다.

| 키 바인딩   | 설명               |
| ~C-x a l~   | 모드별 약어 추가   |
| ~C-x a g~   | 전역 약어 추가     |
| ~C-x a i l~ | 모드별 역약어 추가 |
| ~C-x a i g~ | 전역 역약어 추가   |

~C-x a g~ 또는 ~C-x a l~ 로 약어를 추가할 때, Emacs는 커서 위치 바로 앞의 단어를 확인해서 이를 대체 단어로 사용합니다. 즉, 저조차 헷갈리긴 하지만, ‘트리거 단어’ 가 아니라 ‘확장하려는 단어’ 를 사용한다는 뜻입니다. 따라서, resume 을 résumé 로 바꾸려면, résumé 를 입력한 뒤 커서를 단어 뒤에 두고, ~C-x a g~ 를 누른 다음 resume 을 입력합니다. resume 을 입력한 후 스페이스 바를 누르면, Emacs는 이를 ~résumé~ 로 바꿔줍니다.

반대(역) 명령은 정반대의 동작을 합니다. resume 을 입력하고 ~C-x a i g~ 를 누른 뒤, résumé 라고 대답하면 Emacs는 resume 을 résumé 로 확장해 줍니다.


*** DAbbrev and Hippie Expand
Hippie Expand 는 정말 훌륭합니다. 이 도구는 특정 지점의 텍스트를 사용자가 의도하는 내용으로 확장해 주는, 거의 초자연적인 능력을 갖고 있습니다. Hippie Expand 에 대해 이야기하기 전에, 먼저 Emacs의 기본 동적 약어 도구이자 Hippie Expand 의 동급인 DAbbrev 를 어떻게 사용하는지 살펴보겠습니다:

| 키 바인딩 | 설명                      |
| ~M-/~     | 해당 위치에서 단어를 확장 |
| ~C-M-/~   | 확장 후 완성 후보 표시    |

~M-/~ 키는 입력하기 쉬우며, 이 키를 반복해서 누르면 제안된 단어 목록을 순차적으로 확인할 수 있습니다. 명령을 충분히 반복하면 원래 단어로 되돌아갑니다. 또한 선택지가 많을 경우, ~C-M-/~ 명령은 가능한 한 많이 자동 완성하고, 여전히 선택지가 하나 이상 남아 있으면 완성 후보 목록을 표시합니다.

DAbbrev 는 스마트하지 않습니다. 버퍼에 있는 다른 단어들을 살펴보고, 현재 위치의 단어를 그 중 하나로 완성하려고 시도합니다. 그렇다고 해서 이 기능이 쓸모없다는 것은 아닙니다. 나름의 용도가 있긴 하지만, Hippie Expand 가 훨씬 더 낫다는 뜻입니다.

Hippie Expand 를 효과적으로 사용하려면 DAbbrev 를 대체해야 합니다. 두 기능을 함께 사용할 수 있지만, 사실 서로 전혀 보완적이진 않기 때문입니다. 다음을 init 파일에 추가해서 Hippie Expand 로 전환합니다:

~(global-set-key [remap dabbrev-expand] 'hippie-expand)~

Hippie Expand 는 단순한 단어 확장 그 이상을 수행합니다. 변수 ~hippie-expand-try-functions-list~ 는 ~M-/~ 을 호출할 때 커서 위치의 텍스트를 인수로 받아 Hippie Expand 가 호출할 확장 함수들의 정렬된 목록입니다.

Hippie Expand 에서 제가 가장 마음에 드는 점은 파일 이름 자동 완성 기능입니다. 이 기능은 셸의 TAB 자동 완성 방식과 똑같이 작동합니다. ~M-/~ 을 입력하면 Hippie Expand 가 현재 위치의 파일 이름이나 디렉터리를 자동 완성해 줍니다. 코드, 설정 파일, 또는 문서에 절대 경로나 상대 경로의 파일 이름을 삽입할 일이 있다면—Hippie Expand 가 여러분의 작업을 훨씬 수월하게 만들어 줄 것입니다.

또 다른 훌륭한 기능은 전체 줄을 완성해 준다는 점입니다. 완성할 항목이 없을 경우 단어 완성으로 전환되며, Elisp을 자주 작성한다면 Hippie Expand 는 커서 위치의 텍스트가 Elisp 심볼일 가능성을 추측해서 자동으로 완성해 줍니다.

DAbbrev 와 마찬가지로, ~M-/~ 을 반복 호출하면 모든 가능한 일치 항목을 순환하면서 확인하지만, ~C-M-/~ 은 DAbbrev 가 찾은 완성 항목만 표시합니다. Hippie Expand 는 이에 상응하는 완성 목록이 없습니다.

~M-/~ 을 능숙하게 사용하려면 약간의 연습이 필요합니다. 호출 시 적용되는 확장 규칙에 대한 감각을 키워야 합니다. Hippie Expand 는 시간을 크게 절약해 주므로 배우는 데 투자할 가치는 충분합니다.


**** Customizing Hippie Expand
Hippie Expand 가 텍스트를 확장하는 방식을 변경할 수 있습니다. 이를 위해서는 ~hippie-expand-try-functions-list~ 변수를 사용자 정의하면 되지만, 새로운 try 함수를 추가하려면 해당 함수 이름을 알아야 합니다.

try 함수 목록을 찾으려면 다음을 수행합니다:

- 소스 코드의 주석을 읽습니다(~M-x find-library~ 를 실행한 후, hippie-exp 를 입력하고 문서를 읽습니다). 하지만, 라이브러리 이름은 어떻게 찾을 수 있을까요? 좋은 방법은 명령어(~hippie-expand~)를 설명(describe)해 보는 것입니다. 그러면 Emacs가 해당 심볼을 찾은 라이브러리의 이름을 알려줄 것입니다.

- Apropos 를 사용합니다. try 함수의 이름을 살펴보고 ~M-x apropos-function~ 을 사용해서 유사한 함수를 검색합니다.

항상 그렇듯이 두 방법 모두 다른 결과를 보여주므로 두 가지 모두 시도해 보시기 바랍니다.


** Indenting Text and Code
새로운 프로그래밍 언어가 등장하면, 기본적인 구문 강조와 들여쓰기 기능을 제공하는 Emacs의 메이저 모드가 거의 동시에 등장합니다. 이것이 가능한 이유 중 하나는 다른 메이저 모드의 들여쓰기 엔진을 상속(또는 재사용)할 수 있을 뿐만 아니라, Emacs에 내장된 일반적인 들여쓰기 엔진도 활용할 수 있기 때문입니다.

기본적으로 Emacs는 사용자가 실행 중인 메이저 모드의 규칙에 따라 들여쓰기를 시도합니다. 구버전 Emacs는 이를 위해 직접 설정해야 했는데, 기본적으로 인덴트를 적용하는 경우가 드물었기 때문에 초보자는 답답한 경험이었습니다. 하지만, 오늘날에는 더 이상 문제가 되지 않습니다. Emacs는 '전기 인덴트(electric indentation)' 라고 불리는 기능을 사용해서 인덴트를 자동으로 적용합니다. 이 기능을 끄려면 ~electric-indent-mode~ 를 사용자 정의할 수 있습니다.

들여쓰기 엔진이 정확히 어떻게 작동하는지는 메이저 모드와 개발자의 취향 및 개인적인 선호도에 따라 결정됩니다. 특히 C 계열 언어로 코딩할 때 들여쓰기 방식이 마음에 들지 않을 수도 있습니다. 이 경우 Emacs 매뉴얼(해당 메이저 모드가 Emacs에 포함된 경우)이나 소스 파일 내의 문서 또는 주석을 참고해야 합니다. Emacs는 들여쓰기 사용자 지정을 위한 일률적인 접근 방식이 없습니다. 이를 수행하는 방법에 대한 지침은 문서를 참조해야 합니다.


*** TAB : Indenting the Current Line
~TAB~ 키를 누르면, Emacs는 보통 ~indent-for-tab-command~ 를 호출합니다. 이 명령은 코드를 들여쓰기하거나, 커서 위치의 단어를 ~TAB~ 자동 완성하려고 시도하는 일반적인 대리 명령입니다.

| 키 및 명령어         | 설명                                                 |
| ~TAB~                | 메이저 모드의 들여쓰기 명령을 사용해서 줄을 들여쓰기 |
| ~M-i~                | 다음 탭 정지 위치에 공백이나 탭을 삽입               |
| ~M-x edit-tab-stops~ | 탭 정지 위치를 편집                                  |

일부 메이저 모드(major mode)는 ~TAB~ 키의 동작을 재정의하고 대신 자신만의 특화된 들여쓰기 명령을 호출합니다. 대표적인 예로 C 메이저 모드가 있습니다. 하지만, ~TAB~ 키를 누르면 (또는 ~M-x indent-for-tab-command~)을 누르면, 해당 모드의 휴리스틱이 들여쓰기 한다고 판단할 경우, ~indent-line-function~ 변수에 저장된 들여쓰기 함수를 호출합니다. 여기서 장점은 ~indent-for-tab-command~ 의 일반적인 성격에 있습니다—이 명령은 단순히 작업을 완성 명령이나 들여쓰기 명령 중 하나로 전달하기 위해 존재합니다.

~tab-always-indent~ 변수는 ~TAB~ 키를 누를 때 Emacs의 동작을 제어합니다. 일반적으로 단순히 들여쓰기만 수행하지만, 드물게 사용되기는 하지만 자동 완성 메커니즘도 갖추고 있습니다.

#+BEGIN_QUOTE
*Disabling tab characters* :
탭 문자 사용을 원치 않고 공백을 선호한다면,
~indent-tabs-mode~ 변수를 사용자 지정합니다. 
#+END_QUOTE

마지막으로, Emacs가 들여쓰기를 할 때는 앞서 언급한 ~indent-line-function~ 내의 함수를 호출합니다. 기본 함수는 ~indent-relative~ 로, 실제 탭 문자를 삽입하는 명령어입니다. ~text-mode~ 나 ~fundamental-mode~ (새로 생성된 빈 버퍼의 기본 모드) 같은 모드들은 ~indent-relative~ 를 사용합니다. 대부분의 프로그래밍 모드들은 그렇지 않습니다.

#+BEGIN_QUOTE
*Changing the amount of indentation* :
~tab-width~ 변수는 각 탭이 차지하는 공백의 문자 수를 제어합니다.
또한 ~indent-tabs-mode~ 를 비활성화한 경우 사용할 공백의 양도 제어합니다. 
#+END_QUOTE

Emacs는 탭 정지점(tab stop)이라는 개념도 있는데, ~M-x edit-tab-stops~ 을 입력하고 Emacs가 탭 포인트를 설정할 위치에 ~:~ 문자를 삽입하면 탭 정지점을 편집할 수 있습니다. 이후 ~M-i~ 를 호출하면(이 명령은 ~M-x tab-to-tab-stop~ 을 호출합니다), 공백과 탭 문자를 사용해서 탭 정지점이 삽입됩니다.


*** Indenting Regions
리전(region) 들여쓰기는 훨씬 더 까다롭습니다. 블록 들여쓰기가 프로그램의 흐름을 결정하는 상황에서, 파이썬 코드의 리전을 어떻게 안전하게 들여쓰면 될까요? 정답은 —그냥 하지 않는 것입니다. 영역 들여쓰기 명령은 두 가지 유형이 있습니다. 메이저 모드의 들여쓰기 엔진에 조언을 구하는 “지능형” 명령—HTML이나 C 같은 언어는 잘 작동하지만— 그리고 그 외의 경우를 위한 평범한 고정 폭 들여쓰기입니다.

| 키 및 명령어 | 설명                                                              |
| ~TAB~        | 메이저 모드에 따라 줄이나 영역의 들여쓰기를 조정합니다            |
| ~C-M-\~      | 메이저 모드의 영역 들여쓰기 명령을 사용해서 들여쓰기를 조정합니다 |
| ~C-x TAB~    | 고정된 들여쓰기를 적용합니다                                      |

이상적인 환경에서는, 선택 영역이 활성화된 상태에서 ~TAB~ 키를 누르면 들여쓰기를 다시 설정할 수 있습니다. 안타깝게도, Emacs가 이를 지원하지 않을 수도 있고, 일부 프로그래밍 언어는 올바른 들여쓰기 위치를 물리적으로 파악하는 것이 불가능할 수도 있습니다. ~TAB~ 키를 누르는 것은 줄 들여쓰기와 거의 동일한 규칙을 따릅니다. Emacs는 ~indent-line-function~ 에 따라 들여쓰기를 시도하며, 이것이 실패할 경우 단순히 ~TAB~ 문자를 삽입합니다(또는 ~indent-tabs-mode~ 를 비활성화한 경우 공백을 삽입합니다).

~C-M-\~ 를 입력하면 해당 영역을 명시적으로 들여쓰기합니다. 일부 모드는 ~TAB~ 과 동일하게 작동하지만, 다른 모드는 그렇지 않습니다. 명령에 숫자 인수를 지정하면, 해당 열(즉, 문자 수)만큼 영역을 들여쓰고, Emacs는 (설정되어 있다면) fill prefix 도 사용해서 그에 따라 텍스트를 채웁니다. ~C-M-\~ 는 fill prefix 를 존중하므로 사용해 볼 가치가 있습니다. 하지만, 고정된 열 수만큼 들여쓰기하려면 ~C-x TAB~ 을 사용해야 합니다.

~C-x TAB~ 은 영역을 특정 열의 수만큼 명시적으로 들여쓰기합니다. 이 명령은 음수 및 숫자 인자도 받습니다. 하지만, 인자를 전달하지 않으면, Emacs는 화살표 키로 제어되는 들여쓰기 모드로 전환되어 ~S-<left>~ 와 ~S-<right>~ 를 사용해서 영역을 대화식으로 들여쓰게 해줍니다.



** Sorting and Aligning
텍스트 정렬과 배열은 모두 매우 흔한 작업이라 Emacs는 이 두 가지 기능을 모두 수행하는 전용 명령어 세트가 마련되어 있습니다.


*** Sorting
Emacs의 정렬 기능은 명령줄 유틸리티 sort 와 유사하게 작동합니다. 모든 명령은 줄 단위로 정렬하지만, 단락 단위 정렬(oneparagraph) 명령만 예외입니다.

| 명령어                    | 설명                                          |
| ~M-x sort-lines~          | 알파벳순으로 정렬                             |
| ~M-x sort-fields~         | 필드를 사전순으로 정렬                        |
| ~M-x sort-numeric-fields~ | 필드를 숫자순으로 정렬                        |
| ~M-x sort-columns~        | 열을 알파벳순으로 정렬                        |
| ~M-x sort-paragraphs~     | 단락을 알파벳순으로 정렬,                     |
| ~M-x sort-regexp-fields~  | 정규 표현식으로 정의된 필드를 사전순으로 정렬 |

~M-x sort-lines~ 는 오름차순으로 정렬하지만, 범용 인수를 지정해서 호출하면 정렬 순서가 반대로 바뀝니다.

줄 단위로 정렬할 때, Windows 환경이 아닌 한 Emacs는 (속도가 훨씬 빠르기 때문에) sort 함수를 호출하지만, Microsoft Windows 환경에는 Emacs가 내부적으로 정렬을 수행합니다.

#+BEGIN_QUOTE
*Lexicographic and numeric* :
사전순 정렬은 대부분의 정렬 알고리즘이 일반적으로 작동하는 방식입니다.
이 알고리즘들은 각 문자의 문자 코드를 확인해서 그 순서대로 정렬합니다.

이는 숫자를 제외하고는 대부분의 경우에 잘 작동합니다.
사전순으로 볼 때, 숫자 4는 숫자 23보다 뒤에 옵니다.
왜냐하면, 4의 서수가 23의 서수 2보다 크기 때문입니다.

숫자를 올바르게 정렬하려면 ~M-x sort-numeric-fields~ 를 사용해야 합니다. 
#+END_QUOTE

~M-x sort-fields~ 및 ~M-x sort-numeric-fields~ 를 사용해서 사전순 또는 숫자순으로 정렬할 수 있습니다. 단, 정렬할 열을 지정해야 합니다. 이를 위해 숫자 인자(1부터 시작)를 전달해서 해당 열로 정렬합니다. 열은 공백으로 구분되며, 하나 이상의 공백이 연속되어 나오면 열 구분자로 간주됩니다.

세 번째 열을 정렬하려면 ~M-3 M-x sort-fields~ 를 입력합니다. 한 번에 하나의 열만 정렬할 수 있으며, 앞서 언급했듯이 각 열은 공백으로 구분되어야 합니다. 열 구분자를 변경하려면 ~M-x sort-regexp-fields~ 를 사용해야 합니다.

~M-x sort-columns~ 을 사용해서 열별로 정렬하는 것이 두 개 이상의 열로 정렬할 수 있는 유일한 방법이며, 이 경우 연속된 열만 정렬할 수 있습니다. 이를 사용하려면 정렬하려는 시작 및 끝 열에 커서와 마크를 위치시키면 커서 위치부터 마크까지의 모든 행이 정렬됩니다. 공백으로 구분되지 않은 항목을 정렬할 경우, ~M-x sort-regexp-fields~ 를 사용해야 합니다. 이 명령은 elisp에 대한 탄탄한 실무적 지식이 필요하기 때문에 상당히 복잡합니다. 또한 영역을 부분적으로 정렬하기도 해서 텍스트가 엉망이 될 수 있습니다.

다음과 같은 제품 CSV 파일을 가정합니다:

#+BEGIN_SRC
Price,Product
$3.50,Cappuccino
$4.00,Caramel Latte
$2.00,Americano
$2.30,Macchiato
...
#+END_SRC

이 데이터는 공백으로 구분되지 않았기 때문에 다른 정렬 명령어로는 정렬할 수 없습니다. 이런 데이터를 정렬하려면 ~M-x sort-regexp-fields~ 명령을 사용해야 합니다. Emacs 내부 정렬 루틴은 키(즉, 필드 같이 정렬에 사용하는 기준)와 레코드(일반적으로 전체 줄)가 필요합니다.

위의 예제를 정렬하는 방법은 다음과 같습니다:

#+BEGIN_SRC
M-x sort-regexp-fields

Record: ^\([^,]+\),\([^,]+\)$
Key: \1
#+END_SRC

이 명령은 먼저 레코드를 쉼표로 구분된 두 개의 캡처 그룹(각 열에 하나씩)으로 정의합니다. 다음 단계는 정렬 기준이 될 키(이 경우 가격이 포함된 첫 번째 열)를 선택하는 것입니다.

결과는 다음과 같습니다:

#+BEGIN_SRC
Price,Product
$2.00,Americano
$2.30,Macchiato
$3.50,Cappuccino
$4.00,Caramel Latte
#+END_SRC

정규 표현식을 이용한 정렬은 자주 사용할 일은 아니지만, 필요할 때는 매우 유용한 도구입니다. 한 가지 주의할 점은 한 줄을 부분적으로만 정렬할 수도 있다는 것입니다. 검색 조건이 다음과 같다면:

#+BEGIN_SRC
M-x sort-regexp-fields

Record: ^\([^,]+\)
Key: \1
#+END_SRC

그리고 원본 텍스트를 정렬하면 출력은 다음과 같습니다:

#+BEGIN_SRC
$2.00,Cappuccino
$2.30,Caramel Latte
$3.50,Americano
$4.00,Macchiato
#+END_SRC

첫 번째 열은 정렬되지만, 두 번째 열은 변경되지 않았다는 점에 유의하시기 바랍니다! 즉, 가격은 정렬되지만 관련된 상품명은 정렬되지 않았습니다. 주의하시기 바랍니다.


*** Aligning
Emacs의 텍스트 정렬 기능은 양쪽 정렬과 열 단위 정렬 모두를 포함합니다. 사실, Emacs의 정렬 엔진은 매우 정교해서 정규식 패턴을 기반으로 코드를 자동으로 정렬하거나 양쪽 정렬할 수 있습니다.

| 명령어              | 설명                                  |
| ~M-x align~         | 정렬 규칙에 따라 영역을 정렬합니다.   |
| ~M-x align-current~ | 정렬 규칙에 따라 섹션을 정렬합니다.   |
| ~M-x align-regexp~  | 정규 표현식에 따라 영역을 정렬합니다. |

정렬 명령어는 여러분이 이미 잘 알고 있는 ‘영역(region)’ 대상으로 작동하거나, ~M-x align-current~ 같은 일부 정렬 명령어만 고유하게 적용되는 ‘섹션(section)’ 을 대상으로 작동합니다. 섹션이란 첫 번째 일치하는 정렬 규칙이 적용되는 연속된 줄들의 그룹을 말합니다. 따라서, ~HELLO_WORLD_CONST = “Hello World”;~ 에서 ~=~ 같은 문자열 상수를 정렬하는 규칙이 있다면, 해당 규칙에 부합하는 모든 연속된 줄이 그 규칙의 섹션이 됩니다.

Emacs는 많은 내장 정렬 규칙이 있으며, 텍스트 영역에 ~M-x align~ 을 호출하면 Emacs는 정렬 규칙 목록을 스캔해서 규칙 목록의 모든 기준(메이저 모드, 정렬에 사용할 정규식 등)에 일치하는 첫 번째 규칙을 찾습니다. 안타깝게도 정렬 규칙들은 읽고 이해하기 어렵고, 실질적으로 이 기능이 기대만큼 유용하지 않다는 것을 의미합니다. Emacs의 각 정렬 규칙(~align-rules-list~ 에 저장됨)은 규칙이 어떻게 작동하는지 파악하기 위해 정규 표현식에 대한 깊은 지식과 각 층을 하나씩 뜯어보는 노력이 필요합니다. Emacs 개발자들은 각 정렬 규칙의 작동 방식을 설명하는 문서 문자열을 필수화하지 않음으로써 여기서 기회를 놓쳤습니다.

~M-x align-current~ 의 장점은 영역을 먼저 지정할 필요가 없다는 점입니다. 이 명령은 커서가 위치한 줄 기준으로 어떤 규칙이 적용되는지 파악하고, 인접한 줄에도 (해당 규칙에 부합하는 경우) 이를 적용합니다.

다음은 메이저 모드별로 정리한 Emacs의 내장 규칙 중 일부입니다:

*Python* : 다음과 같이 할당문을 열로 나열할 수 있습니다. ~=~ 의 정렬에 주목합니다:

#+BEGIN_SRC
UNIVERSE_ANSWER_CONST = 42
UNIVERSE_QUESTION     = “What is The Answer ...”
#+END_SRC

*Lisp* : 위의 Python 예제와 거의 동일한 방식으로 알리스(alists)를 열로 정렬할 수 있습니다:

#+BEGIN_SRC
((universe-answer . 42)
 (universe-question . “What is The Answer...”))
#+END_SRC

두 경우 모두, 커서를 각 줄에 위치시킨 후 ~M-x align-current~ 를 입력했더니 Emacs가 어떤 규칙을 적용할지 알아서 처리했습니다.

자동 정렬 기능이 유용하기는 하지만, 사용자의 상황이 Emacs의 정렬 규칙 중 어느 하나와 완벽하게 일치할 가능성은 낮습니다. 그 외의 모든 경우는 Emacs의 유연한 ~M-x align-regexp~ 명령을 사용해서 텍스트를 어떻게 정렬할지 Emacs에 지정해야 합니다.

~M-x align-regexp~ 를 사용할 때 두 가지 작동 모드가 있습니다. 명령을 실행하면 나타나는 초보자 모드와, ~C-u~ 를 함께 눌러 호출할 때 나타나는 복합 모드입니다. 복합 모드를 실제로 사용할 가능성이 있는 유일한 경우는 같은 줄에서 여러 열로 정렬할 때입니다. 한 가지 성가신 점은, 이 기능은 초보자 모드에서 사용할 수 없다는 것입니다.

다음 텍스트를 살펴보겠습니다:

#+BEGIN_SRC
Cappuccino $2.00
Caramel Latte $2.30
Americano $3.50
Macchiato $4.00
#+END_SRC

~M-x align-regexp~ 를 사용해서 텍스트를 열로 나누고 가격을 ~$~ 기호에 맞춰 정렬하려면:

~Align regexp: \$~

출력 결과는 다음과 같습니다:

#+BEGIN_SRC
Cappuccino $2.00
Caramel Latte $2.30
Americano $3.50
Macchiato $4.00
#+END_SRC

여러 열을 정렬하려면 좀 더 어려워집니다. 다음 CSV 텍스트를 살펴보겠습니다:

#+BEGIN_SRC
Price,Product,Qty Sold
$2.00,Cappuccino,289
$2.30,Caramel Latte,109
$3.50,Americano,530
$4.00,Macchiato,20
#+END_SRC

세 열 모두를 정렬하려면 complex 모드를 사용해야 합니다. 따라서, ~C-u M-x align-regexp~ 를 입력합니다. 가장 먼저 눈에 띄는 것은 미리 채워진 제안 사항입니다:

~Complex align using regexp: \(\s-*\)~

이 정규 표현식은 캡처 그룹 내에서 0개 이상의 공백 문자를 일치시킵니다. 이렇게 하는 이유는 정렬하려는 파일에 이미 많은 공백이 있을 수 있기 때문입니다(아마 얼마 전에 정렬을 했으나 텍스트를 수정하면서 정렬이 어긋났을 수 있음). 따라서, Emacs는 정렬하려는 문자 주변의 기존 공백을 일치시키고 캡처한 다음, 올바르게 재정렬해야 합니다. 초보자 모드를 사용할 때, Emacs는 정렬 기준이 될 문자 앞에 해당 정규식을 자동으로 삽입합니다. 즉, 정렬 기준 문자 앞의 모든 공백이 제거된다는 뜻입니다. 따라서, 초보자 모드도 공백 캡처 그룹은 존재합니다.

따라서, ~,~ 를 기준으로 정렬하려면 기존 정규 표현식의 시작 부분이나 끝 부분에 ~,~ 를 추가해야 합니다. 이를 어디에 배치하느냐에 따라 정렬 결과는 달라집니다: 이 기호를 ~,~ 앞에 넣으면 Emacs가 ~,~ 뒤에 열을 맞추기 위한 공백을 삽입합니다.

~,~ 같은 기호를 사용해서 이 작업을 수행하는 것이 좋습니다. 그렇지 않으면 다음과 같이 표시됩니다:

#+BEGIN_SRC
Fooooo     ,Bar
Bizz       ,Buzz
#+END_SRC

이 기호를 ~,~ 뒤에 넣으면 Emacs가 ~,~ 앞에 열을 맞추기 위한 공백을 삽입합니다.

~$~ 같은 기호를 사용해서 이 작업을 수행할 수 있습니다. 그렇지 않으면 다음과 같이 표시됩니다:

#+BEGIN_SRC
Foobar Widget $ 15.00
Fizz Buzz $     10.00
#+END_SRC

따라서, 이 경우 프롬프트에 다음과 같이 답변해야 합니다:

~Complex align using regexp: ,\(\s-*\)~

다음으로 기본 답변을 선택합니다:

~Parenthesis group to modify (justify if negative): 1~

캡처 그룹은 하나뿐이지만, 복합 정렬 작업의 경우 그룹이 하나 이상 있을 수 있습니다.

마지막으로, 간격 설정입니다. Emacs는 ~align-default-spacing~ 을 사용하며, 이 설정은 기본적으로 Emacs가 내부적으로 사용하는 탭 정지점을 따릅니다. 보통 기본값 그대로 두어도 무방하지만, 절대 간격 값을 입력하면 Emacs가 이를 따르도록 시도합니다:

~Amount of spacing (or column if negative): 1~

다음은–아마 여러분이 실제로 신경 쓸만한 부분일텐데–Emacs가 해당 명령을 줄 전체에 걸쳐 반복할지 여부입니다. 모든 ~,~ 기호를 열 단위로 정렬하려면 ‘yes’ 라고 답합니다:

~Repeat throughout the line: yes~

이제 출력은 다음과 같이 표시됩니다:

#+BEGIN_SRC
Price, Product,        Qty Sold
$2.00, Cappuccino,     289
$2.30, Caramel Latte,  109
$3.50, Americano,      530
$4.00, Macchiato,      20
#+END_SRC

Emacs의 정렬 명령어는 강력하고 실용적이어서, 서식이 없는 텍스트나 코드를 다룰 때 유용합니다. 유일한 단점은 한 줄에서 정렬 과정을 두 번 이상 반복하려면 복잡한 모드를 일일이 탐색해야 한다는 점입니다.

#+BEGIN_QUOTE
*Note* :
앞서 말씀드렸듯이, 자주 사용하는 복잡한 명령어들은
매크로로 자동화하는 것이 좋을 수 있는데,
이번 경우가 바로 그런 예시 중 하나일 것입니다!
#+END_QUOTE


** Other Editing Commands

*** Zapping Characters
Kill 명령어는 구조화된 텍스트에서 잘 작동하며, 구문 단위를 대상으로 동작합니다. 하지만, 때로는 임의의 문자를 기준으로 삭제할 때가 있습니다. zap 명령어(~M-z~)는 바로 그 기능을 수행합니다. 이 명령을 호출하면 커서 앞의 단일 문자를 입력하라는 메시지가 표시됩니다. 그러면 zap 은 입력한 문자를 포함해서 그 앞의 문자까지 삭제합니다:

~http://www.example.com/█articles/?id=10~

~/~ 까지 zap 을 실행한 후:

~http://www.example.com/█?id=10~

앞서 설명한 삭제 명령어들과 마찬가지로, 이 명령어도 삭제 링에 추가됩니다. 따라서, 삭제 명령어와 음수 및 숫자 인수를 조합해서 연속적으로 수행할 삭제 횟수와 삭제 방향을 제어할 수 있습니다.

#+BEGIN_QUOTE
*Zap up to char* :
Emacs 28은 이 명령어가 기본으로 내장되어 있지만,
기본적으로 어떤 키와도 연결되지 않습니다.
가능한 키 바인딩 중 하나는 ~M-S-z~ 입니다:

~(global-set-key (kbd “M-S-z”) 'zap-up-to-char)~

하지만, 원할 경우 ~C-z~ 를 재매핑해서
문자까지 위로 이동할 수도 있습니다:

~(global-set-key [remap zap-to-char] 'zap-up-to-char)~
#+END_QUOTE


*** Spell Checking
Emacs에서 맞춤법 검사를 수행하는 방법은 여러 가지가 있으며, 각각 다른 용도에 적합합니다. 놀랍게도 Emacs의 맞춤법 검사는 Emacs 자체에서 수행되지 않습니다. 리눅스의 경우, 선택 가능한 옵션은 aspell 과 ispell 이며, Emacs는 좀 더 빠르고 최신식인 aspell 을 ispell 보다 우선적으로 선택합니다.

| 키 및 명령어             | 설명                                                        |
| ~M-$~                    | 현재 위치의 단어에 대해 맞춤법 검사 수행                    |
| ~M-x flyspell-mode~      | 맞춤법 오류를 강조 표시하는 마이너 모드                     |
| ~M-x flyspell-prog-mode~ | 위와 동일하지만, 코드 내의 문자열과 문서 문자열만 강조 표시 |
| ~M-x ispell-buffer~      | 버퍼에 대해 맞춤법 검사 수행                                |
| ~M-x ispell-region~      | 선택한 영역에 대해 맞춤법 검사 수행                         |

어떤 맞춤법 검사기를 사용하든, Emacs는 둘 다 ispell 로 부릅니다.

#+BEGIN_QUOTE
*Spell checking on Windows* :
이 기능을 사용하려면 Windows에 aspell 또는 ispell 을 직접 설치해야 합니다.
#+END_QUOTE

저는 대충 수정할 때는 ~M-$~ 를 자주 사용합니다. 이 기능을 사용하면 Emacs가 해당 단어가 올바른지 아닌지 알려줍니다. 만약 Emacs가 틀렸다고 판단하면, 선택할 수 있는 제안 목록을 표시하고 원래 단어를 대체해 줍니다.

Flyspell 모드는 워드 프로세서의 인라인 맞춤법 검사기와 동일하게 작동합니다—맞춤법이 틀린 단어는 물결선으로 강조 표시됩니다. 하지만, 이 모드는 텍스트용으로 설계되었을 뿐 코드를 위한 것은 아닙니다. 코드의 경우, 맞춤법 검사를 주석, 문자열 및 doc string 으로 제한하는 ~M-x flyspell-prog-mode~ 를 사용합니다. 이 또한 매우 유용한 기능입니다.

두 Flyspell 마이너 모드 중 하나를 활성화하면, ~C-M-i~ (및 ~C-.~ )에 바인딩된 보조 명령도 함께 활성화되어 커서 위치의 단어를 자동으로 수정해 줍니다. 이 명령은 가장 가능성이 높은 첫 번째 일치 항목을 선택해서 커서 위치의 단어를 수정하며, 이후 호출 시 단어 목록을 순차적으로 순환합니다. 이는 어떤 수정 항목을 선택할지 묻는 ~M-$~ 보다 훨씬 더 빠릅니다.

*사용자 정의* : 이 기능을 자주 사용한다면, 특히 ispell 그룹을 사용자 정의해서 기본 사전 외의 특정 사전을 사용할 경우, 이 기능을 사용자 정의할 것을 권장합니다.


**** Dictionary Lookup
Emacs 28은 자체 서버를 운영하거나, dict.org 로 단어 조회 요청을 전송하는 데 동의할 경우 사전 조회 기능을 지원합니다. 이 원격 서버는 놀라울 정도로 다양한 기능을 갖추고 있으며 여러 언어를 지원합니다.

| 명령어                             | 설명                             |
| ~M-x dictionary-lookup-definition~ | 현재 커서 위치의 단어를 찾습니다 |
| ~M-x dictionary-search~            | 지정된 단어를 검색합니다         |
| ~M-x dictionary-select-dictionary~ | 검색할 사전을 선택합니다         |


*** Quoted Insert
문자 그대로의 ~TAB, RET~ 또는 ASCII 제어 코드 문자를 삽입할 경우, ~C-q~ 에 바인딩된 quoted insert 기능을 사용해야 합니다.

#+BEGIN_QUOTE
*Line feed vs carriage return* :
문자 그대로의 줄바꿈 기호를 삽입하려면, ~C-q C-j~ 를 입력합니다.
이는 줄바꿈(LINE FEED) 기호이며, 엔터 키(CARRIAGE RETURN)와는 다릅니다.
#+END_QUOTE

Quoted insert 는 ASCII 제어 코드를 ~face escape-glyph~ 글리프로 강조 표시해서 사용자가 시각적으로 쉽게 식별할 수 있도록 만드는 영리한 기능을 갖추고 있습니다. Quoted insert 는 사용자가 입력한 모든 문자를 그대로 삽입합니다. 예를 들어, ~C-q ESC~ 를 입력하면 ASCII 제어 코드 ~^[~ (ESCAPE라고도 함)가 삽입됩니다. 


