* Chapter 1. Introduction

#+BEGIN_QUOTE
“I’m using Linux. A library that emacs uses to communicate with Intel hardware.”  
 
 – Erwin, #emacs,Freenode.
#+END_QUOTE


**  Thank You
『Mastering Emacs』 를 구매해 주셔서 감사합니다. 이 책은 오랜 시간 준비한 결과물입니다. 2010년 제 블로그에 『Mastering Emacs』 를 시작한 것은 친한 친구인 리(lee)가 제게 Emacs와 Emacs 작업 흐름에 대한 생각을 공유해보라고 권유했기 때문입니다. 그당시 저는 'blogideas.org' org 파일에 제가 배웠던 내용과 누군가에게 가르쳐 주면 좋겠다고 생각했던 아이디어와 개념을 방대하지만 무작위로 모아 뒀습니다. 그 파일의 최종 결과물이 바로 그 블로그였고 이제는 이 책이 되었습니다.


*** Special Thanks
다음 분들께 격려와 조언, 제안, 그리고 비판을 보내주신 데 대해 감사의 말씀을 전합니다:

#+BEGIN_EXAMPLE
Akira Kitada, Alvaro Ramirez, Arialdo Martini,
Bob Koss, Catherine Mongrain, Chandan
Rajendra, Christopher Lee, Daniel Hannaske,
Edwin Ong, Evan Misshula, Friedrich Paetzke,
Gabriela Hajduk, Gabriele Lana, Greg Sieranski,
Holger Pirk, John Mastro, John Kitchin, Jonas
Enlund, Konstantin Nazarenko, Lee Cullip,
Luis Gerhorst, Lukas Pukenis, Manuel Uberti,
Marcin Borkowski, Mark Kocera, Matt Wilbur,
Matthew Daly, Michael Reid, Nanci Bonfim,
Oliver Martell, Patrick Mosby, Patrick Martin,
Sebastian Garcia Anderman, Stephen Nelson Smith,
Steve Mayer, Tariq Master, Travis
Jefferson, Travis Hartwell.
#+END_EXAMPLE

다른 사람과 마찬가지로 저 또한 Emacs에 대해 아무것도 모르는 상태에서 그 세계로 내몰렸습니다. 저의 경우 대학 1학년 때였는데 그당시 학교 컴퓨터 동아리 대부분은 Vim 사용자들로 구성되어 있었습니다. 저에게 “Vim을 써야 해, 그게 다야!” 라고 단호하게 말했습니다. 누군가에게 지시받는 것을 원치 않았던 저는 Vim과 정반대인 ~Emacs~ 를 선택했습니다.

Emacs는 오랫 동안 안정적이고 믿을만한 편집기임을 증명했지만 익히기엔 꽤 까다로운 도구였습니다. 방대한 사용자 설명서에도 불구하고 Emacs를 배우거나 이해하는 데는 별 도움이 되지 않았습니다.


** 2022 Edition Update
~Emacs 28~ 은 최신 버전으로 오랫동안 기다려온 네이티브 컴파일 기능을 도입해서 Emacs 27에 비해 상당한 업그레이드를 이루었습니다. 타사 패키지의 규모와 야망이 해마다 커짐에 따라 Emacs의 성능도 향상되야 합니다. 네이티브 컴파일 기능은 Elisp를 사용자의 플랫폼과 시스템 아키텍처에 적합한 네이티브 코드로 컴파일함으로 전반적으로 Emacs의 성능을 크게 향상시킵니다. 이는 주로 /Andrea Corallo/ 한 사람의 거대한 노력으로 이루어졌으며 Emacs 28에 포함되기까지 수 년의 고된 작업을 필요로 했습니다.

이 기능을 제외하면 Emacs 28의 변경 사항 대부분은 점진적인 것으로 새로운 명령어나 사용자 정의 기능이 사용자가 알아둘 가치가 있다고 판단될 때 이에 맞춰 책을 업데이트 했습니다.

다음과 같이 강조하고 싶은 몇 가지 기능이 있습니다:

- *프로젝트 관리 기능 개선 사항:* 

이 중 일부는 Emacs 27에도 포함됐지만 Emacs 28에서 크게 강화됐습니다. 프로젝트 관리용 키맵으로 접근성과 사용 편의성이 향상됐으며 Emacs에 이미 존재하던 수많은 기능도 개선됐습니다.

- *좀 더 친숙한 도움말 및 설명 명령어:* 

Emacs는 자체 문서화 기능을 갖추고 있지만 이번 릴리스에서 해결될 것으로 보이던 몇 가지 사각지대가 있습니다. 도움말 시스템은 새로 추가된 키 바인딩과 보다 명확한 설명으로 약간의 업데이트가 이루어 졌습니다. ~describe~ 시스템은 Emacs에서 심볼을 조회할 수 있는 주요 방법이며 Emacs 28은 이를 돕는 몇 가지 새로운 명령어를 추가했습니다.

- *좀 더 나은 기능 탐색성:*

마이너 모드나 메이저 모드와 관련된 유용한 명령을 찾는 것이 항상 쉬운 일은 아닙니다. 특정 모드에서 수많은 명령을 도입할 수 있지만 그 중에서 일반 사용자에게 유용한 것은 소수에 불과할 수 있습니다. 이제 Emacs는 현재 버퍼의 활성 모드와 관련된 명령만 선별적으로 요청할 수 있습니다. 이는 기능 탐색성을 크게 향상시킵니다.

책 내용은 독자에게 실질적인 차이를 주지않을 것으로 판단된 대부분의 버전 표기(일부는 Emacs 24 시절까지 거슬러 올라가는 것들)를 제거했습니다. 그 과정에서 제가 원한만큼 명확하거나 자명하지 않다고 생각되던 부분의 문장을 다듬고 내용을 명확히 했습니다.


** Emacs in the Future
앞으로 몇 년 동안 Emacs에 어떤 변화가 기다리고 있을까요? 한 가지 흥미로운 가능성은 대부분의 편집기에서 구문 강조와 의미론적 정보를 추출할 때 사용하는 도구인 정규 표현식은 이미 수십 년 전에 정점을 찍었다는 사실을 인식하는 것입니다. 이보다 지능적인 도구를 원한다면 소스 코드의 파싱 방식을 좀 더 스마트하게 개선해야 합니다. 이것은 새롭거나 독창적인 아이디어는 아니지만 구현하기 어려운 대규모의 과제입니다. 이로 인해 지능형 코드 완성 기능의 언어 서버(Language Servers)로 누구나 접근하거나 확장할 수 있는 표준화된 프로토콜로 대중화하기 전까진 발전이 더뎠습니다.

Emacs는 ~js2-mode~ 나 ~nxml-mode~ 처럼 구문이나 의미론적 보강 작업을 위해 언어 파서를 사용하는 몇 가지 메이저 모드가 있습니다. 자체 언어 파서와 의미론적 툴링을 갖춘 방대한 다국어 IDE인 ~CEDET~ 는 대략 10년 전 Emacs 코어에 병합됐지만 그다지 인기를 얻진 못했습니다. 다른 편집기에서 널리 채택된 범용 언어 파싱 라이브러리인 ~tree-sitter~ 가 이 작업에 가장 적합한 도구입니다. 이 라이브러리는 정규 표현식을 완전히 대체하진 않으며 그럴 필요도 없습니다. 정규 표현식도 그 나름대로 용도가 있으니까요...

하지만, ~tree sitter~ 는 수십 가지 언어를 지원하며 S-표현식 기반의 쿼리 언어를 사용합니다. 이로 인해 Emacs와 elisp에 완벽히 어울립니다. 또한, 처리 속도가 빠르고 소스 코드를 처리할 수 있으므로 코딩 중에도 제대로 작동합니다. 지금 바로 Emacs의 tree-sitter로 훨씬 개선된 구문 강조 기능을 경험할 수 있습니다.


** 2020 Edition Update
제가 사람들이 관심가질 만하다고 생각되는 Emacs 글을 공유하기 위해 블로그를 시작한 지도 벌써 10년입니다. 그리고 이 책의 초판을 출간한 지도 5년입니다. 5년 동안 어느날 갑자기 등장해서 폭발적으로 인기를 끌었던 텍스트 편집기들이 나타났다가 새로운 도전자 앞에서 그 기세가 꺾이기도 했습니다. 한편 Emacs 사용자들은 여전히 Emacs를 사용하며 다른 편집기들의 발전(그리고 퇴보…)에서 배우고 있습니다. 하지만, 지난 5년 동안 Emacs 사용자들이 혜택볼 수 있는 발전도 많이 있습니다.

Microsoft VSCode는 소프트웨어 커뮤니티에서 수십 년 전에 합의되고 구현했어야 할 것을 표준화 했단 점에서 언급할 가치가 있습니다. 즉, 컴파일러, 인터프리터 및 기타 프로그래밍 가능한 엔진의 내부 구조를 노출하거나(불가능한 경우 재구현) 비공개 소스의 IDE를 사용한 사람은 누구나 익숙한 고급 기능을 지원할 수 있는 프로토콜입니다: 자동 리팩토링; 구문 및 오류 강조 표시; 코드 완성; 문서 조회 등. 

일부는 놀랍게도 마이크로소프트가 개방형 JSON-RPC 표준인 /Language Server Protocol/ 을 통해 논쟁에서 승리했습니다!! 이 프로토콜이 등장하기 전에는 대부분의 IDE와 에디터는 범위, 깊이, 품질 면에서 제각각인 폐쇄적인 자체적인 구현 방식을 사용했습니다. 이는 특히 Emacs와 사용자들에겐 커다란 승리입니다. 그들은 이제 Language Server를 구축한 사람들의 공동 작업 기능을 누릴 수 있습니다.

#+BEGIN_QUOTE
[!NOTE]
*Language Servers in Emacs* : 주목할만한 두 가지 구현체가 있습니다. ~LSP mode~ 와 ~EGlot~ 입니다.
LSP mode는 설치 즉시 완벽한 IDE 환경을 제공하는 반면 EGlot은 간결하고 Emacs 중심의 접근 방식을 선호합니다.

두 가지 모두를 사용한 후 마음에 드는 것으로 선택하시기 바랍니다.

두 제품 모두 현재 활발히 개발 중이며 그에따라 빠르게 변화하고 있습니다.
또한, 다양한 도구와 언어를 폭넓게 지원합니다.
#+END_QUOTE

IDE 스타일의 기능은 이맥스의 위상을 높여주지만 이맥스를 배울 때 피할 수 없는 한 가지 사실은 일단 익숙해지면 배우던 시절의 고생이 얼마나 힘들었는지 금새 잊어버린다는 점입니다. 이것이 바로 비-사용자들이 비판하기 쉬운 표면적인 문제점 중 하나였습니다. 용어는 난해하고 UI는 투박하며 키 바인딩이 복잡하다는 것입니다. 하지만, 사실입니다. 그것이 바로 Emacs입니다. 또한, 모든 것을 바꿀 수 있습니다. 저는 이런 불만에 일말의 진실이 있다고 믿습니다. 좀 더 예쁜 UI는 즉각적인 성과며 몇몇 목소리 크고 까다로운 원로 사용자를 화나게 만들 위험이 있더라도 Emacs의 다소 난해한 기본 설정 중 일부를 변경한 것은 또 다른 성과입니다.

하지만, 첫인상은 매우 중요합니다. 사람들은 적합성과 형태로 순식간에 판단을 내립니다. 만약 이 편집기로는 코드를 처리하진 못하지만 다른 편집기가 해낸다면 그들은 Emacs를 시도조차 하지 않을 수 있다는 뜻입니다. =Spacemacs= 와 =Doom Emacs= 같은 올인원 패키지의 매력이나 첫인상은 이러한 첫인상의 중요성과 합리적인 기본 설정의 가치를 증명합니다. 많은 이들이 스타터 키트 중 하나를 사용하면서 Emacs로 뛰어들고 그런 신기함이 사라지면 그만큼 많은 이들이 자신만의 Emacs 설정 단계로 넘어갑니다. 하지만, 그 시점에 그들은 이미 평생 Emacs 사용자가 된 것입니다.

이 책은 Emacs를 배우는 상세한 방법을 다루며 여러분은 분명 Emacs를 익히게 됩니다. Emacs의 용어들은 현대 컴퓨팅보다 훨씬 더 오래됐지만 다른 곳에서 주로 사용하는 UI 용어와 구별되는 용어는 소수에 불과하므로 배우기 쉽습니다. 키 바인딩과 명령어는 익히기 좀 더 어렵지만 그야말로 Emacs의 핵심입니다.

Emacs는 복잡한 소프트웨어로 이를 익힐려면 시간과 노력이 필요합니다. 하지만, 일단 익힌다면 평생 사용할 수 있는 편집기를 갖게 됩니다. Emacs는 활발하고 친근한 커뮤니티가 있으므로 다른 편집기에서 이루어낸 어떠한 발전이라도 빠르게 받아들여 Emacs에 통합합니다. 그리고 이는-이 책 나머지 부분에서 보겠지만–다른 편집기는 따라올 수 없는 수많은 장점을 제외하는 것입니다.

Emacs 유지보수자는 이런 사실을 잘 알고 있으며 이전 버전과 호환성을 유지하면서 모든 사용자를 위해 Emacs를 점진적으로 개선하기 위해 뒤에서 끊임없이 노력하고 있습니다. 그들은 훌륭한 관리자로 GNU 프로젝트 철학과 Emacs의 유산 그리고 안정성에 대한 헌신을 존중할 필요성과 기술 발전 및 사용자 피드백 사이에서 신중하게 균형을 맞추고 있습니다.

Emacs를 인내심을 가지고 익히신 노력은 분명 크게 보상받을 것입니다. 제가 장담합니다!!


** Intended Audience
이미 책을 구입한 상태에서 대상 독자층에 대해 이야기하는 것이 이상할 수 있습니다. 어쨌든 언급할 필요는 있습니다. 여러분의 Emacs 실력이나 수준과 관계없이 이 책에서 무언가는 얻어갈 수 있으니까요...

첫 번째(이자 가장 명백한) 대상 독자층은 Emacs를 처음 접하는 분입니다. 평생 Emacs를 한 번도 사용한 적 없다면 이 책이 도움되길 바랍니다. 하지만, Emacs도 처음이고 기술적인 배경도 없다면 다소 어려움을 겪을 수 있습니다. Emacs는 단순한 프로그래밍 이상의 용도로 적합하지만 본질적으로 컴퓨터에 익숙한 사람이 주대상입니다. 물론 Emacs를 사용하는 데는 아무런 문제도 없지만 이 책은 독자가 어느 정도의 기술적인 소양이 있다고 가정하되 반드시 프로그래머일 필요는 없습니다.

다음은 Emacs를 사용했지만 포기했다면 이 책으로 계속 사용하길 바랍니다. 하지만, 괜찮습니다. (많은 Emacs 사용자들이 주장하는 것과 달리) 일부 언어나 개발 환경은 Emacs와 맞지 않기 때문입니다. Visual Studio를 사용하는 Microsoft Windows 개발자가 Emacs를 사용한다는 것은 두 걸음 전진하고 한 걸음 후퇴하는 상황입니다. 즉, 전례없는 텍스트 편집 기능과 도구 통합은 얻지만 통합 IDE가 제공하던 이점의 일부를 잃을 겁니다.

만약 Vim에서 넘어오신 분이라면 어둠의 세계에 오신 것을 환영합니다!! 여러분의 주된 목표가 Emacs의 Vim 에뮬레이션 레이어(evil)를 사용하는 것이라면 이 책의 일부 내용은 중복될 수 있습니다. 이 책은 기본 Emacs 키 바인딩에 초점을 맞추며 Emacs의 방식을 가르칩니다. 하지만, 걱정하지 않아도 됩니다. 이 책에 담긴 수많은 팁과 조언은 여전히 유용하며 언젠가 Evil 모드에서 벗어날지 모릅니다.

마지막으로 Emacs를 사용하고 있지만 한 단계 더 발전하는 데 어려움을 겪고 있거나 또는 처음부터 배우고 싶은 분이면 이 책은 바로 여러분을 위한 책입니다!!


** What You'll Learn
한 권의 책에서 Emacs의 모든 기능을 다룬다는 것은 시지프스 노동과 같은 일입니다. 대신 저는 여러분이 Emacs로 생산적으로 작업할 때 필요한 내용 즉, Emacs 기능의 일부만 가르쳐 드립니다. 이 책을 다 읽고 실습하면 Emacs를 충분히 이해하고 이 편집기에 대한 궁금증을 스스로 찾아내거나 해결할 수 있기를 바랍니다.

좀 더 구체적으로 저는 여섯 가지 주제를 다룹니다:

- *What Emacs is about* : Emacs에서 사용하는 용어와 관례에 대한 상세한 설명으로 이는 다른 편집기와 많은 경우 크게 다릅니다. 또한, Emacs의 철학이 무엇인지 그리고 텍스트 편집기에 왜 철학이 필요한지 배웁니다. 또한, Vim을 간략히 다루고 에디터 전쟁과 다양한 수정키의 의미도 설명합니다.

- *Getting started with Emacs*: Emacs 설치 방법과 실행 방법 그리고 최신 버전의 Emacs를 사용하는지 확인하는 방법을 다룹니다. Emacs를 수정하는 방법과 변경 사항을 영구 적용하기 위해 필요한 절차도 설명합니다. =Customize= 인터페이스와 사용자 정의 색상 테마를 로드하는 방법도 소개합니다. 마지막으로 Emacs의 사용자 인터페이스와 무언가 막힐 때 사용할 유용한 팁에 대해 이야기합니다.

- *Discovering Emacs*: Emacs는 자체 문서화 기능을 갖추고 있습니다. 하지만, 이것이 무엇을 의미하며 이런 특성을 활용해서 Emacs에 대해 좀 더 많이 알아가거나 특정 기능에 대한 의문점을 해결하려면 어떻게 할까요? 저는 Emacs에서 새로운 메이저 모드나 사용법을 배울 때 제가 어떻게 했는지를 보여드리고 여러분이 특정 정보를 찾기위해 Emacs의 자체 문서화 특성을 어떻게 활용할지를 설명합니다.

- *Movement*: Emacs에서 이동 방법은 언뜻 보기엔 간단하지만 Emacs는 현재 위치에서 가야할 곳까지 가능한 한 적은 키 입력으로 이동할 수 있는 댜양한 방법이 있습니다. 이동 작업은 개발자에겐 작업의 절반을 차지한다고 할 수 있으며 이를 빠르게 수행할 방법을 안다면 작업 효율은 크게 높아집니다. 배울 내용 중 일부는 구문 단위별 이동과 구문 단위가 정확히 무엇인지; 창과 버퍼의 사용법; 텍스트 검색 및 색인 생성 방법; 텍스트 선택과 마크 사용법 등이 포함됩니다.

- *Editing*: 이전 Movements 장과 마찬가지로 Emacs가 제공하는 다양한 도구로 텍스트를 편집하는 방법을 보여드립니다. 여기엔 균형잡힌 표현식, 단어, 줄, 단락 단위로 텍스트 편집하기; 반복 작업을 자동화하기 위한 키보드 매크로 생성 방법; 검색 및 바꾸기; 레지스터; 다중 파일 편집; 약어; 원격 파일 편집 등이 포함됩니다.

- *Productivity* : Emacs는 단순히 텍스트 편집기 이상의 기능을 제공하며 이 장은 수많은 사람들이 Emacs에 매료되는 이유 즉, 외부 도구와의 긴밀한 통합을 맛보게 해줍니다. 저는 여러분의 호기심을 자극하고 Emacs의 이동 및 편집 기능을 조화롭게 활용했을 때 처리할 수 있는 흥미로운 기능 몇 가지를 보여 드리겠습니다.



* Chapter 2. The Way of Emacs

#+BEGIN_QUOTE
“The purpose of a windowing system is to put
some amusing fluff around your one almighty emacs window.”

– Mark, gnu.emacs.help.
#+END_QUOTE

1960년대부터 시작된 현대 컴퓨팅 시대의 역사를 떠올려 보면 Emacs는 그 어떤 것보다 오랫동안 존재했습니다. Emacs는 1976년 리처드 스톨먼이 =TECO= 편집기에 매크로 세트로 처음 작성했습니다. =TECO= 편집기는 극히 난해한 것으로 기억됩니다. 이후 Emacs의 수많은 경쟁 구현체가 등장했지만 오늘날엔 =XEmacs= 와 =GNU Emacs= 정도만 만날 가능성이 높습니다.

하지만, 이 책은 =GNU Emacs= 에만 초점을 맞춥니다. 한때는 =XEmacs= 가 좀 더 발전됐고 기능도 풍부한 편집기였지만 이젠 그렇지 않습니다. Emacs 22 버전부터 =GNU Emacs= 가 가장 뛰어난 Emacs입니다. =XEmacs= 와 =GNU Emacs= 의 역사는 흥미롭습니다. 이는 자유 소프트웨어 프로젝트에서 일어난 최초의 중요 포크 중 하나였습니다. 오늘날 =XEmacs= 는 더이상 유지보수조차 되지 않고 있습니다.

#+BEGIN_QUOTE
[!NOTE]
*참고*:
대부분의 사람들에게 ‘Emacs’ 는 구체적으로 =GNU Emacs= 를 의미합니다.
저는 서로 다른 구현체로 구분할 때만 전체 이름을 명시합니다.

따라서, 제가 =Emacs= 라고 언급할 때는 항상 =GNU Emacs= 를 의미합니다.
#+END_QUOTE

Emacs가 오랜 역사를 지닌 탓에 여러 가지 특이한 점이 존재합니다. 이상한 용어의 선택이나 시대착오적인 표현이 여전히 남아있는 이유는 대부분의 경우 Emacs가 수십 년 동안 에디터-IDE 분야의 흐름을 선도했기 때문에 각종 기능에 독자적인 용어를 만들어야만 했기 때문입니다. Emacs의 용어를 누구나 익숙한 단어로 바꾸자는 논의도 있었지만 설령 그런 일이 일어나더라도 아직 갈 길이 멉니다.

마케팅은 부족하고 Emacs 개발자 인력은 아주 적으며 현대적인 개인용 컴퓨팅 시대보다 앞서 있던 시대착오적인 요소와 용어에도 불구하고 세상엔 Emacs를 사랑하는 사람들이 많습니다. Emacs의 강점은 그런 적응 능력에 있습니다. 여기서 말하는 '그런 적응 능력' 은 소프트웨어뿐만 아니라 Emacs의 방향을 결정하는 수많은 자원봉사 유지보수자와 기여자를 의미합니다. 그들은 대부분의 사용자들보다 더 오래된 제품의 한계 속에서도 세상의 변화에 뒤처지지 않도록 지칠 줄도 모르고 일을 합니다. 굳어버린 Emacs 커뮤니티와 플랫폼은 그저 신화에 불과합니다.

이번 장엔 ‘Way of Emacs’ 에 대해 이야기합니다. 여기엔 용어와 Emacs가 사람들에게 어떤 의미인지 그리고 Emacs의 기원을 이해하는 것이 왜 Emacs를 받아들이는 데 도움되는지 다룹니다.


** Guiding Philosophy
Emacs는 무언가 만지작거리기 좋아하는 사람을 위한 편집기입니다. 그 이상도 이하도 아닙니다. 사람들이 Emacs를 개조하는 이유는 이 편집기의 거의 모든 측면이 확장 가능하기 때문입니다. Emacs는 확장 가능하고 사용자 정의 가능하며 자동 문서화 기능을 갖춘 최초의 편집기입니다. 다른 편집기를 사용한 사람이라면 뭐든지 바꿀 수 있다는 생각이 불필요한 방해 요소로 보일 수 있습니다. 실제로 많은 Emacs 개조 작업은 본업에 지장주면서 이루어지기도 합니다. 하지만, 편집기를 자신이 원하는대로 만들 수 있다는 사실을 깨닫게 되면 무한한 가능성의 세계가 열립니다.

즉, Emacs의 모든 키 바인딩을 원하는대로 자유롭게 재설정할 수 있다는 뜻입니다. 여러분은 IDE의 문서화되지 않은 버그 투성이 API나 설정을 변경시 따를 수 있는 여러 제한 사항들—예를 들어, 사용자 정의 탐색 키가 검색 및 바꾸기 창이나 내부 도움말에서 제대로 작동하지 않는 것 같은 문제들—에 얽매이지 않습니다. Emacs는 모든 것을 바꿀 수 있으며 실제로 사람들은 그렇게 합니다.

Vim 사용자들이 Emacs로 이동하는 이유는?? 글쎄요, 종종 Emacs가 Vim보다 더 나은 Vim이기 때문입니다.

Emacs는 당신을 매료시킵니다. 일단 편집에 Emacs를 사용하면 IrC, 이메일, 데이터베이스 접속, 생각 정리, 명령줄 셸, 코드 컴파일, 인터넷 서핑까지 모두 텍스트 편집 작업만큼 쉽다는 것을 깨닫습니다. 게다가 키 바인딩과 테마 그리고 모든 동작을 재구성하거나 변경할 수 있는 Emacs와 elisp의 기능을 사용할 수 있습니다.

그리고 그 모든 것이 매끄럽게 통합되면 애플리케이션을 오가면서 겪을 수 있는 컨텍스트 전환을 피할 수 있습니다: 하지만, 대부분의 Emacs 사용자는 편집기, 웹브라우저 그리고 터미널 애플리케이션 정도만 사용합니다.

#+BEGIN_QUOTE
[!NOTE]
*Emacs's history* :
Emacs 소스 코드 저장소(현재 Git 기반)는 30년 이상의 역사를 자랑하며 13만 건이 넘는 커밋과 600명 가까운 커미터가 참여하고 있습니다.
#+END_QUOTE

Emacs나 수많은 패키지 중 하나를 수정하려면 ~Emacs Lisp~ (비공식적으로 =elisp= 라고 함)을 사용해야 합니다. elisp과 Emacs에 다른 언어를 접목하려는 시도도 몇 차례 있었지만 지속적인 성과를 거두진 못했습니다. 결과적으로 LISP는 Emacs 같은 고급 도구를 위한 완벽한 추상화 언어임이 밝혀졌습니다. 그리고 대부분의 현대 언어가 시간의 시험을 견딜 수 있었던 것은 아닙니다. 예를 들어, TCL 언어는 90년대 인기가 많았기에 잠시 고려됐지만 오늘날엔 LISP 언어보다 생소하단 특징을 가집니다.

유일한 단점은 Emacs 설정을 만지는 일을 받아들여야 한다는 점입니다(LISP도 마찬가지지만 사실 장점입니다). 그래서 제가 Emacs를 무언가 만지작거리는 사람을 위한 에디터라고 강조한 것입니다. 만약, 설정 건드리는 걸 싫어하고 설치 즉시 완벽하게 작동하길 원한다면 이제 남은 선택지는 두 가지 뿐입니다:

*Use a starter kit*: 추가 패키지와 작성자가 적절하다고 판단한 설정이 포함된 무료 스타터 키트가 있습니다. 이는 시작하기엔 좋은 방법일 수 있지만 Emacs 본연의 기능이 어디서 끝나고 스타터 키트의 기능이 어디서 시작되는지 구분하기 어렵다는 점을 유념합니다.

다음 스타터 키트 중 하나를 살펴보시길 권장합니다:

• [[Steve Purcell의 .emacs.d] - https://github.com/purcell/emacs.d
• Bozhidar Batzov의 Prelude - https://github.com/bbatsov/prelude

Vim에 강한 애착을 가진 독창적인 키트를 원하신다면:

• Spacemacs: Vim의 모달 편집과 Emacs의 확장성을 결합한 인기있는 스타터 키트 - https://spacemacs.org/
• Doom Emacs: Spacemacs과 마찬가지로 완성도 높고 가벼운 스타터 키트 - https://github.com/hlissner/doom-emacs

*Use the defaults*: 하나의 선택지지만 Emacs는 중립적이고 구식인 기본 설정으로 제공됩니다. 사용자는 자신의 취향에 맞게 Emacs를 설정하거나 다른 사람에게 그 작업을 맡겨야 합니다. 주류 편집기들과 극명하게 다른 이 편집기의 유지보수자들은 기존 사용자층(그들야말로 Emacs 설정 방법을 가장 잘 알고 있을 사람입니다)을 불편하게 만들까봐 기본 설정을 변경할 때는 매우 신중을 기합니다.

개인적으로 저는 스타터 키트를 사용한 적이 없습니다. 제가 20년 전쯤 시작했을 무렵엔 지금처럼 스타터 키트가 존재하지 않았기 때문입니다. 대신 그당시 우리가 '.emacs 파일' 이라 부르던 다른 사람의 설정 파일을 대거 차용했습니다.

이 접근 방식은 편집기를 처음부터 끝까지 이해하려는 사람에게 적합합니다. 스타터 키트를 살펴보시고(앞서 언급한 키트들에서 좋은 아이디어를 얻으세요!) 거기서 마음껏 차용하시길 권합니다.


*** LISP?
Emacs는 ‘Emacs Lisp’ 또는 줄여서 ‘elisp’ 이라 불리는 자체 LISP 구현체 기반으로 작동합니다. 많은 사람들이 이런 난해한 언어때문에 주저하거나 겁을 먹는데 이는 정말 아쉬운 일입니다. 왜냐하면, LISP를 하나의 독립된 기계로 간주하는 개념을 바탕으로 구축된 이 편집기로 LISP 언어를 배운다는 것은 실용적이면서 재미있는 방법이기 때문입니다. Emacs의 모든 부분은 검토, 평가 또는 수정할 수 있습니다. 왜냐하면, 이 편집기는 대략 95%가 elisp 코드이며 5% 정도가 C 코드이기 때문입니다. 또한, 이는 급진적인 패러다임을 배울 수 있는 실용적인 방법입니다. 즉, 코드와 데이터는 상호 교환 가능하고 유연하며 언어의 간단한 구문과 매크로를 통해 쉽게 확장할 수 있습니다.

안타깝지만 언젠가 Elisp를 배워야 합니다!! 하지만, 이 책은 Emacs의 사용자 정의 옵션을 동적으로 설정할 수 있는 인터페이스인 'Customize 인터페이스' 에 대해 이야기합니다. 하지만, 키 재할당처럼 단순한 작업조차 Elisp와 상호작용해야 합니다. 하지만, 나쁜 것만은 아닙니다. 여러분이 마주칠 가능성 높은 문제 대부분은 오래 전에 누군가에 의해 해결됐으니 단지 인터넷에서 해결책만 검색하면 되는 간단한 문제일 뿐입니다.

파이썬, 루비, 자바스크립트 같은 보다 현대적인 언어에 비해 엘리스프(Elisp)는 상대적으로 인기는 적지만 좀 더 전통적인 명령형/객체 지향 언어를 사용했다면 이맥스(Emacs)가 지금처럼 강력한 확장성을 갖출 수 있었을지 의문입니다. LISP를 그토록 훌륭한 언어로 만드는 것은 소스 코드와 데이터 구조는 본질적으로 하나이기 때문입니다. 사람이 읽는 LISP 소스 코드는 LISP가 데이터를 코드로 조작하는 방식과 거의 동일합니다. “데이터란 무엇인가?” 와 “코드란 무엇인가?” 란 질문 사이의 구분은 사실상 존재하지 않습니다.

'데이터는 코드', 매크로 시스템 그리고 임의의 함수에 조언(advise)할 수 있는 기능—즉, 원본 소스를 복사하거나 수정하지 않고 기존 코드의 동작을 변경할 수 있다는 점—은 사용자의 필요에 맞게 Emacs를 변경할 수 있는 전례없는 능력을 제공합니다. 대부분의 소프트웨어 프로젝트에선 코드 스멜이나 부실한 아키텍처로 간주될만한 것이 Emacs에선 장점입니다. 다른 사람이 작성한 소스 코드의 방대한 부분을 다시 작성하지 않고 사용자의 필요에 맞게 Emacs의 기존 루틴을 후크하거나 교체할 수 있기 때문입니다.

하지만, 이 책은 엘리스프(Elisp)에 대해 자세히 다루지 않습니다!! 이맥스(Emacs)는 기본 제공되는 엘리스프 입문 자료가 포함되므로 관심있다면 꼭 한 번 읽어보시길 추천합니다. 솔직히 말해서 여러분은 관심을 가져야 마땅합니다. LISP 언어는 아주 재미있는 언어이며 실용 환경에서 이런 강력한 언어를 배우고 활용하는데 더할나위 없이 좋은 방법입니다. 단지 괄호 때문에 겁먹진 마시기 바랍니다; 괄호는 사실 이 언어의 가장 큰 장점입니다.


*** Emacs as an Operating System

그림

Emacs는 반짝거리는 물건들로 가득찬 까치 둥지 같습니다. 만약 여러분이 Emacs를 처음 접하는 분이라면 제가 비유를 지나치게 확장했다고 생각할 수 있지만 Emacs는 ~M-x zone~ 으로 실행하는 스크린세이버, ~M-x dunnet~ 으로 실행하는 텍스트 어드벤처 게임, ~M-x tetris~ 로 실행하는 테트리스 클론, 본격적인 클라이언트-서버 모델이자 달 위상 계산기, ~M-x doctor~ 로 실행하는 심리 치료사, 여러 이메일 클라이언트, ASCII 아트를 그릴 수 있는 ~Artist Mode~; ~EXWM~ Emacs 기반 X 윈도우 매니저; 그리고 이 책을 읽을 수 있는 EPUB 리더인 ~nov~ 등이 포함된다는 점을 생각하시기 바랍니다.

Emacs를 실행하면 사실상 운영체제의 ABI와 저수준의 상호작용을 담당하는 작은 C 코어를 시작하는 것입니다. 여기엔 파일 시스템과 네트워크 접근, 화면에 무언가 그리거나 터미널에 제어 코드를 출력하는 것 같은 일상적인 작업도 포함됩니다.

하지만, Emacs의 초석은 elisp 인터프리터입니다!! 이것이 없다면 Emacs도 존재할 수 없습니다!! 이 인터프리터는 낡고 구식이라 점점 늘어나는 사용자의 요구를 감당하기에 힘겨워 합니다. 현대의 Emacs 사용자들은 이런 소박한 인터프리터에 너무나 많은 것을 기대합니다. 속도와 비동기 처리가 대표적인 쟁점 사항입니다. 인터프리터는 단일 스레드로 실행되므로 부하가 큰 작업은 UI 스레드를 잠급니다. 하지만, 해결책은 항상 있습니다. 문제는 다양하지만 사람들이 좀 더 정교한 패키지를 작성하는 것을 막진 못합니다. Emacs 28의 출시와 함께(그리고 사용 중인 Emacs 인스턴스가 이를 지원하도록 컴파일된 경우) 사용하는 모든 Elisp 코드는 네이티브 코드로 컴파일되므로 상당한 속도 향상을 가져옵니다.

엘리스프(Elisp)를 작성할 때 여러분은 단순히 모든 것에서 격리된 샌드박스에서 실행되는 코드 조각을 작성하는 것이 아닙니다. 여러분은 살아있는 시스템 즉, 운영체제에서 실행되는 운영체제를 변경하는 것입니다. 여러분이 변경하는 모든 변수와 호출하는 모든 함수는 텍스트를 편집할 때 사용하는 바로 그 인터프리터에 의해 실행됩니다.

Emacs는 거대하고 가변적인 상태 그 자체로 해커들에겐 꿈같은 존재입니다. 그런 단순함은 축복이자 저주입니다. 실행 중인 함수를 재정의할 수 있고 변수를 마음대로 변경할 수 있으며 언제든지 시스템 상태를 조회할 수 있습니다. 이런 상태는 Emacs가 키보드부터 네트워크 스택에 이르는 이벤트에 반응함에 따라 혹은 키를 누를 때마다 변화합니다. 또한, Emacs는 문서 그 자체로 자체 설명적입니다. 이렇게 처리할 수 있는 편집기는 없습니다. 그에 근접한 편집기조차 없습니다.

그런데도 Emacs는 충돌하지 않습니다. 엄밀히 말해서 Emacs는 충돌하지 않는다는 사실을 증명하는 가동 시간 카운터가 있습니다(~M-x emacs-uptime~)—몇 달 동안 가동되는 경우도 드물지 않습니다.

따라서, Emacs에 어떤 질문을 던질 때—나중에 그 방법을 보여드리지만—여러분은 Emacs의 현재 상태가 어떤지 묻는 셈입니다. 이 때문에 Emacs는 훌륭한 Elisp 디버거를 갖추고 있으며 Emacs 인터프리터와 상태의 모든 측면에 제한없이 접근할 수 있습니다. 또한, 뛰어난 코드 완성 기능도 갖추고 있습니다. LISP 표현식을 만날 때마다 Emacs에게 이를 평가할 수 있으며 Emacs는 숫자 더하기부터 변수 설정, 패키지 다운로드까지 모든 작업을 수행합니다.


*** Extensiblility
확장성도 중요하지만 Emacs가 제공하는 가능성의 범위를 모른다면 중요성을 강조하기 어렵습니다. 여기선 Emacs가 무엇을 처리할 수 있는지 좀 더 중요하게는 Emacs가 사람들에게 무엇을 가능하게 해주는지에 대한 몇 가지 예시만 담았습니다.

- *A speech interface for the blind*: 지난 25년 동안 =Emacspeak= 는 시각 장애가 있는 Emacs 사용자들에게 화면에 표시된 내용을 이해하는 음성 인터페이스를 통해 Emacs 및 주변 환경과 상호작용할 수 있는 방법을 제공했습니다. Emacspeak는 소스 코드의 다양한 구문 요소를 반영하거나 레이아웃, 글꼴, 그래픽 아이콘을 강조하기 위해 음성 엔진의 음성 특성으로 변경합니다.

시각 장애가 있는 Emacs 사용자에게 Emacspeak은 이메일이나 웹 브라우징 같은 Emacs의 다양한 도구를 사용해서 작업할 수 있게 해준 생명의 끈과 같은 존재입니다. 이런 기능이 25년 동안 지속됐다는 사실도 인상적이지만 이런 소프트웨어를 지원할 수 있는 Emacs의 능력이야말로 감동 그 자체입니다.

- *Remote file editing*: Emacs의 =TRAMP= 를 사용하면 SSH, FTP, Docker, rclone, rsync 등 다양한 네트워크 프로토콜을 통해 원격 파일을 마치 로컬 파일처럼 매끄럽게 편집할 수 있습니다.

- *Shell access*: Emacs는 ANSI를 지원하는 내장 터미널 에뮬레이터가 있으며 bash 같은 셸을 감싸는 Emacs 래퍼 그리고 전적으로 Elisp로 작성된 셸인 =Eshell= 이 포함됩니다.

- *ORG mode*: 할 일 관리, 일정 관리, 프로젝트 계획, 리터러시 프로그래밍, 메모 작성(그 외 다양한 기능!)을 지원하는 통합 애플리케이션입니다. 이 앱은 역대 최고의 텍스트 기반 일정 관리 도구로 널리 인정받고 있으며 이보다 더 놀라운 점은 사람들이 이 앱을 사용하기 위해 Emacs로 전환한다는 사실입니다.

- *Symbolic Calculator*: 역-폴란드 표기법(RPN) 계산기로 기호 대수, 임의 정밀도 연산, 사용자 정의 함수, 행렬 및 단위 기반의 수학 연산 등 다양한 기능을 지원합니다.

- *Music Player*: Emacs 멀티미디어 시스템(EMMS)은 대화형 미디어 브라우저이자 음악 플레이어입니다.

- *And much more*: 거의 모든 프로그래밍 환경에 대한 공식 또는 비공식 지원; 내장 매뉴얼 페이지 및 인포 리더; 정교한 디렉터리 및 파일 관리자; 대부분의 버전 관리 시스템에 대한 원활한 지원; 그리고 크고 작은 수백 가지 기타 기능이 포함됩니다.



** Important Conventions
진행하기 전에 몇 가지 중요한 Emacs 관례를 설명하겠습니다. 이런 관례는 반드시 외우거나 의문이 생길 때마다 이 페이지를 다시 찾아보는 것이 중요합니다. 이런 관례는 이 책과 다른 곳에서 반복 등장하며 방대한 Emacs의 내부 문서를 제대로 활용하려면 이를 숙지하는 것이 무엇보다 중요합니다.

이 목록은 Emacs 혹은 이 책에서 사용하는 관례의 모든 것을 망라한 것이 아닙니다. 책 전체에 구체적인 용어와 개념을 소개하지만 일부 용어는 특정 주제를 초월하므로 알아두는 것이 중요합니다.


*** The Buffer
대부분의 텍스트 편집기와 IDE는 파일 기반입니다. 즉, 파일의 텍스트를 표시하거나 파일에 저장할 뿐입니다. 그게 전부입니다!! Emacs에서 모든 파일은 버퍼지만 모든 버퍼가 파일은 아닙니다!! 로그 파일에서 가져온 텍스트 조각을 임시로 저장하거나 텍스트를 조작하거나 그 밖의 어떤 이유로든 일회성 작업 공간이 필요하면 그냥 새로운 버퍼를 생성하고 사용하면 됩니다. Emacs는 파일 이름을 묻는 번거로움을 주지 않습니다. 하지만, 이런 버퍼는 Emacs 내에서만 존재합니다!! 따라서, 이를 영구적으로 유지하려면 디스크 파일로 명시적으로 저장해야 합니다.

Emacs는 버퍼를 단순히 텍스트 편집에 사용하는 것이 아닙니다. 버퍼는 마치 I/O 장치처럼 작동해서 bash 같은 셸이나 심지어 Python 같은 다른 프로세스와 통신할 수 있습니다.

Emacs 명령 대부분은 버퍼를 대상으로 작동합니다. 예를 들어, Emacs에게 검색 및 바꾸기를 지시하면 실제로는 버퍼에서 검색 및 바꾸기를 수행합니다. 현재 작성 중인 활성 버퍼일 수도 있고 임시 복제본일 수도 있습니다. 여러분이 생각할 수 있는 불투명한 폐쇄된 데이터 구조가 아닙니다. Emacs에선 버퍼가 데이터 구조입니다. 이는 매우 강력한 개념입니다. 왜냐하면, Emacs에서 이동하거나 편집할 때 사용하는 명령어들은 항상 elisp 내부에서 사용하는 명령어와 동일하기 때문입니다. 따라서, 일단 Emacs의 명령어를 익히면 간단한 함수 호출을 통해 직접 손으로 처리하는 작업을 모방할 수 있습니다.


*** The Window and the Frame
버퍼는 화면에 창으로 표시됩니다. 하지만, Emacs에서 창이란 단순히 프레임의 일부를 타일 형태로 나눈 것에 불과하며 이는 대부분의 윈도우 매니저에서 창이라 부르는 것과 같습니다. Emacs는 그 반대인데 네, 정말 혼란스럽습니다.

그림

위의 스크린샷을 보면 두 개의 창과 하나의 프레임이 보입니다. 프레임은 하나 이상의 창을 가질 수 있으며 창은 정확히 하나의 버퍼를 가집니다. 따라서, 버퍼가 사용자에게 표시되려면 창으로 보여야 하며 창을 사용자에게 표시하려면 프레임에 있어야 합니다.

#+BEGIN_QUOTE
[!NOTE]
*참고*:
이것은 마치 프레임이 달린 물리적인 창문이라 생각해야 합니다. 프레임은 창유리로 이루어져 있습니다.
#+END_QUOTE

Emacs는 원하는만큼 프레임을 자유롭게 생성할 수 있으며 각 프레임을 여러 개의 창으로 분할하거나 배열할 수 있습니다. 대형 모니터를 사용한다면(요즘 누가 그렇지 않겠습니까?), Emacs의 타일링 시스템을 활용해서 화면에 여러 개의 버퍼를 표시하는 것은 유용합니다.


*** Modeline, Echo Area, and Minibuffer

그림

위의 그림은 터미널 모드 Emacs 세션입니다. Emacs는 모드라인으로 Emacs 자체와 현재 열려있는 버퍼에 대한 정보를 표시합니다. 모드라인은 다음과 같습니다:

#+BEGIN_SAMPLE
-UUU:**--F3 *scratch* All L4 (Lisp Interaction) --
#+END_SAMPLE

좁은 공간에 많은 정보가 담겨져 있습니다. 주목할 부분은 버퍼 이름과 메이저 모드입니다. 이 경우 버퍼 이름은 =*scratch*= 이며 메이저 모드는 =Lisp Interaction= 입니다. 대부분의 편집기는 상태표시줄(status bar)이란 이와 유사한 개념이 있습니다.

모드라인(modeline)은 문서의 비율, 현재 실행 중인 함수나 클래스, 사용 중인 소스 제어 리비전이나 브랜치 등 다양한 정보를 표시할 수 있습니다.

미니버퍼(minibuffer)는 모드라인 하단에 위치하며 오류 및 일반 정보를 표시합니다:

#+BEGIN_SAMPLE
-UUU:**--F3 *scratch* All L4 (Lisp Interaction) --
M-x insert-hello-world
#+END_SAMPLE

이 경우 저는 Emacs 확장 명령을 호출했습니다. 이 기능은 ~M-x~ 로 표시하며 이에 대해서는 키에 관한 장에서 자세히 다루겠습니다. 그리고 ~M-x~ 프롬프트에 ~insert-hello-world~ 명령을 입력했습니다.

에코 영역(echo area)과 미니버퍼는 화면상 동일한 위치를 공유합니다. 미니버퍼는 일반 버퍼와 거의 동일합니다. 대부분의 편집 명령을 사용할 수 있으며 한 줄로 구성된 미니버퍼는 필요에 따라 여러 줄로 자동 확장됩니다. 이것이 바로 Emacs와 소통하는 주요 수단입니다. 문자열을 검색하려면 미니버퍼에 검색할 문자열을 입력합니다. 미니버퍼는 필요한 내용을 찾도록 도와주는 자동 완성 메커니즘도 지원하며 이는 아마 여러분이 가장 자주 사용할 필수 도구입니다.


*** The Point and Mark
‘포인트(point)’ 는 캐럿(caret)이나 커서(cursor)를 의미하는 또 다른 표현입니다. Emacs 문서에서 ‘포인트’ 와 ‘커서’ 를 다소 일관성없이 사용하므로 두 용어 모두 등장합니다. 그럼에도 불구하고 포인트 자체는 버퍼의 현재 위치를 의미합니다. 이 책은 =█= 문자로 표시합니다. 각 버퍼는 포인트의 위치를 개별 추적하므로 버퍼를 전환해도 포인트 위치는 기억됩니다.

#+BEGIN_QUOTE
[!NOTE]
*참고*:
Emacs에서 “현재 버퍼” 를 자주 이야기하는데 이 용어는 두 가지 의미를 가집니다.
현재는 그 중 하나만 관심가질 만한데 커서가 위치한 버퍼를 의미합니다.
(다른 경우는 기본적으로 동일하지만 elisp 프로그래밍으로 버퍼를 변경한 경우입니다.)

포인터가 있는 버퍼가 현재 버퍼인 이유는 바로 그 버퍼에 글을 쓰거나 커서를 움직이기 때문입니다.
한 번에 하나의 버퍼만 현재 버퍼가 될 수 있으며 바로 이 버퍼가 포인터를 가집니다.
#+END_QUOTE

Emacs에서 포인트는 단순히 사용자가 입력한 문자가 화면 어느 위치에 표시되는지 시각적으로 표시하는 역할을 넘어 좀 더 많은 용도로 사용됩니다. 포인트는 또한 ‘포인트’ 와 ‘마크’ 로 불리는 한 쌍의 요소 중 하나입니다. 포인트와 마크는 영역의 경계를 의미하며 여기서 영역이란 현재 버퍼의 연속된 텍스트 블록을 의미합니다. 다른 편집기에선 이를 선택 영역이나 하이라이트라고 부릅니다. 대부분의 편집기는 영역의 시작점과 끝점을 가리키는 구체적인 명칭이 없지만 이맥스는 있으며 ‘선택 영역과 영역’ 섹션에서 그 이유에 대해 자세히 설명합니다.

#+BEGIN_QUOTE
[!NOTE]
*팁*:
역사적으로 Emacs는 화면에 가시적인 영역을 표시하지 않으므로 사용자는 마음속으로 이를 시각화해야 했습니다.
Emacs는 오랫동안 '일시적 마크 모드(TMM)' 라 불리는 시각적 영역 기능을 지원했습니다. 이 기능은 기본으로 활성화됩니다.
놀랍게도 TMM을 사용하지 않는 것도 가치가 있겠지만 이에 대해서는 나중에 자세히 다루겠습니다.
#+END_QUOTE

하지만, 포인트와 마찬가지로 마크도 겉으로 보이는 것 이상의 의미를 지닙니다. 마크는 해당 지역의 경계를 표시하는 역할도 처리하지만 버퍼의 다른 곳에서 다시 돌아올 수 있는 이정표 역할도 처리합니다. 마크도 눈으로 보이지 않습니다.


***  Killing, Yanking and CUA
표준 사용자 인터페이스에서 가장 많이 벗어난 첫 번째 요소이자 초보자에게 가장 거부감을 주는 것은 Emacs의 클립보드 시스템입니다. 잘라내기, 복사, 붙여넣기는 보편적으로 ~Ctrl+x~ 또는 ~Shift+Delete~, ~Ctrl+c~ 또는 ~Ctrl+Insert~ 그리고 ~Ctrl+v~ 또는 ~Shift+Insert~ 로 알려져 있습니다.

Emacs는 이런 키와 용어가 크게 다릅니다!!: 'killing' 은 잘라내기, 'yanking' 은 붙여넣기, 복사는 어색하지만 'kill ring에 저장하기' 라고 불립니다(비공식적으로는 그냥 'copy' 라고 합니다).

이는 앞서 언급했듯이 역사적인 이유입니다. 대부분의 키와 용어는 IBM의 =Common User Access= (CUA) 및 Apple에서 유래했습니다. 하지만, CUA는 1987년 도입됐는데 이 시기는 Emacs가 자신만의 용어와 표준을 확립한 지 수 년이나 지난 이후입니다.

'선택 호환 모드' 섹션에서 저는 몇 가지 주의 사항과 현대적인 클립보드 키로 전환하는 방법과 또한 그렇게 해선 안되는 이유를 설명합니다. 대신, 텍스트 편집에 Emacs 시스템이 좀 더 나은 이유도 보여드리겠습니다.


*** emacs.d, init.el, and emacs
Emacs 사용자들이 가장 즐겨하는 취미 중 하나는 자신의 작업을 좀 더 편리하게 만드는 작은 코드 조각이나 사용자 설정을 다른 Emacs 사용자들과 공유하는 것입니다.

예전에는 이런 설정들은 =.emacs= 라는 단일 파일에 저장했지만 리눅스는 =~/.emacs.d/init.el=, 윈도우는 =%HOME%\init.el= 파일에 사용자 설정을 보관합니다. 현재 Emacs는 파일 시스템에 보다 많은 파일을 생성하므로 홈 디렉터리가 복잡해지는 것을 방지하기 위해 이 파일들은 =.emacs.d= 라는 전용 디렉터리에 보관됩니다.

#+BEGIN_QUOTE
[!NOTE]
*XDG Support in Emacs 27*:
Emacs 27 이상은 이를 지원하는 리눅스 플랫폼에서 사용자 설정을 =~/.config/emacs/init.el= 에 저장하는 XDG 표준을 지원합니다.
#+END_QUOTE

따라서, 사람들이 자신의 init 파일이나 “.emacs 파일” 을 이야기하거나 해당 파일에 무언가 추가하라고 말할 때는 바로 그 파일을 의미합니다. Emacs를 처음 사용하면 =~/.emacs.d/init.el= 파일을 사용합니다. 이 파일에 내용을 추가한 후에는 Emacs가 이를 적용하도록 지시해야 합니다. 이를 적용하는 방법도 여러 가지로 ‘Elisp 코드 평가하기’ 섹션에서 보다 자세히 설명하지만 초보자는 단지 Emacs를 종료했다가 다시 시작하는 방법을 권장합니다.

#+BEGIN_QUOTE
[!NOTE]
*참고*:
요즘엔 Emacs 스타터 키트가 흔해졌습니다.
이것은 Emacs에 커뮤니티 차원에서 추가한 것으로 다양한 수정이나 심지어 타사 패키지를 한데 묶어 제공합니다.
만약, 스타터 키트를 사용한다면 수정 사항을 어디 저장하는지 확인하려면 해당 문서를 읽어봐야 합니다.
#+END_QUOTE

Emacs는 변경 사항을 자동으로 저장하지 않습니다!! Emacs에서 변경 사항을 유지하려면 ‘Customize’ 인터페이스로 저장해야 합니다. 즉, 유지하려는 변경 사항은 사용자가 init.el 파일에 직접 저장해야 합니다. 마찬가지로, 실수로 Emacs에 오류가 발생했거나 원치않는 변경을 가한 경우 단순히 Emacs를 종료한 후 다시 시작합니다.


*** Major Modes and Minor Modes
Emacs의 메이저 모드는 버퍼의 동작 방식을 제어합니다. 예를 들어, 파이썬 코드를 편집하려고 Emacs에서 /helloworld.py/ 파일을 열면 Emacs는 파일 확장자를 메이저 모드와 매핑하는 중앙 집중식 레지스터를 통해 파이썬 파일임을 인식하고 파이썬 메이저 모드를 사용한다는 것을 알게 됩니다. 모든 버퍼는 항상 메이저 모드가 지정됩니다. 메이저 모드는 글꼴 잠금(구문 강조) 기능만 제공하고 특별한 기능이 없는 기본적인 형태일 수도 있고 그와 반대로 글꼴 잠금, 고급 들여쓰기 엔진, 특수 명령어 등을 제공하는 완전히 다른 형태일 수도 있습니다.

#+BEGIN_QUOTE
[!NOTE]
*참고*:
‘폰트 락킹(Font Locking)’ 은 Emacs의 구문 강조(syntax highlighting)를 지칭하는 용어이며
이는 폰트 락킹 엔진이 텍스트를 보기좋게 표시하기 위해 사용하는 속성(색상, 폰트, 텍스트 크기 등)의 집합인 ‘페이스(face)’ 로 구성됩니다.
Emacs의 용어인 ‘페이스’ 와 ‘폰트 락킹’ 은 다른 곳에서 흔히 볼 수 있는 용어보다 훨씬 먼저 등장했습니다.
#+END_QUOTE

다른 모드 명령어를 입력해서 언제든지 버퍼의 메이저 모드를 변경할 수 있습니다. Emacs의 파일 확장자 및 메이저 모드 레지스터 외에도 파일 확장자가 모호하거나 아예 없는 파일을 위한 또 다른 감지 시스템이 있습니다. Emacs는 파일 앞부분을 스캔해서 메이저 모드를 추측합니다. 드물게 Emacs가 잘못 판단할 경우도 있으므로 사용자가 직접 변경할 수도 있습니다.

버퍼는 오직 하나의 메이저 모드만 가질 수 있다는 점을 기억합니다. 반면, 마이너 모드는 일반적으로 일부(또는 모든) 버퍼에서 활성화할 수 있는 선택적인 추가 기능입니다. 한 가지 예로는 글을 작성할 동안 문법 검사를 수행하는 마이너 모드인 ~flyspellmode~ 가 있습니다.

메이저 모드는 항상 모드라인에 표시됩니다. 일부 마이너 모드도 모드라인에 표시하지만 대개 버퍼 자체나 사용자와의 상호작용 방식을 어떤 식으로든 변경하는 모드만 표시됩니다.




* Chapter 3. First Steps

#+BEGIN_QUOTE
I use Emacs, which might be thought of as a ther-monuclear word processor.  

– Neal Stephenson, In the Beginning… was the CommandLine.
#+END_QUOTE


** Installing and Starting Emacs
Emacs 설치 방법에 대해 자세히 설명하기 전에 시스템에 이미 설치된지 확인합니다. 하지만, 설치되어 있더라도 주의해야 합니다. 아주 오래된 버전일 수도 있으니까요...

#+BEGIN_QUOTE
[!NOTE]
*Checking Emacs's version*:  
~emacs --version~ 을 입력하면 Emacs 버전을 확인할 수 있습니다. 
#+END_QUOTE

2022년 현재 최신 버전은 =GNU Emacs 28= 입니다. 가능한 한 최신 버전으로 사용하시길 권장합니다. 항상 최신 버전을 유지하도록 노력해야 합니다. Emacs의 메이저 릴리스는 그다지 빈번하진 않으므로 최신 상태로 유지하는 데 큰 어려움은 없습니다. 무언가 업그레이드했다면 버그 수정 때문은 아니며 (왜냐하면, Emacs는 실제로 매우 안정적이기 때문입니다) 기능 추가이며 대부분의 패키지 작성자는 사용자가 최신 버전을 사용한다고 가정하기 때문입니다. (그렇지만, 매우 생소한 플랫폼을 사용 중이라면 업그레이드가 불가능할 수 있습니다.)

XEmacs나 다른 비-GNU Emacs를 사용한다면 꼭 전환해야 합니다. 15년 전만 해도 XEmacs가 선두를 달렸지만 GNU Emacs는 오래 전에 XEmacs의 모든 기능을 따라잡았고 이미 능가했습니다.

Emacs의 특징 중 하나는 호환성을 깨는 비추천 단계에서 제거까지 여러 번의 메이저 릴리스가 필요하단 오래된 신념입니다. 드물게 1980년대 후반에 작성한 코드 조각이 Emacs 유지보수자들이 오래 전부터 쓸모없어진 변수나 함수를 제거했기 때문에 작동하지 않는다는 불만이 Emacs 메일링 리스트로 쏟아지기도 합니다.

Emacs는 여러분이 사용할 가능성 높은 대부분의 주요 플랫폼 즉, BSD와 리눅스, Mac OS X, MS-DOS 그리고 Microsoft Windows를 지원합니다. 리눅스 이외의 운영체제에서 Emacs를 컴파일하거나 빌드하는 방법은 자세히 다루지 않습니다. Emacs는 크로스 플랫폼 에디터로 설계됐지만 리눅스 이외의 환경에서 실행할 경우 어느 정도의 타협이 필요합니다. 특히 Mac OS X의 경우 Emacs 실행 방법에 대한 상반된 조언이 많이 존재합니다. 제가 드릴 수 있는 조언은 몇 가지 방법을 시도한 후 자신에게 맞는 방법을 찾는 것입니다.

- *Microsoft Windows* : Emacs는 공식 웹사이트에서 Microsoft Windows용 공식 빌드를 제공합니다. 파일을 압축 해제하고 실행하면 됩니다.

하지만, 대부분의 외부 도구 지원은 Windows에서 작동하지 않습니다. ~grep~ 같은 기능은 =GNU coreutils= 패키지가 설치되야 작동합니다. 하지만, Cygwin 환경에서 Emacs를 실행하면 Windows도 리눅스와 유사한 환경을 구축할 수 있습니다. 또는, 크로스 컴파일된 GnuWin32 프로젝트는 거의 모든 리눅스 명령줄 프로그램을 Windows에서 네이티브로 실행할 수 있습니다.

최근 등장한 또 다른 방법은 Windows 10의 서브시스템에서 리눅스를 네이티브로 실행하는 호환성 레이어인 =Windows Subsystem for Linux= (WSL)를 사용하는 것입니다.

- *Mac OS X*: 여러 방법이 있지만 한 가지 접근 방식은 비공식 Emacs 빌드를 사용하는 것입니다. Aquamacs도 있지만 이는 GNU Emacs와 상당히 다릅니다!! 이 주제는 그 자체로 꽤 복잡합니다. 어떤 사람은 homebrew 같은 패키지 관리자를 선호하지만 그렇지 않은 사람도 있습니다. 일반적으로 homebrew를 사용하는 사람들은 homebrew 버전의 Emacs도 함께 사용할 경우가 많습니다. EmacsWiki의 Mac OS X 카테고리의 Emacs 설치하기 문서는 Emacs를 직접 컴파일할 때 시작하기 좋은 자료입니다.

- *Linux* : Emacs는 거의 항상 배포판의 패키지 관리자에 포함되어 있습니다. 일부 배포판은 새로운 마이너 릴리스(사실 마이너 릴리스라기엔 무리일 정도로 많은 신규 기능과 버그 수정이 포함되어 있음)로 업데이트하는 데 시간이 오래 걸릴 수 있으므로 소스 코드를 직접 컴파일해서 설치하는 것이 나을 수 있습니다.

예를 들어, Ubuntu 리눅스는 ~apt-get install emacsNN~ 명령을 입력합니다. 여기서 =NN= 은 Emacs의 메이저 버전(26, 27 등)을 의미합니다.

소스 코드로 Emacs를 빌드하혀면 ~apt-get build-dep emacsNN~ 으로 종속성을 빌드한 후 설치할 것을 권장합니다. 그 이후는 빌드 지침에 설명된 일반적인 ~configure, make, make install~ 절차를 따릅니다.

 
*** Starting Emacs
Emacs를 시작하는 방법은 명령줄에서 ~emacs~ 를 실행하는 것만큼 간단합니다. 창 관리자에서 실행하면 터미널로 실행되는 터미널 Emacs가 아닌 GUI Emacs로 실행합니다. 창 관리자 환경도 ~-nw~ (no window)인수를 지정해서 Emacs가 터미널 모드로 실행되도록 강제할 수 있습니다. 예를 들어, ~emacs -nw~ 같이 입력합니다.

Emacs에 전달할 수 있는 명령줄 스위치도 많지만 시작하기 위해선 다음 네 가지만 있으면 됩니다:

| 옵션     | 용도                                                                         |
|----------+------------------------------------------------------------------------------|
| ~--help~ | 도움말을 표시합니다                                                          |
| ~-nw~    | Emacs를 터미널 모드로 강제 실행합니다                                        |
| ~-q~     | 초기화 파일(예: ~init.el~)을 로드하지 않습니다                               |
| ~-Q~     | 사이트 전체 시작 파일, 사용자의 초기화 파일, X 리소스 모두 로드하지 않습니다 |

Emacs를 시작할 때 오류 메시지가 표시되면 ~-q~ 옵션으로 초기화 파일(init file)이 로드되지 않도록 처리할 수 있습니다. 이렇게 해서 오류가 해결되면 초기화 파일 문제로 이를 해결하기 위한 조치를 취합니다. 이전 버전으로 되돌리거나 제대로 작동할 때까지 코드를 주석 처리하거나 도움을 요청하시기 바랍니다.

Emacs 바이너리(~emacs~)는 일반적인 명령줄 규칙을 따릅니다: ~emacs [옵션] [파일1, 파일2, ...]~ 

Emacs의 작업 방식은 프로그램을 계속 실행한 상태로 두고 Emacs 인스턴스에서 모든 작업을 수행하는 것입니다. Emacs는 빠른 편집보단 장시간 실행되는 세션을 처리하도록 설계됐기 때문에 (훨씬 더 많은 패키지와 기능을 가집니다) 일반적으로 다른 편집기보다 시작 속도는 조금 느립니다.


*** Emacs Client-Server
명령줄에서 갑자기 파일을 편집해야 한다면 어떻게 할까요? 예를 들어, 명령줄에서 이메일을 작성하거나 커밋 메시지를 작성할 때 Emacs를 사용하고 싶을텐데 가급적이면 이미 실행 중인 Emacs 인스턴스를 그대로 사용하고 싶을 것입니다. Emacs가 이메일과 소스 제어 시스템 모두 완벽히 지원한다는 사실은 제쳐두고 해답은 바로 Emacs의 클라이언트-서버 모드입니다.

#+BEGIN_QUOTE
[!NOTE]
*참고*:  
클라이언트-서버 기능도 정말 훌륭하지만 Emacs 기본 기능에 익숙해지기 전까지는  
이 기능을 만지면서 시간을 보내진 않는 게 좋습니다.
#+END_QUOTE

Emacs 서버 모드의 장점은 다음과 같습니다:

- 지속적인 세션이란 Emacs가 별개의 Emacs 인스턴스를 생성하는 대신 동일한 세션을 재사용한다는 것을 의미합니다.
- Emacs 세션에서 파일을 열고 세션이 종료되면 호출 프로그램에 자동으로 신호를 보내는 방식으로 ~$EDITOR~ 환경 변수와도 잘 연동됩니다.
- ~emacsclient~ 바이너리로 명령줄에서 파일을 열 수 있습니다. Emacs 클라이언트는 로컬 Emacs 서버 인스턴스에 연결한 후 파일을 엽니다.

Emacs의 클라이언트-서버 모드를 활성화하는 방법이 몇 가지 있습니다: ~M-x server-start~ 는 실행 중인 Emacs 인스턴스에서 서버 모드를 시작합니다. 이 명령을 입력하면 해당 인스턴스는 서버 모드로 전환됩니다. 서버 모드로 실행 중이란 것을 알려주는 시각적인 피드백은 없습니다. Emacs 인스턴스를 종료하면 서버도 함께 종료되므로 서버 데몬을 원한다면 다음과 같은 옵션을 사용합니다.

#+BEGIN_QUOTE
[!NOTE]
*Emacs 28*:  
윈도우 매니저를 사용하고 최신 버전이면 Emacs(클라이언트)를 실행하거나
지정 항목으로 파일을 열도록 설정해서 기존 Emacs 인스턴스를 재사용할 수 있습니다.
#+END_QUOTE

~emacs --daemon~ 은 Emacs를 데몬 모드로 실행합니다. 위와 마찬가지로 ~server-start~ 를 호출하지만 터미널로 제어권을 즉시 반환하고 백그라운드에서 실행되며 클라이언트의 요청을 대기합니다.

운영체제가 =systemd= 를 지원할 경우 Emacs는 =systemd= 에 대한 기본 지원도 제공합니다. Emacs 26 이상은 ~systemctl --user enable emacs~ 명령으로 systemd 유닛 파일을 자동으로 구성합니다. 이후 Emacs 데몬은 systemd로 관리합니다.

서버 모드로 실행했다면 더이상 ~emacs~ 바이너리는 사용할 수 없습니다!! 해당 바이너리는 독립 실행형 인스턴스로 시작합니다. 대신 이름이 비슷한 ~emacsclient~ 를 사용합니다. ~$EDITOR~ 환경 변수를 ~emacsclient~ 로 설정하면 모든 것이 정상 작동합니다.

~emacsclient~ 바이너리에서 알아둘 고유한 옵션이 있습니다:

| 옵션     | 용도                                                                                                |
|----------+-----------------------------------------------------------------------------------------------------|
| ~--help~ | 도움말을 표시합니다.                                                                                |
| ~-c~     | 그래픽 창을 생성합니다(X가 사용 가능한 경우). X를 사용할 수 없는 경우 터미널 창을 생성합니다.       |
| ~-nw~    | 터미널 창을 생성합니다.                                                                             |
| ~-n~     | 클라이언트는 변경 사항을 저장할 때까지 기다리지 않고 즉시 종료합니다. 여러 파일을 열 때 유용합니다. |

~emacsclient~ 로 실행하면 파일 편집을 완료할 때까지 대기합니다. ~C-x #~ 으로 (편집 중인) 다음 버퍼로 전환합니다. 열어둔 파일에 작업을 모두 마치면 Emacs는 클라이언트에 종료 신호를 보내고 제어권을 터미널로 반환합니다. =git= 같은 프로그램을 사용할 때 ~$EDITOR~ 환경 변수로 커밋 메시지를 편집할 수 있는 편집기로 사용할 경우 =git= 은 편집기로부터 커밋 메시지가 임시 파일에 저장됐다는 확인 신호를 받을 때까지 기다린 후 커밋 작업을 재개합니다.

클라이언트가 파일을 즉시 열고 기다리지 않으려면 ~-n~ 옵션을 추가합니다. 저는 탐색 작업할 때나 Emacs에서 파일을 영구히 열어둘 때 이 옵션을 사용합니다.


** The Emacs Interface

그림

Emacs를 처음 실행하면 스플래시 화면이 나타납니다. 이 화면에는 스크롤바, 메뉴, 도구 모음과 함께 대부분의 Emacs 사용자들이 제일 먼저 비활성화하는 요소 중 하나입니다. Emacs 사용에 익숙해질 때까지 UI 요소를 활성화된 상태로 둘 것을 권장합니다. 비록 귀중한 화면 공간을 차지하지만 기억나지 않을 수도 있는 기능에 빠르게 접근할 수 있는 방법을 제공하기 때문입니다.

#+begin_quote
[!NOTE]
터미널 모드로 Emacs를 실행할 경우 =F10= 키로 메뉴에 접근할 수 있습니다.
#+end_quote

위의 그림과 유사한 사용자 인터페이스가 보이지 않으면 init 설정 파일에 적용된 사용자 정의 설정 때문일 가능성이 높습니다. 이를 확인할 가장 빠른 방법은 Emacs를 종료한 후 ~emacs -q~ 명령어로 시작하는 것입니다. 이렇게 해서 문제가 해결된다면 분명 Emacs에 적용된 사용자 지정 설정 때문입니다. 대부분의 스타터 키트는 사용자가 Emacs에 어느 정도 익숙하다고 가정하므로 종종 메뉴 바나 도구 모음 같은 요소를 비활성화합니다.

이제 자유롭게 Emacs를 사용할 수 있습니다. 화살표 키도 작동하며 메뉴로 파일을 열거나 저장할 수 있습니다. Emacs는 대부분의 파일 유형을 자동 감지해서 적절한 메이저 모드를 적용합니다. 그렇지 않으면 나중에 설명할 제3자 패키지를 설치해야 할 수도 있습니다.


** Keys
이는 Emacs에서 가장 중요한 주제로 Emacs는 두 가지로 유명합니다. 알기힘든 키보드 단축키와 무엇이든 처리할 수 있는 만능 에디터라는 점입니다. xkcd 만화는 Emacs의 이런 전설을 유머러스하게 다뤘습니다. 농담삼아 Emacs는 “Escape Meta Alt Control Shift” 약자라고 말합니다.

그럼에도 불구하고 수정 키는 Emacs 사용법에서 큰 부분을 차지하므로 일련의 키를 해독할 수 있다는 것은 매우 중요합니다!!

Emacs는 여러 수정 키가 있으며 각각 고유한 특성을 가집니다:

| 수정자 | 전체 이름                      |
|--------+--------------------------------|
| ~C-~   | Control                        |
| ~M-~   | Meta (대두분의 키보드는 "Alt") |
| ~S-~   | Shift                          |

역사적인 이유로 두 가지 키(~Super~ 와 ~Hyper~)가 존재하지만 오늘날 키보드엔 이 키가 없습니다. 하지만, /Space Cadet/ 키보드와의 일관성을 위해 내부엔 여전히 키가 존재합니다. 현대의 키보드는 또 다른 키(~Alt~)로 존재하지만 Emacs는 ~Meta~ 로 지정되어(그리고 알려져) 있습니다:

| 수정자 | 전체 이름                |
|--------+--------------------------|
| ~s-~   | Super (Shift가 아님!)    |
| ~H-~   | Hyper                    |
| ~A-~   | Alt (중복 사용되지 않음) |

따라서, ~Super~ 와 ~Hyper~ 키도 여전히 사용할 수 있으며 Microsoft Windows 호환 PC 키보드나 프로그래밍 가능한 키보드를 사용할 경우 ~Start~ 및 ~Application~ 컨텍스트 버튼이 장착된 키보드를 사용하면 이 버튼을 슈퍼 및 하이퍼 키로 재할당할 수 있습니다. 이는 키 공간을 확장하는 우아한 처리 방법입니다. Emacs는 기본적으로 이 수정 키를 지원하지만 운영체제나 윈도우 매니저로 이 키를 재할당해야 합니다.

#+BEGIN_QUOTE
[!NOTE]
*중요*:  
터미널 한계로 터미널에서 Emacs를 실행할 때 입력할 수 없는 키 바인딩 몇 가지가 있습니다.  
가능하다면 Emacs는 GUI 환경에서 실행할 것을 권장합니다.
#+END_QUOTE

하지만, 수정 키를 아는 것은 절반에 불과합니다.

Emacs에서 키 시퀀스(또는 단순히 키)는 공식적으로 키보드(또는 마우스) 동작의 연속으로 정의되며 ‘완전한 키’ 는 명령을 호출하는 하나 이상의 키보드 시퀀스를 의미합니다. 만약 이 키 시퀀스가 완전한 키가 아니라면 접두사 키입니다. 그리고 키 시퀀스가 Emacs에서 인식되지 않으면 유효하지 않은 것이며 에코 영역에 오류 메시지로 표시됩니다.

이는 다소 딱딱한 정의로 몇 가지 예를 들어 설명하겠습니다.

- ~C-d~ : ~delete-char~ 명령을 호출합니다. 이 명령은 ~Control~ 키를 누른 상태에서 ~d~ 키를 누릅니다. 이 키 조합은 완성 키로 ~delete-char~ 명령을 호출하고 커서 위치의 문자를 삭제합니다.

- ~C-M-d~ : 위와 비슷하지만 이번엔 ~d~ 키를 누르기 전에 ~Control~ 과 ~Meta~ (~Alt~)키 모두 눌러야 합니다.

기본적으로 접두사 키는 하위 분류된 키를 그룹화해서 키 조합의 수를 늘리는 방법입니다. 예를 들어, 접두사 키 ~C-x~ 는 수십 개의 하위 키가 할당되어 있습니다. ~C-x~ 는 여러분이 항상 사용할 필수 접두사 키입니다.

- ~C-x C-f~ : Emacs에서 이 명령은 ~find-file~ 명령을 실행합니다!! 이 명령은 ~Control~ 키를 누른 상태에서 ~x~ 키를 눌렀다 놓습니다. 에코 영역에 대략 1초 정도 대기 시간이 지난 후  ~– C-x-~ (끝에 대시(-) 문자가 붙은 형태)를 표시하는데 이는 추가 입력을 기다리고 있음을 알리는 Emacs만의 표현 방식입니다. 마지막으로 ~C-f~ 를 입력합니다. 이제 쉽게 입력할 수 있습니다: ~Control~ 키를 누른 상태에서 ~f~ 키를 누릅니다. 또한, ~C-x C-f~ 를 입력할 때 각 키마다 컨트롤 키를 놓을 필요는 없습니다. 컨트롤 키를 계속 누르면 제가 '템포' 라 부르는 것을 유지하는 데도 도움되는데 이에 대해서는 나중에 설명하겠습니다.

- ~C-x 8 P~ : 두 개의 접두사 키가 있습니다: 첫 번째는 ~C-x~, 그 다음은 ~8~ 입니다. 여기서 ~8~ 은 ~C-x~ 의 하위 범주에 속합니다. 따라서, ~8~ 만 누르면 아무 일도 일어나지 않으며(단순히 숫자 8 이 출력될 뿐입니다) ~C-x~ 또는 ~C-x 8~ 만 눌러도 마찬가지입니다. 둘 다 접두사 키이기 때문입니다. 이 키 조합은 마지막 ~P~ 로 끝마쳐야만 완성됩니다.

 접두사 키에 속하는 하위 키 집합을 키 맵(keymap)이라 부르며 Emacs가 내부에서 키와 명령의 매핑을 추적하는 방식입니다. 이 경우 키 맵 ~C-x 8~ 은 글쓰기나 수학 모드에서 주로 사용하지만 대부분의 키보드에 할당되지 않은 다양한 특수 문자들이 포함되어 있습니다. 예를 들어, ~C-x 8 P~ 를 입력하면 단락 기호 ~¶~ 를 삽입합니다.

- ~C-M-%~ : 초보자에겐 까다로운 키조합입니다. 앞서 배운 내용을 활용하면 컨트롤과 알트 키를 누른 상태에서 (위의 표에서 보셨듯이 메타 키는 알트 키입니다) 시프트 키도 함께 눌러야 합니다. ~%~ 기호는 보통 키보드 숫자 영역의 숫자 키에 배치되는데 중요한 점은 시프트 키도 함께 입력해야 한다는 것입니다. ~Shift~ 키를 누르지 않으면 ~C-M-5~ 를 입력하게 됩니다(적어도 미국식 키보드는 그렇습니다.) 이 키는 널리 사용하는 명령어(~M-x query-replace-regexp~)에 할당되어 있으며 터미널의 기술적인 한계로(Emacs의 문제가 아니라) 터미널 Emacs에선 입력할 수 없는 키의 대표적인 예라는 점을 언급할 필요가 있습니다.

- ~TAB, F1 – F12~ : 때때로 이렇게 표기하지만 ~<tab>, <f1>~ 같이 각괄호 형태로 표기합니다. ~TAB~ 을 문자 =T A B= 와 혼동하지 않는 것이 중요합니다. 저는 이런 모호함을 피하기 위해 전자의 표기법만 사용합니다.

#+BEGIN_QUOTE
[!NOTE]
*힌트*:  
작업이 막히거나 드물게 Emacs가 멈췄을 때 혹은 입력한 명령어 일부를 취소할 때는 ~C-g~ 키를 누릅니다.  
이것이 바로 Emacs에서 공통적으로 사용하는 “탈출” (escape command)명령어입니다!!
#+END_QUOTE


*** Caps Lock as Control
사용 환경을 설정할 때 가장 중요한 변경 사항 중 하나는 ~Caps Lock~ 키를 ~Control~ 키로 재설정하는 것입니다. ~Control~ 키를 자주 사용할될테니 Emacs에서 발생하는 ‘새끼손가락 통증 증후군’ (RSI)을 피하려면 오른쪽 ~Control~ 키의 기능을 완전히 해제하고 대신 ~Caps Lock~ 키로 사용할 것을 강력히 권장합니다!!

네, 적응 과정이 번거로울 수 있지만 그만한 가치는 충분합니다 (참고로 이 설정은 Emacs 외에서도 유용합니다.)

이런 변경은 구형 키보드에서 컨트롤 키가 현재 캡스 락 키 자리를 차지했기 때문에 필요한 변경 작업입니다. 왼쪽 컨트롤 키를 누를 때 왼쪽 새끼손가락에 무리를 주지 않고 누를 수 있습니다.

Windows는 =SharpKeys= 프로그램을 사용할 것을 권장합니다. Ubuntu와 Mac OS X는 기본 지원되므로 키보드 설정으로 이동해서 변경합니다. 다른 리눅스 배포판이라면 =xmodmap= 으로 설정합니다.

#+BEGIN_QUOTE
[!NOTE]
*Custom & Programmable Keyboards*:  
인체공학적인 기계식 키보드를 사용하면–보통 펌웨어를 사용자 정의할 수 있는 경우가 많습니다–한 걸음 더 나아가
모든 수정 키를 누를 때 새끼손가락을 사용하지 않도록 설정하는 것이 좋습니다.(Miryoku 배열)  

만약 키보드에 엄지 키가 있거나 키 레이어링 기능이 있다면(많은 고급 인체공학 기계식 키보드가 그렇듯이),  
적어도 컨트롤 키를 집게손가락이나 엄지손가락으로 쉽게 닿을 수 있도록 키보드 배열을 변경합니다.
#+END_QUOTE


*** M-x: Execute Extended Command
Emacs에서 사용할 수 있는 명령어 중 실제 키에 할당된 것은 극히 일부분에 불과합니다. 대부분 그렇지 않습니다. 드물게 사용하거나 키 바인딩할 필요가 없거나 원래 할당된 키를 재정의하면서 할당하지 않은 상태로 남겼거나 혹은 해당 명령어의 키 바인딩을 잊어버렸기 때문일 수 있습니다.

본질적으로 드물게 사용하는 명령을 실행할 경우도 아주 흔합니다. 이를 위해 ~M-x~ (멕스, M-x 또는 메타 x라고 발음)를 누릅니다. 미니버퍼에 프롬프트가 나타나면 실행할 명령 이름을 자유롭게 입력할 수 있습니다.

Emacs 사용자가 현재 “달의 위상을 보려면 ~M-x lunar-phases~ 를 실행하세요!” 라고 말할 때는 다음과 같습니다: 메타(~Alt~) 키를 누른 상태에서 ~x~ 를 누르면 미니버퍼(Emacs 화면의 맨 아래에 있는 줄)에 ~M-x~ 프롬프트가 표시됩니다. 이 시점에서 실행할 명령어 이름을 입력할 수 있습니다. 직접 한 번 해보시기 바랍니다. 그리고 ~lunar-phases~ 를 입력하고 ~RET~ 키를 누릅니다. ~lunar-phases~ 명령어는 화면에 새로운 창(버퍼)을 열고 달 위상을 표시합니다. ~C-x 1~ 로 다른 버퍼를 숨길 수 있습니다.

여러분이 입력한 명령에 ~RET~ 키를 눌러야 함을 알리기 위해 ~M-x lunar-phases RET~ 과 ~M-x lunar-phases~ 를 함께 표시하는 경우를 자주 볼 것입니다. 이는 입력을 요청하는 어떤 명령어도 마찬가지입니다. 진행하기 위해 ~RET~ 키를 사용하는지(또는 사용해선 안되는지)가 모호하거나 불분명하다고 판단되지 않는 한 ~RET~ 키는 생략하겠습니다.

#+BEGIN_QUOTE
[!NOTE]
*힌트*:  
실수로 ~M-x~ 를 입력하면 ~C-g~ 로 종료할 수 있다는 점을 항상 기억하시기 바랍니다!!
#+END_QUOTE

Emacs는 자동 완성 기능이 내장되어 있으므로 ~TAB~ 키를 누르면 새로운 창이 열리고 현재 사용 가능한 모든 후보를 나열합니다. 입력 중에 ~TAB~ 키를 누르면 Emacs가 자동으로 후보 목록을 좁혀줍니다. 입력 내용과 일치한 후보가 ~TAB~ 키를 누를 때 하나만 남았다면 Emacs는 전체 이름을 자동 완성합니다. 따라서, ~RET~ 키로 ~TAB~ 키와 마찬가지로 자동 완성 기능을 사용할 수 있으며 남은 후보가 하나뿐일 경우 명령어를 실행하는 추가적인 이점도 있습니다.

~M-x~ 가 특별한 Emacs 명령어라 생각할 수 있지만 사실 그렇지 않습니다. 이 명령어 역시 elisp 언어로 작성됐으며 다른 모든 기능과 마찬가지로 특정 키에 바인딩됐을 뿐입니다.

#+BEGIN_QUOTE
[!NOTE]
*Commands and functions* :  
제가 명령어라고 말할 때 사용자가 직접 호출할 수 있는 함수 유형을 의미합니다.  
함수가 사용자에게 호출 가능하려면 (Elisp에서 어떤 표현식이든 평가할 수 있다는 점은 제쳐두고),  
해당 함수는 ‘대화형’ 이라야 합니다.  

여기서 ‘대화형’ 이란 Emacs 용어로 추가 속성을 지닌 함수를 의미하며
확장 명령어 실행 인터페이스(~M-x~)와 키 바인딩으로 사용할 수 있습니다.  

따라서, 패키지 작성자는 특정 함수가 ~M-x~ 인터페이스로 사용자에게 접근 가능하도록 처리할지 여부를 선택합니다.  
함수를 대화형으로 표시하면 사용자가 사용할 수 있습니다.  

다시말해 대화형이 아니면 ~M-x~ 로 실행할 수도 없고 특정 키에 바인딩할 수도 없습니다!
#+END_QUOTE


*** M-S-x : Execute Extended Command for Buffer
~M-x~ 를 호출하면 Emacs에서 실행할 수 있는 모든 사용 가능한 명령이 표시됩니다. 찾는 것이 정확히 무엇인지 안다면 문제없지만 그렇지 않으면 다소 불편할 수 있습니다. 이는 Emacs의 ‘발견 가능성(discoverability)’ 개념과 관련된 문제입니다. 즉, Emacs의 ‘발견 가능성(discoverability)’ 개념과 연결된 문제입니다. 정확히 무엇을 찾는지 몰라도 원하는 것을 찾아내는데 필요한 과정에 관한 것입니다.

Emacs 28은 ~M-S-x~ 명령어를 추가했는데 이 명령어는 실행 가능한 명령어를 현재 버퍼와 관련된 선별된 목록으로 제한합니다.

이 명령은 키 바인딩이 지정된 명령 목록이나 모드 작성자가 수동으로 선택한 명령 목록에서 가져오고 또한, 비교적 최근에 추가한 기능인만큼 내용이 다소 부족할 수 있습니다. 그럼에도 불구하고 이 기능을 기억해 두고 Emacs를 탐색하는 도구 상자의 또 다른 필수 도구로 활용하시길 권장합니다.

#+BEGIN_QUOTE
[!NOTE]
*Dealing with Shift*:  
~M-S-x~ 에서 ‘S’ 가 들어간 것을 눈치챘을지 모릅니다.  
또 다른 표기법은 ~M-X~ 로 ‘X’ 를 대문자로 쓰는 방식인데 이는 ~Shift~ 키를 누를 때 ‘x’ 가 ‘X’ 로 바뀌기 때문입니다.

저는 전자가 좀 더 읽기 편하다고 생각하지만 둘 다 유효한 표기법입니다.
#+END_QUOTE


**** Universal Arguments
일부 명령어는 대체 상태가 존재하며 이에 접근하려면 범용 인자(prefix argument 라고 함)를 지정해야 합니다. 범용 인자는 ~C-u~ 키로 알려져 있습니다. 다른 단축키(참고로 ~M-x~ 도 포함됨) 앞에 붙이면(접두사) 해당 명령어의 기능을 수정하도록 Emacs에 지시합니다. 그 다음 일어날 일은 호출 명령에 따라 달라집니다. 일부 명령은 범용 인자가 0개, 1개 혹은 그 이상일 수 있습니다. 만약 명령에 N개의 상태가 있다면 ~C-u~ 를 N번 입력합니다.

사실 범용 인자는 ~숫자 4~ 를 의미하는 약어입니다. 따라서, ~C-u a~ 를 입력하면 화면에 aaaa (4번)를 출력합니다. ~C-u C-u a~ 를 입력하면 16개의 문자를 표시합니다(4×4=16 입니다). 범용 인자 자체로는 전혀 작동하지 않는다는 점을 명심합니다. 이를 입력하면 Emacs는 접두사 키와 마찬가지로 후속 명령을 입력할 때까지 기다린 다음 추가로 입력한 다음에서야 범용 인자를 적용합니다.

Emacs의 범용 인자가 단순한 숫자에 불과하다는 사실은 유용한데 이는 특정 명령에 임의의 숫자를 전달할 수 있기 때문입니다. 많은 Emacs 고수들은 10글자를 출력하기 위해 ~C-u 10 a~ 를 입력하는 훨씬 더 쉬운 방법을 사용합니다.

#+BEGIN_QUOTE
[!NOTE]
키를 누를 때—예를 들어, 키보드의 버튼을 누를 때—Emacs는 이를 화면에 어떻게 표시할까요?

사실 ~self-insert-command~ 라는 특별한 명령어가 있는데 이 명령어를 호출하면 마지막으로 입력한 키를 삽입합니다.
이 명령어로 키와 명령어 사이엔 대칭성이 생깁니다.

즉, 일반 키보드 문자도 Emacs의 다른 명령어와 동일한 방식으로 동작하게 만듭니다.

그리고 이는 키보드 문자 즉 ~self-insert-command~ 역시 다른 명령과 동일한 규칙을 따른다는 것을 의미합니다.

이들은 바인딩 해제하거나 재바인딩해서 사용자가 원하는대로 수정할 수 있습니다.
#+END_QUOTE

~C-0~ 부터 ~C-9~ 키 바인딩엔 숫자 인수가 할당되어 있습니다. 하지만, 개인적으로 ‘타이핑 템포’ 라고 부르는 것을 유지하기 위해 이 키들뿐만 아니라 좀 더 많은 키에 할당되어 있습니다. 템포에 대해서는 아래에 좀 더 자세히 설명하겠습니다.

다음은 명령어에 숫자 인수를 전달할 수 있는 다양한 방법들입니다.

| 키 바인딩       | 노트            |
|-----------------+-----------------|
| ~C-u~           | 숫자 인수 4     |
| ~C-u C-u~       | 숫자 인수 16    |
| ~C-u C-u …~    | 숫자 인수 4^n   |
| ~M-0 ~ M-9~     | 숫자 인수 0 ~ 9 |
| ~C-0 ~ C-9~     | 숫자 인수 0 ~ 9 |
| ~C-M-0 ~ C-M-9~ | 숫자 인수 0 ~ 9 |
| ~C--~           | 음수 인수       |
| ~M--~           | 음수 인수       |
| ~C-M--~         | 음수 인수       |

#+BEGIN_QUOTE
[!NOTE]
*참고*:  
부호(음수)는 위의 표에선 제대로 드러나지 않지만 마이너스 키(-)에 할당되어 있습니다.

~C-~ 대신 ~C--~ 로 표기하는데 후자는 Emacs에서 유효하지 않은 키 조합이기 때문입니다.

~C-~ 를 누른 후 손을 떼고 - 를 누를 수 없습니다.  누르면 화면에 단순히 ~-~ 가 출력될 뿐입니다.

마이너스 기호(-) 자체가 여러 수정 키와 결합되어 있습니다. 공백의 위치가 중요합니다.
#+END_QUOTE

앞서 템포의 중요성에 대해 언급했습니다. 일단 Emacs에 익숙해지면 화면을 순식간에 넘길 수 있는데 부호나 숫자 인수를 입력할 때 수정 키에서 손을 떼지 않아도 된다는 점이 이를 가능하게 해줍니다. 숫자 및 음수 인수를 ~C-, M-, C-M-~ 같은 세 가지 수정키에 바인딩하면 의도한 명령을 입력하기 전에 수정 키에서 손가락을 떼지 않아도 된다는 것이 보장됩니다.

제가 무슨 말을 하는지 몇 가지 예를 들어보겠습니다.

- ~M-- M-d~ : 커서 위치 앞 단어를 삭제합니다. ~M--~ 가 없다면 ~M-d~ 는 커서 뒤의 단어를 삭제합니다. 메타 키(~Alt~)를 누른채로 ~- d~ 를 누를 수 있으므로 이 명령은 부정 인자와 상호 보완적인 효과를 냅니다. 이 조합은 작업 속도를 유지합니다.

- ~C-- M-d~ : 정확히 동일한 기능을 수행하지만 입력에 대략 3배의 시간이 소요됩니다. ~C--~ 를 누른 후 컨트롤 키를 뗀 다음 ~M-~ 를 누르고 d 를 눌러야 합니다. 이 조합은 타이핑 속도를 떨어뜨립니다.

많은 사람들이 작업 흐름에 음수 인수를 활용하는 데 별 관심을 두지않지만 저는 이것이 유용하다고 생각합니다. 방금 입력한 단어의 대소문자를 바꾸는 것 같은 작업은 명령어의 방향을 반대로 바꾸는 음수 인수로 쉽게 수행할 수 있습니다.

#+BEGIN_QUOTE
[!NOTE]
*템포를 유지하세요*:  
그리고 손가락을 기본 행(home row)에서 움직이지 않도록 만듭니다.
부정(음수) 접두사는 명령어에 방향성을 부여하고 숫자는 반복을 추가해서 명령의 작동 방식을 변경합니다.
#+END_QUOTE


*** Discovering and Remembering Keys
특정 기능에 대한 정확한 명령어를 기억하지 못하면 Emacs가 도움줄 수 있습니다. 예를 들어, 단락 기호 ¶ 를 표시하는 방법을 기억하진 못하지만 ~C-x 8~ 키 매핑 어딘가 있다는 것만 기억한다면 접두사 키 뒤에 ~C-h~ 를 입력하면 해당 키 매핑에 속한 모든 바인딩 목록을 확인할 수 있습니다.

따라서, ~C-x 8 C-h~ 를 입력하면 키와 해당 명령어 목록이 동적으로 생성되어 표시됩니다. 이 인터페이스는 하이퍼링크로 연결되며 Emacs의 자체 문서화 도움말 시스템의 일부입니다.

| 키        | 바인딩         |
|-----------+----------------|
| ~C-x 8 "~ | Prefix Command |
| ~C-x 8 <~ | «              |
| ~C-x 8 >~ | »              |
| ~C-x 8 ?~ | ¿              |
| ~C-x 8 C~ | ©              |
| ~C-x 8 L~ | £              |
| ~C-x 8 P~ | ¶              |
| ~C-x 8 R~ | ®              |
| ~C-x 8 S~ | §              |
| ~C-x 8 Y~ | ¥              |

위는 ~C-x 8~ 에 대한 도움말 페이지를 요청했을 때 보이는 도움말의 일부입니다. Binding 열에 단일 문자가 표시되면 해당 키를 입력하면 그 문자가 출력된다는 의미입니다. 하지만, 더 많은 하위 레벨을 가진 접두사 키가 있는 경우 Emacs는 이를 알려줍니다. 이 경우 ~C-x 8 "~ 는 추가 키가 바인딩되어 있습니다.

Emacs의 먼지 쌓인 깊은 곳에 숨겨진 키보드의 모든 사용 가능한 조합에 무작위로 바인딩된 이런 키는 특히 Vim 같은 모달 에디터 사용자에겐 낯설게 느껴질 수 있습니다.

1980년대 초에 사용되던 특정 키보드의 유산은 Super, Hyper, Meta 라는 이름에서 분명히 드러납니다. 그 당시 대부분의 Emacs 키는 물리 키보드의 좀 더 넓은 범위의 수정 키에 할당됐지만 키보드 제조사(그리고 그 키보드가 연결되던 컴퓨터를 만드는 회사)가 파산하자 Emacs도 시대에 맞춰 변화해야 했습니다. Emacs의 근간을 무너뜨리는 대신 개발자들은 키 배치를 재구성해서 평범하고 지루한 PC 키보드에서 작동하도록 만들었습니다.

아마 여러분은 모든 키를 외우는 것이 벅찬 일이라 생각할 수 있습니다. 하지만, 굳이 그럴 필요는 없습니다. 주로 사용하는 키 몇개만 외우고(인간의 뇌가 그러하듯이) 나머지는 Emacs가 대신 기억하도록 맡깁니다.

#+BEGIN_QUOTE
[!NOTE]
*Use Emacs’s help system*:  
특정 키 조합을 잊어버렸을 경우 언제든지 접두사 키 뒤에 ~C-h~ 를 붙일 수 있습니다!!
#+END_QUOTE



** Configuring Emacs
이맥스(Emacs)를 만지작거리는 것은 모든 이맥스 해커들이 가장 좋아하는 취미입니다. 이맥스 모임에 나가거나 경험 많은 이맥스 해커들과 이야기를 나누다 보면 대화는 어김없이 그들의 삶을 보다 편하게 만들기 위해 적용한 사소한 변경 사항이나 해킹 기법으로 흘러갑니다.

편집기 동작 중 마음에 들지 않는 부분이 있다면 간단히 바꿀 수 있다는 사실은 즐겁고 보람찬 일입니다. 사실, Emacs를 변경하는 주제는 책 한 권을 쓸 수 있을 정도입니다. 이 책 전반에 걸쳐 저는 변경할만한 사항을 제안합니다. 가능한 경우 일반적인 변경 방식인 Elisp 스니펫 대신 Customize 인터페이스를 사용합니다.

Emacs를 변경하려면 두 가지 선택지가 있습니다:

*Use the Customize interface*: 이 기능은 기본 내장이고 사용자 친화적으로 설계됐습니다. 그렇게 말하지만 사람들은 이 기능을 번거롭고 사용하기 어렵다고 느낍니다. 저는 그게 불공평하다고 생각합니다: 이 기능은 사실 매우 실용적이며 상당히 복잡한 기능까지 설정하는 수많은 임의적인 방식도 지원하기 때문입니다.

하지만, 모든 기능이 Customize 인터페이스에서 지원되는 것은 아닙니다. 변수를 변경하려면 Elisp으로 작성하고 LISP 언어가 사용하는 ‘데이터는 코드’ 패러다임 때문에 Customize는 작성 방법을 배운 Elisp만 작성할 수 있으며 그것도 특정 옵션만 사용 가능합니다. 이로인해 Emacs의 수많은 설정 전반에 걸쳐 인터페이스를 일반화하는 것은 사실상 불가능합니다. 하지만, 대부분의 Emacs 패키지는 Customize 인터페이스를 지원하며 많은 타사 패키지도 마찬가지입니다.

Elisp 작성에 익숙해질 때까지는 가능한 한 Customize 인터페이스를 사용할 것을 *강력히* 권장합니다.

*Write elisp*: 사용자 정의하려는 항목을 직접 수정합니다. 가장 강력한 방법인 동시에 가장 복잡합니다. 이를 위해 Lisp 언어를 배워야 합니다(그리 어렵진 않으며 코딩 과정 자체가 꽤 재미있습니다). 하지만, 장기적으로 봤을 때 그만한 가치가 충분합니다.

저도 글꼴을 변경할 때는 여전히 Customize 인터페이스를 사용합니다. Emacs는 수백 가지의 글꼴이 포함되어 있습니다. Font lock (구문 강조)부터 모드라인의 글꼴과 색상, info 매뉴얼에 사용할 글꼴 등 모든 것이 포함되어 있습니다.


*** The Customize Interface
Customize 인터페이스는 그룹과 하위 그룹으로 나뉩니다. 각 그룹은 일반적으로 하나의 패키지, 메이저 모드 또는 기능을 대표합니다. 최상위 그룹은 ~Emacs~ 로 예상대로 다른 모든 그룹을 포함합니다.

Customize 인터페이스에 접근하려면 ~M-x customize~ 를 입력합니다. =*Customize Group: Emacs*= 버퍼가 나타나며 그룹 목록이 표시됩니다. 이 부분은 마우스를 사용할 수 있는 Emacs 기능 중 하나입니다.

이 인터페이스는 웹브라우저와 유사한 버튼, 하이퍼링크, 편집 상자가 포함됩니다. 여기저기 클릭하면서 인터페이스를 탐색하고 설정할 수 있는 항목이 얼마나 많은지 알아보시기 바랍니다! 그리고 이것은 단지 커스터마이즈 인터페이스에 노출된 일부 항목일 뿐입니다.

#+BEGIN_QUOTE
[!NOTE]
*Searching in Customize*:  
상단의 검색 창으로 사용자 지정 가능한 옵션을 빠르게 검색할 수 있습니다.
#+END_QUOTE

그림

‘Customize’ 인터페이스는 다소 복잡해 보이지만 작동 원리만 이해하면 사용하기 쉽습니다. 위의 그림은 ‘font-lock-string-face’ 글꼴 설정을 보여줍니다. 이는 해당 글꼴의 실제 elisp 변수명이며 예쁘게 표기된 이름은 ‘Font Lock String Face’ 이고 위의 그림에서 보이는 바로 그 글꼴입니다. 왼쪽에는 화살표가 있습니다. 아주 작지만 이 화살표를 클릭하면 페이스를 숨기거나 표시할 수 있습니다. 터미널 모드에선 이 화살표가 ‘숨기기’ 또는 '표시' 라는 좀 더 읽기 쉬운 텍스트 형태로 대체됩니다.

사용자 정의 인터페이스는 두 가지 요소 즉, '페이스' 와 '옵션' 으로 구성됩니다. '옵션' 은 페이스가 아닌 사용자가 정의할 수 있는 모든 항목을 포괄하는 용어입니다.

=font-lock-string-face= 는 문자열에 적용할 서체(글꼴)를 결정합니다. 문자열의 정의는 문자열이 사용되는 메이저 모드에 따라 달라집니다. 대부분의 프로그래밍 모드는 소스 코드의 리터럴 문자열에 적용되지만 모드 작성자가 원하는대로 서체를 자유롭게 설정할 수 있습니다. 그렇지만 대부분 서체에 대한 명명 규칙을 따릅니다.

그림

제가 주로 사용하는 전경색은 =OrangeRed= 입니다. 하지만, 위의 그림에서 볼 수 있듯이 추가 속성을 더하는 데는 아무런 제약이 없습니다.

#+BEGIN_QUOTE
[!NOTE]
*Supported colors*:  
GUI 환경에서 Emacs를 사용할 경우 디스플레이 색상 심도에 제한받으며 RGB 색상 공간의 색상을 선택할 수 있습니다.  

저는 이름이 지정된 색상을 주로 사용하는데 지원되는 색상 이름의 목록을 보려면 ~M-x list-colors-display~ 를 입력합니다.  

터미널 모드를 사용할 경우 해당 터미널에서 지원하는 색상이 표시됩니다.

터미널 모드는 16색이나 256색 외에도 24비트 색상도 지원됩니다.  
색상이 제대로 표시되지 않으면 터미널 설정 방법에 대한 Info 매뉴얼 FAQ를 읽어보시기 바랍니다:

~M-x info-apropos~ 를 입력한 후 TTY Colors 를 입력합니다.  
잠시 후 터미널 설정을 구성하는 방법을 설명하는 FAQ로 연결되는 하이퍼링크가 표시됩니다.

Emacs 28은 환경 변수 =COLORTERM=truecolor= 를 설정하면 터미널과 관계없이 Emacs가 필요한 조치를 자동으로 취합니다.  
24비트 색상 표시가 제대로 되지 않으면 이 환경 변수를 설정하시기 바랍니다.
#+END_QUOTE

‘사용자 정의 UI’ 로 설정을 변경하는 것으로 충분치 않습니다!! 변경 사항을 실제로 적용해야 하며 필요에 따라 저장해야 합니다. 저장하지 않으면 변경 사항은 Emacs 세션 간에 유지되지 않습니다. 적절한 이름의 ‘적용(Apply)’ 및 ‘적용 및 저장(Apply and Save)’ 버튼을 누르면 이 작업을 수행합니다. ‘되돌리기(Revert)…’ 버튼도 비슷하지만 몇 가지 추가 옵션이 있습니다. 적용한 변경 사항이 마음에 들지않을 때만 '이 세션의 사용자 지정 되돌리기(Revert This Session’s Customizations)' 를 사용합니다. 이 기능은 현재 버퍼에 대한 옵션만 되돌릴 뿐 전역 적용된 모든 사용자 지정 옵션은 되돌리지 않는다는 점을 명심합니다.

저장하기 전까진 언제든지 변경 사항을 되돌릴 수 있다는 점을 기억합니다. 저장 후에는 수동으로 하나씩 되돌리거나 ‘되돌리기…’ 버튼의 ‘사용자 지정 지우기’ 옵션을 사용합니다. 모든 사용자 정의 설정은 기본적으로 init 파일(또는 별도의 사용자 정의 파일)에 저장되며 다른 Emacs 기능과 마찬가지로 변경 사항은 elisp 코드로 저장되므로 elisp 코드를 수정해서 되돌릴 수 있습니다.

그룹 트리를 탐색하는 다음과 같은 명령 중 하나를 사용할 수 있습니다:

- ~M-x customize~ ::  Customize 인터페이스와 모든 그룹을 표시합니다.
- ~M-x customize-option~ :: 사용자 정의 가능한 옵션을 입력하도록 요청하고 해당 옵션이 선택된 상태로 Customize UI를 엽니다.
- ~M-x customize-browse~ ::  트리 그룹 브라우저를 엽니다. 일반적인 Customize 인터페이스와 유사하지만 설명을 표시하지 않습니다.
- ~M-x customize-customized~ ::  변경했지만 저장하지 않은 옵션과 페이스를 사용자 정의합니다. 저장하지 않은 옵션이 있는지 기억나지 않을 때 유용합니다.
- ~M-x customize-changed~ :: 특정 Emacs 버전 이후 변경된 모든 옵션을 표시합니다. 새로운 기능과 옵션을 발견할 수 있는 좋은 방법입니다.
- ~M-x customize-face~ ::  폰트 이름을 입력하라는 메시지를 표시합니다. 변경할 폰트에 커서를 위치시킬 것을 권장합니다. 그러면 이름을 자동으로 채웁니다.
- ~M-x customize-group~ :: 사용자 정의할 그룹 이름(예: python)을 입력하라는 메시지가 표시됩니다.
- ~M-x customize-mode~ :: 현재 버퍼의 메이저 모드를 사용자 정의합니다. 모든 메이저 모드에 이 작업을 수행하는 것이 좋습니다. 설정을 빠르게 변경하고 메이저 모드의 기능을 파악할 수 있는 방법입니다.
- ~M-x customize-saved~ :: 저장된 모든 옵션과 페이스를 표시합니다. 잘못된 변경 사항을 찾아내서 비활성화할 경우 유용합니다.
- ~M-x customize-themes~ :: 전환할 수 있는 현재 설치된 테마 목록을 표시합니다.

Emacs를 설정할 때는 ‘Customize’ 인터페이스로 사용하시길 강력히 권장합니다!! 이 인터페이스는 변경할 수 있거나 변경하려는 항목 중 일부만 포함되지만 Emacs를 나만의 환경으로 꾸미는 첫걸음을 내딛기에는 충분합니다.

Emacs를 사용하면서 계속 개인화하면 결국 init 파일로는 관리하기 어려워지는 시점이 옵니다. 그럴 때는 변경 사항을 관련성 있는 그룹으로 나누는 것이 일반적입니다. 하지만, 이는 여러분이 Emacs에 익숙해진 후의(그리고 init 파일이 터질듯이 부풀어 오를 때까지는) 우선순위가 매우 낮은 작업에 속합니다.


*** Evaluating Elisp Code
인터넷에서 엘리스프(Elisp) 코드 조각을 발견하거나 작성하는데 이를 실행할 때가 있습니다. 매번 Emacs를 닫았다가 다시 시작한다는 것은 번거로운 일입니다. 이를 수행할 방법은 여러 가지로 저는 그 중에 몇 가지만 소개합니다. 이 주제를 자세히 알아보시려면 『Emacs에서 엘리스프 실행하기(Evaluating Elisp in Emacs 12)』 를 읽어보시기 바랍니다.

- ~Restarting Emacs~ :: 가장 간단한 방법으로 Emacs에 문제가 발생했거나 새로운 환경에서 제대로 작동하는지 확인할 때는 이 방법을 권장합니다.
- ~M-x eval-buffer~ :: 현재 버퍼 전체를 평가합니다. 저는 무언가 평가할 때 주로 이 명령을 사용합니다.
- ~M-x eval-region~ :: 사용자가 지정한 선택 영역만 평가합니다.

물론 이건 빙산의 일각에 불과합니다. 여러분이 보게될 코드 중에서 직접 실행할 부분을 다룰 때는 이 정도면 충분합니다.

ZZZZZ


*** The Package Manager
Emacs는 중앙 집중식 저장소에서 패키지를 표시하거나 설치할 수 있는 패키지 관리자가 포함되어 있습니다. 사용 가능한 패키지 저장소는 여러 곳이며 Emacs는 기본적으로 공식 GNU 저장소를 읽도록 설정됩니다. 하지만, 자원봉사자들이 운영하는 패키지 저장소인 =MELPA= 도 추가하는 것이 좋습니다. 패키지 관리자는 모든 목록을 하나로 통합해서 표시합니다. 저장소는 자원봉사자들이 개인적으로 운영하기 때문에 일시적이나 영구적으로 중단될 수 있으므로 Emacs Wiki에서 최신 저장소 목록을 확인하는 것이 좋습니다.

~M-x package-list-packages~ 를 입력하면 Emacs가 설정된 저장소에서 패키지 목록을 가져옵니다. 작업이 완료되면 모든 패키지가 나열된 새로운 버퍼가 표시됩니다. Emacs의 많은 보조 버퍼와 마찬가지로 이 버퍼도 하이퍼링크가 포함됩니다. 한 번 둘러보시기 바랍니다. 관심있는 패키지의 상세 페이지에서 클릭만으로 패키지를 설치할 수 있습니다.

#+BEGIN_QUOTE
*힌트*:  
패키지 이름을 안다면 ~M-x package-install~ 를 사용하고 미니버퍼에 이름을 입력합니다.  
그리고 대부분의 미니버퍼 프롬프트와 마찬가지로 ~TAB~ 자동 완성 기능을 지원합니다.

패키지 아카이브는 끊임없이 변경되며 특히 Emacs를 장시간 실행하면 로컬 사본이 오래된 상태가 됩니다.

이 문제를 해결하려면 ~M-x package-refresh-contents~ 를 입력해서 카탈로그를 새로고칠 수 있습니다. 
#+END_QUOTE


*** Custom Color Themes
Emacs의 기본 색상 구성에 만족하지 못한다면 좋은 소식이 있습니다. 사용자 지정 테마를 사용할 수 있습니다. ~M-x customize-themes~ 를 입력하면 현재 설치된 테마 목록을 확인할 수 있습니다. Emacs의 패키지 관리자나 GitHub 같은 곳에서 좀 더 많은 테마를 구할 수 있습니다.

패키지 관리자를 통해 테마를 설치하려면 패키지 관리자(~M-x package-list-packages~)를 열고 테마를 찾습니다. 대부분은 ~-theme~ 접미사가 붙어있으며 일반 패키지와 마찬가지로 작동하고 설치됩니다. 필요한 테마를 설치한 후에는 ~M-x customize-themes~ 인터페이스를 사용해서 직접 설정할 수 있습니다. 'Customize 인터페이스' 에 설명된 일반 Customize 인터페이스를 사용해서 마음에 들지않는 특정 색상을 재정의할 수 있습니다. Customize 인터페이스로 변경한 내용은 테마보다 우선 적용됩니다.

또한 여러 테마를 동시에 활성화할 수 있다는 점도 알아두시기 바랍니다.


** Getting Help
앞서 키에 대해 이야기할 때 언급했듯이 Emacs는 매우 정교한 자가 문서화 기능을 갖춘 편집기입니다. Emacs의 모든 측면을 검색하거나 설명할 수 있습니다. 이를 활용하는 방법을 배우는 것은 Emacs를 숙달에 있어 절대적으로 필수적입니다. 어떤 질문에 대한 답을 찾는 방법을 안다는 것의 유용성은 아무리 강조해도 지나치지 않습니다. 저는 기억을 되살리거나 모르는 질문에 대한 답을 찾기 위해 Emacs의 자체 문서화 기능을 항상 활용합니다.

#+BEGIN_QUOTE
*Terminology*:  
제가 Emacs의 문서 시스템을 설명할 때 ‘symbol’ 이란 단어를 자주 사용할 것입니다.  
이 단어는 Emacs의 특정 부분에만 독점적으로 쓰는 것은 아니지만  
변수, 함수, 글꼴(face)이든 아니면 그 외의 다른 것이든 간에  
합리적으로 찾아볼 수 있는 모든 것을 포괄적으로 표현하기 때문입니다.
#+END_QUOTE

아직까지 Emacs의 핵심 기능들(이동, 편집 등)에 대해선 언급하지 않았습니다. 물론 이런 기능들은 Emacs를 숙달에 있어 분명 중요하지만 인내심을 가지고 Emacs의 자동 설명형 도움말 시스템을 활용한다면 쉽게 습득할 수 있는 매우 구체적인 기술들이기 때문입니다.

도움말을 찾는 방법을 안다는 것은 다음과 같은 이유로 중요합니다:

*Emacs가 가장 잘 압니다* : 여러분의 Emacs 설정은 –때로는 아주 조금 때로는 상당히 많이– 다른 사람의 Emacs 설정과 다를 수 있습니다. 인터넷에 질문하더라도 일반적인 답변만 얻을 수 있을 뿐입니다. 키를 재할당하면 어떤 키가 어떤 기능을 가지는지 아는 건 오직 여러분의 Emacs 뿐입니다.

*Emacs의 많은 기능을 발견합니다* : 저는 단순히 탐색한 것만으로 셀 수 없을만큼 많은 멋진 기능을 우연히 발견했습니다. 어쩌면 메이저 모드에 숨겨진 시간 절약용 명령어나 자주 사용하는 명령의 동작을 변경하는 변수 같은 것들 말입니다. 많은 타사 패키지는 적절한 사용자 설명서가 없을 수 있으므로 소스 코드를 읽어보거나 패키지가 제공하는 명령과 변수를 직접 조사할 수도 있습니다.

*문제 해결에 도움됩니다* : 저는 항상 다른 사람들의 Emacs와 관련된 질문을 도와주지만 모든 것을 다 아는 것은 아닙니다. 제가 아는 건 어디서 찾아야 하고 문서를 어떻게 읽는지 뿐입니다.

*자신감을 줍니다* : Emacs에서 어떻게 해야할지 모른다는 건 당연하지만 동시에 혼란스럽습니다. 하지만, “아, 이건 어떻게 하는지는 모르지만 도움 구할 곳은 알고 있어요!” 라고 말할 수 있다면 Emacs에 대한 자신감은 지식의 깊이와 함께 커질 것입니다.

Emacs의 도움말 시스템은 크게 세 부분으로 나뉘며 어떤 부분이 언제 필요한지 안다면 시간을 절약할 수 있습니다.


*** The Info Manual
Emacs 자체의 매뉴얼(그리고 사실 GNU 생태계의 모든 매뉴얼)은 =TeXinfo= 형식으로 작성됩니다. 만약 명령줄 도구인 =info= 를 사용한 적이 있다면 이미 TeXinfo 하이퍼텍스트 뷰어를 사용한 셈입니다. 물론 Emacs도 자체적인 info 뷰어가 있습니다. Emacs의 info 매뉴얼은 Emacs와 관련된 주제뿐만 아니라 그 이상의 내용도 포함됩니다. 기본적으로 info 브라우저는 시스템에 설치된 다른 모든 info 매뉴얼을 색인화합니다. 예를 들어, =GNU coreutils= 매뉴얼 같은 것도 여기에 포함됩니다.

많은 사람들이 info를 싫어하는데 사실 저는 이유를 잘 모르겠습니다. 키 바인딩은 다르지만 작동 방식은 웹 브라우저와 거의 비슷합니다.

Emacs의 info 리더를 실행하려면 ~M-x info~ 를 입력하거나 ~C-h i~ 를 누릅니다. 문서 브라우저인 info 가 나타나면 마우스로 하이퍼링크를 클릭하거나 다음과 같은 키보드 단축키를 이용해서 탐색할 수 있습니다:

| 키     | 용도                                                        |   |   |
|--------+-------------------------------------------------------------+---+---|
| [ 및 ] | 이전/다음 노드로 이동합니다                                 |   |   |
| l 및 r | 기록 내에서 뒤로/앞으로 이동합니다                          |   |   |
| n 및 p | 이전/다음 형제 노드로 이동합니다                            |   |   |
| u      | 한 단계 위로 이동해서 상위 노드로 이동합니다                |   |   |
| SPC    | 한 화면씩 스크롤합니다                                      |   |   |
| TAB    | 상호 참조 및 링크를 순환합니다                              |   |   |
| RET    | 활성 링크를 엽니다                                          |   |   |
| m      | 메뉴 이름을 입력하라는 메시지를 표시하고 해당 메뉴를 엽니다 |   |   |
| q      | 정보 브라우저를 닫습니다                                    |   |   |

info 매뉴얼은 이 책이나 다른 책과 마찬가지로 계층적 구조로 info 매뉴얼을 처음부터 끝까지 읽을 때는 [ 와 ] 를 사용해서 이동하는 것이 가장 좋습니다. 이는 책을 특정 장부터 시작해서 구성된 순서대로 모든 소장, 소소장 등을 차례대로 읽는 것과 같습니다.

#+BEGIN_QUOTE
*Everyday reading*:  
평소엔 ~SPC~ 를 사용하면 좋습니다. 이 기능은 “사용자가 원하는대로” 작동하며 페이지 끝까지 넘겨줍니다.

그런 다음 다음 하위 노드나 다음 장으로 이동합니다.  
브라우징할 때는 ~[~ 와 ~]~ 키를 사용해서 노드 사이를 앞뒤로 이동할 수 있습니다.
#+END_QUOTE

반대로 바로 옆의 다음 또는 이전 노드로 이동하려면 ~n~ 과 ~p~ 를 사용합니다. 기록(브라우저와 비슷하게) 내에서 뒤로 가거나 앞으로 가려면 ~l~ 과 ~r~ 을 사용합니다. ~u~ 키를 누르면 한 단계 위의 부모 노드로 이동하고 ~TAB~ 키를 누르면 하이퍼링크를 순차적으로 이동하며 ~RET~ 키로 링크를 엽니다.

대부분의 info 매뉴얼은 온라인에 HTML 버전으로 제공되므로 왜 Emacs 자체의 리더를 사용할까요? 첫째로 Emacs의 범용 북마크 시스템을 사용할 수 있기 때문입니다(이에 대해서는 나중에 자세히 설명!하!겠습니다). Emacs는 info 페이지, 파일, 디렉터리 등 거의 모든 것에 북마크를 설정할 수 있습니다. 또 다른 장점은 Emacs 세션에 있으므로 Emacs의 훌륭한 『An Introduction to Programming in Emacs Lisp』 을 읽으면서 그와 병행해서 코드를 작성할 때 info 매뉴얼을 분할 창으로 옆에 두는 것이 특히 유용합니다.

특정 Emacs 기능을 자세히 읽고싶다면 먼저 Emacs 매뉴얼을 열어야 합니다. 이를 위해 ~C-h i~ 를 입력한 다음 ~m~ 을 입력합니다. 메뉴 항목을 입력하라는 메시지가 나타나고 Emacs 매뉴얼을 살펴보려면 =Emacs=, elisp 입문서를 보려면 =Emacs Lisp Intro= 를 입력합니다. 언제나 그렇듯이 TAB 자동 완성 기능도 제공됩니다. 또한 매뉴얼 전체 목록을 둘러보면서 읽고 싶은 매뉴얼을 찾을 수 있습니다.

#+BEGIN_QUOTE
*Emacs 28*:  
~C-h R~ 단축키로 설명서를 열 수 있습니다.  
Emacs Lisp 입문서를 열려면 ~C-h R eintr~ 를 입력합니다.
#+END_QUOTE

~C-h F~ 를 입력한 후 프롬프트에 명령어 이름을 입력하면 해당 명령어에 대한 설명서를 찾아볼 수 있습니다. 그러면 Emacs는 해당 명령어가 설명된 인포(info) 매뉴얼의 해당 부분으로 이동합니다.


*** Apropos
Emacs는 명령줄 도구인 =apropos= 와 거의 동일한 방식으로 작동하는 =apropos= 시스템이 있습니다. 이 =apropos= 시스템은 무엇을 찾을지 정확히 모를 때 특히 유용합니다. Emacs의 자체 설명형 내부 구조 중 특정 부분만 검색할 수 있는 다양한 명령어들이 있습니다.

=apropos= 는 도구 상자에 반드시 챙겨야할 또 다른 매우 중요한 필수 도구입니다. 이 도구는 찾는 대상을 특정 영역으로 좁힐 수 있다는 점에서 특히 뛰어납니다. 만약 어떤 변수를 찾는다면 변수를 검색하는 =apropos= 시스템을 사용할 수 있고 명령어를 찾는다면 명령어별로 검색할 수 있습니다. 또한 모든 =apropos= 기능은 정규표현식을 지원합니다.

가장 일반적인 명령은 ~C-h a~ 에 바인딩된 ~M-x apropos-command~ 입니다. ~apropos-command~ 는 주어진 패턴과 일치한 모든 명령(함수가 아닌 명령만)을 표시합니다.

예를 들어, 단어(단어에 대한 정의는 'What Constitutes a Word?' 에서 자세히 다룹니다)를 다루는 명령어를 찾는다면 ~C-h a~ 를 입력한 뒤 ~- word$~ 를 입력하는 것은 좋은 시작입니다. 그러면 ~-word~ 로 끝나는 모든 명령어를 나열합니다.

해당 명령어를 실행했을 때 볼 수 있는 출력 결과의 일부는 다음과 같습니다:

| 명령          | 키         | 용도                                                                           |
|---------------+------------+--------------------------------------------------------------------------------|
| ~ispell-word~ | ~M-$~      | 커서 위치 아래 또는 앞의 단어의 맞춤법을 확인합니다.                           |
| ~kill-word~   | ~M-d~      | 단어 끝까지 지점까지 앞쪽 문자를 삭제합니다.                                   |
| ~left-word~   | ~C-<left>~ | 커서를 왼쪽으로 N 단어만큼 이동합니다.(N이 음수일 경우 오른쪽으로 이동합니다.) |
| ~mark-word~   | ~M-@~      | 커서 위치에서 ArG 단어만큼 떨어진 곳에 표시(mark)를 설정합니다.                |

보시다시피 명령어의 이름과 할당된 키(있을 경우) 그리고 용도를 확인할 수 있습니다. Emacs는 특정한 명명 규칙이 있으며 Emacs에 익숙해지면 이런 일정한 패턴이 드러나는 것을 잘 알게 됩니다. 예를 들어, 명령어 뒤에 해당 명령어가 적용될 구문 단위나 컨텍스트를 접미사로 붙이는 것은 일반적입니다. 단어일 경우 ~-word~, 창일 경우 ~-window~ 같은 방식입니다.

#+BEGIN_QUOTE
*힌트*:  
=Apropos= 는 관련성 순으로 결과를 정렬합니다. 다음과 같은 명령어를 입력합니다.

~M-x customize-option RET apropos-sort-by-scores~

~RET~ 을 눌러 설정을 변경합니다.
#+END_QUOTE

Emacs를 검색할 수 있는 다양한 =apropos= 명령어가 있습니다. 그 중에도 ~apropos-command~ 는 반드시 외워야할 가장 중요한 명령어라고 생각합니다. 이 명령어는 패턴으로 검색할 수 있기 때문에 찾고자 하는 것을 찾기 위해 명령어 이름을 전부 다 외울 필요없이 일부만 기억해도 충분합니다. 또한 이 방법은 우연히 Emacs의 새로운 기능을 발견할 때도 아주 훌륭한 방법입니다. ~apropos-command~ 에 ~.+~ 패턴(모든 것을 일치시킴)을 입력하면 Emacs가 인지한 수천 개의 명령어가 나옵니다.

Emacs는 여러분에게 좀 더 적합하다고 느낄 수 있는 다양한 전문적인 =apropos= 명령어들이 있습니다.

~M-x apropos~: 최후의 수단으로 이 명령어는 지정한 패턴과 일치한 모든 기호를 표시합니다. 특정 패턴과 관련된 변수, 명령어 및 함수 모두를 찾을 경우에 사용합니다.

~M-x apropos-command~ 또는 ~C-h a~: 앞서 설명했듯이 이 명령은 명령어만 나열합니다.

~M-x apropos-documentation~ 또는 ~C-h d~: 문서만 검색합니다. Emacs 용어로 말하면 이는 심볼에 부여할 수 있는 doc-string(documentation string)을 의미합니다. 다른 모든 방법이 실패할 때는 유용합니다.

~M-x apropos-library~: 라이브러리에 정의된 모든 변수와 함수를 나열합니다. 새로운 메이저 모드나 패키지를 조사할 때 이 명령으로 해당 라이브러리에 정의된 모든 함수와 변수를 확인할 수 있습니다.

~M-x apropos-user-option~: Customize 인터페이스로 사용 가능한 사용자 옵션을 표시합니다. 이는 Customize 옵션의 심볼 이름을 확인할 수 있는 방법이지만 Customize 인터페이스를 검색할 방법을 찾는다면 일치 조건을 직접 설정할 수 있는 Customize 인터페이스의 검색 상자를 사용하는 것이 더 좋습니다. 저는 이 기능을 결코 사용하지 않습니다.

~M-x apropos-value~: 특정 값을 가진 모든 심볼을 검색합니다. 특정 값을 저장한 변수를 찾는다면 이 명령어가 유용할 수 있습니다. 예를 들어, 변수의 값은 알지만 이름이나 정의 위치를 모를 경우 사용할 수 있습니다.

찾는 것이 무엇인지 확실치 않다면–예를 들어, 명령어 이름의 일부만 알거나 설명서의 일부 내용만 기억할 경우–‘apropos’ 가 도움될 수 있습니다. 저는 ‘apropos’ 는 없어선 안 될 *필수 도구* 라고 생각합니다. 특정 패턴과 일치한 모든 명령어를 나열하는 데 유용할 뿐만 아니라 새로운 명령어를 발견할 때도 더할나위 없이 훌륭한 방법입니다.


*** The Describe System
Emacs의 자체 문서화 특성을 가장 잘 보여주는 것은 바로 ‘describe’ 시스템입니다. 무엇을 찾을지 안다면 =describe= 시스템이 무엇인지 정확히 설명해 줍니다. Elisp로 작성된 코드든 C로 작성된 핵심 레이어든 Emacs의 모든 측면은 =describe= 시스템으로 접근하거나 검색할 수 있습니다. 키부터 명령어, 문자 집합, 인코딩 체계, 폰트, 폰트 스타일, 메이저 모드, 구문 테이블 등 모든 것이 깔끔하게 분류되어 있습니다.

=describe= 시스템은 정적이지 않습니다. Emacs의 특정 부분을 조회할 때마다 내부 반사 계층(reflection layer)을 통해 필요한 세부 정보를 동적으로 가져오는데 이 계층은 내부 데이터 구조에 쿼리를 보냅니다. 인트로스펙션 레이어와 내부 데이터 구조 모두 Elisp로 사용자가 직접 쿼리할 수 있습니다. Emacs에 “비밀” 은 없습니다!! 물론, 문서화된 API 레이어를 통해 Emacs의 내부 상태에 접근하는 것이 권장되는 접근 방식이지만 다른 에디터나 IDE와 달리 패키지 작성자나 Emacs 유지보수자에게 종속되지 않습니다. =describe= 시스템이 아름답게 구현한 이런 개방성은 Emacs의 가장 뛰어난 특징 중 하나라고 생각합니다.

가장 중요한 =describe= 키들은 ~C-h~ 접두사 키에 바인딩됩니다. 사실 좀 더 많은 키가 있지만 대부분 elisp 작성자가 아닌 일반 사용자에겐 그다지 유용하지 않습니다.

저는 =describe= 시스템을 끊임없이 사용합니다. 이 책을 집필할 동안 =info= 매뉴얼과 =apropose= 모두 폭넓게 활용했지만 제가 작성한 내용이 정확한지 다시 한 번 확인할 때는 =describe= 시스템을 사용합니다. 만약 Emacs의 어떤 심볼(함수, 명령어, 변수, 모드 등)이 어떤 역할을 처리하는지 궁금할 때면 =describe= 가 그 답을 알려줄 것입니다.

doc-string의 유일한 작은 단점은 기술적인 독자를 전제로 한다는 점인데 info 매뉴얼은 일반적으로 그렇지 않습니다. 하지만, 전혀 나쁜 것은 아닙니다. 설명을 이해하기 위해 Elisp 전문가일 필요는 없지만 doc string에 사용된 용어에 익숙하려면 약간의 시간이 걸립니다. 기억하시기 바랍니다!! =describe= 시스템은 살아있는 시스템 즉 여러분의 맞춤형 Emacs에 대해 설명합니다.

다음 네 가지 =describe= 키는 일상적인 Emacs 사용에서 중요하므로 반드시 외워야 합니다!!

~M-x describe-mode~ 또는 ~C-h m~: 해당 메이저 모드(및 함께 활성화된 모든 마이너 모드)에 대한 설명과 해당 모드에 정의된 모든 키 바인딩을 표시합니다. =describe= 명령은 현재 버퍼를 대상으로 처리합니다.

새로운 메이저 모드를 사용할 때 이 명령으로 가장 먼저 확인합니다. 이 방법으로 Emacs의 다양한 기능을 발견할 수 있으며 이 명령을 사용하는 것은 절대적으로 필수적입니다. 단, 이 명령어는 어떤 키에도 바인딩되지 않은 모드별 명령어들은 나열하지 않습니다. 하지만 해당 명령어들은 단순히 표시되지 않을 뿐입니다.

~M-x describe-command~ 또는 ~C-h x~: Emacs 28에 도입된 이 명령어는 아래의 동급 명령어와 달리 함수가 아닌 명령어만 설명합니다. 대화형 명령어를 찾는다면 저는 이 명령어를 사용할 것입니다.

~M-x describe-function~ 또는 ~C-h f~: 함수를 설명합니다. 이 명령은 Emacs를 마스터하기 위한 필수 중 하나입니다. Emacs에 특정 기능이 무엇을 처리하는지(그리고 어떻게 찾아보는지) 아는 것도 중요하지만 그 기능이 선언된 코드로 곧바로 이동할 수 있는 능력도 필수적입니다.

함수를 설명하면 elisp 함수 시그니처, 해당 함수에 바인딩된 키(있는 경우), 선언된 위치로 연결된 하이퍼링크 그리고 문서 문자열을 확인할 수 있습니다. 함수가 명령어일 경우 대화형(interactive)이라 표시됩니다. Emacs 28을 사용 중이고 명령어를 찾는다면 ~describe-command~ 를 사용할 것을 권장합니다.

~M-x describe-variable~ 또는 ~C-h v~: 변수를 설명합니다. ~describe-function~ 과 마찬가지로 이 명령도 중요하지만 초보자는 변수를 변경하는 것이 항상 쉬운 일은 아니므로 중요도가 다소 낮을 수 있습니다. 그럼에도 불구하고 변수가 어떤 역할을 처리하는지 확인할 수 있다는 점은 유용합니다.

~M-x describe-key~ 또는 ~C-h k~: 키 바인딩이 어떤 역할을 처리하는지 설명합니다. 모든 명령 중에서 이 명령은 기억할 가치가 가장 높으며 ~M-x describe-function~ 과 마찬가지로 자주 사용할 필수 명령입니다. 키 바인딩의 기능을 확실히 모른다면 ~describe-key~ 인터페이스로 해당 키를 입력하면 Emacs가 그 기능을 정확히 알려줍니다.

일부 키는 메이저 모드나 마이너 모드에서 비롯된 것이며 전역 키가 아니란 점도 기억하는 것이 좋습니다. 따라서, 명령을 입력한 버퍼에 따라 다른 결과가 나올 수 있습니다.

Emacs 28은 모든 =describe= 버퍼에 유용한 몇가지 단축키를 추가했습니다. ~i~ 키를 제외한 모든 단축키는 버퍼 내의 하이퍼링크로 사용할 수 있지만 이런 단축키를 알아두면 도움됩니다.

| 키 바인딩 | 용도                        |
| i         | 정보 설명서 열기            |
| s         | 소스 정의로 이동            |
| c         | 사용자 지정 인터페이스 열기 |

Emacs는 훨씬 더 많은 =describe= 명령어가 있지만 일상적인 사용에는 실용적이지 않습니다. =describe= 명령어의 명명 규칙과 패턴을 이용해서 명령어를 찾는 방법을 안다면 이 모든 명령어를 나열하는 것은 아주 쉬운 일입니다.
