** Transposing Text
텍스트 전치란 두 개의 구문 단위를 서로 위치를 바꾸는 행위입니다. 언뜻 보기엔 유용성이 제한적이라 생각할 수 있지만 사실 이는 실질적인 문제를 해결하며 이를 숙달하면 결코 후회하지 않습니다. 산문에서 단어의 순서를 바꾸거나 함수의 인수를 바꾸는 일은 흔히 발생하는 일입니다.

텍스트를 전치할 때는 텍스트를 이동하거나 삭제할 때와 동일한 방식으로 구문 단위를 사용해서 수행합니다:

| 키 바인딩                  | 용도                 |
|----------------------------+----------------------|
| ~C-t~                      | 문자 순서 바꾸기     |
| ~M-t~                      | 단어 순서 바꾸기     |
| ~C-M-t~                    | S-표현식 순서 바꾸기 |
| ~C-x C-t~                  | 줄 순서 바꾸기       |
| ~M-x transpose-paragraphs~ | 단락 순서 바꾸기     |
| ~M-x transpose-sentences~  | 문장 순서 바꾸기     |

전치(transpose) 명령을 호출하면 Emacs는 먼저 포인터의 위치를 확인한 후 사용자가 입력한 전치 명령에 따라 포인터를 둘러싼 두 개의 구문 단위를 서로 교환합니다. 이 경우 Emacs가 구문 단위를 정의하는 방식은 다소 복잡한데 이는 구문 단위의 정의가 현재 사용 중인 메이저 모드에 따라 결정되기 때문입니다.

음수 인자도 작동하며 숫자 인자도 작동하지만 예상하는 방식과 다릅니다. 전치 명령에 숫자 인자를 지정하면 포인트 앞쪽의 N번째 단위를 가져와(음수 인자도 함께 지정하지 않는 한 반대 순서가 됩니다) 해당 단위를 포인트 바로 앞의 구문 단위와 서로 교환합니다.


*** C-t : Transpose Characters
문자를 전치하면 커서 위치의 좌우 문자를 서로 바꿉니다:

~A█BC~

~C-t~ 를 누른 후:

~BA█C~

포인터가 한 칸 앞으로 이동하므로 ~C-t~ 를 반복해서 문자를 오른쪽으로 “끌어올” 수 있습니다:

~BCA█~

이 규칙의 중요한 예외 중 하나는 줄 끝에서 작업할 때입니다. 이때 ~C-t~ 는 포인터 왼쪽의 두 문자를 서로 바꿉니다:

~BCA█~

~C-t~ 입력 후:

~BAC█~

이런 비대칭성은 오타가 발생했을 때 이를 수정하기 유용한 방법입니다. ~C-t~ 를 사용해서 잘못 입력된 문자를 수정하면 두 문자 모두 삭제한 후 다시 입력하는 수고를 덜어주므로 시간을 절약할 수 있습니다.


*** M-t : Transpose Words
~M-t~ 키를 사용해서 두 단어를 뒤바꾸는 기능은 다음과 같이 단순한 텍스트일 경우는 예상대로 작동합니다:

~Hello █World~

~M-t~ 실행 후:

~World Hello█~

~C-t~ 로 문자를 뒤바꾸는 것과 마찬가지로 커서는 ~M-f~ (~M-x forward-word~)를 입력한 것처럼 앞으로 이동하며 이는 단어를 오른쪽으로 “끌어당길” 수 있음을 의미합니다. ~M-t~ 가 진가를 발휘하는 곳은 소스 코드에서 사용할 때입니다. “단어의 정의란 무엇인가?” 섹션에서 설명했듯이 ~M-f~ 와 ~M-b~ 이동 명령은 이동 방향의 기호를 무시하며 ~M-t~ 도 이와 동일한 방식으로 동작합니다.

다음과 같은 Python 코드 예제로 살펴보겠습니다. 다음과 같은 딕셔너리(키-값 해시 맵)가 있습니다:

#+BEGIN_SRC 
names = {
  ‘Jerry’:█ ‘Seinfeld’,
  ‘Cosmo’: ‘Kramer’,
}
#+END_SRC

커서가 키와 값 사이에 있을 때 ~M-t~ 를 호출하면 마법같은 일이 일어납니다:

#+BEGIN_SRC
names = {
  ‘Seinfeld’: ‘Jerry’,
  ‘Cosmo’: ‘Kramer’,
}
#+END_SRC

보시다시피 키와 값의 위치가 바뀌지만 심볼은 제자리에 남습니다. 이 작업을 다시 반복하면 Emacs는 계속해서 Jerry 와 Cosmo 의 위치를 바꿉니다; 한 번 더 반복하면 Jerry 와 Kramer 의 위치를 바꿀 수 있습니다.

#+BEGIN_QUOTE
*How Transposing Actually Works* :  
~M-t~ 명령어는 본질적으로 ~M-x forward-word (M-f)~ 명령어와 밀접하게 연관되어 있습니다.

간단히 말해 Emacs는 ~M-f~ 를 두 번 호출합니다.  
한 번은 음수 인수를 사용해서 왼쪽 단어를 바꾸고 또 한 번은 음수 인수없이 호출해서 오른쪽 단어를 바꿉니다.

실제로는 좀 더 복잡하지만 큰 차이는 없습니다. 이 이론은 테스트하기 쉽습니다.

원래 위치에서 ~M-- M-f~ 와 ~M-f~ 를 호출합니다. 호출에 커서를 원래 위치로 되돌리는 것을 잊지마시기 바랍니다.  
그러면 ~M-t~ 가 전치할 단어의 좌우 끝을 확인할 수 있습니다.
#+END_QUOTE

이전에 Emacs의 단어 이동 동작이 이해되지 않았다면 이젠 좀 더 이해됐기를 바랍니다. 모든 사람의 취향에 맞는 것은 아니지만 이동, 삭제, 위치 바꾸기 기능 전반에 걸쳐 일관성이 있습니다.

이 기능은 산문에도 그대로 작동합니다:

~Hello,█ World!~

~M-t~ 를 누른 후:

~World, Hello█!~


*** C-M-t : Transpose S-expressions
~C-M-t~ 를 사용해서 균형잡힌 표현식인 S-표현식도 전치할 수 있으며 ~M-t~ 를 이용한 단어 전치와 마찬가지로 작동 원리는 동일합니다. 전치 함수가 좌우 끝을 찾을 때 앞뒤 방향에 동일한 원리가 적용됩니다.

다음과 같은 LISP 코드 조각을 살펴보겠습니다:

#+begin_src 
~(/ (+ 2 n)█ (* 4 n))~
#+end_src

이 코드에 ~C-M-t~ 를 호출하면 두 표현식의 위치가 바뀝니다:

#+begin_src 
~(/ (* 4 n) (+ 2 n)█)~
#+end_src

앞서 설명한 ~M-t~ 와 마찬가지로 개념은 동일하지만 적용 방식이 다릅니다. 하지만, ~C-M-t~ 는 ~M-x forward-sexp~ (~C-M-f~)와 유사하게 균형잡힌 표현식이 없을 경우 ~M-x transpose-word~ 의 역할을 수행합니다:

#+begin_src 
~Hello,█ World!~
#+end_src

그리고 ~C-M-t~ 적용 후에는 다음과 같이 됩니다:

#+begin_src 
~World, Hello█!~
#+end_src

하지만, 균형잡힌 표현식과 단어를 혼합하면 어떻게 되는지 살펴보겠습니다:

#+begin_src 
~Hello,█ (이름을 여기에 입력하세요)!~
#+end_src

~C-M-t~ 적용 후:

#+begin_src 
~(이름을 여기에 입력하세요), Hello█!~
#+end_src

따라서, ~C-M-t~ 는 예상대로 작동합니다. 이런 가능성은 코드에서 분명합니다:

#+BEGIN_SRC
ages = {
  ‘Seinfeld’:█ 34,
}
#+END_SRC

예상대로 Emacs는 해당 요소를 올바르게 전치합니다:

#+BEGIN_SRC
ages = {
  34: ‘Seinfeld’█,
}
#+END_SRC

이 동작은 ~M-t~ 와 다릅니다. 앞선 시나리오에 ~M-t~ 로 적용하겠습니다:

#+BEGIN_SRC
ages = {
  ‘34’: Seinfeld█,
}
#+END_SRC


결과는 확실히 다릅니다. Emacs는 단어를 바꾸지만 심볼은 그대로 남겨둡니다. 이는 Emacs가 단어와 단어 경계를 처리하는 방식과 일치합니다.


*** Other Transpose Commands
줄, 단락, 문장 같은 다른 구문 단위들도 순서를 바꿀 수 있지만 줄 순서를 바꾸는 것 외에는 나머지 기능들은 당장 배울 필요성을 느끼기엔 어렵다고 생각합니다. 단락과 문장 명령어는 단축키가 지정되어 않아서 사용하기 더 어렵습니다. 이 명령어들을 사용하려면 ~M-x~ 로 호출하는 방법 밖에 없습니다!!

하지만, ~C-x C-t~ 를 사용해서 줄을 재배열하는 것은 분명한 용도가 있습니다. 저는 줄바꿈에 기반으로 한 목록의 순서를 바꾸기 위해 이 명령을 자주 사용하며 프로그래밍에도 제 역할을 다한다고 생각합니다.


** Filling and Commenting
*** Filling
텍스트를 많이 작성하면 줄 길이가 일정 길이를 넘지않도록 수동으로 단락을 나눠야할 때가 있습니다. Emacs의 ~fill~ 기능을 사용하면 직접 수동으로 처리하거나 작성 도중에 자동으로 이 작업을 처리할 수 있습니다. fill 명령은 단순히 텍스트에 국한되지 않습니다. 예를 들어, 주석이나 doc string도 80자 이내로 맞추도록 fill 기능을 사용할 수 있습니다.

| 키 바인딩            | 용도                  |
|----------------------+-----------------------|
| ~M-q~                | 단락 채우기           |
| ~C-x f~              | 채우기 열 너비 설정   |
| ~C-x .~              | 채우기 접두사 설정    |
| ~M-x auto-fill-mode~ | 자동 채우기 모드 전환 |

저는 코드에 주석을 달 때 ~M-q~ 를 사용해서 단락 채우기를 자주 활용합니다. 메이저 모드(major modes)는 프로그래밍 언어나 파일 유형에 적합한 모범 사례에 따라 채우기 너비(~C-x f~)를 설정하는 것이 일반적입니다.

한 페이지를 넘쳐흐르는 셜록 홈즈의 다음과 같은 인용문을 살펴보겠습니다:

#+begin_src 
'It is an old maxim of mine that when you have excluded […]
#+end_src

문단 내에 커서를 위치시킨 후 ~M-q~ 를 입력하면:

#+BEGIN_QUOTE
'It is an old maxim of mine that when you  
have excluded the impossible, whatever  
remains, however improbable, must be the  
truth.'
#+END_QUOTE

접두사 ~C-u~ 와 함께 ~M-q~ 를 입력하면 Emacs는 텍스트를 양쪽 정렬(justify)합니다:

#+BEGIN_QUOTE
'It is an old maxim of mine that when you  
have excluded the impossible, whatever  
remains, however improbable, must be the  
truth.'
#+END_QUOTE

~C-x f~ 를 입력하면 채움 너비를 입력하라는 메시지가 나타납니다. 예를 들어, 위의 인용문에서 단락으로 나눌 열에 커서를 두고 ~C-x f~ 를 눌렀습니다. 대략 42글자 정도입니다. 채움 너비는 줄당 문자 수를 의미하지만 Emacs는 단어를 하이픈으로 나누지 않으므로 채움 너비를 너무 작게 설정하면 제대로 채워지지 않습니다.

fill prefix 는 흥미로운 기능입니다. ~C-x .~ 을 입력하면 Emacs는 커서 위치까지의 현재 줄의 모든 문자를 채우기 접두사로 지정합니다. 이름으로 알 수 있듯이 fill prefix 는 ~M-q~ 를 사용해서 단락을 채울 때 줄 앞에 삽입됩니다. fill prefix 를 제거하려면 커서를 빈 줄에 놓고 ~C-x . .~ 를 입력합니다.

~M-x auto-fill-mode~ 를 활성화하면 글을 작성할 동안 텍스트가 자동으로 채워지도록 Emacs에게 지시할 수 있습니다. 저는 프로그래밍 모드에선 이 기능을 사용하지 않으며(제대로 작동하지 않기 때문에) 텍스트 모드에서만 사용하도록 제한합니다.


*** Commenting
코드에 주석을 삽입하는 것은 Emacs가 충분히 잘 할 수 있는 작업입니다. Emacs는 몇 가지 서로 다른 키 바인딩과 명령어가 내장되어 있으며 각각 다른 용도로 사용합니다.

| 키 바인딩         | 용도                                        |
|-------------------+---------------------------------------------|
| ~M-;~             | DWIM 주석 처리 또는 주석 해제               |
| ~C-x C-;~         | 줄 주석 처리 또는 주석 해제                 |
| ~M-x comment-box~ | 해당 영역을 상자 형태로 주석 처리           |
| ~M-j , C-M-j~     | 새 줄을 삽입하고 새 줄에 주석을 이어서 작성 |

주석 달기에서 자주 사용하는 두 가지 명령은 ~M-;~ 와 ~C-x C-;~ 입니다. ~M-;~ 를 입력하면 Emacs는 커서가 위치한 줄 끝에 주석을 삽입하며 커서가 빈 줄에 있을 경우 메이저 모드의 들여쓰기 규칙에 따라 주석을 들여쓰기합니다. 영역이 활성화된 상태에서 ~M-;~ 를 누르면 해당 영역의 주석 표시/해제를 전환합니다. ~C-x C-;~ 명령은 커서가 위치한 줄 전체의 주석 표시를 전환합니다. ~C-x C-;~ 는 음수 및 숫자 인수를 사용해도 정상 작동합니다.

포인트가 주석에 있을 때 ~M-j~ 또는 ~C-M-j~ 를 입력하면 Emacs는 줄을 끊고 새로운 주석을 삽입합니다. 그런 의미에서 이는 fill prefix 와 동일합니다. 이 명령은 문서 문자열을 작성할 때 유용합니다. Emacs는 일반적으로 일부 문서 문자열 형식이 요구하는 주석 접두사를 똑똑하게 인식하기 때문입니다.

앞서 언급한 Emacs fill 명령어들은 주석 구문을 이해하고 준수하므로 주석에서 ~M-q~ 를 자유롭게 사용해도 됩니다.

필요한 주석 변수가 설정되지 않은 메이저 모드에서 주석 명령어를 사용할 경우(아래 표 참조) Emacs는 명령어를 처음 실행할 때 사용할 주석 문자를 묻습니다.

| 변수 이름         | 용도                                   |
|-------------------+----------------------------------------|
| ~comment-style~   | 사용할 주석 스타일                     |
| ~comment-styles~  | 사용 가능한 주석 스타일의 연관 목록    |
| ~comment-start~   | 주석 시작을 표시할 문자                |
| ~comment-end~     | 주석 끝을 표시할 문자                  |
| ~comment-padding~ | 주석 문자(들)와 본문의 여백(보통 공백) |
|                   |                                        |

위의 모든 변수는 ~M-x customize-option~ 을 사용해서 사용자 정의할 수 있습니다. ~comment-start~ 나 ~comment-end~ 는 항상 메이저 모드 작성자가 설정하므로 직접 변경할 일은 거의 없습니다. ~comment-style~ 은 팀 내의 규정이나 개인적인 선호에 따라 특정 주석 스타일을 사용할 경우엔 반드시 설정해야 합니다. 사용 가능한 주석 스타일 목록을 확인하려면 Customize 인터페이스에서 ~comment-styles~ 변수의 설명을 읽거나 ~M-x describe-variable~ (~C-h v~ 키에도 할당됨)을 사용해서 해당 변수를 조회해야 합니다.


** Search and Replace
텍스트를 검색할 때는 정규식(다음 섹션 ‘정규식’ 참조)을 사용하거나 사용하지 않고 검색할 수 있습니다. Emacs에서 텍스트를 바꾸는 작업도 이와 마찬가지지만 검색 및 바꾸기의 ‘바꾸기’ 단계에서 Elisp의 강력한 기능을 활용할 수 있다는 장점이 있습니다.

그런 의미에서 Emacs는 다른 편집기와 다릅니다. Elisp과 정규표현식의 캡처 그룹을 사용할 수 있는데 Elisp을 잘 안다면 이는 강력한 기능입니다. Emacs의 정규표현식 구현은 나중에 설명하겠지만 PCRE 와 다릅니다. 이 구현은 정규표현식에 대한 GNU 표준을 따르되 패키지 개발자와 Emacs 사용자 모두에게 적합하도록 많은 기능이 추가(그리고 꽤 많은 기능이 생략)됐습니다.

Emacs의 검색 및 바꾸기 명령어는 다음과 같습니다:

| 키 바인딩            | 용도                  |
|----------------------+-----------------------|
| ~C-M-%~              | 정규식 검색 및 바꾸기 |
| ~M-%~                | 검색 및 바꾸기        |
| ~M-x replace-string~ | 검색 및 바꾸기        |
| ~M-x replace-regexp~ | 정규식 검색 및 바꾸기 |

Isearch에서 Emacs의 검색 및 바꾸기 기능을 사용할 수 있습니다:

| Isearch 키 바인딩 | 용도                       |
|-------------------+----------------------------|
| ~C-M-%~           | 쿼리 정규식 검색 및 바꾸기 |
| ~M-%~             | 쿼리 검색 및 바꾸기        |

쿼리(query) 명령어는 대화형으로 일치 항목이 나올 때마다 사용자에게 다음 단계를 안내합니다. Isearch와 마찬가지로 인터페이스는 간결하지만 매우 실용적입니다. 또한, 이 인터페이스는 두 부분으로 나뉩니다. 하나는 검색 및 바꾸기 프롬프트, 다른 프롬프트와 동일한 방식으로 작동하며 다른 하나는 각 일치 항목을 선택하는 대화형 부분입니다.

일치 항목이 표시되면 다음 옵션 중 하나를 선택할 수 있습니다:

| Qeury 키 바인딩 | 용도                                          |
|-----------------+-----------------------------------------------|
| ~SPC , y~       | 일치 부분을 하나 교체한 후 계속 진행          |
| ~.~             | 일치 부분을 하나 교체한 후 종료               |
| ~,~             | 교체하되 현재 일치 위치에 그대로 머무름       |
| ~RET,q~         | 일치 부분을 교체하지 않고 종료                |
| ~!~             | 버퍼의 모든 일치 항목을 교체                  |
| ~^~             | 커서를 이전 일치 위치로 이동                  |
| ~u,U~           | 마지막 교체ㅡ 작업 취소 / 모든 교체 작업 취소 |


*** Case Folding
“Isearch: 증분 검색” 섹션에서 저는 대소문자 변환(case folding)를 이미 다룬 바 있습니다. 이는 Emacs의 유용한 기능으로 대소문자가 섞인 문자열이나 대문자로 구성된 문자열을 검색할 때를 제외하고 대소문자를 구분하지 않고 문자열을 지능적으로 일치시킵니다. 이 기능이 활성화되면 대소문자를 구분하는 검색이 수행됩니다. 이는 매우 훌륭한 기능이며 Emacs의 문자열 교체 메커니즘도 이를 활용합니다.

다음과 같은 의사 코드가 포함된 버퍼를 가정합니다:

#+begin_src 
HELLO_WORLD = “Hello, World!”

function hello() {
  print(HELLO_WORLD)
}
#+END_SRC

~C-M-%~ 단축키를 사용해서 hello 를 goodbye 로 쿼리 교체(query replace)하면 위 버퍼의 결과는 다음과 같습니다:

#+begin_src 
GOODBYE_WORLD = “Goodbye, World!”

function goodbye() {
  print(GOODBYE_WORLD)
}
#+end_src

보다시피 Emacs는 Hello 나 HELLO 가 아닌 hello 를 검색하므로 치환 대상의 대소문자를 그대로 유지합니다. 만약 Hello 나 HELLO 를 검색했다면 Emacs는 대문자가 포함된 문자열만 치환했을 겁니다.


*** Regular Expressions
앞서 저는 PCRE와 Emacs의 차이점에 대해 언급한 바 있습니다. 요컨대 Emacs의 정규식 엔진은 도저히 사용자 친화적이라곤 말할 수 없을 정도입니다. 이 엔진은 아주 오래되고 낡았으며 Emacs의 특수한 요구 사항에 맞추기 위해 대대적으로 수정된 탓에 쉽게 대체하기도 어려운 상태입니다.

예를 들어, PCRE 스타일의 엔진에서 ~(~ 와 ~)~ 문자는 메타 문자로 즉, 엔진이 이를 문자그대로의 문자가 아닌 캡처 그룹으로 처리합니다. 반면 Emacs는 이와 정반대입니다. 이 문자들은 백슬래시(~\~)로 이스케이프 처리할 때까지는 문자그대로의 문자로 취급되다가 그 시점에서야 비로소 메타 문자 역할을 수행합니다.

실질적으로 이는 Emacs의 독특한 정규표현식 엔진에 익숙하지 않은 사용자들에게 정규표현식 작성 시 혼란을 야기합니다. Elisp을 작성할 때는 상황이 좀 더 심각합니다. Emacs의 C 스타일 문자열 리더가 백슬래시를 감지해서 오류를 발생시키므로 이탈 문자를 다시 한 번 이스케이프 처리해야 하기 때문입니다.

정규표현식은 그 자체로 한 권의 책이 될만큼 아주 방대하므로 여기선 자세히 다루지 않겠습니다. 대신, Emacs의 정규표현식 엔진이 현대적인 엔진들과 어떻게 다른지를 설명하겠습니다.


**** Backslashed Constructs
다음 구문는 백슬래시가 필요하며 그렇지 않으면 Emacs가 이를 리터럴 문자로 처리합니다:

| 구문      | 설명      |
|-----------+-----------|
| ~\~       | 대안      |
| ~\( , \)~ | 캡처 그룹 |
| ~\{ , \}~ | 반복      |


**** Missing Features
Emacs는 하드코딩된 구문을 제외하곤 어떤 종류의 음수 또는 양수 선행/후행 검사도 지원하지 않습니다!! 분기 재설정 그룹 같은 다소 생소한 정규식 기능도 빠져 있습니다. 대부분의 텍스트 편집 작업에선 이것이 큰 문제가 되진 않습니다.

한 가지 불편한 점은 숫자 클래스를 나타내는 약어인 ~\d~ 가 없다는 것입니다. ~\d~ 대신 ~[0-9]~ 를 사용하거나 명시적인 ~[:digit:]~ 클래스를 사용해야 합니다.


**** Emacs-only features
Emacs의 정규식 엔진이 특히 뛰어난 점은 매치 구문 지원과 유니코드 지원입니다:

| 구문        | 설명                                                    |
|-------------+---------------------------------------------------------|
| ~\< , \>~   | 단어의 시작과 끝을 일치시킵니다                         |
| ~\_< , \_>~ | 기호의 시작과 끝을 일치시킵니다                         |
| ~\scode~    | 구문 테이블 코드가 code인 모든 문자를 일치시킵니다      |
| ~\Scode~    | 구문 테이블 코드가 code가 아닌 모든 문자를 일치시킵니다 |

~\<, \>, \_<, \_>~ 를 사용해서 기호와 단어를 일치시키는 것은 임시적인 리팩토링을 위한 프로그래밍에서 흔히 볼 수 있는 처리 방식입니다. 단어와 기호의 정의는 Emacs의 구문 테이블에 달려 있으므로 메이저 모드에 따라 달라집니다.

~\s~ 와 ~\S~  모두 특정 구문 클래스에 속하는 문자를 일치시킬 수 있다는 점에서 각각의 용도가 있습니다. 각 클래스의 명명은 사실 단순한 지침일 뿐입니다. 메이저 모드 작성자가 숫자 9 를 공백 클래스에 속한다고 선언하는 것을 막을 수 있는 것은 아무것도 없기 때문입니다.

다음은 흥미로운 구문 클래스의 요약 목록입니다:

*공백 문자 (-)* : 예상대로 일반적인 공백뿐만 아니라 줄바꿈 및 일반적으로 비-분리 공백같은 유니코드 등가 문자도 포함합니다.

*단어 구성 요소 (w)* : 이는 일반적으로 모든 소문자 및 대문자, 숫자 그리고 비-라틴 문자 집합의 유니코드 등가 문자를 포함합니다.

*기호 구성 요소 (_)* : 모든 단어 구성 요소와 프로그래밍 언어에서 가장 자주 사용되는 ~!~ 나 ~_~ 같은 기호를 포함합니다. 이 클래스는 다른 어떤 클래스보다 현재 사용 중인 메이저 모드에 따라 변화할 가능성이 높습니다.

*구두점 문자 (.)* : ~.~ 이나 ~;~ 같은 일반적인 문자를 포함합니다. 텍스트 모드와 프로그래밍 모드는 상당히 다를 가능성이 높습니다.

*열림/닫힘 괄호 (( 및 ))* : 쌍을 이루는 모든 문자 집합을 포함합니다. 대부분의 텍스트 및 프로그래밍 모드는 ~() , []~ 및 ~{}~ 가 포함됩니다.

*문자열 문자 (")* : 연속된 블록을 문자열로 표시하는 모든 기호를 포함합니다. 큰따옴표와 작은따옴표, ~'~ 및 ~"~ 가 일반적으로 여기에 포함됩니다. 좌/우 괄호, 기요모트(guillemots) 같은 유니코드 문자도 이 범주에 포함됩니다.

*주석 시작/종료 문자 (< 및 >)* : 주석 경계를 정의하는 모든 문자 또는 문자 쌍입니다. 일부 언어는 줄 단위 주석만 지원하며 이 경우 ~<~ 만 사용됩니다.

예를 들어, 모든 공백 문자를 일치시키려면 ~\s-~ 를 검색합니다. 모든 문자열 따옴표 문자를 일치시키려면 예를 들어, 'strings' 와 “strings” 모두 가능한 Python처럼– ~\s"~ 를 사용해서 모든 따옴표 기호를 일치시킵니다. 이를 통해 Emacs가 사용자의 메이저 모드 구문을 이해하는 기능을 활용해서 텍스트를 변환합니다 (또는 단순히 찾을 수 있습니다. 이 명령은 regexpIsearch 나 Occur 에도 작동합니다).

#+BEGIN_QUOTE
*Determining a character’s syntax class* :  
Emacs의 유니코드 지원 기능은 훌륭하며 광범위한 유니코드 지원의 일환으로  
~C-u M-x what-cursor-position~ 명령을 사용해서 원하는 문자를 자세히 살펴볼 수 있습니다.

이를 사용하려면 확인할 문자에 커서를 위치시킨 후 해당 명령을 실행하거나 ~C-u C-x =~ 를 입력합니다.  
그러면 구문 클래스, 폰트 락, 유니코드 이름 등을 포함한 다양한 정보가 표시됩니다.
#+END_QUOTE

Emacs는 다음과 같은 여러 종류의 캡처 그룹이 있습니다:

| 구문        | 설명                                                        |
|-------------+-------------------------------------------------------------|
| ~\1 ~ \9~   | 그룹 \N 의 텍스트를 삽입합니다                              |
| ~\#1 ~ \#9~ | 그룹 \N 의 텍스트를 삽입하되 정수로 변환합니다 (Elisp 전용) |
| ~\?~        | 사용자에게 텍스트 입력을 요청합니다                         |
| ~\#~        | 0 부터 증가하는 숫자를 삽입합니다                           |
| ~\&~        | 일치한 문자열 전체를 삽입합니다                             |

~\#N~ 캡처 그룹은 elisp 형식 외에는 거의 쓸모가 없습니다. ~\?~ 를 사용하면 일치 부분을 직접 입력한 문자열로 바꿀 수 있습니다. ~\#~ 그룹은 0 부터 시작하는 번호를 삽입하며 일치할 때마다 1 씩 증가합니다. 마지막으로 ~\&~ 는 단순히 일치한 문자열 전체를 삽입합니다.


**** Invoking Elisp
검색 및 바꾸기 인터페이스의 ‘바꾸기’ 부분에서 elisp 함수를 호출할 수 있습니다. 이 기능을 사용할지 여부는 전적으로 elisp에 대한 이해도(또는 실험해 볼 의지)와 복잡한 검색 및 바꾸기 작업을 얼마나 자주 수행하느냐에 달려 있습니다.

Elisp을 호출하려면 다음과 같은 형식을 사용합니다:

#+begin_src 
\,(form ...)
#+end_src

여기서 form 은 호출할 함수의 이름입니다. Elisp을 호출하려면 반드시 따라야 할 몇 가지 규칙이 있습니다:

- 캡처 그룹은 기본적으로 문자열 유형입니다. 정수같은 다른 유형을 기대하는 엘리스프(Elisp) 함수에 문자열을 전달하면 오류가 발생합니다.

- 함수에서 캡처 그룹이 필요하지 않으면 캡처 그룹을 사용할 필요가 전혀 없습니다. 함수의 유일한 출력값으로 일치 결과를 대체하는 것도 충분히 가능합니다.

- 한 번에 하나의 형식만 호출할 수 있습니다. 따라서, 두 개 이상을 호출하려면 progn 이나 prog1 같은 함수로 감싸거나 concat 같은 함수를 사용해서 여러 함수의 결과를 하나로 연결해야 합니다.

- 캡처 그룹을 따옴표로 묶지마시기 바랍니다. 이는 Emacs 인터프리터에게 리터럴 문자열(~\N~ 사용 시) 또는 숫자(~\#N~ 사용 시)로 전달되기 때문입니다.

다음은 시도할 수 있는 몇 가지 대체 문자열의 예입니다:

| 대체 문자열             | 설명                                                           |
|-------------------------+----------------------------------------------------------------|
| ~\,(upcase \N)~         | 대문자로 변환하는 캡처 그룹 \N                                 |
| ~\,(format “%.2f” \#N)~ | ~\#N~ 을 숫자로 변환하고 소수점 두 자리 십진수 형식으로 포맷팅 |

강력한 기능이지만 상황에 따라 다릅니다. ‘버퍼(The Buffer)’ 섹션에서 언급했듯이 Emacs 내부 함수 대부분—흥미로운 작업을 수행하는 거의 모든 함수—은 문자열이 아닌 버퍼를 대상으로 작동합니다. 이로인해 이 기능의 유용성이 크게 떨어지는데 원하는 작업을 수행할 함수를 찾아야할 뿐만 아니라 문자열을 대상으로 작동하는 함수도 찾아야 하기 때문입니다.

이 기능이 필요할 때마다 저는 어쩔 수 없이 원하는 방식으로 텍스트를 변환하는 나만의 특수 함수를 직접 작성했습니다. 하지만, 이는 elisp에 대한 어느 정도의 숙련도를 전제로 합니다. 제 조언은 Emacs의 키보드 매크로를 활용하는 방법입니다. 이 주제는 곧 다룰 예정인데 복잡한 편집 작업에는 키보드 매크로가 훨씬 더 적합하기 때문입니다.


** Changing Case
대소문자 변경—텍스트의 대소문자를 변경하거나 소문자 또는 대문자로 바꾸는 것—은 코드와 텍스트 모두에서 흔히 발생하는 현상입니다.

| 영역 명령                    | 설명                                |
|------------------------------+-------------------------------------|
| ~C-x C-u~                    | 선택 영역의 문자를 대문자로 변환    |
| ~C-x C-l~                    | 선택 영역의 문자를 소문자로 변환    |
| ~M-x upcase-initials-region~ | 선택 영역의 첫 글자를 대문자로 변환 |

처음 두 가지는 딱히 설명할 것이 별로 없습니다. 영역이 활성화된 상태는 해당 영역의 글자를 대문자나 소문자로 변경할 수 있습니다. 영역의 글자를 대문자로 변경하는 것은 실제로는 문장, 줄 또는 단락의 첫 단어뿐만 아니라 영역 내의 모든 단어를 대문자로 만드는 것을 의미합니다.

단어에 적용되는 대소문자 명령어들이 훨씬 더 흥미롭습니다:

| 키 바인딩 | 용도                      |
|-----------+---------------------------|
| ~M-c~     | 다음 단어를 대문자로 변경 |
| ~M-u~     | 다음 단어를 대문자로 변경 |
| ~M-l~     | 다음 단어를 소문자로 변경 |

우선 이 명령어들은 기억하기도 쉽고 소위 ‘주요 키 영역’ (손이 닿기 쉽고 입력하기 편한 키들)에 할당되어 있습니다. 이 명령어들은 Emacs의 다른 단어 기반 명령어들과 정확히 동일한 방식으로 작동하며 ~forward-word, mark-word, kill-word, transpose-words~ 명령어와 동일한 구문 테이블 처리 규칙을 따릅니다.

숫자 인자와 음수 인자 모두 예상대로 작동합니다. 다른 단어 기반 명령어들과 마찬가지로 이 명령어들도 외워둘 것을 권장합니다. 영역 명령어들은 별도로 외울 필요가 없습니다. 영역 단위로 대소문자를 변경하는 작업을 많이 하지않는 한 단어 단위로 대소문자를 변경할 가능성이 훨씬 더 높기 때문입니다.

이 명령어들을 사용할 때 커서를 유지하는 것은 매우 중요합니다. 일반적으로 글을 쓰면서 이 명령어들을 사용하기 때문입니다. ~M-- M-u~ 는 예를 들어, 방금 입력한 단어를 대문자로 바꾸고 ~M-b M-- M-u~ 는 한 단어 뒤로 이동해서 그 앞의 단어를 대문자로 바꿉니다. 물론 키를 누르는 사이에 메타 키를 놓아선 안 됩니다. 따라서, 엄지손가락을 왼쪽 메타 키에 둔 채로 다른 손가락들은 자유롭게 ~b - u~ 를 입력할 수 있습니다.

다음 문장을 살펴보겠습니다. 마침표를 삽입하고 다음 단어를 대문자로 변환합니다:

#+begin_src 
Hey how are you?
#+end_src

~M-f~ 를 눌러 한 단어 앞으로 이동한 후 ~.~ 을 눌러 마침표를 삽입하고 ~M-c~ 를 눌러 다음 단어를 대문자로 변경하면:

#+begin_src 
Hey. How█ are you?
#+end_src

마찬가지로 여기서 식별자 입력은 마쳤지만 이 식별자는 문자열 상수로 대문자로 표기되야 합니다:

#+begin_src 
print(greeting_string)█
#+end_src

대부분의 메이저 모드에서 ~_~ 는 구두점이나 기호로 인식되므로 단어를 끊어버립니다. 따라서, ~M-b~ 를 두 번 눌러 뒤로 이동해서 커서를 greeting_string 의 시작 부분에 위치시켜야 합니다.

아니라면 숫자와 부정 연산자를 결합한 ~M-- M-2 M-u~ 를 사용할 수 있습니다:

#+begin_src 
print(GREETING_STRING)█
#+end_src

조금만 연습하면 생각할 필요없이 빠르고 직관적으로 이 작업을 수행할 수 있습니다. 또 다른 장점은 커서를 이동하지 않으므로 계속 글을 쓸 수 있다는 점입니다. 커다란 시간 절약처럼 보이진 않겠지만 이런 것이 쌓인다면 큰 차이가 납니다.

대소문자 명령어는 비-라틴 문자도 잘 작동합니다. Emacs는 대부분의 유니코드 문자를 올바른 유니코드 범주로 매핑하기 때문입니다. 실질적으로 이는 Emacs가 소문자나 대문자를 만났을 때 이를 인식한다는 것을 의미합니다:

#+BEGIN_QUOTE
그리스어: αβψδεφγ -> ΑΒΨΔΕΦΓ  
덴마크어: abcdæøå -> ABCDÆØÅ
#+END_QUOTE


#+BEGIN_QUOTE
*Unicode categories* :  
~M-x describe-categories~ 를 실행해서 모든 유니코드 범주의 전체 목록을 확인하시기 바랍니다.
#+END_QUOTE



** Counting Things
무언가 세기 위해 굳이 wc 프로그램을 호출할 필요는 없습니다. Emacs도 그 작업을 완벽히 수행할 수 있습니다.

| 명령어                         | 설명                                        |
|--------------------------------+---------------------------------------------|
| ~M-x count-lines-region~       | 지정된 영역의 줄 수를 셉니다                |
| ~M-x count-matches~            | 지정된 영역에서 일치한 패턴의 개수를 셉니다 |
| ~M-x count-words~              | 버퍼의 단어, 줄, 문자 수를 셉니다           |
| ~M-x count-words-region , M-=~ | 지정된 영역의 단어, 줄, 문자 수를 셉니다    |

세는 방법은 여러 가지지만 기억할만한 두 가지는 다음과 같습니다:

*~M-x count-words~* : 이 명령은 이름과 달리 줄과 문자까지 셉니다. 때로는 특정 영역의 항목을 셀 수도 있는데 이 경우 ~M-=~ 를 사용합니다.

*~M-x count-matches~* : 지정한 정규표현식 패턴의 일치 횟수를 셉니다. 활성 영역이 없을 경우 커서 위치부터 버퍼 끝까지, 활성 영역이 있을 경우 해당 영역만 셉니다.


** Text Manipulation
텍스트 조작 작업은 Emacs가 특히 뛰어난 분야 중 하나로 이를 돕기위한 다양한 도구를 갖추고 있습니다. 텍스트 파일을 가공하거나 로그 파일에서 관련 정보를 추출하는 작업은 Emacs에서 흔히 수행되는 작업입니다. 비록 Emacs가 awk 나 sed 같은 전용 도구나 Python 같은 프로그래밍 언어를 완전히 대체할 수 없겠지만 중소 규모의 작업에선 훌륭한 선택지입니다.


*** Editable Occur
앞서 특정 패턴과 일치하는 모든 줄을 정렬하는 방법으로 ~M-x occur~ 를 소개한 바 있습니다. occur 모드에서 아직 언급하지 않은 기능 중 하나는 일치 부분을 편집하고 작업이 끝나면 변경 사항을 해당 줄에 반영할 수 있다는 점입니다.

이를 위해선 우선 ~e~ 를 입력해서 편집 가능한 occur 모드로 진입합니다. 그런 다음 ~C-c C-c~ 를 입력해서 변경 사항을 적용합니다. 활용 가능성은 무궁무진합니다. 이 기능은 특히 키보드 매크로와 검색 및 바꾸기 작업에서 유용합니다.


*** Deleting Duplicates
Emacs는 중복된 줄을 삭제할 수 있으며 가장 큰 장점은 명령줄 유틸리티인 uniq 와 달리 Emacs가 중복을 감지할 때 줄들이 서로 인접할 필요가 없다는 점입니다. 즉, 텍스트를 정렬하지 않고도 중복 부분을 삭제할 수 있습니다.

| 범용 인자     | 설명                         |
|---------------+------------------------------|
| 삭제 없이     | 첫 번째 중복 행 삭제         |
| ~C-u~         | 마지막 중복 행 삭제          |
| ~C-u C-u~     | 인접한 중복 행만 삭제        |
| ~C-u C-u C-u~ | 인접한 빈 행은 삭제하지 않음 |

기본적으로 ~M-x delete-duplicate-lines~ 은 맨 위부터 시작해서 처음 발견된 중복 줄을 삭제합니다. 단일 범용 인수를 지정하면 맨 아래부터 시작하므로 마지막 줄을 삭제합니다.


*** Flushing and Keeping Lines
때로는 영역의 줄을 특정 패턴에 따라 필터링할 때도 있습니다. 패턴과 일치한 줄 혹은 일치하지 않는 줄만 남겨두는 방식입니다.

두 명령어 모두 활성 영역에 적용되므로 버퍼 전체에 이 작업을 수행하려면 먼저 ~C-x h~ 를 눌러 버퍼 전체를 선택하는 것이 일반적입니다.

| 명령어            | 설명                                                                              |
|-------------------+-----------------------------------------------------------------------------------|
| ~M-x flush-lines~ | 지정된 패턴과 일치한 영역의 모든 줄을 지웁니다                                    |
| ~M-x keep-lines~  | 지정된 패턴과 일치한 영역의 모든 줄을 유지하고 일치하지 않는 줄 모두를 제거합니다 |

두 명령어 모두 정규식 패턴을 지원합니다. 패턴이 줄과 일치하면 해당 줄은 유지되거나 삭제됩니다. 패턴 자체는 변경되지 않습니다(패턴 자체를 변경하려면 검색 및 바꾸기 기능을 사용합니다).

저는 텍스트를 처리할 때 이 명령들을 자주 사용합니다. 패턴과 일치한 줄을 유지해서 '가난한 사람의 grep' 처럼 사용할 수 있으며 flush 는 반대 역할을 처리합니다. 로그 파일 필터링이나 데이터 정제 작업은 이 명령들이 가장 효과적으로 활용되는 두 가지 예입니다.


*** Copying and Killing Matching Lines
줄을 지우거나 유지하는 명령과 마찬가지로 Emacs에서 줄을 복사하거나 삭제하도록 지시할 수 있습니다. 하지만, 이 기능들은 Emacs 28에 새로 추가된 기능으로 이전 버전에선 사용할 수 없습니다.

| 명령어                    | 설명                                                           |
|---------------------------+----------------------------------------------------------------|
| ~M-x copy-matching-lines~ | 지정된 영역에서 패턴과 일치한 모든 줄을 복사합니다 (Emacs 28+) |
| ~M-x kill-matching-lines~ | 지정된 영역에서 패턴과 일치한 모든 줄을 삭제합니다 (Emacs 28+) |


*** Joining and Splitting Lines
줄을 삭제하는 명령어(~C-M-<backspace>~ 및 ~C-k~)와 달리 이 명령어들은 킬 링을 변경하지 않습니다. 또한, 커서 위치를 이동하지 않고 줄을 삽입하거나 삭제하므로 좀 더 특수한 용도로 사용합니다.

| 키 바인딩 | 설명                                               |
|-----------+----------------------------------------------------|
| ~C-o~     | 커서 위치 뒤에 빈 줄을 삽입합니다                  |
| ~C-x C-o~ | 커서 위치 뒤의 모든 빈 줄을 삭제합니다             |
| ~C-M-o~   | 커서 위치 뒤에서 줄을 나누되 들여쓰기를 유지합니다 |
| ~M-^~     | 커서가 위치한 줄과 그 위 줄을 합칩니다             |

커서 위치 바로 뒤에 새로운 줄을 삽입하려면 ~C-o~ 를 사용합니다. ~RET~ 과 달리 커서는 다음 줄로 이동하지 않고 원래 위치에 그대로 남습니다. 저는 ~RET~ 을 사용할 때 커서 위치까지 함께 이동하는 것을 원치 않을 때 이 명령으로 단락을 두 개로 나누곤 합니다.

빈 줄을 삭제하는 것은 매우 흔한 작업입니다. ~C-x C-o~ 는 바로 이 작업을 수행하지만 다음과 같은 세 가지 규칙을 따릅니다:

*현재 줄은 무시합니다* : 비어있는 줄도 커서가 위치한 줄은 제거하지 않습니다. 즉, 빈 줄 블록에서 이 명령을 실행하면 정확히 한 줄의 빈 줄만 남습니다. 이 규칙을 반드시 기억하시기 바랍니다. 텍스트의 단락 사이나 코드의 클래스 및 함수 정의 사이 등 일정한 간격을 유지하는 데 유용한 방법입니다.

*커서 앞쪽을 처리합니다* : 따라서, 비어있지 않은 줄에서 이 명령을 호출하면 커서 앞쪽의 빈 줄을 제거합니다. 앞서 설명한 규칙과 달리 ~C-x C-o~ 는 모든 빈 줄을 제거합니다.

*공백과 탭만 포함된 줄도 제거합니다* : 빈 줄에 탭이나 공백 문자를 그대로 남겨두는 많은 언어에 유용합니다.

~C-M-o~ 는 일상적으로 사용하지 않는 매우 특수한 명령어입니다. 마침표 뒤에 새로운 줄을 삽입하는(‘줄 시작’ 이라고도 함) ~C-o~ 와 달리 ~C-M-o~ 는 동일한 기능을 수행하지만 텍스트의 열 오프셋을 그대로 유지합니다.

~C-o~ 와 ~C-M-o~ 의 차이점을 살펴보겠습니다:

#+begin_src 
All the world's a stage, █and all the …
#+end_src

~C-o~ 사용 후:

#+BEGIN_QUOTE
All the world's a stage, █
and all the …
#+END_QUOTE

이제 원래 예제를 ~C-M-o~ 를 사용해서 다시 살펴보겠습니다:

#+BEGIN_QUOTE
All the world's a stage, █
                                         and all the …
#+END_QUOTE

커서가 원래 위치에 그대로 남아있음을 확인하시기 바랍니다.

마지막으로 ~M-^~ 명령어는 ~C-o~ 및 ~C-M-o~ 와 정반대 기능을 수행합니다: 커서가 위치한 현재 줄을 바로 위의 줄과 합칩니다. 문장을 하나의 긴 단락으로 합치거나 여러 줄에 걸친 함수 인수를 한 줄로 합칠 경우 유용합니다.

~M-^~ 는 두 줄을 연결할 때 공백을 적절히 잘라내는 기능을 갖추고 있습니다. 즉, Emacs는 병합하려는 줄에 텍스트가 있는지 여부에 따라 공백을 잘라내어 최소 0개 또는 1개의 공백만 남게 만듭니다. 빈 줄의 경우 모든 공백은 제거되며 텍스트가 있는 줄의 경우 한 칸을 제외한 모든 공백이 제거됩니다.

#+BEGIN_QUOTE
*Fill prefix*:
채우기 접두사가 활성화된 상태에서 ~C-M-o~ 를 입력하 현재 줄은 분할되고 새로운 줄에 채우기 접두사가 삽입됩니다.
반대로 ~M-^~ 를 누르면 병합할 줄의 채우기 접두사는 제거됩니다.
#+END_QUOTE


*** Whitespace Commands
다른 곳에서 텍스트를 가져오거나 공백이 중요한 의미를 갖는 언어나 텍스트를 다룰 때는 공백 관리가 종종 문제가 됩니다.

| 명령어                           | 설명                                                                    |
|----------------------------------+-------------------------------------------------------------------------|
| ~M-x delete-trailing-whitespace~ | 뒤쪽의 모든 공백을 삭제합니다.                                          |
| ~M-SPC~                          | 커서 위치 좌우의 공백이나 탭 중 하나를 제외한 나머지를 모두 삭제합니다. |
| ~M-x cycle-spacing~              | 위와 같으나 ‘하나만 남기기’, ‘모두’, ‘취소’ 모드를 순환합니다.          |
| ~M-\~                            | 커서 위치 주변의 공백을 삭제합니다.                                     |

~M-SPC~ 는 커서 위치 좌우의 모든 공백을 하나의 공백 문자로 줄여줍니다. ~M-\~ 도 마찬가지로 작동하지만 모든 공백 문자를 제거해서 아무것도 남기지 않습니다. ~M-x cycle-spacing~ 은 공백을 하나 남기기, 공백을 전혀 남기지 않기 그리고 원래의 공백 간격을 복원하기를 순차적으로 전환합니다.

#+BEGIN_QUOTE
*Cycle Spacing as the default* :
기본적으로 공백 하나만 입력하는 대신 ~M-SPC~ 키를 누를 때 공백 간격 옵션을 순환하면서 선택할 수 있습니다.

이를 구현하려면 다음 내용을 init 파일에 추가합니다:

~(global-set-key [remap just-one-space] 'cycle-spacing)~
#+END_QUOTE

Emacs의 공백 모드를 사용하면 공백 문자와 줄 끝의 여분 공백이나 지나치게 긴 줄 같은 타자 오류를 화면에 표시할 수 있습니다.


**** Whitespace Minor Mode

| 명령어                          | 설명                                                        |
|---------------------------------+-------------------------------------------------------------|
| ~M-x whitespace-mode~           | 모든 공백 문자를 강조 표시하는 마이너 모드                  |
| ~M-x whitespace-newline-mode~   | 줄바꿈 문자를 ~$~ 기호로 표시하는 줄바꿈 모드               |
| ~M-x whitespace-toggle-options~ | ~whitespace-mode~ 의 모든 옵션을 토글할 수 있는 메뉴를 표시 |

Emacs의 공백 마이너 모드는 평소엔 보이지 않는 공백 문자에 글리프와 색상을 입혀서 사용자가 이를 구분할 수 있도록 해줍니다. 문장 끝의 공백, 잘못된 탭 문자 또는 공백이 포함된 “빈” 줄을 찾을 때 유용합니다.

공백 모드는 다음과 같은 항목을 추적합니다: 줄 끝 공백, 탭, 공백, ~whitespace-line-column~ (일반적으로 80자)보다 긴 줄, 줄바꿈 문자, 유니코드 간격, 빈 줄, 들여쓰기(탭과 공백 모두), 탭 뒤의 공백 및 탭 앞의 공백. 기본적으로 이 모드는 구문이나 서식 오류를 유발할 수 있는 모든 가능한 조합을 추적합니다.

~M-x customize-group~ 명령을 사용해서 whitespace 그룹을 사용자 정의함으로써 특히 색상이 다소 강렬하므로 ~whitespace-mode~ 를 사용자 정의할 것을 권장합니다.

또한, ~M-x whitespace-toggle-options~ 을 사용해서 ~whitespace-mode~ 가 강조 표시할 스타일을 전환할 수 있습니다.


**** Whitespace Reporting and Cleanup

| M-x 명령어                  | 설명                                     |
|-----------------------------+------------------------------------------|
| ~whitespace-report~         | 공백과 관련된 문제를 표시합니다          |
| ~whitespace-report-region~  | 위와 동일하지만 지정한 영역에 적용됩니다 |
| ~whitespace-cleanup~        | 자동 정리를 시도합니다                   |
| ~whitespace-cleanup-region~ | 위와 동일하지만 지정된 영역에 적용됩니다 |

~M-x whitespace-report~ 명령을 실행하면 (리전(region)의 경우도 마찬가지) 버퍼나 리전에 존재하는 “문제점” 을 간결히 정리한 목록을 확인할 수 있습니다. 또한, 해당 정리 명령을 사용해서 Emacs에 버퍼나 리전의 정리를 시도하도록 요청할 수 있습니다.



** Keyboard Macros
Emacs는 키 입력과 명령을 기록해서 나중에 재생할 수 있도록 키보드 매크로로 저장할 수 있습니다. Emacs의 키보드 매크로는 LISP 매크로와 많이 다르므로 두 가지를 혼동해서는 안 됩니다.

매크로 기록 기능은 새로운 발명품이 아닙니다. 대부분의 IDE와 텍스트 편집기에 이 기능이 있지만, Emacs만큼 진보된 기능을 갖춘 것은 거의 없습니다. Emacs의 키보드 매크로는 거의 모든 것이 기록될 수 있으므로 특히 강력합니다. 사각지대는 거의 없으며 –실제로 마주칠 가능성도 거의 없습니다– 바로 이런 점이 Emacs를 IDE와 그 대부분이 빈약한 매크로 기록 기능을 가진 다른 편집기들과 차별화합니다.

Emacs의 매크로 레코더는 LISP 언어로 작성되었습니다. 이 사실만으로도 Emacs가 제공하는 확장성의 힘을 잘 알 수 있지만, 이는 또한 Emacs 내에서 미시적 및 거시적 수준에서 이루어지는 변경 사항을 얼마나 세밀하게 관찰하고 기록할 수 있는지를 다시 한번 증명해 줍니다.


*** Basic Commands

| 키 바인딩        | 설명                                                |
|------------------+-----------------------------------------------------|
| ~F3~             | 매크로 녹화를 시작하거나, 카운터 값을 삽입합니다    |
| ~F4~             | 매크로 녹화를 중지하거나 마지막 매크로를 실행합니다 |
| ~C-x~ (및 ~C-x~) | 매크로 녹화를 시작하고 중지합니다                   |
| ~C-x e~          | 마지막 매크로를 실행합니다                          |

~F3~ 키로 녹화를 시작하고 ~F4~ 키로 중지할 수 있습니다. 나머지 두 키는 사용하기 다소 불편하지만, Emacs의 노련한 베테랑 사용자들과의 하위 호환성을 위해 마련된 것입니다. 매크로 레코더는 범용 종료 명령인 ~C-g~ 를 호출하면 중지됩니다. 

#+BEGIN_QUOTE
*Signaling Errors* :
때때로 Emacs에서 오류가 발생하면 녹화나 재생이 중단되기도 합니다.
흔히 발생하는 “오류” 중 하나는 오류 목록의 시작이나 끝 부분에 도달했을 때
~M-g M-n~ 또는 ~M-g M-p~ (다음 오류 또는 이전 오류로 이동)를 입력하는 경우입니다.

이때 Emacs는 내부적으로 오류를 발생시키는데, 시스템의 사양에 따라 경고음이 울리거나
화면이 깜빡일 수 있습니다.
조심하지 않으면 이 때문에 당황할 수 있습니다. 저조차도 여전히 그런 일이 생기곤 합니다!

하지만, 결국에는 좋은 일입니다. 다음 또는 이전 오류 기능을 호출하는 매크로를 녹화한 다음,
해당 매크로를 반복해서 재생할 수 있기 때문입니다.
오류 목록의 끝(또는 시작)에 도달하면 매크로가 중지 신호를 보낼 것입니다
#+END_QUOTE

매크로 녹화가 진행 중일 때는 모드라인에 ‘Def’ 라는 단어가 표시됩니다. 녹화를 마치면 ~C-x e~ 또는 ~F4~ 를 입력해서 즉시 재생할 수 있습니다.

기록된 매크로는 킬 링, 실행 취소 링, 히스토리 링과 마찬가지로 자체적인 매크로 링을 가지고 있습니다. 즉, 새로운 매크로를 시작하더라도 실수로 기존 매크로를 덮어쓰는 걱정을 할 필요가 없습니다. 매크로는 (Emacs를 종료하지 않는 한) 절대 완전히 사라지지 않지만, 원한다면 디스크에 명시적으로 저장할 수도 있습니다.

또한 매크로 명령어에 범용 인자와 숫자 인자를 전달할 수 있습니다:

| 키 바인딩 | 설명                                                |
|-----------+-----------------------------------------------------|
| ~C-u F3~  | 녹화를 시작하지만 마지막 매크로에 내용을 추가합니다 |
| ~C-u F4~  | 매크로 링에 있는 두 번째 매크로를 재생합니다        |
| ~숫자 F3~ | 녹화를 시작하지만 카운터를 숫자로 설정합니다        |
| ~숫자 F4~ | 마지막 매크로를 숫자 번 재생합니다                  |

따라서, ~C-u~ 와 숫자 인수는 서로 다른 기능을 수행합니다. 여기서 ‘숫자’ 란 ~C-u 10~ 이나 ~M-10~ 같은 숫자를 의미합니다.

마지막 매크로(~C-u F3~) 뒤에 매크로를 추가하는 방법도 유용하지만, ~F4~ 에 숫자 인수를 전달하는 방법도 알아두면 좋습니다. 매크로를 정해진 횟수만큼 반복해서 실행하는 경우가 좀 더 흔하기 때문입니다. 숫자 0 (예를 들어 ~C-0 F4~ 또는 ~C-u 0 F4~)을 전달하면, Emacs는 버퍼의 끝에 도달하거나 기록된 매크로가 오류 신호를 보낼 때 같이 Emacs가 오류를 알릴 때까지 매크로를 반복해서 실행합니다.


*** Advanced Commands
~C-x C-k~ 라는 접두사 키 조합은 전적으로 Emacs의 매크로 기능을 위해 마련된 것입니다. 여기에는 수많은 명령어가 포함되어 있으며, 대부분은 상당히 특수한 용도로 쓰입니다.

#+BEGIN_QUOTE
*Learn more* :
항상 그렇듯이, 접두사 키 앞에 ~C-h~ 를 입력하면
Emacs가 해당 접두사에 바인딩된 모든 키를 나열해 줍니다.

또 다른 방법은 apropos (~C-h a~)를 사용해서
모든 명령어를 나열하는 것입니다.

명명 체계는 다소 일관성이 없습니다. 많은 매크로 명령은 kmacro 로 시작합니다.
그러나, 일부는 Emacs의 해당 부분이 도입되기 이전에 만들어진 것으로,
단순히 ~kbd-macro~ 라는 단어를 포함하고 있을 뿐입니다.
#+END_QUOTE


**** Interactive Macro Playback
먼저 카운터부터 살펴보겠습니다. 녹화를 시작하면 Emacs는 내부 카운터를 자동으로 0 으로 초기화하며, 녹화 중에 ~F3~ 키를 누를 때마다 Emacs는 해당 카운터를 삽입한 뒤 내부 카운터를 1씩 증가시킵니다. 물론 이 카운터를 창의적으로 활용할 수 있는 방법은 많지만, 번호가 매겨진 목록을 만드는 것이 가장 대표적인 예입니다.

| 키 바인딩           | 설명                     |
|---------------------+--------------------------|
| ~C-x C-k C-a~       | 카운터에 값 추가         |
| ~C-x C-k TAB, F3~   | 카운터 삽입              |
| ~C-x C-k C-c~       | 카운터 설정              |
| ~C-x C-k C-f~       | 포맷 카운터 설정         |
| ~C-x C-k q , C-x q~ | 녹화 중 사용자 입력 요청 |

위의 카운터 명령어들은 이뿐만 아니라 좀 더 많은 기능을 수행합니다. ~C-x C-k C-a~ 는 카운터에 숫자를 더하고, 반대로 음수를 입력하면 카운터에서 숫자를 뺍니다. ~F3~ 과 ~C-x C-k TAB~ 은 모두 카운터 값을 삽입하고 1 을 더하지만, 범용 인자 ~C-u~ 를 지정하면 마지막 숫자를 삽입하고 카운터를 증가시키지 않습니다. 이는 같은 숫자를 연속해서 여러 번 사용할 때 유용합니다.

#+BEGIN_QUOTE
*Counter Resets & Registers* :
카운터는 사용자가 명시적으로 초기화하거나
새로운 매크로를 기록할 때만 초기화됩니다.

카운터 값은 매크로 재생 사이에도 유지됩니다.

마찬가지로, 원한다면 Emacs의 레지스터를 사용해서
값을 추적하거나 더하거나 뺄 수도 있습니다.

레지스터는 매크로 메커니즘과 독립적으로 작동하며,
매크로가 초기화될 때 함께 초기화되지 않습니다.
#+END_QUOTE

~C-x C-k C-c~ 명령은 ~C-x C-k C-a~ 같이 단순히 카운터를 증가시키는 것과 달리, 카운터를 명시적으로 설정합니다. 마지막으로, ~C-x C-k C-f~ 는 아마 카운터 명령 중 가장 고급 기능일 것입니다. 이 명령은 포맷 문자열을 받아 이 문자열에 따라 카운터를 포맷팅합니다(포맷 문자열에 대한 자세한 내용은 ~C-h f format~ 을 입력합니다). 예를 들어, 숫자를 10진수로 변환하거나 앞뒤에 0을 채워 출력할 수 있으며, 단순한 숫자와 텍스트를 삽입하는 등 이와 유사한 작업도 가능합니다. ~C-x C-k C-c~ 에 전달하는 텍스트를 따옴표로 묶지 않도록 주의하시기 바랍니다. 따옴표는 자동으로 이스케이프 처리됩니다.

가장 눈에 띄는 명령은 ~C-x C-k q~ (또는 간단히 ~C-x q~)입니다. 이 명령을 호출하면, Emacs는 매크로 기록에서 해당 단계를 표시하고 계속 진행하기 전에 사용자에게 조언을 요청합니다. 즉, 매크로를 일시적으로 중지하고 사용자에게 프롬프트를 표시하는 것입니다.

| Query 키 바인딩 | 설명                              |
|-----------------+-----------------------------------|
| ~y~             | 평소대로 계속 진행                |
| ~n, DEL~        | 매크로의 나머지 부분을 건너뜁니다 |
| ~RET~           | 매크로를 완전히 중지합니다        |
| ~C-l~           | 화면을 중앙에 맞춥니다            |
| ~C-r~           | 재귀 편집 모드로 들어갑니다       |
| ~C-M-c~         | 재귀 편집 모드를 종료합니다       |

~y~ 와 ~n~ 은 현재 매크로의 반복을 계속하거나 중지합니다. 따라서, 연속해서 여러 매크로를 실행 중인 경우, ~N~ 을 누르면 나머지 매크로를 건너뛰고 해당 매크로의 시작 부분에서 다시 시작합니다. ~Y~ 는 그저 평소처럼 실행을 계속합니다. ~RET~ 는 매크로를 완전히 중지하고 이후의 매크로 재생을 멈춥니다.

화면을 다시 중앙에 맞출 수 있습니다. 이는 일반적인 ~C-l~ 명령과 다르며, Emacs는 커서를 버퍼 중앙에 위치시킵니다.

*재귀 편집* : 재귀 편집은 고급 주제입니다. 재귀 편집(~C-r~) 모드로 진입하면, Emacs는 Isearch, 검색 및 바꾸기 또는 매크로 같은 현재 진행 중인 명령을 일시 중지하고 제어권을 사용자에게 돌려줍니다. 그러면 사용자는 평소와 같이 편집을 계속하거나 Emacs를 사용할 수 있지만, 언제든지 ~C-M-c~ 를 입력하면 Emacs는 사용자가 진입했던 이전 재귀 단계로 즉시 돌아가서 그 지점부터 작업을 재개합니다. 재귀 편집은 합리적인 범위 내에서 원하는 만큼 중첩할 수 있으며, 재귀 편집 상태일 때는 모드라인에 대괄호([])가 표시되어 이를 확인할 수 있습니다. ~ESC ESC ESC~ 를 입력하면 Emacs가 모든 재귀 편집 레벨을 강제로 종료하게 할 수 있습니다. 다른 대부분의 경우와 달리, ~C-g~ 는 재귀 편집에서 빠져나오지 않는다는 점에 유의하시기 바랍니다.

그렇다면 실제로는 어떻게 사용할까요? 한 가지 예로, 검색이나 매크로 재생 중에 텍스트를 편집하거나, 이메일을 보내거나, 현재 작업을 일시적으로 중단할 필요가 있다는 것을 깨달았을 때를 들 수 있습니다. ~C-r~ 을 사용하면 이를 수행할 수 있습니다. 작업이 모두 끝나면 ~C-M-c~ 를 입력해서 중단 지점부터 다시 이어갈 수 있습니다. 이것은 매우 강력한 기능으로, 이 책의 다른 모든 내용을 마스터한 후에 알아두면 유용합니다.


**** Saving and Recalling
매크로는 Emacs의 다른 부분(킬링 링이나 되돌리기 링 등)에서 익숙하게 접했을 법한 개념인 매크로 링에 저장됩니다. 새 매크로를 생성하면 별도의 조치 없이도 기존 매크로가 자동으로 매크로 링에 저장됩니다. 아래 명령어를 사용하면 매크로 링에 매크로를 저장하고 불러올 수 있으며, 매크로를 편집하고 키에 바인딩하는 등의 작업을 수행할 수 있습니다.

| 키 바인딩              | 설명                           |
|------------------------+--------------------------------|
| ~C-x C-k C-n~          | 매크로 링을 다음 항목으로 순환 |
| ~C-x C-k C-p~          | 매크로 링을 이전 항목으로 순환 |
| ~C-x C-k n~            | 마지막 매크로에 이름 지정      |
| ~C-x C-k b~            | 마지막 매크로를 키에 바인딩    |
| ~C-x C-k e~            | 마지막 매크로 편집             |
| ~C-x C-k l~            | 최근 300개의 키 입력 편집      |
| ~M-x insert-kbd-macro~ | 매크로를 elisp 코드로 삽입     |

~C-x C-k C-n~ 과 ~C-x C-k C-p~ 모두 매크로 링을 순환합니다. 이 작업을 수행하면 Emacs가 현재 활성화된 매크로가 어느 것인지 알 수 있도록 매크로의 일부를 표시해 줍니다.

~C-x C-k n~ 을 사용해서 매크로에 이름을 지정할 수 있습니다. 매크로를 파일에 저장하려면 먼저 이 작업을 수행해야 합니다. 사용자 init 파일을 열고 ~M-x insert-kbd-macro~ 를 호출하면 Emacs가 코드 생성된 버전의 매크로를 삽입해 줍니다. 이름이 지정되고 삽입된 매크로는 ~M-x~ 를 사용해서 호출할 수 있는 명령으로 변환됩니다. 또한 ~C-x C-k b~ 를 사용해서 현재 세션 동안만 일시적으로 키에 매핑할 수도 있습니다.

#+BEGIN_QUOTE
*Naming Things* :
일관된 명명 규칙을 정하는 것을 추천합니다.
LISP는 공백을 사용할 수 없지만 그 외의 거의 모든 문자를 사용할 수 있습니다.
하지만, 저는 항상 제 이니셜인 ‘mp-’ 로 시작하는데, 이렇게 하면
~C-h a~ 및 관련 단축키들과 결합할 수 있기 때문입니다.

이제 Emacs의 자체 문서화 기능을 통해
제가 직접 만든 모든 명령어를 쉽게 찾을 수 있습니다.
#+END_QUOTE

실수를 했다면 기존 매크로를 편집할 수 있습니다. ~C-x C-k e~ 명령을 실행하면 매크로 명령어 목록이 표시되며, 이 목록을 일반 텍스트처럼 편집할 수 있습니다. ~C-c C-c~ 를 눌러 변경 사항을 적용할 수 있습니다.

#+BEGIN_QUOTE
*Lossage* :
Emacs는 사용자가 입력한 마지막 300개의 문자와 명령을
‘lossage’ 라고 하며 기억합니다.
~C-h l~ 을 입력하면 이 문자 목록을 확인할 수 있습니다.

~M-x open-dribble-file~ 을 입력하면 Emacs에서 입력한
모든 키 입력을 저장할 수도 있습니다.
단, 비밀번호 같은 민감한 정보도 포함되므로 주의해야 합니다.

lossage 는 키 입력이 속한 명령도 함께 표시합니다.
버퍼의 활성 모드 같은 요소에 따라 키가 속한 명령은 달라질 수 있습니다.
따라서, 해당 키가 실행된 버퍼나 모드 외부에서 키를 조회할 때는
이런 점에 유의하시기 바랍니다.

키보드 매크로를 소급해서 생성하고 싶을 때는 lossage 기능을 활용합니다.
~M-x kmacro-edit-lossage~ 명령을 사용하면 입력 내용을 기반으로
매크로를 생성할 수 있습니다.
#+END_QUOTE


**** Practical Uses for Keyboard Macros
키보드 매크로라 하면 가장 먼저 떠오르는 것은 단순한 텍스트 자동화지만, Emacs의 매크로 시스템은 그보다 훨씬 더 많은 기능을 갖추고 있습니다.

간과되기 쉬운 한 가지 측면은 여러 복잡한 작업을 결합한 뒤, 나중에 재사용할 수 있도록 매크로에 이름을 지정하고 저장할 수 있다는 점입니다. 이 기능 자체만으로는 그리 놀랍거나 주목할 만한 특징으로 보이지 않을 수 있습니다. 하지만, 매크로 없이는 (아직 갖추지 못했을 수도 있는!) 심도 있는 Emacs나 elisp 지식이 필요한 수많은 지루한 작업을 매크로를 통해 원활하게 처리할 수 있다는 사실을 깨닫게 되면 이야기가 달라집니다.

*원하는 대로 창 환경을 설정하는 방법* : 특정 파일을 열어 특정 방향으로 표시하려면, 키보드 매크로를 사용하면 됩니다. 먼저 ~C-x 1~ 을 눌러 창을 모두 비운 다음, 매크로를 사용해서 원하는 파일을 엽니다. 원하는 대로 창을 분할하고 관심 있는 버퍼로 전환한 후, 매크로를 종료하면 됩니다. 이제 원할 때마다 이 설정을 자유롭게 불러올 수 있습니다.

*자주 사용하는 텍스트 편집 작업을 위한 매크로 작성* : 일괄 변경하고 싶은 텍스트 패턴이 있거나, 그날의 작업량에 따라 반동적으로 처리하고 싶을 수도 있습니다. 예를 들어, ~M-x rgrep~ 을 사용해서 변경할 파일들을 찾아내고, 키보드 매크로를 사용해서 ~*grep*~ 버퍼의 각 항목을 순차적으로 처리하면서 검색 및 교체 패턴을 적용할 수 있습니다.

단순히 녹화를 시작하고 ~M-g M-n~ 을 입력해서 Emacs가 결과를 가져오는 소스에서 다음 일치 항목을 선택하고, 텍스트 편집을 수행한 후 녹화를 종료하면 됩니다. 이제 ~C-x e~ 를 사용해서 매크로를 호출할 때마다 항목이 하나씩 처리되며, 이 방식은 매우 일반적이라서 grep 대신 ~occur, M-x compile~ 및 ~M-g M-n / M-g M-p~ 를 사용하는 다른 소스를 대체할 수 있습니다.

*복잡한 결정은 사람이 내리도록 미룹니다* : ~C-x C-k q~ 를 사용해서 쿼리 단계를 삽입할 수 있으므로, 매크로가 진행되기 전에 모호하거나 복잡한 선택 사항이 있다는 것을 알고 있다면, 매크로의 주요 지점에서 이를 자유롭게 삽입해서 매크로를 중단할지, 변경 사항을 건너뛸지, 아니면 재귀적 편집 레이어로 들어가서 버퍼를 수동으로 편집한 후 매크로를 계속할지 결정할 수 있습니다. 심지어 포인트를 이동하거나, 재개하기 전에 버퍼 텍스트를 변경할 수도 있습니다.

*매크로 내에서 매크로 호출* : 매크로 내에서 매크로를 호출할 수 있습니다. 그러니 작고 재사용 가능한 매크로 로직 조각들을 만들어 두고, 이를 호출하는 매크로를 하나 만들어 보는 건 어떨까요? 이름을 지어두면–이름이 없더라도 매크로 링을 사용하면– 원할 때 언제든지 호출할 수 있습니다.

*프롬프트에 적절한 기본값 채우기* : 같은 명령을 반복 입력할 경우, 이를 간단한 키보드 매크로로 만들 수 있습니다. 프롬프트에 쿼리 마커를 삽입하고, ~C-r~ 을 눌러 재귀 편집 모드로 진입해서 녹화 시 입력한 기본값을 덮어쓸 수 있습니다. 프롬프트에 입력한 내용을 수정한 후, ~C-M-c~ 를 눌러 매크로로 돌아갈 수 있습니다. Emacs는 프롬프트에 있더라도 실행 중인 매크로를 매끄럽게 수정할 수 있게 해줍니다. 프롬프트는 미니버퍼에 표시되는데, 미니버퍼 역시 버퍼입니다. 이는 Emacs 전반에 걸쳐 개념의 대칭성과 재사용성을 다시 한번 강조해 줍니다.

매크로는 배울 가치가 충분하며, 보시다시피 엘리스프(Elisp)나 사용자 정의 설정만으로는 문제를 해결하는 방법을 모를 때 유연한 대안이 될 수 있습니다. 다만, Emacs와 직접 상호작용해서 사람이 직접 수행할 수 있는 작업이라면, 매크로를 기록해 두면 Emacs가 이를 반복해 줄 수 있다는 점을 기억해 두시기 바랍니다.



** Text Expansion 
Emacs는 텍스트를 확장해 주는 여러 가지 내장 도구와 그만큼 많은 타사 도구가 있습니다. 이들 모두의 용도는 약간씩 다르지만, 목표는 타이핑을 최소화하고 자동화를 극대화하는 것입니다.

다음은 Emacs에서 사용할 수 있는 도구들 중 일부입니다:

*Abbrev*: 모드별 또는 전역 수준에서 func 를 function 같이 약어 확장합니다. 매우 단순한 확장 메커니즘으로, 주요 장점은 사용자가 입력하는 동안 눈에 띄지 않게 작동하며 오타를 수정하거나 약어를 확장해 준다는 점입니다. Emacs의 다른 많은 기능과 마찬가지로, 이 기능도 화려한 그래픽 효과는 거의 없습니다. 키보드 단축키를 확장할 때 사용자의 주의를 산만하게 하는 회전하는 그래픽이나 기타 시각적 잡음은 없습니다. 사실, 일부러 찾지 않는 한 전혀 눈치채지 못할 가능성이 높습니다.

일반적으로 오타 수정 같이 의미상 모호함이 없는 교정을 위해 이 기능을 사용합니다.

*DAbbrev, 또는 동적 약어* : Abbrev 와 유사하지만, 커서 위치의 단어가 무엇으로 확장될 수 있는지 동적으로 검색해서 이전 단어를 확장합니다. 예를 들어, 함수 정의가 많이 있는 버퍼에서 func 를 입력하면, 확장 메커니즘을 수동으로 실행했을 때 DAbbrev 가 이를 자동으로 function 으로 확장해 줍니다.

*Hippie expand* : 단어뿐만 아니라 전체 줄, Lisp 심볼, Abbrev 약어, 파일 이름 및 파일 경로까지 확장하는, DAbbrev 를 대체하는 강력한 기능입니다. 이 기능은 매우 강력하며, Emacs에 기본으로 포함된 DAbbrev 를 곧바로 대체할 수 있습니다.

*Skeletons* : 프롬프트, 영역 감싸기, 들여쓰기, 포인트 위치 지정 같은 간단한 elisp 기본 기능들을 Abbrev 와 유사한 확장 기능과 결합한 복잡한 템플릿 도구입니다. 20년 넘게 Emacs의 핵심 기능으로 자리 잡아 왔음에도 거의 사용되지 않습니다. 정말 안타까운 일입니다. 매우 강력한 도구지만, 사용하려면 인내심이나 Elisp 지식이 필요하기 때문에 거의 아무도 사용하지 않았습니다.

*Tempo* : Emacs에 기본으로 포함된 또 다른 템플릿 도구입니다. Skeletons 과 유사합니다.

*YASnippet* : 텍스트 에디터 TextMate 의 템플릿 도구에서 영감받은 타사 패키지 템플릿 도구입니다. (물론 TextMate 자체도 그 이전의 다른 도구로부터 많은 부분을 차용했습니다.) 간단한 템플릿 언어를 사용해서 탭이나 공백 키로 호출할 수 있는 스니펫을 생성하고, 이를 편집 가능한 템플릿으로 확장할 수 있습니다. Skeletons 과 유사하지만 사용하기 훨씬 더 쉽다고 할 수 있습니다.

*Autoinsert* :  특정 파일 형식과 일치하는 새 파일을 생성할 때 Skeletons 과 유사하게 템플릿을 삽입합니다. html, head 같은 HTML 파일의 기본 내용을 자동으로 생성할 때 유용합니다.

위의 모든 선택지 중에서, 저는 템플릿 작업에는 ~YAsnippet~ 에 주목할 것입니다. 이 도구는 메이저 모드들을 위한 다양한 스니펫을 제공하며, 생산성을 크게 높여주는 ~Hippie Expand~ 도 주목할 만합니다.

특별한 이유가 없다면, 현재로는 Tempo 나 Skeletons 을 배울 가치는 없습니다. Abbrev 는 앞서 언급한 고급 텍스트 확장 도구들의 기능을 갖추지 못했기 때문에 단어 대체 용도로만 적합합니다. YASnippet 과 Hippie Expand 를 작업 흐름에 통합한 후에는, 필요하다고 느껴진다면 Abbrev 와 Autoinsert 를 추가할 수 있습니다.


*** Abbrev
Abbrev 는 워드 프로세서의 자동 수정 기능에 안성맞춤인 도구입니다. 저는 이 도구를 사용해서 흔히 틀리는 철자를 수정하거나, ‘resume’ 같은 단어를 ‘résumé’ 로 바꾸곤 합니다. 하지만, 소프트웨어 개발에서 사용하는 복잡한 텍스트 확장 같은 고급 기능을 원한다면, 이 도구는 분명 적합하지 않습니다.

abbrev 가 효과적인 이유 중 하나는 단순함에 있습니다. 이 도구는 시각적인 방해 요소 없이 단어를 확장해 주며, 사실 저는 단어가 수정되는 것을 거의 눈치채지 못합니다.

| 키 바인딩   | 설명               |
|-------------+--------------------|
| ~C-x a l~   | 모드별 약어 추가   |
| ~C-x a g~   | 전역 약어 추가     |
| ~C-x a i l~ | 모드별 역약어 추가 |
| ~C-x a i g~ | 전역 역약어 추가   |

~C-x a g~ 또는 ~C-x a l~ 로 약어를 추가할 때, Emacs는 커서 위치 바로 앞의 단어를 확인해서 이를 대체 단어로 사용합니다. 즉, 저조차 헷갈리긴 하지만, ‘트리거 단어’ 가 아니라 ‘확장하려는 단어’ 를 사용한다는 뜻입니다. 따라서, resume 을 résumé 로 바꾸려면, résumé 를 입력한 뒤 커서를 단어 뒤에 두고, ~C-x a g~ 를 누른 다음 resume 을 입력합니다. resume 을 입력한 후 스페이스 바를 누르면, Emacs는 이를 ~résumé~ 로 바꿔줍니다.

반대(역) 명령은 정반대의 동작을 합니다. resume 을 입력하고 ~C-x a i g~ 를 누른 뒤, résumé 라고 대답하면 Emacs는 resume 을 résumé 로 확장해 줍니다.


*** DAbbrev and Hippie Expand
Hippie Expand 는 정말 훌륭합니다. 이 도구는 특정 지점의 텍스트를 사용자가 의도하는 내용으로 확장해 주는, 거의 초자연적인 능력을 갖고 있습니다. Hippie Expand 에 대해 이야기하기 전에, 먼저 Emacs의 기본 동적 약어 도구이자 Hippie Expand 의 동급인 DAbbrev 를 어떻게 사용하는지 살펴보겠습니다:

| 키 바인딩 | 설명                      |
|-----------+---------------------------|
| ~M-/~     | 해당 위치에서 단어를 확장 |
| ~C-M-/~   | 확장 후 완성 후보 표시    |

~M-/~ 키는 입력하기 쉬우며, 이 키를 반복해서 누르면 제안된 단어 목록을 순차적으로 확인할 수 있습니다. 명령을 충분히 반복하면 원래 단어로 되돌아갑니다. 또한 선택지가 많을 경우, ~C-M-/~ 명령은 가능한 한 많이 자동 완성하고, 여전히 선택지가 하나 이상 남아 있으면 완성 후보 목록을 표시합니다.

DAbbrev 는 스마트하지 않습니다. 버퍼에 있는 다른 단어들을 살펴보고, 현재 위치의 단어를 그 중 하나로 완성하려고 시도합니다. 그렇다고 해서 이 기능이 쓸모없다는 것은 아닙니다. 나름의 용도가 있긴 하지만, Hippie Expand 가 훨씬 더 낫다는 뜻입니다.

Hippie Expand 를 효과적으로 사용하려면 DAbbrev 를 대체해야 합니다. 두 기능을 함께 사용할 수 있지만, 사실 서로 전혀 보완적이진 않기 때문입니다. 다음을 init 파일에 추가해서 Hippie Expand 로 전환합니다:

~(global-set-key [remap dabbrev-expand] 'hippie-expand)~

Hippie Expand 는 단순한 단어 확장 그 이상을 수행합니다. 변수 ~hippie-expand-try-functions-list~ 는 ~M-/~ 을 호출할 때 커서 위치의 텍스트를 인수로 받아 Hippie Expand 가 호출할 확장 함수들의 정렬된 목록입니다.

Hippie Expand 에서 제가 가장 마음에 드는 점은 파일 이름 자동 완성 기능입니다. 이 기능은 셸의 TAB 자동 완성 방식과 똑같이 작동합니다. ~M-/~ 을 입력하면 Hippie Expand 가 현재 위치의 파일 이름이나 디렉터리를 자동 완성해 줍니다. 코드, 설정 파일, 또는 문서에 절대 경로나 상대 경로의 파일 이름을 삽입할 일이 있다면—Hippie Expand 가 여러분의 작업을 훨씬 수월하게 만들어 줄 것입니다.

또 다른 훌륭한 기능은 전체 줄을 완성해 준다는 점입니다. 완성할 항목이 없을 경우 단어 완성으로 전환되며, Elisp을 자주 작성한다면 Hippie Expand 는 커서 위치의 텍스트가 Elisp 심볼일 가능성을 추측해서 자동으로 완성해 줍니다.

DAbbrev 와 마찬가지로, ~M-/~ 을 반복 호출하면 모든 가능한 일치 항목을 순환하면서 확인하지만, ~C-M-/~ 은 DAbbrev 가 찾은 완성 항목만 표시합니다. Hippie Expand 는 이에 상응하는 완성 목록이 없습니다.

~M-/~ 을 능숙하게 사용하려면 약간의 연습이 필요합니다. 호출 시 적용되는 확장 규칙에 대한 감각을 키워야 합니다. Hippie Expand 는 시간을 크게 절약해 주므로 배우는 데 투자할 가치는 충분합니다.


**** Customizing Hippie Expand
Hippie Expand 가 텍스트를 확장하는 방식을 변경할 수 있습니다. 이를 위해서는 ~hippie-expand-try-functions-list~ 변수를 사용자 정의하면 되지만, 새로운 try 함수를 추가하려면 해당 함수 이름을 알아야 합니다.

try 함수 목록을 찾으려면 다음을 수행합니다:

- 소스 코드의 주석을 읽습니다(~M-x find-library~ 를 실행한 후, hippie-exp 를 입력하고 문서를 읽습니다). 하지만, 라이브러리 이름은 어떻게 찾을 수 있을까요? 좋은 방법은 명령어(~hippie-expand~)를 설명(describe)해 보는 것입니다. 그러면 Emacs가 해당 심볼을 찾은 라이브러리의 이름을 알려줄 것입니다.

- Apropos 를 사용합니다. try 함수의 이름을 살펴보고 ~M-x apropos-function~ 을 사용해서 유사한 함수를 검색합니다.

항상 그렇듯이 두 방법 모두 다른 결과를 보여주므로 두 가지 모두 시도해 보시기 바랍니다.


** Indenting Text and Code
새로운 프로그래밍 언어가 등장하면, 기본적인 구문 강조와 들여쓰기 기능을 제공하는 Emacs의 메이저 모드가 거의 동시에 등장합니다. 이것이 가능한 이유 중 하나는 다른 메이저 모드의 들여쓰기 엔진을 상속(또는 재사용)할 수 있을 뿐만 아니라, Emacs에 내장된 일반적인 들여쓰기 엔진도 활용할 수 있기 때문입니다.

기본적으로 Emacs는 사용자가 실행 중인 메이저 모드의 규칙에 따라 들여쓰기를 시도합니다. 구버전 Emacs는 이를 위해 직접 설정해야 했는데, 기본적으로 인덴트를 적용하는 경우가 드물었기 때문에 초보자는 답답한 경험이었습니다. 하지만, 오늘날에는 더 이상 문제가 되지 않습니다. Emacs는 '전기 인덴트(electric indentation)' 라고 불리는 기능을 사용해서 인덴트를 자동으로 적용합니다. 이 기능을 끄려면 ~electric-indent-mode~ 를 사용자 정의할 수 있습니다.

들여쓰기 엔진이 정확히 어떻게 작동하는지는 메이저 모드와 개발자의 취향 및 개인적인 선호도에 따라 결정됩니다. 특히 C 계열 언어로 코딩할 때 들여쓰기 방식이 마음에 들지 않을 수도 있습니다. 이 경우 Emacs 매뉴얼(해당 메이저 모드가 Emacs에 포함된 경우)이나 소스 파일 내의 문서 또는 주석을 참고해야 합니다. Emacs는 들여쓰기 사용자 지정을 위한 일률적인 접근 방식이 없습니다. 이를 수행하는 방법에 대한 지침은 문서를 참조해야 합니다.


*** TAB : Indenting the Current Line
~TAB~ 키를 누르면, Emacs는 보통 ~indent-for-tab-command~ 를 호출합니다. 이 명령은 코드를 들여쓰기하거나, 커서 위치의 단어를 ~TAB~ 자동 완성하려고 시도하는 일반적인 대리 명령입니다.

| 키 및 명령어         | 설명                                                 |
|----------------------+------------------------------------------------------|
| ~TAB~                | 메이저 모드의 들여쓰기 명령을 사용해서 줄을 들여쓰기 |
| ~M-i~                | 다음 탭 정지 위치에 공백이나 탭을 삽입               |
| ~M-x edit-tab-stops~ | 탭 정지 위치를 편집                                  |

일부 메이저 모드(major mode)는 ~TAB~ 키의 동작을 재정의하고 대신 자신만의 특화된 들여쓰기 명령을 호출합니다. 대표적인 예로 C 메이저 모드가 있습니다. 하지만, ~TAB~ 키를 누르면 (또는 ~M-x indent-for-tab-command~)을 누르면, 해당 모드의 휴리스틱이 들여쓰기 한다고 판단할 경우, ~indent-line-function~ 변수에 저장된 들여쓰기 함수를 호출합니다. 여기서 장점은 ~indent-for-tab-command~ 의 일반적인 성격에 있습니다—이 명령은 단순히 작업을 완성 명령이나 들여쓰기 명령 중 하나로 전달하기 위해 존재합니다.

~tab-always-indent~ 변수는 ~TAB~ 키를 누를 때 Emacs의 동작을 제어합니다. 일반적으로 단순히 들여쓰기만 수행하지만, 드물게 사용되기는 하지만 자동 완성 메커니즘도 갖추고 있습니다.

#+BEGIN_QUOTE
*Disabling tab characters* :
탭 문자 사용을 원치 않고 공백을 선호한다면,
~indent-tabs-mode~ 변수를 사용자 지정합니다. 
#+END_QUOTE

마지막으로, Emacs가 들여쓰기를 할 때는 앞서 언급한 ~indent-line-function~ 내의 함수를 호출합니다. 기본 함수는 ~indent-relative~ 로, 실제 탭 문자를 삽입하는 명령어입니다. ~text-mode~ 나 ~fundamental-mode~ (새로 생성된 빈 버퍼의 기본 모드) 같은 모드들은 ~indent-relative~ 를 사용합니다. 대부분의 프로그래밍 모드들은 그렇지 않습니다.

#+BEGIN_QUOTE
*Changing the amount of indentation* :
~tab-width~ 변수는 각 탭이 차지하는 공백의 문자 수를 제어합니다.
또한 ~indent-tabs-mode~ 를 비활성화한 경우 사용할 공백의 양도 제어합니다. 
#+END_QUOTE

Emacs는 탭 정지점(tab stop)이라는 개념도 있는데, ~M-x edit-tab-stops~ 을 입력하고 Emacs가 탭 포인트를 설정할 위치에 ~:~ 문자를 삽입하면 탭 정지점을 편집할 수 있습니다. 이후 ~M-i~ 를 호출하면(이 명령은 ~M-x tab-to-tab-stop~ 을 호출합니다), 공백과 탭 문자를 사용해서 탭 정지점이 삽입됩니다.


*** Indenting Regions
리전(region) 들여쓰기는 훨씬 더 까다롭습니다. 블록 들여쓰기가 프로그램의 흐름을 결정하는 상황에서, 파이썬 코드의 리전을 어떻게 안전하게 들여쓰면 될까요? 정답은 —그냥 하지 않는 것입니다. 영역 들여쓰기 명령은 두 가지 유형이 있습니다. 메이저 모드의 들여쓰기 엔진에 조언을 구하는 “지능형” 명령—HTML이나 C 같은 언어는 잘 작동하지만— 그리고 그 외의 경우를 위한 평범한 고정 폭 들여쓰기입니다.

| 키 및 명령어 | 설명                                                              |
|--------------+-------------------------------------------------------------------|
| ~TAB~        | 메이저 모드에 따라 줄이나 영역의 들여쓰기를 조정합니다            |
| ~C-M-\~      | 메이저 모드의 영역 들여쓰기 명령을 사용해서 들여쓰기를 조정합니다 |
| ~C-x TAB~    | 고정된 들여쓰기를 적용합니다                                      |

이상적인 환경에서는, 선택 영역이 활성화된 상태에서 ~TAB~ 키를 누르면 들여쓰기를 다시 설정할 수 있습니다. 안타깝게도, Emacs가 이를 지원하지 않을 수도 있고, 일부 프로그래밍 언어는 올바른 들여쓰기 위치를 물리적으로 파악하는 것이 불가능할 수도 있습니다. ~TAB~ 키를 누르는 것은 줄 들여쓰기와 거의 동일한 규칙을 따릅니다. Emacs는 ~indent-line-function~ 에 따라 들여쓰기를 시도하며, 이것이 실패할 경우 단순히 ~TAB~ 문자를 삽입합니다(또는 ~indent-tabs-mode~ 를 비활성화한 경우 공백을 삽입합니다).

~C-M-\~ 를 입력하면 해당 영역을 명시적으로 들여쓰기합니다. 일부 모드는 ~TAB~ 과 동일하게 작동하지만, 다른 모드는 그렇지 않습니다. 명령에 숫자 인수를 지정하면, 해당 열(즉, 문자 수)만큼 영역을 들여쓰고, Emacs는 (설정되어 있다면) fill prefix 도 사용해서 그에 따라 텍스트를 채웁니다. ~C-M-\~ 는 fill prefix 를 존중하므로 사용해 볼 가치가 있습니다. 하지만, 고정된 열 수만큼 들여쓰기하려면 ~C-x TAB~ 을 사용해야 합니다.

~C-x TAB~ 은 영역을 특정 열의 수만큼 명시적으로 들여쓰기합니다. 이 명령은 음수 및 숫자 인자도 받습니다. 하지만, 인자를 전달하지 않으면, Emacs는 화살표 키로 제어되는 들여쓰기 모드로 전환되어 ~S-<left>~ 와 ~S-<right>~ 를 사용해서 영역을 대화식으로 들여쓰게 해줍니다.



** Sorting and Aligning
텍스트 정렬과 배열은 모두 매우 흔한 작업이라 Emacs는 이 두 가지 기능을 모두 수행하는 전용 명령어 세트가 마련되어 있습니다.


*** Sorting
Emacs의 정렬 기능은 명령줄 유틸리티 sort 와 유사하게 작동합니다. 모든 명령은 줄 단위로 정렬하지만, 단락 단위 정렬(oneparagraph) 명령만 예외입니다.

| 명령어                    | 설명                                          |
|---------------------------+-----------------------------------------------|
| ~M-x sort-lines~          | 알파벳순으로 정렬                             |
| ~M-x sort-fields~         | 필드를 사전순으로 정렬                        |
| ~M-x sort-numeric-fields~ | 필드를 숫자순으로 정렬                        |
| ~M-x sort-columns~        | 열을 알파벳순으로 정렬                        |
| ~M-x sort-paragraphs~     | 단락을 알파벳순으로 정렬,                     |
| ~M-x sort-regexp-fields~  | 정규 표현식으로 정의된 필드를 사전순으로 정렬 |

~M-x sort-lines~ 는 오름차순으로 정렬하지만, 범용 인수를 지정해서 호출하면 정렬 순서가 반대로 바뀝니다.

줄 단위로 정렬할 때, Windows 환경이 아닌 한 Emacs는 (속도가 훨씬 빠르기 때문에) sort 함수를 호출하지만, Microsoft Windows 환경에는 Emacs가 내부적으로 정렬을 수행합니다.

#+BEGIN_QUOTE
*Lexicographic and numeric* :
사전순 정렬은 대부분의 정렬 알고리즘이 일반적으로 작동하는 방식입니다.
이 알고리즘들은 각 문자의 문자 코드를 확인해서 그 순서대로 정렬합니다.

이는 숫자를 제외하고는 대부분의 경우에 잘 작동합니다.
사전순으로 볼 때, 숫자 4는 숫자 23보다 뒤에 옵니다.
왜냐하면, 4의 서수가 23의 서수 2보다 크기 때문입니다.

숫자를 올바르게 정렬하려면 ~M-x sort-numeric-fields~ 를 사용해야 합니다. 
#+END_QUOTE

~M-x sort-fields~ 및 ~M-x sort-numeric-fields~ 를 사용해서 사전순 또는 숫자순으로 정렬할 수 있습니다. 단, 정렬할 열을 지정해야 합니다. 이를 위해 숫자 인자(1부터 시작)를 전달해서 해당 열로 정렬합니다. 열은 공백으로 구분되며, 하나 이상의 공백이 연속되어 나오면 열 구분자로 간주됩니다.

세 번째 열을 정렬하려면 ~M-3 M-x sort-fields~ 를 입력합니다. 한 번에 하나의 열만 정렬할 수 있으며, 앞서 언급했듯이 각 열은 공백으로 구분되어야 합니다. 열 구분자를 변경하려면 ~M-x sort-regexp-fields~ 를 사용해야 합니다.

~M-x sort-columns~ 을 사용해서 열별로 정렬하는 것이 두 개 이상의 열로 정렬할 수 있는 유일한 방법이며, 이 경우 연속된 열만 정렬할 수 있습니다. 이를 사용하려면 정렬하려는 시작 및 끝 열에 커서와 마크를 위치시키면 커서 위치부터 마크까지의 모든 행이 정렬됩니다. 공백으로 구분되지 않은 항목을 정렬할 경우, ~M-x sort-regexp-fields~ 를 사용해야 합니다. 이 명령은 elisp에 대한 탄탄한 실무적 지식이 필요하기 때문에 상당히 복잡합니다. 또한 영역을 부분적으로 정렬하기도 해서 텍스트가 엉망이 될 수 있습니다.

다음과 같은 제품 CSV 파일을 가정합니다:

#+BEGIN_SRC
Price,Product
$3.50,Cappuccino
$4.00,Caramel Latte
$2.00,Americano
$2.30,Macchiato
...
#+END_SRC

이 데이터는 공백으로 구분되지 않았기 때문에 다른 정렬 명령어로는 정렬할 수 없습니다. 이런 데이터를 정렬하려면 ~M-x sort-regexp-fields~ 명령을 사용해야 합니다. Emacs 내부 정렬 루틴은 키(즉, 필드 같이 정렬에 사용하는 기준)와 레코드(일반적으로 전체 줄)가 필요합니다.

위의 예제를 정렬하는 방법은 다음과 같습니다:

#+BEGIN_SRC
M-x sort-regexp-fields

Record: ^\([^,]+\),\([^,]+\)$
Key: \1
#+END_SRC

이 명령은 먼저 레코드를 쉼표로 구분된 두 개의 캡처 그룹(각 열에 하나씩)으로 정의합니다. 다음 단계는 정렬 기준이 될 키(이 경우 가격이 포함된 첫 번째 열)를 선택하는 것입니다.

결과는 다음과 같습니다:

#+BEGIN_SRC
Price,Product
$2.00,Americano
$2.30,Macchiato
$3.50,Cappuccino
$4.00,Caramel Latte
#+END_SRC

정규 표현식을 이용한 정렬은 자주 사용할 일은 아니지만, 필요할 때는 매우 유용한 도구입니다. 한 가지 주의할 점은 한 줄을 부분적으로만 정렬할 수도 있다는 것입니다. 검색 조건이 다음과 같다면:

#+BEGIN_SRC
M-x sort-regexp-fields

Record: ^\([^,]+\)
Key: \1
#+END_SRC

그리고 원본 텍스트를 정렬하면 출력은 다음과 같습니다:

#+BEGIN_SRC
$2.00,Cappuccino
$2.30,Caramel Latte
$3.50,Americano
$4.00,Macchiato
#+END_SRC

첫 번째 열은 정렬되지만, 두 번째 열은 변경되지 않았다는 점에 유의하시기 바랍니다! 즉, 가격은 정렬되지만 관련된 상품명은 정렬되지 않았습니다. 주의하시기 바랍니다.


*** Aligning
Emacs의 텍스트 정렬 기능은 양쪽 정렬과 열 단위 정렬 모두를 포함합니다. 사실, Emacs의 정렬 엔진은 매우 정교해서 정규식 패턴을 기반으로 코드를 자동으로 정렬하거나 양쪽 정렬할 수 있습니다.

| 명령어              | 설명                                  |
|---------------------+---------------------------------------|
| ~M-x align~         | 정렬 규칙에 따라 영역을 정렬합니다.   |
| ~M-x align-current~ | 정렬 규칙에 따라 섹션을 정렬합니다.   |
| ~M-x align-regexp~  | 정규 표현식에 따라 영역을 정렬합니다. |

정렬 명령어는 여러분이 이미 잘 알고 있는 ‘영역(region)’ 대상으로 작동하거나, ~M-x align-current~ 같은 일부 정렬 명령어만 고유하게 적용되는 ‘섹션(section)’ 을 대상으로 작동합니다. 섹션이란 첫 번째 일치하는 정렬 규칙이 적용되는 연속된 줄들의 그룹을 말합니다. 따라서, ~HELLO_WORLD_CONST = “Hello World”;~ 에서 ~=~ 같은 문자열 상수를 정렬하는 규칙이 있다면, 해당 규칙에 부합하는 모든 연속된 줄이 그 규칙의 섹션이 됩니다.

Emacs는 많은 내장 정렬 규칙이 있으며, 텍스트 영역에 ~M-x align~ 을 호출하면 Emacs는 정렬 규칙 목록을 스캔해서 규칙 목록의 모든 기준(메이저 모드, 정렬에 사용할 정규식 등)에 일치하는 첫 번째 규칙을 찾습니다. 안타깝게도 정렬 규칙들은 읽고 이해하기 어렵고, 실질적으로 이 기능이 기대만큼 유용하지 않다는 것을 의미합니다. Emacs의 각 정렬 규칙(~align-rules-list~ 에 저장됨)은 규칙이 어떻게 작동하는지 파악하기 위해 정규 표현식에 대한 깊은 지식과 각 층을 하나씩 뜯어보는 노력이 필요합니다. Emacs 개발자들은 각 정렬 규칙의 작동 방식을 설명하는 문서 문자열을 필수화하지 않음으로써 여기서 기회를 놓쳤습니다.

~M-x align-current~ 의 장점은 영역을 먼저 지정할 필요가 없다는 점입니다. 이 명령은 커서가 위치한 줄 기준으로 어떤 규칙이 적용되는지 파악하고, 인접한 줄에도 (해당 규칙에 부합하는 경우) 이를 적용합니다.

다음은 메이저 모드별로 정리한 Emacs의 내장 규칙 중 일부입니다:

*Python* : 다음과 같이 할당문을 열로 나열할 수 있습니다. ~=~ 의 정렬에 주목합니다:

#+BEGIN_SRC
UNIVERSE_ANSWER_CONST = 42
UNIVERSE_QUESTION     = “What is The Answer ...”
#+END_SRC

*Lisp* : 위의 Python 예제와 거의 동일한 방식으로 알리스(alists)를 열로 정렬할 수 있습니다:

#+BEGIN_SRC
((universe-answer . 42)
 (universe-question . “What is The Answer...”))
#+END_SRC

두 경우 모두, 커서를 각 줄에 위치시킨 후 ~M-x align-current~ 를 입력했더니 Emacs가 어떤 규칙을 적용할지 알아서 처리했습니다.

자동 정렬 기능이 유용하기는 하지만, 사용자의 상황이 Emacs의 정렬 규칙 중 어느 하나와 완벽하게 일치할 가능성은 낮습니다. 그 외의 모든 경우는 Emacs의 유연한 ~M-x align-regexp~ 명령을 사용해서 텍스트를 어떻게 정렬할지 Emacs에 지정해야 합니다.

~M-x align-regexp~ 를 사용할 때 두 가지 작동 모드가 있습니다. 명령을 실행하면 나타나는 초보자 모드와, ~C-u~ 를 함께 눌러 호출할 때 나타나는 복합 모드입니다. 복합 모드를 실제로 사용할 가능성이 있는 유일한 경우는 같은 줄에서 여러 열로 정렬할 때입니다. 한 가지 성가신 점은, 이 기능은 초보자 모드에서 사용할 수 없다는 것입니다.

다음 텍스트를 살펴보겠습니다:

#+BEGIN_SRC
Cappuccino $2.00
Caramel Latte $2.30
Americano $3.50
Macchiato $4.00
#+END_SRC

~M-x align-regexp~ 를 사용해서 텍스트를 열로 나누고 가격을 ~$~ 기호에 맞춰 정렬하려면:

~Align regexp: \$~

출력 결과는 다음과 같습니다:

#+BEGIN_SRC
Cappuccino $2.00
Caramel Latte $2.30
Americano $3.50
Macchiato $4.00
#+END_SRC

여러 열을 정렬하려면 좀 더 어려워집니다. 다음 CSV 텍스트를 살펴보겠습니다:

#+BEGIN_SRC
Price,Product,Qty Sold
$2.00,Cappuccino,289
$2.30,Caramel Latte,109
$3.50,Americano,530
$4.00,Macchiato,20
#+END_SRC

세 열 모두를 정렬하려면 complex 모드를 사용해야 합니다. 따라서, ~C-u M-x align-regexp~ 를 입력합니다. 가장 먼저 눈에 띄는 것은 미리 채워진 제안 사항입니다:

~Complex align using regexp: \(\s-*\)~

이 정규 표현식은 캡처 그룹 내에서 0개 이상의 공백 문자를 일치시킵니다. 이렇게 하는 이유는 정렬하려는 파일에 이미 많은 공백이 있을 수 있기 때문입니다(아마 얼마 전에 정렬을 했으나 텍스트를 수정하면서 정렬이 어긋났을 수 있음). 따라서, Emacs는 정렬하려는 문자 주변의 기존 공백을 일치시키고 캡처한 다음, 올바르게 재정렬해야 합니다. 초보자 모드를 사용할 때, Emacs는 정렬 기준이 될 문자 앞에 해당 정규식을 자동으로 삽입합니다. 즉, 정렬 기준 문자 앞의 모든 공백이 제거된다는 뜻입니다. 따라서, 초보자 모드도 공백 캡처 그룹은 존재합니다.

따라서, ~,~ 를 기준으로 정렬하려면 기존 정규 표현식의 시작 부분이나 끝 부분에 ~,~ 를 추가해야 합니다. 이를 어디에 배치하느냐에 따라 정렬 결과는 달라집니다: 이 기호를 ~,~ 앞에 넣으면 Emacs가 ~,~ 뒤에 열을 맞추기 위한 공백을 삽입합니다.

~,~ 같은 기호를 사용해서 이 작업을 수행하는 것이 좋습니다. 그렇지 않으면 다음과 같이 표시됩니다:

#+BEGIN_SRC
Fooooo     ,Bar
Bizz       ,Buzz
#+END_SRC

이 기호를 ~,~ 뒤에 넣으면 Emacs가 ~,~ 앞에 열을 맞추기 위한 공백을 삽입합니다.

~$~ 같은 기호를 사용해서 이 작업을 수행할 수 있습니다. 그렇지 않으면 다음과 같이 표시됩니다:

#+BEGIN_SRC
Foobar Widget $ 15.00
Fizz Buzz $     10.00
#+END_SRC

따라서, 이 경우 프롬프트에 다음과 같이 답변해야 합니다:

~Complex align using regexp: ,\(\s-*\)~

다음으로 기본 답변을 선택합니다:

~Parenthesis group to modify (justify if negative): 1~

캡처 그룹은 하나뿐이지만, 복합 정렬 작업의 경우 그룹이 하나 이상 있을 수 있습니다.

마지막으로, 간격 설정입니다. Emacs는 ~align-default-spacing~ 을 사용하며, 이 설정은 기본적으로 Emacs가 내부적으로 사용하는 탭 정지점을 따릅니다. 보통 기본값 그대로 두어도 무방하지만, 절대 간격 값을 입력하면 Emacs가 이를 따르도록 시도합니다:

~Amount of spacing (or column if negative): 1~

다음은–아마 여러분이 실제로 신경 쓸만한 부분일텐데–Emacs가 해당 명령을 줄 전체에 걸쳐 반복할지 여부입니다. 모든 ~,~ 기호를 열 단위로 정렬하려면 ‘yes’ 라고 답합니다:

~Repeat throughout the line: yes~

이제 출력은 다음과 같이 표시됩니다:

#+BEGIN_SRC
Price, Product,        Qty Sold
$2.00, Cappuccino,     289
$2.30, Caramel Latte,  109
$3.50, Americano,      530
$4.00, Macchiato,      20
#+END_SRC

Emacs의 정렬 명령어는 강력하고 실용적이어서, 서식이 없는 텍스트나 코드를 다룰 때 유용합니다. 유일한 단점은 한 줄에서 정렬 과정을 두 번 이상 반복하려면 복잡한 모드를 일일이 탐색해야 한다는 점입니다.

#+BEGIN_QUOTE
*Note* :
앞서 말씀드렸듯이, 자주 사용하는 복잡한 명령어들은
매크로로 자동화하는 것이 좋을 수 있는데,
이번 경우가 바로 그런 예시 중 하나일 것입니다!
#+END_QUOTE


** Other Editing Commands

*** Zapping Characters
Kill 명령어는 구조화된 텍스트에서 잘 작동하며, 구문 단위를 대상으로 동작합니다. 하지만, 때로는 임의의 문자를 기준으로 삭제할 때가 있습니다. zap 명령어(~M-z~)는 바로 그 기능을 수행합니다. 이 명령을 호출하면 커서 앞의 단일 문자를 입력하라는 메시지가 표시됩니다. 그러면 zap 은 입력한 문자를 포함해서 그 앞의 문자까지 삭제합니다:

~http://www.example.com/█articles/?id=10~

~/~ 까지 zap 을 실행한 후:

~http://www.example.com/█?id=10~

앞서 설명한 삭제 명령어들과 마찬가지로, 이 명령어도 삭제 링에 추가됩니다. 따라서, 삭제 명령어와 음수 및 숫자 인수를 조합해서 연속적으로 수행할 삭제 횟수와 삭제 방향을 제어할 수 있습니다.

#+BEGIN_QUOTE
*Zap up to char* :
Emacs 28은 이 명령어가 기본으로 내장되어 있지만,
기본적으로 어떤 키와도 연결되지 않습니다.
가능한 키 바인딩 중 하나는 ~M-S-z~ 입니다:

~(global-set-key (kbd “M-S-z”) 'zap-up-to-char)~

하지만, 원할 경우 ~C-z~ 를 재매핑해서
문자까지 위로 이동할 수도 있습니다:

~(global-set-key [remap zap-to-char] 'zap-up-to-char)~
#+END_QUOTE


*** Spell Checking
Emacs에서 맞춤법 검사를 수행하는 방법은 여러 가지가 있으며, 각각 다른 용도에 적합합니다. 놀랍게도 Emacs의 맞춤법 검사는 Emacs 자체에서 수행되지 않습니다. 리눅스의 경우, 선택 가능한 옵션은 aspell 과 ispell 이며, Emacs는 좀 더 빠르고 최신식인 aspell 을 ispell 보다 우선적으로 선택합니다.

| 키 및 명령어             | 설명                                                        |
| ~M-$~                    | 현재 위치의 단어에 대해 맞춤법 검사 수행                    |
| ~M-x flyspell-mode~      | 맞춤법 오류를 강조 표시하는 마이너 모드                     |
| ~M-x flyspell-prog-mode~ | 위와 동일하지만, 코드 내의 문자열과 문서 문자열만 강조 표시 |
| ~M-x ispell-buffer~      | 버퍼에 대해 맞춤법 검사 수행                                |
| ~M-x ispell-region~      | 선택한 영역에 대해 맞춤법 검사 수행                         |

어떤 맞춤법 검사기를 사용하든, Emacs는 둘 다 ispell 로 부릅니다.

#+BEGIN_QUOTE
*Spell checking on Windows* :
이 기능을 사용하려면 Windows에 aspell 또는 ispell 을 직접 설치해야 합니다.
#+END_QUOTE

저는 대충 수정할 때는 ~M-$~ 를 자주 사용합니다. 이 기능을 사용하면 Emacs가 해당 단어가 올바른지 아닌지 알려줍니다. 만약 Emacs가 틀렸다고 판단하면, 선택할 수 있는 제안 목록을 표시하고 원래 단어를 대체해 줍니다.

Flyspell 모드는 워드 프로세서의 인라인 맞춤법 검사기와 동일하게 작동합니다—맞춤법이 틀린 단어는 물결선으로 강조 표시됩니다. 하지만, 이 모드는 텍스트용으로 설계되었을 뿐 코드를 위한 것은 아닙니다. 코드의 경우, 맞춤법 검사를 주석, 문자열 및 doc string 으로 제한하는 ~M-x flyspell-prog-mode~ 를 사용합니다. 이 또한 매우 유용한 기능입니다.

두 Flyspell 마이너 모드 중 하나를 활성화하면, ~C-M-i~ (및 ~C-.~ )에 바인딩된 보조 명령도 함께 활성화되어 커서 위치의 단어를 자동으로 수정해 줍니다. 이 명령은 가장 가능성이 높은 첫 번째 일치 항목을 선택해서 커서 위치의 단어를 수정하며, 이후 호출 시 단어 목록을 순차적으로 순환합니다. 이는 어떤 수정 항목을 선택할지 묻는 ~M-$~ 보다 훨씬 더 빠릅니다.

*사용자 정의* : 이 기능을 자주 사용한다면, 특히 ispell 그룹을 사용자 정의해서 기본 사전 외의 특정 사전을 사용할 경우, 이 기능을 사용자 정의할 것을 권장합니다.


**** Dictionary Lookup
Emacs 28은 자체 서버를 운영하거나, dict.org 로 단어 조회 요청을 전송하는 데 동의할 경우 사전 조회 기능을 지원합니다. 이 원격 서버는 놀라울 정도로 다양한 기능을 갖추고 있으며 여러 언어를 지원합니다.

| 명령어                             | 설명                             |
|------------------------------------+----------------------------------|
| ~M-x dictionary-lookup-definition~ | 현재 커서 위치의 단어를 찾습니다 |
| ~M-x dictionary-search~            | 지정된 단어를 검색합니다         |
| ~M-x dictionary-select-dictionary~ | 검색할 사전을 선택합니다         |


*** Quoted Insert
문자 그대로의 ~TAB, RET~ 또는 ASCII 제어 코드 문자를 삽입할 경우, ~C-q~ 에 바인딩된 quoted insert 기능을 사용해야 합니다.

#+BEGIN_QUOTE
*Line feed vs carriage return* :
문자 그대로의 줄바꿈 기호를 삽입하려면, ~C-q C-j~ 를 입력합니다.
이는 줄바꿈(LINE FEED) 기호이며, 엔터 키(CARRIAGE RETURN)와는 다릅니다.
#+END_QUOTE

Quoted insert 는 ASCII 제어 코드를 ~face escape-glyph~ 글리프로 강조 표시해서 사용자가 시각적으로 쉽게 식별할 수 있도록 만드는 영리한 기능을 갖추고 있습니다. Quoted insert 는 사용자가 입력한 모든 문자를 그대로 삽입합니다. 예를 들어, ~C-q ESC~ 를 입력하면 ASCII 제어 코드 ~^[~ (ESCAPE라고도 함)가 삽입됩니다. 





* Chapter 6. The Practicals of Emacs

#+BEGIN_QUOTE
“[…] Emacs outshines all other editing software in approximately the same way
that the noonday sun does the stars. It is not just bigger and brighter;
it simply makes everything else vanish.”

– Neal Stephenson, In the Beginning… was the CommandLine.
#+END_QUOTE

이전 챕터들은 전적으로 Emacs의 이론적인 측면에 대해서만 다루었습니다. 하지만, 두뇌를 활발하게 움직여 실용적이거나 참신한 활용법을 찾아내는 것은 또 다른 문제입니다. 무엇보다 이론만으로는 부족합니다. 이 마지막 챕터는 제가 ‘워크플로’ 라고 부르는 것, 즉 특정 영역이나 문제를 상당히 깊이 있게 다루는 실습 가이드를 보여드리겠습니다.

지난 두 장과 달리, 이 장에서 소개하는 명령어와 기능에 대해서는 자세히 다루지 않을 것입니다. 그 부분은 여러분이 직접 시간을 내서 알아가시기 바랍니다. 만약 새로운 기능을 찾는 방법을 아직까지 잘 모르겠다면, 계속 읽어보시기 바랍니다—이 장의 첫 부분은 ‘Emacs 탐구’ 입니다.


** Exploring Emacs
Emacs를 진정으로 마스터하려면, 무엇을 어떻게 찾아야 하는지부터 배워야 합니다. 이것이 바로 Emacs의 핵심입니다. 매뉴얼, 서적, 블로그 글들은 사용자의 편집 환경, 즉 Emacs에 대해 일정한 가정을 전제로 하고 있습니다. 변수를 변경하거나 키 바인딩을 재설정하거나, 자신의 필요에 맞게 Emacs를 수정하면, 다른 사람이라면 거의, 아니면 아예 아무도 가지고 있지 않은 고유한 변경 사항의 조합이 만들어집니다. 그러므로 문제를 진단하거나, 마음에 들지 않는 부분을 수정하고 변경하려면, 우선 그 요소들을 어떻게 찾아내는지 알아야 합니다.

이제 Emacs의 버전 관리 인터페이스인 VC 시스템을 살펴보겠습니다. VC 시스템은 Emacs에 내장된 강력하지만 제대로 활용되지 않는 기능으로, 버전 이력, 원인 분석, 커밋, 푸시 및 풀 같은 작업에 대한 일반적인 인터페이스를 제공하며, 이를 통해 사용자가 선택한 버전 관리 시스템과 연동됩니다. VC 는 두 개 이상의 버전 관리 시스템을 정기적으로 사용하는 경우 유용합니다.

만약 이전에 VC 에 대해 전혀 알지 못했고, 지금 이 글을 읽는 것이 VC 에 대한 첫 접점이라면, 어떻게 배워야 할까요?


*** Reading the Manual
당연히 Emacs 매뉴얼은 잘 쓰여져 있고 내용도 방대합니다. 먼저 Emacs의 버전 관리(Version Control) 관련 매뉴얼을 열어보겠습니다.

1. ~C-h i~ 를 입력해서 ~M-x info~ 매뉴얼을 엽니다.
2. Emacs 하이퍼링크로 이동해서 엽니다.
3. ~C-s~ 를 사용해서 ~version~ 또는 ~version control~ 을 검색합니다.

보시다시피, ~C-s~ 를 충분히 많이 누르면 결국 그렇게 해서 버전 관리 매뉴얼을 찾게 될 것입니다.

따라서, 매뉴얼을 읽는 것은 효과적이지만, 모든 기능이 매뉴얼에 포함된 것은 아닙니다. 게다가 챕터들이 손이 닿기 어려운 하위-하위-하위 챕터에 묻혀 있을 수도 있습니다. 또한 타사 패키지는 거의 항상 info 매뉴얼이 포함되어 있지 않습니다.

*Apropos for info manuals* : 검색 패턴을 지정해서 ~M-x info-apropos~ 명령을 사용하면, Emacs가 알려진 모든 info 매뉴얼 페이지를 샅샅이 뒤져 해당 패턴과 일치하는 내용을 찾아줍니다. 어떤 내용이 어디에 있는지 잘 모르겠다면, 이 명령은 아주 유용한 도구입니다.


*** Using Apropos
‘Apropos’ 글에서 저는 apropos 를 사용해서 Emacs의 문서 시스템을 조회하는 다양한 방법을 모두 소개했습니다. 그 중 하나의 apropos 명령은 doc string(Emacs의 대부분의 변수와 함수에 동반되는 문서 문자열)을 검색해서 일치하는 함수나 변수를 나열해 줍니다. Emacs의 문서 문자열을 검색하는 것은 정보를 찾는 데 있어 가장 산발적인 접근 방식입니다. 말 그대로 일반 텍스트 문서를 검색하는 것이기 때문입니다. 이를 수행하려면 문서를 검색하는 apropos 명령어인 ~C-h d~ 를 사용해야 합니다.

#+BEGIN_QUOTE
*Namespacing in Emacs Lisp* :
Emacs Lisp은 다른 Lisp 언어들과 달리 네임스페이스 구분이 없습니다.
Emacs는 모듈이나 네임스페이스를 이용해서 관심사를 분리하지 않습니다.
실제로는 그다지 큰 문제는 아니지만(좀 더 중요한 문제들이 많기 때문이죠),
이는 비공식적으로 Emacs 패키지들이 심볼(함수, 변수 등)에 접두사를 붙여
충돌을 방지한다는 것을 의미합니다.

예를 들면, Python 메이저 모드는 `python-`,
apropos 관련 명령어에는 `apropos-` 등이 사용됩니다.
#+END_QUOTE

그럼에도 불구하고, ~C-h d~ 를 사용해서 버전 관리를 검색하면, 첫 번째 결과는 다음과 같습니다:

#+BEGIN_SRC
vc-mode

Function: Version Control minor mode. This
minor mode is automatically activated whenever
you visit a file under control of one of the
revision control systems in
`vc-handled-backends'.

VC commands are globally reachable under the
prefix `C-x v':
#+END_SRC

이제 약간의 단서가 생겼습니다. VC 모드는 ~vc-mode~ 입니다. 하지만, 우리가 원하는 것은 이 모드가 사용하는 접두사이며, 그것은 ~vc-~ 입니다.

VC의 접두사가 ~vc-~ 임을 알았으므로, ~C-h a~ 에 바인딩된 ~M-x apropos-command~ 를 사용해서 모든 VC 명령어를 찾을 수 있습니다:

~M-x apropos-command~

그런 다음 프롬프트에 다음을 입력합니다:

~Search for a command (word list or regexp): ^vc-~

Emacs는 Apropos 검색 결과를 반환합니다:

#+BEGIN_SRC
vc-annotate C-x v g
  Display the edit history of the current
  FILE using colors.
vc-check-headers M-x ... RET
  Check if the current file has any headers in it.
vc-clear-context M-x ... RET
  Clear all cached file properties.
[...]
#+END_SRC

명령어 목록과 간단한 설명, 그리고 해당 키 바인딩(있는 경우)을 확인할 수 있습니다.

대략 훑어보면 몇 가지 흥미로운 명령어들이 나타납니다.

| 키 및 명령어                   | 설명                      |
|--------------------------------+---------------------------|
| ~C-x v vc-~                    | 명령어 접두사 키          |
| ~M-x vc-dir , C-x v d~         | VC 상태 표시              |
| ~M-x vc-diff , C-x v d~        | 버퍼와 마지막 개정판 비교 |
| ~M-x vc-annotate , C-x v g~    | 블레임 표시               |
| ~M-x vc-next-action , C-x v v~ | 다음 논리적 작업 실행     |
| ~M-x vc-print-log , C-x v l~   | 커밋 로그 출력            |

이것들을 살펴보면 분명한 경향을 알 수 있습니다. 많은 명령어가 접두사 키 ~C-x v~ 에 할당되어 있습니다. 다음 단계는 ~C-h~ 를 추가해서 접두사 키 자체에 어떤 명령어가 할당되어 있는지 확인하는 것입니다. 


*** C-h : Exploring Prefix keys
『키 찾기 및 기억하기』 에서, 부분(접두사) 키를 입력할 때 ~C-h~ 를 덧붙이면 해당 접두사 키에 바인딩된 모든 키를 나열한다는 점을 보여드렸습니다. ~C-x v~ 도 예외는 아닙니다. ~C-x v C-h~ 를 입력하면 이 접두사 키에 바인딩된 모든 키가 나열됩니다. ~C-x v C-h~ 를 입력하면 다음과 같은 결과가 나옵니다:

#+BEGIN_SRC
Global Bindings Starting With C-x v:

key binding
C-x v +    vc-update
C-x v =    vc-diff
C-x v D    vc-root-diff
C-x v G    vc-ignore
C-x v I    vc-log-incoming
C-x v L    vc-print-root-log
C-x v O    vc-log-outgoing
C-x v a    vc-update-change-log
C-x v b    vc-switch-backend
[...]
#+END_SRC

이 명령어의 가장 큰 장점은 입력하기 정말 쉽다는 점입니다. ~C-x v~ 가 현재 파일을 마지막 파일 버전과 비교한다는 사실을 잊어버리셨나요? 문제없습니다. ~C-x v C-h~ 를 입력하면 ~C-x v~ 에 할당된 명령어가 ~M-x vc-diff~ 임을 확인할 수 있습니다. 또 다른 분명한 이점은 평소에는 사용하려고 생각조차 하지 않았거나, 심지어 존재조차 몰랐던 명령어들을 접할 수 있게 해준다는 것입니다. 예를 들어, 새로운 태그(~C-x v s~)를 생성할 필요가 생겼는데, 그 명령의 이름이 무엇인지, 어떤 키에 바인딩되어 있는지, 심지어 Emacs에 그런 기능이 존재하는지조차 확실치 않다면, ~C-h~ 를 통해 그 답을 찾을 수 있을 것입니다.


*** C-h k : Describe what a key does
반대로, 키는 알지만 그 기능이 무엇인지 모르는 경우도 있습니다. ~C-h k~ 명령어는 키 바인딩을 입력받아 현재 활성화된 버퍼에서 해당 키에 어떤 명령이 할당되어 있는지 보여줍니다. 예를 들어, ~C-h k~ 를 입력한 뒤 ~C-x v v~ 를 입력하면 명령의 이름뿐만 아니라 해당 명령에 대한 설명문도 확인할 수 있습니다. 보통 이 설명문은 해당 명령이 무엇을 하는지 명확하게 설명해 줍니다:

#+BEGIN_SRC
C-x v v runs the command vc-next-action (found
in global-map), which is an interactive
autoloaded compiled Lisp function in `vc.el'.

It is bound to C-x v v, <menu-bar> <tools> <vc>
<vc-next-action>.

(vc-next-action VERBOSE)

Do the next logical version control operation on
the current fileset. This requires that all
files in the current VC fileset be in the same
state. If not, signal an error.
...
#+END_SRC

위에는 키 바인딩과 해당 키가 실행하는 명령이 표시되어 있습니다. 또한 명령이 발견된 위치(이 경우 전역 키이므로 전역 맵)와 명령이 포함된 라이브러리 파일도 함께 표시됩니다. 다음으로, 해당 명령이 차지하는 모든 키(여러 개의 바인딩이 있을 수 있음)가 나열되며, Lisp에서 직접 명령을 호출할 경우 함수 인수가 그 뒤에 이어집니다. 그리고 마지막으로, 명령을 설명하는 문서 문자열이 표시됩니다.

이 모든 정보는 ~C-h k~ 를 호출할 때 동적으로 생성됩니다.

~C-h k~ 의 약간의 단점은 이 명령이 일반 사용자가 아닌 엘리스프(Elisp) 개발자를 대상으로 한다는 점입니다. 문서 문자열은 기술적인 관점에서 명령이 어떻게 작동하는지 설명하며, 이는 대개 각 인수가 어떻게 작동하는지, 그리고 일반 사용자는 별 관련없는 기타 기술적인 세부 사항을 설명하는 것을 의미합니다. 하지만, 기술에 익숙한 사람이라면, 비록 리스프 개발자가 아니더라도, 이는 대개 문제가 되지 않습니다.

*명령 설명하기* : ~vc-dir~ 같은 명령 이름이 있다면, ~C-h f~ 를 사용하면 Emacs가 해당 명령의 기능을 설명해 줍니다.


*** C-h m : Finding mode commands 
~C-x v d~ 명령을 실행하면 현재 버퍼의 리포지토리 버전 상태를 보여주는 새로운 버퍼가 나타납니다. 여기에는 추적되지 않은 파일이나 수정된 파일 등의 정보가 표시됩니다. 하지만, 이 버퍼를 어떻게 활용할까요? VC 의 상태 버퍼 사용법을 어떻게 알 수 있을까요?

정답은 ~C-h m~ 입니다. 이 도움말 명령어는 활성화된 메이저 모드 및 마이너 모드에 존재하는 문서 문자열을 설명해 줍니다. 즉, 이 명령어를 사용해서 각 메이저 및 마이너 모드가 무엇을 하는지(그리고 해당 모드에서 사용할 수 있는 키가 있다면 어떤 키인지) 알아볼 수 있습니다.

따라서, VC 상태 버퍼 내에서 ~C-h m~ 을 호출하면 수많은 키와 관련 문서를 확인할 수 있습니다:

#+BEGIN_SRC
key    binding
C-c    Prefix Command
TAB    vc-dir-next-directory
C-k    vc-dir-kill-line
RET    vc-dir-find-file
...
#+END_SRC

그 후에는 관심 있는 각 하이퍼링크를 (~RET~ 키나 마우스로) 클릭하면 됩니다.


*** M-S-x : Execute Extended Command for Buffer
또 다른 방법은 Emacs 28에 도입된 ~M-S-x~ 를 사용하는 것입니다. 하지만, 이 방법이 모든 상황에서 훌륭한 결과를 보장하는 것은 아닙니다. 이 기능은 현재 버퍼의 활성 모드에 두 키가 모두 할당되어 있어야 하며, 해당 모드 개발자가 중요한 명령을 표시하기 위해 ~M-S-x~ 에 대한 힌트를 코드에 추가해야 하기 때문입니다.

VC 의 경우, ~C-x v d~ 같은 전용 모드에서 가장 잘 작동하며, ~C-h m~ 을 보완하는 역할을 처리할 수 있습니다.



** Project Management
역사적으로 Emacs는 파일을 항상 개별적으로만 다루었고, 관련된 파일들의 집합으로 간주한 적은 없었습니다. 2002년부터 Emacs에 포함되어 있었음에도 불구하고 유지보수자들조차 잊어버릴 정도로 제대로 알려지지 않았던 ‘파일셋(filesets)’ 기능이 있었음에도 불구하고, Emacs는 그 역할 대부분을 디렉터리 로컬 변수와 Makefile 및 관련 도구 같은 외부 도구들에 맡겨두었습니다. 이로 인해 Emacs 개발자들과 커뮤니티는 검색 및 교체, 컴파일 같은 다중 파일 작업에 대한 일관된 접근 방식을 구축하기 어려웠습니다. 이는 Emacs 23에서 EDE 가 도입되면서 바뀌었는데, EDE 는 Emacs에 IDE와 유사한 기능을 제공하는 매우 복잡한 도구 모음인 CEDET 의 하위 집합입니다.

#+BEGIN_QUOTE
*What is CEDET?* :
CEDET 는 의미 분석 및 코드 완성 기능을 갖춘
언어 구문 분석, 프로젝트 관리, 코드 생성, 도식화 등의
기능을 제공하는 도구 모음입니다.

C 및 C++ 환경에서 잘 작동하며 해당 커뮤니티에서 많은 사랑을 받았지만,
다른 분야는 크게 보편화되지는 못했습니다.
축약된 버전이 Emacs 23에 포함되었습니다.
#+END_QUOTE

CEDET 와 마찬가지로 EDE 도 제대로 자리를 잡지 못했고, 그동안 다중 언어 프로젝트가 보편화되면서 Projectile 같은 수많은 타사 라이브러리가 번성했습니다. 또한 이들은 파일을 선택적으로 추가하거나 제거하는 정적인 프로젝트 파일 대신 소스 제어 저장소를 기반으로 함으로써 프로젝트 관리의 개념을 변화시켰습니다.

그 후, Emacs는 project.el 을 도입했으며, 그 이후로 꾸준히 개발이 진행되어 왔습니다. 이 “새로운” 프로젝트 관리자는 다양한 기능을 갖추고 있으며, 제 생각에는 대부분의 사용자에게 훌륭한 기본적인 경험을 제공하는 무언가를 만들기 위해 타사 도구들의 집합적인 작업에서 영감을 얻었습니다.

주요 기능 중 일부는 다음과 같습니다:

*버전 관리 시스템에 등록된 파일을 기반으로 파일 추론* : Emacs는 현재 사용 중인 버전 관리 시스템에 파일이 등록되어 있다면, 해당 파일이 프로젝트 사용자와 관련이 있을 가능성이 높다는 가정 하에 프로젝트와 관련된 파일을 자동으로 추론합니다.

*버전 관리 시스템의 홈 디렉터리를 기반으로 루트 디렉터리 추론* : 파일 검색, 린팅 도구, 컴파일 명령어 등이 종종 루트 디렉터리를 기준으로 실행되기 때문에 이는 중요합니다.

*프로젝트 파일 열거에 대한 내장 지원* : 프로젝트 내의 여러 파일이나 프로젝트 파일의 일부 집합을 대상으로 검색 및 치환을 수행하기 위함입니다.

*프로젝트와 연동되는 명령어 선택* : ~M-x shell~ 또는 ~M-x dired~ 버퍼 열기; 파일 찾기; 프로젝트 관련 버퍼 종료; 또는 이름으로 다른 프로젝트로 전환하는 것 등이 있습니다.

여기서 나열한 세부 사항들은 저수준으로 보일 수 있지만, 중요합니다: 이는 Emacs에서 오랫동안 간절히 기다려온 기능인 것이며, 탄탄한 기반을 마련하는 것—개발팀이 이미 해낸 일—은 이 기능이 출시된 지금, 좀 더 넓은 커뮤니티의 채택이 필수적이므로 매우 중요합니다.

사용할 도구에 대해 확고한 선호도가 없다면, 이것을 사용해야 합니다. 이를 위해 필요한 것은 Git 이나 Mercurial 저장소 뿐입니다.

~C-x p~ (Emacs 28에 도입됨)에 바인딩된 프로젝트 전용 접두사 키맵이 있습니다:

| 프로젝트 키 | 설명                            |
|-------------+---------------------------------|
| ~C-x p p~   | 다른 알려진 프로젝트로 전환     |
| ~C-x p b~   | 버퍼로 전환                     |
| ~C-x p f~   | 프로젝트 내 파일 찾기           |
| ~C-x p k~   | 프로젝트 버퍼 삭제              |
| ~C-x p g~   | 정규 표현식 검색                |
| ~C-x p r~   | 정규 표현식 검색 및 바꾸기 쿼리 |
| ~C-x p c~   | 프로젝트 컴파일                 |
| ~C-x p v~   | VC 대화 상자 열기               |
| ~C-x p s~   | 셸 열기                         |
| ~C-x p d~   | Dired 버퍼 열기                 |

보다 일반적인 단축키와 달리, ~C-x p f~ 및 ~C-x p b~ 같은 키 바인딩은 동일한 방식으로 작동하지만, 당연히 프로젝트에서 인식하는 파일로 제한됩니다. 모든 명령어 역시 이와 마찬가지입니다. 이 명령어들은 백엔드에 정의된 프로젝트 범위 내에서만 작동하며, 기본적으로 이는 VC 루트 디렉터리와 해당 디렉터리가 인식하는 모든 파일을 의미합니다.


** Xref: Cross-References in Emacs
Xref 는 기호(예: 아래 점)를 해당 정의와 매칭한 후, 사용자가 이를 편집하거나 해당 위치로 이동할 수 있도록 표시해 주는 통합 플랫폼입니다. 이 플랫폼은 실행 중인 버퍼의 메이저 모드에 따라 달라질 수도 있는 구성 가능한 백엔드를 통해 이런 기능을 수행합니다. 이 도구는 타사 패키지와 연동되도록 설계되었으나, 아직까지 널리 채택되지는 않았으며, 자체적인 심볼 정의 목록을 생성하는 도구들과 호환됩니다.

알아두어야 할 가장 일반적인 명령어 네 가지는 다음과 같습니다:

| 키      | 설명                        |
|---------+-----------------------------|
| ~M-.~   | 포인트 지점에서 정의 찾기   |
| ~M-,~   | 팝 마커를 표시하고 돌아가기 |
| ~M-?~   | 패턴과 일치하는 참조 찾기   |
| ~C-M-.~ | 패턴과 일치하는 기호 찾기   |

xref 의 ‘정의 찾기’ 기능을 ~M-.~ 키로 호출할 때, 사용 중인 메이저 모드에 xref 가 아직까지 설정되지 않았다면 먼저 TAGS 테이블 파일을 찾으라는 메시지가 표시될 가능성이 높습니다. TAGS 파일은 오래된 ~M-.~ 같은 명령을 사용하면 현재 위치에서 이동하는데, 이때 나중에 다시 돌아올 수 있도록 마커를 남겨둡니다. 식별자와 그 위치를 생성한 다음, 성능 향상을 위해 파일 시스템의 거대한 정적 조회 테이블에 저장하는 방식입니다. TAGS 파일은 엄청나게 큰 프로젝트를 작업할 때 유용합니다. 하지만, 대부분의 사용자는 파일 시스템을 실시간으로 검색하거나 Language Server에 쿼리를 보내는 도구만으로도 충분합니다.

시작하기 위해, 저는 타사 패키지인 dumb-jump 를 사용해 보기를 권장합니다. 이름과는 달리, 이 패키지는 grep, ack, ag 또는 ripgrep 같은 파일 검색 도구의 실행 속도를 활용해서 현재 사용 중인 메이저 모드와 관련된 일치 항목을 찾아줍니다. 대부분의 경우 이 정도면 충분합니다. 특히 ripgrep 은 최신 하드웨어에서 믿기 힘들 정도로 빠르며 Emacs와 잘 어울립니다.

설정이 완료되면 ~M-.~ 을 눌러 식별자로 이동할 수 있으며, 다시 되돌아가려면 ~M-, .~ 을 눌러 스택에서 마커를 제거할 수 있습니다. 정의가 여러 개 있거나 Emacs가 어떤 것이 가장 적합한지 확신할 수 없는 경우, 일치하는 정의들이 나열된 버퍼가 표시됩니다. ~C-M-.~ 을 사용해서 정규 표현식과 일치시키는 것도 가능합니다. 

#+BEGIN_QUOTE
*Popping the Stack* :
Emacs에서 흔히 쓰이는 용어 중 하나는 ‘스택에서 무언가를 팝(pop)한다’ 는 표현으로,
이는 컴퓨터 과학에서 리스트에 가장 최근에 추가된 항목을 제거한다는 개념을 가리킵니다.
이 용어는 Emacs 사용자 명령어 여기저기서 볼 수 있습니다.
#+END_QUOTE

~M-?~ 키 바인딩은 다른 백엔드가 없는 경우 grep 같은 일반적인 파일 검색 도구를 사용해서 프로젝트 디렉터리를 검색하도록 설정될 수 있습니다. 패키지 관리자를 확인해 보시기 바랍니다. 패키지 목록에서 ~M-s~ 또는 ripgrep 을 입력해서 해당 도구가 언급된 패키지를 찾아보시기 바랍니다. 보통 이 방법이 시작점으로 적합합니다.

검색 결과는 xref 정의 버퍼에 표시됩니다.

| Xref 버퍼 키 | 설명                            |
|--------------+---------------------------------|
| ~RET~        | 정의로 이동                     |
| ~TAB~        | 정의로 이동 및 상호 참조 숨기기 |
| ~C-o~        | 정의 표시                       |
| ~.~ 및 ~,~   | 위/아래로 이동                  |
| ~r~          | 정규식 검색 및 바꾸기           |

~.~ 와 ~,~ 키를 사용해서 일치 항목 목록을 빠르게 훑어보면서 필요한 정의를 찾아보시기 바랍니다. 목록을 이동하면 Emacs가 해당 일치 항목으로 곧바로 이동합니다. 원하는 항목을 찾았다면 TAB 키를 눌러 커서 위치의 정의로 이동하고 xref 버퍼를 닫을 수 있습니다.

~r~ 을 입력하면 검색 및 치환에 사용할 정규식을 입력하라는 메시지가 표시됩니다. 이 기능은 '검색 및 치환' 에서 설명한 ~C-M-%~ 와 동일하게 작동합니다.

#+BEGIN_QUOTE
*Xref and Dired* :
Dired 에서도 Xref 기능을 사용할 수 있습니다.
~A~ 를 입력하면 검색을, ~Q~ 를 입력하면
표시된 파일 내에서 검색 및 바꾸기를 수행할 수 있습니다.
#+END_QUOTE


** Working with Log Files
로그 파일을 꼼꼼히 살펴보는 것은 흔한 작업이며, Emacs는 이를 손쉽게 관리할 수 있는 도구들이 있습니다.

| 키        | 설명                               |
|-----------+------------------------------------|
| ~C-x C-f~ | 파일을 검색합니다                  |
| ~C-x C-r~ | 읽기 전용 모드로 파일을 검색합니다 |
| ~C-x C-q~ | 읽기 전용 모드로 전환합니다        |

로그 파일을 여는 것이 첫 번째 단계입니다. 파일을 읽기 전용으로 열 수도 있습니다. 파일에 쓰기 권한이 없다면, Emacs는 자동으로 ~M-x read-only-mode~ 로 파일을 엽니다. ~C-x C-q~ 를 눌러 이 모드를 켜거나 끌 수 있습니다. 읽기 전용 모드를 해제해야 하는 이유는 버퍼에 플러싱이나 줄 유지 같은 파괴적인 변경을 적용할 수 있도록 처리하기 위해서입니다:

| 키                | 설명                                        |
|-------------------+---------------------------------------------|
| ~M-x flush-lines~ | 지정된 패턴과 일치하는 줄을 모두 삭제합니다 |
| ~M-x keep-lines~  | 지정된 패턴과 일치하는 줄만 남깁니다        |
| ~M-s o~           | 지정된 패턴과 일치하는 줄을 나열합니다      |

~M-s o~ 는 패턴에 일치하는 Occur 모드 버퍼를 생성합니다. 많은 사람들이 간과하는 점은, Occur 모드 버퍼에서 ~M-s o~ 를 다시 실행해서 내용을 좀 더 세밀하게 필터링할 수 있다는 사실입니다.

거의 똑같은 로그 항목들이 줄줄이 이어지는 화면을 스크롤하다 보면 패턴에만 눈이 멀어 정작 중요한 내용을 놓치기 쉽습니다. 이럴 때 Emacs의 하이라이터 기능이 유용합니다. 버퍼 내의 패턴을 서로 다른 색상으로 강조 표시해서 구분할 수 있기 때문입니다:

| 키        | 설명                                    |
|-----------+-----------------------------------------|
| ~M-s h p~ | 특정 구문을 강조 표시합니다             |
| ~M-s h r~ | 정규식을 강조 표시합니다                |
| ~M-s h .~ | 커서 위치의 기호를 강조 표시합니다      |
| ~M-s h u~ | 커서 위치의 밑줄 강조 표시를 해제합니다 |

하이라이터 기능은 유용하며, Emacs 모든 곳에서 사용할 수 있습니다. 키 바인딩을 외우지 못하더라도, 모든 명령 이름이 ~highlight-~ 로 시작하므로 필요할 때 ~M-x .~ 을 사용해서 쉽게 실행할 수 있다는 점만 기억하시기 바랍니다.

로그 파일은 정적 파일이 아닌 경우가 많습니다. 로그 파일은 끊임없이 변경되거나 추가됩니다. 파일 시스템에서 파일이 변경되면 Emacs가 파일을 새로 고치는 마이너 모드를 활성화할 수 있습니다. 최신 버전의 Emacs는 (대부분의 최신 플랫폼에서) 파일 변경 이벤트를 사용하고, 알림을 지원하지 않는 구형 시스템은 폴링 기술을 사용합니다.

| 키                          | 설명                                        |
|-----------------------------+---------------------------------------------|
| ~M-x auto-revert-mode~      | 파일이 변경되면 버퍼를 복원합니다           |
| ~M-x auto-revert-tail-mode~ | 파일이 변경되면 변경 내용을 끝에 추가합니다 |

두 모드 모두 비슷합니다. 파일 내용이 자주 변경되는 경우 ~M-x auto-revert-mode~ 는 필수적입니다. Emacs는 변경 사항을 감지해서 파일 전체를 다시 불러옵니다. 반면 ~M-x auto-revert-tail-mode~ 는 ~tail -f~ 와 동일한 방식으로 작동합니다. 파일이 변경되면 변경된 내용은 버퍼 끝에 추가되고, Emacs는 이에 따라 화면을 스크롤합니다.


*** Browsing Other Files
물론 이런 개념을 다른 파일 형식에 적용하는 것을 막을 이유는 전혀 없습니다. 예를 들어, Emacs는 기본적으로 활성화된 수동 모드인 자동 압축 모드가 내장되어 있으므로, 파일을 열거나 저장할 때 자동으로 압축을 풀고 다시 압축합니다. 이 기능을 ~M-x dired~ 와 함께 사용하면 압축된 아카이브를 마치 디렉터리인 것처럼 탐색할 수 있습니다.


**** Dired: Thumbnail Image Browser
~M-x image-dired~ 를 입력하면 Emacs의 이미지 썸네일 브라우저로 들어갈 수 있습니다. 썸네일이 표시된 창과 파일이 담긴 dired 창이 나타납니다.

썸네일 버퍼는 다양한 키 바인딩이 구비되어 있습니다. 그 중 일부는 다음과 같습니다:

| Thumbnail 키 | 설명                                 |
|--------------+--------------------------------------|
| ~C-f, C-b~   | 다음 또는 이전 썸네일로 이동         |
| ~C-p, C-n~   | 썸네일 행을 위나 아래로 이동         |
| ~d, m, u~    | 삭제, 선택, 선택 해제 (Dired와 동일) |
| ~t t, t u~   | 이미지에 태그 지정 또는 태그 해제    |
| ~RET~        | 이미지 열기                          |
| ~l, r~       | 썸네일을 왼쪽 또는 오른쪽으로 회전   |

전체 크기 이미지 버퍼는 세 가지 단축키로 제공됩니다:

| Image 키 | 설명                         |
|----------+------------------------------|
| ~q~      | 종료                         |
| ~s~      | 이미지를 창 크기에 맞게 조정 |
| ~f~      | 전체 화면으로 보기           |

다만, dired 에서 파일을 열면 Dired Image Display Mode가 아닌 일반 이미지 뷰어인 Image Mode(훨씬 더 강력한 기능을 갖추고 있음)로 전환된다는 점에 유의하시기 바랍니다.


**** DocView: Viewing Rich Documents
사용 중인 시스템이 비교적 최신 버전이고, 필요한 프로그램이 설치되어 있다면, Emacs의 이미지 렌더링 기능을 활용해서 PDF 및 Open/MS Office 문서를 열 때 즉시 변환할 수 있습니다.

#+BEGIN_QUOTE
*DocView Support* :
Emacs가 변환을 시도하는 항목의 전체 목록을 보려면
~C-h v auto-mode-alist~ 를 입력하고 ~doc-view~ 를 검색합니다.
이 변수는 책 초반부에 메이저 모드 로드 순서에 대해 다룰 때
언급했던 것을 기억하실 겁니다.
#+END_QUOTE

DocView 를 사용하면 PDF 또는 기타 지원되는 바이너리 파일을 열면 Emacs가 해당 파일을 렌더링하려고 시도합니다. 파일이 열리면 사용할 수 있는 주요 단축키 조합은 다음과 같습니다:

| 키                | 설명                                     |
|-------------------+------------------------------------------|
| ~n, p~            | 위/아래 페이지 이동                      |
| ~<next>, <prior>~ | 위/아래 페이지 이동                      |
| ~SPC~             | 아래로 스크롤                            |
| ~S-SPC~           | 위로 스크롤                              |
| ~M-<, M->~        | 첫 페이지/마지막 페이지로 이동           |
| ~+ , - , 0~       | 확대, 축소 또는 초기화                   |
| ~W, H, P, F~      | 너비, 높이, 페이지 또는 창 크기에 맞추기 |

이는 사용 가능한 키 바인딩 중 일부에 불과합니다. 특히 주목할 점은 문서를 천천히 넘겨가면서 읽을 때 사용하는 ~SPC~ 와 ~S-SPC~ 로, 이 기능들은 주로 읽는 문서에 맞춰 설계되었습니다. ~+~ 와 ~-~ 를 사용해서 확대하거나 축소할 수 있습니다. 또한 ~W~ 나 ~H~ 를 사용해서 Emacs가 자동으로 문서 크기를 조정해서 창의 너비나 높이에 맞출 수 있습니다. 반면 ~F~ 를 누르면 창의 크기를 문서에 맞게 조정합니다.

만약 이미지가 깨져 보인다면, ~doc-view-resolution~ 을 사용자 정의해서 DPI를 높일 수 있습니다.

#+BEGIN_QUOTE
*Slide Show Viewer*:
~M-x doc-view-presentation~ 명령어는 Doc View 버퍼를
전체 화면 슬라이드 쇼로 전환합니다.

~n~ 과 ~p~ 키를 사용해서 “슬라이드” 사이를 이동할 수 있으며,
~q~ 키를 눌러 종료할 수 있습니다.
#+END_QUOTE



** TRAMP: Remote File Editing
원격 파일 편집은 대개 번거롭습니다. 보통 터미널 에뮬레이터를 통해 원격 환경과 상호작용하며, 거의 항상 그래픽 인터페이스의 편리함이나 평소 사용하던 설정 없이 작업해야 하기 때문입니다. /.emacs.d/ 디렉터리를 휴대하는 것은 식은 죽 먹기지만, 불편한 점은 여전합니다. 기술이 아무리 발전해도 원격 파일 편집에는 대개 타협안이 따르기 마련입니다.

Emacs의 ~TRAMP~ 시스템은 사용자가 마주칠 가능성 높은 대부분의 원격 파일 상호작용 문제를 해결하는 투명한 프록시입니다. TRAMP 는 의심할 여지 없이 Emacs에서 가장 멋진 기능 중 하나입니다.

TRAMP 는 ~C-x C-f~ (및 기타 명령어)를 모니터링해서 작동하며, scp 같은 명령줄 도구가 사용하는 것과 비슷한 특수 구문을 통해 원격 파일에 접근하려는 시도를 감지합니다. TRAMP 의 가장 큰 장점은 완전한 투명성입니다. Emacs에 원격 편집 기능이 있다는 사실을 모른다면, 전혀 눈치채지 못했을 것입니다. 원격 파일에 접근해서 편집하는 과정은 빠르고 매끄럽습니다.

모든 TRAMP 연결은 다음과 같은 구문을 따릅니다:

~/protocol:[user@]hostname[#port]:~

TRAMP 는 구형 및 신형 프로토콜을 다수 지원하지만, 요즘에는 주로 ssh 나 scp 를 사용할 가능성이 높습니다. TRAMP 프로토콜의 전체 목록과 작동 방식은 ~tramp-methods~ 변수나 info 매뉴얼 페이지(tramp)의 ‘Internal methods’ 항목을 참조하시기 바랍니다.

#+BEGIN_QUOTE
*Microsoft Window* :
Windows는 프로토콜 선택 옵션이 다릅니다.
Cygwin이나 크로스 컴파일된 OpenSSH 버전을 사용하지 않는다면,
PuTTY의 plink.exe 도구를 설치하고 프로토콜로 plink 를 사용해야 합니다.
#+END_QUOTE

오늘날의 서버 환경은 25년 전보다 훨씬 더 균일해졌지만, TRAMP 는 원격 셸이 일관되고 신뢰할 수 있는 환경을 제공하도록 배경에서 많은 작업을 수행합니다. 앞서 언급한 변수인 ~tramp-methods~ 는 TRAMP 가 각 프로토콜 유형을 어떻게 처리할지를 제어합니다. 잘 알려지지 않은 시스템을 사용하는 경우, 이 변수를 사용자 정의해야 할 수도 있습니다.

TRAMP 의 또 다른 유용한 기능은 =~/.ssh/config= 파일을 파싱해서 프로토콜로 ssh 를 입력했을 때 알려진 호스트를 자동으로 완성해 준다는 점입니다. 물론 호스트 이름, 사용자 이름, 포트 모두를 수동으로 지정할 수 있으며, 후자 두 가지는 선택 사항입니다.

#+BEGIN_QUOTE
*SSH config*:
ssh 를 사용한다면, 모든 연결 및 인증 정보를 기억하기 쉬운 이름으로
저장할 수 있는 설정 파일을 사용하시기를 강력히 권장합니다.

자세한 내용은 Emacs에서 ~M-x man ssh_config~ 를 입력해서
관련 매뉴얼 페이지를 참조하시기 바랍니다.
#+END_QUOTE

마지막으로, TRAMP 를 실제로 실행하려면 루트에서 호출해야 합니다. FIDO 또는 IDO 모드에서 ~//~ 를 입력하면 루트로 이동하며, 위와 같은 형식을 따라야 합니다.

#+BEGIN_QUOTE
*Helm* :
Helm 을 사용 중이면, ~helm-tramp~ 라는 타사 패키지를 설치해서
필요한 모든 TRAMP 구성을 자동으로 생성할 수 있습니다.

또한 Docker 같은 도구에 대한 지원을 추가하는 TRAMP 확장 기능도 찾아볼 수 있습니다.
#+END_QUOTE

Emacs는 다음과 같이 두 번째 콜론(:)을 입력할 때까지 원격 연결을 시작하지 않는다는 점에 유의하시기 바랍니다:

~/ssh:homer@powerplant:/var/log/reactor.log~

위의 명령은 ssh 프로토콜과 homer 사용자를 사용해서 powerplant 서버에 연결합니다. 그런 다음 ~/var/log/reactor.log~ 파일을 엽니다. 


*** The Default Directory and Remote Editing
모든 버퍼는 ~default-directory~ 변수가 있습니다. 이 변수는 엘리스프(Elisp) 용어로 말하면 버퍼 로컬 변수입니다. 각 버퍼는 해당 버퍼에 국한되고 전역 변수가 아니기 때문에(Emacs에서 기본적으로 변수가 전역인 것과 달리) 고유한 ~default-directory~ 변수를 가지고 있습니다.

버퍼에서 ~C-x C-f~ 를 입력하면, Emacs는 ~default-directory~ 를 확인하고 해당 디렉터리를 새 파일을 열 때의 기본 디렉터리로 선택합니다. 이는 현재 버퍼와 디렉터리를 공유하는 다른 파일을 열기를 원할 수 있으므로 합리적인 방식입니다. ~/etc~ 에서 파일을 편집하는 중에 ~C-x C-f~ 를 입력하면 ~/etc~ 에 있는 다른 파일을 열기를 원할 수 있으므로, Emacs는 그곳을 기본 디렉터리로 선택합니다.

이 기능은 TRAMP 및 원격 파일도 동일하게 작동합니다. 원격으로 편집 중인 파일에서 ~C-x C-f~ 를 호출하면, Emacs는 로컬 시스템이 아닌 원격 시스템을 자동으로 조회해서, 다른 원격 파일을 쉽게 열 수 있게 해줍니다.

파일을 열면 TRAMP 가 뒤에서 마법 같은 작업을 수행해서, Emacs에서 로컬 파일과 거의 똑같이 보이고 느껴지는 파일을 사용할 수 있게 됩니다. 해당 파일이 원격 파일임을 알 수 있는 유일한 시각적인 단서는 모드라인입니다. 파일 이름 앞에 ~@~ 기호가 나타나며, ~default-directory~ 변수는 TRAMP 가 주석 처리한 파일 경로를 반영합니다. 직접 시도해 보고 ~C-h v~ 를 눌러 해당 변수를 확인하시기 바랍니다.

따라서, 파일을 원격으로 편집할 수 있을 뿐만 아니라, TRAMP 와 Emacs 간의 긴밀한 통합 덕분에 훨씬 더 많은 작업을 수행할 수 있습니다. ~M-x rgrep~ 같은 명령을 호출하면 Emacs와 TRAMP 가 매끄럽게 연동됩니다. 명령은 원격 머신에서 실행되며, 마치 로컬에서 명령을 호출한 것처럼 결과는 Emacs로 다시 전송됩니다.

원격으로 실행할 수 있는 작업에는 끝이 없습니다. 다음은 제가 원격으로 사용하는 몇 가지 명령어입니다:

*~C-x d~ : Dired* : 모든 명령어는 원격 세션을 통해 터널링되므로, 마치 로컬에 있는 것처럼 Dired 를 사용해서 파일과 디렉터리를 관리할 수 있습니다. 원격 및 로컬 Dired 세션 간에 파일을 복사할 수도 있으며, TRAMP 가 파일을 투명하게 복사해 줍니다.

*~M-x compile~ : Compile* : make 나 python manage.py runserver 같은 컴파일 명령어, 또는 원하는 어떤 명령어든 입력할 수 있습니다. Emacs는 명령을 원격으로 실행하며, 그 결과는 ~*compilation*~ 버퍼에 표시됩니다. 실시간 피드백을 통해 원격으로 대화형 서버를 실행할 수도 있습니다.

*~M-x rgrep~ : Grep* : find 와 grep 모두 원격으로 호출되며, 다른 명령과 마찬가지로 결과는 Emacs에 표시됩니다. grep 출력에 포함된 하이퍼링크된 파일은 원격 파일을 올바르게 엽니다.

*~M-x shell~ : Emacs의 셸 래퍼* : 원격 로그인 셸을 시작하고 사용자에게 제어권을 넘겨줍니다. 이는 로컬 머신에서 ~M-x shell~ 을 실행하는 것과 똑같이 작동하지만, 이 경우 셸은 당연히 원격 머신에 있습니다. TAB 자동 완성 – ~M-x shell~ 은 실제 셸이 아닌 Emacs에서 수행됨– 역시 작동합니다.

*~M-x eshell~ : Emacs의 Elisp 셸* : Eshell 은 Emacs Lisp으로 작성된 셸입니다. 또한 원격 TRAMP 연결도 투명하게 작동합니다. 실제로 로컬 셸에서 곧바로 원격 디렉터리로 cd 명령을 실행할 수 있습니다.


*** Multi-Hops and User Switching
TRAMP 의 또 다른 멋진 기능은 su 또는 sudo 를 통한 권한 상승입니다. 다른 사용자나 루트 권한으로 파일을 편집할 경우, 로컬 파일도 이 기능이 작동합니다. 이 기능은 중간 호스트를 통해 원격 호스트에 연결하는 ‘멀티 홉(multi-hop)’ 개념과 자연스럽게 연결됩니다. 예를 들어, 내부 서버에 접속해야지만 보안을 강화하기 위해 먼저 공용 서버를 통해 연결하는 경우나, 특정 사용자로 로그인한 후 sudo 를 호출해서 원격 서버에서 루트 권한으로 파일을 편집할 경우가 있습니다.

~/etc/fstab~ 파일에 대한 sudo 접근 권한을 요청하는 좀 더 간단한 경우부터 시작해 보겠습니다:

~/sudo:root@localhost:/etc/fstab~

보시다시피, 구문은 일반적인 원격 TRAMP 연결 방식과 동일합니다. 단지 sudo 를 사용하고 로컬로 연결한다는 점만 다를 뿐입니다. TRAMP 는 root 사용자임을 알아차릴 만큼 똑똑하므로 보통 ~root@~ 는 생략해도 됩니다. 이 파일은 (TRAMP의 관점에서) 기술적으로 원격 파일이므로 기본 디렉터리에 대한 일반적인 규칙이 그대로 적용된다는 점을 명심하시기 바랍니다. 원격 버퍼에서 ~C-x C-f~ 로 파일을 열면 다른 파일들도 sudo 권한으로 열립니다

TRAMP 에서 멀티 홉(multi-hopping)은 보통 ~tramp-default-proxies-alist~ 를 수정해서 수행하지만, 저는 이 방법이 다소 번거롭다고 생각합니다.

adhoc 구문을 사용하는 것이 훨씬 더 간편합니다:

~/ssh:homer@powerplant|sudo:powerplant:/root/salary.txt~

위의 예제는 homer 계정으로 powerplant 서버에 연결합니다. 그런 다음, 또 다른 ‘연결’ 이 sudo 를 호출해서 sudo 권한을 가진 사용자로 ~/root/salary.txt~ 파일을 엽니다. sudo 문자열에 호스트명을 반복해서 지정하는 것이 중요합니다. 그렇지 않으면 작동하지 않습니다. 앞서 설명한 것과 마찬가지로, 원격 파일도 이와 동일한 규칙을 따릅니다. salary 파일 내에서 ~M-x shell~ 같은 명령을 호출하면 powerplant 서버에서 루트 셸을 얻을 수 있습니다.

#+BEGIN_QUOTE
*Bookmarks* :
~C-x r m~ 을 사용해서 원격 파일을 북마크로 저장할 수 있으며(북마크 및 레지스터 참조),
나중에 ~C-x r b~ 또는 ~C-x r l~ 로 북마크를 다시 열면 TRAMP가 자동으로 다시 연결됩니다.

북마크는 Emacs의 다양한 기능과 폭넓게 연동됩니다.
특히 복잡한 다단계 연결의 경우, 북마크를 사용하면 시간을 크게 절약할 수 있습니다.
#+END_QUOTE

마지막으로, init 파일에 다음 코드 조각을 추가하시기를 권장합니다. 이것은 ~M-x sudo~ 로 호출하면 TRAMP 를 사용해서 현재 파일을 루트 권한으로 편집하는 사용자 정의 명령어입니다:

#+BEGIN_SRC
(defun sudo ()
  "Use TRAMP to `sudo' the current buffer."
  (interactive)
  (when buffer-file-name
    (find-alternate-file
      (concat "/sudo:root@localhost:"
              buffer-file-name))))
#+END_SRC

위에서 살펴본 것 같이, 문자열을 약간 수정하면 다단계 명령을 쉽게 만들 수 있습니다. 엘리스프(Elisp)를 처음 접하고 다단계 명령이 필요하다면, 이를 재미있는 입문 과정으로 삼아서 배워보는 것도 좋습니다.

*Conclusion* : TRAMP 는 Emacs의 내장 셸 지원 기능 및 창과 버퍼와 결합되어, tmux 및 GNU screen 기반의 워크플로우를 대체할 훌륭한 대안이 됩니다. 원격 파일 편집을 Emacs 내에서 수행함으로써, 사용 환경이 통합되고 서로 다른 TRAMP 는 Emacs의 정말 강력한 기능이며, 다른 대안들보다 사용해 볼 가치가 있습니다. 기존의 원격 편집 방식을 완전히 대체할 수는 없겠지만, 시작하기에 좋은 선택지입니다.



** EWW: Emacs Web Wowser
오래전부터 Emacs는 자윈스키(Zawinski)의 ‘소프트웨어 포괄화 법칙’ 에 굴복해 왔습니다. 이 법칙은 “모든 프로그램은 이메일을 읽을 수 있을 때까지 확장하려 한다. 그렇게 확장할 수 없는 프로그램은 확장할 수 있는 프로그램으로 대체된다!” 고 규정하는데 Emacs는 하나가 아닌 여러 개의 메일 클라이언트를 내장함으로써 이를 실천해 왔습니다.

분명 21세기엔 기준을 한 단계 더 높여야 합니다. 따라서, 이맥스에 내장 웹 브라우저인 EWW(Emacs Web Wowser)가 있다는 사실은 그리 놀라운 일도 아닙니다.

EWW는 작고 멋진 웹 브라우저 엔진입니다. 렌더러는 기본적인 HTML과 이미지 지원으로 제한되지만 기존 텍스트 기반 브라우저들과 크게 다르지 않습니다. 하지만, 제한된 렌더러에도 불구하고 기술 문서를 훑어보거나, 빠르게 웹 검색을 하거나, 상사에게 들키고 싶지 않은 웹사이트를 둘러보는 데는 아주 훌륭합니다.

EWW를 사용하려면 ~M-x eww~ 를 입력한 후 URL 이나 검색어(keyword)를 입력하라는 메시지가 나타납니다. 기본 검색 엔진은 DuckDuckGo 지만 ~eww-search-prefix~ 를 사용자 정의해서 변경할 수 있습니다. Emacs 27부터 이미 EWW 버퍼가 존재해도 ~C-u M-x eww~ 를 입력하면 새로운 EWW 버퍼를 생성합니다.

#+BEGIN_QUOTE
*External and internal browsing* :
~M-x browse-url~ 명령어로 시스템 웹 브라우저로 열 수 있습니다.

Emacs는 ~browse-url-default-browser~ 변수를 사용하는데 이 변수는 운영체제에 설치된 브라우저에 따라
적절한 브라우저를 자동으로 추정하는 함수입니다.

~M-x customize-option browse-url-default-browser~ 로 기본 브라우저를 사용자 정의할 수 있습니다. 
#+END_QUOTE

EWW는 주로 키보드로 탐색하지만(Emacs에서 예상할 수 있듯이) 하이퍼링크는 마우스로 클릭할 수 있습니다.

| 키           | 설명                            |
|--------------+---------------------------------|
| ~TAB, S-TAB~ | 다음/이전 하이퍼링크로 이동     |
| ~q~          | EWW 종료                        |
| ~&~          | ~M-x browse-url~ 로 페이지 열기 |
| ~B~          | 북마크 표시                     |
| ~b~          | 북마크 추가                     |
| ~H~          | 브라우저 기록 표시              |
| ~l, r~       | 기록에서 뒤로/앞으로 이동       |
| ~p, n, u, t~ | 시맨틱 웹 탐색 보조 기능        |
| ~R~          | 리더 모드 활성화                |
| ~RET~        | 링크 탐색                       |
| ~C-u RET~    | 외부 브라우저에서 링크 열기     |
| ~M-s M-w~    | EWW에서 현재 위치 검색          |
| ~M-RET~      | 새 버퍼에서 링크 열기           |
| ~s~          | 다른 EWW 버퍼로 전환            |
| ~w~          | 현재 위치의 링크 복사           |

#+BEGIN_QUOTE
*Emacs 28* :
Emacs 28에서 EWW는 Emacs의 다른 구성 요소들과 북마크 시스템을 공유합니다.
#+END_QUOTE

가장 많이 사용하는 명령어는 하이퍼링크를 여는 ~TAB~ 과 ~S-TAB~ 그리고 브라우저 기록 내에서 앞뒤로 이동하는 ~l~ 과 ~r~ 입니다. ~p, n, u, t~ 명령어는 웹 페이지에서 어떤 하이퍼링크가 다음 링크고 이전 링크인지 의미론적으로 명시되어 있을 때만 작동합니다.

~R~ 키를 누르면 리더 모드로 전환합니다. 정말 훌륭합니다. 이 모드는–시도만 하지만 EWW는 대부분 정확하게 처리합니다–모든 방해 요소를 제거하고 본문 텍스트만 남깁니다. 읽기에 최적입니다.

~M-s M-w~ 명령어도 유용합니다. 이 명령어는 선택된 영역을 기본 검색 엔진(보통 DuckDuckGo)으로 보내고 결과를 EWW에 표시합니다.

** Dired: Files and Directories
파일 시스템에서 파일과 디렉터리를 탐색하고 조작하는 작업은 Emacs에 특히 잘 맞는 분야입니다. 일반적인 방식으로 로컬 파일을 편집하거나 TRAMP 를 사용해서 원격 파일을 편집하는 것 외에도, Emacs의 디렉터리 편집기인 dired 를 사용해서 디렉터리와 파일을 조작할 수 있습니다.

dired 에 접근하는 방법은 여러 가지가 있습니다:

*IDO 또는 FIDO 모드에서* : ~C-x C-f~ 로 파일을 검색할 때 ~C-d~ 를 입력하면 해당 파일의 현재 디렉터리에서 dired 버퍼를 열 수 있습니다.

*명령어로* : ~M-x dired~ 명령어를 실행하면 열 디렉터리를 입력하라는 프롬프트가 나타납니다. 기본값은 ~current-buffer~ 가 위치한 디렉터리인 ~default-directory~ 입니다. TRAMP 와 마찬가지로, 파일이 원격에 있는 경우 Emacs는 원격 dired 세션을 열 것인지 묻습니다.

*키 바인딩으로* : 키 바인딩 ~C-x d~ 는 위의 명령과 동일하게 작동합니다. 명령 ~C-x 4 d~ 는 동일한 작업을 수행하지만 다른 창에서 실행합니다.

Emacs에서 dired 버퍼를 열면, 다음과 비슷한 화면이 나타납니다:

#+BEGIN_SRC
/usr/share/dict:
total used in directory 2328 available 187646744
drwxr-xr-x 2 root root 4096 Feb 16 09:57 .
drwxr-xr-x 326 root root 12288 Mar 27 11:43 ..
-rw-r--r-- 1 root root 938848 Oct 23 2011 american-english
-rw-r--r-- 1 root root 938969 Oct 23 2011 british-english
-rw-r--r-- 1 root root 199 Jan 14 2014 select-wordlist
#+END_SRC

리눅스 명령줄을 사용해 본 적이 있다면, 출력 결과가 매우 익숙하게 느껴질 것입니다. 이는 Emacs가 ~M-x grep~ 같은 다른 명령어들의 정신을 이어받아, 기존 명령줄 유틸리티의 출력 결과를 단순히 확장하기 때문입니다. 이 경우 대개 ~ls -al~ 명령을 사용하지만, ~dired-listing-switches~ 를 사용자 정의해서 적용되는 옵션을 변경할 수 있습니다.

#+BEGIN_QUOTE
*Microsoft Windows* :
Microsoft Windows를 사용한다면 걱정하지 않아도 됩니다.
Emacs는 엘리스프(Elisp)로 작성된 ls 에뮬레이션 레이어가 내장되어 있습니다.

Emacs는 ls 를 호출하는 대신 운영체제에 직접 쿼리를 보냅니다.
그 결과 플랫폼을 가리지 않고 원활하게 작동하는 인터페이스를 제공합니다.
#+END_QUOTE

앞서 언급했듯이, 버퍼(The Buffer) 개념과 Emacs의 “확장(augmentation)” 시스템은 외부 프로그램과 연동하는 강력하고 실용적인 방식입니다. Emacs가 ls 를 호출하면, 그 출력은 버퍼로 삽입되고, dired 모드가 활성화되며, Emacs가 텍스트를 자동으로 탐색할 수 있도록 돕기 위해 텍스트에 하이라이트, 하이퍼링크 및 기타 숨겨진 속성이 추가됩니다. 메이저 모드 자체가 키 바인딩을 제공하므로, 파일에서 ~RET~ 키를 누르면 해당 파일이 열립니다. 실제 다른 버퍼와 마찬가지로, dired 의 출력은 기본적으로 일반 텍스트로 그대로 복사할 수 있습니다.

대부분의 Emacs 초보자, 심지어 중급 사용자들조차 dired 를 제대로 다루지 못합니다. 대부분은 디렉터리를 탐색하는 정도를 넘어서지 못하는데, 이는 매우 안타까운 일입니다. 왜냐하면, 단순해 보이는 겉모습 뒤에는 파일 및 디렉터리 작업을 위한 매우 복잡하고 효율적인 시스템이 숨어 있기 때문입니다. 실제로, 수백 가지의 dired 명령어와 수십 가지의 다른 명령어와의 연동 기능이 dired 인터페이스와 매끄럽게 연동되어 작동합니다.


*** Navigation
dired 의 탐색 기능은 꽤 직관적이며, 버퍼이기 때문에 Isearch, 화살표 키, 마우스 등 평소 사용하던 모든 탐색 도구를 그대로 사용할 수 있습니다.

| 키               | 설명                           |
|------------------+--------------------------------|
| ~RET~            | 파일 또는 디렉터리를 열기      |
| ~^~              | 한 단계 위 디렉터리로 이동     |
| ~q~              | dired 종료                     |
| ~n, p, C-n, C-p~ | 커서를 목록에서 위/아래로 이동 |

하지만, 현재 디렉터리의 상위 디렉터리로 한 단계 이동하려면 ~^~ 키를 사용해야 합니다. ~C-n~ 및 ~n, C-p~ 및 ~p~ 명령은 한 줄씩 위나 아래로 이동할 뿐만 아니라, 포인터를 파일 이름 바로 앞에 위치하도록 재조정합니다.

~RET~ 키를 누르면 Emacs는 해당 파일이나 디렉터리를 열며, 디렉터리인 경우 새로운 dired 버퍼가 열립니다. 따라서, 하위 디렉터리를 열고 난 후 ~q~ 를 누르면 마지막으로 열었던 dired 버퍼로 돌아갈 수 있습니다.


*** Marking and Unmarking
여러 파일이나 디렉터리에 어떠한 작업을 수행하려면 항목에 체크 표시를 하거나 해제하는 작업을 자주할 것입니다.

| 키  | 설명           |
|-----+----------------|
| ~m~ | 선택 상태 표시 |
| ~u~ | 선택 상태 해제 |
| ~U~ | 모두 선택 해제 |
| ~d~ | 삭제 표시      |

표시(marking)와 삭제 표시(flagging for deletion)는 반드시 구분해서 사용해야 합니다. ~d~ 는 삭제 표시를 의미하며(표시된 항목 옆에 =D= 가 표시됨), ~m~ 은 표시를 의미합니다. 표시된 파일은 삭제 명령의 영향을 받지 않으며, 그 반대의 경우도 마찬가지입니다. 단, 표시된 파일을 삭제하는 특정 명령 하나는 예외입니다. 표시된 파일은 ~*~ 로 강조 표시됩니다.

표시 및 삭제 표시 모두 커서를 다음 항목으로 이동시킵니다(마치 ~C-n~ 을 입력한 것처럼), 하지만, 음수 인수를 사용하면 이동 방향을 반대로 바꿀 수 있습니다.

#+BEGIN_QUOTE
*Discover more* :
dired 는 명령어가 너무 많아 모두 나열하는 것은 불가능합니다.
나머지 명령어들은 평소처럼 탐색적인 접근 방식
(즉, 모드 설명, 접두사에 바인딩된 키 목록 확인 등)을 이용해서
직접 찾아보시길 권장합니다.

또는, Emacs에 설명이 포함된 팝업 메뉴를 추가해 주는
저의 패키지인 Discover 를 사용할 수도 있습니다.

또한 저의 웹사이트를 방문하시면 다양한 dired 기능을
매우 상세하게 다루는 글들을 찾아보실 수 있습니다.
#+END_QUOTE

특정 항목을 표시하는 마크 명령어도 있습니다:

| 키       | 설명                             |
|----------+----------------------------------|
| ~* m~    | 영역 표시                        |
| ~* u~    | 영역 표시 해제                   |
| ~* %~    | 정규 표현식을 사용해서 파일 표시 |
| ~* .~    | 확장자를 기준으로 파일 표시      |
| ~t, * t~ | 표시 상태 전환                   |
| ~* c~    | 표시 변경                        |

접두사 키 ~*~ 는 다양한 마크 명령이 포함되어 있습니다. 위에 나열된 것은 일상적으로 사용하기에 가장 실용적인 네 가지 명령입니다. 영역 키들은 활성 영역이 닿는 모든 dired 항목을 표시하거나 표시를 해제합니다. 정규식 및 확장자 표시 명령도 마찬가지로 유용하며, ~* t~ 를 사용해서 표시 상태를 토글(반전)할 수 있습니다.

~* c~ 는 매우 특별한 기능입니다. 이 명령은 마크 기호를 기존 기호에서 새로운 기호로 변경합니다. 따라서, ~*~ (기본 마크 기호)를 ~D~ 로 변경해서 마크된 파일을 삭제 표시된 파일로 바꿀 수 있습니다. 하지만, 삭제 표시된 파일로 처리할 수 있는 작업은 사실상 삭제 뿐이므로, 삭제 표시된 파일을 삭제하는 전용 명령과 마크된 파일도 삭제하는 또 다른 명령이 따로 있습니다.


*** Operations
작업(또는 연산)은 현재 선택된 항목(디렉터리에 선택된 파일이 없는 경우)이나, 선택된 파일이 있는 경우 해당 파일들에 대해 수행할 수 있습니다.

선택된 파일에 작업을 수행할 때, Emacs는 대개 작업 확인을 요청하고 영향받는 파일 목록을 표시합니다. 선택 명령어와 마찬가지로 수행할 수 있는 작업은 다양합니다. 먼저 기본적인 작업들을 살펴보겠습니다:

| 키(마크 표시됨) | 설명                             |
|-----------------+----------------------------------|
| ~C~             | 파일 복사                        |
| ~R~             | 파일 이름 변경 또는 이동         |
| ~O~             | 소유자 변경                      |
| ~G~             | 그룹 변경                        |
| ~M~             | 권한 변경                        |
| ~D~             | 표시된 파일 삭제 (*로 표시됨)    |
| ~x~             | 표시된 파일 삭제 (D로 표시됨)    |
| ~F~             | 파일 열기 (dired-x 필요)         |
| ~c~             | 표시된 파일을 하나의 파일로 압축 |

위의 키들은 대부분 설명이 필요없을 정도로 매우 직관적입니다. 파일을 삭제하려면 ~x~ 와 ~D~ 의 차이점만 기억하면 됩니다.

#+BEGIN_QUOTE
*Copying or renaming between dired buffers* :
~dired-dwim-target~ 옵션을 사용자 정의하면 두 개의 dired 버퍼 간에
파일을 복사하거나 이름을 변경(이동)할 수 있습니다.

실수로 열어둔 채 잊고 있던 다른 dired 버퍼로 파일을 옮기지 않도록
주의하시기 바랍니다. 저도 그런 실수를 꽤 여러 번 저질렀거든요!
#+END_QUOTE

또한 표시된 파일에 적용되지 않는 키들도 있습니다:

| 키     | 설명                      |
|--------+---------------------------|
| ~g~    | 디렉터리 버퍼 새로 고침   |
| ~+~    | 하위 디렉터리 생성        |
| ~s~    | 이름/날짜 정렬 전환       |
| ~<, >~ | 이전/다음 디렉터리로 이동 |
| ~j~    | 파일로 이동               |

#+BEGIN_QUOTE
*Dired-X* :
일부 명령어는 ~dired-x~ 가 필요합니다.
이 패키지는 어떤 타당한 이유없이 기본적으로 활성화되지 않아서
안타깝게도 수동으로 활성화해야 합니다.

이 설정이 적용되도록 초기화 파일(init 파일)에 다음을 추가합니다:

~(require 'dired-x)~
#+END_QUOTE

~dired-x~ 가 설치되면, 마크된 모든 파일을 순차적으로 확인하는 ~F~ 명령을 사용할 수 있습니다. 중요한 점은, 이 명령은 파일을 열려고 시도하며 각 파일에 별도의 창을 할당한다는 것입니다. 이는 원치 않는 상황일 수 있습니다. 이를 피하고 파일을 백그라운드에서 열려면 ~C-u F~ 를 입력합니다.

| 키(마크 표시됨) | 설명                     |
|-----------------+--------------------------|
| ~M-s~ 및 ~C-s~  | iSearch 시작             |
| ~Q~             | Xref Query로 regexp 대체 |
| ~A~             | Xref 검색 regexp 검색    |
| ~!~             | 동기식 셸 명령           |
| ~&~             | 비동기식 셸 명령         |

때때로 파일 내의 텍스트를 검색하거나 바꿔치울 때가 있는데, 다소 다루기 까다로운 키 바인딩인 ~M-s a C-s~ 를 사용해서 여러 파일을 한 번에 검색할 수 있습니다. ~Q~ 명령어는 마크된 모든 파일에 ~C-M-%~ –정규식 검색 및 교체–를 실행합니다. 하지만, 변경 사항을 저장하는 것을 잊지 마시기 바랍니다(~C-x s~ 를 누르면 저장되지 않은 모든 버퍼에 대해 저장 여부를 묻는 메시지가 표시됩니다).

~!~ 를 마크없이 호출하면, ~dired-xis~ 가 활성화된 경우 해당 파일에 대한 다음 작업을 추측하려고 시도합니다. 예를 들어 ~.zip~ 파일인 경우, 압축을 풀 것인지를 묻습니다. ~.patch~ 파일인 경우, Emacs는 해당 파일에 patch 명령을 실행합니다. ~dired-guess-shell-alist-default~ 변수는 많은 패턴이 지정되어 있습니다. 이는 시간을 많이 절약해 줍니다.

마크가 활성화된 상태에서 ~!~ 와 ~&~ 를 누르면 사용자가 선택한 외부 명령을 호출합니다. 또한 Emacs에 마크된 항목을 명령에 어떻게 전달할지 알려주어야 합니다:

*표시된 항목당 하나의 명령* : 이 모드는 Emacs가 마크된 각 항목에 대해 사용자가 선택한 명령을 한 번씩 호출합니다.

*표시된 모든 항목에 대한 하나의 명령* : 이 경우 Emacs는 마크된 각 항목을 공백으로 구분해서 단일 명령에 전달합니다.

일부 명령은 실행하는 데 시간이 오래 걸릴 수도 있으므로, Emacs가 명령을 동기식으로 호출해서 완료될 때까지 Emacs를 대기 상태로 만들지(~!~ 사용), 아니면 명령을 비동기식으로 실행하도록 지정할지(~&~ 사용) 결정해야 합니다.

다음은 실제 예입니다. /american-english/ 와 /british-english/ 라는 두 파일을 가정합니다. 셸 명령을 어떻게 작성하느냐에 따라 동작은 달라집니다. 선택적으로 ~*~ 또는 ~?~ 를 지정해서, 각 선택 항목마다 하나의 명령을 실행할지, 아니면 모든 선택 항목에 대해 하나의 명령을 실행할지 지정할 수 있습니다.

~*~ 는 셸의 파일 글로브(glob) 패턴처럼 작동하며, Emacs는 선택된 모든 파일을 하나의 긴 인수로 단일 명령에 삽입합니다:

~echo *~

출력 결과:

~american-english british-english~

이것은 Emacs가 선택된 두 항목 모두를 포함해서 명령을 한 번만 실행했기 때문입니다.

반면 ~?~ 를 사용하면 마크된 각 항목에 대해 명령이 실행됩니다:

~echo ?~

이때 출력은 다음과 같습니다:

#+BEGIN_SRC
american-english
british-english
#+END_SRC

출력이 있는 경우, 몇 줄에 불과하다면 echo 영역에 표시됩니다. 그렇지 않은 경우, ~*Shell Command Output*~ 또는 ~*Async Shell Command*~ 라는 전용 버퍼로 리디렉션됩니다. 


*** Working Across Directories
디렉터리를 새로운 dired 버퍼로 여는 대신, 기존 dired 버퍼에 해당 내용을 삽입하도록 설정할 수 있습니다. 디렉터리에 커서를 두고 ~i~ 를 입력하면, dired 는 이를 하위 디렉터리로 동일한 dired 버퍼에 삽입합니다. 즉, 동일한 dired 버퍼에 있는 한, 여러 dired 디렉터리에 걸쳐 동일한 마크 및 플래그 명령을 사용할 수 있습니다. ~$~ 명령어를 사용하면 하위 디렉터리를 접을 수 있으며, 접혀있는 동안엔 해당 디렉터리에 명령어가 적용되지 않습니다.

여러 디렉터리를 하나의 공유 dired 버퍼에 삽입하면, 여러 디렉터리를 동시에 한 눈에 볼 수 있을 뿐만 아니라, 마치 하나의 커다란 디렉터리인 것처럼 작업할 수도 있습니다. 이는 Emacs의 강력하지만 제대로 활용되지 않는 또 다른 기능입니다. 하지만, ~i~ 를 입력하는 것은 번거로울 뿐만 아니라, dired 또는 셸 명령을 재귀적으로 적용할 경우는 제대로 작동하지 않으므로 다른 접근 방식이 필요합니다.

이 문제를 해결하려면 Emacs의 find 래퍼 명령을 사용할 수 있습니다. 저는 이런 명령들이 dired 의 강력한 기능과 결합되면 find 와 xargs 를 직접 사용하는 것을 거의 완전하게 대체할 수 있다고 생각합니다. dired 의 셸 명령어 지원과 광범위한 파일 조작 기능을 활용하면, 대부분의 사용자가 find 를 사용해서 제대로 수행하기 어려워하는 작업도 Emacs에서 처리할 수 있습니다.

모든 명령어는 find 의 출력을 받아서 시작 디렉터리를 기준으로 dired 버퍼를 생성합니다. Emacs는 버퍼의 파일 이름 부분에 포함된 상대 경로를 자동으로 인식할만큼 똑똑합니다. dired 내의 모든 명령어는 평소와 같이 작동합니다.

| 키                     | 설명                                         |
|------------------------+----------------------------------------------|
| ~find-dired~           | 패턴을 지정해서 find 명령을 실행합니다       |
| ~find-name-dired~      | -name 옵션을 사용해서 find 명령을 실행합니다 |
| ~find-grep-dired~      | find 와 grep 을 함께 실행합니다              |
| ~find-lisp-find-dired~ | Emacs와 정규식을 사용해서 파일을 찾습니다    |

처음 세 개 명령어는 명령줄 유틸리티인 find 를 호출합니다. ~find-dired~ 는 grep 명령어와 마찬가지로 가장 기본적인 명령어입니다. 이 명령어는 find 패턴과 시작 디렉터리를 지정해야 합니다. ~find-name-dired~ 는 사용자가 지정한 특정 디렉터리에서 시작해서 파일 이름에 대해서만 셸 글로브 패턴을 사용해서 검색합니다. ~find-grep-dired~ 는 모든 파일을 검색하지만, grep 에 전달된 패턴과 일치하는 파일만 표시합니다.

#+BEGIN_QUOTE
*Microsoft Windows* :
Microsoft Windows는 GNUWin32나 Cygwin 같은 크로스 컴파일된 바이너리를
설치하거나 ~find-lisp-find-dired~ 를 사용할 수 있습니다.
#+END_QUOTE

~find-lisp-find-dired~ 명령어는 Emacs의 elisp로 구현된 ~find-dired~ 입니다. 이 명령어는 모든 플랫폼에서 작동하며 별도의 외부 도구가 필요하지 않습니다. 대신, 기능 면에서는 그다지 강력하지 않습니다. 또한, 셸 글로빙(globbing)이 아닌 Emacs의 정규 표현식 엔진을 사용합니다.



** Shell Commands
dired 에 관한 장에서 살펴본 것 같이, Emacs는 셸과 연동되는 강력한 명령어들이 있습니다. 그 외의 모든 버퍼의 경우, 일반적인 버퍼에서 작동하는 훨씬 더 포괄적이면서도 강력한 셸 명령어들이 있습니다.

| 키            | 설명                                          |
|---------------+-----------------------------------------------|
| ~M-!~         | 셸 명령을 호출하고 출력을 표시합니다          |
| ~C-u M-!~     | 위와 같으나, 버퍼에 내용을 삽입합니다         |
| ~M-&~         | ~M-!~ 와 같으나 비동기적으로 실행됩니다       |
| ~C-u M-&~     | ~C-u M-!~ 와 같으나 비동기적으로 실행됩니다   |
| ~M-\vert~     | 선택한 영역을 셸 명령으로 파이프합니다        |
| ~C-u M-\vert~ | ~M-\vert~ 와 같으나, 선택한 영역을 대체합니다 |

~M-!~ 를 사용해서 어떤 셸 명령이든 호출할 수 있으며, 텍스트가 몇 줄에 불과한 경우 Emacs는 출력 결과를 에코 영역에 표시합니다. ~M-!~ 를 사용한 경우는 ~*Shell Command Output*~ 이라는 전용 버퍼에, ~M-&~ 를 사용한 경우는 ~*Async Shell Command*~ 버퍼에 출력됩니다. 두 명령 중 하나를 범용 인자와 함께 호출하면, 현재 버퍼의 커서 위치에 출력 결과를 삽입합니다.

~M-|~ 명령은 훨씬 더 실용적입니다. 이 명령은 선택된 영역을 입력으로 받아 사용자가 지정한 셸 명령의 표준 입력으로 보내며, ~M-!~ 와 거의 동일한 방식으로 출력을 반환합니다: 즉, 에코 영역이나 전용 버퍼에 출력합니다. 범용 인수를 사용해서 명령을 호출하면, 활성 영역이 대체됩니다. 이는 uniq 나 입력을 수정하는 다른 명령줄 도구 같은 명령을 즉석에서 호출할 때 ~C-u M-|~ 을 훌륭하게 만들어 줍니다.

~M-&~ 는 비동기적이라서(즉, 명령이 종료될 때까지 Emacs를 블록하지 않음) 장시간 실행되는 작업에 적합하지 않습니다. ~M-x compile~ 을 사용하는 것이 훨씬 더 낫습니다.


*** Compiling in Emacs
셸 명령어를 호출하는 것은 빠르고 일회성인 명령에 적합하며, 일반적으로 반복적으로 자주 수행하는 작업은 아닙니다. 그런 목적으로는 이름과는 달리 단순한 컴파일 이상의 기능을 뛰어나게 수행하는 Emacs의 ~M-x compile~ 명령어를 고려하시기 바랍니다.

| 명령어             | 설명                                    |
|--------------------+-----------------------------------------|
| ~M-x compile~      | 명령을 실행하고 오류를 추적합니다       |
| ~M-x recompile~    | 마지막 명령을 다시 실행합니다           |
| ~M-g M-n, M-g M-p~ | 다음/이전 오류 위치로 이동합니다 (전역) |
| ~g~                | 마지막 명령을 다시 실행합니다           |
| ~C-x p c~          | 현재 프로젝트에서 컴파일합니다          |

~M-x compile~ 을 호출하면 명령어를 입력하라는 메시지가 나타나며, Emacs는 사용자가 make 를 사용한다고 가정합니다. 하지만, 출력을 추적하고 싶은 명령어라면 무엇이든 자유롭게 대입할 수 있습니다: 단위 테스트, 컴파일, 스크립트 실행 등 무엇이든 가능합니다.

~M-x compile~ 의 가장 큰 장점은 보조 명령어인 ~M-x recompile~ 로, 이 명령어는 마지막으로 실행한 명령을 다시 실행합니다. 또한 Compile 은 패턴 매칭 엔진 덕분에 오류도 추적합니다. ~M-x grep~ 및 ~M-x occur~ 와 마찬가지로, ~M-g M-n~ 및 ~M-g M-p~ 명령어는 호출 스택이나 컴파일러 오류 로그를 탐색할 수 있으며, 해당 형식이 Emacs가 인식하는 형식과 일치하는 경우에 한합니다. 파이썬부터 대부분의 컴파일러에 이르기까지 모든 것이 Emacs에 알려져 있으므로, 여러분이 사용하는 컴파일러도 아마 작동할 것입니다.



** Shells in Emacs
외부 터미널 에뮬레이터를 사용하거나, tmux 나 screen 과 함께 쓰기 위해 터미널에서 Emacs를 실행하는 대신, Emacs를 “멀티플렉서” 로 활용해서 Emacs 내에서 셸을 실행하는 건 어떨까요? TRAMP 와 Emacs의 타일형 창 관리 및 버퍼 기능을 결합하면, 전용 터미널 에뮬레이터의 거의 모든 일반적인 사용 사례를 대체할 수 있습니다.

Emacs에서 bash 같은 셸을 사용하는 방법에는 세 가지가 있습니다. 하나는 ~M-x shell~ 이라 불리는, 외부에 존재하는 기존 셸(예: bash)을 단순히 감싸는 래퍼 방식입니다. 또 다른 방법은 ~M-x eshell~ 이라 불리는, Lisp으로 작성된 완전한 셸 구현체입니다. 그리고 세 번째는 ~M-x ansi-term~ 이라 불리는 터미널 에뮬레이터입니다.

세 가지 모두 매우 강력하며, 각각 고유한 방식으로 문제를 해결하려 시도합니다. 어떤 것을 사용하든 (결국 하나 이상을 사용할 수도 있습니다) 여러 가지 장단점이 따릅니다.

그러나, 이 세 가지 모두 elisp를 사용해서 외부 프로그램과 통신하거나, Emacs 내에서 셸을 구현하거나, top 같은 복잡하고 대화형인 프로그램을 렌더링하는 데 필요한 터미널 제어 코드를 해석합니다. 또한 세 가지 모두 지금쯤이면 여러분이 꽤 익숙해졌을 Emacs의 강력한 버퍼 패러다임을 사용해서 세 가지 구현체 모두에 대한 통합된 인터페이스를 제공합니다.

버퍼 패러다임은 특히 여기서 강력한데, 외부 프로그램이나 운영체제와 직접 통신할 수 있는 기능이 바로 Emacs를 그토록 강력한 편집기로 만드는 요소 중 하나이기 때문입니다. 텍스트 편집 같은 전통적인 용도로도 사용되지만, 이제 bash와의 상호작용 같은 훨씬 더 고급스럽고 특화된 작업까지 활용되는 버퍼에서 모든 편집 및 이동 명령과 elisp의 강력한 기능을 활용할 수 있습니다. 그리고 이 두 극단적인 용도가 버퍼라는 공통 기반을 공유하기 때문에, 완전히 새로운 시스템을 다시 배울 필요가 없습니다. 텍스트 편집기나 웹 브라우저로 복사하기 위해 터미널 에뮬레이터에서 마우스로 텍스트를 일일이 선택하는 번거로움도 더 이상 없습니다. Emacs는 모든 것이 텍스트이며, 여러분이 익숙한 모든 이동 및 편집 명령이 여기서도 정확히 동일하게 작동합니다.


*** M-x shell : Shell Mode
Emacs의 셸 모드는 외부 프로그램(예: Linux의 bash 나 Windows의 cmd.exe)을 호출하며, Windows는 stdin, stdout, stderr 를 재지정하거나(리디렉션), Linux는 의사 터미널을 통해 Emacs를 통해 기본 셸과 상호작용할 수 있도록 해줍니다.

하지만, Emacs가 I/O를 리디렉션하기 때문에, 이에 따르는 장점과 단점을 감수해야 합니다. 예를 들어, 셸 고유의 TAB 자동 완성 기능을 사용할 수 없습니다. 대신 Emacs 자체의 자동 완성 기능을 사용해야 하는데, 이는 어떤 면에서는 좀 더 강력합니다. 반대로 셸 모드 버퍼는 완전히 텍스트로 구성되므로, 명령어의 출력을 편집하고 삭제할 수 있으며, 버퍼 안팎으로 텍스트를 복사하고 붙여넣는 것도 손쉽게 처리할 수 있습니다. 이로 인해 셸 모드는 유연하지만 호불호가 갈립니다. top 이나 man 같은 프로그램은 작동하지 않거나, 작동하더라도 제대로 동작하지 않습니다.

저는 개인적으로 거의 모든 명령줄 작업에 셸 모드를 사용합니다. 대화형 터미널 프로그램은 거의 사용하지 않으며, 정말 필요할 때는 Emacs의 ~M-x ansi-term~ 을 사용해서 제대로 된 터미널 에뮬레이션을 이용할 수 있습니다.

*장점* : 셸 모드는 단순한 버퍼에 불과하기 때문에 자유로운 텍스트 편집과 이동이 가능하다는 점이 단점보다 더 큽니다.

#+BEGIN_QUOTE
*GNU readline and defaults* :
대부분의 리눅스 배포판은 GNU readline 라이브러리를 사용해서
명령어 기록, 검색 및 교체, 고급 이동 및 편집 같은
기본적인 명령 프롬프트 기능을 제공합니다.

기본적으로 이런 기능은 Emacs 키 바인딩을 통해 사용할 수 있습니다.
#+END_QUOTE

다음은 가장 흔히 사용되는 명령어 몇 가지입니다. 아쉽게도 키 바인딩은 제각각입니다.

| 키                 | 설명                                             |
|--------------------+--------------------------------------------------|
| ~M-p, M-n~         | 명령어 이력을 순환합니다                         |
| ~C-<위>, C-<아래>~ | 명령어 이력을 순환합니다                         |
| ~M-r~              | 이력을 역방향으로 검색합니다                     |
| ~C-c C-p, C-c C-n~ | 이전/다음 프롬프트로 이동합니다                  |
| ~C-c C-s~          | 명령어 출력을 파일에 저장합니다                  |
| ~C-c C-o~          | 명령어 출력을 킬 링(kill ring)으로 보냅니다      |
| ~C-c C-l~          | 명령어 이력을 나열합니다                         |
| ~C-d~              | 현재 위치의 문자를 삭제하거나 ~^D~ 를 전송합니다 |
| ~C-c C-z~          | 서브 작업 중지 신호를 전송합니다                 |
| ~TAB~              | 현재 위치에서 자동 완성합니다                    |

~M-p, M-n, C-<up>, C-<down>~ 은 모두 일반 터미널 에뮬레이터에서 위/아래 화살표 키를 사용할 때와 거의 동일한 방식으로 명령어 이력을 순환합니다. Emacs는 이 키들이 버퍼 내에서 커서를 실제로 이동시키지만, 셸 모드에 익숙하지 않은 사용자들은 이를 보고 항상 헷갈려 합니다.

~M-r~ 은 이력 역방향 Isearch 를 실행합니다. 이 명령은 매우 강력해서 배워둘 가치가 충분히 있습니다. ~C-d~ 는 다른 곳과 마찬가지로 커서 앞의 문자를 삭제합니다. 하지만, 입력 내용이 없는 경우(즉, 프롬프트에 아무것도 입력하지 않은 경우), Emacs는 EOF 제어 코드를 전송해서 현재 실행 중인 프로그램을 종료합니다. 마찬가지로, ~C-c C-z~ 는 bash에서 작업 제어를 위해 사용하는 ~C-z~ 와 동일한 기능을 수행합니다.

셸 모드의 멋진 기능 중 하나는 ~C-c C-s~ 를 사용해서 마지막 명령의 출력을 파일에 저장하거나, ~C-c C-o~ 를 사용해서 그 내용을 킬 링(kill ring)으로 보낼 수 있다는 점입니다.

~TAB~ 키는 별도로 언급할 가치가 있습니다. bash 같은 셸은 파일 경로뿐만 아니라 자체적인 복잡한 자동 완성 메커니즘을 갖추고 있습니다. Emacs도 마찬가지입니다. ssh 같은 명령어의 호스트명이나 chown 명령어의 그룹 및 소유자 등을 자동 완성할 수 있습니다.


*** M-x ansi-term : Terminal Emulator
Emacs는 ANSI를 지원하는 터미널 에뮬레이터입니다. ~M-x ansi-term~ 을 실행하고 셸을 선택하면, top 이나 심지어 vim, emacs 같은 대화형 프로그램을 실행할 수 있습니다.

이 에뮬레이터의 가장 큰 단점은 속도가 느리다는 점이며, 일부 잘 알려지지 않은 터미널 에뮬레이션 기능은 지원되지 않습니다.

| 키        | 설명             |
|-----------+------------------|
| ~C-c C-j~ | 라인 모드로 전환 |
| ~C-c C-k~ | 문자 모드로 전환 |

기본적으로 ~ansi-term~ 은 셸 모드나 일반적인 Emacs 버퍼가 아닌 일반 터미널 에뮬레이터처럼 작동합니다. 하지만, 두 가지 모드, 즉 일반적인 Emacs 버퍼와 유사한 ‘라인 모드’ 와 일반 터미널 에뮬레이터와 유사한 ‘캐릭터 모드’ 사이를 전환할 수 있습니다.

기본 모드는 문자 모드이며, 이는 키보드 문자를 포함해서(단순히 Emacs 키 바인딩뿐만 아니라) 대부분의 키 입력이 Emacs를 완전히 우회해서 기본 셸 프로그램으로 직접 전송된다는 것을 의미합니다. ~C-c~ 라는 이스케이프 문자가 있는데, Emacs가 이를 가로채기 때문에 ~C-c C-j~ 나 ~C-c C-k~ 같은 명령은 하위 프로그램으로 전송되지 않습니다. 따라서, ~C-c~ 를 하위 프로그램으로 보내려면 ~C-c C-c~ 를 입력해야 합니다.

Emacs에서 가장 실제 터미널과 유사한 환경을 원한다면, ANSI term이 최선의 선택입니다. 저는 라인 모드와 문자 모드 사이를 전환하는 번거로움이 꽤 귀찮게 느껴져서, 대신 셸 모드를 사용하는 것을 선호합니다.


*** M-x eshell : Emacs’s Shell
누군가가 Lisp으로 셸 전체를 구현했다는 사실은 그다지 놀라운 일도 아닙니다. ~M-x eshell~ 을 실행하면, Elisp로 작성된 셸을 사용하는데, 이 셸은 Emacs를 통해 기본 호스트 운영체제와 통신하며, ls, cp, cd 등 Elisp로 에뮬레이트된 GNU coreutils 명령어를 포함한 전형적인 리눅스 스타일의 bash 셸을 훌륭하게 재현해 줍니다.

실질적으로 이는 Emacs가 실행되는 모든 플랫폼에서 일관된 셸 환경을 제공한다는 것을 의미합니다. 네이티브 TRAMP 지원 및 명령어 출력을 Emacs 버퍼로 직접 리디렉션하는 기능과 결합되어, 다재다능하고 강력하며 Emacs의 정신을 충실히 반영한 도구를 갖게 됩니다.

Eshell 은 ANSI-term 보다는 쉘 모드에 좀 더 가깝습니다. top 같은 대화형 프로그램을 지원하지 않으며, 대신 Eshell에서 해당 프로그램을 호출할 때 전용 ~M-x ansi-term~ 인스턴스를 열어 실행하는 방식을 선호합니다. 이는 문제에 대한 영리하고 실용적인 해결책입니다.

또 다른 중요한 차이점은, Eshell이 bash 같은 셸에서 영감을 받았지만, 사실은 그 자체만의 셸 구현체로서 그에 따르는 모든 특이점, 기능 및 한계를 고유하게 지니고 있다는 점입니다. Eshell은 무엇보다 elisp 셸이라는 점을 명심해야 합니다. Eshell에 입력하는 모든 명령은 먼저 Eshell 고유의 에뮬레이션 레이어를 거쳐, 그 다음 Emacs 고유의 대화형 명령을 통과한 뒤, 마지막으로 ~$PATH~ 에 있거나 현재 디렉터리에 있는 프로그램을 통해 처리되기 때문입니다. 예를 들어, ~dired .~ 을 입력하면 현재 디렉터리에서 ~M-x dired~ 세션을 열 수 있고, ~find-file todo.org~ 를 입력하면 현재 실행 중인 Emacs에서 todo.org 파일을 열 수 있습니다.




* Chapter 7. Conclusion

#+BEGIN_QUOTE
“Emacs is the ground. We run around and actsilly
on top of it,and when we die, may our remnants grace
its ongoing incrementation.”

– Thien-Thi Nguyen, comp.emacs.
#+END_QUOTE

Emacs처럼 다재다능한 텍스트 편집기를 어떻게 마스터할 수 있을까요?

놀랍게도 해답은 간단합니다!! Emacs에게 올바른 질문을 하는 방법을 아는 것입니다. 제가 『운영체제로서의 Emacs』 장에서 말했듯이 Emacs의 구조 자체는 elisp를 통해 수정하거나 확장할 수 있습니다. 따라서, Emacs에서 무슨 일이 일어나는지 진정으로 이해할 수 있는 유일한 방법은 Emacs에게 직접 물어보는 것 뿐입니다!! 간단하지만 사실입니다.

그리고 이맥스에게 질문하는 것은 모든 이맥스 고수들도 하는 일입니다. 어떤 키에 어떤 기능이 할당된지 확인하든 명령어가 정확히 무엇을 처리하는지 확인하든 이는 이맥스 숙달을 위한 핵심 요소입니다. 물론 엘리스프(Elisp)에 대한 지식도 도움되지만 반드시 필요한 전제 조건은 아닙니다.

이 책 전체에 걸쳐 저는 기능과 함수 그리고 무엇에 집중할 가치가 있고 무엇은 그렇지 않은지에 대한 저만의 개인적인 견해를 적어왔습니다. 바로 이것이 이 책의 진정 실용적이고 포괄적인 측면입니다. 좀 더 깊은 교훈이자 제가 처음 Emacs를 배우기 시작했을 때의 결정적인 전환점이 된 것은 Emacs에게 어떻게 질문하는지? 를 제대로 이해한 것입니다.

키나 명령어를 기억하지 못하는 것은 극히 자연스러운 현상이며 특히 배우는 중이라면 더 더욱 그렇습니다. 하지만, 키 바인딩을 대대적으로 수정하거나 변경했더라도 Emacs가 자신의 기능을 알려줄 수 있다는 사실을 안다는 것은 궁극적으로 Emacs를 마스터하는 데 도움됩니다. ~C-x r l~ 키가 무엇을 처리하는지 잊어버린 것은 ~C-h k~ 로 알아낼 수 있다면 중요하지 않습니다. 그리고 어떤 기능이 무엇을 처리하는지 부분만 기억해도 접두사 키에 ~C-h~ 를 붙여 그 키에 바인딩된 모든 키를 설명할 수 있다면 그 역시 중요하지 않습니다.

모든 Emacs 사용자의 장기적인 목표는 자신의 질문에 대한 답을 Emacs에게 물어볼 수 있는 단계에 도달하는 것입니다. 결국, 자주 사용하는 명령어와 키는 무의식적으로 익힐 것이고 나머지는 언제든지 찾아볼 수 있으니까요...

Emacs를 오래 사용하면–이미 그 단계에 도달한 분은 제 말에 동의하실 겁니다–어느 날 갑자기 모든 것이 딱 맞아 떨어집니다. 그리고 바로 그럴 때 그것은 수천 개의 키 바인딩을 외웠기 때문이 아닙니다. 그것은 Emacs가 더이상 불투명한 상자가 아니라 내부를 훤히 들여다보고 수정하며 그 변화의 결과를 관찰할 수 있는 매우 개방적이고 투명한 상자이기 때문입니다.

이 책의 집필 순서는 누군가가 제 옆에서 Emacs를 배우는 것처럼 제가 가르칠 때와 동일한 방식으로 구성되어 있습니다. 먼저 용어를 이해하는 것은 기초를 다지는 중요한 일입니다; 그 다음은 Emacs를 사용할 수 있는 기본적인 키와 명령어입니다; 그 다음은 이동 및 편집 명령어이며 이어서 배운 내용을 확고히 하고 앞으로 어떻게 나아갈지에 대한 아이디어를 얻을 수 있도록 도와주는 몇 가지 실전 예제가 나옵니다.

마지막으로 이 책에 더 배울 것이 없다고 느껴질 때는 어떻게 할지에 대해 잠시 언급하겠습니다. 그 다음 단계는 엘리스프(Elisp)를 배우는 것입니다. 비록 이 LISP 방언이 현대적인 LISP 언어의 화려한 기능을 많이 결여하고 있지만 여전히 아주 재미있는 언어입니다. LISP 언어를 배우면 까다로운 구세대 프로그래머들이 왜 “현대적인” 프로그래밍 언어를 LISP의 열등한 버전이라 비난하는지 이해할 것입니다. 그리고 그들의 말도 어느 정도는 맞습니다. LISP의 ‘데이터-에즈-코드(data-as-code)’ 개념이 어떻게 작동하는지 본다면—Emacs의 모든 곳에 이 개념이 사용되므로 반드시 보게 됩니다—왜 좀 더 일찍 배우지 않았는지 후회할 것입니다.

*추천 자료* : 제 블로그의 'Mastering Emacs' 는 이 다음 단계에 읽어볼만한 심도있는 글들이 가득합니다. IDO나 Emacs의 Eshell 같은 타사 패키지는 해당 웹사이트에 상세히 설명되어 있습니다.

[[https://www.masteringemacs.org/]]



** Other Resources

*** Third-Party Packages and Tools
저도 여러 타사 패키지를 사용합니다. 제가 흥미롭게 생각하는 몇 가지만 간략히 나열하겠습니다.

- *nov* :: Emacs용 훌륭한 EPUB 리더로 이 책을 읽을 때 사용하시길 권합니다.

[[https://depp.brause.cc/nov.el/]]

- *Magit* :: 독특한 코드 기반의 키 시스템을 갖춘 훌륭한 Git UI입니다.

[[https://www.magit.vc]]

- *Multiple Cursors* :: 여러 커서를 배치해서 동시에 편집할 수 있습니다.

[[https://github.com/magnars/multiple-cursors.el]]

- *LSP mode 와 EGlot* :: Emacs용 언어 서버 인터페이스입니다.

[[https://github.com/emacs-lsp/lsp-mode]]

[[https://github.com/joaotavora/eglot]]

- *Helm* :: 다양한 자동 완성 기능을 갖춘 강력한 자동 완성 프레임워크입니다.

[[https://emacs-helm.github.io/helm/]]

- *Flycheck* :: 코드 린팅 및 구문 오류 검사를 위한 범용 프레임워크로 수십 가지 도구가 사전 구성되어 제공됩니다.

[[https://www.flycheck.org/en/latest/]]

- *ORG Mode* :: 뛰어난 정리 도구이며 일기 및 일정 관리자, 리터러시 프로그래밍 도구 등 다양한 기능을 갖춘 프로그램입니다. 기본적으로 내장되어 있지만 반드시 웹사이트를 방문해서 설명서를 읽어보시기 바랍니다.

[[https://orgmode.org/]]

- *YASnippet* :: 텍스트 스니펫 확장 도구입니다.

[[http://joaotavora.github.io/yasnippet/]]

- *Hydra* :: 키 바인딩을 위한 유연한 팝업 UI를 구축할 수 있는 패키지입니다.

[[https://github.com/abo-abo/hydra]]

- *dumb-jump* :: 커서의 심볼 정의로 이동합니다. 프로젝트와 파일, 검색할 정의를 자동 추론합니다. 95%의 사용 사례로 충분히 유용합니다. ripgrep 과 함께 사용하시기 바랍니다.

[[https://github.com/jacktasia/dumb-jump]]

ripgrep 은 매우 빠르기 때문에 여러 번 추천했습니다. 또한, 기본적으로 ORG 모드를 포함하고 다양한 파일 형식도 지원합니다.


*** Communities
인터넷에는 수 많은 커뮤니티 사이트와 블로그가 있습니다. 다음은 제가 추천하는 몇 가지 목록입니다(모든 사이트를 포함하지 않습니다).

- *Reddit* :: ~/r/emacs~ 서브 레딧에는 활기찬 Emacs 사용자 커뮤니티가 있습니다. 제가 2015년에 이 책을 집필한 이후 엄청나게 성장했습니다. 또한, Emacs의 특정 분야를 다루는 전문 서브 레딧도 있습니다. ~/r/orgmode~ 도 방문할만 합니다.

- *StackExchange* :: 이제 Stack Exchange에 자체 사이트를 가집니다:

[[https://emacs.stackexchange.com/]]

질문하기 아주 좋은 곳입니다.

요즘엔 훌륭한 Emacs 관련 블로그도 많습니다. 저는 다음과 같은 블로그를 좋아합니다:

-  *Sacha Chua* :

[[https://sachachua.com/blog/]]

- *Irreal’s Emacs blog* :

[[https://irreal.org/blog/]]

- *Artur Malabarba* :

[[https://endlessparentheses.com/]]

- *Bozhidar Batzov* :

[[https://batsov.com/]]

- *John Kitchin* :

[[https://kitchingroup.cheme.cmu.edu/blog/]]

위의 블로그 대부분과 그 외의 많은 훌륭한 블로그는 Planet Emacs 애그리게이터에서 찾을 수 있습니다:

[[https://planet.emacslife.com/]]

- *Emacs* : 그리고 Emacs가 있습니다. 이는 과거, 현재 그리고 앞으로도 여러분의 Emacs에 대한 가장 권위있는 정보원입니다.

