#+TITLE: NextVI(1) General Command Manual   
#+AUTHOR: PilJin Kwon
#+EMAIL:  piljin.kwon@gmail.com

#+DESCRIPTION: 이 문서는 https://github.com/kyx0r/nextvi 문서의 한국어 버전입니다.
#+KEYWORDS:  vi, nextvi, ex-mode
#+LANGUAGE:  ko
#+OPTIONS:   H:4
#+TOC: headlines 2
#+TOC: tables

* NAME
*Nextvi - A small vi/ex terminal text editor*

* SYNOPSIS

     #+begin_src 
vi [-aemsv] [file ...]
     #+end_src

* DESCRIPTION
~Nextvi~ 는 1976년 Bill Joy가 유닉스 기반 시스템을 위해 처음 개발한 명령줄 텍스트 편집기 ~vi(1)~ 의 현대적인 클론입니다. Nextvi는 vi(1)의 여러 표준 기능을 기반으로 하며 사용자의 효율적인 텍스트 편집을 위해 일반 모드(/normal mode/), 삽입 모드(/insert mode/), 명령 모드(/command mode/) 를 전환할 수 있는 독특한 모달 인터페이스(/modal interface/)를 포함합니다.

추가 개선 사항은 제한 없는 매크로 시스템, 구문 강조, 키맵, 양방향 UTF-8 지원 및 그 밖의 수많은 기능이 포함됩니다. Nextvi는 매우 효율적이고 이식성이 뛰어나며 사용자 맞춤형으로 수정하기 쉬우므로 앞으로도 오랫동안 유용성과 높은 품질을 유지할 것입니다.

* OPTIONS
     ~-a~      대체 터미널 화면 활성화
     ~-e~      시작 시 ex 모드 진입
     ~-m~      초기 파일 읽기 및 메시지 비활성화
     ~-s~      시작 시 원시 ex 모드 진입
     ~-v~      모든 옵션 해제

* MANPAGE NOTATION
     ~<x>~     x가 문자 리터럴을 나타내는 클로저
     ~[x]~     x가 선택적 인자를 나타내는 클로저
     ~{x}~     x가 필수 인자를 나타내는 클로저
     ~“x”~     x가 문자열을 나타내는 클로저
     ~<^X>~    ~Ctrl~ 키와 ~X~ 를 의미함
     ~< >~     클로저 내의 대안들은 공백으로 구분
     ~#~       클로저 내의 10진수 표현
     ~x-y~     x부터 y까지의 범위

     
* VI NORMAL
     ~[#]j~          # 줄 아래로 이동
     ~[#]k~          # 줄 위로 이동
     ~[#]+~
     ~[#]<^M>~
     ~[#]<Enter>~    # 줄 아래로 이동, 커서를 들여쓰기 뒤 위치로 이동
     ~[#]-~          # 줄 위로 이동, 커서를 들여쓰기 뒤 위치로 이동
     ~[#]h~          # 열 왼쪽으로 이동
     ~[#]l~          # 열 오른쪽으로 이동
     ~[#]f{arg}~     arg 문자가 나타날 때까지 앞으로 #번 이동
     ~[#]F{arg}~     arg 문자가 나타날 때까지 뒤로 #번 이동
     ~[#]t{arg}~     arg 문자가 나타날 때까지 앞으로 #번 이동
     ~[#]T{arg}~     arg 문자가 나타날 때까지 뒤로 #번 이동
     ~[#],~          마지막 <f F t T> 이동을 #번 뒤로 반복
     ~[#];~          마지막 <f F t T> 이동을 #번 앞으로 반복
     ~[#]E~          단어 끝까지 #번 이동, 구두점 건너뛰기
     ~[#]e~          단어 끝까지 #번 이동
     ~[#]B~          구문의 시작 부분으로 #번 뒤로 이동, 구두점 건너뛰기
     ~[#]b~          구문의 시작 부분으로 #번 뒤로 이동
     ~[#]W~          구문의 시작 부분으로 #번 앞으로 이동, 구두점 건너뛰기
     ~[#]w~          구문의 시작 부분으로 #번 앞으로 이동
     ~vw~            <E e B b W w 공백 백스페이스>에 대한 단일 행 모드 전환
     ~[#](~          다음 문장 경계까지 #번 아래로 이동
     ~[#])~          다음 문장 경계까지 #번 위로 이동
     ~[#]{~          다음 <{> 섹션까지 #번 아래로 이동
     ~[#]}~          다음 <{> 섹션까지 #번 위로 이동
     ~[#][~          다음 <Newline> 섹션까지 #번 아래로 이동
     ~[#]]~          다음 <Newline> 섹션으로 #번 위로 이동
     ~^~             들여쓰기 후 줄 시작 부분으로 이동
     ~0~             줄 시작 부분으로 이동
     ~$~             줄 끝으로 이동
     ~[#]|~          #번째 열로 이동
     ~[#]<Space>~    #자 앞으로 이동
     ~[#]<^H>~
     ~[#]<Backspace>~  #개 문자를 뒤로 이동
     ~%~             가장 가까운 <] ) } [ ( {> 쌍으로 이동
     ~{#}%~          행 번호의 #퍼센트 지점으로 이동
     ~'{<mark>}~     행 마커로 이동
     ~`{<mark>}~     커서 위치와 일치하는 행 마커로 이동
     ~gg~            버퍼의 첫 번째 행으로 이동
     ~[#]G~          버퍼의 마지막 줄 또는 #번째 줄로 이동
     ~H~             화면의 가장 위쪽 줄로 이동
     ~L~             화면의 가장 아래쪽 줄로 이동
     ~M~             화면의 중간 줄로 이동
     ~z.~            커서 위치를 기준으로 화면 중앙 정렬
     ~z<^M>~
     ~z<Enter>~      상단 행을 기준으로 화면 중앙 정렬
     ~z-~            화면을 맨 아래 줄에 중앙 정렬
     ~[#]<^E>~       1줄 또는 #줄 아래로 스크롤하며, #과 커서 위치를 유지
     ~[#]<^Y>~       1줄 또는 #줄 위로 스크롤하며, #과 커서 위치를 유지
     ~[#]<^D>~       화면 크기의 절반만큼 아래로 스크롤. [#]인 경우, 스크롤을 #줄로 설정
     ~[#]<^U>~       화면 크기의 절반만큼 위로 스크롤. [#]인 경우, 스크롤을 # 줄로 설정
     ~<^B>~          화면 전체 크기만큼 위로 스크롤
     ~<^F>~          화면 전체 크기만큼 아래로 스크롤
     ~#~             전역 및 상대 줄 번호 표시
     ~2#~            전역 줄 번호 표시를 영구적으로 토글
     ~4#~            들여쓰기 후 상대 줄 번호 표시를 영구적으로 토글
     ~8#~            상대 줄 번호 표시를 영구적으로 토글
     ~V~             숨겨진 문자 표시 토글: <공백 탭 줄바꿈>
     ~<^C>~          <l h e b E B w W>에 대한 줄 이동 번호 표시 토글
     ~{<1-5>}<^C>~   줄 이동 번호 모드 1-5 선택
     ~<^V>~          줄 이동 번호 모드 순환
     ~[#]<^R>~       #회 다시 실행
     ~[#]u~          #회 취소
     ~<^I>~
     ~<Tab>~         커서 위치부터 줄 끝까지의 파일 경로 열기
     ~<^K>~          현재 버퍼를 파일에 기록합니다. 두 번째 시도 시 강제로 기록합니다.
     ~[#]<^W>{arg}~  arg 영역의 들여쓰기를 #번 줄입니다.
     ~[#]<{arg}~     arg 영역의 왼쪽 들여쓰기를 #번 늘립니다.
     ~[#]>{arg}~     arg 영역의 오른쪽 들여쓰기를 #번 늘립니다.
     ~[#]"{<arg>}{cmd}~ 레지스터 arg를 사용하여 일반 cmd를 실행합니다. #은 cmd에 적용됩니다.
     ~[#]"{<arg>}q~  기록을 시작하고 rr ex 옵션을 arg 레지스터로 설정합니다. #레지스터 내용을 유지합니다.
     ~q~             기록을 중지하고 rr ex 옵션을 0으로 설정합니다.
     ~R~             레지스터와 그 내용을 출력합니다.
     ~[#]&{<arg>}~   arg 레지스터 매크로를 비차단 모드로 #번 실행합니다.
     ~[#]@{<arg>}~   arg 레지스터 매크로를 차단 모드로 #번 실행
     ~[#]@@~         마지막 매크로를 #번 차단 모드로 실행
     ~[#]&&~         마지막 매크로를 #번 비차단 모드로 실행
     ~[#]@:~
     ~[#]&:~         <:> 레지스터를 ex 명령어로 #번 실행
     ~[#].~          마지막 일반 명령을 #번 반복합니다. 반복 가능한 명령:  =x X D C s S Y p P r d c ~ gu gU g~ ! > < <^W> i I a A o O ci di J K=
     ~[#]v.~         마지막 일반 명령을 #줄 아래로 이동하며 반복합니다
     ~[#]Q~          재귀적으로 ex 모드로 진입합니다. #는 현재 수평 스크롤 위치를 유지합니다
     ~:~             ex 프롬프트로 진입합니다                  
     ~[#]!{arg}~     # 또는 arg 영역을 기반으로 파이프 ex 프롬프트를 표시합니다.
     ~vv~            히스토리 버퍼의 b-1번째 줄을 사용하여 ex 프롬프트를 표시합니다.
     ~[#]vr~         %s/ ex 프롬프트를 표시합니다. 커서 위치부터 # 단어를 삽입합니다.
     ~[#]vt[#arg]~   .,.+0s/ ex 프롬프트를 표시합니다. 커서 위치부터 # 줄을 삽입합니다. 커서 위치부터 #arg 단어를 삽입
     ~[#]v/~         정규식 키워드를 설정하는 re ex 프롬프트를 표시합니다. 커서 위치부터 # 단어를 삽입
     ~v;~            ! ex 프롬프트를 표시
     ~[#]vi~         %s/ ex 프롬프트를 표시합니다. 공백을 탭으로 변경하는 정규식이 포함되어 있으며 #은 탭 너비를 조정합니다
     ~[#]vI~         %s/ ex 프롬프트를 표시합니다. 탭을 공백으로 바꾸는 정규 표현식이 포함되어 있습니다. #는 탭 너비를 조정합니다
     ~vo~            줄 끝의 공백과 <\r> 줄 끝 문자를 제거합니다
     ~<^G>~          버퍼 상태 정보 표시
     ~1<^G>~         영구 상태 행 활성화
     ~2<^G>~         영구 상태 행 비활성화
     ~ga~            문자 정보 표시
     ~1ga~           영구 문자 정보 행 활성화
     ~2ga~           영구 문자 정보 행 비활성화
     ~[#]gw~         줄을 # 열 제한까지 강제 줄바꿈합니다. 기본값: 80
     ~[#]gq~         버퍼를 # 열 제한으로 강제 단어 줄바꿈합니다. 기본값: 80
     ~[#]g~{arg}~    arg 영역의 대소문자를 #번 전환합니다
     ~[#]gu{arg}~    arg 영역을 소문자로 #번 전환합니다
     ~[#]gU{arg}~    arg 영역을 대문자로 #번 전환합니다
     ~[#]~           문자의 대소문자를 #번 앞으로 전환
     ~i~             삽입 모드로 진입
     ~I~             들여쓰기 후 줄 시작 부분에서 삽입 모드로 진입
     ~A~             줄 끝에서 삽입 모드로 진입
     ~a~             1자 앞으로 이동한 후 삽입 모드로 진입
     ~o~             아래에 새 줄을 만들고 삽입 모드로 진입
     ~O~             위에 새 줄을 만들고 삽입 모드로 진입
     ~[#]s~          #자를 삭제하고 삽입 모드로 진입
     ~[#]S~          # 줄 전체를 삭제하고 삽입 모드로 진입
     ~[#]c{arg}~     arg 영역을 #번 삭제하고 삽입 모드로 진입
     ~C~             커서 위치부터 줄 끝까지 삭제하고 삽입 모드로 진입
     ~[#]d{arg}~     arg 영역을 #번 삭제
     ~D~             커서 위치부터 줄 끝까지 삭제
     ~[#]x~          커서 위치부터 앞으로 #자 삭제
     ~[#]X~          커서 위치부터 뒤로 #자 삭제
     ~[#]di{<arg>}~  arg 쌍 안의 내용을 삭제하고, #개의 일치 항목을 건너뜁니다
     ~[#]ci{<arg>}~  arg 쌍 안의 내용을 삭제하고 삽입 모드로 들어갑니다. #개의 일치 항목을 건너뜁니다
     ~[#]r{arg}~     커서부터 앞으로 arg로 #개의 문자를 대체합니다
     ~[#]K~          한 줄을 #번 분할합니다
     ~[#]J~          #줄을 병합합니다
     ~[#]y{arg}~     arg 영역을 #번 복사합니다
     ~[#]Y~          #줄을 복사합니다     
     ~[#]p~          기본 레지스터를 현재 줄 아래 또는 커서 위치 뒤에 #번 붙여넣기
     ~[#]P~          기본 레지스터를 현재 줄 위 또는 커서 위치 앞에 #번 붙여넣기
     ~m{<mark>}~     버퍼 로컬 줄 표시 설정
     ~<^T>~          글로벌 줄 표시 0 설정. 전역 마크는 항상 유효합니다
     ~{<0 2 4 6 8>}<^T>~ 전역 라인 마크 # 설정
     ~{<1 3 5 7 9>}<^T>~ 전역 라인 마크 #로 전환
     ~[#]<^7>{<0-9>}~
     ~[#]<^_>{<0-9>}~
     ~[#]<^/>{<0-9>}~ 버퍼 목록을 표시하고, 프롬프트가 표시될 때 # 또는 0-9 인덱스에 따라 전환합니다
     ~<^^>~
     ~<^6>~          이전 버퍼로 전환
     ~[#]<^N>~       다음 버퍼로 전환, #을 누르면 앞으로/뒤로 방향이 반전됨
     ~\~             /fm/ 버퍼 b-2로 전환
     ~{#}\~          b-2의 보조 디렉터리 목록 새로 고침
     ~vb~            b-1 히스토리 버퍼로 재귀 진입. 종료 시 현재 줄을 ex 프롬프트에 삽입
     ~z1~            대체 키맵을 페르시아어 키맵으로 설정
     ~z2~            대체 키맵을 러시아어 키맵으로 설정
     ~ze~            영어 키맵으로 전환
     ~zf~            대체 키맵으로 전환
     ~zL~            td ex 옵션을 2로 설정
     ~zl~            td ex 옵션을 1로 설정
     ~zr~            td ex 옵션을 -1로 설정
     ~zR~            td ex 옵션을 -2로 설정
     ~[#]/~          정규식 검색 프롬프트, 1개 또는 #개의 일치 항목만큼 아래로 이동
     ~[#]?~          정규식 검색 프롬프트, 1개 또는 #개의 일치 항목만큼 위로 이동
     ~[#]n~          정규식 검색 반복, 1개 또는 #개의 일치 항목만큼 이동
     ~[#]N~          정규식 검색 반복, 1개 또는 #개의 일치 항목만큼 반대 방향으로 이동
     ~<^A>~          커서 위치에서 1단어 거리 정규식 검색, 중심 위치 무시, 위나 아래로 순환 이동
     ~*~             정규식 검색, 중심 위치 무시, 위나 아래로 순환 이동
     ~{#}*~
     ~{#}<^A>~       정규식 검색, 키워드를 커서 위치에서 #단어 거리로 설정
     ~<^]>~          b-2의 디렉터리 목록을 기반으로 파일 시스템 정규식 정방향 검색 <^P> 대체 처리를 위해 전역 줄 표시 0 설정
     ~{#}<^]>~       파일 시스템 정규식 검색(앞으로), 커서 위치부터 # 단어까지 키워드 설정
     ~[#]<^P>~       파일 시스템 정규식 검색(뒤로)
     ~<^Z>~          vi 일시 중지
     ~<^L>~          전체 화면을 강제 다시 그리기 및 터미널 크기 업데이트
     ~[#]Z{<Any>}~   강제 종료 및 터미널 정리, # 재귀 레벨에서 종료
     ~[#] Zz~        강제 종료 및 히스토리 명령어 실행, # 재귀 레벨 종료
     ~ZZ~            종료 및 저장되지 않은 변경 사항을 파일에 기록
     ~<ESC ^C>~      보류 중인 입력 또는 명령어 취소		   

* VI REGIONS
영역은 vi 이동 명령의 ~[h v]~ 범위를 정의하는 vi 일반 명령어입니다. “move” 라는 단어가 포함된 명령어는 영역을 정의합니다.

     #+begin_src 
     j + <^M> <Enter> - k h l f F t T , ; B E b e W w ( ) { } [ ] ^ 0 $
             <스페이스> <^H> <백스페이스> % ' ` G H L M / ? n N * <^A>

             모든 영역
     #+end_src

* VI MOTIONS
이동 명령은 ~[h v]~ 범위 내에서 실행되는 vi의 일반 명령입니다. “region” 이란 단어로 설명된 명령은 한 영역을 소비합니다. 이동 명령 앞이나 뒤에 ~[#]~ 을 붙일 수 있습니다.

     =<^W> > < ! c d y g~ gu gU=
             모든 이동 명령

     =dd yy cc g~~ guu gUU >> << <^W><^W> !!=
             ~[#]~ 를 줄 수로 사용할 수 있는 특수 이동 명령

     *예시:*
     - ~3d/int~ :: “int” 키워드가 세 번째로 나타나는 지점까지 텍스트 삭제
     - ~3dw~ ::    단어 3개 삭제 (접두사 [#])
     - ~d3w~ ::    단어 3개 삭제 (접미사 [#])
     - ~"ayl~ ::   <a> 레지스터에 문자 하나를 복사
     - ~"Ayw~ ::   <a> 레지스터에 단어 하나를 추가

* VI/EX INSERT
     <^H>
     <Backspace>   문자를 하나 삭제하고, 빈 상태일 경우 ex 모드를 초기화합니다.                   
     <^U>          <^X> 마크까지 또는 전체를 삭제합니다.
     <^W>          단어를 하나 삭제합니다.
     <^T>          들여쓰기를 늘립니다.
     <^D>          들여쓰기를 줄입니다.
     <^]>          0~9번 레지스터 중에서 붙여넣기 레지스터를 순차적으로 선택합니다.
     <^\>{<arg>}   붙여넣기 레지스터 arg를 선택합니다. <^\>는 기본 레지스터를 선택합니다.
     <^P>          레지스터 내용을 붙여넣습니다.
     <^X>          자동 완성 마크와 <^U> 시작 위치를 지정합니다. <^X>는 마크를 초기화합니다
     <^G>          자동 완성용 현재 버퍼 색인 생성
     <^Y>          색인된 모든 자동 완성 데이터 초기화
     <^R>          자동 완성 옵션을 뒤로 순회
     <^N>          자동 완성 옵션을 앞으로 순회
     <^B>          vi 삽입 모드일 때 자동 완성 옵션 표시
     <^B>          ex 프롬프트에서 b-1번째 히스토리 버퍼로 재귀 진입. 삽입 종료 시 현재 줄을 ex 프롬프트에 삽입
     <^A>          히스토리 버퍼 b-1의 줄을 순회
     <^Z>          vi/ex 일시 중지
     <^L>          vi 모드에서는 화면을 다시 그리며, ex 모드에서는 터미널을 정리
     <^O>          vi 모드와 ex 모드 간 재귀적으로 전환
     <^E>          영어 키맵으로 전환
     <^F>          대체 키맵으로 전환
     <^V>{<arg>}   리터럴 문자 arg 읽기
     <^K>{arg}     디그래프 시퀀스 arg 읽기
     <^C>
     <ESC>         vi 모드에서 삽입 모드 종료, ex 모드에서 재설정
     <^M>
     <Enter>       vi에서 <줄바꿈>을 삽입하고, ex 모드에서 명령을 실행합니다.

     
* EX
~Ex~ 는 유닉스 시스템용의 강력한 줄 편집기로 1976년에 빌 조이(Bill Joy)가 처음 개발했습니다. 이 필수적인 도구는 vi의 중추적인 역할을 수행하며 vi가 명령어와 매크로를 실행할 수 있게 해줄 뿐만 아니라 필요할 때 순수한 명령줄 인터페이스(CLI)로 전환할 수도 있게 해줍니다.
                        

* EX PARSING
구문 분석은 다음 구조를 따릅니다:

#+begin_src 
[<sep>][prefix][cmd][<pad>][args]
#+end_src

Ex 명령어는 <sep> 으로 시작하고 <sep> 으로 구분됩니다. 필드는 <Space> 또는 <Tab> 으로 채울 수 있습니다. [prefix] 는 [cmd] 가 소비하는 필드로 [range] 구조의 문자를 허용합니다. [prefix] 구조 내부의 패딩은 중첩된 블록 내부를 제외하고는 제거됩니다. [cmd] 와 [args] 사이에는 패딩이 하나만 있을 수 있습니다. 스크립트에서 모호함을 피하기 위해, [cmd] 와 [args] 사이에 항상 패딩을 사용할 것을 권장합니다.

     *예시:*
     - ~:evi.c~ :: “:e vi.c”로 평가됩니다.
     - ~:efbc ::~ “:e fbc”가 아닌 “:ef bc”로 평가됩니다.
     - ~:e  vi.c~ :: “vi.c”를 편집합니다. <pad> 가 필수입니다.

* EX ESCAPES
[args] 및 [prefix] 블록 내의 특수 문자는 <\> 로 이스케이프 처리되면 일반 문자로 변환됩니다. 이스케이프 처리는 POSIX와 다른 짝수/홀수 규칙에 따라 적용됩니다: 특수 문자 바로 앞의 이스케이프 수는 절반으로 줄어들며 홀수 개일 경우 해당 특수 문자는 일반 문자로 변환되고 그 외 위치의 이스케이프는 리터럴로 처리됩니다.

     - ~( ^ ] -~ :: 정규 표현식 “[]” 표현식 내의 특수 문자
     - ~( ) { + * ? ^ $ [ | \ . \< \>~ :: 정규 표현식 내의 특수 문자
     - ~\ : % !~ :: ex 내의 특수 문자

* EX EXPANSION
[args] 내의 <%> 는 현재 버퍼의 경로명이나, 해당 버퍼 번호가 뒤따를 경우 어떤 버퍼의 경로명으로 확장됩니다. %# 는 마지막으로 전환된 버퍼의 경로명으로 확장됩니다. %@ 는 지정된 레지스터로 확장됩니다.

     - 현재 파일의 복사본을 만들고 편집하기 :: ~:!cp % %_:e %_~
     - 현재 버퍼의 경로명 삽입하기 :: ~:&i%~
     - <a> 레지스터의 값 출력 :: ~:!echo %@97~

[args] 내의 <!> 는 외부 명령을 포함하는 블록을 시작하며 선택적으로 끝을 표시합니다. 이 블록은 실행되어 생성된 /stdout/ 및 /stderr/ 로 확장됩니다.

     - “int” 를 $RANDOM 의 값으로 치환 :: ~:%s/int/!printf “%s” $RANDOM!~
     - ls 셸 명령의 출력을 삽입 :: ~:&i!ls~
     - ls 출력을 좀 더 효율적으로 삽입 :: ~:;c!ls!<^V><ESC>~

* EX RANGES
일부 ex 명령어 앞에는 범위 지정자를 붙일 수 있습니다.

- [range] 접두사는 수직 및 수평 범위를 지정합니다.
- [vrange] 접두사는 수직 범위와 수평 위치를 지정합니다.
- [cmd] 가 없을 경우, [vrange] 가 [prefix] 를 대체합니다.

     #+begin_src 
     [% |][, ;][#][. $ ' > <][- + * / %][#num]
             모든 범위 구조
     {|}{cmd}[|]
             ex 하위 명령 구조
     {>}[정규식][>]
             앞으로 검색 구조
     {<}[정규식][<]
             뒤로 검색 구조
     '{#mark}
             마크 구조
     #+end_src

     ~%~       첫 번째 줄부터 마지막 줄까지의 범위
     ~|~       ex 하위 명령어 블록 시작
     ~,~       수직 범위 구분자
     ~;~       수평 범위 구분자
     ~#~       범위 구조에서 이전 값으로 재설정
     ~.~       현재 위치
     ~$~       버퍼의 마지막 줄 또는 줄 끝
     ~'~       마크 구조 시작
     ~>~       앞으로 검색 블록 시작
     ~<~       뒤로 검색 블록 시작
     ~-~       뒤따르는 숫자를 뺌
     ~+~       뒤따르는 숫자를 더함
     ~*~       뒤따르는 숫자로 곱함
     ~/~       뒤따르는 숫자로 나눕
     ~%~       뒤따르는 숫자로 나눈 나머지
     ~#num~    숫자 또는 위치

*예시:*
     - ~:1,5p~ :: 1, 5행을 출력합니다.
     - ~:.-5,.+5p~ :: 현재 위치 주변 5행을 출력합니다.
     - ~:>int>p~ :: “int”가 처음 나타나는 위치를 출력합니다.
     - ~:<int<p~ :: “int”가 처음 나타나는 위치를 역순으로 출력합니다.
     - ~:.,>int>p~ :: “int”가 발견될 때까지 출력
     - ~:<int<,.p~ :: “int”가 역순으로 발견될 때까지 출력
     - ~:>~ :: 이전에 설정된 정규식 키워드를 사용하여 검색
     - ~:'100,'97p~ :: 마크 <d>부터 마크 <a>까지의 줄을 출력
     - ~:%p~ :: 버퍼의 모든 줄을 출력
     - ~:$p~ :: 버퍼의 마지막 줄을 출력
     - ~:$*50/100+1~ :: 파일의 50% 지점으로 이동
     - ~:;50~ :: 50번째 문자 위치로 이동
     - ~:10;50~ :: 10번째 줄의 50번째 문자 위치로 이동
     - ~:10;.+5~ :: 10번째 줄의 5번째 문자 위치로 이동
     - ~:'97;'97~ :: 줄 마크 <a> 오프셋 마크 <a>로 이동
     - ~:;$~ :: 줄 끝으로 이동
     - ~:5;>int>~ :: 5번째 줄에서 “int” 검색
     - ~:.;<int<~ :: 현재 줄에서 “int”를 역방향으로 검색
     - ~:;5;+10=~ :: +10은 5가 아닌 초기 현재 오프셋을 기준으로 합니다
     - ~:;5;#+10=~ :: +10은 5를 기준으로 한 상대적 값입니다
     - ~:;>int>+3;#>>p~ :: 현재 줄에서 “int”로 둘러싸인 텍스트를 출력합니다
     - ~:|grp1|;>(a)+>+1|grp|;#>>p~ :: 비결정적 패턴 “a+”로 둘러싸인 텍스트를 출력합니다

* EX COMMANDS


* EX OPTIONS

* EXINIT ENV VAR
~EXINIT~ 는 시작 시 수행될 ex 명령어 체인을 정의하며 모든 파일이 열린 후 한 번 실행됩니다. 이는 C나 유닉스 파이프를 제외하고 Nextvi를 스크립팅하고 사용자 정의할 수 있는 유일한 방법입니다. grep, awk, sed 같은 많은 표준 텍스트 처리 유틸리티는 ~EXINIT~ 를 고려하여 Nextvi로 대체할 수 있습니다.

8진수 이스케이프를 사용하는 ~printf~ 는 ~EXINIT~ 에 제어 문자를 삽입하는 표준적인 방법입니다.

*예시:*

     - ~export EXINIT=‘td 2:order 0:lim 5000’~ :: 긴 줄 처리 성능을 최적화하기 위한 ex 옵션 설정
     - ~export EXINIT=‘b-1:r ./vi.c:b-1’~ :: vi.c를 히스토리 버퍼에 로드
     - ~export EXINIT="$(printf ‘e ./vi.c:& i\007\003:bx 1:bx’)"~ :: 자동 완성용 vi.c 색인 생성
     - ~export EXINIT="$(printf ‘97reg o{\n}\003kA\n\t’)"~ :: 레지스터 <a>에 @ 매크로 설정  @a 매크로는 커서 바로 아래에 <{}와 닫는 <}>를 생성하며 중괄호 사이에 커서를 삽입 모드로 남겨둡니다.
     - ~export EXINIT=‘98reg \:mpt-1\:;;$w \\\!xclip -selection clipboard\:mpt’~ :: 레지스터 <b>에 @ 매크로 설정 @b 매크로는 현재 줄을 X11 클립보드로 전송합니다.
     - ~export EXINIT=‘rr z:vis 2:&Q:b-3:pu 122:wq! bugreport.txt’~ :: 버그 보고를 위해 세션을 캡처합니다


* REGEX
~Pikevm~ 은 Nextvi를 위해 개발된 백트래킹 없는 고속 NFA 시뮬레이션 정규식 엔진입니다. 이 엔진은 정규식이 상수 공간과 O(~n * k~) 시간 복잡도 내에서 평가되도록 보장하며 여기서 <n> 은 입력 문자열의 길이고 <k> 는 정규식의 구조적 복잡도(예: 상태 전환 또는 선택)를 나타냅니다. 비록 이것이 엄격한 O(n) 선형 실행 시간 성능을 보장하지는 않지만 계산 및 메모리 자원이 입력 전체에 걸쳐 선형적이고 균등하게 분배되도록 보장하며, <k> 는 상수 계수에 직접적인 영향을 미칩니다. 이 원리는 기수 정렬 알고리즘에서 활용되는 개념과 유사합니다.

Pikevm 구문은 Plan 9의 regexp(7)과 유사합니다. 이 섹션에서 설명하는 매뉴얼 페이지 표기법은 무시합니다.

     ~.~       임의의 단일 문자를 일치시킵니다.
     ~[N-M]~   N에서 M까지의 대체 범위 집합을 일치시킵니다.
     ~{N,M}~   N에서 M회까지 일치시킵니다.
     ~()~      캡처 그룹
     ~(?:)~    비캡처 그룹
     ~*~       0회 이상 반복
     ~+~       1회 이상 반복
     ~|~       합집합, 대안 분기
     ~?~       0회 또는 1회 일치 (탐욕적)
     ~??~      0회 또는 1회 일치 (비탐욕적)
     ~^~       줄 시작 확인
     ~$~       줄 끝 확인
     ~\<~      단어 시작 확인
     ~\>~      단어 끝 확인
     ~(?=)~    양방향 선행 확인
     ~(?!)~    부정 선행 검사
     ~(?>)~    양수 후행 검사
     ~(?<)~    부정 후행 검사
     ~(?#)~    바이트 단위의 후행 검사 오프셋

룩어라운드 표현식을 사용하면 이 표현식이 없으면 구성할 수 없는 정규 표현식을 만들 수 있습니다. 룩어라운드는 정규 표현식 내 어디에서나 사용할 수 있지만, 몇 가지 고려 사항이 필요합니다.

     - 특징 1 :: 룩어라운드에는 완전한 정규 표현식이 포함됩니다.
     - 측면 2 :: 룩어라운드 내에는 중첩된 룩어라운드가 포함될 수 있습니다.
     - 측면 3 :: ~(?=^word)~ 같은 정적 룩어라운드는 정규식 엔진을 우회하여 최적화됩니다.
     - 측면 4 :: 룩어라운드는 엔진이 이미 잠재적인 일치 항목을 좁혀 놓은 복잡한 패턴의 끝부분 근처에서 조건을 확인하는 데 가장 적합합니다.
     - 측면 5 :: 오프셋이 없거나 오프셋이 0인 룩비하인드는 이전 문자로부터 시작됩니다. 오프셋이 지정된 경우, 현재 위치에서 지정된 값을 뺀 위치부터 스캔을 시작합니다. 음수 오프셋은 문자열의 시작 부분에서 시작됩니다.

* SPECIAL MARKS
     ~*~       이전 명령어 체인의 위치
     ~[~       이전 변경 사항의 첫 번째 위치
     ~]~       이전 변경 사항의 마지막 위치
     ~'~       이전 줄 영역의 위치
     ~`~       이전 줄 영역의 위치

* SPECIAL REGISTERS
     ~/~       이전 정규식 키워드
     ~:~       이전 ex 명령어
     ~<#0>~    기본 레지스터
     ~<0>~     기본 레지스터의 이전 값 (원자형) ‘원자형’이란 해당 연산에 <줄바꿈>이 포함되지 않았음을 의미합니다.
     ~<1-9>~   기본 레지스터의 이전 값(들) (비원자형)

* CODE MAP
     +--------------+----------------------+
     | 537 kmap.h   |  keymap translation  |
     | 582 vi.h     |  definitions/aux     |
     +--------------+----------------------+
     | 352 term.c   |  low level IO        |
     | 379 conf.c   |  hl/ft/td config     |
     | 462 ren.c    |  positioning/syntax  |
     | 615 uc.c     |  UTF-8 support       |
     | 674 lbuf.c   |  file/line buffer    |
     | 768 regex.c  |  pikevm              |
     | 812 led.c    |  insert mode/output  |
     | 1907 vi.c    |  normal mode/general |
     | 2000 ex.c    |  ex options/commands |
     | 7969 total   |  wc -l *.c|sort      |
     +--------------+----------------------+

* COMPILING
     - ~export CC=‘g++ -x c’~ :: 컴파일러 설정, g++ 예시
     - ~export CFLAGS=‘-s’~ :: CFLAGS 설정, 스트립 예시
     - ~./cbuild.sh~ :: 한 번 빌드
     - ~./cbuild.sh build~ :: 빌드
     - ~./cbuild.sh debug~ :: 심볼 포함, 정적 분석, 동적 분석 적용 및 최적화 없이 빌드
     - ~./cbuild.sh pgobuild~ :: PGO 빌드는 일부 애플리케이션 특정 작업에서 상당한 성능 향상을 가져올 수 있음
     - ~./cbuild.sh install~ :: vi를 ~$DESTDIR$PREFIX/bin~ 에 설치
     - ~./cbuild.sh fetch~ :: 업스트림 저장소의 커밋 병합
     - ~./cbuild.sh bench~ :: vi.c에서 2000단어 삭제 성능 벤치마크 테스트

* PHILOSOPHY
대부분의 텍스트 편집기는 상당한 기술적 부채를 안고 있습니다. 이런 편집기들은 빠르게 익히거나 깊이 이해하기 어렵고 쉽게 변경할 수도 없습니다. Nextvi는 ‘기본성’, ‘간결성’, ‘유연성’ 이란 세 가지 기둥을 중심으로 설계되었습니다.

- ‘기본성’ 이란 무제한적인 텍스트 변환을 위한 완전하면서도 최소한의 명령어 세트를 의미합니다.
- ‘간결성’ 이란 버스 팩터가 0인 간결하고 효율적이며 일관성 있는 구현을 의미합니다.
- ‘유연성’ 이란 깊은 조합성과 다재다능하며 확장 가능한 C 코드베이스를 의미합니다.

일반적인 통념에 따르면 이 세 가지 기둥은 모순된 개념으로 여겨질 것입니다. 이 세 가지를 모두 유지하는 것은 텍스트 편집기가 하나를 희생해야만 다른 하나를 얻을 수 있다는 통념에 도전하는 것입니다. Nextvi는 이 세 가지가 공존할 수 있을뿐만 아니라 훌륭한 텍스트 편집기가 갖추어야 할 필수 요소임을 증명합니다.

#+begin_quote
“모든 소프트웨어는 형편없지만, 어떤 것은 다른 것보다 더 형편없다.”

                       - 키릴 멜레킨
#+end_quote

* SEE ALSO
 새로운 기능은 ‘patches’ 브랜치에 제공되는 선택적 패치를 통해 이용할 수 있습니다. 의미 있는 기여 내용이 있고 이를 공개하고 싶다면, 이메일을 통해 또는 GitHub 풀 리퀘스트를 통해 패치를 제출할 수 있습니다. [[https://github.com/kyx0r/nextvi/tree/patches]]

     - Patch2vi 지원 유틸리티 :: [[https://github.com/kyx0r/nextvi/tree/patch2vi]]

     - 단위 테스트 :: [[https://github.com/kyx0r/nextvi/tree/test]]

     - 이 설명서를 생성하는 데 사용된 스크립트 :: [[https://github.com/kyx0r/nextvi/tree/manual]]]

     - 통합 태그 릴리스 :: [[https://github.com/kyx0r/nextvi/tree/release]]

     - 원본 Neatvi 저장소 :: [[https://github.com/aligrudi/neatvi]]

     - Posix vi(1) :: [[https://pubs.opengroup.org/onlinepubs/9699919799/utilities/vi.html]]

     - Posix ex(1) :: [[https://pubs.opengroup.org/onlinepubs/9699919799/utilities/ex.html]]

     - Russ Cox의 NFA 정규 표현식 :: [[https://swtch.com/~rsc/regexp/regexp1.html]]

     - Plan 9 regexp(7) :: [[https://man.cat-v.org/p9p/7/regexp]]


* AUTHORS
 Nextvi는 Kyryl Melekhin <k.melekhin@gmail.com>이 작성했습니다. 이 프로그램은 Ali Gholami Rudi <ali@rudi.ir>가 작성한 neatvi(1)을 기반으로 합니다. 이 매뉴얼 페이지는 nepeta <nepeta@canaglie.net>의 영감을 받아 작성되었습니다.

 
