* ■ Org Mode Compact Guide ■

* 1 Introduction
“Org 모드” 는 빠르고 효율적인 “순수 텍스트 시스템” 으로 메모를 작성하거나 할 일 목록을 관리하고 프로젝트 계획을 세울 수 있는 모드(mode)입니다. 또한, 문서 작성 및 출판 시스템이며 리터러시 프로그래밍과 재현 가능한 연구를 위한 소스 코드 작업도 지원합니다.

이 문서는 포괄적인 “Org 모드 매뉴얼” 을 대폭 압축해서 정리한 것입니다. 여기엔 모든 기본적인 기능과 명령어뿐만 아니라 사용자 정의에 대한 중요한 팁도 포함됩니다. 이 문서는 “분량이 방대하다!” 는 이유로 200페이지에 달하는 매뉴얼 읽기가 부담스러운 초보자를 위해 작성되었습니다.

** 1.1 Installation
*중요*: Emacs 배포판에 포함된 Org를 사용할 경우 이번 섹션을 건너뛰고 ‘활성화’ 섹션으로 이동합니다.

웹에서 Org를 ‘.zip’ 또는 ‘.tar’ (배포) 파일이나 Git 아카이브 형태로 다운로드한 경우 배포 디렉터리에서 직접 실행하는 것이 가장 좋습니다. 이 경우 Emacs 로드 경로에 ‘lisp/’ 하위 디렉터리를 추가해야 합니다. 이를 위해 Emacs 초기화 파일에 다음과 같은 줄을 추가합니다:

#+begin_src 
(add-to-list 'load-path "~/path/to/orgdir/lisp")
#+end_src

Git이나 tar 아카이브로 Org를 설치한 경우 ~로드 정보~ 를 생성하려면 다음 명령어를 실행합니다.

#+begin_src 
make autoloads
#+end_src


** 1.2 Activation
Emacs 초기화 파일에 다음과 같은 줄을 추가해서 Org 버퍼뿐만 아니라 모든 Emacs 버퍼에서 유용하게 사용할 수 있는 세 가지 명령에 대한 전역 단축키를 정의합니다. 적절한 단축키는 직접 선택하시기 바랍니다.

#+begin_src 
(global-set-key (kbd "C-c l") #'org-store-link)
(global-set-key (kbd "C-c a") #'org-agenda)
(global-set-key (kbd "C-c c") #'org-capture)
#+end_src

확장자가 ‘.org’ 인 파일은 자동으로 Org 모드로 전환됩니다.(또는 ~M-x org-mode~ 명령을 실행합니다)

** 1.3 Feedback
Org 모드에서 어떤 문제를 발견했거나 질문, 의견, 제안이 있으면 Org 메일링 리스트([[mailto:emacs-orgmode@gnu.org]])로 메일을 보내주시기 바랍니다. 버그 보고를 제출하는 방법에 대한 정보는 설명서를 참조합니다.



* 2 Document Structure
~Org mode~ 는 “아웃라이너” (outliner)입니다. 아웃라인을 사용하면 “문서를 계층 구조로 정리” 할 수 있는데 제게는 이것이 “메모와 생각을 표현하는 가장 좋은 방법” 입니다. 

문서의 구조나 개요를 쉽게 파악하기 위해 ‘접기(folding)’ 기능을 사용합니다. 즉, 문서 대부분을 숨겨서 전체적인 문서의 구조를 파악하고 현재 작업 중인 부분만 표시하는 방법입니다. Org는 전체 표시 및 숨기기 기능을 `TAB` 키에 할당한 단일 명령어인 ~org-cycle~ 로 통합함으로써 아웃라인의 사용법을 크게 간소화합니다.

** 2.1 Headlines
“제목(headline)은 개요 트리(outline tree)의 구조를 정의” 합니다. Org에서 제목은 줄 왼쪽에 여백[fn:1]없이 하나 이상의 별표와 뒤에 공백을 붙여서 시작합니다. 예를 들어:

[fn:1] 헤드라인에서 ~C-a~ 및 ~C-e~ 의 동작을 설정하려면 ~org-special-ctrl-a/e~ 변수를 참조합니다.

#+begin_src 
* First (top) level headline
** Second level
*** Third level
    some text
*** Third level
    more text
* Another first (top) level headline
#+end_src

~org-footnote-section~ 에서 이름을 따온 제목(기본값은 ‘Footnotes’)은 특수한 것으로 간주된다는 점에 유의합니다. 이런 제목을 가진 하위 트리는 내보내기(export) 함수에 의해 아무런 경고없이 무시됩니다.

일부 사용자들은 “별표가 많아서 산만하다!” 고 느끼며 제목 시작 부분의 공백 뒤에 별표 하나만 사용하는 형식의 개요(clear view)를 선호합니다. 이를 구현하는 설정 방법은 ‘기타’ 장을 참조합니다.


** 2.2 Visibility Cycling
이처럼 아웃라인을 사용하면 버퍼 내의 텍스트를 숨길 수 있습니다. Org는 “TAB” 및 “S-TAB” (org-cycle 및 org-shifttab)에 할당된 두 가지 명령어로 버퍼 내의 텍스트 표시 여부를 변경합니다.

~TAB~ (org-cycle)  
서브트리 순환: 현재 서브트리를 순환합니다.

#+begin_src 
,-> FOLDED -> CHILDREN -> SUBTREE --.
'-----------------------------------'
#+end_src

접두사 인자(~C-u TAB~)로 호출하거나 Shift 키를 누른 상태로 호출하면 전역 순환 기능이 실행됩니다.

~S-TAB~ (org-global-cycle), ~C-u TAB~ (org-cycle)  
전역 순환: 버퍼 전체를 순환합니다.

#+begin_src 
,-> OVERVIEW -> CONTENTS -> SHOW ALL --.
'--------------------------------------'
#+end_src

~C-u C-u C-u TAB~ (org-fold-show-all)  
서랍(drawer)을 포함해서 모두 표시합니다.

Emacs가 Org 파일을 처음 열 때 전역 상태는 ~showeverything~ 으로 설정되어 즉, “파일의 모든 내용을 표시” 합니다. 이는 ~org-startup-folded~ 변수로 설정하며 다음과 같이 ‘overview’, ‘content’, ‘showall’, ‘showeverything’ 또는 ‘show<n>levels’(n = 2..5)를 ‘STARTUP’ 키워드에 추가해서 파일별로 설정할 수 있습니다:

#+begin_src 
,#+STARTUP: content
#+end_src

** 2.3 Motion
다음 명령어는 버퍼 내의 다른 제목으로 이동합니다.

~C-c C-n~ (org-next-visible-heading)  
다음 제목으로 이동합니다.

~C-c C-p~ (org-previous-visible-heading)  
이전 제목으로 이동합니다.

~C-c C-f~ (org-backward-heading-same-level)  
같은 수준(형제)의 다음 제목으로 이동합니다.

~C-c C-b~ (outline-backward-same-level)  
같은 수준(형제)의 이전 제목으로 이동합니다.

~C-c C-u~ (outline-up-heading)  
좀 더 높은 수준(부모)의 제목으로 이동합니다.
