#+TITLE: SED — A Non-interactive Text Editor  
#+AUTHOR: PilJin Kwon
#+EMAIL:  piljin.kwon@gmail.com

#+DESCRIPTION: 이 문서는 SED 문서의 한국어 버전입니다.
#+KEYWORDS:  sed, regex, regular expression
#+LANGUAGE:  ko
#+OPTIONS:   H:4
#+TOC: headlines 2
#+TOC: tables


~Sed~ 는 /UNIX/ 운영 체제에서 실행하는 비대화형(/non-interactive/) 텍스트 편집기이다.

Sed는 다음과 같은 세 가지 상황에 사용하기 위해 설계됐다:

+ 파일이 너무 커서 대화형 편집이 불편한 파일을 편집할 경우

+ 편집 과정이 복잡해서 대화형 모드로 편하게 입력할 수 없는 경우 또는 모든 크기의 파일을 편집할 경우

+ 한 번의 입력으로 전역 편집을 효율적으로 수행할 경우

이 문서는 SED 사용자를 위한 매뉴얼이다.


*  Introduction
입력 데이터의 일부만 메모리에 상주하고 임시 파일을 사용하지 않으므로 편집할 수 있는 파일의 실질적인 크기는 입력과 출력 동시에 사용 가능한 보조 저장 장치 크기로 제한된다.

복잡한 스크립트는 (명령 또는 함수) 파일로 작성해서 sed에 함수를 파일 형태로 제공할 수 있다. 이로써 상당한 타이핑 시간과 그에 따른 오류까지 줄여준다. 함수 파일로 실행되는 sed는 스크립트로 구동되는 어떤 편집기보다 훨씬 효율적이다.

대화형 편집기와 비교할 때의 기능 손실은 상대 주소 지정 부재(줄 단위 작업 방식 때문)와 함수의 작동 여부를 즉시 확인할 수 없다는 점이다.

Sed는 UNIX 표준 편집기인 ~ed~ 의 직계 후손이다. 대화형과 비대화형의 작업 방식 차이로 ed와 sed는 상당한 변화가 있으며 ed에 익숙한 사용자도 이 문서의 2장과 3장을 읽지 않고 섣불리 sed를 사용할 경우엔 많이 놀랄 것이다. 

두 편집기의 유사성은 문자열을 인식하는 패턴(정규 표현식)에 있다. 패턴을 매칭하는 코드는 ed 코드를 그대로 복사했으며 2장에서 설명하는 정규 표현식도 UNIX 프로그래머 매뉴얼[^1]에서 그대로 복사되었다. (코드와 설명 모두 /Dennis M. Ritchie/ 가 작성함)



*  Overall Operation 
Sed는 기본적으로 표준 입력(/STDIN/)을 표준 출력(/STDOUT/)으로 복사하며 각 줄에 하나 이상의 함수를 수행한 후 출력에 기록한다. 이런 동작은 명령줄 옵션으로 수정할 수 있으며 이에 대한 내용은 1.1절에 설명한다.

함수의 일반적인 사용 형식은 다음과 같다:

#+begin_src 
[address1,address2][function][arguments]
#+end_src

주소는 하나 또는 둘 다 생략할 수 있으며 주소 형식은 2장에 설명한다. 

주소(/address/)와 함수(/function/) 사이엔 공백이나 탭 문자가 들어갈 수 있다. 함수는 반드시 존재해야 하며 사용 가능한 함수는 3장에 설명한다. 

인수(/arguments/)는 함수에 따라 필수 혹은 선택일 수 있으며 함수별로 3장에 설명한다.

줄 시작에 포함된 탭 문자와 공백은 무시된다.


** Command-line Flags
명령줄 옵션은 다음과 같은 세 가지를 인식한다:

- ~-n~ :: 모든 줄을 표준 출력으로 복사하지 않고 ~p~ (/print/)함수나 ~s~ (/substitute/)함수의 ~p~ (/print/)플래그로 지정한 줄만 복사하라고 지시한다.

- ~-e~ :: 지정한 인수를 함수로 처리하라고 지시한다.

- ~-f~ :: 지정한 인수를 파일로 처리하라고 지시한다. 파일은 함수가 줄마다 하나씩 포함되야 한다.


** Order of Application of Editing Commands
편집을 수행하기 전에(실제는 입력 파일이 열리기 전) 모든 함수는 실행 단계(함수가 입력 파일의 각 줄에 적용되는 단계)에서 적절한 효율을 낼 수 있는 형태로 컴파일된다. 또한 함수는 순서대로 컴파일되며 이는 실행 순서와 일치한다. 

함수는 한 번에 하나씩 적용되며 함수의 입력은 앞서 적용된 함수의 출력 결과이다.

함수의 적용 순서는 흐름 제어 함수인 ~t~ (/test/)와 ~b~ (/branch/) 함수로 변경할 수 있다. 이 함수로 적용 순서가 변경되도 함수의 입력은 이전에 적용된 함수의 출력 결과라는 사실은 변하지 않는다.


** Pattern-space
패턴 매칭이 이루어지는 곳을 패턴 공간(/pattern space/) 이라 부른다. 

일반적으로 패턴 공간은 입력 텍스트 한 줄이지만 ~N~ (/multi-line next/)함수로 여러 줄을 패턴 공간에 읽을 수 있다.


** Examples
예제는 문서 곳곳에 흩어져 있다. 별도로 명시하지 않는 한 모든 예제는 다음과 같은 텍스트를 가정한다: /example.txt/

#+begin_src 
In Xanadu did Kubla Khan
A stately pleasure dome decree:
Where Alph, the sacred river, ran
Through caverns measureless to man
Down to a sunless sea.
#+end_src

#+begin_quote
[!NOTE]
sed 함수의 출력은 어떤 경우라도 원문보다 개선된 것으로 간주하지 않는다.
#+end_quote

*예제:*  

#+begin_src 
sed 2q example.txt
#+end_src

위의 함수는 입력의 처음 두 줄을 표준 출력으로 복사한 후 종료한다. 출력은 다음과 같다:

#+begin_src 
In Xanadu did Kubla Khan
A stately pleasure dome decree:
#+end_src


* ADDRESSES: Selecting lines for editing
함수를 적용할 입력 파일의 줄은 주소(/address/)로 선택할 수 있다. 또한 주소는 줄 번호 또는 컨텍스트 주소일 수 있다.

함수 그룹을 하나의 주소(또는 주소 쌍)에 적용할 수 있으며 함수는 중괄호(~{...}~)로 묶어 그룹화해서 사용한다.


** Line-number Addresses
줄 번호 주소는 10진 정수이다. 입력에서 각 줄을 읽을 때마다 줄 번호 카운터는 증가하며 줄 번호는 해당 주소의 줄 번호와 일치(선택)한다. 

줄 번호 카운터는 여러 개의 입력 파일에서 누적되며 새로운 파일이 열릴 때마다 초기화 되지 않는다. 특별한 경우로 ~$~ 문자는 마지막 파일의 마지막 줄과 일치한다.


** Context Addresses
컨텍스트 주소는 슬래시(~/~) 문자로 둘러싸인 패턴(정규 표현식)이다. sed에서 인식하는 정규 표현식은 다음과 같다:

+ 일반 문자(아래에서 설명하는 특수 문자가 아닌)는 해당 문자와 매칭되는 정규 표현식이다.  

+ 정규 표현식 시작의 캐럿(~^~) 문자는 줄 시작의 널 문자와 매칭된다.  

+ 정규 표현식 끝의 달러 기호(~$~)는 줄 끝의 널 문자와 매칭된다.

+ 줄바꿈(~\n~)은 패턴 공간에 추가로 삽입한 줄바꿈 문자와 매칭되며 패턴 공간 끝에 있는 줄바꿈 문자와 매칭되지 않는다.

+ 마침표(~.~)는 패턴 공간의 줄바꿈 문자를 제외한 모든 단일 문자와 매칭된다.

+ 별표(~*~)는 해당 문자 앞의 0번 이상 반복될 경우 매칭된다.

+ 대괄호(~[ ]~)로 둘러싸인 문자 집합(/character class/)은 집합 내의 하나의 문자와 매칭된다. 단, 집합 첫 문자가 캐럿(~^~) 문자일 경우 집합 내의 문자와 패턴 공간의 마지막 줄바꿈을 제외한 모든 문자와 매칭되지 않는다.

+ 정규 표현식의 연결은 각 구성 요소가 매칭되는 문자열을 이어붙인 문자열과 매칭된다.

+ ~\(~ 와 ~\)~ 사이의 정규 표현식은 일반 표현식과 동일하지만 ~s~ 명령에서 다음 항목에서 설명하는 부수 효과를 가진다.

+ ~\d~ 표현식은 앞서 ~\(~ 와 ~\)~ 로 둘러싸인 표현식으로 매칭한 문자열과 동일한 문자열을 의미한다. 여기서 ~d~ 는 한 자리 숫자이며 왼쪽부터 세어 ~d~ 번째 ~\(~ 로 시작한 표현식이 매칭한 문자열을 역참조한다. 예를 들어, ~^\(.*\)\1~ 패턴은 동일한 문자열이 두 번 반복되고 줄 시작 부분에 나타난 경우 매칭된다.  

+ 단독으로 사용한 널 표현식(예: ~//~)은 마지막으로 컴파일한 정규 표현식과 동일하게 작동한다.

+ 특수 문자(=^, $, ., *, [, ], \, /=)를 리터럴로 사용하려면 해당 문자 앞에 백슬래시(~\~) 문자를 붙여야 한다.

+ 컨텍스트 주소가 입력과 매칭되려면 주소 내의 전체 패턴이 패턴 공간의 일부와 일치해야 한다.


** Number of Addresses
다음 섹션에 설명할 함수(/function/)는 0개, 1개 또는 2개의 주소를 가질 수 있다. 각 함수에서 허용할 최대 주소는 함수 설명에 함께 명시했으며 이를 초과한 주소를 사용하는 것은 오류(/error/)로 간주된다.

- 함수에 주소가 없으면 입력의 모든 줄에 적용된다.

- 함수에 주소가 하나만 있으면 해당 주소와 일치한 줄만 적용된다.

- 함수에 주소가 두 개 있으면 첫 번째 주소부터 두 번째 주소까지(포함)의 줄만 적용된다. 이후 줄에서 첫 번째 주소와 일치한 줄을 찾고 이 과정을 반복한다.

두 개의 주소는 쉼표 문자로 구분된다.

예제 파일에 다음과 같은 함수를 적용하면 결과는 다음과 같다.

#+begin_src 
/an/           → 1, 3, 4번 줄과 일치  
/an.*an/       → 1번 줄과 일치  
/^an/          → 어떤 줄도 일치하지 않음  
/./            → 모든 줄과 일치  
/\./           → 5번 줄과 일치  
/r*an/         → 1, 3, 4번 줄과 일치 (r의 반복 횟수가 0일 수 있음!)  
/\(an\).*\1/   → 1번 줄과 일치
#+end_src

#+begin_quote
[!NOTE]
~sed -n '/\(an\).*\1/' example.txt~ 로 실행한다.
#+end_quote


* FUNCTIONS
모든 함수는 한 개의 문자로 이름이 지정된다. 다음 요약은 괄호에 허용하는 최대 주소의 수를 먼저 제시하고 이어서 한 문자로 된 함수 이름과 꺾쇠 괄호(~<...>~)로 둘러싸인 사용 가능한 인수, 해당 함수의 확장된 해석 그리고 각 함수가 수행할 작업에 대한 설명이 제공된다. 따라서 꺾쇠 괄호 문자는 인수의 일부가 아니며 실제 함수에 입력하지 않아야 한다.


** Whole-line Oriented Functions
- ~(2)d~ -- 줄 삭제 :: ~d~ (/delete/)함수는 주소와 일치한 줄을 삭제한다. (결과를 출력하지 않음) 또한 삭제한 줄은 이후의 함수가 적용되지 않는 부수 효과가 있다. ~d~ 함수가 실행되면 입력에서 새로운 줄을 읽고 함수 목록은 새로운 읽은 줄에 처음부터 적용된다.

- ~(2)n~ -- 다음 줄 :: ~n~ (/next/)함수는 입력에서 다음 줄을 읽어 현재 줄을 대체한다. 현재 줄은 출력할 경우는 출력된다. 함수 목록은 ~n~ 함수 이후 계속된다.

- ~(1)a\ <text>~ -- 줄 추가 :: ~a~ (/append, add/)함수는 주소와 일치한 줄 다음에 ~<text>~ 인수를 출력한다. 본질적으로 ~a~ 함수는 여러 줄로 구성된다. ~a~ 함수에서 ~<text>~ 인수는 한 줄일 수도 있고 여러 줄일 수도 있다. 한 줄당 함수 하나라는 사용 형식을 유지하기 위해 내부의 줄바꿈은 줄바꿈 앞에 백슬래시 문자(~\~)를 붙여 숨겨야 한다. ~<text>~ 인수는 처음으로 숨겨지지 않은 줄바꿈(즉, 앞에 백슬래시가 없는 줄바꿈)에서 종료된다. ~a~ 함수가 성공적으로 실행되면 ~<text>~ 인수는 해당 줄 이후에 다른 함수가 어떤 영향을 주더라도 출력된다. 해당 줄이 완전히 삭제되도 ~<text>~ 인수는 여전히 출력된다. ~<text>~ 인수는 주소 일치 여부를 검사하지 않고 함수를 적용하지 않는다. 줄 번호 카운터에 영향을 주지 않는다.

- ~(1)i\ <text>~ -- 줄 삽입 :: ~i~ (/insert/)함수는 ~a~ 함수와 동일하지만 ~<text>~ 인수는 일치한 줄 앞에 출력된다. ~a~ 함수에 대한 모든 설명은 ~i~ 함수에 그대로 적용된다.

- ~(2)c\ <text>~ -- 줄 변경 :: ~c~ (/change/)함수는 주소로 선택한 줄을 삭제한 후 ~<text>~ 인자로 대체한다. ~a~ 및 ~i~ 함수와 마찬가지로 ~c~ 함수는 백슬래시로 숨겨진 줄바꿈 뒤에 와야 하며 ~<text>~ 인수 내부의 줄바꿈은 백슬래시로 숨겨야 한다. ~c~ 함수는 두 개의 주소를 가질 수 있으므로 줄 범위를 선택할 수 있다. 이 경우 주소 범위의 모든 줄은 삭제되지만 ~<text>~ 인수는 삭제한 각 줄마다 출력하는 것이 아니라 한 번만 출력된다. ~a~ 및 ~i~ 함수와 마찬가지로 ~<text>~ 인수는 주소 일치 여부를 검사하지 않고 함수를 적용하지 않는다. 줄 번호 카운터도 영향을 주지 않는다. 줄이 ~c~ 함수에 의해 삭제된 후에는 해당 줄에 함수를 적용하지 않는다. 줄 뒤에 ~a~ 또는 ~r~ (/read/)함수에 의해 텍스트가 추가되고 그 줄이 이후 변경될 경우 ~c~ 함수로 삽입한 텍스트는 ~a~ 또는 ~r~ 함수의 텍스트 앞에 위치한다. (~r~ 함수는 3.4절에서 설명됨)

#+begin_quote
[!NOTE]
이 함수에 의해 출력된 텍스트는 줄 앞의 공백과 탭은 항상 다른 sed 함수처럼 사라진다. 출력에서 줄 앞의 공백과 탭을 포함하려면 원하는 첫 번째 공백 또는 탭 앞에 백슬래시 문자를 붙여야 하며 이 경우 백슬래시 문자 자체는 출력되지 않는다.
#+end_quote

*예제:*  

#+begin_src 
n
a\
XXXX
d
#+end_src

위와 같은 함수 목록을 예제 파일에 적용하면 출력은 다음과 같다:

#+begin_src 
In Xanadu did Kubhla Khan
XXXX
Where Alph, the sacred river, ran
XXXX
Down to a sunless sea.
XXXX
#+end_src

이 경우 다음 두 함수 목록 중 어떤 것이든 동일한 결과를 생성한다:

#+begin_src 
n      n
i\     c\
XXXX   XXXX
d
#+end_src


** Substitute Function
컨텍스트 검색으로 선택한 부분만 변경할 수 있는 매우 중요한 함수가 있다.

- ~(2)s<pattern><replacement><flags>~ -- 치환 :: ~s~ (/substitute/)함수는 ~<pattern>~ 으로 선택된 줄을 ~<replacement>~ 로 바꾼다. 다음과 같이 읽는다: ~<pattern>~ 을 ~<replacement>~ 로 치환하라!

~<pattern>~ 인수는 주소에 사용한 패턴과 정확히 동일한 패턴을 포함한다. (위 2.2절 참조) ~<pattern>~ 과 컨텍스트 주소의 유일한 차이점은 컨텍스트 주소는 슬래시(~/~) 문자로 구분되지만 ~<pattern>~ 은 공백이나 줄바꿈이 아닌 임의의 문자로 구분한다는 점이다. 기본적으로 ~<pattern>~ 과 일치한 첫 번째 문자열만 치환되지만 자세한 내용은 아래의 ~g~ (/global/)플래그를 참조한다.

~<replacement>~ 인수는 ~<pattern>~ 다음 두 번째 구분 문자 다음에 시작하며 또 하나의 구분 문자로 끝나야 한다. (따라서 구분 문자는 정확히 세 번 등장한다.) ~<replacement>~ 는 패턴이 아니며 패턴에서 특수한 의미를 가지는 문자도 여기선 특별한 의미를 가지지 않는다!! 대신 다음과 같은 문자는 특별한 의미를 가진다:

- ~&~ 문자는 ~<pattern>~ 과 일치한 문자열로 대체된다  

- ~\d~ (여기서 ~d~ 는 한 자리 숫자)는 ~<pattern>~ 에서 ~\(~ 와 ~\)~ 로 둘러싸인 부분 문자열 중 ~d~ 번째 해당하는 문자열로 대체된다. ~<pattern>~ 에 중첩된 부분 문자열이 있을 경우 ~d~ 번째는 왼쪽부터 ~\(~ 의 개수를 세어 결정된다.  

- ~<pattern>~ 과 마찬가지로 위의 특수 문자를 리터럴로 사용하려면 앞에 백슬래시(~\~) 문자를 붙인다.

~<flags>~ 인수는 다음과 같은 플래그를 포함할 수 있다:

- ~g~ — 줄에서 ~<pattern>~ 과 일치한 모든(겹치지 않는) 인스턴스를 ~<replacement>~ 로 치환한다. 치환이 성공하면 다음 ~<pattern>~ 검색은 삽입된 문자 끝 바로 다음부터 시작된다. 따라서 ~<replacement>~ 에 삽입된 문자는 다시 검색되지 않는다.  

- ~p~ — 치환이 성공한 경우 줄을 출력한다. ~p~ 플래그는 ~s~ 함수가 치환을 수행할 경우만 줄을 출력한다. 여러 개의 ~s~ 함수에서 ~p~ 플래그를 사용하고 동일한 줄에 성공적으로 치환할 경우 해당 줄의 복사본은 성공한 치환마다 출력된다.  

- ~w <filename>~ — 치환이 성공한 경우 줄을 파일로 기록한다. ~w~ 플래그는 ~s~ 함수로 치환한 줄을 ~<filename>~ 파일에 기록한다. sed를 실행하기 전에 ~<filename>~ 이 존재하면 덮어쓰고 존재하지 않으면 새로 생성한다. ~w~ 와 ~<filename>~ 사이엔 공백 하나가 있어야 한다. 동일한 줄의 여러 개의 약간 다른 복사본이 기록될 가능성은 ~p~ 함수와 동일하다. ~w~ 플래그 및 ~w~ 함수(아래 참조)에 지정할 수 있는 파일 이름은 최대 10개이다.

*예제:*

다음 명령을 예제 파일에 적용하면

#+begin_src 
s/to/by/w changes
#+end_src

출력은 다음과 같다:

#+begin_src 
In Xanadu did Kubhla Khan
A stately pleasure dome decree:
Where Alph, the sacred river, ran
Through caverns measureless by man
Down by a sunless sea.
#+end_src

그리고 /changes/ 파일은 다음과 같이 기록된다:

#+begin_src 
Through caverns measureless by man
Down by a sunless sea.
#+end_src

~nocopy~ 옵션이 활성화된 경우 다음 함수는:

#+begin_src 
s/[.,;?:]/*P&*/gp
#+end_src

다음과 같은 결과를 생성한다:

#+begin_src 
A stately pleasure dome decree*P:*
Where Alph*P,* the sacred river*P,* ran
Down to a sunless sea*P.*
#+end_src

마지막으로 ~g~ 플래그 효과를 보여주는 예로 다음 함수는:

#+begin_src 
/X/s/an/AN/p
#+end_src

(~nocopy~ 모드일 경우):

#+begin_src 
In XANadu did Kubhla Khan
#+end_src

그리고 다음 함수는:

#+begin_src 
/X/s/an/AN/gp
#+end_src

다음과 같은 결과를 생성한다:

#+begin_src 
In XANadu did Kubhla KhAN
#+end_src



** Input-output Functions
- ~(2)p~ -- 출력 :: ~p~ (/print/)함수는 주소와 일치한 줄을 표준 출력에 기록한다. 줄은 ~p~ 함수가 실행될 시점에 기록되며 이후 함수로 해당 줄에 어떤 영향을 주더라도 관계없다.

- ~(2)w <filename>~ -- <filename> 에 기록 :: ~w~ (/write/)함수는 주소와 일치한 줄을 ~<filename>~ 파일에 기록한다. 해당 파일이 이미 존재하면 덮어쓰고 존재하지 않으면 새로 생성된다. 줄은 /write/ 함수가 각 줄에 실행될 시점에 기록되며 이후 함수로 해당 줄에 어떤 영향을 주더라도 관계없다. ~w~ 와 ~<filename>~ 사이엔 정확히 하나의 공백이 있어야 한다. /write/ 함수와 ~s~ 함수 뒤의 ~w~ 플래그에서 지정할 수 있는 파일은 최대 10개이다.

- ~(1)r <filename>~ -- 파일 내용 읽기 :: ~r~ (/read/)함수는 ~<filename>~ 의 내용을 읽어온 후 주소와 일치한 줄 뒤에 추가한다. 해당 줄에 이후 함수가 어떤 영향을 주더라도 파일은 읽혀지고 추가된다. ~r~ 함수와 ~a~ 함수가 동일한 줄에서 실행되면 ~a~ 함수와 ~r~ 함수의 텍스트는 실행 순서대로 출력된다. ~r~ 과 ~<filename>~ 사이엔 정확히 하나의 공백이 있어야 한다. ~r~ 함수로 언급한 파일을 열 수 없는 경우 해당 파일은 널(/NULL/) 파일로 간주되며 오류로 처리하지 않고 진단 메시지도 출력하지 않는다.

#+begin_quote
[!NOTE]
동시에 열 수 있는 파일 수에 제한이 있으므로 ~w~ 함수나 ~w~ 플래그에 언급한 파일 수가 10개를 넘지 않도록 주의해야 한다. ~r~ 함수로 읽을 경우 수 하나가 줄어든다. (한 번에 하나의 파일만 열 수 있음)
#+end_quote

*예제:*

/note1/ 파일에 다음과 같은 내용이 있다고 가정한다:

#+begin_src 
Note: Kubla Khan (more properly Kublai Khan; 1216-1294) was the grandson and most
eminent successor of Genghiz (Chingiz) Khan, and founder of the Mongol dynasty in
China.
#+end_src

다음 함수는:

#+begin_src 
/Kubla/r note1
#+end_src

다음과 같은 결과를 생성한다:

#+begin_src 
In Xanadu did Kubla Khan
Note: Kubla Khan (more properly Kublai Khan; 1216-1294) was the grandson and most
eminent successor of Genghiz (Chingiz) Khan, and founder of the Mongol dynasty in
China.
A stately pleasure dome decree:
Where Alph, the sacred river, ran
Through caverns measureless to man
Down to a sunless sea.
#+end_src


** Multiple Input-line Functions
다음 세 가지 함수는 모두 대문자로 표기되며 패턴 공간에 삽입된 줄바꿈 문자가 포함된 여러 줄일 경우 특별하게 처리한다. 이들은 주로 줄을 넘나드는 패턴 매칭을 제공하기 위해 설계되었다.

- ~(2)N~ -- 다음 줄 :: 다음 줄을 현재 패턴 공간 줄에 추가한다. 두 줄은 삽입한 줄바꿈 문자로 구분된다. 패턴 매칭은 삽입한 줄바꿈을 넘어 확장될 수 있다.

- ~(2)D~ -- 패턴 공간 첫 부분 삭제 :: 현재 패턴 공간의 첫 번째 줄바꿈 문자까지(포함해서) 삭제한다. 패턴 공간이 비게 되면(유일한 줄바꿈이 끝에 있는 경우) 입력에서 새로운 줄을 읽는다. 어떤 경우든 함수 목록을 처음부터 다시 시작한다.

- ~(2)P~ -- 패턴 공간 첫 부분 출력 :: 패턴 공간의 첫 번째 줄바꿈 문자까지(포함하여) 출력한다.

~P~ 와 ~D~ 함수는 패턴 공간에 삽입된 줄바꿈 문자가 없을 경우 각각 소문자 ~p~ 와 ~d~ 함수와 동일하게 작동한다.


** Hold and Get Functions
다음 네 가지 함수는 입력의 일부를 저장하거나 나중에 사용할 수 있도록 다시 불러오는 기능을 제공한다.

- ~(2)h~ -- 패턴 공간 저장 :: ~h~ (/hold/)함수는 패턴 공간의 내용을 보관 영역으로 복사한다. (기존 보관 영역 내용은 삭제됨)

- ~(2)H~ -- 패턴 공간 추가 저장 :: ~H~ 함수는 패턴 공간의 내용을 보관 영역에 추가한다. 기존 내용과 새로운 내용은 줄바꿈 문자로 구분된다.

- ~(2)g~ -- 보관 영역 가져오기 :: ~g~ (/get/)함수는 보관 영역의 내용을 패턴 공간으로 복사한다. (기존 패턴 공간의 내용은 삭제됨)

- ~(2)G~ -- 보관 영역 추가 가져오기 :: ~G~ 함수는 보관 영역의 내용을 패턴 공간에 추가한다. 기존 내용과 새로운 내용은 줄바꿈 문자로 구분된다.

- ~(2)x~ -- 교환 :: ~x~ (/exchange/)함수는 패턴 공간과 보관 영역의 내용을 서로 교환한다.

*예제:*

#+begin_src 
1h
1s/ did.*//
1x
G
s/\n/ :/
#+end_src

위의 함수를 표준 예제 파일에 적용하면 다음과 같은 결과가 생성된다:

#+begin_src 
In Xanadu did Kubla Khan :In Xanadu
A stately pleasure dome decree: :In Xanadu
Where Alph, the sacred river, ran :In Xanadu
Through caverns measureless to man :In Xanadu
Down to a sunless sea. :In Xanadu
#+end_src


** Flow-of-Control Functions
다음 함수는 줄에 직접적인 편집을 수행하지 않으며 주소에 선택된 줄에 함수 적용을 제어한다.

- ~(2)!~ -- 적용하지 않음 :: ~!~ (/Don’t/)함수는 주소에 선택되지 않은 모든 줄에 적용되도록 한다.

- ~(2){~ -- 그룹화 :: ~{~ (/group/)함수는 함수 집합을 그룹화해서 주소에 선택된 줄에 블록 단위로 적용(또는 적용하지 않음)한다. 그룹화된 함수 중 첫 번째 함수는 ~{~ 문자와 같은 줄에 있거나 다음 줄에 있을 수 있다. 함수 그룹은 단독 줄에 위치한 일치한 ~}~ 문자로 종료한다. 그룹은 중첩될 수 있다.

- ~(0):<label>~ -- 레이블 지정 :: 레이블은 함수 목록에서 ~b~ 및 ~t~ 함수가 참조할 위치를 표시한다. ~<label>~ 은 8자 이하의 임의의 문자 시퀀스이다. 서로 다른 함수가 동일한 레이블을 가지면 컴파일 시에 진단 메시지를 출력하며 실행하지 않는다.

- ~(2)b<label>~ -- 레이블로 분기 :: ~b~ (/branch/)함수는 현재 줄에 적용 중인 함수를 동일한 ~<label>~ 을 가진 콜론 문자가 발견된 위치 다음부터 시작한다. 컴파일된 모든 함수는 이후 동일한 레이블을 가진 콜론 문자가 발견되지 않으면 컴파일 시에 진단 메시지를 출력하며 실행하지 않는다. ~<label>~ 이 없는 ~b~ 함수는 함수 목록 끝으로 분기하는 것으로 간주한다. 현재 줄에 수행할 작업이 모두 완료되고 다음 줄을 읽으며 함수 목록은 새로운 줄에 처음부터 다시 시작된다.

- ~(2)t<label>~ -- 치환 테스트 :: ~t~ (/test/)함수는 입력에서 치환이 성공적으로 수행된지를 테스트한다. 치환이 성공했다면 ~<label>~ 로 분기하고 그렇지 않으면 아무런 작업도 처리하지 않는다. 치환이 성공했음을 나타내는 플래그는 다음과 같은 경우 초기화된다: 

+ 새로운 입력 줄을 읽을 때  
+ ~t~ 함수를 실행할 때


** Miscellaneous Functions
- ~(1)=~ -- 등호 :: ~=~ (/print line number/)함수는 주소와 일치한 줄의 줄 번호를 표준 출력에 쓴다.

- ~(1)q~ -- 종료 :: ~q~ (/quit/)함수는 현재 줄을 추가하거나 읽은 텍스트를 출력에 쓰고(있을 경우) 실행을 종료한다.

** 참고  
[^1]: Ken Thompson and Dennis M. Ritchie, The UNIX Programmer’s Manual. Bell Laboratories, 1978.






