* Perface
사람들이 쉘 스크립트를 사용하는 가장 일반적인 기능 중 하나는 *텍스트 파일을 다루는 것* 이다. 로그 파일을 검사하거나 설정 파일을 읽거나 데이터를 처리하는 등 쉘 스크립트는 텍스트 파일에 포함된 모든 유형의 데이터를 조작하는 지루한 작업을 "자동화" 하는 데 도움될 수 있다. 

하지만, 쉘 스크립트 명령만으로 파일 내용을 조작하려면 다소 부족할 수 있다. 쉘 스크립트로 어떤 형태로든 데이터를 조작하려면 Linux에서 사용할 수 있는 ~sed~ 도구에 하루빨리 익숙해지는 것이 좋다. 이 도구는 데이터 처리 작업을 크게 단순화할 수 있다.


** Getting to know the sed editor
sed 편집기는 대화형 편집기와 다르게 *스트림 편집기* (*S* tream *ED* itor)라고 불린다. vim 같은 대화형 텍스트 편집기는 키보드나 명령으로 텍스트를 삽입하거나 삭제 또는 교체하는 작업을 사용자와 대화형(interactive)으로 수행한다. 

스트림 편집기는 데이터를 처리할 때 사용자가 제공한 규칙(또는 집합)을 기반으로 입력 스트림을 편집한다. sed 편집기는 명령줄에서 직접 입력해서 실행하거나 명령 파일에 저장한 명령으로 데이터 스트림을 조작할 수 있다. 

일반적으로 sed 편집기는 다음과 같이 작업을 처리한다:

+ 입력(STDIN) 스트림에서 한 줄의 데이터를 읽는다. 
+ 읽은 데이터를 제공한 편집기 명령의 패턴과 일치 여부를 검사한다. 
+ 패턴과 일치하면 제공한 편집기 명령으로 스트림의 데이터를 변경한다. 
+ 변경한 데이터를 표준 출력(STDOUT)으로 출력한다.

스트림 편집기는 입력에서 읽은 한 줄의 데이터에 모든 명령을 적용한 후, 다음 줄의 데이터를 읽고 이런 과정을 반복한다. 입력 스트림의 모든 데이터 줄을 처리하면 종료한다. 이렇듯 명령은 줄 단위로 순차 적용되므로 sed 편집기는 데이터가 입력 스트림을 통과할 때마다 작업을 수행한다. 따라서, sed 편집기는 대화형 편집기 보다 데이터를 빠르게 편집할 수 있다. 

sed 프로그램을 사용하는 형식은 다음과 같다:

#+begin_src bash
sed options script file
#+end_src


/options/ 매개 변수는 sed 편집기의 기본 동작을 사용자 정의하며 다음과 같은 옵션을 사용한다.

| 옵션        | 설명                                                           |
|-------------+----------------------------------------------------------------|
| ~-e script~ | 입력 스트림에 처리할 명령을 지정한 명령으로 실행함             |
| ~-f file~   | 입력 스트림에 처리할 명령을 명령 파일에 저장한 명령으로 실행함 |
| ~-n~        | 명령의 출력 결과를 생성하지 않고 별도의 `print` 명령을 기다림  |

/script/ 매개 변수는 입력 스트림에 적용할 명령을 지정한다. 하나 이상의 명령이 필요할 경우 명령줄에 ~-e~ 옵션을 여러번 사용하거나, ~;~ (세미콜론)문자로 명령을 분리하거나, 명령이 저장된 파일을 ~-f~ 옵션으로 지정해서 실행할 수 있다. 데이터를 조작하는 다양한 명령 (/command/)이 제공된다.

다음 섹션은 sed 편집기에서 사용하는 기본 명령 몇 가지를 살펴보고 이후 고급 명령을 살펴본다.



** Defining an editor command in the command line
기본적으로 sed 편집기는 지정한 명령을 /STDIN/ 즉, 표준 입력 스트림에 적용한다. 따라서, 입력 데이터를 sed 편집기로 파이프(/pipe/)해서 필터(/filter/)로 사용할 수 있다. 

다음은 이런 기능을 보여주는 간단한 예제이다:

#+begin_src bash
$ echo "This is a test" | sed 's/test/big test/'
This is a big test
$
#+end_src

이 예제는 sed 편집기의 ~s~ (/substitute/) 대체 명령을 사용한다. ~s~ 명령은 슬래시 문자 사이에 지정한 첫 번째 텍스트 패턴(검색 문자열)을 두 번째 텍스트 패턴(대체 문자열)으로 대체한다. 예제의 경우 test 를 big test 로 대체한다.

예제는 실행과 동시에 화면에 결과를 출력한다. 이것이 바로 sed 편집기를 사용할 때의 강력함이다. 일부 대화형 편집기를 시작할 시간 동안 데이터를 여러 번 빠르게 편집할 수 있다. 예제는 한 줄의 데이터만 편집했다. 다음과 같이 여러 줄로 구성된 데이터 파일을 편집해도 빠르게 결과를 얻을 수 있다.

#+begin_src bash
$ cat data1.txt
The quick brown fox jumps over the lazy dog.
The quick brown fox jumps over the lazy dog.
The quick brown fox jumps over the lazy dog.
The quick brown fox jumps over the lazy dog.
$
$ sed 's/dog/cat/' data1.txt
The quick brown fox jumps over the lazy cat.
The quick brown fox jumps over the lazy cat.
The quick brown fox jumps over the lazy cat.
The quick brown fox jumps over the lazy cat.
$
#+end_src

sed는 거의 실행과 동시에 데이터를 즉시 반환한다!! 데이터 줄을 처리하면서 처리 결과도 함께 출력한다. 따라서, sed는 파일 전체를 처리하기도 전에 처리 결과를 볼 수 있다.

여기서 중요한 점은 *sed 편집기는 원본 파일의 데이터를 수정하지 않는다!!* 는 것이다. 

명령으로 수정한 텍스트는 표준 출력(/STDOUT/)으로만 전송된다!! 원본 파일을 확인해 보면 원본 데이터가 그대로인 것을 알 수 있다.

#+begin_src bash
$ cat data1.txt
The quick brown fox jumps over the lazy dog.
The quick brown fox jumps over the lazy dog.
The quick brown fox jumps over the lazy dog.
The quick brown fox jumps over the lazy dog.
$
#+end_src



** Using multiple editor commands in the command line
명령줄(/command line/)에서 하나 이상의 sed 명령을 실행하려면 ~-e~ 옵션을 여러 번 사용하거나, 다음과 같이 ~;~ 세미콜론 문자로 각 명령을 구분한다.

#+begin_src bash
$ sed -e 's/brown/green/; s/dog/cat/' data1.txt
The quick green fox jumps over the lazy cat.
The quick green fox jumps over the lazy cat.
The quick green fox jumps over the lazy cat.
The quick green fox jumps over the lazy cat.
$
#+end_src

세미콜론 문자로 구분된 명령은 파일의 *모든 줄에 적용* 된다. 이 경우 명령은 세미콜론 문자로 구분하며 이때 명령과 세미콜론 문자 사이에 공백이 없어야 한다. 또한, 명령을 구분할 때 세미콜론 문자 대신 bash 같은 쉘의 보조 프롬프트를 사용할 수 있다. 쉘에서 sed 스크립트(sed 편집기 명령)를 입력할 때 작은따옴표 문자를 입력하면 닫는 따옴표를 입력할 때까지 계속 입력할 수 있다.

#+begin_src bash
$ sed -e '
> s/brown/green/
> s/fox/elephant/
> s/dog/cat/' data1.txt
The quick green elephant jumps over the lazy cat.
The quick green elephant jumps over the lazy cat.
The quick green elephant jumps over the lazy cat.
The quick green elephant jumps over the lazy cat.
$
#+end_src

닫는 따옴표가 포함된 줄에서 명령을 끝내야 한다는 점에 주의한다. 쉘은 닫는 따옴표를 감지하면 명령을 실행한다. 명령이 실행되면 sed는 지정한 명령을 파일의 모든 줄에 적용한다.



** Reading editor commands from a file
처리할 sed 명령이 많을 경우, 별도의 명령 파일에 저장하는 것이 보다 효율적이다. ~sed -f~ 옵션으로 명령 파일을 지정해서 실행한다.

#+begin_src bash
$ cat script1.sed
s/brown/green/
s/fox/elephant/
s/dog/cat/
$
$ sed -f script1.sed data1.txt
The quick green elephant jumps over the lazy cat.
The quick green elephant jumps over the lazy cat.
The quick green elephant jumps over the lazy cat.
The quick green elephant jumps over the lazy cat.
$
#+end_src

이 경우 각 명령 끝에 세미콜론 문자를 넣지 않아도 된다. 왜냐하면, sed는 각 줄이 개별 명령을 포함한다는 것을 잘 알고 있다. 명령줄에서 입력할 때와 마찬가지로 sed는 지정한 명령 파일에서 명령을 읽고 대상 파일의 모든 줄에 적용한다.

#+begin_quote
"sed 스크립트와 쉘 스크립트를 혼동할 수 있다. 이런 혼동을 피하려면 sed 스크립트에 ~.sed~ 확장자를 사용하는 것이 좋다."
#+end_quote

이제부터 데이터를 편집할 때 유용한 sed의 기본 명령을 살펴보겠다.



* Commanding at the sed Editor Basics
sed를 성공적으로 사용하기 위한 핵심은 명령과 사용 형식을 잘 아는 것이다. 이것은 텍스트 편집 작업에도 도움된다. 

다음 섹션은 sed 편집기를 (기본적으로) 사용하거나 스크립트에서 사용할 수 있는 몇 가지 기본 명령과 기능에 대해 설명한다.



** Introducing more substitution options
~s~ (대체)명령으로 한 줄의 텍스트를 새로운 텍스트로 대체하는 방법을 살펴봤다. 하지만, 대체 명령은 작업을 보다 다양하게 처리할 수 있는 추가 옵션(플래그)이 존재한다.


*** Substituting flags
대체 명령으로 검색 일치한 패턴을 대체할 때는 한 가지 주의할 점이 있다. 다음 예제로 어떤 일이 일어나는지 살펴보자.

#+begin_src bash
$ cat data4.txt
This is a test of the test script.
This is the second test of the test script.
$
$ sed 's/test/trial/' data4.txt
This is a trial of the test script.
This is the second trial of the test script.
$
#+end_src

대체 명령은 여러 줄에 포함된 검색 문자열을 대체했지만 기본적으로 줄 내의 첫 번째 항목만 대체한다!! 한 줄에 포함된 여러 항목을 대체하려면 플래그 (/flags/)를 사용한다. 대체 명령의 플래그는 대체 문자열 뒤에 설정한다.

#+begin_src bash
s/pattern/replacement/flags
#+end_src

다음과 같이 네 가지 대체 명령 플래그를 사용할 수 있다:

| 플래그   | 설명                                              |
|----------+---------------------------------------------------|
| ~숫자~   | 대체 문자열로 대체할 검색 문자열의 검색 위치 지정 |
| ~p~      | 명령으로 대체한 경우 줄 내용 출력                 |
| ~g~      | 줄 내의 일치 항목 모두 대체                       |
| ~w file~ | 대체 결과를 파일에 저장                           |

- 숫자(/number/) 플래그는 검색 문자열의 검색 위치(순서)를 지정한다.

#+begin_src bash
$ sed 's/test/trial/2' data4.txt
This is a test of the trial script.
This is the second test of the trial script.
$
#+end_src

숫자 플래그 ~2~ 는 한 줄에 두 번째로 나타난 검색 패턴을 대체한다.(test → trial)

- ~g~ (/global/) 플래그는 한 줄에 나타난 모든 검색 패턴을 대체한다.

#+begin_src bash
$ sed 's/test/trial/g' data4.txt
This is a trial of the trial script.
This is the second trial of the trial script.
$
#+end_src

- ~p~ (/print/) 플래그는 대체 문자열로 대체한 줄만 출력한다. 대부분의 경우 ~-n~ (/no print - next/ 명령) sed 옵션과 함께 사용한다.

#+begin_quote
"문서 내의 일부 텍스트만 추출하는 것을 필터링이라 부른다."
#+end_quote

#+begin_src bash
$ cat data5.txt
This is a test line.
This is a different line.
$
$ sed -n 's/test/trial/p' data5.txt
This is a trial line.
$
#+end_src

~-n~ 옵션은 sed 편집기의 기본 출력 기능을 억제하고 ~p~ 플래그는 대체한 줄만 출력한다. 따라서, 이 둘을 함께 사용하면 대체 명령으로 대체한 줄만 (필터링해서) 출력할 수 있다.

- ~w~ (/write/) 플래그는 동일한 출력 결과를 생성하지만 플래그에 지정한 대상 파일에 출력 결과를 저장한다.

#+begin_src bash
$ sed 's/test/trial/w test.txt' data5.txt
This is a trial line.
This is a different line.
$
$ cat test.txt
This is a trial line.
$
#+end_src

기본적으로 sed 편집기의 출력은 표준 출력(/STDOUT/)으로 보내지만 ~w~ 플래그는 대체 문자열로 대체한 줄만 지정한 파일에 저장한다.


*** Replacing characters
때로는 검색 문자열에 사용하기 까다로운 문자를 만날 수 있다. 가장 흔한 예로 슬래시(~/~) 문자가 있다. 따라서, 파일 경로명 대체 작업은 번거로울 수 있다. 예를 들어, ~/etc/passwd~ 파일에서 bash 쉘을 C 쉘로 대체하려면 다음과 같이 처리한다:

#+begin_src bash
$ sed 's/\/bin\/bash/\/bin\/csh/' /etc/passwd
#+end_src

이 경우 슬래시(~/~) 문자는 대체 명령 *구분자* 로 사용하기 때문에 검색 문자열에 슬래시 문자가 포함될 경우 *백슬래시(~\~) 문자로 이스케이프 처리* 해야 한다. 하지만, 이 작업은 종종 혼란과 실수를 초래한다.

이런 문제를 해결하기 위해 sed는 대체 명령의 *구분자를 다른 문자로 선택할 수 있도록 허용* 한다.

#+begin_src bash
$ sed 's!/bin/bash!/bin/csh!' /etc/passwd
#+end_src

예제는 느낌표 문자를 *구분자로 사용* 해서 경로명을 보다 읽기 쉽고 이해하기 쉽게 만든다.


** Using addresses
기본적으로 sed 명령은 *모든 줄에 적용* 된다. 따라서, 특정 줄이나 줄 그룹에 명령을 *한정적으로 적용* 하려면 *주소 지정으로 적용 범위를 한정* 해야 한다.

sed에서 사용하는 *주소* (address)는 다음과 같이 두 가지 형식이 있다:

- 단일 줄 번호 또는 줄 범위 주소
- (특정 줄만 필터링하는) 텍스트 패턴 또는 패턴 범위

위의 두 가지 주소 형식은 다음과 같이 사용한다.

#+begin_src 
[address]command
#+end_src

또한, 주소(address)에 *둘 이상의 명령을 중괄호 문자로 그룹화* 해서 실행할 수 있다.

#+begin_src 
address {
    command1
    command2
    command3
}
#+end_src

sed는 명령(들)을 주소와 *일치한 줄에만 적용* 한다. 

다음 섹션에서 두 가지 주소 지정에 대한 사용법을 설명한다.


*** Addressing the numeric line
줄 주소 지정을 사용할 때는 *줄 위치(라인 번호)를 기준* 으로 처리한다. sed는 텍스트 스트림의 첫 번째 줄을 1번 줄로 지정하고 이후 각 줄에 순차적으로 번호를 매긴다.[fn:1]

[fn:1]반드시 단일 파일만 처리하는 것은 아니다. 여러 파일을 입력 데이터로 사용할 수 있다. 이경우 줄 번호는 누적된다.

또한, 줄 주소는 *단일 줄* 이거나 시작 줄과 끝 줄을 쉼표 문자로 구분한 *줄 범위 주소* 이다.

다음은 sed 명령을 단일 줄에 적용한다.

#+begin_src bash
$ sed '2s/dog/cat/' data1.txt
The quick brown fox jumps over the lazy dog
The quick brown fox jumps over the lazy cat
The quick brown fox jumps over the lazy dog
The quick brown fox jumps over the lazy dog
$
#+end_src

sed는 지정한 주소인 두 번째 줄의 텍스트만 수정한다. 

다음은 줄 범위에 적용한다.

#+begin_src bash
$ sed '2,3s/dog/cat/' data1.txt
The quick brown fox jumps over the lazy dog
The quick brown fox jumps over the lazy cat
The quick brown fox jumps over the lazy cat
The quick brown fox jumps over the lazy dog
$
#+end_src

특정 줄부터 *마지막 줄* 까지 명령을 적용할 때 주소 기호 문자(~$~)를 사용할 수 있다.

#+begin_src bash
$ sed '2,$s/dog/cat/' data1.txt
The quick brown fox jumps over the lazy dog
The quick brown fox jumps over the lazy cat
The quick brown fox jumps over the lazy cat
The quick brown fox jumps over the lazy cat
$
#+end_src

대부분의 경우 파일에 몇 줄이 포함된지 알 수 없으므로 달러 주소 기호는 유용하다!!


*** Using text pattern filters
명령을 적용할 대상인 줄을 지정하는 또 다른 방법은 조금 복잡하다.

sed는 명령을 적용할 줄만 *필터링할 때 검색 문자열을 사용* 한다. 사용 형식은 다음과 같다:

#+begin_src 
/pattern/command
#+end_src

*검색 문자열(pattern)은 슬래시(~/~) 문자로 감싸야 한다.* sed는 지정한 *검색 문자열을 포함한 줄에만 명령(command)을 적용* 한다. 

예를 들어, Samantha 사용자의 로그인 쉘을 변경하려면 다음과 같이 사용한다:

#+begin_src bash
$ grep Samantha /etc/passwd
Samantha:x:502:502::/home/Samantha:/bin/bash
$
$ sed '/Samantha/s/bash/csh/' /etc/passwd
root:x:0:0:root:/root:/bin/bash
bin:x:1:1:bin:/bin:/sbin/nologin
[...]
Christine:x:501:501:Christine B:/home/Christine:/bin/bash
Samantha:x:502:502::/home/Samantha:/bin/csh
Timothy:x:503:503::/home/Timothy:/bin/bash
$
#+end_src

위의 명령은 검색 문자열(~Samantha~)이 포함된 줄에만 명령(~s/bash/csh/~)을 적용한다. 

지금처럼 고정 검색 문자열로 사용하는 것은 특정 값을 직접 필터링할 때는 유용하지만 활용성은 어느 정도 제한이 있다. sed는 검색 문자열에 *정규 표현식* (regular expression)을 사용해서 훨씬 더 복잡한 검색 문자열을 처리할 수 있다. 정규 표현식을 사용하면 다양한 문자열을 일치시킬 수 있는 *고급 텍스트 패턴 매칭을 처리* 할 수 있다.

고급 텍스트 패턴 매칭은 와일드카드 문자, 특수 문자, 고정 텍스트를 조합해서 거의 모든 텍스트에 맞는 검색 패턴을 생성할 수 있다. 하지만, 정규 표현식은 쉘 스크립트 프로그래밍에서 가장 어려운 부분에 속하며 이후에 보다 자세히 다룬다.


*** Grouping commands
단일 줄(주소)에 둘 이상의 명령을 수행할 경우 *중괄호 문자로 명령을 그룹화* 한다. 

sed는 다음과 같이 지정한 줄에 나열한 명령을 모두 적용한다.

#+begin_src bash
$ sed '2{
> s/fox/elephant/
> s/dog/cat
> }' data1.txt
The quick brown fox jumps over the lazy dog.
The quick brown elephant jumps over the lazy cat.
The quick brown fox jumps over the lazy dog.
The quick brown fox jumps over the lazy dog.
$
#+end_src

두 가지 명령 모두 2번 라인에만 적용한다. 그룹 명령을 주소 범위로 지정할 수 있다.

#+begin_src bash
$ sed '3,${
> s/brown/green/
> s/lazy/active/
> }' data1.txt
The quick brown fox jumps over the lazy dog.
The quick brown fox jumps over the lazy dog.
The quick green fox jumps over the active dog.
The quick green fox jumps over the active dog.
$
#+end_src

sed는 주소 범위의 줄에 그룹 명령을 적용한다.


** Deleting lines
sed 편집기에서 대체 명령이 사용할 수 있는 유일한 명령은 아니다. 텍스트 스트림의 특정 줄만 삭제하려면 *delete* (d)명령을 사용할 수 있다. 삭제 명령 즉, ~d~ 는 예상대로 동작한다. 지정한 주소와 일치한 텍스트 줄을 삭제한다. 

하지만, 삭제 명령은 *매우 주의해서 사용* 해야 한다!! 별도로 주소를 지정하지 않으면 *스트림의 모든 줄을 삭제* 한다.

#+begin_src bash
$ cat data1.txt
The quick brown fox jumps over the lazy dog
The quick brown fox jumps over the lazy dog
The quick brown fox jumps over the lazy dog
The quick brown fox jumps over the lazy dog
$
$ sed 'd' data1.txt
$
#+end_src

따라서, 삭제 명령은 주소를 지정해서 사용할 때 가장 유용하다. 이를 통해 데이터 스트림의 *특정 줄만 삭제* 할 수 있다.

#+begin_src bash
$ cat data6.txt
This is line number 1.
This is line number 2.
This is line number 3.
This is line number 4.
$
$ sed '3d' data6.txt
This is line number 1.
This is line number 2.
This is line number 4.
$
#+end_src

또는 줄 범위를 삭제할 수 있다.

#+begin_src bash
$ sed '2,3d' data6.txt
This is line number 1.
This is line number 4.
$
#+end_src

파일 끝을 의미하는 기호 주소(~$~)를 사용할 수 있다.

#+begin_src bash
$ sed '3,$d' data6.txt
This is line number 1.
This is line number 2.
$
#+end_src

sed의 패턴 매칭(filtering)도 삭제 명령에 적용된다.

#+begin_src bash
$ sed '/number 1/d' data6.txt
This is line number 2.
This is line number 3.
This is line number 4.
$
#+end_src

sed는 검색 문자열과 일치한 텍스트를 포함한 줄만 제거한다.

#+begin_quote
"sed는 *절대!* 원본 파일을 수정하지 않는다!! 삭제한 줄은 단지 출력에서 사라진 것이며 원본 파일에는 여전히 삭제한 줄이 그대로 남아 있다."
#+end_quote

검색 문자열 두 개로 패턴 범위도 삭제할 수 있지만 *주의할 필요* 가 있다. 첫 번째 검색 문자열은 삭제 기능을 "*켜고*" 두 번째 검색 문자열은 삭제 기능을 "*끄는*" 역할을 처리한다!!

sed는 두 검색 패턴 사이의 모든 줄(지정한 줄까지 포함)을 삭제한다.

#+begin_src bash
$ sed '/1/,/3/d' data6.txt
This is line number 4.
$
#+end_src

이처럼 sed는 데이터 스트림에서 첫 번째 검색 패턴을 감지할 때마다 삭제 기능이 "*켜진다!!*" 는 것이다. 이는 전혀 예상치 못한 결과를 초래할 수도 있다.

#+begin_src bash
$ cat data7.txt
This is line number 1.
This is line number 2.
This is line number 3.
This is line number 4.
This is line number 1 again.
This is text you want to keep.
This is the last line in the file.
$
$ sed '/1/,/3/d' data7.txt
This is line number 4.
$
#+end_src

첫 번째 검색 패턴인 숫자 ~1~ 이 포함된 줄이 두 번 나타나면서 삭제 명령이 다시 실행되고 중지 패턴은 인식되지 않으므로 데이터 스트림의 나머지 줄까지 모두 삭제한다!!

또다른 문제는 *중지 패턴이 전혀 나타나지 않을 경우* 도 발생한다.

#+begin_src bash
$ sed '/1/,/5/d' data7.txt
$
#+end_src

삭제 명령은 첫 번째 패턴(~1~)과 일치해서 "켜졌지만" 두 번째 패턴(~5~)과 일치하지 않으므로 전체 데이터 스트림을 삭제한다!!


** Inserting and appending text
예상할 수 있듯이 다른 편집기와 마찬가지로 sed 편집기도 텍스트 스트림에 *줄을 삽입하거나 추가* 할 수 있다. 하지만, 이 두 명령은 약간 혼란스럽다:

- insert 명령(~i~)은 *주소 앞 줄* 에 새로운 줄을 *삽입* 한다. 
- append 명령(~a~)은 *주소 뒷 줄* 에 새로운 줄을 *추가* 한다.

이 두 명령이 혼란스러운 점은 바로 이런 사용 형식이다. 또한, 여러 줄의 텍스트를 삽입할 경우 각각 별도의 줄로 지정하고 마지막 줄을 제외한 모든 줄 끝에는 ~\~ 문자로 줄바꿈한다!!  

사용 형식은 다음과 같다:

#+begin_src bash
sed '[address]command\
new line'
#+end_src

새로 추가될 줄은 사용한 명령에 따라 다른 줄에 나타난다. insert 명령의 경우 새로운 줄은 *앞 줄에 나타난다* 는 점을 기억한다.

#+begin_src bash
$ echo "Test Line 2" | sed 'i\Test Line 1'
Test Line 1
Test Line 2
$
#+end_src

그리고 append 명령의 경우 새로운 줄은 *뒷 줄에 나타난다.*

#+begin_src bash
$ echo "Test Line 2" | sed 'a\Test Line 1'
Test Line 2
Test Line 1
$
#+end_src

시스템 쉘에서 작은 따옴표와 슬래시 문자를 입력한 후 엔터키를 누르면 새로운 줄을 입력하기 위한 *보조 프롬프트가 표시* 된다. 이 줄에 나머지 sed 명령을 입력해서 완료한다. 명령을 종료하는 작은따옴표(~'~) 문자를 입력하면 쉘은 해당 명령을 실행한다.

#+begin_src bash
$ echo "Test Line 2" | sed 'i\
> Test Line 1'
Test Line 1
Test Line 2
$
#+end_src

단일 줄 앞이나 뒤에 텍스트를 추가하는 것은 잘 작동했지만 여러 줄이나 중간 줄에 텍스트를 추가하려면 어떻게 해야할까? 줄 중간에 텍스트를 삽입하거나 추가하려면 추가할 위치를 *주소 지정* 으로 알려줘야 한다. 하지만, 이 두 명령은 *단일 주소만 지정할 수 있다!!*

따라서, 단일 줄 번호나 검색 문자열은 사용할 수 있지만 *범위 주소는 사용할 수 없다!!* 하지만, 이것은 아주 논리적인 제한이다. 줄 삽입이나 추가 작업은 특정 줄 앞이나 뒤에서 사용할 것이고 줄 범위로 적용할 필요는 없기 때문이다.

다음은 데이터 스트림 3번 줄 *앞에* 새로운 줄을 삽입하는 예이다:

#+begin_src bash
$ sed '3i\
> This is an inserted line.' data6.txt
This is line number 1.
This is line number 2.
This is an inserted line.
This is line number 3.
This is line number 4.
$
#+end_src

다음은 데이터 스트림 3번 줄 *뒤에* 새로운 줄을 추가하는 예이다:

#+begin_src bash
$ sed '3a\
> This is an appended line.' data6.txt
This is line number 1.
This is line number 2.
This is line number 3.
This is an appended line.
This is line number 4.
$
#+end_src

insert 명령과 동일하지만 새로운 줄은 지정한 줄 번호 뒤에 추가된다.

만약, 데이터 스트림이 여러 줄로 구성되어 있고 줄 끝에 추가하려면 달러 주소 기호(~$~)를 사용한다. 이 기호는 파일의 마지막 줄을 의미한다.

#+begin_src bash
$ sed '$a\
> This is a new line of text.' data6.txt
This is line number 1.
This is line number 2.
This is line number 3.
This is line number 4.
This is a new line of text.
$
#+end_src

동일한 원리로 파일의 첫 줄에 추가할 때는 단순히 *1번 줄 앞에 새로운 줄을 삽입* 하면 된다.

만약, 한 줄 이상의 여러 줄을 삽입하거나 추가하려면 여러 줄로 구성된 줄 끝에 역슬래시(~\~)] 문자를 *반드시* 추가해야 한다. 연속된 줄은 역슬래시 문자를 계속 붙여야 하며 *마지막 줄에는 붙이지 않는다.* 

sed는 여러 줄로 구성된 텍스트를 하나의 삽입 또는 추가 명령으로 처리할 수 있다.

#+begin_src bash
$ sed '1i\
> This is one line of new text.\
> This is another line of new text.' data6.txt
This is one line of new text.
This is another line of new text.
This is line number 1.
This is line number 2.
This is line number 3.
This is line number 4.
$
#+end_src

예제는 두 줄의 텍스트를 데이터 스트림 1 번 앞 줄에 추가한다.


** Changing lines
change 명령으로 데이터 스트림의 줄 내용을 변경할 수 있다. 이 명령은 insert 및 append 명령과 동일한 형식으로 사용한다.

#+begin_src bash
$ sed '3c\
> This is a changed line of text.' data6.txt
This is line number 1.
This is line number 2.
This is a changed line of text.
This is line number 4.
$
#+end_src

예제는 3번 줄의 텍스트를 변경했다. 주소 대신 검색 문자열(패턴)을 사용할 수 있다.

#+begin_src bash
$ sed '/number 3/c\
> This is a changed line of text.' data6.txt
This is line number 1.
This is line number 2.
This is a changed line of text.
This is line number 4.
$
#+end_src

검색 문자열을 사용한 change 명령은 데이터 스트림에서 일치한 *모든 텍스트 줄을 변경!!* 한다.

#+begin_src bash
$ cat data8.txt
This is line number 1.
This is line number 2.
This is line number 3.
This is line number 4.
This is line number 1 again.
This is yet another line.
This is the last line in the file.
$
$ sed '/number 1/c\
> This is a changed line of text.' data8.txt
This is a changed line of text.
This is line number 2.
This is line number 3.
This is line number 4.
This is a changed line of text.
This is yet another line.
This is the last line in the file.
$
#+end_src

change 명령은 주소 범위로 사용할 수 있지만 처리 결과는 예상과 다를 수 있다.

#+begin_src bash
$ sed '2,3c\
> This is a new line of text.' data6.txt
This is line number 1.
This is a new line of text.
This is line number 4.
$
#+end_src

두 줄을 각각 변경하는 대신 두 줄 모두 새로운 줄로 대체한다.


** Transforming characters
transform 명령(~y~)은 sed 명령 중에서 줄 단위가 아닌 *단일 문자에 적용되는 유일한 명령* 이다!!

transform 명령은 다음과 같은 형식으로 사용한다:

#+begin_src 
[address]y/inchars/outchars/
#+end_src

transform 명령은 inchars 와 outchars 의 *일대일 매핑 작업을 수행* 한다.

- inchars의 첫 번째 문자는 outchars의 첫 번째 문자로 변환된다. 
- inchars의 두 번째 문자는 outchars의 두 번째 문자로 변환된다. 

이런 매핑은 문자 길이만큼 계속된다. 만약, inchars와 outchars의 길이가 같지 않으면 sed는 *오류 메시지를 출력* 한다.

다음은 transform 명령을 사용한 간단한 예이다:

#+begin_src bash
$ sed 'y/123/789/' data8.txt
This is line number 7.
This is line number 8.
This is line number 9.
This is line number 4.
This is line number 7 again.
This is yet another line.
This is the last line in the file.
$
#+end_src

출력 결과로 알 수 있듯이 inchars에 지정한 각 문자는 동일한 위치의 outchars 문자로 대체된다. 또한, transform 명령은 *전역 명령* 이다. 즉, 줄에서 발견된 *모든 문자를 변환* 하며 등장 횟수에 관계없이 모두 적용된다.

#+begin_src bash
$ echo "This 1 is a test of 1 try." | sed 'y/123/456/'
This 4 is a test of 4 try.
$
#+end_src

sed는 줄에서 일치한 숫자 ~1~ 의 모든 인스턴스를 변환한다. 

#+begin_quote
"하지만, 변환 작업을 특정 문자로 제한할 수 없다!"
#+end_quote


** Printing revisited
이전 장에서 대체 명령으로 변경한 줄만 표시하기 위해 대체 명령에 ~p~ 플래그를 사용하는 방법을 보여줬다. 이 외에도 데이터 스트림에서 특정 정보를 출력할 수 있는 세 가지 출력 명령이 있다:

| 명령 | 설명             |
|------+------------------|
| ~p~  | 줄 내용 출력     |
| ~=~  | 줄 번호 출력     |
| ~l~  | 보다 자세히 출력 |

다음 섹션에서 sed의 세 가지 출력 명령에 대해 살펴본다.


*** Printing lines
대체 명령의 ~p~ 플래그처럼 ~p~ 명령도 줄을 출력한다. 하지만, 단독 사용할 경우 그다지 흥미로운 기능을 제공하지 않는다.

#+begin_src bash
$ echo "this is a test" | sed 'p'
this is a test
this is a test
$
#+end_src

이 명령이 처리하는 일은 이미 존재하는 텍스트를 *중복 출력* 하는 것 뿐이다. (기본 출력 + p 명령 출력)

print 명령의 일반적인 사용 용도는 *검색 문자열을 포함한 줄만 출력* 하는 것이다.

#+begin_src bash
$ cat data6.txt
This is line number 1.
This is line number 2.
This is line number 3.
This is line number 4.
$
$ sed -n '/number 3/p' data6.txt
This is line number 3.
$
#+end_src

이 경우 명령줄에 ~-n~ 옵션을 함께 사용해서 *다른 줄의 기본 출력을 억제하고 검색 문자열을 포함한 줄만 출력* 한다.

다음과 같은 명령으로 데이터 스트림에서 특정 줄만 빠르게 출력하는 필터링 용도로 사용할 수 있다.

#+begin_src bash
$ sed -n '2,3p' data6.txt
This is line number 2.
This is line number 3.
$
#+end_src

또한, 대체 명령으로 특정 줄을 변경할 때 처리 결과 확인용으로 print 명령을 사용할 수 있다. 다음과 같이 변경하기 이전의 줄을 출력하는 스크립트를 작성할 수 있다.

#+begin_src bash
$ sed -n '/3/{
> p
> s/line/test/p
> }' data6.txt
This is line number 3.
This is test number 3.
$
#+end_src

위의 명령은 우선 숫자 3을 포함한 줄을 검색하고 두 개의 그룹 명령을 실행한다. ~p~ 명령으로 변경 직전 원본 줄을 출력한다. 그 다음 ~s~ 대체 명령으로 텍스트를 대체하고 ~p~ 플래그로 변경한 텍스트를 출력한다. 따라서, 출력 결과는 원본 줄과 새로 변경한 줄 모두 출력된다.


*** Printing line numbers
등호(~=~) 명령은 *줄 번호를 출력* 한다. 줄 번호는 줄바꿈 문자(newline character) 기준으로 결정된다. 데이터 스트림에 줄바꿈 문자가 나타날 때마다 *줄의 끝으로 간주* 한다.

#+begin_src bash
$ cat data1.txt
The quick brown fox jumps over the lazy dog.
The quick brown fox jumps over the lazy dog.
The quick brown fox jumps over the lazy dog.
The quick brown fox jumps over the lazy dog.
$
$ sed '=' data1.txt
1
The quick brown fox jumps over the lazy dog.
2
The quick brown fox jumps over the lazy dog.
3
The quick brown fox jumps over the lazy dog.
4
The quick brown fox jumps over the lazy dog.
$
#+end_src

기본적으로 앞 라인에 줄 번호를 *별도로 출력* 한다. 등호(~=~) 명령은 검색 문자열을 검색할 때 유용하다.

#+begin_src bash
$ sed -n '/number 4/{
> =
> p
> }' data6.txt
4
This is line number 4.
$
#+end_src

~-n~ 옵션을 사용하면 검색 문자열을 포함한 줄 번호와 텍스트만 필터링해서 출력할 수 있다.


** Listing lines
list 명령(~l~)은 기본적으로 *출력되지 않는(non-printable) 문자를 출력* 한다.

이처럼 출력되지 않는 문자는 역슬래시 문자로 시작하는 8진수 값이나 탭 문자 같은 비-출력 문자는 C언어 스타일 표기법(~\t~ 등)으로 출력한다.

#+begin_src bash
$ cat data9.txt
This      line     contains    tabs.
$
$ sed -n 'l' data9.txt
This\tline\tcontains\ttabs.$
$
#+end_src

탭 문자는 ~\t~ 표기법으로 출력된다. 여기서 *달러 기호는 줄바꿈 문자를 의미* 한다.

데이터 스트림에 제어 문자가 포함될 경우 list 명령은 해당 문자를 16진수 코드로 출력한다.

#+begin_src bash
$ cat data10.txt
This line contains an escape character.
$
$ sed -n 'l' data10.txt
This line contains an escape character. \a$
$
#+end_src

data10.txt 파일은 벨소리를 발생시키는 16진수 제어 코드(~\a~)가 마지막에 포함되어 있다. ~cat~ 명령으로 텍스트 파일을 출력하면 이런 제어 코드는 화면에 보이지 않고(스피커가 켜져있다면) 소리만 들린다. 그러나, list 명령으로 제어 코드를 화면에 출력할 수 있다.


** Using files with sed
대체 명령엔 파일을 처리할 수 있는 ~w~ 플래그가 포함되어 있다. 하지만, 대체 명령으로 텍스트를 변경하지 않고 파일을 처리할 수 있는 명령이 있다.


*** Writing to a file
~w~ 명령은 파일에 출력 결과를 쓰기(write)위해 사용한다. ~w~ 명령의 사용 형식은 다음과 같다:

#+begin_src 
[address]w filename
#+end_src

filename 은 상대 경로 또는 절대 경로로 지정할 수 있지만 어떤 경우든 해당 파일에 대한 *쓰기 권한* 을 가지고 있어야 한다. 여기서 사용한 주소는 모든 주소 지정 방식---단일 줄이나 검색 문자열, 줄 범위나 검색 문자열 범위---를 사용할 수 있다.

다음 예제는 데이터 스트림의 처음 두 줄만 test.txt 파일에 저장하는 예이다:

#+begin_src bash
$ sed '1,2w test.txt' data6.txt
This is line number 1.
This is line number 2.
This is line number 3.
This is line number 4.
$
$ cat test.txt
This is line number 1.
This is line number 2.
$
#+end_src

파일 내용을 표준 출력(STDOUT)에 출력하지 않으려면 ~-n~ 옵션을 사용한다.

이 명령은 메일링 리스트 같은 공통 텍스트를 마스터 파일에서 특정 파일로 추출할 때 유용하다.

#+begin_src bash
$ cat data11.txt
Blum, R Browncoat
McGuiness, A Alliance
Bresnahan, C Browncoat
Harken, C Alliance
$
$ sed -n '/Browncoat/w Browncoats.txt' data11.txt
$
$ cat Browncoats.txt
Blum, R Browncoat
Bresnahan, C Browncoat
$
#+end_src

sed는 검색 문자열을 포함한 줄만 대상 파일에 기록한다.


*** Reading data from a file
쉘에서 데이터 스트림에 데이터를 삽입하거나 텍스트를 추가하는 명령을 살펴봤다. read 명령(~r~)은 외부 파일의 데이터를 읽어온 후 현재 파일에 삽입한다. 

다음은 read 명령의 사용 형식이다:

#+begin_src 
[address]r filename
#+end_src

filename 매개 변수는 데이터를 포함한 외부 파일의 절대 경로 또는 상대 경로를 지정한다.

주의할 점은 read 명령은 *주소 범위를 사용할 수 없다!!* 따라서, 단일 줄 번호나 검색 문자열만 지정할 수 있다. 다음은 3번 줄 다음에 외부 파일의 텍스트를 읽어와서 삽입한다.

#+begin_src bash
$ cat data12.txt
This is an added line.
This is the second added line.
$
$ sed '3r data12.txt' data6.txt
This is line number 1.
This is line number 2.
This is line number 3.
This is an added line.
This is the second added line.
This is line number 4.
$
#+end_src

외부 파일의 모든 줄을 읽은 후 데이터 스트림에 삽입한다. 

동일한 방법으로 검색 문자열 주소를 사용할 때도 그대로 작동한다.

#+begin_src bash
$ sed '/number 2/r data12.txt' data6.txt
This is line number 1.
This is line number 2.
This is an added line.
This is the second added line.
This is line number 3.
This is line number 4.
$
#+end_src

파일을 읽어와서 끝 줄에 추가하려면 달러 기호 주소 기호(~$~)를 사용한다.

#+begin_src bash
$ sed '$r data12.txt' data6.txt
This is line number 1.
This is line number 2.
This is line number 3.
This is line number 4.
This is an added line.
This is the second added line.
$
#+end_src

read 명령의 활용 방법 중 하나는 delete 명령으로 자리표시자(place-holder)를 외부 파일 데이터로 교체하는 것이다. 예를 들어, 다음과 같은 파일을 가정한다:

#+begin_src bash
$ cat notice.std
Would the following people:
LIST
please report to the ship's captain.
$
#+end_src

사람 이름이 들어갈 자리에 자리표시자 LIST 를 사용한다. 자리표시자 다음에 사람 이름 목록을 파일에서 읽어와서 삽입하려면 read 명령을 사용한다. 하지만, 출력 결과에 자리표시자 문자열이 그대로 남는다. 이를 제거하기 위해 delete 명령을 사용한다. 처리 결과는 다음과 같다:

#+begin_src bash
$ sed '/LIST/{
> r data11.txt
> d
> }' notice.std
Would the following people:
Blum, R Browncoat
McGuiness, A Alliance
Bresnahan, C Browncoat
Harken, C Alliance
please report to the ship's captain.
$
#+end_src

자리표시자는 외부 파일 이름 목록으로 교체되고 자리표시자 문자열은 제거된다.





* Regular Expressions
~sed~ 편집기를 성공적으로 사용하는 핵심은 *정규 표현식을 능숙하게 다루는 것* 이다. 하지만, 이는 결코 쉬운 일이 아니며 많은 양의 데이터에서 특정 데이터를 필터링하려면 복잡해질 경우도 많다.

이번 장은 ~sed~ 편집기로 *필요한 데이터만 정확히 필터링할 수 있는 정규 표현식* 에 대해 설명한다.


** What Are Regular Expressions?
정규 표현식을 이해하기 위한 첫 단계는 정규 표현식이 정확히 무엇인지 *정의하는 것* 이다.

이 장은 정규 표현식이 무엇인지 설명하고 정규 표현식의 사용 방법을 설명한다.


*** A definition
"정규 표현식" (Regular Expression)은 *텍스트를 필터링할 때 사용할 패턴이자 템플릿* 이다!! sed는 데이터가 프로그램으로 들어오면 정규 표현식 패턴과 비교한다. 입력 데이터가 패턴과 일치하면 처리 대상으로 받아들이고 일치하지 않으면 거부한다. 

정규 표현식의 패턴은 와일드카드 같은 특수 문자를 사용해서 데이터 스트림에서 하나 이상의 문자를 정확히 필터링할 수 있다.

시스템 쉘도 이름을 알 수 없는 파일 이름을 지정할 때 와일드카드 문자를 사용한다. 예를 들어, 파일과 디렉터리를 나열하는 ~ls~ 프로그램에서 와일드카드를 사용한 예제를 본 적이 있을 것이다. 즉, 별표(~*~) 와일드카드 문자를 사용해서 특정 조건에 맞는 파일 이름만 나열할 수 있다. 

#+begin_src bash
$ ls -al da*
-rw-r--r-- 1 rich rich 45 Nov 26 12:42 data
-rw-r--r-- 1 rich rich 25 Dec 4 12:40 data.tst
-rw-r--r-- 1 rich rich 180 Nov 26 12:42 data1
-rw-r--r-- 1 rich rich 45 Nov 26 12:44 data2
-rw-r--r-- 1 rich rich 73 Nov 27 12:31 data3
-rw-r--r-- 1 rich rich 79 Nov 28 14:01 data4
-rw-r--r-- 1 rich rich 187 Dec 4 09:45 datatest
$
#+end_src

~da*~ 패턴은 ~ls~ 프로그램에게 "파일 이름이 da 로 시작하는 파일만 나열하라!" 고 지시한다. 파일 이름은 da 뒤에 아무런 문자가 없거나 여러 문자가 올 수 있다. ~ls~ 프로그램은 디렉터리의 모든 파일을 읽지만 와일드카드와 일치한 파일만 *필터링해서 표시* 한다.

정규 표현식의 와일드카드 문자도 이와 유사하게 작동한다. 정규 표현식은 텍스트 또는 특수 문자를 조합해서 sed 프로그램이 데이터를 비교할 *템플릿을 정의* 한다. 정규 표현식은 다양한 *특수 문자를 사용해서 데이터를 필터링하기 위한 패턴을 정의* 할 수 있다.


*** Types of regular expressions
정규 표현식을 사용할 때 가장 큰 문제는 정규 표현식 엔진이 하나만 존재하는 것이 아니란 점이다. 

Linux는 서로 다른 유형의 정규 표현식 엔진을 사용한다. 프로그래밍 언어(Java, Perl, Python), Linux 유틸리티(sed, gawk, grep) 그리고 일반 애플리케이션(MySQL 및 PostgreSQL 데이터베이스 서버 등)이 포함된다.

정규 표현식은 정규 표현식 엔진으로 구현된다. 정규 표현식 엔진은 정규 표현식 패턴을 해석하고 정의된 패턴으로 텍스트를 비교하는 소프트웨어이다.

Linux에는 두 가지 정규 표현식 엔진이 존재한다:

- POSIX 기본 정규 표현식(*BRE* - Basic Regular Expression) 엔진 
- POSIX 확장 정규 표현식(*ERE* - Extended Regular Expression) 엔진

Linux 유틸리티 대부분은 *최소한 POSIX BRE 엔진 사양을 준수* 하며 해당 엔진에서 정의한 모든 패턴 기호를 인식한다.

불행하게도 일부 유틸리티(sed 편집기)는 BRE 엔진의 일부만 준수한다. 왜냐하면, 속도 제약 때문인데 sed는 데이터 스트림의 텍스트를 가능한 한 빠르게 처리할 목적으로 만들었기 때문이다.

POSIX ERE 엔진은 일반적으로 텍스트 필터링에 주로 정규 표현식을 사용하는 프로그래밍 언어에서 사용한다. 이 엔진은 고급 패턴뿐만 아니라 숫자, 단어, 영숫자 문자를 일치시키기 위한 특수 전용 기호를 제공한다. 대표적으로 ~gawk~ 프로그램은 ERE 엔진으로 정규 표현식 패턴을 처리한다.

정규 표현식을 구현한 엔진이 다양하기 때문에 모든 정규 표현식을 간결하게 설명하기란 어렵다. 다음 절에는 일반적으로 자주 사용하는 정규 표현식에 대해 설명하고 sed 편집기에서 사용하는 방법을 보여준다.


** Defining BRE Patterns
기본적인 BRE 정규 표현식 패턴은 데이터 스트림에서 특정 텍스트를 일치시키는 것이다.

이번 섹션은 정규 표현식 패턴으로 텍스트 패턴을 정의하는 방법과 그 결과로 기대할 수 있는 내용을 보여준다.


*** Plain text
이전 장에서 검색 문자열로 데이터를 필터링하는 방법을 설명했다. 다음은 그 기억을 되살리기 위한 예이다:

#+begin_src bash
$ echo "This is a test" | sed -n '/test/p'
This is a test
$ echo "This is a test" | sed -n '/trial/p'
$
#+end_src

첫 번째 명령은 test 패턴을 정의한다. sed는 print 명령으로 정규 표현식 패턴과 일치한 줄을 출력한다. ~echo~ 명령에 test 가 포함되어 정규 표현식 패턴과 일치하므로 sed는 해당 줄을 출력한다.

두 번째 명령은 trial 패턴을 정의한다. ~echo~ 명령에 해당 단어가 포함되지 않아서 정규 표현식 패턴은 일치하지 않으므로 sed는 출력하지 않는다.

눈치챘듯이 정규 표현식 엔진은 패턴이 데이터 스트림 어디서 나타나는지 전혀 신경쓰지 않는다!! 또한, 패턴이 몇 번 나타나는지도 별로 중요하지 않다. 정규 표현식이 어디서든 일치하면 해당 문자열은 정규 표현식을 사용한 Linux 유틸리티에 그대로 전달된다.

여기서 핵심은 정규 표현식 패턴을 입력 스트림의 텍스트와 일치시키는 것이다. *정규 표현식은 패턴 일치에 아주 까다롭다!!* 는 점도 항상 기억하는 것이 중요하다.

기억할 첫 번째 규칙은 정규 표현식 패턴은 *대소문자를 구분한다!!* 는 것이다. 즉, 정확한 대소문자를 가진 패턴만 일치한다.

#+begin_src bash
$ echo "This is a test" | sed -n '/this/p'
$
$ echo "This is a test" | sed -n '/This/p'
This is a test
$
#+end_src

첫 번째 명령은 실패하는데 검색 문자열에 포함된 this 가 소문자이기 때문이다. 반면 두 번째 명령은 패턴에 대문자를 정확히 사용했기 때문에 일치한다.

또한, 정규 표현식에 전체 단어를 정의할 필요는 없다. 정의한 텍스트가 데이터 스트림 *어디서든 나타나면 정규 표현식은 일치* 한다:

#+begin_src bash
$ echo "The books are expensive" | sed -n '/book/p'
The books are expensive
$
#+end_src

입력 스트림의 텍스트는 books 지만 정규 표현식에 book 이 포함되므로 일치한다.

이와 반대로 시도하면 정규 표현식은 실패한다:

#+begin_src bash
$ echo "The book is expensive" | sed -n '/books/p'
$
#+end_src

정규 표현식의 텍스트가 입력 스트림에 나타나지 않으므로 텍스트를 출력하지 않는다.

또한, 정규 표현식을 단일 단어로 제한할 필요도 없다. 검색 문자열은 공백과 숫자를 포함할 수 있다:

#+begin_src bash
$ echo "This is line number 1" | sed -n '/ber 1/p'
This is line number 1
$
#+end_src

공백 문자는 정규 표현식의 다른 문자와 마찬가지로 동등하게 처리된다:

#+begin_src bash
$ echo "This is line number1" | sed -n '/ber 1/p'
$
#+end_src

하지만, 정규 표현식 패턴에 공백을 정의하면 입력 스트림에 반드시 나타나야 한다. 또한, 여러 개의 연속된 공백과 일치하는 정규 표현식 패턴을 만들 수 있다:

#+begin_src bash
$ cat data1
This is a normal line of text.
This is a line with too many  spaces.
$ sed -n '/  /p' data1
This is a line with too many  spaces.
$
#+end_src

단어 사이에 공백 두 개가 포함된 줄은 정규 표현식 패턴과 일치한다. 이 패턴은 파일에 포함된 공백을 찾아내는 훌륭한 방법이다!


*** Special characters
정규 표현식을 사용할 때 주의할 사항이 하나 더 있다. 검색 문자열을 정의할 때 몇 가지 *예외 문자가 존재한다!!* 는 것이다. 

정규 표현식은 (검색 문자열) 패턴의 *일부 문자에 특별한 의미를 부여* 한다. 이런 문자를 검색 문자열 패턴에 사용하면 예상한 결과를 얻지못할 수 있다. 정규 표현식에서 인식 가능한 특수 문자의 전체 목록은 다음과 같다:

#+begin_src 
. * [ ] ^ $ { } \ + ? | ( )
#+end_src

이번 장에서 특수 문자가 정규 표현식에서 어떤 역할을 처리하는지 잘 알 것이다. 하지만, 지금은 단지 이런 *(특수) 문자들은 정규 표현식의 검색 문자열 패턴에 사용할 경우 문제가 있을 수 있다!* 는 점만 기억한다.

특수 문자를 일반 문자로 사용하려면 *이스케이프 처리* 해야 한다. 특수 문자를 이스케이프 처리할 때는 특수 문자 앞에 특별한 문자를 추가해서 정규 표현식 엔진이 다음 문자를 일반 텍스트 문자로 해석하도록 지시해야 한다. 이때 사용할 특별한 문자는 바로 *역슬래시 문자(~\~)* 이다.

예를 들어, 검색 문자열에 포함된 특수 문자인 달러 기호 자체를 검색하려면 달러 기호 앞에 역슬래시 문자를 붙인다:

#+begin_src bash
$ cat data2
The cost is $4.00
$ sed -n '/\$/p' data2
The cost is $4.00
$
#+end_src

역슬래시 문자도 특수 문자로 정규 표현식 패턴에 역슬래시 문자를 정의하려면 이스케이프 처리해야 한다. 따라서, 두 개의 역슬래시(~\\~)를 사용해야 한다:

#+begin_src bash
$ echo "\ is a special character" | sed -n '/\\/p'
\ is a special character
$
#+end_src

마지막으로 슬래시(~/~) 문자는 정규 표현식의 특수 문자는 아니지만 sed나 다른 프로그램에서 정규 표현식 패턴에 슬래시 문자를 사용하면 오류가 발생할 수 있다:

#+begin_src bash
$ echo "3 / 2" | sed -n '///p'
sed: -e expression #1, char 2: No previous regular expression
$
#+end_src

검색 명령에서 사용하는 슬래시 문자(구분자)와 구분할 수 없으므로 이스케이프 처리해야 한다:

#+begin_quote
"사실 검색 문자열이 ~\~ 문자로 시작하면 ~\~ *다음 문자를 구분자로 인식* 한다. 따라서 ~\,pattern,~ 형식으로 검색 명령의 슬래시 구분자 대신 쉼표 문자를 구분자로 사용할 수 있다. 기본적으로 대체 명령은 ~s~ 명령어 다음 문자를 구분자로 인식한다."
#+end_quote

#+begin_src bash
$ echo "3 / 2" | sed -n '/\//p'
3 / 2
$
#+end_src

이제 sed로 정규 표현식 패턴을 사용할 수 있고 모든 것이 제대로 작동한다.


** Anchor characters
"일반 텍스트" [[(#plain-text)]] 섹션에서 보여준 것처럼 기본적으로 정규 표현식 패턴을 지정하면 해당 패턴이 *입력 스트림 어디서든 나타난다면 일치* 한다. 패턴을 입력 스트림의 *시작이나 끝으로 고정* 할 때는 두 개의 특수 문자를 사용한다.


*** Starting at the beginning
캐럿(~^~) 문자는 입력 스트림의 *줄 시작 패턴을 정의* 한다. 줄 시작이 아닌 다른 위치에 있다면 정규 표현식은 실패한다.

이 경우 *캐럿 문자를 앵커로 사용하려면 정규 표현식 패턴 맨 앞에 배치* 해야 한다:

#+begin_src bash
$ echo "The book store" | sed -n '/^book/p'
$
$ echo "Books are great" | sed -n '/^Book/p'
Books are great
$
#+end_src

캐럿 앵커 문자는 줄바꿈으로 결정된 새로운 줄의 시작 부분에서 패턴을 확인한다:

#+begin_src bash
$ cat data3
This is a test line.
this is another test line.
A line that tests this feature.
Yet more testing of this
$ sed -n '/^this/p' data3
this is another test line.
$
#+end_src

검색 패턴이 새로운 줄의 시작에 나타나면 캐럿 앵커는 이를 정확히 포착한다.

캐럿 문자를 검색 패턴 시작이 아닌 다른 위치에 배치하면 특수 문자가 아닌 일반 문자로 인식한다:

#+begin_src bash
$ echo "This  ^ is a test" | sed -n '/s  ^/p'
This ^ is a test
$
#+end_src

캐럿 문자를 정규 표현식 패턴 마지막에 배치했으므로 일반 문자로 일치시켰다.

#+begin_quote
"캐럿 문자만 사용한 정규 표현식 패턴으로 정의할 경우 백슬래시 문자로 이스케이프 처리할 필요는 없다. 그러나, 캐럿 문자 먼저 지정하고 그 뒤에 텍스트가 패턴에 포함될 경우 캐럿 문자 앞에 이스케이프 문자를 사용해야 한다."
#+end_quote


*** Looking for the ending
줄 시작 패턴의 반대는 줄 끝 패턴이다. 달러(~$~) 문자는 끝 앵커를 정의한다. 이 특수 문자를 텍스트 패턴 뒤에 추가하면 줄은 텍스트 패턴으로 끝나야 함을 의미한다:

#+begin_src bash
$ echo "This is a good book" | sed -n '/book$/p'
This is a good book
$ echo "This book is good" | sed -n '/book$/p'
$
#+end_src

끝 텍스트 패턴과 관련된 문제는 *무엇을 찾는지 주의해야 한다* 는 점이다:

#+begin_src bash
$ echo "There are a lot of good books" | sed -n '/book$/p'
$
#+end_src

줄 끝에 포함된 단어 book 을 복수형으로 만들면 입력 스트림에 book 이 포함돼도 정규 표현식 패턴과 일치하지 않는다. 패턴과 일치하려면 반드시 줄 마지막에 있어야 한다.


*** Combining anchors
일부 상황에선 *시작 앵커와 끝 앵커를 결합* 할 수 있다. 첫 번째 상황은 *텍스트 패턴만 포함된 줄을 찾는다* 고 가정한다:

#+begin_src bash
$ cat data4
this is a test of using both anchors
I said this is a test
this is a test
I'm sure this is a test.
$ sed -n '/^this is a test$/p' data4
this is a test
$
#+end_src

sed는 지정한 텍스트 외의 다른 텍스트가 포함된 줄은 모두 무시한다.

두 번째 상황은 처음엔 다소 이상하지만 아주 유용하다. 패턴없이 두 앵커만 결합해서 입력 스트림에서 *빈 줄만 필터링* 할 수 있다. 

#+begin_src bash
$ cat data5
This is one test line.


This is another test line.
$ sed '/^$/d' data5
This is one test line.
This is another test line.
$
#+end_src

여기서 정의한 정규 표현식 패턴은 줄 시작과 줄 끝에 아무것도 없는 줄을 찾는다. 즉, 빈 줄은 줄바꿈 문자 외에 어떤 텍스트도 없으므로 정규 표현식 패턴과 일치한다. 또한, ~d~ 삭제 명령으로 정규 표현식 패턴과 일치한 줄을 삭제해서 빈 줄은 모두 제거된다. 

이는 파일에서 *빈 줄만 제거하는 효과적인 방법* 이다.


*** The dot character
점(~.~, 닷) 문자는 *줄바꿈 문자를 제외한 모든 단일 문자와 일치* 시킬 때 사용한다. 점 문자는 *반드시 어떤 문자와 일치* 하므로 점이 위치한 자리에 문자가 없으면 실패한다.

다음은 정규 표현식 패턴에 점 문자를 사용한 몇 가지 예이다:

#+begin_src bash
$ cat data6
This is a test of a line.
The cat is sleeping.
That is a very nice hat.
This test is at line four.
at ten o'clock we'll go home.
$
$ sed -n '/.at/p' data6
The cat is sleeping.
That is a very nice hat.
This test is at line four.
$
#+end_src

첫 줄은 실패하고 두 번째와 세 번째 줄이 성공한 이유는 쉽게 이해할 수 있을 것이다. 하지만, 네 번째 줄은 좀 까다롭다. at 과 일치하지만 그 앞의 점 문자와 일치한 문자가 전혀 없기 때문이다. 하지만, 사실 있다!! *정규 표현식은 공백 문자도 일반 문자로 간주* 하므로 at 앞의 공백 문자도 패턴과 일치한다!! 

다섯 번째 줄은 at 이 줄 맨 앞에 배치됨으로 이 사실을 증명하고 따라서, 패턴과 일치하지 않는다.


*** Character classes
점(~.~) 특수 문자는 어떤 단일 문자도 일치시키므로 유용하지만 *일치시킬 문자를 제한* 하려면 어떻게 할까? 이것을 정규 표현식에선 *문자 클래스* (character classes)라 부른다.

문자 클래서는 패턴과 일치하는 *문자의 집합을 정의* 할 수 있다. 문자 클래스에 포함된 문자 중 하나가 입력 스트림에 있다면 패턴과 일치한다.

문자 클래스를 정의하려면 대괄호 (~[..]~)문자를 사용한다. 대괄호 문자 사이에 문자 클래스에 포함시킬 문자(들)를 넣는다. 그 다음 문자 클래스를 다른 와일드카드 문자처럼 패턴으로 사용한다. 처음엔 익숙해질 시간이 필요하지만 일단 익숙해지면 꽤 놀라운 결과를 만들 수 있다.

다음은 문자 클래스를 사용한 예이다:

#+begin_src bash
$ sed -n '/[ch]at/p' data6
The cat is sleeping.
That is a very nice hat.
$
#+end_src

점(~.~) 특수 문자 예제에서 사용한 동일한 데이터 파일을 사용했지만 이번엔 좀 다른 결과를 얻었다. at 만 포함된 줄만 필터링할 수 있었다. 이 패턴과 일치한 단어는 cat 과 hat 뿐이다! 또한, at 으로 시작하는 줄도 일치하지 않았다!! 는 점에 주목한다. 해당 위치에 문자 클래스에 포함된 문자가 *반드시 있어야만 일치* 한다.

문자 클래스는 대소문자가 확실치 않을 때 유용하다:

#+begin_src bash
$ echo "Yes" | sed -n '/[Yy]es/p'
Yes
$ echo "yes" | sed -n '/[Yy]es/p'
yes
$
#+end_src

정규 표현식에 둘 이상의 문자 클래스를 사용할 수 있다:

#+begin_src bash
$ echo "Yes" | sed -n '/[Yy][Ee][Ss]/p'
Yes
$ echo "yEs" | sed -n '/[Yy][Ee][Ss]/p'
yEs
$ echo "yeS" | sed -n '/[Yy][Ee][Ss]/p'
yeS
$
#+end_src

정규 표현식은 세 개의 문자 클래스로 세 문자 모두 소문자와 대문자를 포함하도록 처리했다.

문자 클래스는 문자뿐만 아니라 숫자도 포함할 수 있다:

#+begin_src bash
$ cat data7
This line doesn't contain a number.
This line has 1 number on it.
This line a number 2 on it.
This line has a number 4 on it.
$ sed -n '/[0123]/p' data7
This line has 1 number on it.
This line a number 2 on it.
$
#+end_src

정규 표현식 패턴은 숫자 0, 1, 2, 또는 3 이 포함된 줄과 일치한다. 그 외의 숫자나 숫자가 없는 줄은 무시된다.

문자 클래스로 전화번호나 우편번호 같은 형식화된 숫자를 확인할 수 있다. 하지만, 특정 형식을 일치시킬 때는 *주의가 필요* 하다. 

다음은 잘못된 우편번호 일치 예이다:

#+begin_src bash
$ cat data8
60633
46201
223001
4353
22203
$ sed -n '
>/[0123456789][0123456789][0123456789][0123456789][0123456789]/p
>' data8
60633
46201
223001
22203
$
#+end_src

결과는 예상과 다르다. 짧은 우편번호 숫자를 잘 걸렀지만 이는 마지막 문자 클래스와 일치한 문자가 없었기 때문이다. 그러나, 여섯 자리 숫자까지 통과했는데 문자 클래스는 다섯 개만 정의했음에도 말이다.

*정규 표현식 패턴은 입력 스트림 어디서든 발견될 수 있다!* 는 점을 항상 기억한다. 일치한 패턴 외에도 항상 추가 문자가 있을 수 있다. 이 경우 숫자 다섯 개만 *정확히 일치* 시키려면 공백을 추가하거나 다음 예제처럼 줄 시작과 끝을 명시적으로 표시해서 명확히 처리한다:

#+begin_src bash
$ sed -n '
> /^[0123456789][0123456789][0123456789][0123456789][0123456789]$/p
> ' data8
60633
46201
22203
$
#+end_src

훨씬 더 좋아졌다! 이 장 후반부에 이를 좀 더 간단히 만드는 방법을 살펴보겠다.

문자 클래스의 사용 용도는 사용자가 입력한 데이터의 철자를 파싱하는 것이다. 일반적인 철자 오류를 파싱하는 정규 표현식은 다음과 같이 쉽게 만들 수 있다:

#+begin_src bash
$ cat data9
I need to have some maintenence done on my car.
I'll pay that in a seperate invoice.
After I pay for the maintenance my car will be as good as new.
$
$ sed -n '
/maint[ea]n[ae]nce/p
/sep[ea]r[ea]te/p
' data9
I need to have some maintenence done on my car.
I'll pay that in a seperate invoice.
After I pay for the maintenance my car will be as good as new.
$
#+end_src

예제는 문자 클래스를 활용해서 텍스트에 철자가 틀린 단어인 maintenance 와 separate 를 포착한다. 이 정규 표현식 패턴은 올바른 철자인 maintenance 도 일치한다.


*** Negating character classes
정규 표현식 패턴은 *문자 클래스의 효과를 반대로 적용* 할 수 있다!!

문자 클래스에 포함된 문자를 찾는 대신 문자 클래스에 *포함되지 않은 문자* 를 찾을 수 있다. *문자 클래스 정의 시작 부분에 캐럿 문자를 배치* 한다:

#+begin_src bash
$ sed -n '/[^ch]at/p' data6
This test is at line four.
$
#+end_src

이것은 *문자 클래스를 부정* 함으로 정규 표현식 패턴은 c 나 h 가 *아닌 모든 문자* 와 일치한다. 공백 문자도 이 범주에 속하므로 패턴과 일치했다. 

그러나, 부정(반전 문자 클래스) 기능을 사용해도 문자 클래스는 여전히 어떤 문자와 반드시 일치해야 하므로 줄 시작에 at 이 있는 줄은 패턴과 일치하지 않는다.


*** Using ranges
앞서 우편번호 예제에서 문자 클래스에 모든 숫자를 나열한 것이 다소 번거롭다는 점을 느꼈을 것이다. 다행히 간단한 처리 방법이 있다. 문자 클래스에 대시 (~-~) 기호를 사용해서 *문자의 범위를 지정* 할 수 있다. 문자 범위의 첫 번째 문자, 대시 문자, 그리고 마지막 문자를 지정한다. 

정규 표현식은 시스템에서 사용하는 문자 집합에 따라 *지정한 문자 범위의 모든 문자를 포함* 한다. 이제 숫자 범위를 지정해서 우편번호 예제를 좀 더 간단히 만들 수 있다:

#+begin_src bash
$ sed -n '/^[0-9][0-9][0-9][0-9][0-9]$/p' data8
60633
46201
45902
$
#+end_src

이로써 많은 타이핑을 줄일 수 있다!! 문자 클래스는 0 부터 9 까지의 숫자 범위와 일치한다. 입력 데이터에 문자가 포함되면 패턴은 일치하지 않는다.

#+begin_src bash
$ echo "a8392" | sed -n '/^[0-9][0-9][0-9][0-9][0-9]$/p'
$
$ echo "1839a" | sed -n '/^[0-9][0-9][0-9][0-9][0-9]$/p'
$
$ echo "18a92" | sed -n '/^[0-9][0-9][0-9][0-9][0-9]$/p'
$
#+end_src

같은 원리로 문자도 그대로 적용된다:

#+begin_src bash
$ sed -n '/[c-h]at/p' data6
The cat is sleeping.
That is a very nice hat.
$
#+end_src

새로운 ~\[c-h\]at~ 패턴은 첫 글자가 c 부터 h 사이의 문자로 시작하는 단어와 일치한다. 이 경우 at 만 있는 줄은 패턴과 일치하지 않는다.

또한, 문자 클래스에 여러 개의 비-연속적인 범위를 지정할 수 있다:

#+begin_src bash
$ sed -n '/[a-ch-m]at/p' data6
The cat is sleeping.
That is a very nice hat.
$
#+end_src

이 문자 클래스는 at 앞에 a 부터 c 까지 그리고 h 부터 m 까지 범위의 문자가 나타나는 것을 허용한다. 이 범위는 d 부터 g 까지 문자는 제외한다.

#+begin_src bash
$ echo "I'm getting too fat." | sed -n '/[a-ch-m]at/p'
$
#+end_src

이 패턴은 fat 문자열은 거부했다. 왜냐하면, f 문자는 지정한 범위에 포함되지 않기 때문이다.


*** Special character classes
사용자가 직접 문자 클래스를 정의하는 것 외에 BRE는 특정 유형을 일치시킬 때 사용할 수 있는 *내장된 특수 문자 클래스가 포함* 되어 있다. 표 20-1은 사용할 수 있는 BRE 특수 문자 클래스이다.

*TABLE 20-1 BRE Special Character Classes*

| 문자 클래스   | 설명                                                                                   |
|---------------+----------------------------------------------------------------------------------------|
| ~[[:alpha:]]~ | 대소문자 알파벳 문자와 일치                                                            |
| ~[[:alnum:]]~ | 숫자 0--9, 대소문자 A--Z 와 일치                                                       |
| ~[[:blank:]]~ | 스페이스 또는 탭 문자와 일치                                                           |
| ~[[:digit:]]~ | 숫자 0 부터 9 까지 일치                                                                |
| ~[[:lower:]]~ | 소문자 알파벳 a--z 와 일치                                                             |
| ~[[:print:]]~ | 출력 가능한 모든 문자와 일치                                                           |
| ~[[:punct:]]~ | 구두점 문자와 일치                                                                     |
| ~[[:space:]]~ | 공백 문자와 일치: 스페이스, 탭, 줄 바꿈(NL), 폼 피드(FF), 수직 탭(VT), 캐리지 리턴(CR) |
| ~[[:upper:]]~ | 대문자 알파벳 A--Z 와 일치                                                             |

내장 문자 클래스는 정규 표현식 패턴에서 일반 문자 클래스처럼 사용한다.

#+begin_src bash
$ echo "abc" | sed -n '/[[:digit:]]/p'
$
$ echo "abc" | sed -n '/[[:alpha:]]/p'
abc
$ echo "abc123" | sed -n '/[[:digit:]]/p'
abc123
$ echo "This is, a test" | sed -n '/[[:punct:]]/p'
This is, a test
$ echo "This is a test" | sed -n '/[[:punct:]]/p'
$
#+end_src

내장 문자 클래스는 범위를 정의하기 가장 쉬운 방법이다. ~[0-9]~ 범위를 사용하는 대신 단순히 ~[[:digit:]]~ 을 사용할 수 있다.


*** The asterisk
문자 뒤에 별표(~*~) 문자를 붙이면 해당 문자가 텍스트에 *0번 이상 나타나야만 패턴과 일치함* 을 의미한다.

#+begin_src bash
$ echo "ik" | sed -n '/ie*k/p'
ik
$ echo "iek" | sed -n '/ie*k/p'
iek
$ echo "ieek" | sed -n '/ie*k/p'
ieek
$ echo "ieeek" | sed -n '/ie*k/p'
ieeek
$ echo "ieeeek" | sed -n '/ie*k/p'
ieeeek
$
#+end_src

이 패턴은 일반적으로 *철자 오류가 자주 발생할 단어* 나 언어별 철자 변형을 처리할 때 주로 사용한다. 예를 들어, 미국식 영어와 영국식 영어 모두 사용하려면 다음과 같이 처리한다:

#+begin_src bash
$ echo "I'm getting a color TV" | sed -n '/colou*r/p'
I'm getting a color TV
$ echo "I'm getting a colour TV" | sed -n '/colou*r/p'
I'm getting a colour TV
$
#+end_src

~*u~ 패턴은 u 문자가 텍스트에 나타나도 되고 나타나지 않더라도 패턴과 일치함을 의미한다. 마찬가지로 철자를 자주 틀리는 단어가 있다면 별표 문자로 이를 수용하도록 처리할 수 있다.

#+begin_src bash
$ echo "I ate a potatoe with my lunch." | sed -n '/potatoe*/p'
I ate a potatoe with my lunch.
$ echo "I ate a potato with my lunch." | sed -n '/potatoe*/p'
I ate a potato with my lunch.
$
#+end_src

특정 문자 앞에 별표 문자를 붙이면 철자가 틀린 단어라도 허용할 수 있다.

또 하나 유용한 기능은 점(~.~) 문자와 별표(~*~) 문자를 결합한 것이다. 이 조합은 *임의의 문자들이 0번 이상 나타나는 패턴* 을 제공한다. 

입력 스트림에 두 문자열이 서로 인접할 수도 있고 아닐 수도 있을 경우 주로 사용한다.

#+begin_src bash
$ echo "this is a regular pattern expression" | sed -n '
> /regular.*expression/p'
this is a regular pattern expression
$
#+end_src

이 패턴으로 입력 스트림의 텍스트 줄 어디서든 나타날 수 있는 여러 단어를 쉽게 검색할 수 있다.

별표 문자를 문자 클래스에 적용할 수 있다. 이를 통해 텍스트에 여러 번 나타날 수 있는 문자의 그룹이나 범위를 지정할 수 있다.

#+begin_src bash
$ echo "bt" | sed -n '/b[ae]*t/p'
bt
$ echo "bat" | sed -n '/b[ae]*t/p'
bat
$ echo "bet" | sed -n '/b[ae]*t/p'
bet
$ echo "btt" | sed -n '/b[ae]*t/p'
btt
$
$ echo "baat" | sed -n '/b[ae]*t/p'
baat
$ echo "baaeeet" | sed -n '/b[ae]*t/p'
baaeeet
$ echo "baeeaeeat" | sed -n '/b[ae]*t/p'
baeeaeeat
$ echo "baakeeet" | sed -n '/b[ae]*t/p'
$
#+end_src

a 와 e 문자가 b 와 t 문자 사이에서 어떤 조합으로든 나타나면(아예 나타나지 않더라도 포함) 패턴은 일치한다. 정의한 문자 클래스 외의 다른 문자가 나타나면 실패한다.


** Extended Regular Expressions
POSIX ERE(확장 정규 표현식)는 일부 Linux 애플리케이션과 유틸리티에서 사용하는 추가적인 기호가 포함된다. 하지만, *기본적으로 sed는 ERE 패턴을 인식하지 않는다!!*

#+begin_quote
"sed와 gawk 프로그램의 정규 표현식 엔진은 서로 다르다는 점을 기억하길 바란다. gawk 프로그램은 확장 정규 표현식 패턴 기호를 사용할 수 있으며 sed에서 제공하지 않는 추가적인 필터링 기능도 제공한다. 하지만, 이런 기능들 때문에 입력 스트림을 처리하는 속도는 약간 느려질 수 있다."
#+end_quote

다음 섹션은 ~gawk~ 프로그램이나 ~sed -E~ 옵션(gnu 버전)으로 사용할 수 있는 ERE 전용 패턴에 대해 설명한다.


*** The question mark
물음표(~?~) 문자는 별표 문자와 비슷하지만 약간 다르다. 물음표 문자는 앞의 문자가 *0번이나 1번만* 나타날 수 있다. 그러나, 해당 문자가 반복해서 나타날 경우 일치하지 않는다.

#+begin_src bash
$ echo "bt" | sed -n -E '/be?t/p'
bt
$ echo "bet" | sed -n -E '/be?t/p'
bet
$ echo "beet" | sed -n -E '/be?t/p'
$
$ echo "beeet" | sed -n -E '/be?t/p'
$
#+end_src

e 문자가 전혀 나타나지 않거나 한 번만 나타날 경우만 패턴과 일치한다. 별표 문자와 마찬가지로 물음표 문자도 문자 클래스에 사용할 수 있다.

#+begin_src bash
$ echo "bt" | sed -n -E '/b[ae]?t/ p'
bt
$ echo "bat" | sed -n -E '/b[ae]?t/ p'
bat
$ echo "bot" | sed -n -E '/b[ae]?t/ p'
$
$ echo "bet" | sed -n -E '/b[ae]?t/ p'
bet
$ echo "baet" | sed -n -E '/b[ae]?t/ p'
$
$ echo "beat" | sed -n -E '/b[ae]?t/ p'
$
$ echo "beet" | sed -n -E '/b[ae]?t/ p'
$
#+end_src

패턴에 0 개 또는 1 개의 문자가 나타나면 패턴은 일치한다. 그러나, 두 문자 모두 나타나거나 하나의 문자가 두 번 나타나면 실패한다.


*** The plus sign
더하기 기호(~+~)는 별표 문자와 유사한 또 다른 패턴 기호지만 물음표 문자와 조금 다르게 동작한다. 

더하기 기호는 앞의 문자가 *최소한 1번 이상* 나타남을 의미한다. 즉, 해당 문자는 최소한 한 번은 반드시 존재해야 하며 그렇지 않으면 패턴은 일치하지 않는다.

#+begin_src bash
$ echo "beeet" | sed -n -E '/be+t/p'
beeet
$ echo "beet" | sed -n -E '/be+t/p'
beet
$ echo "bet" | sed -n -E '/be+t/p'
bet
$ echo "bt" | sed -n -E '/be+t/p'
$
#+end_src

입력 스트림에 e 문자가 존재하지 않으면 실패한다. 더하기 기호는 별표와 물음표 문자처럼 문자 클래스에 사용한다.

#+begin_src bash
$ echo "bt" | sed -n -E '/b[ae]+t/p'
$
$ echo "bat" | sed -n -E '/b[ae]+t/p'
bat
$ echo "bet" | sed -n -E '/b[ae]+t/p'
bet
$ echo "beat" | sed -n -E '/b[ae]+t/p'
beat
$ echo "beet" | sed -n -E '/b[ae]+t/p'
beet
$ echo "beeat" | sed -n -E '/b[ae]+t/p'
beeat
$
#+end_src

문자 클래스에 정의된 문자 중에서 하나라도 나타나면 지정한 패턴과 일치한다.


*** Using braces
ERE는 중괄호 문자로 반복 가능한 *제한 횟수를 지정* 할 수 있다. 종종 *간격* (interval)이라 부른다. 

간격은 두 가지 형식으로 표현할 수 있다:

- ~{m}~ : 정규 표현식 패턴이 *정확히 m 번* 나타남 
- ~{m,n}~ : 정규 표현식 패턴이 *최소 m 번, 최대 n 번* 나타남

이 기능으로 문자(또는 문자 클래스)가 패턴에서 나타나는 *횟수를 정밀하게 조정* 할 수 있다.

다음은 하나의 간격을 사용하는 예이다:

#+begin_src bash
$ echo "bt" | sed -n -E '/be{1}t/p'
$
$ echo "bet" | sed -n -E '/be{1}t/p'
bet
$ echo "beet" | sed -n -E '/be{1}t/p'
$
#+end_src

간격을 1 로 지정하면 해당 문자가 문자열에 나타날 수 있는 횟수를 1로 제한한다. 문자가 더 많이 나타나면 실패한다.

하한과 상한을 함께 지정하는 형식도 유용하다.

#+begin_src bash
$ echo "bt" | sed -n -E '/be{1,2}t/p'
$
$ echo "bet" | sed -n -E '/be{1,2}t/p'
bet
$ echo "beet" | sed -n -E '/be{1,2}t/p'
beet
$ echo "beeet" | sed -n -E '/be{1,2}t/p'
$
#+end_src

예제는 e 가 한 번 또는 두 번만 나타나는 패턴만 일치한다. 그렇지 않으면 실패한다.

정규 표현식의 간격은 문자 클래스에 적용된다.

#+begin_src bash
$ echo "bt" | sed -n -E '/b[ae]{1,2}t/p'
$
$ echo "bat" | sed -n -E '/b[ae]{1,2}t/p'
bat
$ echo "bet" | sed -n -E '/b[ae]{1,2}t/p'
bet
$ echo "beat" | sed -n -E '/b[ae]{1,2}t/p'
beat
$ echo "beet" | sed -n -E '/b[ae]{1,2}t/p'
beet
$ echo "beeat" | sed -n -E '/b[ae]{1,2}t/p'
$
$ echo "baeet" | sed -n -E '/b[ae]{1,2}t/p'
$
$ echo "baeaet" | sed -n -E '/b[ae]{1,2}t/p'
$
#+end_src

위의 정규 표현식 패턴은 a 또는 e 가 *정확히 1 번 또는 2 번만* 나타날 경우 일치하며 그 이상 어떤 조합이든 더 많이 나타나면 일치하지 않는다.


*** The pipe symbol
파이프 기호(~|~)를 사용하면 정규 표현식 엔진이 데이터를 검사할 때 *논리적 OR* 방식으로 두 개 이상의 패턴을 지정할 수 있다. 즉, 나열한 패턴 중 하나라도 입력 스트림의 텍스트와 일치하면 성공한다. 패턴이 하나도 일치하지 않으면 실패한다.

다음은 파이프 기호를 사용하는 형식이다:

#+begin_src 
expr1|expr2|...
#+end_src

예제는 다음과 같다:

#+begin_src bash
$ echo "The cat is asleep" | sed -n -E '/cat|dog/p'
The cat is asleep
$ echo "The dog is asleep" | sed -n -E '/cat|dog/p'
The dog is asleep
$ echo "The sheep is asleep" | sed -n -E '/cat|dog/p'
$
#+end_src

예제는 입력 스트림에서 정규 표현식 cat 이나 dog 을 찾는다. 정규 표현식과 파이프 기호 사이에 공백을 넣으면 공백 문자도 정규 표현식 패턴에 포함되므로 주의한다.

파이프 기호 양쪽의 정규 표현식은 문자 클래스 등 어떤 정규 표현식이든 모두 사용할 수 있다. 이를 통해 텍스트를 보다 유연하게 정의할 수 있다.

#+begin_src bash
$ echo "He has a hat." | sed -n -E '/[ch]at|dog/p'
He has a hat.
$
#+end_src

예제는 입력 스트림의 cat, hat 또는 dog 와 일치한다.


*** Grouping expressions
정규 표현식은 *괄호 문자를 사용해서 그룹화* 할 수 있다. 패턴을 그룹화하면 그룹은 하나의 일반 문자처럼 취급된다. 따라서, 특수 문자를 그룹에 적용할 수 있으며 개별 문자에 적용하던 방식과 동일하다. 

#+begin_src bash
$ echo "Sat" | sed -n -E '/Sat(urday)?/p'
Sat
$ echo "Saturday" | sed -n -E '/Sat(urday)?/p'
Saturday
$
#+end_src

urday 끝부분을 괄호로 묶고 물음표 문자와 함께 사용하면 전체 요일 이름인 Saturday 또는 축약형인 Sat 과 일치한다.

그룹화를 파이프 기호와 함께 사용해서 사용 가능한 패턴의 그룹을 만드는 것도 일반적인 처리 방식이다.

#+begin_src bash
$ echo "cat" | sed -n -E '/(c|b)a(b|t)/p'
cat
$ echo "cab" | sed -n -E '/(c|b)a(b|t)/p'
cab
$ echo "bat" | sed -n -E '/(c|b)a(b|t)/p'
bat
$ echo "bab" | sed -n -E '/(c|b)a(b|t)/p'
bab
$ echo "tab" | sed -n -E '/(c|b)a(b|t)/p'
$
$ echo "tac" | sed -n -E '/(c|b)a(b|t)/p'
$
#+end_src

~(c|b)a(b|t)~ 패턴은 첫 번째 그룹의 문자들과 두 번째 그룹의 문자들이 어떤 조합으로든 나타날 경우만 일치한다.


** Regular Expressions in Action
이제 정규 표현식의 사용 규칙과 몇 가지 간단한 예제를 살펴봤으니 그 지식을 토대로 실제로 활용할 시간이다. 

다음 섹션은 쉘 스크립트에서 자주 사용하는 정규 표현식 예제를 보여준다.


*** Counting directory files
~PATH~ 환경 변수에 정의된 디렉터리에 존재하는 실행 가능한 파일의 갯수를 세는 쉘 스크립트를 살펴보겠다. 이를 처리하려면 ~PATH~ 환경 변수의 값을 개별 디렉터리로 분리해야 한다. 

먼저 ~PATH~ 환경 변수를 표시하는 방법은 다음과 같다.

#+begin_src bash
$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/
local/games
$
#+end_src

~PATH~ 환경 변수는 애플리케이션이 Linux 시스템 어디에 위치한 지에 따라 달라진다. 핵심은 ~PATH~ 환경 변수의 각 디렉터리는 *콜론(~:~) 문자로 구분된다* 는 점을 인식하는 것이다. 따라서, 스크립트에서 사용할 디렉터리 목록을 얻으려면 콜론 문자를 공백 문자로 (대체)바꿔야 한다. 이제 sed로 간단한 정규 표현식을 사용해서 수행할 수 있다는 것도 잘 알 것이다:

#+begin_src bash
$ echo $PATH | sed 's/:/ /g'
/usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin
/usr/games /usr/local/games
$
#+end_src

디렉터리를 분리한 후, 쉘 표준 ~for~ 문으로 각 디렉터리를 반복한다.

#+begin_src bash
mypath=$(echo $PATH | sed 's/:/ /g')
for directory in $mypath
do
...
done
#+end_src

개별 디렉터리를 얻은 후, ~ls~ 프로그램으로 디렉터리의 파일을 나열할 수 있으며 또 다른 ~for~ 문으로 반복해서 파일 카운터를 증가시킬 수 있다. 최종 스크립트는 다음과 같다:

#+begin_src bash
$ cat countfiles
#!/bin/bash
# count number of files in your PATH
mypath=$(echo $PATH | sed 's/:/ /g')
count=0
for directory in $mypath
do
    check=$(ls $directory)
    for item in $check
    do
        count=$[ $count + 1 ]
    done
    echo "$directory - $count"
    count=0
done
$ ./countfiles /usr/local/sbin - 0
/usr/local/bin - 2
/usr/sbin - 213
/usr/bin - 1427
/sbin - 186
/bin - 152
/usr/games - 5
/usr/local/games – 0
$
#+end_src

이제 정규 표현식이 가진 강력한 기능 중 일부를 확인할 수 있었다!


*** Validating a phone number
이전 예제는 간단한 정규 표현식을 sed와 함께 사용해서 입력 스트림의 문자를 바꾸고 데이터를 처리하는 방법을 보여줬다. 종종 정규 표현식은 *데이터가 스크립트에 적합한 형식인지 확인하기 위한 유효성 검사* 에 자주 사용된다.

일반적인 데이터 유효성 검사는 전화번호 유효성 확인이다. 입력 양식에 전화번호를 자주 요청하지만 사용자가 항상 올바른 형식으로 입력하는 것은 아니다. 미국의 경우 전화번호를 표시하는 여러 가지 형식이 존재한다:

#+begin_src 
(123)456-7890
(123) 456-7890
123-456-7890
123.456.7890
#+end_src

사용자가 전화번호를 입력하는 방식은 네 가지이다. 따라서, 정규 표현식은 이 모든 경우를 처리할 수 있을만큼 견고하게 작성되야 한다.

정규 표현식을 만들 때는 왼쪽부터 시작해서 마주칠 수 있는 가능한 문자를 일치시키는 방식으로 구성하는 것이 좋다. 예제는 전화번호에 왼쪽 괄호가 있을 수도 있고 없을 수도 있다!! 이를 위한 패턴은 다음과 같다:

#+begin_src 
^\(?
#+end_src

캐럿(~^~) 문자는 입력 스트림의 *시작 위치를 의미* 한다. 정규 표현식에서 괄호 문자는 특수 문자로 인식하므로 일반 문자로 사용하려면 이스케이프 처리해야 한다. 물음표(~?~) 문자는 괄호가 *있을 수도 있고 없을 수도 있음* 을 의미한다.

다음은 3자리 지역번호를 처리한다. 미국은 지역번호가 2부터 시작하며 0 이나 1 로 시작하는 지역번호는 일단 없다! 따라서, 지역번호를 위한 패턴은 다음과 같다:

#+begin_src 
[2-9][0-9]{2}
#+end_src

이 패턴의 첫 번째 문자는 2 부터 9 사이의 숫자이며 그 뒤에 임의의 숫자 두 개가 따른다. 

지역번호 다음은 오른쪽 괄호가 있을 수도 있고 없을 수도 있다.

#+begin_src 
\)?
#+end_src

지역번호 다음은 공백, 공백 없음, 하이픈(-) 또는 점(.) 문자가 올 수 있다. 이 모든 경우를 처리하려면 문자 그룹과 파이프 기호를 사용한다:

#+begin_src 
(| |-|\.)
#+end_src

첫 부분의 파이프 기호는 왼쪽 괄호 뒤에 위치하며 공백이 없는 경우를 처리한다. 점(~.~) 문자를 이스케이프하지 않으면 임의의 단일 문자로 해석한다.

다음은 3자리의 교환 번호를 처리한다. 이 부분은 특별히 처리할 필요가 없다.

#+begin_src 
[0-9]{3}
#+end_src

교환 번호 다음은 공백, 하이픈(-) 또는 점(.) 문자를 일치시켜야 한다. 하지만, 여기선 공백 없음 처리를 수행할 필요는 없다. 왜냐하면, 교환 번호와 그 다음 번호 사이엔 최소한 하나의 구분 문자가 반드시 있어야 하기 때문이다.

#+begin_src 
( |-|\.)
#+end_src

마지막으로 문자열 끝의 4자리 전화번호(내선 번호)를 일치시켜야 한다.

#+begin_src 
[0-9]{4}$
#+end_src

전체 패턴을 조합하면 다음과 같다:

#+begin_src 
^\(?[2-9][0-9]{2}\)?(| |-|\.)[0-9]{3}( |-|\.)[0-9]{4}$
#+end_src

위의 정규 표현식 패턴은 sed로 전화번호를 걸러내는 용도로 사용할 수 있다. 이제 위의 정규 표현식을 활용해서 간단한 스크립트로 만들어 전화번호 목록 파일을 해당 스크립트로 필터링한다.

다음은 전체 스크립트이다:

#+begin_src bash
$ cat isphone
#!/bin/bash
# script to filter out bad phone numbers
sed -n -E '/^\(?[2-9][0-9]{2}\)?(| |-|\.)[0-9]{3}( |-|\.)[0-9]{4}$/p'
$
#+end_src

정확히 알 수 없겠지만 쉘 스크립트에서 sed 명령은 한 줄로 작성한다!! 

이제 전화번호 데이터를 다음과 같이 스크립트로 리디렉션해서 필터로 처리할 수 있다.

#+begin_src bash
$ echo "317-555-1234" | ./isphone
317-555-1234
$ echo "000-555-1234" | ./isphone
$ echo "312 555-1234" | ./isphone
312 555-1234
$
#+end_src

또는, 전화번호가 담긴 전체 파일을 리디렉션해서 유효하지 않은 번호만 필터링할 수 있다.

#+begin_src bash
$ cat phonelist
000-000-0000
123-456-7890
212-555-1234
(317)555-1234
(202) 555-9876
33523
1234567890
234.123.4567
$ cat phonelist | ./isphone
212-555-1234
(317)555-1234
(202) 555-9876
234.123.4567
$
#+end_src

이로써 정규 표현식과 일치하는 유효한 전화번호만 출력된다.


*** Parsing an e-mail address
이메일은 매우 중요한 커뮤니케이션 수단이다. 이메일 주소의 유효성 검사는 스크립트 작성자에겐 도전적인 작업이다. 그 이유는 이메일 주소를 만드는 방법이 매우 다양할 수 있기 때문이다.

이메일의 기본적인 형식은 다음과 같다:

#+begin_src 
username@hostname
#+end_src

username 은 영숫자 외에 다음과 같은 특수 문자를 사용할 수 있다:

- 점(~.~) 
- 대시(~-~) 
- 더하기 기호(~+~) 
- 밑줄(~_~)

이런 문자들은 어떤 조합으로든 유효한 이메일 사용자 ID에 포함될 수 있다.

이메일의 hostname 부분은 하나 이상의 도메인 이름과 서버 이름으로 구성된다. 서버 및 도메인 이름 역시 엄격한 명명 규칙을 따르며 다음과 같은 문자를 허용한다:

- 영숫자 문자 
- 점(~.~) 
- 밑줄(~_~)

서버 이름과 도메인 이름은 각각 점 문자로 구분되며 서버 이름이 먼저 오고 그 다음 서브 도메인 이름, 마지막으로 최상위 도메인 이름이 위치하며 마지막엔 점 문자가 없어야 한다.

한때 최상위 도메인(TLD)은 제한적이라서 정규 표현식 작성자는 모든 도메인을 패턴에 포함시켰다. 하지만, 인터넷이 성장하면서 TLD의 수가 급격히 늘어났고 이런 방식은 더이상 실효성있는 해결책이 아니다!

지금부터 정규 표현식을 *왼쪽부터* 순서대로 만들어 보겠다. 

사용자 이름은 여러 가지 문자가 포함될 수 있다!는 점을 알고 있으므로 이 부분은 비교적 쉽게 처리할 수 있다:

#+begin_src 
^([a-zA-Z0-9_\-\.\+]+)@
#+end_src

이 그룹은 사용자 이름에 허용할 문자를 지정하며 플러스 기호(~+~)는 최소한 하나 이상의 문자가 반드시 있어야 함을 의미한다. 그 다음 문자는 당연히 ~@~ 기호이다. 특별할 것 없는 부분이다.

hostname 은 서버 이름과 서브 도메인 이름을 일치시키기 위해 이전과 동일한 방식의 정규 표현식 기법을 사용한다:

#+begin_src 
([a-zA-Z0-9_\-\.]+)
#+end_src

패턴은 다음과 같은 형식의 텍스트와 일치한다:

#+begin_src 
server
server.subdomain
server.subdomain.subdomain
#+end_src

최상위 도메인(TLD)은 특별한 규칙이 있다. TLD는 알파벳 문자만 사용할 수 있으며 길이는 최소 2자(국가 코드 등)]에서 최대 5자이다.

다음은 최상위 도메인(TLD)의 정규 표현식이다:

#+begin_src 
\.([a-zA-Z]{2,5})$
#+end_src

패턴 전체를 모두 조합하면 다음과 같다:

#+begin_src 
^([a-zA-Z0-9_\-\.\+]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$
#+end_src

이 패턴은 사용 형식이 잘못된 이메일 주소를 데이터 목록에서 걸러낸다. 이제 이 정규 표현식을 구현한 스크립트를 만들 수 있다:

#+begin_src bash
$ echo "rich@here.now" | ./isemail
rich@here.now
$ echo "rich@here.now." | ./isemail
$
$ echo "rich@here.n" | ./isemail
$
$ echo "rich@here-now" | ./isemail
$
$ echo "rich.blum@here.now" | ./isemail
rich.blum@here.now
$ echo "rich_blum@here.now" | ./isemail
rich_blum@here.now
$ echo "rich/blum@here.now" | ./isemail
$
$ echo "rich#blum@here.now" | ./isemail
$
$ echo "rich*blum@here.now" | ./isemail
$
#+end_src

*** Summary
쉘 스크립트로 파일을 다루려면 정규 표현식에 익숙해져야 한다. 정규 표현식은 Linux 유틸리티, 프로그래밍 언어 그리고 정규 표현식 엔진을 사용하는 모든 애플리케이션에서 다양하게 구현된다. Linux는 다양한 정규 표현식 엔진이 사용되며 그 중에서 가장 널리 쓰이는 두 가지는 POSIX 기본 정규 표현식(BRE) 엔진과 POSIX 확장 정규 표현식(ERE) 엔진이다. sed는 주로 BRE 엔진을 따르며 ~sed -E~ 옵션으로 ERE 엔진도 사용할 수 있다.

정규 표현식은 입력 스트림의 텍스트를 필터링하는 패턴 템플릿을 정의한다. 이 패턴은 일반 문자와 특수 문자 조합으로 구성된다. 특수 문자는 정규 표현식 엔진이 하나 이상의 문자를 일치시킬 때 사용하며 시스템 쉘에서 와일드카드 문자 작동 방식과 유사하다. 일반 문자와 특수 문자를 조합해서 모든 유형의 데이터를 일치시키는 패턴을 정의할 수 있다. 그 다음 sed로 데이터 스트림의 특정 데이터만 필터링하거나 애플리케이션에서 받은 데이터를 검증할 수 있다.

다음 장은 sed를 사용해서 고급 텍스트 조작을 수행하는 방법에 대해 좀 더 깊이 다룬다. sed는 대용량 데이터 스트림을 처리하거나 필요한 데이터만 필터링하는 데 유용한 다양한 고급 기능이 포함되어 있다.


* Advanced sed
첫 번째 장에서 sed로 입력 스트림의 텍스트를 조작하는 기본적인 방법을 살펴봤다. sed 기본 명령으로 대부분의 일상적인 텍스트 편집 작업을 처리할 수 있다. 

이번 장은 sed로 처리할 수 있는 고급 기능을 살펴본다. 이 기능을 자주 사용하진 않지만 필요할 때 사용할 수 있다는 점과 사용 방법을 알아두면 유용할 것이다.


** Looking at Multiline Commands
sed로 기본 명령을 사용할 때 한 가지 제한 사항을 눈치챘을 것이다. sed 명령은 *한 줄의 데이터에 동작한다!!* 는 것이다.

sed는 입력 스트림을 읽을 때 *줄바꿈 문자 기준으로 데이터를 줄 단위로 나누며 각 줄을 하나씩 처리* 한다. 즉, 사용자가 정의한 스크립트나 명령을 한 줄에 모두 적용한 후, 다음 줄로 넘어가면서 처리를 반복한다.

하지만, 간혹 *여러 줄에 나눠진 데이터를 작업할 때* 가 있다!! 

대표적으로 긴 문구를 찾거나 교체할 경우이다. 예를 들어, Linux System Administrators Group 문구가 두 줄에 나눠져 분리될 가능성이 있다. 일반적인 sed 명령은 이렇게 *분리된 문구를 제대로 처리할 수 없다!!*

다행히 sed 설계자는 이런 상황까지 고려했고 해결책도 마련했다. sed는 여러 줄의 텍스트를 처리할 수 있는 세 가지 명령이 포함되어 있다:

- ~N~ : 다음 줄을 현재 줄에 추가해서 *멀티라인을 생성* 한다.
- ~D~ : 멀티라인의 *첫 번째 줄만 삭제* 한다. 
- ~P~ : 멀티라인의 *첫 번째 줄만 출력* 한다.

다음 섹션은 멀티라인 명령을 자세히 살펴보고 스크립트에서 어떻게 활용할 수 있는지 예제로 설명한다.


*** Navigating the next command
멀티라인 next (N)명령을 살펴보기 전에 단일라인 next 명령이 어떻게 작동하는지 이해해야 한다. 단일라인 명령의 동작 방식을 알면 멀티라인 next 명령이 어떻게 작동하는지 쉽게 이해할 수 있다.


**** Using the single-line next command
소문자 ~n~ (next) 명령은 sed 편집기에 *시작 명령으로 돌아가지 않고 입력 스트림의 다음 줄로 이동하라!* 고 지시한다.

일반적으로 sed는 한 줄의 텍스트에 정의한 모든 명령을 처리한 후 다음 줄로 이동한다. 하지만, 단일라인 next 명령은 이런 *처리 흐름을 변경* 한다. 이 설명은 다소 복잡하고 실제로도 그럴 것이다. 

예를 들어, 다섯 줄로 구성된 파일에서 두 줄이 빈 줄이라 가정한다. 목표는 header 줄 다음의 빈 줄은 제거하고 마지막 줄 앞의 빈 줄은 그대로 유지하는 것이다.

다음과 같이 단순히 빈 줄만 제거하는 sed 스크립트는 두 개의 빈 줄 모두 제거한다!:

#+begin_src bash
$ cat data1.txt
This is the header line.

This is a data line.

This is the last line.
$
$ sed '/^$/d' data1.txt
This is the header line.
This is a data line.
This is the last line.
$
#+end_src

제거할 줄이 빈 줄이라 특정 빈 줄만 고유하게 식별할 수 있는 패턴이 없다. 해결책은 ~n~ 명령을 사용하는 방법이다.

다음 예제는 header 를 포함한 줄부터 찾는다. 그 줄을 식별한 후, ~n~ 명령으로 다음 줄(즉, 빈 줄)로 이동한다.

#+begin_src bash
$ sed '/header/{n; d}' data1.txt
This is the header line.
This is a data line.

This is the last line.
$
#+end_src

sed는 나머지 명령을 계속 처리하며 ~d~ 명령으로 빈 줄을 삭제한다. sed가 명령 끝에 도달하면 입력 스트림에서 다음 줄을 읽고 처음부터 다시 처리한다. 처리 이후 sed는 header 가 포함된 줄을 찾지 못하므로 나머지 줄은 삭제하지 않는다.


**** Combining lines of text
이제 단일라인 next 명령을 살펴봤으니 멀티라인 명령을 살펴보자. 단일라인 next 명령은 입력 스트림에서 다음 줄의 텍스트를 가져와서 sed의 *처리 공간(패턴 공간)]으로 이동* 시킨다. 

멀티라인 next 명령은 대문자 ~N~ 을 사용하며 다음 줄의 텍스트를 *패턴 공간의 기존 텍스트에 추가* 한다. 따라서, 입력 스트림의 *두 줄은 하나의 패턴 공간에 결합* 된다. 또한, 이렇게 합쳐진 두 줄은 *줄바꿈 문자로 구분* 되지만 sed는 합쳐진 두 줄을 하나의 줄처럼 처리할 수 있다.

다음은 ~N~ 명령의 작동 방식을 보여주는 예제이다:

#+begin_src bash
$ cat data2.txt
This is the header line.
This is the first data line.
This is the second data line.
This is the last line.
$
$ sed '/first/{N; s/\n/ /}' data2.txt
This is the header line.
This is the first data line. This is the second data line.
This is the last line.
$
#+end_src

sed는 우선 first 가 포함된 줄을 검색한다. 해당 줄을 찾으면 ~N~ 명령으로 다음 줄을 현재 줄과 패턴 공간으로 결합한다. 그 다음 대체(~s~) 명령으로 줄바꿈 문자를 공백 문자로 대체한다. 그 결과 결합된 두 줄은 마치 한 줄처럼 출력된다.

이 방식은 텍스트가 두 줄에 분리될 경우 유용하다. 다음은 그 예제이다:

#+begin_src bash
$ cat data3.txt
On Tuesday, the Linux System
Administrator's group meeting will be held.
All System Administrators should attend.
Thank you for your attendance.
$
$ sed 's/System Administrator/Desktop User/' data3.txt
On Tuesday, the Linux System
Administrator's group meeting will be held.
All Desktop Users should attend.
Thank you for your attendance.
$
#+end_src

대체 명령(~s~)은 System Administrator 검색 문자열을 찾는다. 검색 문자열이 한 줄에 나타날 경우 문제없이 검색 문자열을 대체 문자열로 대체한다. 하지만, 검색 문자열이 두 줄로 분리될 경우 대체 명령은 *패턴을 인식하지 못한다!!* 이 문제의 해결책은 멀티라인 ~N~ 명령이다:

#+begin_src bash
$ sed 'N; s/System.Administrator/Desktop User/' data3.txt
On Tuesday, the Linux Desktop User's group meeting will be held.
All Desktop Users should attend.
Thank you for your attendance.
$
#+end_src

~N~ 명령으로 첫 번째 검색 문자열이 포함된 줄과 그 다음 줄을 패턴 공간에서 결합하고 줄바꿈 문자로 분리된 경우까지 처리한다. 여기서 System 과 Administrator 사이에 와일드카드(~.~) 문자를 사용해서 공백 문자와 줄바꿈 문자까지 모두 검색 일치시킨다. 

하지만, 줄바꿈 문자를 일치시킬 경우 대체 문자열에서 제거되어 두 줄이 한 줄로 병합된다. 이것은 원하던 처리 결과가 아닐 수 있다. sed로 이 문제를 해결하려면 대체 명령을 나눠서 처리해야 한다. 즉, 하나는 여러 줄에 걸친 경우를 처리하고 다른 하나는 한 줄에 있는 경우를 처리한다.

#+begin_src bash
$ sed 'N
> s/System\nAdministrator/Desktop\nUser/
> s/System Administrator/Desktop User/
> ' data3.txt
On Tuesday, the Linux Desktop
User's group meeting will be held.
All Desktop Users should attend.
Thank you for your attendance.
$
#+end_src

첫 번째 명령은 검색 문자열의 줄바꿈 문자를 명시적으로 찾은 후, 대체 문자열에도 포함한다. 이렇게 처리하면 대체 문자열도 같은 위치에 줄바꿈 문자를 그대로 유지할 수 있다.

하지만, 여전히 미묘한 문제가 있다. sed는 항상 명령을 실행하기 전에 다음 줄의 텍스트를 패턴 공간으로 읽어 들인다. 따라서, 입력 스트림의 마지막 줄에 도달하면 다음 줄이 존재하지 않으므로 ~N~ 명령은 sed를 *중단시킨다!!* 즉, 검색 문자열이 마지막 줄에 있을 경우 제대로 처리하지 못한다.

#+begin_src bash
$ cat data4.txt
On Tuesday, the Linux System
Administrator's group meeting will be held.
All System Administrators should attend.
$
$ sed 'N
> s/System\nAdministrator/Desktop\nUser/
> s/System Administrator/Desktop User/
> ' data4.txt
On Tuesday, the Linux Desktop
User's group meeting will be held.
All System Administrators should attend.
$
#+end_src

예제는 System Administrator 검색 문자열이 마지막 줄에 있으므로 ~N~ 명령은 처리하지 못한다!! 왜냐하면, 더이상 결합할 다음 줄이 없기 때문이다. 하지만, 이 문제는 의외로 간단히 해결할 수 있다. 단일라인 처리는 ~N~ 명령 앞에 배치하고 멀티라인 처리는 ~N~ 명령 뒤에 배치한다. 

#+begin_src bash
$ sed '
> s/System Administrator/Desktop User/
> N
> s/System\nAdministrator/Desktop\nUser/
> ' data4.txt
On Tuesday, the Linux Desktop
User's group meeting will be held.
All Desktop Users should attend.
$
#+end_src

이제 마지막 줄도 처리할 수 있고 입력 스트림 중간에 검색 문자열이 분리된 경우도 처리할 수 있다.


*** Navigating the multiline delete command
이전 장에서 sed의 단일라인 삭제 명령(~d~)을 설명했다. 이 명령은 패턴 공간의 줄을 삭제한다. 하지만, 단일라인 삭제 명령을 ~N~ 명령과 사용할 경우엔 *주의해야 한다.*

#+begin_src bash
$ sed 'N; /System\nAdministrator/d' data4.txt
All System Administrators should attend.
$
#+end_src

위의 명령은 System 과 Administrator 를 두 줄에서 찾은 후, 패턴 공간에 합쳐진 두 줄 모두 삭제한다!! 이것은 의도했을 수도 있고 아닐 수도 있다.

sed는 이 문제를 해결하기 위해 멀티라인 삭제 명령(~D~)을 제공한다. 이 명령은 *패턴 공간에 병합된 첫 번째 줄만 삭제하며 이때 줄바꿈 문자도 포함해서 모든 문자를 제거* 한다.

#+begin_src bash
$ sed 'N; /System\nAdministrator/D' data4.txt
Administrator's group meeting will be held.
All System Administrators should attend.
$
#+end_src

따라서, ~N~ 명령으로 패턴 공간에 병합된 *두 번째 줄은 그대로 유지* 된다. 이 기능은 데이터 *문자열이 포함된 줄 앞 줄을 제거할 때 유용* 하다. 

다음은 입력 스트림에서 첫 번째 줄 앞의 빈 줄만 제거하는 예제이다:

#+begin_src bash
$ cat data5.txt

This is the header line.
This is a data line.

This is the last line.
$
$ sed '/^$/{N; /header/D}' data5.txt
This is the header line.
This is a data line.

This is the last line.
$
#+end_src

위의 명령은 빈 줄을 찾은 다음 ~N~ 명령으로 다음 줄을 패턴 공간에 추가한다. 패턴 공간에 header 가 포함되면 ~D~ 명령으로 패턴 공간의 첫 번째 줄만 제거한다.

만약, ~N~ 과 ~D~ 명령이 없었다면 첫 번째 빈 줄만 제거하고 다른 빈 줄은 그대로 유지하는 작업은 처리할 수 없다.


*** Navigating the multiline print command
이쯤되면 단일라인 명령과 멀티라인 명령의 차이점을 이해했을 것이다. 멀티라인 출력 명령(~P~)도 동일한 방식으로 작동한다. 이 명령은 *멀티라인으로 구성된 패턴 공간의 첫 번째 줄만 출력* 한다. 즉, 줄바꿈 문자까지의 모든 문자를 출력한다.

~P~ 명령은 ~sed -n~ 옵션으로 기본 출력을 억제할 때 원하는 텍스트만 출력하는 단일라인 출력 명령(~p~)과 유사한 방식으로 사용한다.

#+begin_src bash
$ sed -n 'N; /System\nAdministrator/P' data3.txt
On Tuesday, the Linux System
$
#+end_src

멀티라인에서 일치가 발생하면 ~P~ 명령은 패턴 공간의 첫 번째 줄만 출력한다. 멀티라인 ~P~ 명령의 강력함은 ~N~ 및 ~D~ 명령과 조합할 때 빛을 발휘한다.

~D~ 명령의 독특한 기능은 *스크립트 처음으로 돌아간 후, 동일한 패턴 공간에 명령을 반복하도록 강제한다!!* 는 것이다. 또한, *입력 스트림에서 새로운 줄을 읽지 않는다!!* 따라서, ~N~ 명령과 함께 사용하면 패턴 공간을 한 줄씩 처리하면서 여러 줄을 효과적으로 처리할 수 있다. 

~P~ 명령으로 첫 번째 줄만 출력하고 ~D~ 명령으로 첫 번째 줄만 삭제한 뒤 스크립트 처음으로 루프를 되돌린다. 스크립트의 처음으로 돌아오면 ~N~ 명령으로 다음 줄을 읽고 과정을 시작한다. 이 루프는 입력  스트림 끝까지 계속 반복된다.


** Holding Space
*패턴 공간은 sed가 명령을 처리할 동안 텍스트를 저장하고 패턴을 검사하는 활성 버퍼 영역* 이다. 하지만, 텍스트를 저장할 수 있는 공간이 패턴 공간만 있는 것은 아니다. sed는 또 다른 버퍼인 *홀드 공간(hold space)]을 사용* 한다. *홀드 공간은 패턴 공간에서 작업할 동안 특정 줄을 임시로 저장하는 용도로 사용* 한다.

홀드 공간을 다룰 때 사용하는 다섯 가지 명령은 다음과 같다.

| 명령어 | 설명                                  |
|--------+---------------------------------------|
| ~h~    | 패턴 공간의 내용을 +홀드 공간에 복사* |
| ~H~    | 패턴 공간의 내용을 *홀드 공간에 추가* |
| ~g~    | 홀드 공간의 내용을 *패턴 공간에 복사* |
| ~G~    | 홀드 공간의 내용을 *패턴 공간에 추가* |
| ~x~    | 패턴 공간과 홀드 공간의 *내용을 교환* |
 
위의 명령으로 *패턴 공간의 텍스트를 홀드 공간으로 조작* 할 수 있다. 이를 통해 패턴 공간을 비우고 새로운 문자열을 처리할 수 있다.

일반적으로 ~h~ 또는 ~H~ 명령으로 패턴 공간의 문자열을 홀드 공간으로 이동시킨 후에는 ~g~, ~G~ 또는 ~x~ 명령으로 저장한 문자열을 패턴 공간으로 다시 가져온다. 그렇지 않으면 애초에 홀드 공간에 저장할 필요도 없다.

sed는 이처럼 두 개의 버퍼 영역이 존재하므로 현재 어떤 줄의 텍스트가 어느 공간에 있는지 파악하는 것이 혼란스러울 수 있다. 다음은 ~h~ 와 ~g~ 명령으로 sed의 버퍼 공간 사이의 *데이터 이동 방법을 보여주는 간단한 예제* 이다:

#+begin_src bash
$ cat data2.txt
This is the header line.
This is the first data line.
This is the second data line.
This is the last line.
$
$ sed -n '/first/ {h; p; n; p; g; p}' data2.txt
This is the first data line.
This is the second data line.
This is the first data line.
$
#+end_src

위의 코드를 단계별로 살펴보면 다음과 같다:

+ sed는 정규 표현식으로 first 가 포함된 줄을 필터링한다. 
+ first 가 일치하면 중괄호 ~{ }~ 첫 번째 명령인 ~h~ 명령으로 *홀드 공간에 저장* 한다. 
+ ~p~ 명령은 *패턴 공간의 내용을 출력* 한다. 즉, 첫 번째 줄을 출력한다. 
+ ~n~ 명령은 *다음 줄(두 번째 데이터 줄)을 가져와서 패턴 공간에 저장* 한다. 
+ ~p~ 명령은 *현재 패턴 공간의 내용 즉, 두 번째 줄을 출력* 한다.
+ ~g~ 명령은 *홀드 공간의 내용(첫 번째 데이터 줄)을 다시 패턴 공간으로 복사해서 현재 텍스트를 대체* 한다. 
+ ~p~ 명령은 *현재 패턴 공간의 내용 즉, 첫 번째 줄을 출력* 한다.

이처럼 홀드 공간을 활용해서 줄을 재배치함으로 *첫 번째 줄을 두 번째 줄 뒤에 출력* 할 수 있다!! 만약, 첫 번째 ~p~ 명령을 생략하면 *줄을 역순으로 출력* 할 수 있다.

#+begin_src bash
$ sed -n '/first/ {h; n; p; g; p}' data2.txt
This is the second data line.
This is the first data line.
$
#+end_src

드디어 유용한 작업의 시작점에 도달했다!! 이 기술을 활용하면 sed로 줄 순서를 역순으로 뒤집는 것도 가능하다!! 하지만, 이를 처리하기 전에 sed의 부정 기능(negating feature)을 이해해야 한다.

다음 섹션은 부정 기능을 설명한다.


*** Negating a Command
이전 장에서 살펴본 것처럼 *sed는 명령을 입력 스트림의 모든 줄에 적용하거나 단일 주소 또는 주소 범위로 지정한 줄에만 적용* 할 수 있다. 하지만, 명령을 특정 주소나 주소 범위에 *적용하지 않도록 처리* 할 수 있다.

이때 사용하는 것이 느낌표 명령(~!~)] 즉, *부정 명령* 이다. 부정 명령은 명령 실행 상황을 역으로 실행되지 않도록 만든다. 다음은 이 기능을 보여주는 예제이다:

#+begin_src bash
$ sed -n '/header/!p' data2.txt
This is the first data line.
This is the second data line.
This is the last line.
$
#+end_src

일반적으로 ~p~ 명령은 data2.txt 파일에 header 가 포함된 줄만 출력한다. 하지만, 느낌표(~!~) 명령을 추가하면 반대로 header 가 포함된 줄을 *제외한 모든 줄을 출력* 한다.

느낌표 문자로 사용하는 부정 명령은 다양한 상황에서 유용하게 사용한다. 앞서 Navigating the next command 섹션에서 입력 스트림 마지막 줄에서 작동하지 않던 문제를 다룬 바 있다. 그 이유는 마지막 줄 뒤에는 더이상의 줄이 없기 때문이였다. 이 문제를 해결할 때 느낌표(~!~) 부정 명령이 효과적이다.

#+begin_src bash
$ sed 'N;
> s/System\nAdministrator/Desktop\nUser/
> s/System Administrator/Desktop User/
> ' data4.txt
On Tuesday, the Linux Desktop
User's group meeting will be held.
All System Administrators should attend.
$
$ sed '$!N;
> s/System\nAdministrator/Desktop\nUser/
> s/System Administrator/Desktop User/
> ' data4.txt
On Tuesday, the Linux Desktop
User's group meeting will be held.
All Desktop Users should attend.
$
#+end_src

예제는 부정 명령(~!~)과 ~N~ 명령을 함께 사용하는 방법을 보여주며 달러 기호(~$~)도 사용한다. 달러 기호는 입력 스트림의 마지막 줄을 의미하고 마지막 줄에 도달할 경우 ~N~ 명령을 실행하지 않는다!! 하지만, 다른 줄은 명령을 정상 실행한다.

이제 완벽히 입력 스트림의 *줄 순서를 역순으로 바꿀 수 있다!!* 입력 스트림의 줄 순서를 뒤집어 즉, 마지막 줄 먼저 출력하고 첫 번째 줄을 마지막에 출력하려면 홀드 공간을 활용한 약간 복잡한 작업이 필요하다.

전체적인 작업 흐름은 다음과 같다:

+ 한 줄을 패턴 공간에 저장한다. 
+ 패턴 공간을 홀드 공간으로 옮긴다. 
+ 다음 줄을 패턴 공간에 저장한다. 
+ 홀드 공간의 내용에 패턴 공간의 내용을 추가한다. 
+ 패턴 공간의 내용을 홀드 공간으로 다시 옮긴다. 
+ 3 ~ 5단계를 반복해서 모든 줄을 역순으로 홀드 공간에 저장한다. 
+ 이렇게 저장한 줄을 가져와서 출력한다.

우선 이렇게 줄을 처리하는 과정을 출력하면 안된다. 따라서, sed 명령을 실행할 때 ~sed -n~ 옵션으로 자동 출력을 억제한다. 다음으로 처리할 것은 홀드 공간의 텍스트를 패턴 공간에 어떻게 추가할 것인가? 이다. 이 작업은 ~G~ 명령으로 처리한다.

다음은 첫 번째 줄은 홀드 공간에 추가하지 않아야 한다!! 는 점이다. 이 문제는 느낌표(~!~) 부정 명령을으로 쉽게 해결할 수 있다.

#+begin_src 
1!G
#+end_src

다음은 패턴 공간(역순으로 추가한 텍스트 줄)을 홀드 공간에 저장하는 것이다. 이 작업도 간단하며 ~h~ 명령으로 처리한다. 입력 스트림이 역순으로 패턴 공간에 모두 저장될 때 처리 결과를 출력한다.

입력 스트림의 마지막 줄에 도달했을 때 전체 데이터는 패턴 공간에 모두 다 들어온 상태임을 알 수 있다. 따라서, 결과를 출력하려면 다음과 같은 명령을 사용한다:

#+begin_src 
$p
#+end_src

줄 순서를 뒤집는 sed 스크립트를 만들기 위한 모든 기능이 준비됐다. 이제 테스트할 차례이다.

#+begin_src bash
$ cat data2.txt
This is the header line.
This is the first data line.
This is the second data line.
This is the last line.
$
$ sed -n '{1!G; h; $p}' data2.txt
This is the last line.
This is the second data line.
This is the first data line.
This is the header line.
$
#+end_src

위의 스크립트는 예상대로 잘 작동한다!! 스크립트의 출력은 원래 줄 순서를 역순으로 뒤집어 출력한다! 이것은 sed로 홀드 공간을 활용하는 가장 강력한 기능을 정확히 보여주는 예제이다. 이처럼 홀드 공간을 사용하면 줄 순서를 쉽게 조작할 수 있는 강력한 방법을 제공한다.

#+begin_quote
"bash 쉘도 역순 출력 기능을 수행할 수 있다. ~tac~ 명령인데 이 명령은 텍스트 파일을 줄 단위로 역순으로 출력한다. ~tac~ 이란 이름은 ~cat~ 명령의 반대 기능을 수행한다는 의미로 지어진 재치있는 이름이다. ~cat~ 명령이 순서대로 출력한다면 ~tac~ 명령은 뒤에서 출력한다."
#+end_quote


** Changing the Flow
sed는 일반적으로 *스크립트 맨 위부터 시작해서 아래로 진행하면서 명령을 처리* 한다. 예외적으로 ~D~ 명령은 *새로운 줄을 읽지 않고 스크립트 맨 위로 다시 돌아간다!!*

sed는 스크립트의 실행 흐름을 변경할 수 있는 방법을 제공한다. 이를 통해 구조적인 프로그래밍과 유사한 결과를 만들 수 있다!!


*** Branching
앞에서 느낌표(~!~) 부정 명령으로 줄에 대한 명령 효과를 부정하는 방법을 살펴봤다. sed는 이보다 확장된 기능으로 *주소, 검색 문자열 또는 주소 범위에 명령 블록 전체를 부정하는 방법* 도 제공한다. 이를 통해 데이터 스트림의 특정 부분에만 그룹 명령을 적용할 수 있다.

다음은 ~b~ 분기 명령(branch command)의 사용 형식이다:

#+begin_src 
[address]b [label]
#+end_src

address 매개 변수는 어떤 줄이나 줄들의 데이터가 분기 명령을 트리거할지 결정한다. label 매개 변수는 분기할 위치를 정의한다. 만약, *label 매개 변수가 지정되지 않으면 branch 명령은 기본적으로 스크립트 끝으로 이동* 한다.

#+begin_src bash
$ cat data2.txt
This is the header line.
This is the first data line.
This is the second data line.
This is the last line.
$
$ sed '{2,3b ; s/This is/Is this/ ; s/line./test?/}' data2.txt
Is this the header test?
This is the first data line.
This is the second data line.
Is this the last test?
$
#+end_src

branch 명령은 입력 스트림의 두 번째, 세 번째 줄에선 명령 실행을 건너뛴다!!

스크립트 끝으로 이동하는 대신 branch 명령으로 점프할 수 있는 라벨(label)을 정의할 수 있다. *라벨은 콜론(~:~) 문자로 시작하며 최대 7자* 까지 사용할 수 있다.

#+begin_src 
:label2
#+end_src

라벨로 이동하려면 *~b~ 명령 뒤에 라벨 이름을 지정* 한다. 이처럼 라벨을 사용하면 분기 주소와 일치한 명령은 건너뛰면서 스크립트의 다른 명령은 계속해서 처리할 수 있다.

#+begin_src bash
$ sed '{/first/b jump1 ; s/This is the/No jump on/
> :jump1
> s/This is the/Jump here on/}' data2.txt
No jump on header line
Jump here on first data line
No jump on second data line
No jump on last line
$
#+end_src

branch 명령은 first 가 나타나면 jump1 라벨로 점프한다. 만약, branch 명령의 패턴과 줄이 일치하지 않으면 sed는 스크립트의 다음 명령을 계속 처리하며 이 경우 branch 라벨 이후의 명령도 포함해서 실행한다. 

#+begin_quote
"따라서, first 와 일치하지 않는 줄은 세 개의 대체 명령 모두 실행된다!!"
#+end_quote

반면, branch 패턴과 일치하면 sed는 branch 라벨로 분기한다. 이 경우 마지막 대체 명령만 실행된다.

다음 예제는 sed 스크립트에서 아래쪽 라벨로 분기하는 방식을 보여준다. 하지만, 라벨은 스크립트 앞에 위치할 수 있으며 이것으로 루프 효과를 만들 수 있다.

#+begin_src bash
$ echo "This, is, a, test, to, remove, commas." | sed -n '{
> :start
> s/,//1p
> b start
> }'
This is, a, test, to, remove, commas.
This is a, test, to, remove, commas.
This is a test, to, remove, commas.
This is a test to, remove, commas.
This is a test to remove, commas.
This is a test to remove commas.
^C
$
#+end_src

스크립트에서 각 반복(iteration)은 문자열의 첫 번째 쉼표 문자를 제거하고 문자열을 출력한다. 하지만, 이 스크립트엔 치명적인 문제가 있다. 그것은 바로 영원히 끝나지 않는 *무한 루프가 발생* 한다. 왜냐하면, 쉼표 문자를 계속 찾으면서 반복하므로 ~Ctrl+C~ 로 중단 신호를 보내지 않는 한 종료되지 않는다!!

이 문제를 해결하려면 branch 명령에 주소 패턴을 지정해야 한다. 즉, 특정 패턴이 존재할 때만 분기하며 만약, 패턴이 없다면 분기를 멈추도록 처리한다.

#+begin_src bash
$ echo "This, is, a, test, to, remove, commas." | sed -n '{
> :start
> s/,//1p
> /,/b start
> }'
This is, a, test, to, remove, commas.
This is a, test, to, remove, commas.
This is a test, to, remove, commas.
This is a test to, remove, commas.
This is a test to remove, commas.
This is a test to remove commas.
$
#+end_src

이제 branch 명령은 쉼표 문자가 있을 때만 분기한다. 마지막 쉼표까지 모두 제거한 후에는 branch 명령이 실행되지 않으므로 정상적으로 종료한다.


*** Testing
branch 명령과 유사하게 test 명령(~t~)도 sed 스크립트의 실행 흐름을 수정한다. 주소 기준으로 특정 라벨로 점프하는 branch 명령과 달리 test 명령은 이전 대체 명령의 처리 결과를 기준으로 특정 라벨로 점프한다.

대체 명령이 성공적으로 대체 문자열로 대체한 경우만 test 명령은 지정한 라벨로 분기한다. 따라서, 대체 명령이 검색 문자열과 일치하지 않으면 test 명령은 분기하지 않는다.

test 명령은 branch 명령과 동일한 형식으로 사용한다.

#+begin_src 
[address]t [label]
#+end_src

branch 명령과 마찬가지로 라벨을 지정하지 않으면 test 명령이 성공하면 스크립트 끝으로 분기한다. test 명령은 입력 스트림에 간단한 ~if-then~ 구문을 구현할 수 있는 저렴한 방법을 제공한다.

예를 들어, 대체 작업을 처리한 경우 다른 명령을 수행할 필요가 없을 경우 test 명령으로 처리할 수 있다.

#+begin_src bash
$ sed '{
> s/first/matched/
> t
> s/This is the/No match on/
> }' data2.txt
No match on header line
This is the matched data line
No match on second data line
No match on last line
$
#+end_src

첫 번째 대체 명령은 first (검색) 문자열을 찾는다. 검색 문자열과 일치하면 텍스트를 대체하고 test 명령은 두 번째 대체 명령을 건너뛴다. 반대로 첫 번째 대체 명령이 검색 문자열과 일치하지 않으면 두 번째 대체 명령이 실행된다.

이처럼 test 명령으로 이전에 branch 명령으로 시도했던 무한 루프 문제를 좀 더 깔끔하게 처리할 수 있다.

#+begin_src bash
$ echo "This, is, a, test, to, remove, commas. " | sed -n '{
> :start
> s/,//1p
> t start
> }'
This is, a, test, to, remove, commas.
This is a, test, to, remove, commas.
This is a test, to, remove, commas.
This is a test to, remove, commas.
This is a test to remove, commas.
This is a test to remove commas.
$
#+end_src

더이상 대체할 내용이 없으면 test 명령은 분기하지 않고 스크립트의 나머지 부분을 계속 실행한다.


** Replacing via a Pattern
지금까지 검색 패턴으로 입력 스트림의 텍스트를 대체하는 방법을 살펴봤다. 하지만, 와일드카드 문자를 사용할 경우 어떤 텍스트가 정확히 검색 문자열과 일치하는지 예측하기 어려울 수 있다. 예를 들어, 특정 줄에서 검색 일치한 문자열에 큰따옴표를 추가한다고 가정한다. 만약, 고정된 검색 문자열이면 비교적 간단히 처리한다.

#+begin_src bash
$ echo "The cat sleeps in his hat." | sed 's/cat/"cat"/'
The "cat" sleeps in his hat.
$
#+end_src

하지만, 검색 패턴에 와일드카드 문자 ~.~ 를 사용하면 어떻게 될까?

#+begin_src bash
$ echo "The cat sleeps in his hat." | sed 's/.at/".at"/g'
The ".at" sleeps in his ".at".
$
#+end_src

검색 문자열에 점(~.~) 와일드카드 문자를 사용해서 어떤 글자든 하나 뒤에 "at" 이 오는 경우만 일치하도록 처리했다. 하지만, 대체 문자열은 검색 일치된 단어의 와일드카드를 반영하지 않는다!!


*** Using the ampersand
sed는 이 문제에 대한 해결책이 있다. 앰퍼샌드 기호(~&~) 문자를 사용하는 방법이다. ~&~ 문자는 *대체 명령의 검색 문자열 자체를 의미하는 기호* 이다. 즉, 검색 문자열과 일치한 텍스트 그대로 치환 문자열에서 참조할 수 있다. 이를 통해 검색 문자열과 일치한 단어를 원하는 방식으로 조작할 수 있다.

#+begin_src bash
$ echo "The cat sleeps in his hat." | sed 's/.at/"&"/g'
The "cat" sleeps in his "hat".
$
#+end_src

검색 문자열이 cat 과 일치하면 대체 문자열에 cat 이 나타난다. 검색 문자열이 hat 과 일치하면 대체 문자열에 hat 이 나타난다.


*** Replacing individual words
앰퍼샌드 기호(~&~)는 대체 명령에 지정한 검색 문자열과 일치한 전체 문자열을 그대로 가져온다. 하지만, 때로는 검색 문자열의 일부만 가져올 때도 있다. 이것도 가능하지만 약간 까다롭다.

sed는 *괄호 문자로 검색 문자열의 하위 문자열을 정의* 할 수 있다. 그 다음 대체 문자열에서 특수 문자를 사용해서 하위 문자열을 역참조할 수 있다. 이 특수 문자는 역슬래시(~\~) 문자와 숫자로 구성되며 숫자는 하위 문자열의 발생 순서를 나타낸다. 첫 번째 하위 문자열은 ~\1~, 두 번째 하위 문자열은 ~\2~ 를 순서대로 할당하며 그 이후도 계속된다.

#+begin_quote
"대체 명령에 괄호 문자를 사용할 때는 하위 문자열로 인식시키기 위해 *반드시* 이스케이프 문자(~\~)를 사용해야 한다. 즉, 괄호 문자를 일반 문자로 처리하지 않도록 ~\(~ 와 ~\)~ 형태로 작성해야 한다. 이것은 다른 특수 문자를 이스케이프 처리할 때와 정반대이다."
#+end_quote

다음은 이 기능을 사용하는 sed 스크립트의 예제이다:

#+begin_src bash
$ echo "The System Administrator manual" | sed '
> s/\(System\) Administrator/\1 User/'
The System User manual
$
#+end_src

이 대체 명령은 System 을 *괄호로 감싸서 하위 문자열로 식별* 한다. 그런 다음 대체 문자열에서 ~\1~ 을 사용해서 첫 번째 식별된 하위 문자열을 역참조한다. 이 자체는 흥미롭지 않지만 *와일드카드와 함께 사용할 때는 아주 유용* 하다. 예를 들어, 검색 문자열 전체를 대체하되 그 중 일부 단어는 남겨야할 때 하위 문자열이 와일드카드 문자로 일치될 경우 하위 문자열이 도움된다.

#+begin_src bash
$ echo "That furry cat is pretty" | sed 's/furry \(.at\)/\1/'
That cat is pretty
$
$ echo "That furry hat is pretty" | sed 's/furry \(.at\)/\1/'
That hat is pretty
$
#+end_src

여기선 앰퍼샌드 기호(~&~)를 사용할 수 없다!! 왜냐하면, 검색 일치한 패턴 전체를 대체하기 때문이다. 이럴 때는 하위 문자열이(substring component) 유일한 해결책이다. 검색 문자열의 일부분만 대체 문자열에서 사용할 수 있기 때문이다.

특히 이 기능은 두 개 이상의 문자열에서 특정 텍스트를 삽입할 때 유용하다. 다음은 매우 긴 숫자에 쉼표 문자를 삽입하는 스크립트이다:

#+begin_src bash
$ echo "1234567" | sed '{
> :start
> s/\(.*[0-9]\)\([0-9]\{3\}\)/\1,\2/
> t start
> }'
1,234,567
$
#+end_src

이 스크립트는 검색 문자열을 두 개의 하위 문자열로 나눈다.

#+begin_src 
.*[0-9]
[0-9]{3}
#+end_src

이 패턴은 두 개의 하위 문자열을 찾는다. 첫 번째 하위 문자열은 숫자로 끝나는 임의의 문자들이고 두 번째 하위 문자열은 세 자리의 숫자이다. 이 패턴이 발견되면 대체 문자열은 두 구성 요소 사이에 쉼표 문자를 삽입한다. 하위 문자열은 발생 순서로 식별된다. 또한, 스크립트는 test 명령으로 숫자를 반복 처리하며 모든 쉼표가 삽입될 때까지 계속 실행한다.


** Placing sed Commands in Scripts
지금까지 sed의 다양한 부분을 모두 살펴봤으니 이제 모든 것을 하나로 결합해서 쉘 스크립트로 활용할 때이다.

다음 섹션은 bash 쉘 스크립트에서 sed를 사용할 때 알아둘 몇 가지 기능을 소개한다.


*** Using wrappers
특히 sed 스크립트를 구현하면 스크립트 내용이 길어질 경우 번거롭게 느껴질 수 있다. 매번 전체 스크립트를 입력하는 대신 sed 명령을 쉘 스크립트 래퍼(wrapper)에 넣어서 사용할 수 있다. 이런 래퍼는 sed 스크립트와 쉘 사이에서 중간 역할을 처리한다.

쉘 스크립트는 일반 변수와 매개 변수를 사용할 수 있다. 다음은 쉘 매개 변수를 sed의 입력 스트림으로 사용하는 예제이다:

#+begin_src bash
$ cat reverse.sh
#!/bin/bash
# Shell wrapper for sed editor script.
# to reverse text file lines.
#
sed -n '{ 1!G ; h ; $p }' $1
#
$
#+end_src

reverse.sh 쉘 스크립트는 sed로 입력 스트림의 줄 순서를 뒤집는다. 이 스크립트는 ~$1~ 쉘 매개 변수로 명령줄에 전달된 첫 번째 인자를 가져오며 이 인자는 줄 순서를 뒤집을 파일 이름이다.

#+begin_src bash
$ ./reverse.sh data2.txt
This is the last line.
This is the second data line.
This is the first data line.
This is the header line.
$
#+end_src

이제부터 전체 명령을 입력하지 않고 어떤 파일이든 sed 스크립트로 쉽게 처리할 수 있다.


*** Redirecting sed output
sed는 기본적으로 처리 결과를 표준 출력(STDOUT)으로 출력한다. 쉘 스크립트는 sed의 출력을 표준적인 방법으로 리디렉션할 수 있다. 예를 들어, 달러 기호와 괄호(~$()~)로 sed의 출력을 특정 변수에 저장해서 재사용할 수 있다. 다음은 숫자 계산 결과에 쉼표를 추가하는 sed 스크립트 예제이다:

#+begin_src bash
$ cat fact.sh
#!/bin/bash
# Add commas to number in factorial answer
#
factorial=1
counter=1
number=$1
#
while [ $counter -le $number ]
do
    factorial=$[ $factorial * $counter ]
    counter=$[ $counter + 1 ]
done
#
result=$(echo $factorial | sed '{
:start
s/\(.*[0-9]\)\([0-9]\{3\}\)/\1,\2/
t start
}')
#
echo "The result is $result"
#
$
$ ./fact.sh 20
The result is 2,432,902,008,176,640,000
$
#+end_src

일반적인 팩토리얼을 계산한 후 결과 값을 sed 스크립트 입력으로 전달해서 쉼표를 추가한다. 이렇게 처리한 값은 이후 ~echo~ 문으로 결과를 출력한다.


** Creating sed Utilities
지금까지 소개한 짧은 예제로 알 수 있듯이 sed를 사용하면 다양하고 멋진 데이터 형식 작업을 수행할 수 있다.

이번 섹션은 일반적인 데이터 처리를 수행할 때 유용한 몇 가지 sed 스크립트를 소개한다.


*** Spacing with double lines
파일의 각 줄 사이에 빈 줄을 삽입하는 간단한 sed 스크립트부터 살펴보겠다:

#+begin_src bash
$ sed 'G' data2.txt
This is the header line.

This is the first data line.

This is the second data line.

This is the last line.
$
#+end_src

매우 간단하다!! 이번 트릭의 핵심은 *홀드 공간(hold space)의 기본값* 에 있다. 기억하는가? ~G~ 명령은 홀드 공간의 내용을 현재 패턴 공간에 단순히 덧붙이는 역할을 처리한다. sed를 처음 시작하면 홀드 공간은 빈 줄을 포함한다!! 따라서, 기존 줄에 덧붙이면 줄 뒤에 빈 줄이 추가된다. 하지만, 이 스크립트는 입력 스트림의 마지막 줄도 빈 줄을 추가하면서 결과적으로 파일 끝에 빈 줄 하나를 추가한다.

이를 제거하려면 부정 명령(~!~)과 마지막 줄 기호(~$~)로 스크립트가 입력 스트림의 마지막 줄에선 빈 줄을 추가하지 않도록 처리한다.

#+begin_src bash
$ sed '$!G' data2.txt
This is the header line.

This is the first data line.

This is the second data line.

This is the last line.
$
#+end_src

훨씬 더 보기 좋아졌다. 마지막 줄이 아닐 때만 ~G~ 명령으로 홀드 공간의 내용을 덧붙인다. 마지막 줄에 도달하면 ~G~ 명령은 건너뛴다.


*** Spacing files that may have blanks
두 줄 간격(double spacing) 예제를 한 단계 더 발전시켜 보겠다. 파일에 몇 개의 빈 줄이 포함된 경우 모든 줄을 두 줄 간격으로 만들려면 어떻게 할까? 이전 스크립트 그대로 쓰면 기존의 빈 줄까지 두 번 처리하면서 빈 줄이 너무 많이 생기는 문제가 발생한다.

#+begin_src bash
$ cat data6.txt
This is line one.
This is line two.

This is line three.
This is line four.
$
$ sed '$!G' data6.txt
This is line one.

This is line two.


This is line three.

This is line four.
$
#+end_src

원래 빈 줄까지 빈 줄을 추가했다! 이 문제를 해결하려면 먼저 입력 스트림의 모든 빈 줄을 제거한 다음 ~G~ 명령으로 모든 줄 뒤에 빈 줄을 삽입한다.

기존 빈 줄 모두 삭제하려면 빈 줄과 일치하는 검색 문자열과 ~d~ 명령을 사용한다:

#+begin_src 
/^$/d
#+end_src

이 패턴은 줄 시작을 나타내는 캐럿(~^~)] 앵커와 줄 끝을 의미하는 달러(~$~) 앵커를 사용한다. 이 패턴을 스크립트에 추가하면 원하는 결과를 얻을 수 있다!

#+begin_src bash
$ sed '/^$/d ; $!G' data6.txt
This is line one.

This is line two.

This is line three.

This is line four.
$
#+end_src

이제 완벽하다! 예상대로 잘 작동한다.


*** Numbering lines in a file
이전 장에서 등호 명령(~=~)으로 입력 스트림의 줄 번호를 출력하는 방법을 소개했다.

#+begin_src bash
$ sed '=' data2.txt
1
This is the header line.
2
This is the first data line.
3
This is the second data line.
4
This is the last line.
$
#+end_src

이 방식은 읽기엔 불편할 수 있다. 왜냐하면, 줄 번호가 줄 위에 별도 라인으로 표시되기 때문이다. 좀 더 나은 해결책은 줄 번호를 같은 줄에 함께 표시하는 것이다.

~N~ 명령으로 줄을 결합하는 방법을 살펴봤으니 이 정보를 sed 스크립트에 활용하는 것도 어렵진 않을 것이다. 하지만, 여기서 핵심은 *이 두 명령은 같은 스크립트에서 함께 사용할 수 없다!!* 는 점이다. 등호(~=~) 명령으로 출력을 얻은 다음 출력 결과를 다시 sed로 파이프한 후, ~N~ 명령으로 두 줄을 결합한다. 그리고 대체 명령에서 줄바꿈 문자(~\n~)를 공백이나 탭 문자로 바꾸는 작업도 필요하다.

최종 해결책은 다음과 같다:

#+begin_src bash
$ sed '=' data2.txt | sed 'N; s/\n/ /'
1 This is the header line.
2 This is the first data line.
3 This is the second data line.
4 This is the last line.
$
#+end_src

이제 훨씬 더 보기 좋아졌다. 오류 메시지의 줄 번호를 확인하는 프로그램으로 작업할 경우 이런 작은 유틸리티는 꽤 유용할 것이다.

물론 줄 번호를 추가하는 쉘 프로그램도 존재한다. 하지만, 그런 프로그램은 원하지 않는 공백까지 추가할 경우가 있다.

#+begin_src bash
$ nl data2.txt
1 This is the header line.
2 This is the first data line.
3 This is the second data line.
4 This is the last line.
$
$ cat -n data2.txt
1   This is the header line.
2   This is the first data line.
3   This is the second data line.
4   This is the last line.
$
#+end_src

sed 스크립트는 불필요한 공백없이 출력 결과를 깔끔하게 처리한다.


*** Printing last lines
지금까지 ~p~ 명령으로 입력 스트림의 모든 줄 또는 특정 패턴과 일치한 줄만 출력하는 방법을 살펴봤다. 그렇다면, 로그 파일처럼 매우 긴 파일에서 마지막 몇 줄만 작업할 때는 어떻게 할까?

달러 기호(~$~)는 입력 스트림 마지막 줄을 의미하므로 마지막 줄만 출력하는 작업은 간단하다!

#+begin_src bash
$ sed -n '$p' data2.txt
This is the last line.
$
#+end_src

달러 기호로 입력 스트림 끝에서 이전 몇 줄만 표시하려면 어떻게 할까? 해답은 *롤링 윈도우* (rolling window)를 만드는 것이다. 롤링 윈도우는 패턴 공간에 블록을 결합해서 살펴보는 일반적인 처리 방법이다. ~N~ 명령으로 다음 줄을 패턴 공간의 기존 텍스트에 덧붙일 수 있다. 패턴 공간에 10줄의 블록이 만들어지면 달러 기호로 입력 스트림 끝을 확인할 수 있다. 만약, 끝이 아니라면 계속해서 줄을 패턴 공간에 추가하면서 기존 줄을 제거한다.(패턴 공간의 첫 번째 줄만 삭제하는 ~D~ 명령을 기억하라!)

~N~ 과 ~D~ 명령을 반복하면 패턴 공간의 블록에 새로운 줄을 추가하고 오래된 줄을 제거할 수 있다. 이런 반복 작업엔 branch 명령이 적절하다. 반복 작업을 종료하려면 마지막 줄을 식별한 후 ~q~ 명령으로 종료한다.

다음은 롤링 윈도우를 만드는 최종 sed 스크립트이다:

#+begin_src bash
$ cat data7.txt
This is line 1.
This is line 2.
This is line 3.
This is line 4.
This is line 5.
This is line 6.
This is line 7.
This is line 8.
This is line 9.
This is line 10.
This is line 11.
This is line 12.
This is line 13.
This is line 14.
This is line 15.
$
$ sed '{
> :start
> $q ; N ; 11,$D
> b start
> }' data7.txt
This is line 6.
This is line 7.
This is line 8.
This is line 9.
This is line 10.
This is line 11.
This is line 12.
This is line 13.
This is line 14.
This is line 15.
$
#+end_src

위의 스크립트는 

+ 현재 줄이 입력 스트림 마지막 줄인지 확인한다. 마지막 줄이면 quit 명령으로 루프를 종료한다.
+ ~N~ 명령은 다음 줄을 현재 패턴 공간의 기존 줄에 덧붙인다. 
+ ~11,$D~ 명령은 현재 줄이 10번째 줄 이상일 경우 패턴 공간에서 첫 번째 줄만 삭제한다. 

이로 인해 패턴 공간에 롤링 윈도우 효과가 발생한다. 결과적으로 이 sed 스크립트는 data7.txt 파일의 마지막 10줄만 출력한다.


*** Deleting lines
sed의 또 다른 유용한 기능은 입력 스트림에서 원치않는 빈 줄만 제거하는 것이다. 입력 스트림의 모든 빈 줄을 제거하는 작업은 간단하지만 선택적으로 특정 빈 줄만 제거하려면 약간의 기지가 필요하다.

이번 섹션은 원치않는 빈 줄만 제거할 때 도움되는 sed 스크립트 몇 가지를 소개한다.


**** Deleting consecutive blank lines
데이터 파일에 불필요한 빈 줄이 생기는 것은 아주 성가신 일이다. 종종 데이터 파일에 빈 줄이 포함되지만 때로는 줄이 누락되면서 너무 많은 빈 줄이 생긴다. (앞서 살펴본 두 줄 예제처럼…)

연속된 빈 줄을 제거하기 가장 쉬운 방법은 주소 범위로 제한하는 것이다. 이전 장에서 주소 범위를 사용하는 방법과 주소 범위에 패턴을 포함시키는 방법을 배웠다. sed는 주소 범위의 모든 줄에 명령을 실행한다.

연속된 빈 줄을 제거하는 작업에서 핵심은 *비어있지 않은 줄과 빈 줄을 포함한 주소 범위* 를 만드는 것이다. sed는 이런 범위를 만나면 해당 줄을 삭제하지 않는다. 하지만, 이 범위에 해당하지 않는 줄(연속된 두 개 이상의 빈 줄)은 삭제한다.

다음은 이를 수행하는 스크립트이다:

#+begin_src 
/./,/^$/!d
#+end_src

여기서 주소 범위는 ~/./~ 에서 ~/^$/~ 까지다. 시작 주소는 하나 이상의 문자를 포함한 모든 줄과 일치한다. 끝 주소는 빈 줄과 일치한다. 따라서, 이 범위에 포함된 줄은 삭제하지 않는다.

다음은 이 스크립트의 실행 예제이다:

#+begin_src bash
$ cat data8.txt
This is line one.


This is line two.

This is line three.


This is line four.
$
$ sed '/./,/^$/!d' data8.txt
This is line one.

This is line two.

This is line three.

This is line four.
$
#+end_src

줄 사이에 얼마나 많은 빈 줄이 있든지 상관없이 출력 결과는 각 줄 사이에 오직 하나의 빈 줄만 출력한다.


**** Deleting leading blank lines
만약, 파일 시작 부분에 여러 개의 빈 줄이 포함될 경우도 처리하기 성가신 문제이다. 데이터베이스에서 데이터를 가져올 때 이런 빈 줄은 널(null) 항목을 생성하면서 계산을 방해할 경우도 많다.

입력 스트림 맨 앞의 빈 줄만 제거하는 작업은 그리 어렵지 않다. 다음은 그 기능을 수행하는 스크립트이다:

#+begin_src 
/./,$!d
#+end_src

이 스크립트는 주소 범위로 어떤 줄을 삭제할지 결정한다. 주소 범위는 문자를 포함한 첫 번째 줄부터 입력 스트림 끝까지이다. 이 범위에 포함된 줄은 출력에서 삭제하지 않는다! 즉, 문자를 포함한 첫 번째 줄 이전의 모든 줄(빈 줄)은 삭제된다는 뜻이다.

다음은 스크립트의 실행 예제이다:

#+begin_src bash
$ cat data9.txt


This is line one.

This is line two.
$
$ sed '/./,$!d' data9.txt
This is line one.

This is line two.
$
#+end_src

파일은 줄 앞에 두 개의 빈 줄이 포함되어 있다. 스크립트는 앞 부분의 두 줄을 성공적으로 제거하면서 데이터 중간의 빈 줄은 그대로 유지한다.


**** Deleting trailing blank lines
안타깝지만 끝 부분의 빈 줄만 삭제하는 작업은 앞 부분의 빈 줄만 삭제하는 것처럼 간단하지 않다.

입력 스트림 끝을 출력할 때 같이 스트림 끝의 빈 줄만 삭제하려면 약간의 기지와 반복 작업이 필요하다. 설명에 앞서 스크립트가 어떻게 생겼는지 살펴보겠다:

#+begin_src bash
sed '{
:start
/^\n*$/{$d; N; b start }
}'
#+end_src

처음엔 스크립트가 이상할 수도 있겠다. 일반적인 스크립트와 다르게 *중괄호 안에 또 다른 중괄호가 있다!* 는 점에 주목하자. 이렇게 처리하면 전체 명령 스크립트 내에서 명령을 다시 그룹화할 수 있다. 이 명령 그룹은 지정한 주소 패턴에 적용된다.

검색 문자열은 줄바꿈 문자만 포함된 줄(즉, 빈 줄)과 일치한다. 이런 줄이 발견되면

- 마지막 줄일 경우 delete 명령으로 삭제한다. 
- 마지막 줄이 아닐 경우 ~N~ 명령으로 다음 줄을 패턴 공간에 덧붙이고 branch 명령으로 루프를 다시 시작한다.

다음은 이 스크립트의 실행 예제이다:

#+begin_src bash
$ cat data10.txt
This is the first line.
This is the second line.



$ sed '{
> :start
> /^\n*$/{$d ; N ; b start }
> }' data10.txt
This is the first line.
This is the second line.
$
#+end_src

스크립트는 파일 끝부분의 빈 줄만 성공적으로 제거했다.


*** Removing HTML tags
요즘 웹사이트에서 텍스트를 다운로드하거나 애플리케이션 데이터로 사용하는 일이 흔하다. 하지만, 웹사이트에서 다운로드할 때 데이터를 꾸미기 위한 HTML 태그도 따라올 경우가 있다. 순수 데이터만 볼 때는 문제될 수 있다. 표준 HTML 페이지는 정보를 표시하기 위한 여러 종류의 HTML 태그가 포함된다.

다음은 HTML 파일의 예제이다:

#+begin_src bash
$ cat data11.txt
<html>
<head>
<title>This is the page title</title>
</head>
<body>
<p>
This is the <b>first</b> line in the Web page.
This should provide some <i>useful</i>
information to use in our sed script.
</body>
</html>
$
#+end_src

HTML 태그는 꺾쇠 괄호(~< ... >~)로 식별한다. 대부분의 HTML 태그는 쌍으로 구성된다. 하나의 태그는 서식을 시작하고(예: ~<b>~ 는 굵게 표시) 다른 태그는 서식을 종료한다. (예: ~</b>~ 는 굵게 표시 해제)

하지만, 이런 HTML 태그를 제거할 때 주의하지 않으면 문제가 발생할 수 있다. 처음엔 단순히 ~<~ 로 시작하고 ~>~ 로 끝나는 문자열을 찾아서 제거한다고 생각할 수 있다. 예를 들어, 꺾쇠 괄호 사이의 문자열 모두 제거하는 방식이다:

#+begin_src 
s/<.*>//g
#+end_src

안타깝지만 이 명령은 다음과 같은 예상치 못한 부작용을 초래한다.

#+begin_src bash
$ sed 's/<.*>//g' data11.txt






This is the line in the Web page.
This should provide some
information to use in our sed script.

$
#+end_src

제목뿐만 아니라 굵게 표시되거나 이탤릭체로 표시한 텍스트까지 모두 사라진다는 것을 알 수 있다. sed는 스크립트를 문자그대로 해석해서 꺾쇠 괄호(~<~, ~>~) 사이의 모든 텍스트를 제거했다. 여기엔 다른 꺾쇠 괄호도 포함된다!!

텍스트가 HTML 태그로 둘러싸여 있을 때(예: ~<b>first</b>~) sed 스크립트는 태그뿐만 아니라 내부 텍스트도 전부 제거했다. 이 문제를 해결하려면 sed가 태그 사이의 중첩된 ~>~ 기호를 무시하도록 처리해야 한다. 이를 위해 ~>~ 기호를 제외하는 문자 클래스를 만들 수 있다. 이렇게 처리하면 스크립트는 다음과 같이 변경된다:

#+begin_src 
s/<[^ >]*>//g
#+end_src

이제 스크립트는 정상 작동하며 웹 페이지의 HTML 코드는 필요한 데이터만 표시한다.

#+begin_src 
$ sed 's/<[^>]*>//g' data11.txt

This is the page title


This is the first line in the Web page.
This should provide some useful
information to use in our sed script.


$
#+end_src

훨씬 더 나아졌다. 좀 더 깔끔하게 정리하려면 성가신 빈 줄을 제거하는 delete 명령을 추가한다:

#+begin_src bash
$ sed 's/<[^>]*>//g ; /^$/d' data11.txt
This is the page title
This is the first line in the Web page.
This should provide some useful
information to use in our sed script.
$
#+end_src

이제 훨씬 더 간결해졌다. 정확히 표시할 데이터만 남고 불필요한 요소는 모두 제거됐다.



** Summary
sed는 여러 줄에 나눠진 검색 문자열을 처리할 수 있는 고급 기능을 제공한다. 이번 장에서 next 명령으로 입력 스트림의 다음 줄을 가져와서 패턴 공간에 배치하는 방법을 살펴봤다. 패턴 공간에 들어온 후에는 여러 줄에 걸친 문자열을 처리하는 멀티라인 명령을 실행할 수 있다.

멀티라인 delete 명령은 패턴 공간에 두 줄 이상 있을 때 첫 번째 줄만 제거한다. 이것은 입력 스트림을 여러 줄로 반복 처리할 수 있는 유용한 방법이다. 마찬가지로 멀티라인 print 명령은 패턴 공간에 여러 줄이 있을 때 첫 번째 줄만 출력한다. 이런 멀티라인 명령을 조합하면 입력 스트림을 반복하면서 멀티라인 시스템을 구축할 수 있다.

다음으로 hold 공간을 살펴봤다. hold 공간은 잠시동안 따로 저장하거나 다른 줄을 처리할 수 있게 해준다. hold 공간의 내용은 언제든 불러와서 패턴 공간의 텍스트를 대체하거나 덧붙일 수 있다. hold 공간을 활용하면 입력 스트림을 정렬하거나 줄 순서를 뒤집는 작업도 가능하다.

다음은 다양한 sed의 흐름 제어 명령을 살펴봤다. branch 명령은 일반적인 실행 흐름을 변경해서 루프를 만들거나 특정 조건에서 명령을 건너뛸 수 있다. test 명령은 sed 스크립트에서 if-then 조건문처럼 작동한다. 이 명령은 이전 대체 명령이 성공했을 때만 분기한다.

마지막은 sed 스크립트를 쉘 스크립트에서 사용하는 방법을 다루었다. 매우 큰 sed 스크립트는 쉘 래퍼(shell wrapper)에 넣는 것이 일반적인 처리 방법이다. 쉘 매개 변수를 sed 스크립트에 전달해서 쉘 매개 변수를 사용할 수 있다. 이렇게 처리하면 sed 스크립트를 명령줄이나 다른 쉘 스크립트에서 재활용할 수 있는 간편한 처리 방법이다.



