* Perface
사람들이 쉘 스크립트를 사용하는 가장 일반적인 기능 중 하나는 *텍스트 파일을 다루는 것* 이다. 로그 파일을 검사하거나 설정 파일을 읽거나 데이터를 처리하는 등 쉘 스크립트는 텍스트 파일에 포함된 모든 유형의 데이터를 조작하는 지루한 작업을 "자동화" 하는 데 도움될 수 있다. 

하지만, 쉘 스크립트 명령만으로 파일 내용을 조작하려면 다소 부족할 수 있다. 쉘 스크립트로 어떤 형태로든 데이터를 조작하려면 Linux에서 사용할 수 있는 ~sed~ 도구에 하루빨리 익숙해지는 것이 좋다. 이 도구는 데이터 처리 작업을 크게 단순화할 수 있다.


** Getting to know the sed editor
<<getting-to-know-the-sed-editor>>
sed 편집기는 대화형 편집기와 다르게 *스트림 편집기* (*S* tream *ED* itor)라고 불린다. vim 같은 *대화형 텍스트 편집기* 는 키보드나 명령으로 텍스트를 삽입하거나 삭제 또는 교체하는 작업을 사용자와 대화형(interactive)으로 수행한다. 

*스트림 편집기* 는 데이터를 처리할 때 사용자가 제공한 *규칙(또는 집합)을 기반으로 데이터 스트림을 편집* 한다. sed 편집기는 명령줄에서 직접 입력해서 실행하거나 명령 파일에 저장한 *명령으로 데이터 스트림을 조작* 할 수 있다. 

일반적으로 sed 편집기는 다음과 같이 작업을 처리한다:

+ 입력(STDIN)에서 한 줄의 데이터를 읽는다. 
+ 읽은 데이터를 제공한 편집기 명령의 패턴과 일치 여부를 검사한다. 
+ 패턴과 일치하면 제공한 편집기 명령으로 스트림의 데이터를 변경한다. 
+ 변경한 데이터를 표준 출력(STDOUT)으로 출력한다.

스트림 편집기는 입력에서 읽어 온 한 줄의 데이터에 명령 모두를 적용한 후 다음 줄의 데이터를 읽고 이런 과정을 반복한다. 데이터 스트림의 모든 데이터 줄을 처리하면 종료한다.

이렇듯 *명령은 줄 단위로 순차 적용* 되므로 sed 편집기는 데이터 스트림을 통과할 때마다 작업을 수행한다. 따라서, sed 편집기는 대화형 편집기 보다 데이터를 빠르게 편집할 수 있다. 

sed 프로그램을 사용하는 형식은 다음과 같다:

#+begin_src bash
sed options script file
#+end_src


*options 매개 변수* 는 sed의 *기본 동작을 사용자 정의* 할 수 있으며 다음과 같은 옵션을 사용한다.

| 옵션        | 설명                                                                  |
|-------------+-----------------------------------------------------------------------|
| ~-e script~ | 입력에 처리할 명령을 지정한 명령으로 실행함                           |
| ~-f file~   | 입력에 처리할 명령을 명령 파일에 저장한 명령으로 실행함               |
| ~-n~        | 각 명령에 대한 출력 결과를 생성하지 않고 별도의 `print` 명령을 기다림 |

*script 매개 변수* 는 스트림 데이터에 적용할 *명령을 지정* 한다. 하나 이상의 명령이 필요할 경우 명령줄에 ~-e~ 옵션을 여러번 사용하거나 ~;~ (세미콜론)문자로 명령을 분리하거나 명령이 저장된 파일을 ~-f~ 옵션으로 지정해서 실행할 수 있다. 데이터를 조작할 수 있는 다양한 *명령* (command)이 제공된다.

다음 섹션은 sed 편집기에서 사용하는 *기본 명령* 몇 가지를 살펴보고 이후에 *고급 명령* 을 살펴본다.



** Defining an editor command in the command line
<<defining-an-editor-command-in-the-command-line>>
기본적으로 sed 편집기는 지정한 명령을 *STDIN 즉, 표준 입력 스트림에 적용* 한다. 따라서, 입력 데이터를 sed 편집기로 파이프(pipe)해서 필터(filter)로 사용할 수 있다. 

다음은 이 기능을 보여주는 간단한 예이다:

#+begin_src bash
$ echo "This is a test" | sed 's/test/big test/'
This is a big test
$
#+end_src

이 예제는 sed 편집기의 ~s~ (substitute) 대체 명령을 사용한다. ~s~ 명령은 슬래시 문자 사이에 지정한 첫 번째 텍스트 패턴(*검색 문자열*)을 두 번째 텍스트 패턴(*대체 문자열*)으로 대체한다. 예제의 경우 `test` 를 `big test` 로 대체한다.

예제는 실행과 동시에 화면에 결과를 출력한다. 이런 것이 바로 sed 편집기를 사용할 때의 *강력함* 이다. 일부 대화형 편집기를 시작할 시간에 데이터를 여러 번 편집할 수 있다. 예제는 한 줄의 데이터만 편집했다. 다음과 같이 여러 줄로 구성된 데이터 파일을 편집해도 빠르게 결과를 얻을 수 있다.

#+begin_src bash
$ cat data1.txt
The quick brown fox jumps over the lazy dog.
The quick brown fox jumps over the lazy dog.
The quick brown fox jumps over the lazy dog.
The quick brown fox jumps over the lazy dog.
$
$ sed 's/dog/cat/' data1.txt
The quick brown fox jumps over the lazy cat.
The quick brown fox jumps over the lazy cat.
The quick brown fox jumps over the lazy cat.
The quick brown fox jumps over the lazy cat.
$
#+end_src

sed는 실행과 동시에 데이터를 *즉시 반환* 한다!! 데이터 줄을 처리하면서 처리 결과도 함께 출력한다. 따라서, sed는 파일 전체를 처리하기 전에 처리 결과를 볼 수 있다.

여기서 중요한 점은 *sed 편집기는 원본 파일의 데이터를 수정하지 않는다!!* 는 것이다. 

명령으로 수정한 텍스트는 표준 출력(*STDOUT*)으로만 전송된다!! 원본 파일을 확인하면 원본 데이터가 그대로인 것을 알 수 있다.

#+begin_src bash
$ cat data1.txt
The quick brown fox jumps over the lazy dog.
The quick brown fox jumps over the lazy dog.
The quick brown fox jumps over the lazy dog.
The quick brown fox jumps over the lazy dog.
$
#+end_src



** Using multiple editor commands in the command line
<<using-multiple-editor-commands-in-the-command-line>>
명령줄(command line)에서 하나 이상의 sed 명령을 실행하려면 ~-e~ 옵션을 여러 번 사용하거나 다음과 같이 ~;~ 세미콜론 문자로 각 명령을 구분한다.

#+begin_src bash
$ sed -e 's/brown/green/; s/dog/cat/' data1.txt
The quick green fox jumps over the lazy cat.
The quick green fox jumps over the lazy cat.
The quick green fox jumps over the lazy cat.
The quick green fox jumps over the lazy cat.
$
#+end_src

세미콜론 문자로 구분된 명령은 파일의 *모든 줄에 적용* 된다. 이 경우 명령은 *세미콜론 문자로 구분* 하며 이때 명령과 세미콜론 문자 사이에 공백이 없어야 한다.

또한, 명령을 구분할 때 세미콜론 문자 대신 bash 쉘의 *보조 프롬프트* 를 사용할 수 있다. 쉘에서 sed 스크립트(sed 편집기 명령)를 직접 입력할 때 작은따옴표 문자를 입력하면 닫는 따옴표를 입력할 때까지 계속 입력할 수 있다.

#+begin_src bash
$ sed -e '
> s/brown/green/
> s/fox/elephant/
> s/dog/cat/' data1.txt
The quick green elephant jumps over the lazy cat.
The quick green elephant jumps over the lazy cat.
The quick green elephant jumps over the lazy cat.
The quick green elephant jumps over the lazy cat.
$
#+end_src

"*닫는 따옴표가 포함된 줄에서 명령을 끝내야 한다!*" 는 점에 주의한다. 쉘은 닫는 따옴표를 감지하면 명령을 실행한다. 명령이 실행되면 sed는 지정한 명령을 지정한 파일의 *모든 줄에 적용* 한다.



** Reading editor commands from a file
<<reading-editor-commands-from-a-file>>
처리할 sed 명령이 많을 경우 별도의 *명령 파일* 에 저장하는 것이 보다 효율적이다. ~sed -f~ 옵션으로 명령 파일을 지정해서 실행한다.

#+begin_src bash
$ cat script1.sed
s/brown/green/
s/fox/elephant/
s/dog/cat/
$
$ sed -f script1.sed data1.txt
The quick green elephant jumps over the lazy cat.
The quick green elephant jumps over the lazy cat.
The quick green elephant jumps over the lazy cat.
The quick green elephant jumps over the lazy cat.
$
#+end_src

이 경우 각 명령 끝에 세미콜론 문자는 넣지 않아도 된다. 왜냐하면 sed는 "*각 줄이 개별 명령을 포함한다!*" 는 것을 잘 알고 있다. 명령줄에서 직접 입력할 때와 마찬가지로 sed는 지정한 명령 파일에서 명령을 읽고 대상 파일의 모든 줄에 적용한다.

#+begin_quote
"sed 스크립트와 쉘 스크립트를 혼동할 수 있다. 이런 혼동을 피하려면 sed 스크립트에 ~.sed~ 확장자를 사용하는 것이 좋다."
#+end_quote

이제부터 데이터를 편집할 때 유용한 sed의 *기본 명령* 을 살펴보겠다.



* Commanding at the sed Editor Basics
<<commanding-at-the-sed-editor-basics>>
sed를 성공적으로 사용하기 위한 핵심은 *명령과 사용 형식을 잘 아는 것* 이다. 이것은 텍스트 편집 작업을 처리할 때 도움된다. 

이번 섹션은 sed 편집기를 (기본적으로) 사용하거나 스크립트에서 사용할 수 있는 몇 가지 기본 명령과 기능에 대해 설명한다.



** Introducing more substitution options
<<introducing-more-substitution-options>>
이미 ~s~ (대체)명령으로 한 줄의 텍스트를 새로운 텍스트로 대체하는 방법을 살펴봤다. 하지만, 대체 명령은 작업을 다양하게 처리할 수 있는 추가 옵션(플래그)이 존재한다.


*** Substituting flags
<<substituting-flags>>
대체 명령으로 검색 일치한 패턴을 대체할 때 한 가지 *주의할 점* 이 있다. 다음 예제로 어떤 일이 일어나는지 살펴보자.

#+begin_src bash
$ cat data4.txt
This is a test of the test script.
This is the second test of the test script.
$
$ sed 's/test/trial/' data4.txt
This is a trial of the test script.
This is the second trial of the test script.
$
#+end_src

대체 명령은 여러 줄에 포함된 검색 문자열을 잘 대체했지만 *기본적으로 줄 내의 첫 번째 항목만 대체* 한다!! 한 줄에 포함된 여러 항목을 대체하려면 *플래그* (flags)를 사용해야 한다. 

대체 명령의 플래그는 대체 문자열 뒤에 설정한다.

#+begin_src bash
s/pattern/replacement/flags
#+end_src

다음과 같이 네 가지 대체 명령 플래그를 사용할 수 있다:

| 플래그   | 설명                                              |
|----------+---------------------------------------------------|
| ~숫자~   | 대체 문자열로 대체할 검색 문자열의 검색 위치 지정 |
| ~p~      | 명령으로 대체한 경우 줄의 내용 출력               |
| ~g~      | 한 줄 내의 일치 항목 모두 대체                    |
| ~w file~ | 대체 결과를 파일에 저장                           |

첫 번째 *숫자 플래그* 는 검색 문자열의 검색 위치(순서)를 지정한다.

#+begin_src bash
$ sed 's/test/trial/2' data4.txt
This is a test of the trial script.
This is the second test of the trial script.
$
#+end_src

숫자 플래그 ~2~ 는 한 줄에 *두 번째로 나타난 검색 패턴을 대체* 한다.(~test → trial~)

*g* (global) 플래그는 한 줄에 나타난 *모든 검색 패턴을 대체* 한다.

#+begin_src bash
$ sed 's/test/trial/g' data4.txt
This is a trial of the trial script.
This is the second trial of the trial script.
$
#+end_src

*p* (print) 플래그는 대체 문자열로 *대체한 줄만 출력* 한다. 대부분의 경우 ~-n~ (no print - next 명령) sed 옵션과 함께 사용한다.

#+begin_quote
"문서 내의 일부 텍스트만 추출하는 것을 필터링이라 부른다."
#+end_quote

#+begin_src bash
$ cat data5.txt
This is a test line.
This is a different line.
$
$ sed -n 's/test/trial/p' data5.txt
This is a trial line.
$
#+end_src

~-n~ 옵션은 sed 편집기의 *기본 출력 기능을 억제* 하고 ~p~ 플래그는 *대체한 줄만 출력* 한다. 따라서, 이 둘을 함께 사용하면 *대체 명령으로 대체한 줄만 (필터링해서) 출력* 할 수 있다.

*w* (write) 플래그는 동일한 출력 결과를 생성하지만 플래그에 *지정한 파일에 출력 결과를 저장* 한다.

#+begin_src bash
$ sed 's/test/trial/w test.txt' data5.txt
This is a trial line.
This is a different line.
$
$ cat test.txt
This is a trial line.
$
#+end_src

기본적으로 sed 편집기의 출력은 표준 출력(STDOUT)으로 보내지만 ~w~ 플래그는 대체 문자열로 대체한 줄만 지정한 파일에 저장한다.


*** Replacing characters
<<replacing-characters>>
때로는 검색 문자열에 사용하기 까다로운 문자를 만날 수 있다. 가장 흔한 예로 슬래시(~/~) 문자가 있다. 따라서, 파일 경로명 대체 작업은 번거로울 수 있다. 예를 들어, ~/etc/passwd~ 파일에서 bash 쉘을 C 쉘로 대체하려면 다음과 같이 처리한다:

#+begin_src bash
$ sed 's/\/bin\/bash/\/bin\/csh/' /etc/passwd
#+end_src

이 경우 슬래시(~/~) 문자는 대체 명령 *구분자* 로 사용하기 때문에 검색 문자열에 슬래시 문자가 포함될 경우 *백슬래시(~\~) 문자로 이스케이프 처리* 해야 한다. 하지만, 이 작업은 종종 혼란과 실수를 초래한다.

이런 문제를 해결하기 위해 sed는 대체 명령의 *구분자를 다른 문자로 선택할 수 있도록 허용* 한다.

#+begin_src bash
$ sed 's!/bin/bash!/bin/csh!' /etc/passwd
#+end_src

예제는 느낌표 문자를 *구분자로 사용* 해서 경로명을 보다 읽기 쉽고 이해하기 쉽게 만든다.


** Using addresses
<<using-addresses>>
기본적으로 sed 명령은 *모든 줄에 적용* 된다. 따라서, 특정 줄이나 줄 그룹에 명령을 *한정적으로 적용* 하려면 *주소 지정으로 적용 범위를 한정* 해야 한다.

sed에서 사용하는 *주소* (address)는 다음과 같이 두 가지 형식이 있다:

- 단일 줄 번호 또는 줄 범위 주소
- (특정 줄만 필터링하는) 텍스트 패턴 또는 패턴 범위

위의 두 가지 주소 형식은 다음과 같이 사용한다.

#+begin_src 
[address]command
#+end_src

또한, 주소(address)에 *둘 이상의 명령을 중괄호 문자로 그룹화* 해서 실행할 수 있다.

#+begin_src 
address {
    command1
    command2
    command3
}
#+end_src

sed는 명령(들)을 주소와 *일치한 줄에만 적용* 한다. 

다음 섹션에서 두 가지 주소 지정에 대한 사용법을 설명한다.


*** Addressing the numeric line
<<addressing-the-numeric-line>>
줄 주소 지정을 사용할 때는 *줄 위치(라인 번호)를 기준* 으로 처리한다. sed는 텍스트 스트림의 첫 번째 줄을 1번 줄로 지정하고 이후 각 줄에 순차적으로 번호를 매긴다.[fn:1]

[fn:1]반드시 단일 파일만 처리하는 것은 아니다. 여러 파일을 입력 데이터로 사용할 수 있다. 이경우 줄 번호는 누적된다.

또한, 줄 주소는 *단일 줄* 이거나 시작 줄과 끝 줄을 쉼표 문자로 구분한 *줄 범위 주소* 이다.

다음은 sed 명령을 단일 줄에 적용한다.

#+begin_src bash
$ sed '2s/dog/cat/' data1.txt
The quick brown fox jumps over the lazy dog
The quick brown fox jumps over the lazy cat
The quick brown fox jumps over the lazy dog
The quick brown fox jumps over the lazy dog
$
#+end_src

sed는 지정한 주소인 두 번째 줄의 텍스트만 수정한다. 

다음은 줄 범위에 적용한다.

#+begin_src bash
$ sed '2,3s/dog/cat/' data1.txt
The quick brown fox jumps over the lazy dog
The quick brown fox jumps over the lazy cat
The quick brown fox jumps over the lazy cat
The quick brown fox jumps over the lazy dog
$
#+end_src

특정 줄부터 *마지막 줄* 까지 명령을 적용할 때 주소 기호 문자(~$~)를 사용할 수 있다.

#+begin_src bash
$ sed '2,$s/dog/cat/' data1.txt
The quick brown fox jumps over the lazy dog
The quick brown fox jumps over the lazy cat
The quick brown fox jumps over the lazy cat
The quick brown fox jumps over the lazy cat
$
#+end_src

대부분의 경우 파일에 몇 줄이 포함된지 알 수 없으므로 달러 주소 기호는 유용하다!!


*** Using text pattern filters
<<using-text-pattern-filters>>
명령을 적용할 대상인 줄을 지정하는 또 다른 방법은 조금 복잡하다.

sed는 명령을 적용할 줄만 *필터링할 때 검색 문자열을 사용* 한다. 사용 형식은 다음과 같다:

#+begin_src 
/pattern/command
#+end_src

*검색 문자열(pattern)은 슬래시(~/~) 문자로 감싸야 한다.* sed는 지정한 *검색 문자열을 포함한 줄에만 명령(command)을 적용* 한다. 

예를 들어, Samantha 사용자의 로그인 쉘을 변경하려면 다음과 같이 사용한다:

#+begin_src bash
$ grep Samantha /etc/passwd
Samantha:x:502:502::/home/Samantha:/bin/bash
$
$ sed '/Samantha/s/bash/csh/' /etc/passwd
root:x:0:0:root:/root:/bin/bash
bin:x:1:1:bin:/bin:/sbin/nologin
[...]
Christine:x:501:501:Christine B:/home/Christine:/bin/bash
Samantha:x:502:502::/home/Samantha:/bin/csh
Timothy:x:503:503::/home/Timothy:/bin/bash
$
#+end_src

위의 명령은 검색 문자열(~Samantha~)이 포함된 줄에만 명령(~s/bash/csh/~)을 적용한다. 

지금처럼 고정 검색 문자열로 사용하는 것은 특정 값을 직접 필터링할 때는 유용하지만 활용성은 어느 정도 제한이 있다. sed는 검색 문자열에 *정규 표현식* (regular expression)을 사용해서 훨씬 더 복잡한 검색 문자열을 처리할 수 있다. 정규 표현식을 사용하면 다양한 문자열을 일치시킬 수 있는 *고급 텍스트 패턴 매칭을 처리* 할 수 있다.

고급 텍스트 패턴 매칭은 와일드카드 문자, 특수 문자, 고정 텍스트를 조합해서 거의 모든 텍스트에 맞는 검색 패턴을 생성할 수 있다. 하지만, 정규 표현식은 쉘 스크립트 프로그래밍에서 가장 어려운 부분에 속하며 이후에 보다 자세히 다룬다.


*** Grouping commands
<<grouping-commands>>
단일 줄(주소)에 둘 이상의 명령을 수행할 경우 *중괄호 문자로 명령을 그룹화* 한다. 

sed는 다음과 같이 지정한 줄에 나열한 명령을 모두 적용한다.

#+begin_src bash
$ sed '2{
> s/fox/elephant/
> s/dog/cat
> }' data1.txt
The quick brown fox jumps over the lazy dog.
The quick brown elephant jumps over the lazy cat.
The quick brown fox jumps over the lazy dog.
The quick brown fox jumps over the lazy dog.
$
#+end_src

두 가지 명령 모두 2번 라인에만 적용한다. 그룹 명령을 주소 범위로 지정할 수 있다.

#+begin_src bash
$ sed '3,${
> s/brown/green/
> s/lazy/active/
> }' data1.txt
The quick brown fox jumps over the lazy dog.
The quick brown fox jumps over the lazy dog.
The quick green fox jumps over the active dog.
The quick green fox jumps over the active dog.
$
#+end_src

sed는 주소 범위의 줄에 그룹 명령을 적용한다.


** Deleting lines
<<deleting-lines>>
sed 편집기에서 대체 명령이 사용할 수 있는 유일한 명령은 아니다. 텍스트 스트림의 특정 줄만 삭제하려면 *delete* (d)명령을 사용할 수 있다. 삭제 명령 즉, ~d~ 는 예상대로 동작한다. 지정한 주소와 일치한 텍스트 줄을 삭제한다. 

하지만, 삭제 명령은 *매우 주의해서 사용* 해야 한다!! 별도로 주소를 지정하지 않으면 *스트림의 모든 줄을 삭제* 한다.

#+begin_src bash
$ cat data1.txt
The quick brown fox jumps over the lazy dog
The quick brown fox jumps over the lazy dog
The quick brown fox jumps over the lazy dog
The quick brown fox jumps over the lazy dog
$
$ sed 'd' data1.txt
$
#+end_src

따라서, 삭제 명령은 주소를 지정해서 사용할 때 가장 유용하다. 이를 통해 데이터 스트림의 *특정 줄만 삭제* 할 수 있다.

#+begin_src bash
$ cat data6.txt
This is line number 1.
This is line number 2.
This is line number 3.
This is line number 4.
$
$ sed '3d' data6.txt
This is line number 1.
This is line number 2.
This is line number 4.
$
#+end_src

또는 줄 범위를 삭제할 수 있다.

#+begin_src bash
$ sed '2,3d' data6.txt
This is line number 1.
This is line number 4.
$
#+end_src

파일 끝을 의미하는 기호 주소(~$~)를 사용할 수 있다.

#+begin_src bash
$ sed '3,$d' data6.txt
This is line number 1.
This is line number 2.
$
#+end_src

sed의 패턴 매칭(filtering)도 삭제 명령에 적용된다.

#+begin_src bash
$ sed '/number 1/d' data6.txt
This is line number 2.
This is line number 3.
This is line number 4.
$
#+end_src

sed는 검색 문자열과 일치한 텍스트를 포함한 줄만 제거한다.

#+begin_quote
"sed는 *절대!* 원본 파일을 수정하지 않는다!! 삭제한 줄은 단지 출력에서 사라진 것이며 원본 파일에는 여전히 삭제한 줄이 그대로 남아 있다."
#+end_quote

검색 문자열 두 개로 패턴 범위도 삭제할 수 있지만 *주의할 필요* 가 있다. 첫 번째 검색 문자열은 삭제 기능을 "*켜고*" 두 번째 검색 문자열은 삭제 기능을 "*끄는*" 역할을 처리한다!!

sed는 두 검색 패턴 사이의 모든 줄(지정한 줄까지 포함)을 삭제한다.

#+begin_src bash
$ sed '/1/,/3/d' data6.txt
This is line number 4.
$
#+end_src

이처럼 sed는 데이터 스트림에서 첫 번째 검색 패턴을 감지할 때마다 삭제 기능이 "*켜진다!!*" 는 것이다. 이는 전혀 예상치 못한 결과를 초래할 수도 있다.

#+begin_src bash
$ cat data7.txt
This is line number 1.
This is line number 2.
This is line number 3.
This is line number 4.
This is line number 1 again.
This is text you want to keep.
This is the last line in the file.
$
$ sed '/1/,/3/d' data7.txt
This is line number 4.
$
#+end_src

첫 번째 검색 패턴인 숫자 ~1~ 이 포함된 줄이 두 번 나타나면서 삭제 명령이 다시 실행되고 중지 패턴은 인식되지 않으므로 데이터 스트림의 나머지 줄까지 모두 삭제한다!!

또다른 문제는 *중지 패턴이 전혀 나타나지 않을 경우* 도 발생한다.

#+begin_src bash
$ sed '/1/,/5/d' data7.txt
$
#+end_src

삭제 명령은 첫 번째 패턴(~1~)과 일치해서 "켜졌지만" 두 번째 패턴(~5~)과 일치하지 않으므로 전체 데이터 스트림을 삭제한다!!


** Inserting and appending text
<<inserting-and-appending-text>>
예상할 수 있듯이 다른 편집기와 마찬가지로 sed 편집기도 텍스트 스트림에 *줄을 삽입하거나 추가* 할 수 있다. 하지만, 이 두 명령은 약간 혼란스럽다:

- insert 명령(~i~)은 *주소 앞 줄* 에 새로운 줄을 *삽입* 한다. 
- append 명령(~a~)은 *주소 뒷 줄* 에 새로운 줄을 *추가* 한다.

이 두 명령이 혼란스러운 점은 바로 이런 사용 형식이다. 또한, 여러 줄의 텍스트를 삽입할 경우 각각 별도의 줄로 지정하고 마지막 줄을 제외한 모든 줄 끝에는 ~\~ 문자로 줄바꿈한다!!  

사용 형식은 다음과 같다:

#+begin_src bash
sed '[address]command\
new line'
#+end_src

새로 추가될 줄은 사용한 명령에 따라 다른 줄에 나타난다. insert 명령의 경우 새로운 줄은 *앞 줄에 나타난다* 는 점을 기억한다.

#+begin_src bash
$ echo "Test Line 2" | sed 'i\Test Line 1'
Test Line 1
Test Line 2
$
#+end_src

그리고 append 명령의 경우 새로운 줄은 *뒷 줄에 나타난다.*

#+begin_src bash
$ echo "Test Line 2" | sed 'a\Test Line 1'
Test Line 2
Test Line 1
$
#+end_src

시스템 쉘에서 작은 따옴표와 슬래시 문자를 입력한 후 엔터키를 누르면 새로운 줄을 입력하기 위한 *보조 프롬프트가 표시* 된다. 이 줄에 나머지 sed 명령을 입력해서 완료한다. 명령을 종료하는 작은따옴표(~'~) 문자를 입력하면 쉘은 해당 명령을 실행한다.

#+begin_src bash
$ echo "Test Line 2" | sed 'i\
> Test Line 1'
Test Line 1
Test Line 2
$
#+end_src

단일 줄 앞이나 뒤에 텍스트를 추가하는 것은 잘 작동했지만 여러 줄이나 중간 줄에 텍스트를 추가하려면 어떻게 해야할까? 줄 중간에 텍스트를 삽입하거나 추가하려면 추가할 위치를 *주소 지정* 으로 알려줘야 한다. 하지만, 이 두 명령은 *단일 주소만 지정할 수 있다!!*

따라서, 단일 줄 번호나 검색 문자열은 사용할 수 있지만 *범위 주소는 사용할 수 없다!!* 하지만, 이것은 아주 논리적인 제한이다. 줄 삽입이나 추가 작업은 특정 줄 앞이나 뒤에서 사용할 것이고 줄 범위로 적용할 필요는 없기 때문이다.

다음은 데이터 스트림 3번 줄 *앞에* 새로운 줄을 삽입하는 예이다:

#+begin_src bash
$ sed '3i\
> This is an inserted line.' data6.txt
This is line number 1.
This is line number 2.
This is an inserted line.
This is line number 3.
This is line number 4.
$
#+end_src

다음은 데이터 스트림 3번 줄 *뒤에* 새로운 줄을 추가하는 예이다:

#+begin_src bash
$ sed '3a\
> This is an appended line.' data6.txt
This is line number 1.
This is line number 2.
This is line number 3.
This is an appended line.
This is line number 4.
$
#+end_src

insert 명령과 동일하지만 새로운 줄은 지정한 줄 번호 뒤에 추가된다.

만약, 데이터 스트림이 여러 줄로 구성되어 있고 줄 끝에 추가하려면 달러 주소 기호(~$~)를 사용한다. 이 기호는 파일의 마지막 줄을 의미한다.

#+begin_src bash
$ sed '$a\
> This is a new line of text.' data6.txt
This is line number 1.
This is line number 2.
This is line number 3.
This is line number 4.
This is a new line of text.
$
#+end_src

동일한 원리로 파일의 첫 줄에 추가할 때는 단순히 *1번 줄 앞에 새로운 줄을 삽입* 하면 된다.

만약, 한 줄 이상의 여러 줄을 삽입하거나 추가하려면 여러 줄로 구성된 줄 끝에 역슬래시(~\~)] 문자를 *반드시* 추가해야 한다. 연속된 줄은 역슬래시 문자를 계속 붙여야 하며 *마지막 줄에는 붙이지 않는다.* 

sed는 여러 줄로 구성된 텍스트를 하나의 삽입 또는 추가 명령으로 처리할 수 있다.

#+begin_src bash
$ sed '1i\
> This is one line of new text.\
> This is another line of new text.' data6.txt
This is one line of new text.
This is another line of new text.
This is line number 1.
This is line number 2.
This is line number 3.
This is line number 4.
$
#+end_src

예제는 두 줄의 텍스트를 데이터 스트림 1 번 앞 줄에 추가한다.


** Changing lines
<<changing-lines>>
change 명령으로 데이터 스트림의 줄 내용을 변경할 수 있다. 이 명령은 insert 및 append 명령과 동일한 형식으로 사용한다.

#+begin_src bash
$ sed '3c\
> This is a changed line of text.' data6.txt
This is line number 1.
This is line number 2.
This is a changed line of text.
This is line number 4.
$
#+end_src

예제는 3번 줄의 텍스트를 변경했다. 주소 대신 검색 문자열(패턴)을 사용할 수 있다.

#+begin_src bash
$ sed '/number 3/c\
> This is a changed line of text.' data6.txt
This is line number 1.
This is line number 2.
This is a changed line of text.
This is line number 4.
$
#+end_src

검색 문자열을 사용한 change 명령은 데이터 스트림에서 일치한 *모든 텍스트 줄을 변경!!* 한다.

#+begin_src bash
$ cat data8.txt
This is line number 1.
This is line number 2.
This is line number 3.
This is line number 4.
This is line number 1 again.
This is yet another line.
This is the last line in the file.
$
$ sed '/number 1/c\
> This is a changed line of text.' data8.txt
This is a changed line of text.
This is line number 2.
This is line number 3.
This is line number 4.
This is a changed line of text.
This is yet another line.
This is the last line in the file.
$
#+end_src

change 명령은 주소 범위로 사용할 수 있지만 처리 결과는 예상과 다를 수 있다.

#+begin_src bash
$ sed '2,3c\
> This is a new line of text.' data6.txt
This is line number 1.
This is a new line of text.
This is line number 4.
$
#+end_src

두 줄을 각각 변경하는 대신 두 줄 모두 새로운 줄로 대체한다.


** Transforming characters
<<transforming-characters>>
transform 명령(~y~)은 sed 명령 중에서 줄 단위가 아닌 *단일 문자에 적용되는 유일한 명령* 이다!!

transform 명령은 다음과 같은 형식으로 사용한다:

#+begin_src 
[address]y/inchars/outchars/
#+end_src

transform 명령은 inchars 와 outchars 의 *일대일 매핑 작업을 수행* 한다.

- inchars의 첫 번째 문자는 outchars의 첫 번째 문자로 변환된다. 
- inchars의 두 번째 문자는 outchars의 두 번째 문자로 변환된다. 

이런 매핑은 문자 길이만큼 계속된다. 만약, inchars와 outchars의 길이가 같지 않으면 sed는 *오류 메시지를 출력* 한다.

다음은 transform 명령을 사용한 간단한 예이다:

#+begin_src bash
$ sed 'y/123/789/' data8.txt
This is line number 7.
This is line number 8.
This is line number 9.
This is line number 4.
This is line number 7 again.
This is yet another line.
This is the last line in the file.
$
#+end_src

출력 결과로 알 수 있듯이 inchars에 지정한 각 문자는 동일한 위치의 outchars 문자로 대체된다. 또한, transform 명령은 *전역 명령* 이다. 즉, 줄에서 발견된 *모든 문자를 변환* 하며 등장 횟수에 관계없이 모두 적용된다.

#+begin_src bash
$ echo "This 1 is a test of 1 try." | sed 'y/123/456/'
This 4 is a test of 4 try.
$
#+end_src

sed는 줄에서 일치한 숫자 ~1~ 의 모든 인스턴스를 변환한다. 

#+begin_quote
"하지만, 변환 작업을 특정 문자로 제한할 수 없다!"
#+end_quote


** Printing revisited
<<printing-revisited>>
이전 장에서 대체 명령으로 변경한 줄만 표시하기 위해 대체 명령에 ~p~ 플래그를 사용하는 방법을 보여줬다. 이 외에도 데이터 스트림에서 특정 정보를 출력할 수 있는 세 가지 출력 명령이 있다:

| 명령 | 설명             |
|------+------------------|
| ~p~  | 줄 내용 출력     |
| ~=~  | 줄 번호 출력     |
| ~l~  | 보다 자세히 출력 |

다음 섹션에서 sed의 세 가지 출력 명령에 대해 살펴본다.


*** Printing lines
<<printing-lines>>
대체 명령의 ~p~ 플래그처럼 ~p~ 명령도 줄을 출력한다. 하지만, 단독 사용할 경우 그다지 흥미로운 기능을 제공하지 않는다.

#+begin_src bash
$ echo "this is a test" | sed 'p'
this is a test
this is a test
$
#+end_src

이 명령이 처리하는 일은 이미 존재하는 텍스트를 *중복 출력* 하는 것 뿐이다. (기본 출력 + p 명령 출력)

print 명령의 일반적인 사용 용도는 *검색 문자열을 포함한 줄만 출력* 하는 것이다.

#+begin_src bash
$ cat data6.txt
This is line number 1.
This is line number 2.
This is line number 3.
This is line number 4.
$
$ sed -n '/number 3/p' data6.txt
This is line number 3.
$
#+end_src

이 경우 명령줄에 ~-n~ 옵션을 함께 사용해서 *다른 줄의 기본 출력을 억제하고 검색 문자열을 포함한 줄만 출력* 한다.

다음과 같은 명령으로 데이터 스트림에서 특정 줄만 빠르게 출력하는 필터링 용도로 사용할 수 있다.

#+begin_src bash
$ sed -n '2,3p' data6.txt
This is line number 2.
This is line number 3.
$
#+end_src

또한, 대체 명령으로 특정 줄을 변경할 때 처리 결과 확인용으로 print 명령을 사용할 수 있다. 다음과 같이 변경하기 이전의 줄을 출력하는 스크립트를 작성할 수 있다.

#+begin_src bash
$ sed -n '/3/{
> p
> s/line/test/p
> }' data6.txt
This is line number 3.
This is test number 3.
$
#+end_src

위의 명령은 우선 숫자 3을 포함한 줄을 검색하고 두 개의 그룹 명령을 실행한다. ~p~ 명령으로 변경 직전 원본 줄을 출력한다. 그 다음 ~s~ 대체 명령으로 텍스트를 대체하고 ~p~ 플래그로 변경한 텍스트를 출력한다. 따라서, 출력 결과는 원본 줄과 새로 변경한 줄 모두 출력된다.


*** Printing line numbers
<<printing-line-numbers>>
등호(~=~) 명령은 *줄 번호를 출력* 한다. 줄 번호는 줄바꿈 문자(newline character) 기준으로 결정된다. 데이터 스트림에 줄바꿈 문자가 나타날 때마다 *줄의 끝으로 간주* 한다.

#+begin_src bash
$ cat data1.txt
The quick brown fox jumps over the lazy dog.
The quick brown fox jumps over the lazy dog.
The quick brown fox jumps over the lazy dog.
The quick brown fox jumps over the lazy dog.
$
$ sed '=' data1.txt
1
The quick brown fox jumps over the lazy dog.
2
The quick brown fox jumps over the lazy dog.
3
The quick brown fox jumps over the lazy dog.
4
The quick brown fox jumps over the lazy dog.
$
#+end_src

기본적으로 앞 라인에 줄 번호를 *별도로 출력* 한다. 등호(~=~) 명령은 검색 문자열을 검색할 때 유용하다.

#+begin_src bash
$ sed -n '/number 4/{
> =
> p
> }' data6.txt
4
This is line number 4.
$
#+end_src

~-n~ 옵션을 사용하면 검색 문자열을 포함한 줄 번호와 텍스트만 필터링해서 출력할 수 있다.


** Listing lines
<<listing-lines>>
list 명령(~l~)은 기본적으로 *출력되지 않는(non-printable) 문자를 출력* 한다.

이처럼 출력되지 않는 문자는 역슬래시 문자로 시작하는 8진수 값이나 탭 문자 같은 비-출력 문자는 C언어 스타일 표기법(~\t~ 등)으로 출력한다.

#+begin_src bash
$ cat data9.txt
This      line     contains    tabs.
$
$ sed -n 'l' data9.txt
This\tline\tcontains\ttabs.$
$
#+end_src

탭 문자는 ~\t~ 표기법으로 출력된다. 여기서 *달러 기호는 줄바꿈 문자를 의미* 한다.

데이터 스트림에 제어 문자가 포함될 경우 list 명령은 해당 문자를 16진수 코드로 출력한다.

#+begin_src bash
$ cat data10.txt
This line contains an escape character.
$
$ sed -n 'l' data10.txt
This line contains an escape character. \a$
$
#+end_src

data10.txt 파일은 벨소리를 발생시키는 16진수 제어 코드(~\a~)가 마지막에 포함되어 있다. ~cat~ 명령으로 텍스트 파일을 출력하면 이런 제어 코드는 화면에 보이지 않고(스피커가 켜져있다면) 소리만 들린다. 그러나, list 명령으로 제어 코드를 화면에 출력할 수 있다.


** Using files with sed
<<using-files-with-sed>>
대체 명령엔 파일을 처리할 수 있는 ~w~ 플래그가 포함되어 있다. 하지만, 대체 명령으로 텍스트를 변경하지 않고 파일을 처리할 수 있는 명령이 있다.


*** Writing to a file
<<writing-to-a-file>>
~w~ 명령은 파일에 출력 결과를 쓰기(write)위해 사용한다. ~w~ 명령의 사용 형식은 다음과 같다:

#+begin_src 
[address]w filename
#+end_src

filename 은 상대 경로 또는 절대 경로로 지정할 수 있지만 어떤 경우든 해당 파일에 대한 *쓰기 권한* 을 가지고 있어야 한다. 여기서 사용한 주소는 모든 주소 지정 방식---단일 줄이나 검색 문자열, 줄 범위나 검색 문자열 범위---를 사용할 수 있다.

다음 예제는 데이터 스트림의 처음 두 줄만 test.txt 파일에 저장하는 예이다:

#+begin_src bash
$ sed '1,2w test.txt' data6.txt
This is line number 1.
This is line number 2.
This is line number 3.
This is line number 4.
$
$ cat test.txt
This is line number 1.
This is line number 2.
$
#+end_src

파일 내용을 표준 출력(STDOUT)에 출력하지 않으려면 ~-n~ 옵션을 사용한다.

이 명령은 메일링 리스트 같은 공통 텍스트를 마스터 파일에서 특정 파일로 추출할 때 유용하다.

#+begin_src bash
$ cat data11.txt
Blum, R Browncoat
McGuiness, A Alliance
Bresnahan, C Browncoat
Harken, C Alliance
$
$ sed -n '/Browncoat/w Browncoats.txt' data11.txt
$
$ cat Browncoats.txt
Blum, R Browncoat
Bresnahan, C Browncoat
$
#+end_src

sed는 검색 문자열을 포함한 줄만 대상 파일에 기록한다.


*** Reading data from a file
<<reading-data-from-a-file>>
쉘에서 데이터 스트림에 데이터를 삽입하거나 텍스트를 추가하는 명령을 살펴봤다. read 명령(~r~)은 외부 파일의 데이터를 읽어온 후 현재 파일에 삽입한다. 

다음은 read 명령의 사용 형식이다:

#+begin_src 
[address]r filename
#+end_src

filename 매개 변수는 데이터를 포함한 외부 파일의 절대 경로 또는 상대 경로를 지정한다.

주의할 점은 read 명령은 *주소 범위를 사용할 수 없다!!* 따라서, 단일 줄 번호나 검색 문자열만 지정할 수 있다. 다음은 3번 줄 다음에 외부 파일의 텍스트를 읽어와서 삽입한다.

#+begin_src bash
$ cat data12.txt
This is an added line.
This is the second added line.
$
$ sed '3r data12.txt' data6.txt
This is line number 1.
This is line number 2.
This is line number 3.
This is an added line.
This is the second added line.
This is line number 4.
$
#+end_src

외부 파일의 모든 줄을 읽은 후 데이터 스트림에 삽입한다. 

동일한 방법으로 검색 문자열 주소를 사용할 때도 그대로 작동한다.

#+begin_src bash
$ sed '/number 2/r data12.txt' data6.txt
This is line number 1.
This is line number 2.
This is an added line.
This is the second added line.
This is line number 3.
This is line number 4.
$
#+end_src

파일을 읽어와서 끝 줄에 추가하려면 달러 기호 주소 기호(~$~)를 사용한다.

#+begin_src bash
$ sed '$r data12.txt' data6.txt
This is line number 1.
This is line number 2.
This is line number 3.
This is line number 4.
This is an added line.
This is the second added line.
$
#+end_src

read 명령의 활용 방법 중 하나는 delete 명령으로 자리표시자(place-holder)를 외부 파일 데이터로 교체하는 것이다. 예를 들어, 다음과 같은 파일을 가정한다:

#+begin_src bash
$ cat notice.std
Would the following people:
LIST
please report to the ship's captain.
$
#+end_src

사람 이름이 들어갈 자리에 자리표시자 LIST 를 사용한다. 자리표시자 다음에 사람 이름 목록을 파일에서 읽어와서 삽입하려면 read 명령을 사용한다. 하지만, 출력 결과에 자리표시자 문자열이 그대로 남는다. 이를 제거하기 위해 delete 명령을 사용한다. 처리 결과는 다음과 같다:

#+begin_src bash
$ sed '/LIST/{
> r data11.txt
> d
> }' notice.std
Would the following people:
Blum, R Browncoat
McGuiness, A Alliance
Bresnahan, C Browncoat
Harken, C Alliance
please report to the ship's captain.
$
#+end_src

자리표시자는 외부 파일 이름 목록으로 교체되고 자리표시자 문자열은 제거된다.
